### ISSUE TITLE
MySQL does not load cleanly due to new roles constraint

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10089]
We have an error on startup in mysql due to this change: #9793

```
INFO  2016-11-08 12:30:50,821 com.dotmarketing.common.db.DotConnect:info(58): Executing create index dist_reindex_index  using btree on dist_reindex_journal (serverid,dist_action)
INFO  2016-11-08 12:30:50,823 com.dotmarketing.common.db.DotConnect:info(58): Finished Executing create index dist_reindex_index  using btree on dist_reindex_journal (serverid,dist_action)
INFO  2016-11-08 12:30:50,823 com.dotmarketing.common.db.DotConnect:info(58): Executing create index dist_reindex_index5 using btree on dist_reindex_journal (priority, time_entered)
INFO  2016-11-08 12:30:50,825 com.dotmarketing.common.db.DotConnect:info(58): Finished Executing create index dist_reindex_index5 using btree on dist_reindex_journal (priority, time_entered)
INFO  2016-11-08 12:30:50,825 com.dotmarketing.common.db.DotConnect:info(58): Executing create index dist_reindex_index6 using btree on dist_reindex_journal (priority)
INFO  2016-11-08 12:30:50,827 com.dotmarketing.common.db.DotConnect:info(58): Finished Executing create index dist_reindex_index6 using btree on dist_reindex_journal (priority)
INFO  2016-11-08 12:30:50,827 com.dotmarketing.common.db.DotConnect:info(58): Executing create table `quartz_log` (`id` bigint  not null auto_increment,`job_name` varchar(255)  not null,`serverid` varchar(64) ,`time_started` datetime  not null, primary key (`id`))
INFO  2016-11-08 12:30:50,846 com.dotmarketing.common.db.DotConnect:info(58): Finished Executing create table `quartz_log` (`id` bigint  not null auto_increment,`job_name` varchar(255)  not null,`serverid` varchar(64) ,`time_started` datetime  not null, primary key (`id`))
INFO  2016-11-08 12:30:50,846 com.dotmarketing.common.db.DotConnect:info(58): Executing alter table cms_role add unique (role_key)
INFO  2016-11-08 12:30:50,848 com.dotmarketing.common.db.DotConnect:info(58): Finished Executing alter table cms_role add unique (role_key)
INFO  2016-11-08 12:30:50,848 com.dotmarketing.common.db.DotConnect:info(58): Executing alter table cms_role add constraint cms_role_name_db_fqn unique (db_fqn(1000))
FATAL 2016-11-08 12:30:50,849 com.dotmarketing.startup.runalways.Task00001LoadSchema:fatal(156): Error: Specified key was too long; max key length is 767 byteswhile trying to execute alter table cms_role add constraint cms_role_name_db_fqn unique (db_fqn(1000)) proccessed 289 statements
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_101]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_101]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.37-bin.jar:5.1.37]
	at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[mysql-connector-java-5.1.37-bin.jar:5.1.37]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941) ~[mysql-connector-java-5.1.37-bin.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870) ~[mysql-connector-java-5.1.37-bin.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806) ~[mysql-connector-java-5.1.37-bin.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470) ~[mysql-connector-java-5.1.37-bin.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617) ~[mysql-connector-java-5.1.37-bin.jar:5.1.37]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2546) ~[mysql-connector-java-5.1.37-bin.jar:5.1.37]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2504) ~[mysql-connector-java-5.1.37-bin.jar:5.1.37]
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:840) ~[mysql-connector-java-5.1.37-bin.jar:5.1.37]
```

## Expected Behavior
This should load cleanly

**Comment by jgambarios** [comment]
Related to https://github.com/dotCMS/core/issues/10074 ?

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10090

**Comment by shaydotcms** [comment]
Passed QA, no errors related to key length.
Tested in latest master-3.7 // Mac OS 10.10 // MySQL 5.6.23 // Firefox v45.0.1
