### ISSUE TITLE
WebResourceTest failing after changes in 10134

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#10191]
The **WebResourceTest** test started to fail after the changes in: https://github.com/dotCMS/core/issues/10134

Look at: https://cb.dotcms.com/job/Git_Master_Int_Funct_Test_Runner_3.7_Postgres/44/testReport/com.dotcms.rest/WebResourceTest/testUserWithoutPermissionOnPortlet/

```
Caused by: java.lang.NullPointerException
	at com.dotcms.rest.WebResource.getUser(WebResource.java:180)
	at com.dotcms.rest.WebResource.init(WebResource.java:145)
	at com.dotcms.rest.WebResourceTest.testUserWithoutPermissionOnPortlet(WebResourceTest.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 81 more
```

**Comment by jgambarios** [comment]
There are more tests failing and looks like it is related to the same change:

https://cb.dotcms.com/view/master-3.7/job/Git_Master_Int_Funct_Test_Runner_3.7_Postgres/lastCompletedBuild/testReport/
- WebResourceTest.testUserWithoutPermissionOnPortlet
- WebResourceTest.testUserWithPermissionOnPortlet

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/10215

**Comment by jgambarios** [comment]
**QA:** Please re-test https://github.com/dotCMS/core/issues/10134

**Comment by bryanboza** [comment]
After retest the #10134 works as expected
