### ISSUE TITLE
RuleEngine Throws Error if response is committed

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10247]
If you have a rule that commits the HttpServlet.response, for example sending a 401 or a redirect, the system should stop processing rules after that and just send the response.  Currently, it continues processing and this throws an error in the log:

```
[02/12/16 09:05:36:423 EST] ERROR business.RulesEngine: Unable process rules: Cannot create a session after the response has been committed
java.lang.IllegalStateException: Cannot create a session after the response has been committed
	at org.apache.catalina.connector.Request.doGetSession(Request.java:2872) ~[catalina.jar:8.0.18]
	at org.apache.catalina.connector.Request.getSession(Request.java:2249) ~[catalina.jar:8.0.18]
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:895) ~[catalina.jar:8.0.18]
	at com.dotmarketing.portlets.rules.business.RulesEngine.trackFiredRule(RulesEngine.java:162) ~[dotcms_3.6.0_3876030.jar:?]
	at com.dotmarketing.portlets.rules.business.RulesEngine.fireRules(RulesEngine.java:130) [dotcms_3.6.0_3876030.jar:?]
	at com.dotmarketing.portlets.rules.business.RulesEngine.fireRules(RulesEngine.java:65) [dotcms_3.6.0_3876030.jar:?]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:251) [dotcms_3.6.0_3876030.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61) [dotcms_3.6.0_3876030.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.
```

**Comment by dsilvam** [comment]
@wezell good candidate for integration or functional test?

**Comment by wezell** [comment]
Dunno.  We have the same checking code sprinkled around the system, e.g.

https://github.com/dotCMS/core/blob/master-3.7/dotCMS/src/main/java/com/dotmarketing/filters/CMSFilter.java#L213
https://github.com/dotCMS/core/blob/master-3.7/dotCMS/src/main/java/com/dotmarketing/filters/CMSFilter.java#L249
https://github.com/dotCMS/core/blob/master-3.7/dotCMS/src/main/java/com/dotmarketing/velocity/VelocityServlet.java#L463
https://github.com/dotCMS/core/blob/master-3.7/dotCMS/src/main/java/com/dotmarketing/velocity/VelocityServlet.java#L472
https://github.com/dotCMS/core/blob/master-3.7/dotCMS/src/main/java/com/dotmarketing/velocity/VelocityServlet.java#L481

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/10248

**Comment by dsilvam** [comment]
This is my thinking, maybe I am wrong. If we are planning to manual-QA this one, why not create an automated test instead? taking advantage of the functional tests.  The other choice is not to QA and move it straight to Done. I was discussing with @jgambarios and he thinks so as well.

**Comment by erickgonzalez** [comment]
Not able to reproduce it. Talked to @wezell and follow the steps he gave but still no luck.
