### ISSUE TITLE
Unable to neither View nor Add Content Type Relationships

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#10251]
## Expected Behavior

- [ ] Viewing Content Type Relationships should be successful.

- [ ] Adding Content Type Relationships should be successful.

## Current Behavior
When you try to view Content Type Relationships an error is thrown.

> ERROR util.SQLUtil: Invalid or pernicious sql parameter passed in : relation_type_value
com.dotmarketing.business.DotStateException: Invalid or pernicious sql parameter passed in : relation_type_value
	at com.dotmarketing.common.util.SQLUtil.sanitizeSortBy(SQLUtil.java:209) [dotcms_3.8.0_0873b8c.jar:?]
	at com.dotcms.contenttype.business.RelationshipFactoryImpl.byContentType(RelationshipFactoryImpl.java:203) [dotcms_3.8.0_0873b8c.jar:?]
	at com.dotmarketing.portlets.structure.action.ViewRelationshipsAction._loadRelationships(ViewRelationshipsAction.java:50) [dotcms_3.8.0_0873b8c.jar:?]
	at com.dotmarketing.portlets.structure.action.ViewRelationshipsAction.render(ViewRelationshipsAction.java:34) [dotcms_3.8.0_0873b8c.jar:?]

When adding a new relationship this is the error:
https://gist.github.com/dsilvam/d40884113f37a9e4968fa86ca60864c3

## Steps to Reproduce (for bugs)
View Relationships
1. Go To the Content Types Portlet
2. Click over the View Content Type Relationships

Add Relationships
1. Go To the Content Types Portlet
2. Click over the View Content Type Relationships
3. Click on "Add New Relationship"

## Your Environment
* dotCMS version used: master-3.8
* Browser Name and version: FF and Chrome
* Operating System and version: Mac OS
* Database and version: MySQL and Postgres

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/10253

**Comment by shaydotcms** [comment]
Passed QA.
No errors are showing when viewing or adding content type relationships.
Tested on latest master-3.8 / Postgres and MySQL
