### ISSUE TITLE
java.sql.SQLException executing ContentTypeAPIImplTest in MSSQL

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#10331]
The **ContentTypeAPIImplTest** is failing on **MSSQL**. 

https://cb.dotcms.com/job/Git_Master_Int_Funct_Test_Runner_3.8_MSSQL/27/testReport/com.dotcms.contenttype.test/ContentTypeAPIImplTest/testAddingUpdatingDeleteing/

```
Caused by: java.sql.SQLException: Snapshot isolation transaction aborted due to update conflict. You cannot use snapshot isolation to access table 'dbo.QRTZ_EXCL_LOCKS' directly or indirectly in database 'dotcms' to update, delete, or insert the row that has been modified or deleted by another transaction. Retry the transaction or change the isolation level for the update/delete statement.
	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:368) ~[jtds-1.2.2.jar:1.2.2]
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2816) ~[jtds-1.2.2.jar:1.2.2]
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2254) ~[jtds-1.2.2.jar:1.2.2]
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:631) ~[jtds-1.2.2.jar:1.2.2]
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:584) ~[jtds-1.2.2.jar:1.2.2]
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:546) ~[jtds-1.2.2.jar:1.2.2]
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.executeUpdate(JtdsPreparedStatement.java:505) ~[jtds-1.2.2.jar:1.2.2]
	at com.dotcms.repackage.org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[dot.commons-dbcp-1.3_2.jar:1.3]
	at com.dotcms.repackage.org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[dot.commons-dbcp-1.3_2.jar:1.3]
	at org.quartz.impl.jdbcjobstore.UpdateLockRowSemaphore.executeSQL(UpdateLockRowSemaphore.java:86) ~[dot.quartz-all-1.8.6_2.jar:?]
	... 54 more
```

**Comment by agomez-dotcms** [comment]
Hey Guys, here are some additional resources after troubleshooting/investigation related to this issue:

1. http://web.archive.org/web/20090713052112/http://jira.opensymphony.com/browse/QUARTZ-497
2. http://web.archive.org/web/20070827011117/http://forums.opensymphony.com/thread.jspa?forumID=6&threadID=39696
3. http://quartz.10975.n7.nabble.com/MS-SQL-Server-Clustering-possible-solution-quartz-1-5-2-td4859.html
4. https://msdn.microsoft.com/en-us/library/ms187373.aspx
5. http://osdir.com/ml/java.quartz.user/2008-03/msg00092.html

Thanks,
Anibal

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10334

**Comment by bryanboza** [comment]
Fixed, tested on master-3.7
