### ISSUE TITLE
Content Type: Hibernate Exception when a Site/Folder field is deleted

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#10426]
## Expected Behavior
Once a Site/Folder field is deleted, the Content Type is updated as well and a new Mod Date is set, along with a cleanup of the URL Map Master Pattern in cache.

## Current Behavior
The field is deleted without issues, but updating the Content Type returns a Hibernate Exception. 

```
[11/01/17 09:35:03:779 EST] INFO job.DeleteFieldJob: triggerJobImmediately : Deleting Field 'siteOrFolder' for Structure with id: 62756e7f-54ba-48b8-93df-f081c8483a53
[11/01/17 09:35:03:799 EST] INFO h22.H22Cache: Flushing H22 cache group:contentletcache | Note: this can be an expensive operation
[11/01/17 09:35:03:955 EST] INFO guava.GuavaCache: ***	Building Cache : translatedquerycache, size:5000,Concurrency:32
[11/01/17 09:35:03:961 EST] ERROR db.HibernateUtil: ---------- DotHibernate: error on rollbackTransaction ---------------
org.postgresql.util.PSQLException: Cannot rollback when autoCommit is enabled.
[11/01/17 09:35:03:961 EST] ERROR job.DeleteFieldJob: Unable to delete field 'siteOrFolder'. Field Inode: 9d19ba02-6657-463a-8126-913a5f63659e, Structure Inode: 62756e7f-54ba-48b8-93df-f081c8483a53
com.dotmarketing.exception.DotHibernateException: Unable to save/update Object to Hibernate Session 
at com.dotmarketing.db.HibernateUtil.saveOrUpdate(HibernateUtil.java:485) ~[dotcms_3.6.1_cfa5586.jar:?]
at com.dotmarketing.portlets.structure.factories.StructureFactory.saveStructure(StructureFactory.java:551) ~[dotcms_3.6.1_cfa5586.jar:?]
at com.dotmarketing.quartz.job.DeleteFieldJob.execute(DeleteFieldJob.java:139) [dotcms_3.6.1_cfa5586.jar:?]
at org.quartz.core.JobRunShell.run(JobRunShell.java:223) [dot.quartz-all-1.8.6_2.jar:?]
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) [dot.quartz-all-1.8.6_2.jar:?]
Caused by: com.dotcms.repackage.net.sf.hibernate.NonUniqueObjectException: a different object with the same identifier value was already associated with the session: 62756e7f-54ba-48b8-93df-f081c8483a53, of class: com.dotmarketing.portlets.structure.model.Structure
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.checkUniqueness(SessionImpl.java:1687) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.doUpdateMutable(SessionImpl.java:1453) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.doUpdate(SessionImpl.java:1480) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:1403) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotmarketing.db.HibernateUtil.saveOrUpdate(HibernateUtil.java:482) ~[dotcms_3.6.1_cfa5586.jar:?]
... 4 more
```

This is how the Notifications bar looks: It says the field was deleted, but then a false negative message is thrown about deleting the field. Again, there are no issues with deleting the field itself (after refreshing the page, the field is no longer listed).

<img width="424" alt="screen shot 2017-01-11 at 9 54 37 am" src="https://cloud.githubusercontent.com/assets/1717110/21853412/02fda7f8-d7e5-11e6-965a-1689a701e8b6.png">

## Possible Solution
The EditFieldAction.java field already sets a Hibernate Transaction for every single operation related to fields, so it should not be needed to set an additional one (or perhaps setting a local only transaction for this job).

## Known Workarounds
None.

## Steps to Reproduce (for bugs)

1. Create a Test Content Type on demo site.
2. Add two fields: Title (Text-type, required, user-searchable, listed) and Site or Folder.
3. Once both fields are created, delete the Site or Folder one.

Stacktrace from above is thrown.

## Context
Reported by customer: 	https://my.dotcms.com/tickets/detail.dot?id=08ba3cda-a078-43d7-9259-7606cef2b276
Reproduced on demo.dotcms.com site.

## Your Environment

* dotCMS version 3.6.1.
* Google Chrome, Firefox Browsers.
* Windows Server 2016, macOS Sierra, any Linux-flavored distro.
* Built-in Tomcat 8.0.18.
* Oracle Java 8.
* Postgres 9.3.5, SQL Server 2014.

**Comment by joseorsini** [comment]
Unable to reproduce on current 4.1. Closing.
