### ISSUE TITLE
Clustering: Node cannot be added to cluster if hostname > 36 chars.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#10466]
Depending on the OS where the dotCMS application is running, there is a char limitation on the hostname set at OS level. Despite that on Unix environments we're allowed to have hostnames with a max length of 255 bytes, and on Windows we're limited to 15 characters only, we restrict the host names on cluster_server table to 36 characters only. 

Database definition on 3.6.1 release, for Postgres DBs:

```
dotcms361=# \d cluster_server;
               Table "public.cluster_server"
        Column         |          Type          | Modifiers
-----------------------+------------------------+-----------
 server_id             | character varying(36)  | not null
 cluster_id            | character varying(36)  | not null
 name                  | character varying(100) |
 ip_address            | character varying(39)  | not null
 host                  | character varying(36)  |
 cache_port            | smallint               |
 es_transport_tcp_port | smallint               |
 es_network_port       | smallint               |
 es_http_port          | smallint               |
 key_                  | character varying(100) |
Indexes:
    "cluster_server_pkey" PRIMARY KEY, btree (server_id)
Foreign-key constraints:
    "fk_cluster_id" FOREIGN KEY (cluster_id) REFERENCES dot_cluster(cluster_id)
Referenced by:
    TABLE "cluster_server_uptime" CONSTRAINT "cluster_server_uptime_server_id_fkey" FOREIGN KEY (server_id) REFERENCES cluster_server(server_id)
    TABLE "cluster_server_uptime" CONSTRAINT "fk_cluster_server_id" FOREIGN KEY (server_id) REFERENCES cluster_server(server_id)
``` 

## Expected Behavior
We should be able to have enough room for storing the hostname on this table, regardless of the OS where the application is running.

## Current Behavior
A node cannot be added to the cluster because of the hostname length

Stacktrace: 
```
[04/01/17 16:27:50:379 EST] ERROR jgroups.JGroupsCacheTransport [[ACTIVE] ExecuteThread: '0' for queue: 'weblogic.kernel.Default (self-tuning)'] : Error initializing jgroups channel: ORA-12899: value too large for column "DOTCMS3"."CLUSTER_SERVER"."HOST" (actual: 39, maximum: 36)

com.dotmarketing.exception.DotDataException: ORA-12899: value too large for column "DOTCMS3"."CLUSTER_SERVER"."HOST" (actual: 39, maximum: 36)

        at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:233) ~[DotConnect.class:?]
        at com.dotcms.enterprise.cluster.ServerFactoryImpl.updateServer(SourceFile:232) ~[ee-933f706.jar:?]
        at com.dotcms.cluster.business.ServerAPIImpl.updateServer(ServerAPIImpl.java:132) ~[dotcms_3.3.2_fb28b98f.jar:?]
        at com.dotmarketing.business.jgroups.JGroupsCacheTransport.init(JGroupsCacheTransport.java:71) [dotcms_3.3.2_fb28b98f.jar:?]
        at com.dotmarketing.business.ChainableCacheAdministratorImpl.setCluster(ChainableCacheAdministratorImpl.java:208) [dotcms_3.3.2_fb28b98f.jar:?]
        at com.dotcms.enterprise.cluster.ClusterFactory.a(SourceFile:319) [ee-933f706.jar:?]
        at com.dotcms.enterprise.cluster.ClusterFactory.addNodeToCluster(SourceFile:309) [ee-933f706.jar:?]
        at com.dotcms.enterprise.cluster.ClusterFactory.addNodeToCluster(SourceFile:198) [ee-933f706.jar:?]
        at com.dotcms.enterprise.cluster.ClusterFactory.initialize(SourceFile:112) [ee-933f706.jar:?]
        at com.dotmarketing.startup.runalways.Task00009ClusterInitialize.executeUpgrade(Task00009ClusterInitialize.java:45) [dotcms_3.3.2_fb28b98f.jar:?]

```

## Possible Solution
Update the table definition and increase the allowed characters in host and name columns.

## Known Workarounds
Manually alter the table, or edit the hostname to a shorter one.

## Steps to Reproduce (for bugs)

1. Update the hostname of your local machine. Hostname must have more than 36 characters.
2. Start your server.

## Context
Reported by customer running 3.3.1 and Oracle DB.
https://my.dotcms.com/tickets/detail.dot?id=d0c9debe-7085-4cef-a767-0ac6284e9a13

Reference of hostname limitation on Unix:
http://stackoverflow.com/questions/8724954/what-is-the-maximum-number-of-characters-for-a-host-name-in-unix

For Windows: 
https://support.microsoft.com/en-us/kb/909264

## Your Environment

* dotCMS versions 3.3.1 and 3.6.1.
* Unix-flavored OS.
* Tomcat 8.0.18, Weblogic 12c.
* Oracle JDK 8.
* Postgres 9.4.1, Oracle 11G.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/11792
