### ISSUE TITLE
Exception thrown when adding a field to a content type

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#10505]
This exception is thrown when I add a new field to a new content type:

~~~
[23/01/17 09:40:30:003 EST] ERROR util.ContentTypeUtil: null
java.lang.NullPointerException
	at com.dotmarketing.business.LayoutAPIImpl.loadLayoutsForUser(LayoutAPIImpl.java:77) ~[dotcms_4.1_90db46f.jar:?]
	at com.dotcms.util.ContentTypeUtil.getActionUrl(ContentTypeUtil.java:93) ~[dotcms_4.1_90db46f.jar:?]
	at com.dotcms.util.ContentTypeUtil.getActionUrl(ContentTypeUtil.java:84) ~[dotcms_4.1_90db46f.jar:?]
	at com.dotcms.util.ContentTypeUtil.getActionUrl(ContentTypeUtil.java:69) ~[dotcms_4.1_90db46f.jar:?]
	at com.dotmarketing.portlets.structure.factories.StructureFactory.lambda$pushSaveUpdateEvent$0(StructureFactory.java:434) ~[dotcms_4.1_90db46f.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]

~~~

**In spite of the error, the field has been added without any problem**

## Expected Behavior

A new field should be added to a Content Type without any exception in logs files.

## Current Behavior

The field is added without any problem, but an exception is thrown in _dotcms.log_

## Steps to Reproduce (for bugs)

1. Create a new Content Type
2. Add a new field
3. View details in _dotcms.log_

## Your Environment

* dotCMS version used: 4.1
* Browser Name and version: Google Chrome
* Operating System and version: Mac OS
* Application Server and version: Tomcat 8
* Java Brand and version: JDK 1.8
* Database and version: Postgres (Client DB). Shared on dotCMS' Google Drive: dotcms_postgres_ticket_10501_10502.sql.zip
* Application module (if apply): Content Types

**Comment by erickgonzalez** [comment]
Not able to reproduce with latest-4.1.

**Comment by shaydotcms** [comment]
Passed QA.
Tested on upgrade using 3.6 client db to latest master-4.1
Mac OS 10.10 / Postgres 9.3.5
