### ISSUE TITLE
Viewtools: FileTool does not respect DEFAULT_FILE_TO_DEFAULT_LANGUAGE property

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#10515]
The FileTool viewtool, which is called on the Velocity Context for every view mode (Edit, Preview, Live) sets some variables in context related to contents added to containers. For Image/Field files, images are pulled in the background according to the language in session, however, we're not verifying if DEFAULT_FILE_TO_DEFAULT_LANGUAGE property is enabled, so for an image stored with default language, all non-default pages will cause issues on the Velocity Context. 

## Expected Behavior
FileTool should ask if the DEFAULT_FILE_TO_DEFAULT_LANGUAGE property is set to true, in case:

- The image/file field is populated for a content.
- No occurrences of the file/image are found for the non-default language in session.
- Fall back to a pull using the default language.

## Current Behavior
- FileTool viewtool cannot pull an image stored with default language if the page has a non-default language.

## Known Workarounds
Create a version in other languages in the CMS for the same asset.

## Steps to Reproduce (for bugs)
1.  Create a new content type of type "Widget" with a Image/File field type.  You do not need to set any widget code or add any other fields.
2.  Create a new Contentlet with this content type in English, and select an English image for the file field (make sure it's not a multilingual file).
3.  Create a Spanish version of this content, simply accepting the English values for the Spanish version.
4.  Save and publish this multilingual content.
5.  Create a page and, in Edit mode, add this new Widget to the page.
6.  In Edit Mode, Access the page in English: there will be no exception in dotcms-velocity.log
7.  Switch the language to Spanish: you will see an exception in dotcms-velocity.log

```
[24/01/17 09:20:25:364 EST] ERROR viewtools.FileTool: Can't find contentlet: 55a20bb2-13ff-474c-b3b0-ee575768baca lang:2 live:false @ url:GET//demo.dotcms.com/test-001 | lang:2 | ip:0:0:0:0:0:0:0:1 | Admin:true | start:01-24-2017 09:19:00 EST  ref:http://localhost:8080/test-001?leftMenu=true&livePage=0&com.dotmarketing.htmlpage.language=1&language=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797  ?mainFrame=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797&com.dotmarketing.htmlpage.language=2&com.dotmarketing.persona.id=&previewPage=1 {working/7d674661-ed1b-4807-a481-fec72c8b617d_2.content}
com.dotmarketing.portlets.contentlet.business.DotContentletStateException: Can't find contentlet: 55a20bb2-13ff-474c-b3b0-ee575768baca lang:2 live:false
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.findContentletByIdentifier(ESContentletAPIImpl.java:279) ~[dotcms_3.6.1_cfa5586.jar:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.findContentletByIdentifier(ContentletAPIInterceptor.java:822) ~[dotcms_3.6.1_cfa5586.jar:?]
	at com.dotmarketing.viewtools.FileTool.getFile(FileTool.java:62) [dotcms_3.6.1_cfa5586.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:178) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:572) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTExpression.value(ASTExpression.java:71) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTSetDirective.render(ASTSetDirective.java:150) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:330) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.Template.merge(Template.java:362) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.Template.merge(Template.java:265) [dotcms_3.6.1_cfa5586.jar:?]
	at com.dotmarketing.viewtools.VelocityWebUtil.mergeTemplate(VelocityWebUtil.java:90) [dotcms_3.6.1_cfa5586.jar:?]
	at sun.reflect.GeneratedMethodAccessor284.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:178) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:374) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:218) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:308) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:226) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:211) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:218) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:308) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:226) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:211) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:423) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:211) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:330) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.Template.merge(Template.java:362) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.Template.merge(Template.java:265) [dotcms_3.6.1_cfa5586.jar:?]
	at com.dotmarketing.viewtools.VelocityWebUtil.mergeTemplate(VelocityWebUtil.java:90) [dotcms_3.6.1_cfa5586.jar:?]
	at sun.reflect.GeneratedMethodAccessor284.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:178) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:374) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:218) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:308) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:226) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:211) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:330) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.RuntimeInstance.render(RuntimeInstance.java:1363) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.RuntimeInstance.evaluate(RuntimeInstance.java:1299) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.RuntimeInstance.evaluate(RuntimeInstance.java:1250) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.app.VelocityEngine.evaluate(VelocityEngine.java:200) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.tools.generic.RenderTool.eval(RenderTool.java:138) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.tools.view.tools.ViewRenderTool.eval(ViewRenderTool.java:125) [dotcms_3.6.1_cfa5586.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:178) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:374) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:423) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:211) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:423) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:211) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:330) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.Template.merge(Template.java:362) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.velocity.Template.merge(Template.java:265) [dotcms_3.6.1_cfa5586.jar:?]
	at com.dotmarketing.velocity.VelocityServlet.doEditMode(VelocityServlet.java:1150) [dotcms_3.6.1_cfa5586.jar:?]
	at com.dotmarketing.velocity.VelocityServlet.service(VelocityServlet.java:231) [dotcms_3.6.1_cfa5586.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:246) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:308) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:130) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146) [dotcms_3.6.1_cfa5586.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: com.dotmarketing.portlets.contentlet.business.DotContentletStateException: No contenlet found for given identifier
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.findContentletByIdentifier(ESContentletAPIImpl.java:268) ~[dotcms_3.6.1_cfa5586.jar:?]
	... 145 more
```

## Context
Reported by customer: https://my.dotcms.com/tickets/detail.dot?id=f69b0514-f1c2-4ed4-b61c-a5b812627ce7

## Your Environment

* dotCMS 3.6.x.
* Google Chrome, Firefox browsers.
* macOS Sierra, any Windows version.
* Tomcat 8.0.18
* Oracle JDK 8, openJDK 8.
* Postgres 9.4.1.

**Comment by joseorsini** [comment]
Another customer affected by this https://my.dotcms.com/tickets/detail.dot?id=c27d9ca5-0706-41f8-a5fb-a806baaee553 

Needs to be tested on current release and see if issue is fixed or not.

**Comment by oarrietadotcms** [comment]
This is still happening in 5.2.4
