### ISSUE TITLE
SQL errors on Task03600UpdateMssqlVarcharTextColumns.java

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#10608]
While running an upgrade to 3.7.0 on a client dataset, ran into a number of WARNs and ERRORs during Task03600UpdateMssqlVarcharTextColumns due to unexpected schema. Some of these may be unique to the client, but quite a few are not. The ERRORS are due to a mismatched schema definition for converted NVARCHAR() column sizes.

**Comment by chrismccracken** [comment]
```
[31/01/17 18:46:21:251 EST]  WARN runonce.Task03600UpdateMssqlVarcharTextColumns: Drop constraint failed with 'ux_permission_reference_1': ['ux_permission_reference_1' is not a constraint.] . Try again by dropping it as an index...
[31/01/17 18:46:21:293 EST]  WARN runonce.Task03600UpdateMssqlVarcharTextColumns: Drop constraint failed with 'UQ__analytic_summary__16EE5E27': ['UQ__analytic_summary__16EE5E27' is not a constraint.] . Try again by dropping it as an index...
[31/01/17 18:46:21:326 EST]  WARN runonce.Task03600UpdateMssqlVarcharTextColumns: Drop constraint failed with 'IX_structure_velocity_var_name': ['IX_structure_velocity_var_name' is not a constraint.] . Try again by dropping it as an index...
[31/01/17 18:46:21:331 EST]  WARN runonce.Task03600UpdateMssqlVarcharTextColumns: Drop constraint failed with 'UQ__structure__48BAC3E5': ['UQ__structure__48BAC3E5' is not a constraint.] . Try again by dropping it as an index...
[31/01/17 18:46:21:334 EST]  WARN runonce.Task03600UpdateMssqlVarcharTextColumns: Drop constraint failed with 'IX_cms_role1': ['IX_cms_role1' is not a constraint.] . Try again by dropping it as an index...
[31/01/17 18:46:21:342 EST]  WARN runonce.Task03600UpdateMssqlVarcharTextColumns: Drop constraint failed with 'permission_id_type_role_ux': ['permission_id_type_role_ux' is not a constraint.] . Try again by dropping it as an index...
[31/01/17 18:46:21:360 EST]  WARN runonce.Task03600UpdateMssqlVarcharTextColumns: Drop constraint failed with 'IX_category_category_velocity_var_name': ['IX_category_category_velocity_var_name' is not a constraint.] . Try again by dropping it as an index...
[31/01/17 18:46:21:475 EST]  WARN runonce.Task03600UpdateMssqlVarcharTextColumns: Drop constraint failed with 'proxy_id_key': ['proxy_id_key' is not a constraint.] . Try again by dropping it as an index...
[31/01/17 18:46:21:480 EST]  WARN runonce.Task03600UpdateMssqlVarcharTextColumns: Drop constraint failed with 'IDX_FIELD_VELOCITY_STRUCTURE': ['IDX_FIELD_VELOCITY_STRUCTURE' is not a constraint.] . Try again by dropping it as an index...
[31/01/17 18:46:21:543 EST]  WARN runonce.Task03600UpdateMssqlVarcharTextColumns: Drop constraint failed with 'workflow_idx_scheme_structure_2': ['workflow_idx_scheme_structure_2' is not a constraint.] . Try again by dropping it as an index...

[31/01/17 19:22:58:062 EST]  INFO runonce.Task03600UpdateMssqlVarcharTextColumns: Executing: ALTER TABLE workflow_task ADD CONSTRAINT FK_workflow_assign FOREIGN KEY (assigned_to) REFERENCES cms_role (id)
[31/01/17 19:22:58:063 EST] ERROR runonce.Task03600UpdateMssqlVarcharTextColumns: Can't create foreign key on table 'cms_role' in columns [id]. Message: Column 'cms_role.id' is not the same length or scale as referencing column 'workflow_task.assigned_to' in foreign key 'FK_workflow_assign'. Columns participating in a foreign key relationship must be defined with the same length and scale.
com.microsoft.sqlserver.jdbc.SQLServerException: Column 'cms_role.id' is not the same length or scale as referencing column 'workflow_task.assigned_to' in foreign key 'FK_workflow_assign'. Columns participating in a foreign key relationship must be defined with the same length and scale.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1635) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:426) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:372) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:6276) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1793) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:184) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:159) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:354) ~[sqljdbc42.jar:?]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:197) ~[tomcat-dbcp.jar:8.0.18]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:197) ~[tomcat-dbcp.jar:8.0.18]
	at com.dotmarketing.startup.AbstractJDBCStartupTask.createConstraint(AbstractJDBCStartupTask.java:1103) ~[dotcms_3.7.0_b5bf438.jar:?]
	at com.dotmarketing.startup.AbstractJDBCStartupTask.executeUpgrade(AbstractJDBCStartupTask.java:867) [dotcms_3.7.0_b5bf438.jar:?]
	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:268) [dotcms_3.7.0_b5bf438.jar:?]
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:116) [dotcms_3.7.0_b5bf438.jar:?]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4901) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5188) [catalina.jar:8.0.18]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714) [catalina.jar:8.0.18]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1069) [catalina.jar:8.0.18]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1719) [catalina.jar:8.0.18]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

[31/01/17 19:22:58:068 EST]  INFO runonce.Task03600UpdateMssqlVarcharTextColumns: Executing: ALTER TABLE workflow_task ADD CONSTRAINT FK_workflow_task_asset FOREIGN KEY (webasset) REFERENCES identifier (id)
[31/01/17 19:22:58:070 EST] ERROR runonce.Task03600UpdateMssqlVarcharTextColumns: Can't create foreign key on table 'identifier' in columns [id]. Message: Column 'identifier.id' is not the same length or scale as referencing column 'workflow_task.webasset' in foreign key 'FK_workflow_task_asset'. Columns participating in a foreign key relationship must be defined with the same length and scale.
com.microsoft.sqlserver.jdbc.SQLServerException: Column 'identifier.id' is not the same length or scale as referencing column 'workflow_task.webasset' in foreign key 'FK_workflow_task_asset'. Columns participating in a foreign key relationship must be defined with the same length and scale.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1635) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:426) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:372) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:6276) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1793) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:184) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:159) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:354) ~[sqljdbc42.jar:?]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:197) ~[tomcat-dbcp.jar:8.0.18]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:197) ~[tomcat-dbcp.jar:8.0.18]
	at com.dotmarketing.startup.AbstractJDBCStartupTask.createConstraint(AbstractJDBCStartupTask.java:1103) ~[dotcms_3.7.0_b5bf438.jar:?]
	at com.dotmarketing.startup.AbstractJDBCStartupTask.executeUpgrade(AbstractJDBCStartupTask.java:867) [dotcms_3.7.0_b5bf438.jar:?]
	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:268) [dotcms_3.7.0_b5bf438.jar:?]
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:116) [dotcms_3.7.0_b5bf438.jar:?]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4901) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5188) [catalina.jar:8.0.18]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714) [catalina.jar:8.0.18]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1069) [catalina.jar:8.0.18]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1719) [catalina.jar:8.0.18]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
	
[31/01/17 19:22:58:070 EST]  INFO runonce.Task03600UpdateMssqlVarcharTextColumns: Executing: ALTER TABLE workflow_task ADD CONSTRAINT FK_workflow_step FOREIGN KEY (status) REFERENCES workflow_step (id)
[31/01/17 19:22:58:071 EST] ERROR runonce.Task03600UpdateMssqlVarcharTextColumns: Can't create foreign key on table 'workflow_step' in columns [id]. Message: Column 'workflow_step.id' is not the same length or scale as referencing column 'workflow_task.status' in foreign key 'FK_workflow_step'. Columns participating in a foreign key relationship must be defined with the same length and scale.
com.microsoft.sqlserver.jdbc.SQLServerException: Column 'workflow_step.id' is not the same length or scale as referencing column 'workflow_task.status' in foreign key 'FK_workflow_step'. Columns participating in a foreign key relationship must be defined with the same length and scale.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1635) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:426) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:372) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:6276) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1793) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:184) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:159) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:354) ~[sqljdbc42.jar:?]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:197) ~[tomcat-dbcp.jar:8.0.18]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:197) ~[tomcat-dbcp.jar:8.0.18]
	at com.dotmarketing.startup.AbstractJDBCStartupTask.createConstraint(AbstractJDBCStartupTask.java:1103) ~[dotcms_3.7.0_b5bf438.jar:?]
	at com.dotmarketing.startup.AbstractJDBCStartupTask.executeUpgrade(AbstractJDBCStartupTask.java:867) [dotcms_3.7.0_b5bf438.jar:?]
	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:268) [dotcms_3.7.0_b5bf438.jar:?]
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:116) [dotcms_3.7.0_b5bf438.jar:?]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4901) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5188) [catalina.jar:8.0.18]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714) [catalina.jar:8.0.18]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1069) [catalina.jar:8.0.18]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1719) [catalina.jar:8.0.18]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by chrismccracken** [comment]
Ref https://my.dotcms.com/ticket/dotcms-199/

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/10639

**Comment by erickgonzalez** [comment]
The errors are gone but the warnings still show, checking the logs the index is drop. E.g:

```
[03/02/17 12:19:35:959 CST]  INFO runonce.Task03600UpdateMssqlVarcharTextColumns: Executing: ALTER TABLE field DROP CONSTRAINT IDX_FIELD_VELOCITY_STRUCTURE
[03/02/17 12:19:35:959 CST]  WARN runonce.Task03600UpdateMssqlVarcharTextColumns: Drop constraint failed with 'IDX_FIELD_VELOCITY_STRUCTURE': ['IDX_FIELD_VELOCITY_STRUCTURE' is not a constraint.] . Try again by dropping it as an index...
[03/02/17 12:19:35:959 CST]  INFO runonce.Task03600UpdateMssqlVarcharTextColumns: Executing: DROP INDEX field.IDX_FIELD_VELOCITY_STRUCTURE
```

As you can see it first tries to drop it as a constraint, when it fails it immediately tries as an index.

**Comment by jcastro-dotcms** [comment]
@erickgonzalez @chrismccracken Erick's comment is correct, the warning message is just informative. The Java API used to read the metadata in that part of the code might return mixed constraint and index objects. Therefore, if the object cannot be dropped as a constraint, it means it actually is an index object.

**Comment by oarrietadotcms** [comment]
Note to QA: we need to check dotCMS from a upgrade and also from clean install of dotCMS, both in MSSQL.

**Comment by shaydotcms** [comment]
Passed QA.
Tested on upgrade using 3.3 client db to latest master-3.7
No errors in the logs as described by @erickgonzalez, just warning messages
