### ISSUE TITLE
Upload (PUT) language properties files via webdav fails

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#10741]
Test: Connect to demo.dotcms.com via webdav, using path /webdav/live/1. Browse to /system/properties, download a file, make a quick edit, and try to re-upload. Throws following exception:

```
[15/02/17 13:36:46:280 EST]  INFO http.HttpManager: PUT :: http://demo.dotcms.com/webdav/live/1/system/languages/cms_language_en_US.properties-dd4a4248-8631-4569-b648-f8716565b3de
- http://demo.dotcms.com/webdav/live/1/system/languages/cms_language_en_US.properties-dd4a4248-8631-4569-b648-f8716565b3de
[15/02/17 13:36:46:336 EST] ERROR http.StandardFilter: process
java.lang.RuntimeException: You cannot add/edit languages files that are not properties files.
        at com.dotmarketing.webdav.LanguageFolderResourceImpl.createNew(LanguageFolderResourceImpl.java:256) ~[dotcms_3.7.0_ded9292.jar:?]
        at com.dotcms.repackage.com.bradmcevoy.http.http11.PutHandler.processCreate(PutHandler.java:214) ~[dot.milton-api-1.8.1.4_2.jar:?]
        at com.dotcms.repackage.com.bradmcevoy.http.http11.PutHandler.process(PutHandler.java:188) ~[dot.milton-api-1.8.1.4_2.jar:?]
        at com.dotcms.repackage.com.bradmcevoy.http.StandardFilter.process(StandardFilter.java:52) [dot.milton-api-1.8.1.4_2.jar:?]
        at com.dotcms.repackage.com.bradmcevoy.http.FilterChain.process(FilterChain.java:40) [dot.milton-api-1.8.1.4_2.jar:?]
        at com.dotcms.repackage.com.bradmcevoy.http.HttpManager.process(HttpManager.java:228) [dot.milton-api-1.8.1.4_2.jar:?]
        at com.dotcms.repackage.com.bradmcevoy.http.MiltonServlet.service(MiltonServlet.java:195) [dot.milton-servlet-1.8.1.4_2.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:259) [dotcms_3.7.0_ded9292.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61) [dotcms_3.7.0_ded9292.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:152) [dotcms_3.7.0_ded9292.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:63) [dotcms_3.7.0_ded9292.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_3.7.0_ded9292.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) [dotcms_3.7.0_ded9292.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146) [dotcms_3.7.0_ded9292.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:673) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by joseorsini** [comment]
Reproduced on demo.dotcms.com site.

Steps to reproduce:

- Connect to a dotCMS 3.7.0 environment using a Webdav Client like Cyberduck.
- Once connection to /webdav/live/1 is made, go to /system/languages folder.
- Right click -> edit the cms_language_en_US.properties file (use any text editor for this).
- Add the following key: 
    - hello-world=hello world
- Save and exit.

Error is thrown because the file extension is not 'properties'. See there's a system-generated UUID value next to the file extension, which breaks the process of updating a properties file via WebDAV.

**Comment by chrismccracken** [comment]
Affecting client https://my.dotcms.com/tickets/detail.dot?id=cd198cf9-571a-4028-a9d1-adcf9db4c705

**Comment by joseorsini** [comment]
@chrismccracken after upgrading Cyberduck to version 5.3.7, I'm no longer able to reproduce the issue. 

For Cyberduck 4.x releases, it seems there is a half-baked locking process that adds a UUID to the end of the filename in order to set a lock over while it's edited/uploaded to the application. Nothing in the dotCMS logic modifies the properties file name while it's uploaded, according to the remote debugging I've been making for WebDAV operations. 

Please try with an updated version of Cyberduck and let us know if this can be reproduced again on customer's end.

**Comment by wezell** [comment]
or try curl:
😄 
`curl -v -u admin@dotcms.com:admin  -T '/Users/will/Desktop/dotcms.png' 'http://localhost:8080/webdav/live/1/demo.dotcms.com/‘`

**Comment by joseorsini** [comment]
tested and working, @wezell 😄

**Comment by chrismccracken** [comment]
Verified this was a CyberDuck bug, due to the uuid locking mechanism. It is not exclusive to 4.x though, I hit it with 5.3.3. Update to 5.3.7 resolved it.
