### ISSUE TITLE
Page to Content Migration - Fix for tab-divider field to avoid exception/error

### ISSUE THREAD

**Issue by agomez-dotcms** [dotCMS/core#10797]
When migrating pages to content for a specific Client, exception was thrown during an attempt to validate a tab-divider field. In this particular case, validation for tab-divider field should be skipped (should not be validated) because they hold no value at the contentlet level.

Following is the exception thrown, which caused the Page to Content migration to break:
```
[23/02/17 13:27:47:620 CST] ERROR business.HTMLPageAssetAPIImpl: There was a problem migrating Pages to Contents: Unknown field type
com.dotmarketing.portlets.contentlet.business.DotContentletStateException: Unknown field type
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.validateContentlet(ESContentletAPIImpl.java:3976) ~[dotcms_3.7.1_8d1e90a.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.validateContentlet(ESContentletAPIImpl.java:4227) ~[dotcms_3.7.1_8d1e90a.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2686) ~[dotcms_3.7.1_8d1e90a.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2556) ~[dotcms_3.7.1_8d1e90a.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2551) ~[dotcms_3.7.1_8d1e90a.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2501) ~[dotcms_3.7.1_8d1e90a.jar:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkin(ContentletAPIInterceptor.java:259) ~[dotcms_3.7.1_8d1e90a.jar:?]
	at com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPIImpl.migrateLegacyPage(HTMLPageAssetAPIImpl.java:493) ~[dotcms_3.7.1_8d1e90a.jar:?]
	at com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPIImpl.migrateAllLegacyPages(HTMLPageAssetAPIImpl.java:416) [dotcms_3.7.1_8d1e90a.jar:?]
	at com.dotmarketing.portlets.cmsmaintenance.ajax.CMSMaintenanceAjax.migrateHTMLPagesToContent(CMSMaintenanceAjax.java:311) [dotcms_3.7.1_8d1e90a.jar:?]
```

Following was the fix made, which may be incorporated as part of dotCMS's core (Added  "**|| "tab_divider".equalsIgnoreCase(field.getFieldType())**" as part of the else-if condition):
https://github.com/dotCMS/core/blob/3.7.1/src/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L3972

```
@Override
public void validateContentlet(Contentlet contentlet,List<Category> cats)throws DotContentletValidationException {
   ...
   }else if(isFieldTypeSystem(field) || isFieldTypeConstant(field) || "tab_divider".equalsIgnoreCase(field.getFieldType())){
   }else{
         Logger.error(this,"Found an unknown field type : This should never happen!!!");
         throw new DotContentletStateException("Unknown field type");
   }
   ...
}
```

This issue was reproduced during Page to Content migration for a specific client which had Page Asset content-type with a Metadata tab-divider field:
<img width="1439" alt="screen shot 2017-02-23 at 3 40 00 pm" src="https://cloud.githubusercontent.com/assets/22307536/23280448/d3a3d312-f9de-11e6-9ea0-02a48bb463c3.png">

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10798

**Comment by agomez-dotcms** [comment]
This fix for this issue may be borrowed from hot-fix at https://github.com/dotCMS/support/tree/master/hotfixes/hotfix-GIT-10797_v3.7.1

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11333
