### ISSUE TITLE
Push Publishing: Cannot configure "receive from" endpoint if DB is Oracle

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#10825]
## Expected Behavior
If a server is going to be part of a Push Publishing configuration, you must be able to set it as either sender or receiver environment.

## Current Behavior
For clients running dotCMS 3.7.x with Oracle 11g/12c databases, a server cannot be configured as "Receive From" environment because of NullPointerException errors triggered at the Publishing Environments tab (which breaks the entire Push Publishing-related backend view) and the PublisherQueueJob, affecting all Push Publishing jobs pending to be executed.

## Possible Solution
Handle potential NullPointerExceptions cases in Java/JSP code.

## Known Workarounds
None.

## Steps to Reproduce (for bugs)

1. Start dotCMS 3.7.1 using an Oracle 11g/12c Database.
2. After initial startup, apply an Enterprise License
3. Once license is applied, go to "Publishing Environments" tab, from Configuration Portlet.
4. Add a "Receive From" Environment

A "Sorry, an error occurred" message is displayed on the backend, and the browser Inspector tool shows an Error 500 message

Backend: 
<img width="1630" alt="screen shot 2017-02-27 at 8 30 41 am" src="https://cloud.githubusercontent.com/assets/1717110/23363255/cc989436-fcc7-11e6-9ca1-cba0206fdd1f.png">

Browser inspector tool:
![screen shot 2017-02-27 at 8 30 41 am 2](https://cloud.githubusercontent.com/assets/1717110/23363263/d7519b8e-fcc7-11e6-9f33-ce5eef71a431.png)

After the PublisherQueueJob is executed, this error is logged on the dotcms.log file: 

```
[27/02/17 08:31:00:062 EST] ERROR business.PublisherQueueJob: null
java.lang.NullPointerException
	at com.dotcms.publisher.util.PublisherUtil.getObjectByMap(PublisherUtil.java:64) ~[dotcms_3.7.1_57dc8a6.jar:?]
	at com.dotcms.publisher.endpoint.business.PublishingEndPointFactoryImpl.getEndPoints(PublishingEndPointFactoryImpl.java:43) ~[dotcms_3.7.1_57dc8a6.jar:?]
	at com.dotcms.publisher.endpoint.business.PublishingEndPointFactoryImpl.ensureCacheIsLoaded(PublishingEndPointFactoryImpl.java:29) ~[dotcms_3.7.1_57dc8a6.jar:?]
	at com.dotcms.publisher.endpoint.business.PublishingEndPointFactoryImpl.getEnabledReceivingEndPoints(PublishingEndPointFactoryImpl.java:157) ~[dotcms_3.7.1_57dc8a6.jar:?]
	at com.dotcms.publisher.endpoint.business.PublishingEndPointAPIImpl.getEnabledReceivingEndPoints(PublishingEndPointAPIImpl.java:88) ~[dotcms_3.7.1_57dc8a6.jar:?]
	at com.dotcms.publisher.business.PublisherQueueJob.execute(PublisherQueueJob.java:83) [dotcms_3.7.1_57dc8a6.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223) [dot.quartz-all-1.8.6_2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) [dot.quartz-all-1.8.6_2.jar:?]
```

Indicating that it cannot retrieve the Port of one of the saved environments: https://github.com/dotCMS/core/blob/master-4.0/dotCMS/src/main/java/com/dotcms/publisher/util/PublisherUtil.java#L64 This NPE affects Oracle clients only because of how empty strings are handled at database level (they're stored as null values instead). 

This is how the Server is stored on the publishing_end_point table: 

![screen shot 2017-02-27 at 8 44 47 am 2](https://cloud.githubusercontent.com/assets/1717110/23363528/0d4730e0-fcc9-11e6-8751-91ef470104b4.png)

This was tested on  dotCMS 3.7.1 running on Postgres and SQL Server database, however it cannot be reproduced on those setups.

## Context
Tested as part of local troubleshooting related to https://my.dotcms.com/tickets/detail.dot?id=78607db5-ef06-4c10-a80d-093a16a7336d 

## Your Environment

* dotCMS 3.7.1
* Google Chrome Browser.
* macOS Sierra (CMS), Ubuntu 16.04.2 LTS (Database)
* Tomcat 8.0.18
* Oracle Java JDK 8u60
* Oracle 11G Express Edition

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/10826

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/10827

**Comment by nollymar** [comment]
Tested on 4.0. Result: Successful
