### ISSUE TITLE
Upgrade - Error executing Task03605FixMSSQLMissingConstraints

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/core#10834]
Client upgrading from 3.6.2 to 3.7.1 (MS SQL Server) got the following error while executing Task03605FixMSSQLMissingConstraints.

```
[27/02/17 14:32:47:488 EST] FATAL runonce.Task03605FixMSSQLMissingConstraints: Unable to execute SQL upgrade
com.microsoft.sqlserver.jdbc.SQLServerException: The ALTER TABLE statement conflicted with the FOREIGN KEY constraint "FK_workflow_task_asset". The conflict occurred in database "dotcms", table "dbo.identifier", column 'id'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1635) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:865) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:762) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:6276) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1793) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:184) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:159) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:735) ~[sqljdbc42.jar:?]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:290) ~[tomcat-dbcp.jar:8.0.18]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:290) ~[tomcat-dbcp.jar:8.0.18]
	at com.dotmarketing.common.db.DotConnect.executeStatement(DotConnect.java:222) ~[dotcms_3.7.1_8d1e90a.jar:?]
	at com.dotmarketing.startup.AbstractJDBCStartupTask.executeUpgrade(AbstractJDBCStartupTask.java:793) [dotcms_3.7.1_8d1e90a.jar:?]
	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:268) [dotcms_3.7.1_8d1e90a.jar:?]
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:116) [dotcms_3.7.1_8d1e90a.jar:?]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4901) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5188) [catalina.jar:8.0.18]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714) [catalina.jar:8.0.18]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1069) [catalina.jar:8.0.18]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1719) [catalina.jar:8.0.18]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[27/02/17 14:32:47:502 EST] FATAL startup.StartupTasksExecutor: Unable to execute the upgrade task : Task03605FixMSSQLMissingConstraints
com.dotmarketing.exception.DotDataException: The ALTER TABLE statement conflicted with the FOREIGN KEY constraint "FK_workflow_task_asset". The conflict occurred in database "dotcms", table "dbo.identifier", column 'id'.
	at com.dotmarketing.startup.AbstractJDBCStartupTask.executeUpgrade(AbstractJDBCStartupTask.java:796) ~[dotcms_3.7.1_8d1e90a.jar:?]
	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:268) [dotcms_3.7.1_8d1e90a.jar:?]
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:116) [dotcms_3.7.1_8d1e90a.jar:?]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4901) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5188) [catalina.jar:8.0.18]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714) [catalina.jar:8.0.18]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1069) [catalina.jar:8.0.18]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1719) [catalina.jar:8.0.18]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The ALTER TABLE statement conflicted with the FOREIGN KEY constraint "FK_workflow_task_asset". The conflict occurred in database "dotcms", table "dbo.identifier", column 'id'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1635) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:865) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:762) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:6276) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1793) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:184) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:159) ~[sqljdbc42.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:735) ~[sqljdbc42.jar:?]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:290) ~[tomcat-dbcp.jar:8.0.18]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:290) ~[tomcat-dbcp.jar:8.0.18]
	at com.dotmarketing.common.db.DotConnect.executeStatement(DotConnect.java:222) ~[dotcms_3.7.1_8d1e90a.jar:?]
	at com.dotmarketing.startup.AbstractJDBCStartupTask.executeUpgrade(AbstractJDBCStartupTask.java:793) ~[dotcms_3.7.1_8d1e90a.jar:?]
	... 18 more
```
I'm waiting for some information on the client's database to rule out custom data inconsistency, but I wanted to report the issue since this upgrade task was just included in our latest 3.7.x release.

https://my.dotcms.com/tickets/detail.dot?id=f823de45-c097-420e-8f4c-544a9a5af15a

**Comment by gabbydotCMS** [comment]
@dsilvam we've got the 3.6.2 DB from the client in case you want to try this locally

**Comment by benjaminmichoux** [comment]
Hey,

I fixed the issue. Check the dotcms ticket to see how.

Thanks
Ben

**Comment by gabbydotCMS** [comment]
These are the queries to check/fix any inconsistencies in the table workflow_task that may get in the way of executing the upgrade task:

```
select * from workflow_task w where w.assigned_to is not null and not exists (select r.id from cms_role r where w.assigned_to = r.id);
select * from workflow_task w where w.webasset is not null and not exists (select i.id from identifier i where w.webasset = i.id);
select * from workflow_task w where w.status is not null and not exists (select s.id from workflow_step s where w.status = s.id);

delete from workflow_task where assigned_to is not null and not exists (select r.id from cms_role r where assigned_to = r.id);
delete from workflow_task where webasset is not null and not exists (select i.id from identifier i where webasset = i.id);
delete from workflow_task where status is not null and not exists (select s.id from workflow_step s where status = s.id);
```

No need for any changes to the upgrade task; we'll check if this is something that needs to be added to our fix inconsistency tasks.

Thanks !!!
