### ISSUE TITLE
Delete User is not updating deleted user references in the publishing_bundle table

### ISSUE THREAD

**Issue by oswaldogallango** [dotCMS/core#10838]
When you delete a user using the delete user button on the users portlet. We are not updating the user references in the 'owner' field of this table 'publishing_bundle'. That causes the following error when a user try to edit that content
```
[24/02/17 08:30:21:125 GMT] ERROR portlet.PortletRequestDispatcherImpl: org.apache.jasper.JasperException: com.dotmarketing.business.NoSuchUserException: dotcms.org.2867
org.apache.jasper.JasperException: org.apache.jasper.JasperException: com.dotmarketing.business.NoSuchUserException: dotcms.org.2867
        at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:548) ~[jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:454) ~[jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) ~[jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) ~[jasper.jar:8.0.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[catalina.jar:8.0.18]
       at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:584) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:523) ~[catalina.jar:8.0.18]
        at com.liferay.portlet.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:209) [dotcms_3.6.0_3876030.jar:?]
        at com.liferay.portal.struts.PortletRequestProcessor.doInclude(PortletRequestProcessor.java:344) [dotcms_3.6.0_3876030.jar:?]
        at com.liferay.portal.struts.PortletRequestProcessor.doForward(PortletRequestProcessor.java:319) [dotcms_3.6.0_3876030.jar:?]
        at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processTilesDefinition(TilesRequestProcessor.java:237) [dot.struts-1.2.4_2.jar:1.2.4]
        at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processForwardConfig(TilesRequestProcessor.java:300) [dot.struts-1.2.4_2.jar:1.2.4]
        at com.dotcms.repackage.com.oroad.stxx.plugin.StxxTilesRequestProcessor.processForwardConfig(StxxTilesRequestProcessor.java:134) [dot.stxx-1.3_2.jar:?]
        at com.liferay.portal.struts.PortletRequestProcessor.processForwardConfig(PortletRequestProcessor.java:205) [dotcms_3.6.0_3876030.jar:?]
        at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:231) [dot.struts-1.2.4_2.jar:1.2.4]
        at com.liferay.portal.struts.PortletRequestProcessor.process(PortletRequestProcessor.java:91) [dotcms_3.6.0_3876030.jar:?]
        at com.liferay.portlet.StrutsPortlet.include(StrutsPortlet.java:148) [dotcms_3.6.0_3876030.jar:?]
        at com.liferay.portlet.StrutsPortlet.doView(StrutsPortlet.java:100) [dotcms_3.6.0_3876030.jar:?]
        at com.dotcms.repackage.javax.portlet.GenericPortlet.doDispatch(GenericPortlet.java:235) [dot.portlet-1.0_2.jar:?]
        at com.dotcms.repackage.javax.portlet.GenericPortlet.render(GenericPortlet.java:163) [dot.portlet-1.0_2.jar:?]
        at com.liferay.portlet.CachePortlet.render(CachePortlet.java:159) [dotcms_3.6.0_3876030.jar:?]
                at org.apache.jsp.html.portal.layout_jsp._jspService(layout_jsp.java:605) [ROOT/:?]
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [jasper.jar:8.0.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) [jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) [jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) [jasper.jar:8.0.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:584) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:523) [catalina.jar:8.0.18]
        at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:934) [jasper.jar:8.0.18]
        at org.apache.jsp.html.portal.layout_005fportal_jsp._jspService(layout_005fportal_jsp.java:2964) [ROOT/:?]
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [jasper.jar:8.0.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) [jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) [jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) [jasper.jar:8.0.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318) [catalina.jar:8.0.18]
        at com.liferay.portal.struts.StrutsUtil.forward(StrutsUtil.java:72) [dotcms_3.6.0_3876030.jar:?]
        at com.liferay.portal.struts.PortalRequestProcessor.doForward(PortalRequestProcessor.java:174) [dotcms_3.6.0_3876030.jar:?]
        at com.dotmarketing.struts.PortalRequestProcessor.doForward(PortalRequestProcessor.java:51) [dotcms_3.6.0_3876030.jar:?]
        at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processTilesDefinition(TilesRequestProcessor.java:237) [dot.struts-1.2.4_2.jar:1.2.4]
        at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processForwardConfig(TilesRequestProcessor.java:300) [dot.struts-1.2.4_2.jar:1.2.4]
        at com.dotcms.repackage.com.oroad.stxx.plugin.StxxTilesRequestProcessor.processForwardConfig(StxxTilesRequestProcessor.java:134) [dot.stxx-1.3_2.jar:?]
        at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:231) [dot.struts-1.2.4_2.jar:1.2.4]
        at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:160) [dotcms_3.6.0_3876030.jar:?]
        at com.dotcms.repackage.org.apache.struts.action.ActionServlet.process(ActionServlet.java:1164) [dot.struts-1.2.4_2.jar:1.2.4]
        at com.dotcms.repackage.org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:397) [dot.struts-1.2.4_2.jar:1.2.4]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:618) [servlet-api.jar:?]
        at com.liferay.portal.servlet.MainServlet.callParentService(MainServlet.java:277) [dotcms_3.6.0_3876030.jar:?]
        at com.liferay.portal.servlet.MainServlet.service(MainServlet.java:506) [dotcms_3.6.0_3876030.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotcms.repackage.com.liferay.filters.secure.SecureFilter.doFilter(SecureFilter.java:135) [dot.secure-filter-ukv_2.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:259) [dotcms_3.6.0_3876030.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61) [dotcms_3.6.0_3876030.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:308) [dotcms_3.6.0_3876030.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
 
 Caused by: org.apache.jasper.JasperException: com.dotmarketing.business.NoSuchUserException: dotcms.org.2867
        at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:548) ~[jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:469) ~[jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) ~[jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) ~[jasper.jar:8.0.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:584) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:523) ~[catalina.jar:8.0.18]
        at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:934) ~[jasper.jar:8.0.18]
        at org.apache.jsp.html.portal.layout_005fportal_jsp._jspService(layout_005fportal_jsp.java:636) ~[?:?]
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:8.0.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) ~[jasper.jar:8.0.18]
        ... 118 more
Caused by: com.dotmarketing.business.NoSuchUserException: dotcms.org.2867
        at com.dotmarketing.business.UserFactoryLiferayImpl.loadUserById(UserFactoryLiferayImpl.java:145) ~[dotcms_3.6.0_3876030.jar:?]
        at com.dotmarketing.business.UserAPIImpl.loadUserById(UserAPIImpl.java:84) ~[dotcms_3.6.0_3876030.jar:?]
        at org.apache.jsp.html.portlet.ext.contentlet.edit_005fcontentlet_jsp._jspService(edit_005fcontentlet_jsp.java:5339) ~[?:?]
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:8.0.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) ~[jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) ~[jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) ~[jasper.jar:8.0.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:584) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:523) ~[catalina.jar:8.0.18]
        at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:934) ~[jasper.jar:8.0.18]
        at org.apache.jsp.html.portal.layout_005fportal_jsp._jspService(layout_005fportal_jsp.java:636) ~[?:?]
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:8.0.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) ~[jasper.jar:8.0.18]
        ... 118 more
Caused by: com.liferay.portal.NoSuchUserException: dotcms.org.2867
        at com.liferay.portal.ejb.UserPersistence.findByPrimaryKey(UserPersistence.java:246) ~[dotcms_3.6.0_3876030.jar:?]
        at com.liferay.portal.ejb.UserUtil.findByPrimaryKey(UserUtil.java:128) ~[dotcms_3.6.0_3876030.jar:?]
        at com.liferay.portal.ejb.UserLocalManagerImpl.getUserById(UserLocalManagerImpl.java:357) ~[dotcms_3.6.0_3876030.jar:?]
        at com.liferay.portal.ejb.UserLocalManagerUtil.getUserById(UserLocalManagerUtil.java:145) ~[dotcms_3.6.0_3876030.jar:?]
        at com.dotmarketing.business.UserFactoryLiferayImpl.loadUserById(UserFactoryLiferayImpl.java:143) ~[dotcms_3.6.0_3876030.jar:?]
        at com.dotmarketing.business.UserAPIImpl.loadUserById(UserAPIImpl.java:84) ~[dotcms_3.6.0_3876030.jar:?]
        at org.apache.jsp.html.portlet.ext.contentlet.edit_005fcontentlet_jsp._jspService(edit_005fcontentlet_jsp.java:5339) ~[?:?]
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:8.0.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) ~[jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) ~[jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) ~[jasper.jar:8.0.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:584) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:523) ~[catalina.jar:8.0.18]
        at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:934) ~[jasper.jar:8.0.18]
        at org.apache.jsp.html.portal.layout_005fportal_jsp._jspService(layout_005fportal_jsp.java:636) ~[?:?]
[24/02/17 08:30:21:133 GMT] ERROR portlet.StrutsPortlet: org.apache.jasper.JasperException: com.dotmarketing.business.NoSuchUserException: dotcms.org.2867
[24/02/17 08:30:31:484 GMT] ERROR portlet.PortletRequestDispatcherImpl: org.apache.jasper.JasperException: com.dotmarketing.business.NoSuchUserException: dotcms.org.2851
org.apache.jasper.JasperException: org.apache.jasper.JasperException: com.dotmarketing.business.NoSuchUserException: dotcms.org.2851
        at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:548) ~[jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:454) ~[jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) ~[jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) ~[jasper.jar:8.0.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:584) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:523) ~[catalina.jar:8.0.18]
        at com.liferay.portlet.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:209) [dotcms_3.6.0_3876030.jar:?]
        at com.liferay.portal.struts.PortletRequestProcessor.doInclude(PortletRequestProcessor.java:344) [dotcms_3.6.0_3876030.jar:?]
        at com.liferay.portal.struts.PortletRequestProcessor.doForward(PortletRequestProcessor.java:319) [dotcms_3.6.0_3876030.jar:?]
        at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processTilesDefinition(TilesRequestProcessor.java:237) [dot.struts-1.2.4_2.jar:1.2.4]
        at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processForwardConfig(TilesRequestProcessor.java:300) [dot.struts-1.2.4_2.jar:1.2.4]
        at com.dotcms.repackage.com.oroad.stxx.plugin.StxxTilesRequestProcessor.processForwardConfig(StxxTilesRequestProcessor.java:134) [dot.stxx-1.3_2.jar:?]
        at com.liferay.portal.struts.PortletRequestProcessor.processForwardConfig(PortletRequestProcessor.java:205) [dotcms_3.6.0_3876030.jar:?]
        at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:231) [dot.struts-1.2.4_2.jar:1.2.4]
```               

## Expected Behavior
When a user has pushed some content, in the contentlet history is reported the bundle used. But if the owner is not replaced when the user is deleted throws the exception mentioned before when this code is executed

```
for(PushedAsset pushedAsset: pushedAssets) {

                Environment env = APILocator.getEnvironmentAPI().findEnvironmentById(pushedAsset.getEnvironmentId());
                Bundle bundle = APILocator.getBundleAPI().getBundleById(pushedAsset.getBundleId());
                User owner = APILocator.getUserAPI().loadUserById(bundle.getOwner()); 
```

## Steps to Reproduce (for bugs)
1. create a user, add/edit some contents
2. push some content with that user
3. delete the user and replace with other
4. try to edit some content previously pushed by the deleted user

## Context
the error was reported by a client on this ticket https://my.dotcms.com/tickets/detail.dot?id=adbd2016-a46a-4a2a-bc50-ee94dcf053ac

## Your Environment

* dotCMS version used: 3.6

**Comment by joseorsini** [comment]
Perhaps related to https://github.com/dotCMS/core/issues/9917 ?

**Comment by gabbydotCMS** [comment]
Dup #9917
