### ISSUE TITLE
White screen if session times out or something

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10922]
This happens sometimes, and I am not sure what is causing it.  It is a 500being thrown here:

http://localhost:8080/api/v1/CORE_WEB/menu

and we are not handling it properly.  We should catch and redirect to login or something.

![white-screen-login](https://cloud.githubusercontent.com/assets/934364/23590926/8dbee1f4-01b6-11e7-8558-09f0a523b818.gif)

**Comment by wezell** [comment]
Clearing my cookies took me to the proper login screen.

**Comment by jgambarios** [comment]
@bryanboza please make sure this is not happening anymore.

**Comment by jdotcms** [comment]
I have tested it on Chrome and FF in different kinds of scenarios, works ok when there is session time out or any other artificial configuration just return 401 as expected

**Comment by joseorsini** [comment]
This was recently reported by a dEC customer. 

https://dotcms.zendesk.com/agent/tickets/94613

```
xxx.xxx.xxx visitor.ip.address - - [31/Oct/2017:22:43:11 +0000] GET /dotAdmin/assets/icon/favicon-32x32.png HTTP/1.1 200 390 "https://xxx.xxx.xxx/dotAdmin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" - 
xxx.xxx.xxx visitor.ip.address - - [31/Oct/2017:22:43:11 +0000] GET /api/v1/authentication/logInUser HTTP/1.1 200 611 "https://xxx.xxx.xxx/dotAdmin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" - 
xxx.xxx.xxx visitor.ip.address - - [31/Oct/2017:22:43:11 +0000] GET /api/v1/CORE_WEB/menu HTTP/1.1 500 55 "https://xxx.xxx.xxx/dotAdmin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" - 
xxx.xxx.xxx visitor.ip.address - - [31/Oct/2017:22:43:11 +0000] GET /api/v1/CORE_WEB/menu HTTP/1.1 500 55 "https://xxx.xxx.xxx/dotAdmin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" - 
```

nginx logs returned this 

```
2017/10/30 09:00:00 [error] 3418#0: *138061 open() "/opt/dotcms/wwwroot/nginx/50x.html" failed (2: No such file or directory), client: visitor.ip.address, server: xxx.xxx.xxx, request: "GET /categoriesServlet?inode=4ee464af-bc97-430d-9599-b06f03550b30&q=&start=0&count=10 HTTP/1.1", upstream: "http://127.0.0.1:8082/categoriesServlet?inode=4ee464af-bc97-430d-9599-b06f03550b30&q=&start=0&count=10", host: "xxx.xxx.xxx", referrer: "https://xxx.xxx.xxx/c/portal/layout?p_l_id=71b8a1ca-37b6-4b6e-a43b-c7482f28db6c&p_p_id=content&p_p_action=1&p_p_state=maximized&p_p_mode=view&_content_struts_action=%2Fext%2Fcontentlet%2Fedit_contentlet&_content_cmd=edit&inode=b311c046-9ce9-495c-ad6a-f41d5cc5815e&referer=%2Fc%2Fportal%2Flayout%3Fp_l_id%3D71b8a1ca-37b6-4b6e-a43b-c7482f28db6c%26p_p_id%3Dcontent%26p_p_action%3D1%26p_p_state%3Dmaximized%26_content_struts_action%3D%2Fext%2Fcontentlet%2Fview_contentlets"
2017/10/30 12:57:51 [error] 3418#0: *203555 open() "/opt/dotcms/wwwroot/nginx/50x.html" failed (2: No such file or directory), client: visitor.ip.address, server: xxx.xxx.xxx, request: "GET /api/v1/CORE_WEB/menu HTTP/1.1", upstream: "http://127.0.0.1:8082/api/v1/CORE_WEB/menu", host: "xxx.xxx.xxx", referrer: "https://xxx.xxx.xxx/dotAdmin/"
2017/10/30 12:57:51 [error] 3418#0: *203561 open() "/opt/dotcms/wwwroot/nginx/50x.html" failed (2: No such file or directory), client: visitor.ip.address, server: xxx.xxx.xxx, request: "GET /api/v1/CORE_WEB/menu HTTP/1.1", upstream: "http://127.0.0.1:8082/api/v1/CORE_WEB/menu", host: "xxx.xxx.xxx", referrer: "https://xxx.xxx.xxx/dotAdmin/"
```

Nothing else was logged in the catalina.out, dotcms.log and catalina.2017-10-31.log. Closest error messages to those timestamps were related to websockets 

```
[31/10/17 08:49:07:058 GMT] ERROR websocket.SystemEventsWebSocketEndPoint: Message will not be sent because the WebSocket session has been closed
java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:381) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessage(WsRemoteEndpointImplBase.java:338) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessageBlock(WsRemoteEndpointImplBase.java:270) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPing(WsRemoteEndpointImplBase.java:174) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.WsRemoteEndpointBase.sendPing(WsRemoteEndpointBase.java:55) ~[tomcat-websocket.jar:8.0.18]
        at com.dotcms.rest.api.v1.system.websocket.SystemEventsWebSocketEndPoint.doPing(SystemEventsWebSocketEndPoint.java:116) ~[dotcms_4.1.1_999999.jar:?]
        at com.dotcms.rest.api.v1.system.websocket.SystemEventsWebSocketEndPoint.processPingPongQueue(SystemEventsWebSocketEndPoint.java:95) ~[dotcms_4.1.1_999999.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]

[31/10/17 14:57:27:136 GMT] ERROR websocket.SystemEventsWebSocketEndPoint: java.util.concurrent.ExecutionException: java.io.IOException: Broken pipe
java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: Broken pipe
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessageBlock(WsRemoteEndpointImplBase.java:282) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPing(WsRemoteEndpointImplBase.java:174) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.WsRemoteEndpointBase.sendPing(WsRemoteEndpointBase.java:55) ~[tomcat-websocket.jar:8.0.18]
        at com.dotcms.rest.api.v1.system.websocket.SystemEventsWebSocketEndPoint.doPing(SystemEventsWebSocketEndPoint.java:116) ~[dotcms_4.1.1_999999.jar:?]
        at com.dotcms.rest.api.v1.system.websocket.SystemEventsWebSocketEndPoint.processPingPongQueue(SystemEventsWebSocketEndPoint.java:95) ~[dotcms_4.1.1_999999.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Broken pipe
        at org.apache.tomcat.websocket.FutureToSendHandler.get(FutureToSendHandler.java:102) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessageBlock(WsRemoteEndpointImplBase.java:275) ~[tomcat-websocket.jar:8.0.18]
        ... 11 more
Caused by: java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:1.8.0_141]
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[?:1.8.0_141]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[?:1.8.0_141]
        at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[?:1.8.0_141]
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[?:1.8.0_141]
        at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:127) ~[tomcat-coyote.jar:8.0.18]
        at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:184) ~[tomcat-coyote.jar:8.0.18]
        at org.apache.coyote.http11.upgrade.NioServletOutputStream.doWriteInternal(NioServletOutputStream.java:94) ~[tomcat-coyote.jar:8.0.18]
        at org.apache.coyote.http11.upgrade.NioServletOutputStream.doWrite(NioServletOutputStream.java:61) ~[tomcat-coyote.jar:8.0.18]
        at org.apache.coyote.http11.upgrade.AbstractServletOutputStream.writeInternal(AbstractServletOutputStream.java:162) ~[tomcat-coyote.jar:8.0.18]
        at org.apache.coyote.http11.upgrade.AbstractServletOutputStream.write(AbstractServletOutputStream.java:129) ~[tomcat-coyote.jar:8.0.18]
        at org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer.onWritePossible(WsRemoteEndpointImplServer.java:99) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer.doWrite(WsRemoteEndpointImplServer.java:81) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:450) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessage(WsRemoteEndpointImplBase.java:338) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessageBlock(WsRemoteEndpointImplBase.java:270) ~[tomcat-websocket.jar:8.0.18]
        ... 11 more
```
