### ISSUE TITLE
Bundle fails to Publish

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11009]
This is from a dotcms 4 to a dotcms 4 instance.  See attached.

```
INFO  2017-03-11 09:20:21,664 com.dotmarketing.business.cache.provider.guava.GuavaCache:info(58): ***	 Building Cache : hostaliascache, size:1000,Concurrency:32
INFO  2017-03-11 09:20:21,664 com.dotmarketing.business.cache.provider.guava.GuavaCache:info(58): ***	 Building Cache : hostaliascache, size:1000,Concurrency:32
ERROR 2017-03-11 09:20:21,688 com.dotcms.publisher.business.PublisherAPIImpl:error(124): Error Publishing Bundle: Folder must already have an identifier before saving
com.dotcms.publishing.DotPublishingException: Folder must already have an identifier before saving
	at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.handleFolders(FolderHandler.java:223) ~[FolderHandler.class:?]
	at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.handle(FolderHandler.java:79) ~[FolderHandler.class:?]
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:201) [BundlePublisher.class:?]
	at com.dotcms.rest.PublishThread.run(PublishThread.java:41) [PublishThread.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: com.dotmarketing.business.DotStateException: Folder must already have an identifier before saving
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.save(FolderAPIImpl.java:553) ~[FolderAPIImpl.class:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.save(FolderAPIImpl.java:580) ~[FolderAPIImpl.class:?]
	at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.handleFolders(FolderHandler.java:217) ~[FolderHandler.class:?]
	... 4 more
ERROR 2017-03-11 09:20:21,693 java.lang.String:error(111): Error Publishing: com.dotcms.publishing.DotPublishingException: Folder must already have an identifier before saving
INFO  2017-03-11 09:20:21,693 com.dotmarketing.util.PushPublishLogger:info(58): class com.dotcms.rest.PublishThread : [BundleID: d839e469-cef3-4e9a-9299-244e44584fe1.tar.gz] Finished bundle publish process
INFO  2017-03-11 09:20:21,694 com.dotcms.rest.PublishThread:info(58): Finished bundle publish process
****
```

**Comment by wezell** [comment]
Here is the failing bundle:

[4041f728-099e-42fb-971c-75489087d170.tar.gz](https://github.com/dotCMS/core/files/835827/4041f728-099e-42fb-971c-75489087d170.tar.gz)

**Comment by wezell** [comment]
Ask me for the failing bundle

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/452

**Comment by bryanboza** [comment]
Hi @wezell please add more details related to the bundle to test... Thanks...

**Comment by bryanboza** [comment]
Tested in the last master-4.0 with a fresh install  and multiple data bases and i am having this error https://github.com/dotCMS/core/issues/9767  , but just uploading the bundle not directly with the PP
