### ISSUE TITLE
Push Publishing: Improvement of Push status for environments with multiple endpoints

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#11047]
Currently, we allow Push Publishing Configuration to set as many Environments as needed, and each Environment does not have a limit on how many servers and what kind of servers it allows. Common combinations are: 

1. One Environment, multiple Endpoints from the same Clustered environment, set to "Push to Only one Server".
2. One Environment with only one Endpoint, usually a Standalone server or only one node from a clustered environment (which needs to be always available).
3. One Environment, multiple Endpoints, being each Endpoint a Standalone server (with no connection with other Endpoints under the same Environment), set to "Push to All Servers".

## Expected Behavior
When there are multiple endpoints added to a single environment, and the Push Config is set to "Push to All Servers", we should get more details about how the push task went for each endpoint under this Environment.

## Current Behavior
We only provide details of how the push went to specific environments, and current status available are: 

- Success.
- Failed to send to all environments.
- Failed to send to some environments.

In the scenario # 3 described above, if one of the endpoints (meaning a standalone server) is not available at the moment, the Push indicates "Success" even though not all endpoints were able to get the Pushed bundle to them. 

## Possible Solution
Set an additional Publishing Status that indicate that some, or all endpoints from an Environment couldn't get the contents pushed to them and show the right info on the Publishing Queue -> Status/History tab for all bundles that partially failed.

## Known Workarounds
- Set a 1:1 Push Publish configuration -> 1 Environment with only 1 Endpoint/Server added to it.
- If the contents where manually pushed to this environment, there's no way to force-push them. There's only a "retry" option which sends the bundle with the already existing info (asset and its dependencies, force-push setting, etc.). So the user needs to add the contents to a new bundle and force-push them to this Environment.

## Steps to Reproduce 
1. 3 dotCMS 3.7.1 environments were started.
    - 1 Environment works as a Source/Sender environment.
    - 2 standalone environments work as Target/Receiver environments.
2. Set the Push Publishing configuration as follows:
    - 1 Environment set as Receiver Environment, which consists on 2 separate Standalone Endpoints (each one with its own data and assets).
    - On the 2 Receiver Environments, the “receive from” server is the Sender one.
    - Push config is set to Push to All Endpoints/Servers.

![screen shot 2017-03-15 at 10 01 07 am 2](https://cloud.githubusercontent.com/assets/1717110/23951996/58664350-0966-11e7-96e6-11994824e7a3.png)

5. Create a “/test-push” folder under demo.dotcms.con site, and added a single image to it. 
6. Then, push the folder to all endpoints under the same Environment. Push, as expected, worked without issues.

`Sender Environment`
![push-001-sender-001](https://cloud.githubusercontent.com/assets/1717110/23952232/2a3bb55e-0967-11e7-9e81-b36c1fb657de.png)

`Receiver Server # 1`
<img width="1548" alt="push-001-receiver-001" src="https://cloud.githubusercontent.com/assets/1717110/23952210/10049eda-0967-11e7-997e-428a1cbd70ce.png">

`Receiver Server # 2`
<img width="1659" alt="push-001-receiver-002" src="https://cloud.githubusercontent.com/assets/1717110/23952223/1c013b9e-0967-11e7-9fb4-508753f94834.png">

7. Stopped Receiver server #2.
8. Added a new image on Sender Environment, under the same folder.

![screen shot 2017-03-15 at 10 08 39 am 2](https://cloud.githubusercontent.com/assets/1717110/23952287/66c72d82-0967-11e7-97ff-c007ccb2e434.png)

9. Pushed the folder to All Environments.
    - Receiver Server #1 was updated, as expected.
    - Error is logged on Sender Environment, saying that a specific endpoint couldn't be reached.

```
[15/03/17 10:10:27:562 EDT]  INFO pusher.PushUtils: Compressing 1 to /Users/joseorsini/dotCMS/releases/3.7.1-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/bundles/ea19ed76-e5b6-4431-8b84-e671d645a261/../ea19ed76-e5b6-4431-8b84-e671d645a261.tar.gz
[15/03/17 10:10:27:654 EDT] ERROR pusher.PushPublisher: An error occured for the endpoint 8d6d2bcb-83a4-4398-8d14-8cfd017cc1ca with address 127.0.0.1.  Error: java.net.ConnectException: Connection refused
[15/03/17 10:11:00:092 EDT] ERROR business.PublisherQueueJob: java.net.ConnectException: Connection refused
com.dotcms.repackage.javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused
	at com.dotcms.repackage.org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287) ~[dot.jersey-client-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255) ~[dot.jersey-client-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:700) ~[dot.jersey-client-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:228) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:696) ~[dot.jersey-client-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:420) ~[dot.jersey-client-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:316) ~[dot.jersey-client-2.22.1_1.jar:?]
	at com.dotcms.publisher.business.PublisherQueueJob.updateAuditStatus(PublisherQueueJob.java:231) [dotcms_3.7.1_57dc8a6.jar:?]
	at com.dotcms.publisher.business.PublisherQueueJob.execute(PublisherQueueJob.java:79) [dotcms_3.7.1_57dc8a6.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223) [dot.quartz-all-1.8.6_2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) [dot.quartz-all-1.8.6_2.jar:?]
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_60]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_60]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_60]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_60]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_60]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_60]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0_60]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[?:1.8.0_60]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[?:1.8.0_60]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[?:1.8.0_60]
	at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[?:1.8.0_60]
	at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512) ~[?:1.8.0_60]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[?:1.8.0_60]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_60]
	at com.dotcms.repackage.org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:394) ~[dot.jersey-client-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285) ~[dot.jersey-client-2.22.1_1.jar:?]
	... 13 more
```

10. Receiver Server #2 was started.

11. Bundle that was pushed with the /test-push/ folder and two images was pushed again from Sender Server to All Environments. Image was not created on Receiver Server #2 because there were no edits on the pushed assets since they were pushed for the last time.

On all tests, pushed bundles were labeled as “Success”, meaning there were no problems with the Push Publishing tasks. However, on the bundle details, we noticed that there is an error message for the Endpoint that couldn't be reached when the Push was made

![screen shot 2017-03-15 at 10 12 43 am 2](https://cloud.githubusercontent.com/assets/1717110/23952535/1b3cfa8a-0968-11e7-8739-644a463f8b0b.png)

## Context
In this scenario, the bundle status should match with the actual status of each endpoint added to this environment. Additionally, there's no way from this view to push again the bundle to all Servers if the assets within it were not edited after the Push was made for the first time, not it's not possible to modify the Bundle settings and set "force push" to true. 

Reported by customers: 
- https://my.dotcms.com/tickets/detail.dot?id=d671ab77-7d18-41e8-a3b2-f241f4a4d385
- https://my.dotcms.com/tickets/detail.dot?id=4c8090ad-a529-48de-b918-db49b45b10f0

## Your Environment
* dotCMS 3.7.1.
* Google Chrome, Firefox, Safari browsers.
* macOS Sierra (CMS and DB).
* Tomcat 8.0.18.
* Java JDK 8u60.
* Postgres 9.4.1.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11145

**Comment by bryanboza** [comment]
Unable to test push publish, we have a some issues related in 4.1 and we need this fixes to test...

**Comment by bryanboza** [comment]
We still having the "failed to send to all environments" message, in the case #3... if the system send to one environment without problems but fail sending to the second server should be more specific with the message....

**Comment by jgambarios** [comment]
@bryanboza so it is working but we want a different error message in case 3?, what message should be display it in that case?

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11454

**Comment by bryanboza** [comment]
After test with the last changes, I see the different status are working now, but we still having a problem, because those ones appears just during the pushing process (if some one fail, we retry 3 times). After this process finish, the system is changing the status again to "**Failed to publish** or **Success**" this because the system shows a final status... And do some operations whit this.... We need make some change over this, to have the new messages as final status....
