### ISSUE TITLE
Content Types: Cannot reuse name/velVarName of Content Type that was previously deleted

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#11088]
We currently enforce users to place different names for each content type created in dotCMS. However, there's a chance that, depending on its name, there's already a match with an existing Velocity Var Name, and current code should allow saving the name parsed as Velocity Var Name plus an incremental number, depending on the amount of occurrences with existing content types.

## Expected Behavior

If we're saving a new content type, and the name is not currently used, or if it was used by a content type that no longer exists, it should allow saving it without conflicts.

## Current Behavior
Cannot create a new content type with the same name of a content type that was previously deleted.

## Possible Solution
Improve proper name/VelVarName validations for new Content Types.

## Known Workarounds
Save the Content Type with a different Name.

## Steps to Reproduce (for bugs)
1. Create a Widget Content Type called "Promo Box". Velocity Var Name will be set to "PromoBox"
2. Create a new Widget Content Type called "Promo Box 1". Velocity Var Name will be set to "PromoBox1"
3. Delete "Promo Box" content type. 
4. Attempt to re-create the "Promo Box" content type. 

Stacktrace: 

```
[21/03/17 10:26:49:977 EDT] WARN util.JDBCExceptionReporter: SQL Error: 0, SQLState: 23505
[21/03/17 10:26:49:977 EDT] ERROR util.JDBCExceptionReporter: ERROR: duplicate key value violates unique constraint "unique_struct_vel_var_name"
Detail: Key (velocity_var_name)=(PromoBox1) already exists.
[21/03/17 10:26:49:977 EDT] ERROR impl.SessionImpl: Could not synchronize database state with session
[21/03/17 10:26:49:977 EDT] ERROR action.EditStructureAction: com.dotmarketing.exception.DotHibernateException: Unable to save/update Object to Hibernate Session 
[21/03/17 10:26:49:977 EDT] WARN util.JDBCExceptionReporter: SQL Error: 0, SQLState: 25P02
[21/03/17 10:26:49:977 EDT] ERROR util.JDBCExceptionReporter: ERROR: current transaction is aborted, commands ignored until end of transaction block
[21/03/17 10:26:49:977 EDT] ERROR impl.SessionImpl: Could not synchronize database state with session
[21/03/17 10:26:49:977 EDT] ERROR db.HibernateUtil: could not insert: [com.dotmarketing.portlets.structure.model.Structure#c7c323a8-c560-4f46-b0f2-102667abe09a]
com.dotcms.repackage.net.sf.hibernate.exception.GenericJDBCException: could not insert: [com.dotmarketing.portlets.structure.model.Structure#c7c323a8-c560-4f46-b0f2-102667abe09a]
at com.dotcms.repackage.net.sf.hibernate.exception.SQLStateConverter.handledNonSpecificException(SQLStateConverter.java:80) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:69) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:29) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.persister.AbstractEntityPersister.convert(AbstractEntityPersister.java:1331) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.persister.NormalizedEntityPersister.insert(NormalizedEntityPersister.java:464) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.persister.NormalizedEntityPersister.insert(NormalizedEntityPersister.java:426) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.ScheduledInsertion.execute(ScheduledInsertion.java:37) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.execute(SessionImpl.java:2449) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.executeAll(SessionImpl.java:2435) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.execute(SessionImpl.java:2392) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.flush(SessionImpl.java:2261) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotmarketing.db.HibernateUtil.closeSession(HibernateUtil.java:739) [dotcms_4.0_999999.jar:?]
at com.dotmarketing.db.HibernateUtil.commitTransaction(HibernateUtil.java:831) [dotcms_4.0_999999.jar:?]
at com.dotmarketing.portlets.structure.action.EditStructureAction.processAction(EditStructureAction.java:156) [dotcms_4.0_999999.jar:?]
at com.liferay.portal.struts.PortletRequestProcessor.process(PortletRequestProcessor.java:128) [dotcms_4.0_999999.jar:?]
at com.liferay.portlet.StrutsPortlet.processAction(StrutsPortlet.java:116) [dotcms_4.0_999999.jar:?]
at com.liferay.portlet.CachePortlet.processAction(CachePortlet.java:130) [dotcms_4.0_999999.jar:?]
at com.liferay.portal.action.LayoutAction._processPortletRequest(LayoutAction.java:232) [dotcms_4.0_999999.jar:?]
at com.liferay.portal.action.LayoutAction._processActionRequest(LayoutAction.java:249) [dotcms_4.0_999999.jar:?]
at com.liferay.portal.action.LayoutAction.execute(LayoutAction.java:93) [dotcms_4.0_999999.jar:?]
at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:421) [dot.struts-1.2.4_2.jar:1.2.4]
at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:226) [dot.struts-1.2.4_2.jar:1.2.4]
at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:128) [dotcms_4.0_999999.jar:?]
at com.dotcms.repackage.org.apache.struts.action.ActionServlet.process(ActionServlet.java:1164) [dot.struts-1.2.4_2.jar:1.2.4]
at com.dotcms.repackage.org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:415) [dot.struts-1.2.4_2.jar:1.2.4]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:644) [servlet-api.jar:?]
at com.liferay.portal.servlet.MainServlet.callParentService(MainServlet.java:281) [dotcms_4.0_999999.jar:?]
at com.liferay.portal.servlet.MainServlet.service(MainServlet.java:510) [dotcms_4.0_999999.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotcms.repackage.com.liferay.filters.secure.SecureFilter.doFilter(SecureFilter.java:135) [dot.secure-filter-ukv_2.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:266) [dotcms_4.0_999999.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.0_999999.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:308) [dotcms_4.0_999999.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:134) [dotcms_4.0_999999.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_4.0_999999.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) [dotcms_4.0_999999.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146) [dotcms_4.0_999999.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:673) [catalina.jar:8.0.18]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102) ~[postgresql-9.0-801.jdbc3.jar:?]
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835) ~[postgresql-9.0-801.jdbc3.jar:?]
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257) ~[postgresql-9.0-801.jdbc3.jar:?]
at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500) ~[postgresql-9.0-801.jdbc3.jar:?]
at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388) ~[postgresql-9.0-801.jdbc3.jar:?]
at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:334) ~[postgresql-9.0-801.jdbc3.jar:?]
at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97) ~[tomcat-dbcp.jar:8.0.18]
at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97) ~[tomcat-dbcp.jar:8.0.18]
at com.dotcms.repackage.net.sf.hibernate.persister.NormalizedEntityPersister.insert(NormalizedEntityPersister.java:454) ~[dot.hibernate-2.1.7_2.jar:?]
... 74 more
[21/03/17 10:26:49:982 EDT] WARN action.RequestProcessor: Unhandled Exception thrown: class com.dotmarketing.exception.DotHibernateException
[21/03/17 10:26:49:982 EDT] ERROR portlet.StrutsPortlet: com.dotmarketing.exception.DotHibernateException: Unable to close Hibernate Session 
[21/03/17 10:26:49:987 EDT] WARN util.JDBCExceptionReporter: SQL Error: 0, SQLState: 25P02
[21/03/17 10:26:49:987 EDT] ERROR util.JDBCExceptionReporter: ERROR: current transaction is aborted, commands ignored until end of transaction block
[21/03/17 10:26:49:987 EDT] ERROR impl.SessionImpl: Could not synchronize database state with session
[21/03/17 10:26:49:987 EDT] ERROR db.HibernateUtil: could not insert: [com.dotmarketing.portlets.structure.model.Structure#c7c323a8-c560-4f46-b0f2-102667abe09a]
com.dotcms.repackage.net.sf.hibernate.exception.GenericJDBCException: could not insert: [com.dotmarketing.portlets.structure.model.Structure#c7c323a8-c560-4f46-b0f2-102667abe09a]
at com.dotcms.repackage.net.sf.hibernate.exception.SQLStateConverter.handledNonSpecificException(SQLStateConverter.java:80) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:69) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:29) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.persister.AbstractEntityPersister.convert(AbstractEntityPersister.java:1331) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.persister.NormalizedEntityPersister.insert(NormalizedEntityPersister.java:464) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.persister.NormalizedEntityPersister.insert(NormalizedEntityPersister.java:426) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.ScheduledInsertion.execute(ScheduledInsertion.java:37) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.execute(SessionImpl.java:2449) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.executeAll(SessionImpl.java:2435) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.execute(SessionImpl.java:2392) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.flush(SessionImpl.java:2261) ~[dot.hibernate-2.1.7_2.jar:?]
at com.dotmarketing.db.HibernateUtil.closeSession(HibernateUtil.java:739) [dotcms_4.0_999999.jar:?]
at com.dotmarketing.listeners.HibernateSessionsListener.requestDestroyed(HibernateSessionsListener.java:19) [dotcms_4.0_999999.jar:?]
at org.apache.catalina.core.StandardContext.fireRequestDestroyEvent(StandardContext.java:5918) [catalina.jar:8.0.18]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:187) [catalina.jar:8.0.18]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:673) [catalina.jar:8.0.18]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102) ~[postgresql-9.0-801.jdbc3.jar:?]
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835) ~[postgresql-9.0-801.jdbc3.jar:?]
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257) ~[postgresql-9.0-801.jdbc3.jar:?]
at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500) ~[postgresql-9.0-801.jdbc3.jar:?]
at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388) ~[postgresql-9.0-801.jdbc3.jar:?]
at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:334) ~[postgresql-9.0-801.jdbc3.jar:?]
at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97) ~[tomcat-dbcp.jar:8.0.18]
at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97) ~[tomcat-dbcp.jar:8.0.18]
at com.dotcms.repackage.net.sf.hibernate.persister.NormalizedEntityPersister.insert(NormalizedEntityPersister.java:454) ~[dot.hibernate-2.1.7_2.jar:?]
... 24 more
```

## Context
Once this issue happens, it is not clear why it fails because at this point because there are no Content Types that match the selected Name/VelVarName combination. The deleted Content type is not listed anymore, and even if we flush all caches, the issue persists.
Reported by customer via Support Ticket: 	https://my.dotcms.com/tickets/detail.dot?id=e2957661-a331-4890-9961-b4ff3b1dd051

## Your Environment

* dotCMS 3.6.0, 4.0.
* Google Chrome Browser.
* macOS Sierra.
* Tomcat 8.0.18.
* Java JDK 8u60.
* Postgres 9.4.1.

**Comment by joseorsini** [comment]
This issue also affects fields. Support ticket: 	https://my.dotcms.com/tickets/detail.dot?id=8bff256b-1ed7-4d87-9eb6-a0f145caff56

**Comment by joseorsini** [comment]
This has been tested on current demo site, running 4.1, and works as expected. Content Types and Fields can reuse VelVarNames of items that were deleted in the past. Closing this ticket.
