### ISSUE TITLE
UserUtilTests are failing 

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#11127]
Almost the whole package of UserUtilTest is failing. https://cb.dotcms.com/view/master-4.1/job/Git_Master_Int_Funct_Test_Runner_4.1_MSSQL/lastCompletedBuild/testReport/com.liferay.portal.ejb/UserUtilTest/

There are 2 issues:

- **The one most common** com.dotmarketing.business.DotStateException:Cannot save locked or system role
	at com.dotmarketing.business.RoleAPIImpl.save(RoleAPIImpl.java:203)
	at com.dotmarketing.business.UserAPIImpl.delete(UserAPIImpl.java:411)

- **A couple is throwing this one** java.lang.Exception: Unexpected exception, expected<com.liferay.portal.NoSuchUserException> but was<com.dotmarketing.business.DotStateException>

These tests started failing on March 23.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/11174
