### ISSUE TITLE
Limited User unable to access Site->Browser tab because of READ permissions over Host ContentType

### ISSUE THREAD

**Issue by agomez-dotcms** [dotCMS/core#11248]
While addressing issue #11173, it was found that Limited Users are currently not able to access Site->Browser tab. Instead, system breaks with an exception in log. This is caused by the fact that [ContentTypeAPIImpl's find method](https://github.com/dotCMS/core/blob/master-4.1/dotCMS/src/main/java/com/dotcms/contenttype/business/ContentTypeAPIImpl.java#L126) is throwing exception if the Limited User does not have READ permissions over Host ContentType

## Expected Behavior
Site->Browser tab should be available to Limited Users

## Current Behavior
Site->Browser tab is not available to Limited Users. System throws following exception in log:

```
[05/04/17 11:11:37:569 CST] ERROR business.HostAPIImpl: User My Limited User : dotcms.org.2879 does not have READ permissions on ContentType SimpleContentType{name=Host, id=855a2d72-f2f3-4169-8b04-ac5157c4380c, description=System hosts information, defaultType=false, detailPage=null, fixed=true, iDate=Mon Mar 28 13:10:14 CST 2016, system=true, versionable=true, multilingualable=false, variable=Host, urlMapPattern=null, publishDateVar=null, expireDateVar=null, owner=null, modDate=Mon Apr 03 15:50:11 CST 2017, host=SYSTEM_HOST, folder=SYSTEM_FOLDER, requiredFields=[]}
com.dotmarketing.exception.DotSecurityException: User My Limited User : dotcms.org.2879 does not have READ permissions on ContentType SimpleContentType{name=Host, id=855a2d72-f2f3-4169-8b04-ac5157c4380c, description=System hosts information, defaultType=false, detailPage=null, fixed=true, iDate=Mon Mar 28 13:10:14 CST 2016, system=true, versionable=true, multilingualable=false, variable=Host, urlMapPattern=null, publishDateVar=null, expireDateVar=null, owner=null, modDate=Mon Apr 03 15:50:11 CST 2017, host=SYSTEM_HOST, folder=SYSTEM_FOLDER, requiredFields=[]}
	at com.dotcms.contenttype.business.ContentTypeAPIImpl.find(ContentTypeAPIImpl.java:129) ~[dotcms_4.1.0_999999.jar:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl.findDefaultHost(HostAPIImpl.java:98) [dotcms_4.1.0_999999.jar:?]
	at org.apache.jsp.html.portlet.ext.browser.sub_005fnav_jsp._jspService(sub_005fnav_jsp.java:618) [ROOT/:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [jasper.jar:8.0.18]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) [jasper.jar:8.0.18]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) [jasper.jar:8.0.18]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) [jasper.jar:8.0.18]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:584) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:523) [catalina.jar:8.0.18]
	at com.dotcms.repackage.com.liferay.taglib.IncludeTag.doEndTag(IncludeTag.java:72) [dot.util-taglib-ukv_2.jar:?]
	at org.apache.jsp.html.portal.layout_005fportal_jsp._jspService(layout_005fportal_jsp.java:581) [ROOT/:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [jasper.jar:8.0.18]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) [jasper.jar:8.0.18]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) [jasper.jar:8.0.18]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) [jasper.jar:8.0.18]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:584) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:523) [catalina.jar:8.0.18]
	at com.liferay.portlet.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:209) [dotcms_4.1.0_999999.jar:?]
	at com.liferay.portal.struts.PortletRequestProcessor.doInclude(PortletRequestProcessor.java:344) [dotcms_4.1.0_999999.jar:?]
	at com.liferay.portal.struts.PortletRequestProcessor.doForward(PortletRequestProcessor.java:319) [dotcms_4.1.0_999999.jar:?]
	at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processTilesDefinition(TilesRequestProcessor.java:237) [dot.struts-1.2.4_2.jar:1.2.4]
	at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processForwardConfig(TilesRequestProcessor.java:300) [dot.struts-1.2.4_2.jar:1.2.4]
	at com.dotcms.repackage.com.oroad.stxx.plugin.StxxTilesRequestProcessor.processForwardConfig(StxxTilesRequestProcessor.java:134) [dot.stxx-1.3_2.jar:?]
	at com.liferay.portal.struts.PortletRequestProcessor.processForwardConfig(PortletRequestProcessor.java:205) [dotcms_4.1.0_999999.jar:?]
	at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:231) [dot.struts-1.2.4_2.jar:1.2.4]
	at com.liferay.portal.struts.PortletRequestProcessor.process(PortletRequestProcessor.java:91) [dotcms_4.1.0_999999.jar:?]
	at com.liferay.portlet.StrutsPortlet.include(StrutsPortlet.java:148) [dotcms_4.1.0_999999.jar:?]
	at com.liferay.portlet.StrutsPortlet.doView(StrutsPortlet.java:100) [dotcms_4.1.0_999999.jar:?]
	at com.dotcms.repackage.javax.portlet.GenericPortlet.doDispatch(GenericPortlet.java:235) [dot.portlet-1.0_2.jar:?]
	at com.dotcms.repackage.javax.portlet.GenericPortlet.render(GenericPortlet.java:163) [dot.portlet-1.0_2.jar:?]
	at com.liferay.portlet.CachePortlet.render(CachePortlet.java:159) [dotcms_4.1.0_999999.jar:?]
	at org.apache.jsp.html.portal.layout_jsp._jspService(layout_jsp.java:618) [ROOT/:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [jasper.jar:8.0.18]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) [jasper.jar:8.0.18]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) [jasper.jar:8.0.18]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) [jasper.jar:8.0.18]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:584) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:523) [catalina.jar:8.0.18]
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:934) [jasper.jar:8.0.18]
	at org.apache.jsp.html.portal.layout_005fportal_jsp._jspService(layout_005fportal_jsp.java:1376) [ROOT/:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [jasper.jar:8.0.18]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) [jasper.jar:8.0.18]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) [jasper.jar:8.0.18]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) [jasper.jar:8.0.18]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318) [catalina.jar:8.0.18]
	at com.liferay.portal.struts.StrutsUtil.forward(StrutsUtil.java:72) [dotcms_4.1.0_999999.jar:?]
	at com.liferay.portal.struts.PortalRequestProcessor.doForward(PortalRequestProcessor.java:142) [dotcms_4.1.0_999999.jar:?]
	at com.dotmarketing.struts.PortalRequestProcessor.doForward(PortalRequestProcessor.java:51) [dotcms_4.1.0_999999.jar:?]
	at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processTilesDefinition(TilesRequestProcessor.java:237) [dot.struts-1.2.4_2.jar:1.2.4]
	at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processForwardConfig(TilesRequestProcessor.java:300) [dot.struts-1.2.4_2.jar:1.2.4]
	at com.dotcms.repackage.com.oroad.stxx.plugin.StxxTilesRequestProcessor.processForwardConfig(StxxTilesRequestProcessor.java:134) [dot.stxx-1.3_2.jar:?]
	at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:231) [dot.struts-1.2.4_2.jar:1.2.4]
	at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:128) [dotcms_4.1.0_999999.jar:?]
	at com.dotcms.repackage.org.apache.struts.action.ActionServlet.process(ActionServlet.java:1164) [dot.struts-1.2.4_2.jar:1.2.4]
	at com.dotcms.repackage.org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:397) [dot.struts-1.2.4_2.jar:1.2.4]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618) [servlet-api.jar:?]
	at com.liferay.portal.servlet.MainServlet.callParentService(MainServlet.java:281) [dotcms_4.1.0_999999.jar:?]
	at com.liferay.portal.servlet.MainServlet.service(MainServlet.java:510) [dotcms_4.1.0_999999.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.repackage.com.liferay.filters.secure.SecureFilter.doFilter(SecureFilter.java:135) [dot.secure-filter-ukv_2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:265) [dotcms_4.1.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.1.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:308) [dotcms_4.1.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:134) [dotcms_4.1.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_4.1.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) [dotcms_4.1.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:110) [dotcms_4.1.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
[05/04/17 11:11:37:569 CST] ERROR browser.sub_005fnav_jsp: user does not have a default host
[05/04/17 11:11:39:254 CST] ERROR business.HostAPIImpl: User dotcms.org.2879 does not have permission to host:demo.dotcms.com
[05/04/17 11:11:39:258 CST] ERROR business.HostAPIImpl: User dotcms.org.2879 does not have permission to host:demo.dotcms.com
```

## Steps to Reproduce (for bugs)
1. Create a new Role (My Limited Role). Grant access to all Tools
<img width="1440" alt="screen shot 2017-04-05 at 10 52 42 am" src="https://cloud.githubusercontent.com/assets/22307536/24718204/6847c7b6-19f2-11e7-8400-e61fc84e2ded.png">

2. Create a new User (My Limited User). Grant new Role
<img width="1440" alt="screen shot 2017-04-05 at 10 52 25 am" src="https://cloud.githubusercontent.com/assets/22307536/24718190/5f6694e2-19f2-11e7-808f-b832e22b9225.png">

3. Login as new User
4. Access Site->Browser tab
<img width="1439" alt="screen shot 2017-04-05 at 11 20 14 am" src="https://cloud.githubusercontent.com/assets/22307536/24718158/4b16d3c6-19f2-11e7-843a-497f7237a75b.png">

5. See exception in logs

## Known Workarounds
Manually/Individually Grant new Role (My Limited Role) access to Host Content-Type
<img width="1440" alt="screen shot 2017-04-05 at 11 21 38 am" src="https://cloud.githubusercontent.com/assets/22307536/24718154/4320d608-19f2-11e7-8b8c-40cb9a75ee1a.png">

## Your Environment
* dotCMS version used: 4.1.0 (master-4.1)
* Browser Name and version: Any
* Operating System and version: Mac OSX
* Application Server and version: Apache Tomcat
* Java Brand and version: Oracle Java 1.8.0_102
* Database and version: MySQL

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11259

**Comment by shaydotcms** [comment]
Passed QA. Followed steps to reproduce. Limited user now has access to Site->Browser tab.
Tested in master-4.1 / commit4b045577a008bd9838608f6849a1870ccd5677ee
Mac OS 10.10 / MySQL 5.6.35 / Firefox v45.0.1 / Tomcat 8 / Java 8
