### ISSUE TITLE
Seeing this error when you run Timemachine on starter

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11277]
```
INFO  2017-04-07 10:19:59,680 com.dotmarketing.business.cache.provider.guava.GuavaCache:info(58): ***	 Building Cache : tagbynameandhostcache, size:1000,Concurrency:32
WARN  2017-04-07 10:20:00,060 com.dotmarketing.viewtools.navigation.NavTool:velocityWarn(287): getNav null @ Thread-39 {/Users/will/git/dotcms4/tomcat8/webapps/ROOT/assets/b/a/ba85b092-02c1-4b20-bbae-eaff39b785cf/fileAsset/second-level-nav.vtl}
WARN  2017-04-07 10:20:00,389 com.dotmarketing.viewtools.navigation.NavTool:velocityWarn(287): getNav null @ Thread-39 {/Users/will/git/dotcms4/tomcat8/webapps/ROOT/assets/b/a/ba85b092-02c1-4b20-bbae-eaff39b785cf/fileAsset/second-level-nav.vtl}
ERROR 2017-04-07 10:20:00,538 com.dotcms.contenttype.util.KeyValueFieldUtil:error(124): Error parsing json: {"xmptpgNpages":"4","keywords":"Adobe Photoshop CS3 Keyboard Shortcuts","lastModified":"2008-03-11T18:18:57Z","subject":"Adobe Photoshop CS3 Keyboard Shortcuts","contentType":"application/pdf","creator":"Acrobat PDFMaker 8.1 for Excel","fileSize":"43552","content":"Adobe® Photoshop®\n \nCS3  Keyboard Shortcuts \nTools Edit Alt+E Layer Alt+L\nAdd Shape + C Assign Profile Ctrl+Alt+Shift+ [ C Blending Options Ctrl+Shift+O\nSubtract Shape - C Convert to Profile Ctrl+Alt+Shift+ ] Bring Forward Ctrl+ ]\nPreserve Transparency (toggle) / Clear (selection) Delete / Backspace Bring to Front Ctrl+Shift+ ]\nDecrease Brush Size [ Color Settings Ctrl+Shift+K Create / Release Clipping Mask (toggle) Ctrl+Alt+G\nIncrease Brush Size ] Copy Ctrl+C Group Layers Ctrl+G\nDecrease Brush Softness by 25% Shift+ [ Copy Merged Ctrl+Shift+C C Delete Layer (Group) Ctrl+Shift+ -\nIncrease Brush Hardness by 25% Shift+ ] Cut Ctrl+X C Delete Layer (Group) (no dialog) Ctrl+Alt+Shift+ -\nPrevious Brush < Duplicate Free Transform Ctrl+Alt+T C Duplicate Layer (Group) Ctrl+Shift+Q\nNext Brush > Duplicate Transform Again Ctrl+Alt+Shift+T C Duplicate Layer (no dialog) Ctrl+Alt+Shift+Q\nFirst Brush Shift+ < Fade (last filter / adjustment) Ctrl+Shift+F C Flatten Image Ctrl+Alt+Shift+0\nLast Brush Shift+ > Fill Dialog Shift+Backspace C Group into New Smart Object Ctrl+Alt+Shift+H\nTool Opacity 10% → 100% 1 → 0 Fill from History Ctrl+Alt+Backspace Layer Opacity 10% → 100% 1 → 0\nFlow / Airbrush Opacity 10% → 100% Shift+1 → 0 Fill from History & Preserve Trans. Ctrl+Alt+Shift+Backspace C Layer (Group) Properties Ctrl+ /\nPath / Direct Selection Tool A Fill w/ Background & Preserve Trans. Ctrl+Shift+Backspace Layer via Copy Ctrl+J\nBrush / Pencil / Color Replacement Tool B Fill w/ Foreground & Preserve Trans. Alt+Shift+Backspace Layer via Copy (with dialog) Ctrl+Alt+J\nCrop Tool C Fill with Background Color Ctrl+Backspace Layer via Cut Ctrl+Shift+J\nDefault Colors D Fill with Foreground Color Alt+Backspace Layer via Cut (with dialog) Ctrl+Alt+Shift+J\nEraser Tool E Free Transform Ctrl+T Merge Layers Ctrl+E\nCycle Screen Modes F Keyboard Shortcuts Alt+Shift+Ctrl+K Merge Visible Ctrl+Shift+E\nGradient / Paint Bucket Tool G Menus Ctrl+Alt+Shift+M New Layer Ctrl+Shift+N\nHand Tool H Paste Ctrl+V New Layer (no dialog) Ctrl+Alt+Shift+N\nEyedropper / Sampler / Measure Tool I Paste Into (selection) Ctrl+Shift+V C New Group Ctrl+Shift+ +\nSpot Healing / Healing / Patch / Red Eye J Paste Outside (selection) Ctrl+Alt+Shift+V C New Group (no dialog) Ctrl+Alt+Shift+ +\nSlice Tool K Preferences (General) Ctrl+K Next Layer Alt+ ]\nLasso Tool L Preferences (last used) Ctrl+Alt+K Previous Layer Alt+ [\nMarquee Tool M C Preset Manager Ctrl+Alt+ / Select Previous Layer Alt+Shift+ [\nNotes / Audio Annotation Tool N C Purge All Ctrl+Shift+ ' Select Next Layer Alt+Shift+ ]\nDodge / Burn / Sponge Tool O C Purge All (no dialog) Ctrl+Alt+Shift+ ' Send Backward Ctrl+ [\nPen / Freeform Pen Tool P Step Backward (History) Ctrl+Alt+Z Send to Back Ctrl+Shift+ [\nStandard / Quick Mask Mode Q Step Forward (History) Ctrl+Shift+Z Stamp Down Ctrl+Alt+E\nBlur / Sharpen / Smudge Tool R C Stroke Ctrl+Alt+H Stamp Visible Ctrl+Alt+Shift+E\nClone / Pattern Stamp Tool S Transform Again Ctrl+Shift+T Select Bottom Layer Alt+ ,\nType Tool (Vertical / Horizontal) T Undo/Redo Ctrl+Z Select Top Layer Alt+ .\nShape Tool U Select Layers to Bottom Layer Alt+Shift+ ,\nMove Tool V Filter Alt+T Select Layers to Top Layer Alt+Shift+ .\nMagic Wand Tool W C Add Noise Ctrl+Alt+Shift+Z Ungroup Layers Ctrl+Shift+G\nSwitch Colors X Extract Ctrl+Alt+X\nHistory / Art History Brush Tool Y C Gaussian Blur Ctrl+Alt+Shift+G File Alt+F\nZoom Tool Z Last Filter Ctrl+F Browse (Launch Adobe Bridge) Ctrl+Alt+O\nHand Tool (toggle) Space Last Filter (show dialog box) Ctrl+Alt+F Close Ctrl+W / Ctrl+F4\nZoom In (toggle) Ctrl+Space C Lens Correction Ctrl+Alt+Shift+Y Close All Ctrl+Alt+W / Ctrl+Shift+F4\nZoom Out (toggle) Alt+Space Liquify Ctrl+Shift+X Close and Go To Bridge Ctrl+Shift+W\nCycle Path / Direct Selection Tools Shift+A Pattern Maker Ctrl+Alt+Shift+X Edit in ImageReady Ctrl+Shift+M\nCycle Brush / Pencil / Color Replacement Shift+B C Smart Blur Ctrl+Alt+Shift+D Exit Ctrl+Q\nCycle Eraser Tools Shift+E C Smart Sharpen Ctrl+Alt+Shift+W File Info Ctrl+Alt+Shift+ I\nMenubar (show / hide) Shift+F C Unsharp Mask Ctrl+Alt+Shift+U New Document Ctrl+N\nToggle Gradient / Paint Bucket Tools Shift+G Vanishing Point Ctrl+Alt+V New Document (last settings) Ctrl+Alt+N\nCycle Eyedropper / Sampler / Measure Shift+ I Open Ctrl+O\nCycle Spot / Healing / Patch / Red Eye Shift+J Channels Open As Ctrl+Alt+Shift+O\nToggle Slice / Slice Select Tools Shift+K Add Composite Selection Ctrl+Alt+Shift+ ~ Page Setup Ctrl+Shift+P\nCycle Lasso Tools Shift+L Add Layer Mask Selection Ctrl+Alt+Shift+ \\ Print Ctrl+P\nToggle Rectangular / Elliptical Marquee Shift+M Add Selection Channel 1 → 9 Ctrl+Alt+Shift+1 → 9 Print One Copy Ctrl+Alt+Shift+P\nToggle Notes / Audio Annotation Tools Shift+N Channel / Rubylith View (toggle) ~ Print with Preview Ctrl+Alt+P\nCycle Dodge / Burn / Sponge Tools Shift+O Layer Mask as Rubylith (toggle) \\ Revert F12\nToggle Pen / Freeform Pen Tools Shift+P Load Composite as Selection Ctrl+Alt+ ~ Save Ctrl+S\nCycle Blur / Sharpen / Smudge Tools Shift+R Load Layer Mask as Selection Ctrl+Alt+ \\ Save As Ctrl+Shift+S\nToggle Clone / Pattern Stamp Tools Shift+S Load Selection Channel 1 → 9 Ctrl+Alt+1 → 9 Save As (Copy) Ctrl+Alt+S\nCycle Type Tools (Vertical / Horizontal) Shift+T Select Channel 1 → 9 Ctrl+1 → 9 Save for Web Ctrl+Alt+Shift+S\nCycle Shape / Line Tools Shift+U Select Composite Channel Ctrl+ ~\nToggle History / Art History Brush Shift+Y Select Layer Mask (Channel) Ctrl+ \\ Author:  Trevor Morris ( trevor@morris-photographics.com )\nAirbrush (Brush Tool) Alt+Shift+P Show Composite Channel (toggle) Shift+ ~ Website:  Morris Photographics ( Morris-Photographics.com )\n[N] New to Adobe Photoshop CS3\nVersion: 6/July/2007 [C] Custom keyboard shortcut\n\nAdobe® Photoshop®\n \nCS3  Keyboard Shortcuts \nSelect Alt+S Type Image Alt+I\nAll Ctrl+A Align Left Ctrl+Shift+L Auto Color Ctrl+Shift+B\nAll Layers Ctrl+Alt+A Align Right Ctrl+Shift+R Auto Contrast Ctrl+Alt+Shift+L\nC Contract Selection Ctrl+Alt+ [ Bold (toggle) Ctrl+Shift+B Auto Levels Ctrl+Shift+L\nDeselect Ctrl+D Center Text Ctrl+Shift+C N Black & White Ctrl+Alt+Shift+B\nC Expand Selection Ctrl+Alt+ ] Change Kerning by 100/1000em Ctrl+Alt+ ←,  → Canvas Size Ctrl+Alt+C\nFeather Ctrl+Alt+D Change Kerning by 20/1000em Alt+ ←,  → Color Balance Ctrl+B\nInverse Ctrl+Shift+ I Decrease / Increase Baseline by 10pt Ctrl+Alt+Shift+ ↑, ↓ Color Balance (last settings) Ctrl+Alt+B\nMove Duplicate of Selection 10px Ctrl+Alt+Shift+ ←, ↑, →, ↓ Decrease / Increase Baseline by 2pt Alt+Shift+ ↑, ↓ C Crop Ctrl+Alt+Shift+C\nMove Duplicate of Selection 1px Ctrl+Alt+ ←, ↑, →, ↓ Decrease / Increase Leading by 10pt Ctrl+Alt+ ↑, ↓ Curves Ctrl+M\nMove Selection (while creating) Space Decrease / Increase Leading by 2pt Alt+ ↑, ↓ Curves (last settings) Ctrl+Alt+M\nMove Selection 10px Ctrl+Shift+ ←, ↑, →, ↓ Decrease / Increase Type Size by 10pt Ctrl+Alt+Shift+ <, > Desaturate Ctrl+Shift+U\nMove Selection 1px Ctrl+ ←, ↑, →, ↓ Decrease / Increase Type Size by 2pt Ctrl+Shift+ <, > C Duplicate Ctrl+Shift+A\nMove Selection Area 10px Shift+ ←, ↑, →, ↓ Hyphenation (toggle) Ctrl+Alt+Shift+H C Duplicate (no dialog) Ctrl+Alt+Shift+A\nMove Selection Area 1px ←, ↑, →, ↓ Italic (toggle) Ctrl+Shift+I Hue / Saturation Ctrl+U\nN Refine Edge Ctrl+Alt+R Justify Paragraph (Force Last Line) Ctrl+Shift+F Hue / Saturation (last settings) Ctrl+Alt+U\nReselect Ctrl+Shift+D Justify Paragraph (Left Align Last Line) Ctrl+Shift+J Image Size Ctrl+Alt+I\nMove Cursor One Word Left or Right Ctrl+ ←, → Invert Ctrl+ I\nView Alt+V Move Cursor to End of Line End Levels Ctrl+L\nActual Pixels Ctrl+Alt+0 Move Cursor to End of Story Ctrl+End Levels (last settings) Ctrl+Alt+L\nC Clear Guides Ctrl+Alt+Shift+ ; Move Cursor to Start of Line Home C Mode > 8 Bits/Channel Ctrl+Alt+ ,\nExtras (show / hide) Ctrl+H Move Cursor to Start of Story Ctrl+Home C Mode > RGB Ctrl+ ,\nFit on Screen Ctrl+0 Move to Previous / Next Paragraph Ctrl+ ↑, ↓ C Reveal All Ctrl+Shift+R\nGamut Warning Ctrl+Shift+Y Regular (toggle) Ctrl+Shift+Y C Rotate Arbitrary Ctrl+Alt+Shift+R\nGrid (show / hide) Ctrl+ ' Select One Character to Left or Right Shift+ ←,  → C Shadow/Highlight Ctrl+Shift+ /\nGuides (lock / unlock) Ctrl+Alt+ ; Select One Line (to end) Up or Down Ctrl+Shift+ ↑, ↓ C Shadow/Highlight (last settings) Ctrl+Alt+Shift+ /\nGuides (show / hide) Ctrl+ ; Select One Line Up or Down Shift+ ↑, ↓ C Trim Ctrl+Alt+Y\nC New Guide Ctrl+Alt+ ' Select One Word to Left or Right Ctrl+Shift+ ←, →\nProof Colors (CMYK preview) Ctrl+Y Select Type to End of Line Shift+End Blending Modes\nRulers (show / hide) Ctrl+R Select Type to End of Story Ctrl+Shift+End Cycle Blending Modes Backward Shift+ -\nC Smart Guides (toggle) Ctrl+Alt+Q Select Type to Start of Line Shift+Home Cycle Blending Modes Forward Shift+ +\nSnap (on / off) Ctrl+Shift+ ; Select Type to Start of Story Ctrl+Shift+Home Behind Alt+Shift+Q\nTarget Path (show / hide) Ctrl+Shift+H Set Horizontal Scale to 100% Ctrl+Shift+X Clear Alt+Shift+R\n* Zoom In Ctrl+ + Set Leading to Auto Ctrl+Alt+Shift+A Color Alt+Shift+C\n* Zoom In & Resize Window Ctrl+Alt+ + Set Tracking to 0 Ctrl+Shift+Q Color Burn Alt+Shift+B\n* Zoom Out Ctrl+ - Set Vertical Scale to 100% Ctrl+Alt+Shift+X Color Dodge Alt+Shift+D\n* Zoom Out & Resize Window Ctrl+Alt+ - Show / Hide Type Ctrl+H Darken Alt+Shift+K\nSmall Caps (toggle) Ctrl+Shift+H Difference Alt+Shift+E\nWindow Alt+W Strikethrough (toggle) Ctrl+Shift+ / Dissolve Alt+Shift+ I\nAll Palettes (show / hide) Tab Subscript (toggle) Ctrl+Alt+Shift+ + Exclusion Alt+Shift+X\nTool Bar & Palettes (show / hide) Shift+Tab Superscript (toggle) Ctrl+Shift+ + Hard Light Alt+Shift+H\nActions Palette (show / hide) F9 Toggle Single / Every-Line Composer Ctrl+Alt+Shift+T Hard Mix / Threshold Alt+Shift+L\nC Animation (show / hide) F11 Underlining (toggle) Ctrl+Shift+U Hue Alt+Shift+U\nBrushes Palette (show / hide) F5 Uppercase (toggle) Ctrl+Shift+K Lighten Alt+Shift+G\nColor Palette (show / hide) F6 Cancel Type Changes Esc Linear Burn Alt+Shift+A\nC Histogram (show / hide) F4 Commit Type Changes Ctrl+Return / Enter Linear Dodge Alt+Shift+W\nC History (show / hide) F10 Linear Light Alt+Shift+J\nInfo Palette (show / hide) F8 Navigation Luminosity Alt+Shift+Y\nC Layer Comps (show / hide) F3 Move View to Bottom Right End Multiply Alt+Shift+M\nLayers Palette (show / hide) F7 Move View to Top Left Home Normal Alt+Shift+N\nOptions Bar (show) Return / Enter Next Document Ctrl+Tab Overlay Alt+Shift+O\nC New Window Ctrl+Shift+0 Previous Document Ctrl+Shift+Tab Pin Light Alt+Shift+Z\nScroll View Down 10px Shift+PageDown Saturation Alt+Shift+T\nMiscellaneous Scroll View Down One Page PageDown Screen Alt+Shift+S\nHelp F1 Scroll View Left 10px Ctrl+Shift+PageUp Soft Light Alt+Shift+F\nC About Photoshop Shift+F1 Scroll View Left One Page Ctrl+PageUp Vivid Light Alt+Shift+V\nAccept Operation Return / Enter Scroll View Right 10px Ctrl+Shift+PageDown Pass Through (Groups) Alt+Shift+P\nCancel Operation Esc / Ctrl+ . Scroll View Right One Page Ctrl+PageDown Desaturate (Sponge Tool) Alt+Shift+D\nApply Zoom & Keep Zoom Field Active Shift+Return Scroll View Up 10px Shift+PageUp Saturate (Sponge Tool) Alt+Shift+S\nNew Frame (animation) Ctrl+Alt+Shift+F Scroll View Up One Page PageUp Highlights (Dodge & Burn Tools) Alt+Shift+H\nC Play Action Ctrl+Alt+ . Pan / Zoom Multiple Documents Shift Midtones (Dodge & Burn Tools) Alt+Shift+M\nShadows (Dodge & Burn Tools) Alt+Shift+S\n[N] New to Adobe Photoshop CS3\n* These represent the default keyboard shortcuts; to reverse them, enable the \"Zoom Resizes Windows\" option in the General Preferences dialog [C] Custom keyboard shortcut\n\nAdobe® Photoshop®\n \nCS3  Keyboard Shortcuts \nShift Alt Alt+Shift\n1 Layer / Tool Opacity 10% Flow / Airbrush Opacity 10% 1\n2 Layer / Tool Opacity 20% Flow / Airbrush Opacity 20% 2\n3 Layer / Tool Opacity 30% Flow / Airbrush Opacity 30% 3\n4 Layer / Tool Opacity 40% Flow / Airbrush Opacity 40% 4\n5 Layer / Tool Opacity 50% Flow / Airbrush Opacity 50% 5\n6 Layer / Tool Opacity 60% Flow / Airbrush Opacity 60% 6\n7 Layer / Tool Opacity 70% Flow / Airbrush Opacity 70% 7\n8 Layer / Tool Opacity 80% Flow / Airbrush Opacity 80% 8\n9 Layer / Tool Opacity 90% Flow / Airbrush Opacity 90% 9\n0 Layer / Tool Opacity 100% Flow / Airbrush Opacity 100% 0\nA Path / Direct Selection Tool Path / Direct Selection Tools Linear Burn Blending Mode A\nB Brush / Pencil / Color Replacement Tool Cycle Brush / Pencil / Color Replacement Color Burn Blending Mode B\nC Crop Tool Color Blending Mode C\nD Default Colors Color Dodge / Desaturate D\nE Eraser Tool Cycle Eraser Tools Edit Menu${esc.b}u2026 Difference Blending Mode E\nF Cycle Screen Modes Menu Bar (show / hide) File Menu${esc.b}u2026 Soft Light Blending Mode F\nG Gradient / Paint Bucket Tool Toggle Gradient / Paint Bucket Lighten Blending Mode G\nH Hand Tool Help Menu${esc.b}u2026 Hard Light / Highlights H\nI Eyedropper / Sampler / Measure Eyedropper / Sampler / Measure Image Menu${esc.b}u2026 Dissolve Blending Mode I\nJ Spot / Healing / Patch / Red Eye Cycle Spot / Healing / Patch / Red Eye Linear Light Blending Mode J\nK Slice Tool Toggle Slice / Slice Select Tools Darken Blending Mode K\nL Lasso Tool Cycle Lasso Tools Layer Menu${esc.b}u2026 Hard Mix / Threshold L\nM Marquee Tool Rectangular / Elliptical Marquee Multiply  / Midtones M\nN Notes / Audio Annotation Tool Toggle Notes / Audio Annotations Normal Blending Mode N\nO Dodge / Burn / Sponge Tool Cycle Dodge / Burn / Sponge Overlay Blending Mode O\nP Pen / Freeform Pen Tool Toggle Pen / Freeform Pen Tools Pass Through Blend Mode (Groups) P\nQ Standard / Quick Mask Mode Behind Blending Mode Q\nR Blur / Sharpen / Smudge Tool Cycle Blur / Sharpen / Smudge Clear Blending Mode R\nS Clone / Pattern Stamp Tool Toggle Clone / Pattern Stamp Select Menu${esc.b}u2026 Screen / Saturate / Shadows S\nT Type Tool Filter Menu${esc.b}u2026 Saturation Blending Mode T\nU Shape Tool Cycle Shape / Line Tools Hue Blending Mode U\nV Move Tool View Menu${esc.b}u2026 Vivid Light Blending Mode V\nW Magic Wand Tool Window Menu${esc.b}u2026 Linear Dodge Blending Mode W\nX Switch Colors Exclusion Blending Mode X\nY History / Art History Brush Tool Toggle History / Art History Brush Luminosity Blending Mode Y\nZ Zoom Tool Pin Light Blending Mode Z\n+ Add Shape Cycle Blending Modes Forward +\n- Subtract Shape Cycle Blending Modes Backward -\n; ;\n' '\n[ Decrease Brush Size Decrease Brush Softness by 25% Previous Layer Select Previous Layer [\n] Increase Brush Size Increase Brush Hardness by 25% Next Layer Select Next Layer ]\n< ( , ) Previous Brush First Brush Select Bottom Layer Select Layers to Bottom Layer < ( , )\n> ( . ) Next Brush Last Brush Select Top Layer Select Layers to Top Layer > ( . )\n/ Preserve Transparency (toggle) /\n\\ Layer Mask as Rubylith (toggle) \\\n~ Channel / Rubylith View (toggle) Show Composite Channel (toggle) ~\nBackspace Clear (Selection) Fill Dialog Fill with Foreground Color Fill w/ Foreground & Preserve Trans. Backspace\nReturn Options Bar (show) Apply Zoom & Keep Box Active Return\nSpace Hand Tool / Drag Selection Zoom Out (toggle) Space\nTab Toolbar & Palettes (show / hide) All Palettes (show / hide) Next Application (Windows) Previous Application (Windows) Tab\n↑ Move Selection Area 1px Up Move Selection Area 10px Up T Increase Leading 2pt T Increase Baseline 2pt ↑\n↓ Move Selection Area 1px Down Move Selection Area 10px Down T Decrease Leading 2pt T Decrease Baseline 2pt ↓\n← Move Selection Area 1px Left Move Selection Area 10px Left T Decrease Kerning by 20/1000em ←\n→ Move Selection Area 1px Right Move Selection Area 10px Right T Increase Kerning by 20/1000em →\nHome Move View to Top Left T Select Type to Start of Line Home\nEnd Move View to Bottom Right T Select Type to End of Line End\nPageUp Scroll View Up Scroll View Up 10px PageUp\nPageDown Scroll View Down Scroll View Down 10px PageDown\n[N] New to Adobe Photoshop CS3\n[T] Only available in Type Mode\n[C] Custom keyboard shortcut\n\nAdobe® Photoshop®\n \nCS3  Keyboard Shortcuts \nCtrl Ctrl+Alt Ctrl+Shift Ctrl+Alt+Shift\n1 Select Channel 1 Load Selection Channel 1 Add Selection Channel 1 1\n2 Select Channel 2 Load Selection Channel 2 Add Selection Channel 2 2\n3 Select Channel 3 Load Selection Channel 3 Add Selection Channel 3 3\n4 Select Channel 4 Load Selection Channel 4 Add Selection Channel 4 4\n5 Select Channel 5 Load Selection Channel 5 Add Selection Channel 5 5\n6 Select Channel 6 Load Selection Channel 6 Add Selection Channel 6 6\n7 Select Channel 7 Load Selection Channel 7 Add Selection Channel 7 7\n8 Select Channel 8 Load Selection Channel 8 Add Selection Channel 8 8\n9 Select Channel 9 Load Selection Channel 9 Add Selection Channel 9 9\n0 Fit on Screen (View) Actual Pixels C New Window C Flatten Image 0\nA (Select) All All Layers C Duplicate C Duplicate (no dialog) A\nB Color Balance Color Balance (last settings) Auto Color N Black & White B\nC Copy Canvas Size Copy Merged C Crop C\nD Deselect Feather (Selection) Reselect C Smart Blur D\nE Merge Layers Stamp Down Merge Visible Stamp Visible E\nF Last Filter Last Filter Dialog Box Fade (last filter / adjustment) New Frame (animation) F\nG Group Layers Create / Release Clipping Mask (toggle) Ungroup Layers C Gaussian Blur G\nH Extras (show / hide) C Stroke Target Path (show / hide) C Group into New Smart Object H\nI Invert Image Size Inverse (selection) File Info I\nJ New Layer via Copy New Layer via Copy (with dialog) New Layer via Cut New Layer via Cut (with dialog) J\nK Preferences (General) Preferences Panel (last used) Color Settings Keyboard Shortcuts K\nL Levels Levels (last settings) Auto Levels Auto Contrast L\nM Curves Curves (last settings) Edit in ImageReady Menus M\nN New Document New Document (last settings) New Layer New Layer (no dialog) N\nO Open Browse (Launch Adobe Bridge) C Blending Options Open As O\nP Print Print with Preview Page Setup Print One Copy P\nQ Exit C Smart Guides (toggle) C Duplicate Layer (Group) C Duplicate Layer (Group) (no dialog) Q\nR Rulers (show / hide) N Refine Edge C Reveal All C Rotate Arbitrary R\nS Save Save As (Copy) Save As Save for Web S\nT Free Transform Duplicate Free Transform Transform Again Duplicate Transform Again T\nU Hue / Saturation Hue / Saturation (last settings) Desaturate C Unsharp Mask U\nV Paste Vanishing Point Paste Into (selection) Paste Outside (selection) V\nW Close Close All Close and Go To Bridge C Smart Sharpen W\nX Cut Extract Liquify Pattern Maker X\nY Proof Colors (CMYK preview) C Trim Gamut Warning C Lens Correction Y\nZ Undo/Redo Step Back (History) Step Forward (History) C Add Noise Z\n+ * Zoom In * Zoom In & Resize Window C New Group C New Group (no dialog) +\n- * Zoom Out * Zoom Out & Resize Window C Delete Layer (Group) C Delete Layer (Group) (no dialog) -\n; Guides (show / hide) Guides (lock / unlock) Snap (on / off) C Clear Guides ;\n' Grid (show / hide) C New Guide C Purge All C Purge All (no dialog) '\n[ Send Backward C Contract Selection Send to Back C Assign Profile [\n] Bring Forward C Expand Selection Bring to Front C Convert to Profile ]\n< ( , ) C Mode > RGB C Mode > 8 Bits/Channel T Decrease Type Size by 2pt T Decrease Type Size by 10pt < ( , )\n> ( . ) Cancel Operation C Play Action T Increase Type Size by 2pt T Increase Type Size by 10pt > ( . )\n/ C Layer (Group) Properties C Preset Manager C Shadow/Highlight C Shadow/Highlight (last settings) /\n\\ Select Layer Mask (Channel) Load Layer Mask as Selection Add Layer Mask Selection \\\n~ Select Composite Channel Load Composite as Selection Add Composite Selection ~\nBackspace Fill with Background Color Fill from History Fill w/ Background & Preserve Trans. Fill from History & Preserve Trans. Backspace\nReturn T Commit Changes Return\nSpace Zoom In (toggle) Space\nTab Next Document Previous Document Tab\n↑ Move Selection 1px Up Duplicate Selection 1px Up Move Selection 10px Up Duplicate Selection 10px Up ↑\n↓ Move Selection 1px Down Duplicate Selection 1px Down Move Selection 10px Down Duplicate Selection 10px Down ↓\n← Move Selection 1px Left Duplicate Selection 1px Left Move Selection 10px Left Duplicate Selection 10px Left ←\n→ Move Selection 1px Right Duplicate Selection 1px Right Move Selection 10px Right Duplicate Selection 10px Right →\nHome T Cursor to Start of Story T Select Type to Start of Story Home\nEnd T Cursor to End of Story T Select Type to End of Story End\nPageUp Scroll View Left Scroll View Left 10px PageUp\nPageDown Scroll View Right Scroll View Right 10px PageDown\n[N] New to Adobe Photoshop CS3\n[T] Only available in Type Mode\n* These represent the default keyboard shortcuts; to reverse them, enable the \"Zoom Resizes Windows\" option in the General Preferences dialog [C] Custom keyboard shortcut\n\n","author":"Trevor Morris (trevor@morris-photographics.com)","creationDate":"2007-07-07T02:27:57Z","category":"Adobe Photoshop CS3 Keyboard Shortcuts","title":"Adobe Photoshop CS3 Keyboard Shortcuts","created":"Fri Jul 06 22:27:57 EDT 2007","company":"Trevor Morris Photographics","producer":"Acrobat Distiller 8.1.0 (Windows)","comments":"Copyright ©2007, Trevor Morris (trevor@morris-photographics.com)"}
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 12439 path $.content
	at com.google.gson.Gson.fromJson(Gson.java:876) ~[gson-2.5.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:826) ~[gson-2.5.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:775) ~[gson-2.5.jar:?]
	at com.dotcms.util.marshal.MarshalFactory$GsonMarshalUtils.unmarshal(MarshalFactory.java:319) ~[MarshalFactory$GsonMarshalUtils.class:?]
	at com.dotcms.contenttype.util.KeyValueFieldUtil.JSONValueToHashMap(KeyValueFieldUtil.java:57) [KeyValueFieldUtil.class:?]
	at com.dotmarketing.portlets.structure.model.KeyValueFieldUtil.JSONValueToHashMap(KeyValueFieldUtil.java:14) [KeyValueFieldUtil.class:?]
	at com.dotmarketing.viewtools.content.ContentMap.get(ContentMap.java:256) [ContentMap.class:?]
	at com.dotmarketing.viewtools.content.ContentMap.get(ContentMap.java:104) [ContentMap.class:?]
	at sun.reflect.GeneratedMethodAccessor529.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.apache.velocity.runtime.parser.node.GetExecutor.execute(GetExecutor.java:102) [GetExecutor.class:?]
	at org.apache.velocity.util.introspection.UberspectImpl$VelGetterImpl.invoke(UberspectImpl.java:516) [UberspectImpl$VelGetterImpl.class:?]
	at org.apache.velocity.runtime.parser.node.ASTIdentifier.execute(ASTIdentifier.java:202) [ASTIdentifier.class:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285) [ASTReference.class:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:572) [ASTReference.class:?]
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:156) [ASTMethod.class:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285) [ASTReference.class:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.evaluate(ASTReference.java:535) [ASTReference.class:?]
	at org.apache.velocity.runtime.parser.node.ASTAndNode.evaluate(ASTAndNode.java:106) [ASTAndNode.class:?]
	at org.apache.velocity.runtime.parser.node.ASTExpression.evaluate(ASTExpression.java:62) [ASTExpression.class:?]
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:85) [ASTIfStatement.class:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [ASTBlock.class:?]
	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:423) [Foreach.class:?]
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:211) [ASTDirective.class:?]
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:339) [SimpleNode.class:?]
	at org.apache.velocity.Template.merge(Template.java:362) [Template.class:?]
	at org.apache.velocity.Template.merge(Template.java:265) [Template.class:?]
	at com.dotmarketing.viewtools.VelocityWebUtil.mergeTemplate(VelocityWebUtil.java:90) [VelocityWebUtil.class:?]
```

**Comment by dsilvam** [comment]
This is because of chances here: https://github.com/dotCMS/core/issues/10529. @danlaguna please check

**Comment by danlaguna** [comment]
The latest code fixes the issue in TimeMachine.

**Comment by dsilvam** [comment]
Fixed in https://github.com/dotCMS/core/issues/10529

**Comment by shaydotcms** [comment]
Passed QA. Error is not showing using Time Machine on starter
Tested on master-4.1 / commit 6caf33e8f8ba46cdf1db336e500969febdee9ee0
Mac OS 10.10 / MySQL 5.6.35 / Firefox v45.0.1 / Tomcat 8 / Java 8
