### ISSUE TITLE
Silent failure from ReindexThread

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#11444]
Silent failure from reindexThread resulting in reindex thread forever looping but not indexing or logging why it is not indexing.

## Expected Behavior
If reindexing is unable to progress, there should be something in the logs indicating why it is unable to progress.

## Current Behavior
Reindex page in the backend kept showing same percentage - no progress.  kept logging this:
```
ERROR db.HibernateUtil: ---------- DotHibernate: error on rollbackTransaction ---------------
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Can't call rollback when autocommit=true
```
Kept logging that over and over but no root cause or stacktrace to identify exactly where the failure was coming from.

Here is the origin of the exception in code:
https://github.com/dotCMS/core/blob/3.6.2/src/com/dotcms/journal/business/ESDistributedJournalFactoryImpl.java#L444
The loadObjectResults method was throwing a DotDataException which bubbles up to try block here:  https://github.com/dotCMS/core/blob/3.6.2/src/com/dotmarketing/common/reindex/ReindexThread.java#L630-L642
As you can see, this code catches the exception, rolls back the transaction, but does not log or rethrow the exception - resulting in a silent failure.

## Possible Solution
Just have the fillRemoteQ method rethrow the exception which the run method will then catch and log.

## Known Workarounds
Create a test jsp and catch the real exception and fix the root cause :-)

## Steps to Reproduce (for bugs)
Do anything to break the load_records_to_index stored procedure - delete it, change permissions whatever and then run a reindex.

If you want to recreate original issue manifesting this problem, you can run using the mysql db attached to this ticket:  https://my.dotcms.com/tickets/detail.dot?id=1a0a08a3-a880-4548-9635-56c5ed46e904

## Your Environment
* dotCMS version used: 3.6.2 but looks like a long time issue from the code
* Operating System and version: any
* Database and version: any

**Comment by danlaguna** [comment]
I have reviewed the behavior of the platform by doing the following:
1- renaming the SP
2- deleting the SP
3- removing permission to the SP

The dotCMS platform registers now the following StackTrace:
[02/05/17 11:04:32:068 CST] ERROR db.HibernateUtil: ---------- DotHibernate: error on rollbackTransaction ---------------
org.postgresql.util.PSQLException: Cannot rollback when autoCommit is enabled.
[02/05/17 11:04:32:068 CST] ERROR reindex.ReindexThread: Unable to index record
com.dotmarketing.exception.DotDataException: ERROR: function load_records_to_index(character varying, integer, integer) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 15
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:213) ~[dotcms_4.1.0_c6de0b1.jar:?]
	at com.dotmarketing.common.db.DotConnect.loadObjectResults(DotConnect.java:879) ~[dotcms_4.1.0_c6de0b1.jar:?]
	at com.dotcms.journal.business.ESDistributedJournalFactoryImpl.findContentReindexEntriesToReindex(ESDistributedJournalFactoryImpl.java:444) ~[dotcms_4.1.0_c6de0b1.jar:?]
	at com.dotmarketing.common.business.journal.DistributedJournalAPIImpl.findContentReindexEntriesToReindex(DistributedJournalAPIImpl.java:58) ~[dotcms_4.1.0_c6de0b1.jar:?]
	at com.dotmarketing.common.reindex.ReindexThread.fillRemoteQ(ReindexThread.java:660) ~[dotcms_4.1.0_c6de0b1.jar:?]
	at com.dotmarketing.common.reindex.ReindexThread.fillRemoteQ(ReindexThread.java:654) ~[dotcms_4.1.0_c6de0b1.jar:?]
	at com.dotmarketing.common.reindex.ReindexThread.run(ReindexThread.java:236) [dotcms_4.1.0_c6de0b1.jar:?]
Caused by: org.postgresql.util.PSQLException: ERROR: function load_records_to_index(character varying, integer, integer) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:273) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:82) ~[tomcat-dbcp.jar:8.0.18]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:82) ~[tomcat-dbcp.jar:8.0.18]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:605) ~[dotcms_4.1.0_c6de0b1.jar:?]
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:211) ~[dotcms_4.1.0_c6de0b1.jar:?]
	... 6 more
