### ISSUE TITLE
ClassNotFoundException when using Hazelcast Client cache provider

### ISSUE THREAD

**Issue by agomez-dotcms** [dotCMS/core#11465]
After adjustments made for Hazelcast implementation as part of #11124, following exception stack-trace was noticed after logging into dotCMS instance using Hazelcast Client cache provider. This needs to be fixed ("java.lang.ClassNotFoundException: com.liferay.portlet.admin.model.AdminConfig"):

```
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: com.liferay.portlet.admin.model.AdminConfig
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:224) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:184) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.map.impl.record.ObjectRecordFactory.newRecord(ObjectRecordFactory.java:37) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.map.impl.recordstore.AbstractRecordStore.createRecord(AbstractRecordStore.java:96) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.createRecord(DefaultRecordStore.java:75) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putInternal(DefaultRecordStore.java:790) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.set(DefaultRecordStore.java:976) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.map.impl.operation.SetOperation.run(SetOperation.java:45) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:186) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:382) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:409) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:534) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:519) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:490) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:200) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:67) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:142) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:127) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102) ~[hazelcast-all-3.8.jar:3.8]
	at ------ submitted from ------.(Unknown Source) ~[?:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:243) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.execute(AbstractPartitionMessageTask.java:78) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblock(AbstractInvocationFuture.java:239) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.andThen(AbstractInvocationFuture.java:215) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:69) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:142) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:127) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102) ~[hazelcast-all-3.8.jar:3.8]
	at ------ submitted from ------.(Unknown Source) ~[?:?]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:74) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:31) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:154) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:148) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.client.proxy.ClientMapProxy.setInternal(ClientMapProxy.java:606) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.client.proxy.NearCachedClientMapProxy.setInternal(NearCachedClientMapProxy.java:274) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.client.proxy.ClientMapProxy.set(ClientMapProxy.java:599) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.client.proxy.ClientMapProxy.set(ClientMapProxy.java:1495) ~[hazelcast-all-3.8.jar:3.8]
	at com.dotmarketing.business.cache.provider.hazelcast.AbstractHazelcastCacheProvider.put(AbstractHazelcastCacheProvider.java:55) ~[dotcms_4.1.0_999999.jar:?]
	at com.dotcms.enterprise.cache.provider.CacheProviderAPIImpl.put(CacheProviderAPIImpl.java:344) [ee_clean.jar:?]
	at com.dotmarketing.business.ChainableCacheAdministratorImpl.put(ChainableCacheAdministratorImpl.java:340) [dotcms_4.1.0_999999.jar:?]
	at com.dotmarketing.business.CacheLocator$CommitListenerCacheWrapper.put(CacheLocator.java:108) [dotcms_4.1.0_999999.jar:?]
	at com.liferay.portlet.admin.ejb.AdminConfigPool._put(AdminConfigPool.java:111) [dotcms_4.1.0_999999.jar:?]
	at com.liferay.portlet.admin.ejb.AdminConfigPool.put(AdminConfigPool.java:50) [dotcms_4.1.0_999999.jar:?]
	at com.liferay.portlet.admin.ejb.AdminConfigHBMUtil.model(AdminConfigHBMUtil.java:41) [dotcms_4.1.0_999999.jar:?]
	at com.liferay.portlet.admin.ejb.AdminConfigPersistence.findByC_T(AdminConfigPersistence.java:456) [dotcms_4.1.0_999999.jar:?]
	at com.liferay.portlet.admin.ejb.AdminConfigPersistence.findByC_T(AdminConfigPersistence.java:419) [dotcms_4.1.0_999999.jar:?]
	at com.liferay.portlet.admin.ejb.AdminConfigUtil.findByC_T(AdminConfigUtil.java:197) [dotcms_4.1.0_999999.jar:?]
	at com.liferay.portlet.admin.ejb.AdminConfigManagerImpl.getAdminConfig(AdminConfigManagerImpl.java:65) [dotcms_4.1.0_999999.jar:?]
	at com.liferay.portlet.admin.ejb.AdminConfigManagerImpl.getUserConfig(AdminConfigManagerImpl.java:201) [dotcms_4.1.0_999999.jar:?]
	at com.liferay.portlet.admin.ejb.AdminConfigManagerUtil.getUserConfig(AdminConfigManagerUtil.java:97) [dotcms_4.1.0_999999.jar:?]
	at com.liferay.portal.ejb.UserLocalManagerImpl.validate(UserLocalManagerImpl.java:662) [dotcms_4.1.0_999999.jar:?]
	at com.liferay.portal.ejb.UserLocalManagerImpl.updateUser(UserLocalManagerImpl.java:433) [dotcms_4.1.0_999999.jar:?]
	at com.liferay.portal.ejb.UserLocalManagerUtil.updateUser(UserLocalManagerUtil.java:203) [dotcms_4.1.0_999999.jar:?]
	at com.dotmarketing.business.UserFactoryLiferayImpl.saveUser(UserFactoryLiferayImpl.java:261) [dotcms_4.1.0_999999.jar:?]
	at com.dotmarketing.business.UserAPIImpl.save(UserAPIImpl.java:283) [dotcms_4.1.0_999999.jar:?]
	at com.dotcms.cms.login.LoginServiceAPIFactory$LoginServiceImpl.doAuthentication(LoginServiceAPIFactory.java:307) [dotcms_4.1.0_999999.jar:?]
	at com.dotcms.cms.login.LoginServiceAPIFactory$LoginServiceImpl.doActionLogin(LoginServiceAPIFactory.java:278) [dotcms_4.1.0_999999.jar:?]
	at com.dotcms.rest.api.v1.authentication.AuthenticationResource.authentication(AuthenticationResource.java:100) [dotcms_4.1.0_999999.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) [dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:315) [dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:297) [dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:267) [dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471) [dot.jersey-container-servlet-core-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425) [dot.jersey-container-servlet-core-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383) [dot.jersey-container-servlet-core-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336) [dot.jersey-container-servlet-core-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223) [dot.jersey-container-servlet-core-2.22.1_1.jar:?]
	at com.dotcms.rest.servlet.ReloadableServletContainer.service(ReloadableServletContainer.java:105) [dotcms_4.1.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:265) [dotcms_4.1.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.1.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.1.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:308) [dotcms_4.1.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:134) [dotcms_4.1.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_4.1.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) [dotcms_4.1.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:110) [dotcms_4.1.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.ClassNotFoundException: com.liferay.portlet.admin.model.AdminConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_102]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_102]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_102]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_102]
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:149) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:123) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.nio.IOUtil$ClassLoaderAwareObjectInputStream.resolveClass(IOUtil.java:522) ~[hazelcast-all-3.8.jar:3.8]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620) ~[?:1.8.0_102]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521) ~[?:1.8.0_102]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781) ~[?:1.8.0_102]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353) ~[?:1.8.0_102]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373) ~[?:1.8.0_102]
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:219) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:184) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.map.impl.record.ObjectRecordFactory.newRecord(ObjectRecordFactory.java:37) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.map.impl.recordstore.AbstractRecordStore.createRecord(AbstractRecordStore.java:96) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.createRecord(DefaultRecordStore.java:75) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putInternal(DefaultRecordStore.java:790) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.set(DefaultRecordStore.java:976) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.map.impl.operation.SetOperation.run(SetOperation.java:45) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:186) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:382) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:409) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:534) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:519) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:490) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:200) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:67) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:142) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:127) ~[hazelcast-all-3.8.jar:3.8]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102) ~[hazelcast-all-3.8.jar:3.8]
```

**Comment by agomez-dotcms** [comment]
PR Core: #11414
PR EE: dotCMS/enterprise-2.x#464

**Comment by shaydotcms** [comment]
Passed QA.
Exception is not found in logs when using Hazelcast Client cache provider nor Hazelcast Embedded cache provider.
Tested on dotcms 4.1.0 distribution generated from master on commit 6b1238a
Mac OS 10.10 / MySQL 5.6.35 / Firefox v45.0.1 / Tomcat 8 / Java 8
