### ISSUE TITLE
We are not updating structures via push publish 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11713]
We are having problems with the push publish process, this because we are not updating structures, when you push some content type, and after modify you try to push again, this changes are not refreshing in the receiver side. 

## Expected Behavior
We should modify the structure, every time you push it

## Current Behavior
We are not refreshing and you are unable to see changes on receiver 

## Steps to Reproduce (for bugs)
1. Login as admin
2. Create a new content type with some fields 
3. Push it 
4. Modify the structure and add some fields 
5. Try to push again 

## Your Environment
Tested on release-4.1 // Postgres // FF

**Comment by gabbydotCMS** [comment]
https://my.dotcms.com/tickets/detail.dot?id=bad11907-9e0d-4a9d-8a64-dd53cad75dfa

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/11736 and https://github.com/dotCMS/enterprise-2.x/pull/468

**Comment by bryanboza** [comment]
Tested after the last changes and now we are unable to push content types:
We have this error on log: 
```
[30/05/17 10:48:00:383 PDT] ERROR business.PublisherAPIImpl: Error Publishing Bundle: You cannot delete a fixed or read only fiedl
com.dotcms.publishing.DotPublishingException: You cannot delete a fixed or read only fiedl
	at com.dotcms.enterprise.publishing.remote.handler.ContentTypeHandler.a(SourceFile:197) ~[ee-4.1.0-SNAPSHOT.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentTypeHandler.handle(SourceFile:74) ~[ee-4.1.0-SNAPSHOT.jar:?]
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:201) [dotcms_4.1.0_c337963.jar:?]
	at com.dotcms.rest.PublishThread.run(PublishThread.java:41) [dotcms_4.1.0_c337963.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: com.dotmarketing.exception.DotDataException: You cannot delete a fixed or read only fiedl
	at com.dotcms.contenttype.business.FieldAPIImpl.lambda$delete$0(FieldAPIImpl.java:164) ~[dotcms_4.1.0_c337963.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturn(LocalTransaction.java:34) ~[dotcms_4.1.0_c337963.jar:?]
	at com.dotcms.contenttype.business.FieldAPIImpl.delete(FieldAPIImpl.java:155) ~[dotcms_4.1.0_c337963.jar:?]
	at com.dotcms.contenttype.business.FieldAPIImpl.delete(FieldAPIImpl.java:147) ~[dotcms_4.1.0_c337963.jar:?]
	at com.dotcms.contenttype.business.ContentTypeAPIImpl.lambda$save$0(ContentTypeAPIImpl.java:446) ~[dotcms_4.1.0_c337963.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturn(LocalTransaction.java:34) ~[dotcms_4.1.0_c337963.jar:?]
	at com.dotcms.contenttype.business.ContentTypeAPIImpl.save(ContentTypeAPIImpl.java:380) ~[dotcms_4.1.0_c337963.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentTypeHandler.a(SourceFile:131) ~[ee-4.1.0-SNAPSHOT.jar:?]
	... 4 more
[30/05/17 10:48:00:386 PDT] ERROR lang.String: Error Publishing: com.dotcms.publishing.DotPublishingException: You cannot delete a fixed or read only fiedl

``` 

Also the bundle fail but the same problem: https://www.screencast.com/t/wU3s5UOdS

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/11763

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11780

**Comment by oarrietadotcms** [comment]
PR for release 4.1.0: https://github.com/dotCMS/core/pull/11788
