### ISSUE TITLE
[Push Publish Bug] Error in required fields when PP

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#11717]
Error testing dotCMS Site Push Publish

Stack Trace: 
```
[25/05/17 11:03:23:055 CST]  INFO rest.PublishThread: Started bundle publish process
[25/05/17 11:03:23:091 CST]  INFO caffine.CaffineCache: ***	 Building Cache : categoryparentscache, size:1000,Concurrency:32
[25/05/17 11:03:23:097 CST]  INFO caffine.CaffineCache: ***	 Building Cache : fileassetmetadatacache, size:200,Concurrency:32
[25/05/17 11:03:23:097 CST]  INFO caffine.CaffineCache: ***	 Building Cache : htmlpagecache, size:1000,Concurrency:32
[25/05/17 11:03:23:100 CST]  INFO caffine.CaffineCache: ***	 Building Cache : hostaliascache, size:1000,Concurrency:32
[25/05/17 11:03:23:100 CST]  INFO caffine.CaffineCache: ***	 Building Cache : hostaliascache, size:1000,Concurrency:32
[25/05/17 11:03:23:100 CST]  INFO caffine.CaffineCache: ***	 Building Cache : hostaliascache, size:1000,Concurrency:32
[25/05/17 11:03:23:104 CST]  INFO caffine.CaffineCache: ***	 Building Cache : hostaliascache, size:1000,Concurrency:32
[25/05/17 11:03:23:104 CST]  INFO caffine.CaffineCache: ***	 Building Cache : hostaliascache, size:1000,Concurrency:32
[25/05/17 11:03:23:109 CST]  INFO caffine.CaffineCache: ***	 Building Cache : velocitycache, size:1000,Concurrency:32
[25/05/17 11:03:23:119 CST]  INFO caffine.CaffineCache: ***	 Building Cache : parentrulescache, size:1000,Concurrency:32
[25/05/17 11:03:23:120 CST]  INFO handler.HandlerUtil: User with ID: dotcms.org.2769 does not exist. Leaving system user as mod user
[25/05/17 11:03:23:126 CST]  INFO caffine.CaffineCache: ***	 Building Cache : hostaliascache, size:1000,Concurrency:32
[25/05/17 11:03:23:126 CST]  INFO caffine.CaffineCache: ***	 Building Cache : hostaliascache, size:1000,Concurrency:32
[25/05/17 11:03:23:126 CST]  INFO caffine.CaffineCache: ***	 Building Cache : hostaliascache, size:1000,Concurrency:32
[25/05/17 11:03:23:139 CST]  INFO caffine.CaffineCache: ***	 Building Cache : workflowstepcache, size:1000,Concurrency:32
[25/05/17 11:03:23:141 CST]  INFO caffine.CaffineCache: ***	 Building Cache : workflowactioncache, size:10000,Concurrency:32
[25/05/17 11:03:23:155 CST]  INFO caffine.CaffineCache: ***	 Building Cache : parentpermissionablecache, size:10000,Concurrency:32
[25/05/17 11:03:23:685 CST]  INFO business.ContentTypeAPIImpl: UserId : system : ContentType : ContentType saved : Documentation
[25/05/17 11:03:23:705 CST]  INFO caffine.CaffineCache: ***	 Building Cache : workflowstepcache, size:1000,Concurrency:32
[25/05/17 11:03:23:713 CST]  INFO business.ContentTypeAPIImpl: UserId : system : ContentType : ContentType saved : Comments
[25/05/17 11:03:23:715 CST]  INFO caffine.CaffineCache: ***	 Building Cache : workflowstepcache, size:1000,Concurrency:32
[25/05/17 11:03:23:716 CST]  INFO caffine.CaffineCache: ***	 Building Cache : workflowstepcache, size:1000,Concurrency:32
[25/05/17 11:03:23:738 CST]  INFO caffine.CaffineCache: ***	 Building Cache : workflowstepcache, size:1000,Concurrency:32
[25/05/17 11:03:23:739 CST] ERROR business.PublisherAPIImpl: Error Publishing Bundle: ContentType does not have the required Fields: TabDividerField{acceptedDataTypes=[system_field], dataType=system_field, searchable=false, unique=false, indexed=false, listed=false, readOnly=false, modDate=Thu May 25 11:03:24 CST 2017, name=Advanced Properties, typeName=com.dotcms.contenttype.model.field.TabDividerField, required=false, variable=advancedtab, sortOrder=8, fixed=false, iDate=Thu May 25 11:03:24 CST 2017}
com.dotcms.publishing.DotPublishingException: ContentType does not have the required Fields: TabDividerField{acceptedDataTypes=[system_field], dataType=system_field, searchable=false, unique=false, indexed=false, listed=false, readOnly=false, modDate=Thu May 25 11:03:24 CST 2017, name=Advanced Properties, typeName=com.dotcms.contenttype.model.field.TabDividerField, required=false, variable=advancedtab, sortOrder=8, fixed=false, iDate=Thu May 25 11:03:24 CST 2017}
	at com.dotcms.enterprise.publishing.remote.handler.ContentTypeHandler.handleContentTypes(ContentTypeHandler.java:193) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentTypeHandler.handle(ContentTypeHandler.java:74) ~[ee_clean.jar:?]
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:201) [dotcms_4.2.0_999999.jar:?]
	at com.dotcms.rest.PublishThread.run(PublishThread.java:41) [dotcms_4.2.0_999999.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: com.dotmarketing.exception.DotDataException: ContentType does not have the required Fields: TabDividerField{acceptedDataTypes=[system_field], dataType=system_field, searchable=false, unique=false, indexed=false, listed=false, readOnly=false, modDate=Thu May 25 11:03:24 CST 2017, name=Advanced Properties, typeName=com.dotcms.contenttype.model.field.TabDividerField, required=false, variable=advancedtab, sortOrder=8, fixed=false, iDate=Thu May 25 11:03:24 CST 2017}
	at com.dotmarketing.db.LocalTransaction.wrapReturn(LocalTransaction.java:47) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotcms.contenttype.business.ContentTypeFactoryImpl.save(ContentTypeFactoryImpl.java:208) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotcms.contenttype.business.ContentTypeAPIImpl.save(ContentTypeAPIImpl.java:233) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentTypeHandler.handleContentTypes(ContentTypeHandler.java:124) ~[ee_clean.jar:?]
	... 4 more
Caused by: com.dotmarketing.business.DotValidationException: ContentType does not have the required Fields: TabDividerField{acceptedDataTypes=[system_field], dataType=system_field, searchable=false, unique=false, indexed=false, listed=false, readOnly=false, modDate=Thu May 25 11:03:24 CST 2017, name=Advanced Properties, typeName=com.dotcms.contenttype.model.field.TabDividerField, required=false, variable=advancedtab, sortOrder=8, fixed=false, iDate=Thu May 25 11:03:24 CST 2017}
	at com.dotcms.contenttype.business.ContentTypeFactoryImpl.validateFields(ContentTypeFactoryImpl.java:673) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotcms.contenttype.business.ContentTypeFactoryImpl.lambda$save$19(ContentTypeFactoryImpl.java:214) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturn(LocalTransaction.java:34) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotcms.contenttype.business.ContentTypeFactoryImpl.save(ContentTypeFactoryImpl.java:208) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotcms.contenttype.business.ContentTypeAPIImpl.save(ContentTypeAPIImpl.java:233) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentTypeHandler.handleContentTypes(ContentTypeHandler.java:124) ~[ee_clean.jar:?]
	... 4 more
[25/05/17 11:03:23:742 CST] ERROR lang.String: Error Publishing: com.dotcms.publishing.DotPublishingException: ContentType does not have the required Fields: TabDividerField{acceptedDataTypes=[system_field], dataType=system_field, searchable=false, unique=false, indexed=false, listed=false, readOnly=false, modDate=Thu May 25 11:03:24 CST 2017, name=Advanced Properties, typeName=com.dotcms.contenttype.model.field.TabDividerField, required=false, variable=advancedtab, sortOrder=8, fixed=false, iDate=Thu May 25 11:03:24 CST 2017}
[25/05/17 11:03:23:742 CST]  INFO rest.PublishThread: Finished bundle publish process
```

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11718

**Comment by oarrietadotcms** [comment]
PR for release 4.1.0: https://github.com/dotCMS/core/pull/11719

**Comment by oarrietadotcms** [comment]
FYI: When testing we found a blocker in order to test this one: https://github.com/dotCMS/core/issues/11713#issuecomment-304956258
