### ISSUE TITLE
Content types are not pushing by dependency when you push an entire site 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11723]
The system is having an error when try to add the content types by dependencies to the bundle, to push a complete site 

## Expected Behavior
When you push an entire site, the system should be send the content types by dependency
 
## Current Behavior
We are having an error adding the content types to the bundle 
```
[25/05/17 15:48:48:118 CST] ERROR factories.StructureFactory: No value specified for parameter 6.
com.dotmarketing.exception.DotDataException: No value specified for parameter 6.
	at com.dotmarketing.db.LocalTransaction.wrapReturn(LocalTransaction.java:47) ~[dotcms_4.1.0_255852a.jar:?]
	at com.dotcms.contenttype.business.ContentTypeFactoryImpl.search(ContentTypeFactoryImpl.java:131) ~[dotcms_4.1.0_255852a.jar:?]
	at com.dotcms.contenttype.business.ContentTypeFactoryImpl.search(ContentTypeFactoryImpl.java:139) ~[dotcms_4.1.0_255852a.jar:?]
	at com.dotcms.contenttype.business.ContentTypeAPIImpl.search(ContentTypeAPIImpl.java:390) ~[dotcms_4.1.0_255852a.jar:?]
	at com.dotmarketing.portlets.structure.factories.StructureFactory.getStructuresUnderHost(StructureFactory.java:321) [dotcms_4.1.0_255852a.jar:?]
	at com.dotcms.publisher.util.DependencyManager.setHostDependencies(DependencyManager.java:418) [dotcms_4.1.0_255852a.jar:?]
	at com.dotcms.publisher.util.DependencyManager.setDependencies(DependencyManager.java:307) [dotcms_4.1.0_255852a.jar:?]
	at com.dotcms.enterprise.publishing.remote.bundler.DependencyBundler.generate(SourceFile:67) [ee-4.1.0-SNAPSHOT.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:75) [dotcms_4.1.0_255852a.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:16) [dotcms_4.1.0_255852a.jar:?]
	at com.dotcms.publisher.business.PublisherQueueJob.execute(PublisherQueueJob.java:181) [dotcms_4.1.0_255852a.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223) [dot.quartz-all-1.8.6_2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) [dot.quartz-all-1.8.6_2.jar:?]
Caused by: org.postgresql.util.PSQLException: No value specified for parameter 6.
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:178) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:246) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:273) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:82) ~[tomcat-dbcp.jar:8.0.18]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:82) ~[tomcat-dbcp.jar:8.0.18]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:605) ~[dotcms_4.1.0_255852a.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:511) ~[dotcms_4.1.0_255852a.jar:?]
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:240) ~[dotcms_4.1.0_255852a.jar:?]
	at com.dotmarketing.common.db.DotConnect.loadObjectResults(DotConnect.java:890) ~[dotcms_4.1.0_255852a.jar:?]
	at com.dotcms.contenttype.business.ContentTypeFactoryImpl.dbSearch(ContentTypeFactoryImpl.java:529) ~[dotcms_4.1.0_255852a.jar:?]
	at com.dotcms.contenttype.business.ContentTypeFactoryImpl.lambda$search$11(ContentTypeFactoryImpl.java:132) ~[dotcms_4.1.0_255852a.jar:?]
	at com.dotcms.contenttype.business.ContentTypeFactoryImpl$$Lambda$51/1328312326.call(Unknown Source) ~[?:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturn(LocalTransaction.java:34) ~[dotcms_4.1.0_255852a.jar:?]
	... 12 more
[25/05/17 15:48:48:119 CST] ERROR util.DependencyManager: No value specified for parameter 6.
com.dotmarketing.exception.DotDataException: No value specified for parameter 6.
	at com.dotmarketing.portlets.structure.factories.StructureFactory.getStructuresUnderHost(StructureFactory.java:326) ~[dotcms_4.1.0_255852a.jar:?]
	at com.dotcms.publisher.util.DependencyManager.setHostDependencies(DependencyManager.java:418) [dotcms_4.1.0_255852a.jar:?]
	at com.dotcms.publisher.util.DependencyManager.setDependencies(DependencyManager.java:307) [dotcms_4.1.0_255852a.jar:?]
	at com.dotcms.enterprise.publishing.remote.bundler.DependencyBundler.generate(SourceFile:67) [ee-4.1.0-SNAPSHOT.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:75) [dotcms_4.1.0_255852a.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:16) [dotcms_4.1.0_255852a.jar:?]
	at com.dotcms.publisher.business.PublisherQueueJob.execute(PublisherQueueJob.java:181) [dotcms_4.1.0_255852a.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223) [dot.quartz-all-1.8.6_2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) [dot.quartz-all-1.8.6_2.jar:?]
```

## Steps to Reproduce (for bugs)
1. Login as admin and configure your push environment 
2. Add a new site 
3. Add some structures to that site
4. Add some pieces of content to the created structures 
5. Try to push the entire site 

## Your Environment
Tested in the last release-4.1 // Postgres... This on both environments

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11739

**Comment by bryanboza** [comment]
Fixed, the main problems was solved, but now we have another problem related: #11748
