### ISSUE TITLE
NPE on receiver trying to push remove content types 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11721]
We are having a NPE error when you try to push remove some content type 

**FYI: THE CONTENT TYPE IS REMOVED, BUT WE SHOWS THIS ERROR...** 

## Expected Behavior
We need be able to push remove content types without errors 

## Current Behavior
We have the follow NPE error 
```
[25/05/17 13:09:30:036 PDT] ERROR util.ContentTypeUtil: An error occurred when retrieving the action URL of Content Type [79e2385b-97f7-4325-8631-6d2dea09385c] for user [system]: null
java.lang.NullPointerException
	at com.liferay.portlet.PortletURLImpl.<init>(PortletURLImpl.java:82) ~[dotcms_4.1.0_03f3610.jar:?]
	at com.dotcms.util.ContentTypeUtil.getActionUrl(ContentTypeUtil.java:155) [dotcms_4.1.0_03f3610.jar:?]
	at com.dotcms.util.ContentTypeUtil.getActionUrl(ContentTypeUtil.java:127) [dotcms_4.1.0_03f3610.jar:?]
	at com.dotcms.util.ContentTypeUtil.getActionUrl(ContentTypeUtil.java:110) [dotcms_4.1.0_03f3610.jar:?]
	at com.dotcms.contenttype.business.ContentTypeAPIImpl.delete(ContentTypeAPIImpl.java:113) [dotcms_4.1.0_03f3610.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentTypeHandler.a(SourceFile:111) [ee-4.1.0-SNAPSHOT.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentTypeHandler.handle(SourceFile:74) [ee-4.1.0-SNAPSHOT.jar:?]
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:201) [dotcms_4.1.0_03f3610.jar:?]
	at com.dotcms.rest.PublishThread.run(PublishThread.java:41) [dotcms_4.1.0_03f3610.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

## Steps to Reproduce (for bugs)
1. Login as admin and configure your push environment 
2. Create a new content type and add a text field  
3. Try to push it 
4. Now try to made a push remove of the same content type 

5. Check the log on the receiver side 

## Your Environment
Tested on the last release-4.1 // Postgres... This on both instances

**Comment by wezell** [comment]
We should not throw notifications when a content type is PP deleted.

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/11816

**Comment by bryanboza** [comment]
Fixed, tested on the last master // MySQL // FF and now we don't have the NPE
