### ISSUE TITLE
Fixing Integration Test

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11794]
Updating the mod_date of the type when every default field is saved meant that we were returning a stale object when doing a saveUpdate
Equals method was failiing
```
WidgetContentType{multilingualable=false, defaultType=false, description=description1496344192457, fixed=false, folder=SYSTEM_FOLDER, host=SYSTEM_HOST, iDate=Thu Jun 01 15:09:52 EDT 2017, id=1349e011-ffdc-474e-bf11-7bf5b65d4279, modDate=Thu Jun 01 15:09:52 EDT 2017, name=WIDGETTesting1496344192457, owner=owner, system=false, variable=velocityVarNameTesting1496344192457, versionable=true}

WidgetContentType{multilingualable=false, defaultType=false, description=description1496344192457, fixed=false, folder=SYSTEM_FOLDER, host=SYSTEM_HOST, iDate=Thu Jun 01 15:09:52 EDT 2017, id=1349e011-ffdc-474e-bf11-7bf5b65d4279, modDate=Thu Jun 01 15:09:53 EDT 2017, name=WIDGETTesting1496344192457, owner=owner, system=false, variable=velocityVarNameTesting1496344192457, versionable=true}
```

```
java.lang.AssertionError: Type saved correctly
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:26)
	at com.dotcms.contenttype.test.ContentTypeFactoryImplTest.insert(ContentTypeFactoryImplTest.java:412)
	at com.dotcms.contenttype.test.ContentTypeFactoryImplTest.testAddingUpdatingDeleteing(ContentTypeFactoryImplTest.java:279)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.GeneratedMethodAccessor667.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by dsilvam** [comment]
PR 4.1: https://github.com/dotCMS/core/pull/11795
