### ISSUE TITLE
Issue with the Ping/Pong websocket

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#11872]
Issue with the Ping/Pong websocket

An user gets this issue it seems after Integrity checker (probably not related) but could be good to take a look to the issue.

In the logs I see these: 

[12/06/17 10:57:09:062 PDT] ERROR websocket.SystemEventsWebSocketEndPoint: java.util.concurrent.ExecutionException: java.io.IOException: Key must be cancelled java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: Key must be cancelled at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessageBlock(WsRemoteEndpointImplBase.java:282) ~[tomcat-websocket.jar:8.0.18] at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPing(WsRemoteEndpointImplBase.java:174) ~[tomcat-websocket.jar:8.0.18] at org.apache.tomcat.websocket.WsRemoteEndpointBase.sendPing(WsRemoteEndpointBase.java:55) ~[tomcat-websocket.jar:8.0.18] at com.dotcms.rest.api.v1.system.websocket.SystemEventsWebSocketEndPoint.doPing(SystemEventsWebSocketEndPoint.java:116) ~[dotcms_4.1.0_999999.jar:?] at com.dotcms.rest.api.v1.system.websocket.SystemEventsWebSocketEndPoint.processPingPongQueue(SystemEventsWebSocketEndPoint.java:95) ~[dotcms_4.1.0_999999.jar:?] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121] at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_121] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_121] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121] Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Key must be cancelled at org.apache.tomcat.websocket.FutureToSendHandler.get(FutureToSendHandler.java:102) ~[tomcat-websocket.jar:8.0.18] at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessageBlock(WsRemoteEndpointImplBase.java:275) ~[tomcat-websocket.jar:8.0.18] … 11 more

**Comment by bryanboza** [comment]
As we discuss, R&D need to check this card

**Comment by jdotcms** [comment]
We already cover that!
