### ISSUE TITLE
Drop Old Assets Versions stuck after ConcurrentModificationException

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#11884]
After some attempts to run Drop Old Assets Versions, this exception is thrown:
```
[12/06/17 13:34:29:333 CDT] ERROR action.ViewCMSMaintenanceAction: java.util.ConcurrentModificationException
java.util.ConcurrentModificationException
	at java.util.ArrayList$SubList.checkForComodification(ArrayList.java:1231) ~[?:1.8.0_121]
	at java.util.ArrayList$SubList.size(ArrayList.java:1040) ~[?:1.8.0_121]
	at com.dotmarketing.business.BaseWebAssetAPI.deleteOldVersions(BaseWebAssetAPI.java:533) ~[dotcms_3.6.2_b6bb7d6.jar:?]
	at com.dotmarketing.portlets.templates.business.TemplateAPIImpl.deleteOldVersions(TemplateAPIImpl.java:515) ~[dotcms_3.6.2_b6bb7d6.jar:?]
	at com.dotmarketing.portlets.cmsmaintenance.factories.CMSMaintenanceFactory.deleteOldAssetVersions(CMSMaintenanceFactory.java:83) [dotcms_3.6.2_b6bb7d6.jar:?]
	at com.dotmarketing.portlets.cmsmaintenance.ajax.CMSMaintenanceAjax.removeOldVersions(CMSMaintenanceAjax.java:323) [dotcms_3.6.2_b6bb7d6.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule$1.doFilter(CreatorModule.java:229) [dot.dwr-3rc2modified_2.jar:?]
	at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule.executeMethod(CreatorModule.java:241) [dot.dwr-3rc2modified_2.jar:?]
	at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:379) [dot.dwr-3rc2modified_2.jar:?]
	at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:332) [dot.dwr-3rc2modified_2.jar:?]
	at com.dotcms.repackage.org.directwebremoting.dwrp.BaseCallHandler.handle(BaseCallHandler.java:104) [dot.dwr-3rc2modified_2.jar:?]
	at com.dotcms.repackage.org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:120) [dot.dwr-3rc2modified_2.jar:?]
	at com.dotcms.repackage.org.directwebremoting.servlet.DwrServlet.doPost(DwrServlet.java:141) [dot.dwr-3rc2modified_2.jar:?]
	at com.dotmarketing.servlets.DwrWrapperServlet.doPost(DwrWrapperServlet.java:60) [dotcms_3.6.2_b6bb7d6.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644) [servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:259) [dotcms_3.6.2_b6bb7d6.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61) [dotcms_3.6.2_b6bb7d6.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:308) [dotcms_3.6.2_b6bb7d6.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:130) [dotcms_3.6.2_b6bb7d6.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_3.6.2_b6bb7d6.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) [dotcms_3.6.2_b6bb7d6.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146) [dotcms_3.6.2_b6bb7d6.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
```

## Possible Solution

Replace sublist calls by a copy of the ArrayList

## Context
This issue was reported by a client running dotCMS 3.6.2. However, this enhancement would benefit future versions.
https://my.dotcms.com/tickets/detail.dot?id=80c00ccb-d224-444b-a9ae-6453e1a76dcc

## Your Environment

* dotCMS version used: dotCMS 3.6.2
* Operating System and version: Mac OSx
* Application Server and version: Tomcat 8
* Java Brand and version: JDK 1.8
* Database and version: Postgres
* Application module (if apply): Drop Old Assets Versions

**Comment by joseorsini** [comment]
For use case on customer, running 3.6.2, this was tested and we're still getting the ConcurrentModificationException on this line 

https://github.com/dotCMS/core/blob/e84cea10a86b24d8dacf0938bf1e80d564491399/dotCMS/src/main/java/com/dotmarketing/business/BaseWebAssetAPI.java#L522 

Thinking of creating a temporary list of inodes with same values from inodesToDelete list doesn't work either, despite the inodesToDelete list is not being modified on call above (only getters).

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/12012

**Comment by agomez-dotcms** [comment]
Hi Guys,

After analysis/investigation/tests, PR above (https://github.com/dotCMS/core/pull/12012/) has been updated with a [hopefully] definitive fix.

Thanks,
Anibal

**Comment by agomez-dotcms** [comment]
The fix for this issue may be found on hot-fix at https://github.com/dotCMS/support/tree/master/hotfixes/hotfix-GIT-11884_v3.6.2. Also, the original Support ticket may be accessed at https://my.dotcms.com/tickets/detail.dot?id=80c00ccb-d224-444b-a9ae-6453e1a76dcc

**Comment by DeanGonzalez** [comment]
upgraded client from a 3.3 database with over 8000 contentlets... ran drop old asset versions without error, examined content and history was fine - old versions cleared.
