### ISSUE TITLE
[Push-Publishing] Individual Contentlet fails to bundle when Host/Site lacks live version

### ISSUE THREAD

**Issue by agomez-dotcms** [dotCMS/core#11977]
After [reproducing an issue](https://my.dotcms.com/tickets/detail.dot?id=9f3204fb-255f-4900-b267-d99d20ecd466) for a client, it was found that individual contentlet was not push-published when host/site -grabbed as dependency- lacks its live version. After investigation, this problem seem to be present on latest dotCMS versions and it may be fixed by letting HostBundler to continue because it the currently can work with the working/unpublished version only. This ticket has been added to fix/track issue explained above and as documentation of hotfix for client.

## Expected Behavior
dotCMS may let host-bundler in push-publish process to work with host's working/unpublished version only

## Current Behavior
dotCMS is not currently able to push individual contentlet referencing a host/site with no live version. Instead, it throws following exception:
```
[21/06/17 13:35:14:056 EDT]  INFO ajax.RemotePublishAjaxAction: Start of Bundler: HostBundler
[21/06/17 13:35:14:057 EDT] ERROR ajax.RemotePublishAjaxAction: Error trying to generate bundle with id: 2be991f5-a97c-44cc-a0d9-66fbed116b52
com.dotcms.publishing.DotBundleException: com.dotcms.enterprise.publishing.remote.bundler.HostBundler : generate()Content error on host 75da6d25-57ad-4613-8f30-a329c853c254: Unable to pull content
	at com.dotcms.enterprise.publishing.remote.bundler.HostBundler.generate(SourceFile:163) ~[ee-3.7.0.jar:?]
	at com.dotcms.publisher.ajax.RemotePublishAjaxAction.generateBundle(RemotePublishAjaxAction.java:618) ~[dotcms_3.7.0_ded9292.jar:?]
	at com.dotcms.publisher.ajax.RemotePublishAjaxAction.downloadUnpushedBundle(RemotePublishAjaxAction.java:510) [dotcms_3.7.0_ded9292.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at com.dotcms.publisher.ajax.RemotePublishAjaxAction.service(RemotePublishAjaxAction.java:139) [dotcms_3.7.0_ded9292.jar:?]
	at com.dotmarketing.servlets.ajax.AjaxAction.doGet(AjaxAction.java:44) [dotcms_3.7.0_ded9292.jar:?]
	at com.dotmarketing.servlets.ajax.AjaxDirectorServlet.service(AjaxDirectorServlet.java:45) [dotcms_3.7.0_ded9292.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:259) [dotcms_3.7.0_ded9292.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61) [dotcms_3.7.0_ded9292.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:308) [dotcms_3.7.0_ded9292.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:130) [dotcms_3.7.0_ded9292.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_3.7.0_ded9292.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) [dotcms_3.7.0_ded9292.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146) [dotcms_3.7.0_ded9292.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:673) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: com.dotcms.publishing.DotBundleException: Content error on host 75da6d25-57ad-4613-8f30-a329c853c254
	at com.dotcms.enterprise.publishing.remote.bundler.HostBundler.generate(SourceFile:141) ~[ee-3.7.0.jar:?]
	... 57 more
Caused by: com.dotmarketing.portlets.contentlet.business.DotContentletStateException: Can't find contentlet: 75da6d25-57ad-4613-8f30-a329c853c254 lang:1 live:true
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.findContentletByIdentifier(ESContentletAPIImpl.java:279) ~[ESContentletAPIImpl.class:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.findContentletByIdentifier(ContentletAPIInterceptor.java:822) ~[dotcms_3.7.0_ded9292.jar:?]
	at com.dotcms.enterprise.publishing.remote.bundler.HostBundler.generate(SourceFile:125) ~[ee-3.7.0.jar:?]
	... 57 more
Caused by: com.dotmarketing.exception.DotHibernateException: Error loading object from Hibernate Session 
	at com.dotmarketing.db.HibernateUtil.load(HibernateUtil.java:270) ~[dotcms_3.7.0_ded9292.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.find(ESContentFactoryImpl.java:727) ~[ESContentFactoryImpl.class:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.find(ESContentletAPIImpl.java:228) ~[ESContentletAPIImpl.class:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.findContentletByIdentifier(ESContentletAPIImpl.java:271) ~[ESContentletAPIImpl.class:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.findContentletByIdentifier(ContentletAPIInterceptor.java:822) ~[dotcms_3.7.0_ded9292.jar:?]
	at com.dotcms.enterprise.publishing.remote.bundler.HostBundler.generate(SourceFile:125) ~[ee-3.7.0.jar:?]
	... 57 more
Caused by: java.lang.NullPointerException: null is not a valid identifier
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.load(SessionImpl.java:1929) ~[dot.hibernate-2.1.7_2.jar:?]
	at com.dotmarketing.db.HibernateUtil.load(HibernateUtil.java:251) ~[dotcms_3.7.0_ded9292.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.find(ESContentFactoryImpl.java:727) ~[ESContentFactoryImpl.class:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.find(ESContentletAPIImpl.java:228) ~[ESContentletAPIImpl.class:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.findContentletByIdentifier(ESContentletAPIImpl.java:271) ~[ESContentletAPIImpl.class:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.findContentletByIdentifier(ContentletAPIInterceptor.java:822) ~[dotcms_3.7.0_ded9292.jar:?]
	at com.dotcms.enterprise.publishing.remote.bundler.HostBundler.generate(SourceFile:125) ~[ee-3.7.0.jar:?]
	... 57 more
```

## Steps to Reproduce (Potential cause only reproduced on client environment/data)
1. Add Contentlet to Bundle: Contentlet used was found to reference a host lacking live version (only unpublished/working version)
2. Download for Publish Bundle

## Context
Reproduced during client tests on dotCMS 3.7.0. Reported by client on ticket: https://my.dotcms.com/tickets/detail.dot?id=9f3204fb-255f-4900-b267-d99d20ecd466

## Your Environment
* dotCMS version used: 3.7.0.
* Browser Name and version: Any Browser
* Operating System and version: Amazon Linux
* Application Server and version: Apache Tomcat
* Database and version: Postgres

**Comment by agomez-dotcms** [comment]
PR Enterprise (Master): https://github.com/dotCMS/enterprise-2.x/pull/481

**Comment by agomez-dotcms** [comment]
The fix for this issue may be found on hot-fix at https://github.com/dotCMS/support/tree/master/hotfixes/hotfix-GIT-11977_v3.7.0. Also, the original Support ticket may be accessed at https://my.dotcms.com/tickets/detail.dot?id=9f3204fb-255f-4900-b267-d99d20ecd466

**Comment by nollymar** [comment]
Test case was included on this PR: https://github.com/dotCMS/core/pull/12043

**Comment by levosgien** [comment]
Ref: https://dotcms.zendesk.com/agent/tickets/95178
