### ISSUE TITLE
“Null” error on Workflow Step using 'Delete Content' sub action

### ISSUE THREAD

**Issue by agomez-dotcms** [dotCMS/core#11971]
After [reproducing an issue](https://my.dotcms.com/tickets/detail.dot?id=c029733a-5c9c-45ad-bdd9-72ecded0f039) for a client, it was discovered that 'Delete Content' sub action on Workflow Step was not working and instead throwing a "Null" error upon clicking on corresponding Workflow Step. After investigation, this problem -that is already fixed with a null-check on WorkflowAPIImpl's fireWorkflowPostCheckin (https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/workflows/business/WorkflowAPIImpl.java#L892-L894)- needs to be hotfixed for old versions of dotCMS (in our case, 3.3.2). This ticket was only added for hotfix tracking purposes (it will be closed) since problem is already fixed on our latest versions.

## Expected Behavior
dotCMS should successfully delete content upon clicking on Workflow Step using 'Delete Content' sub-action

## Current Behavior
dotCMS is not currently able to delete content upon clicking on Workflow Step using 'Delete Content' sub-action. Instead, it is displaying "Null" error and throwing following exception:
```
[21/06/17 17:05:15:634 CST]  WARN web.ContentletWebAPIImpl: com.dotmarketing.portlets.workflows.business.DotWorkflowException
com.dotmarketing.portlets.workflows.business.DotWorkflowException
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireWorkflowPostCheckin(WorkflowAPIImpl.java:898) ~[dotcms_3.3.2_3.3.2.jar:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireWorkflowNoCheckin(WorkflowAPIImpl.java:927) ~[dotcms_3.3.2_3.3.2.jar:?]
	at com.dotmarketing.portlets.contentlet.business.web.ContentletWebAPIImpl._saveWebAsset(ContentletWebAPIImpl.java:394) [dotcms_3.3.2_3.3.2.jar:?]
	at com.dotmarketing.portlets.contentlet.business.web.ContentletWebAPIImpl.saveContent(ContentletWebAPIImpl.java:141) [dotcms_3.3.2_3.3.2.jar:?]
	at com.dotmarketing.portlets.contentlet.ajax.ContentletAjax.saveContent(ContentletAjax.java:1407) [dotcms_3.3.2_3.3.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
	at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule$1.doFilter(CreatorModule.java:229) [dot.dwr-3rc2modified_2.jar:?]
	at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule.executeMethod(CreatorModule.java:241) [dot.dwr-3rc2modified_2.jar:?]
	at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:379) [dot.dwr-3rc2modified_2.jar:?]
	at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:332) [dot.dwr-3rc2modified_2.jar:?]
	at com.dotcms.repackage.org.directwebremoting.dwrp.BaseCallHandler.handle(BaseCallHandler.java:104) [dot.dwr-3rc2modified_2.jar:?]
	at com.dotcms.repackage.org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:120) [dot.dwr-3rc2modified_2.jar:?]
	at com.dotcms.repackage.org.directwebremoting.servlet.DwrServlet.doPost(DwrServlet.java:141) [dot.dwr-3rc2modified_2.jar:?]
	at com.dotmarketing.servlets.DwrWrapperServlet.doPost(DwrWrapperServlet.java:60) [dotcms_3.3.2_3.3.2.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644) [servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:214) [dotcms_3.3.2_3.3.2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61) [dotcms_3.3.2_3.3.2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CacheImagesFilter.doFilter(CacheImagesFilter.java:47) [dotcms_3.3.2_3.3.2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:300) [dotcms_3.3.2_3.3.2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:174) [dotcms_3.3.2_3.3.2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_3.3.2_3.3.2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) [dotcms_3.3.2_3.3.2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146) [dotcms_3.3.2_3.3.2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

## Possible Solution
Null-check at https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/workflows/business/WorkflowAPIImpl.java#L892-L894

## Context
Reproduced during client tests on dotCMS 3.3.2. Reported by client on ticket: https://my.dotcms.com/tickets/detail.dot?id=c029733a-5c9c-45ad-bdd9-72ecded0f039. Seems very similar to https://github.com/dotCMS/core/issues/8124 (however, it was not possible to match the lines-of-code in reported exception stacktraces). Just for reference purposes, following are screen-shoots with configuration of Workflow Scheme used to reproduce the problem:

<img width="1439" alt="screen shot 2017-06-22 at 10 36 39 am" src="https://user-images.githubusercontent.com/22307536/27446889-40c00a3c-573c-11e7-9706-645a2cfe9b71.png">

<img width="1440" alt="screen shot 2017-06-22 at 10 37 03 am" src="https://user-images.githubusercontent.com/22307536/27446898-45b0f574-573c-11e7-8be6-9a84add2dafa.png">

<img width="1439" alt="screen shot 2017-06-22 at 10 37 27 am" src="https://user-images.githubusercontent.com/22307536/27446908-4e8a5550-573c-11e7-9338-ccb26fc4faea.png">

## Your Environment
* dotCMS version used: 3.3.2.
* Browser Name and version: Any Browser
* Operating System and version: Mac OSX
* Application Server and version: Apache Tomcat
* Database and version: MySQL

**Comment by agomez-dotcms** [comment]
The fix for this issue may be found on hot-fix at https://github.com/dotCMS/support/tree/master/hotfixes/hotfix-GIT-11971_v3.3.2. Also, the original Support ticket may be accessed at https://my.dotcms.com/tickets/detail.dot?id=c029733a-5c9c-45ad-bdd9-72ecded0f039
