### ISSUE TITLE
Error when pushing event after upgrade

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12046]
To reproduce:
Push a piece of content of type "Event" that existed in a very old (maybe even <2.x) dotCMS version where binaries fields where of type "integer" 

Error in log:
```
WARN business.FieldFactoryImpl: field db column being updated:Field Type:class com.dotcms.contenttype.model.field.FileField does not accept datatype integer:file
[03/07/17 15:45:03:281 UTC] ERROR business.PublisherAPIImpl: Error Publishing Bundle: Field Type:class com.dotcms.contenttype.model.field.FileField does not accept datatype integer:file
com.dotcms.publishing.DotPublishingException: Field Type:class com.dotcms.contenttype.model.field.FileField does not accept datatype integer:file
        at com.dotcms.enterprise.publishing.remote.handler.ContentTypeHandler.a(SourceFile:197) ~[ee-4.1.1.jar:?]
        at com.dotcms.enterprise.publishing.remote.handler.ContentTypeHandler.handle(SourceFile:74) ~[ee-4.1.1.jar:?]
        at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:201) [dotcms_4.1.1_999999.jar:?]
        at com.dotcms.rest.PublishThread.run(PublishThread.java:41) [dotcms_4.1.1_999999.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: com.dotcms.contenttype.exception.DotDataValidationException: Field Type:class com.dotcms.contenttype.model.field.FileField does not accept datatype integer:file
        at com.dotcms.contenttype.business.FieldFactoryImpl.validateDbColumn(FieldFactoryImpl.java:294) ~[dotcms_4.1.1_999999.jar:?]
        at com.dotcms.contenttype.business.FieldFactoryImpl.dbSaveUpdate(FieldFactoryImpl.java:243) ~[dotcms_4.1.1_999999.jar:?]
        at com.dotcms.contenttype.business.FieldFactoryImpl.lambda$save$3(FieldFactoryImpl.java:146) ~[dotcms_4.1.1_999999.jar:?]
        at com.dotmarketing.db.LocalTransaction.wrapReturn(LocalTransaction.java:34) ~[dotcms_4.1.1_999999.jar:?]
        at com.dotcms.contenttype.business.FieldFactoryImpl.save(FieldFactoryImpl.java:145) ~[dotcms_4.1.1_999999.jar:?]
        at com.dotcms.contenttype.business.FieldAPIImpl.save(FieldAPIImpl.java:105) ~[dotcms_4.1.1_999999.jar:?]
        at com.dotcms.contenttype.business.ContentTypeAPIImpl.lambda$save$1(ContentTypeAPIImpl.java:488) ~[dotcms_4.1.1_999999.jar:?]
        at com.dotmarketing.db.LocalTransaction.wrapReturn(LocalTransaction.java:34) ~[dotcms_4.1.1_999999.jar:?]
        at com.dotcms.contenttype.business.ContentTypeAPIImpl.save(ContentTypeAPIImpl.java:417) ~[dotcms_4.1.1_999999.jar:?]
        at com.dotcms.enterprise.publishing.remote.handler.ContentTypeHandler.a(SourceFile:131) ~[ee-4.1.1.jar:?]
```

This can be reproduced with auth data.

**Comment by jgambarios** [comment]
@wezell @dsilvam should be close this one?

**Comment by dsilvam** [comment]
This is probably still reproducible. I think it is @wezell call

**Comment by wezell** [comment]
Affects customers coming from a very old 1.7 implementation.  They need to manually update the data type on their Event File field to text in their db.
