### ISSUE TITLE
Contents: Multiple issues with CheckinWithoutVersioning method.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12173]
If the content Type where a content is updated via checkinWithoutVersioning, we present multiple issues here: 

Scenario # 1. If the content type has a binary field and it gets updated, the original reference in filesystem is NEVER deleted, so basically we have a binary field reference with two files on filesystem.

Scenario # 2. If the content type has a binary field and it's not updated (let's assume we edit a text field here), an exception is thrown and the original reference in binary field is deleted. 

## Expected Behavior

For Scenario 1: if CheckinWithoutVersioning is called and a binary field is updated, the old reference SHOULD be deleted and store the new File assigned to this field.

For Scenario 1: If checkinWithoutVersioning method is called, and there are no differences between the original reference in filesystem and the new value for Binary Fields, then re-use this value.

## Steps to Reproduce (for bugs)

Scenario 1:

1. Create a content type, called "Test Checkin" and create two fields:
    - Text field, called Title.
    - Binary Field, called File.
2. Create a new content: populate the Title field assign an image to the Binary field (let's call it "IMG_0003.jpg").
3. go to your ASSET_REAL_PATH and create a folder called "our_file", and place an image inside it. Let's call this image "0020.jpg".
4. Make a git clone of this repo: https://github.com/joseorsini/checkinWithoutVersioningBug 
5. Get the newly created content's identifier and on this line, https://github.com/joseorsini/checkinWithoutVersioningBug/blob/master/src/main/java/com/dotmarketing/osgi/hooks/ContentEditor.java#L35 paste your content identifier value. 
6. Compile the plugin and deploy it in a 4.1.1 install. Content gets updated, but if you inspect the reference in Assets folder, you'll find two images under the same path: 0020.jpg and IMG_0003.jpg

<img width="1594" alt="screen shot 2017-07-20 at 8 53 20 am" src="https://user-images.githubusercontent.com/1717110/28467039-ba46aefe-6deb-11e7-9931-fc0eaa4eb56b.png">

Scenario 2: 
1. Create a content type, called "Test Checkin" and create two fields:
    - Text field, called Title.
    - Binary Field, called File.
2. Create a new content: populate the Title field assign an image to the Binary field (let's call it "IMG_0003.jpg").
3. Make a git clone of this repo: https://github.com/joseorsini/checkinWithoutVersioningBug 
4. Get the newly created content's identifier and on this line, https://github.com/joseorsini/checkinWithoutVersioningBug/blob/master/src/main/java/com/dotmarketing/osgi/hooks/ContentEditor.java#L35 paste your content identifier value. 
5. Compile the plugin and deploy it in a 4.1.1 install. Content is not updated, and stacktrace is thrown

Stacktrace: 

```
[21/07/17 07:52:04:375 CST] ERROR business.ESContentletAPIImpl: Error occurred while processing the file:/Users/joseorsini/dotCMS/releases/4.1.1-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/e/0/e0bf882e-8e1c-4b9b-9e3e-d98f736ed74b/file/IMG_0003.jpg (No such file or directory)
com.dotmarketing.portlets.contentlet.business.DotContentletValidationException: Error occurred while processing the file:/Users/joseorsini/dotCMS/releases/4.1.1-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/e/0/e0bf882e-8e1c-4b9b-9e3e-d98f736ed74b/file/IMG_0003.jpg (No such file or directory)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:3093) [dotcms_4.1.1_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkinWithoutVersioning(ESContentletAPIImpl.java:2636) [dotcms_4.1.1_999999.jar:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkinWithoutVersioning(ContentletAPIInterceptor.java:261) [dotcms_4.1.1_999999.jar:?]
	at com.dotmarketing.osgi.hooks.ContentEditor.EditFileAsset(ContentEditor.java:62) [com.dotcms.hooks2-0.2.jar:?]
	at com.dotmarketing.osgi.hooks.Activator.start(Activator.java:32) [com.dotcms.hooks2-0.2.jar:?]
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697) [org.apache.felix.framework-5.6.2.jar:?]
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2238) [org.apache.felix.framework-5.6.2.jar:?]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2144) [org.apache.felix.framework-5.6.2.jar:?]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998) [org.apache.felix.framework-5.6.2.jar:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1253) [org.apache.felix.fileinstall-3.5.8.jar:3.5.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1225) [org.apache.felix.fileinstall-3.5.8.jar:3.5.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512) [org.apache.felix.fileinstall-3.5.8.jar:3.5.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361) [org.apache.felix.fileinstall-3.5.8.jar:3.5.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:312) [org.apache.felix.fileinstall-3.5.8.jar:3.5.8]
Caused by: java.io.FileNotFoundException: /Users/joseorsini/dotCMS/releases/4.1.1-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/e/0/e0bf882e-8e1c-4b9b-9e3e-d98f736ed74b/file/IMG_0003.jpg (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_121]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_121]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_121]
	at com.liferay.util.FileUtil.copyFile(FileUtil.java:209) ~[dotcms_4.1.1_999999.jar:?]
	at com.liferay.util.FileUtil.copyFile(FileUtil.java:142) ~[dotcms_4.1.1_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:3077) ~[dotcms_4.1.1_999999.jar:?]
	... 13 more
[21/07/17 07:52:04:385 CST] ERROR hooks.ContentEditor: Something happened - 001
com.dotmarketing.portlets.contentlet.business.DotContentletValidationException: Error occurred while processing the file:/Users/joseorsini/dotCMS/releases/4.1.1-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/e/0/e0bf882e-8e1c-4b9b-9e3e-d98f736ed74b/file/IMG_0003.jpg (No such file or directory)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:3093) ~[dotcms_4.1.1_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkinWithoutVersioning(ESContentletAPIImpl.java:2636) ~[dotcms_4.1.1_999999.jar:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkinWithoutVersioning(ContentletAPIInterceptor.java:261) ~[dotcms_4.1.1_999999.jar:?]
	at com.dotmarketing.osgi.hooks.ContentEditor.EditFileAsset(ContentEditor.java:62) [com.dotcms.hooks2-0.2.jar:?]
	at com.dotmarketing.osgi.hooks.Activator.start(Activator.java:32) [com.dotcms.hooks2-0.2.jar:?]
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697) [org.apache.felix.framework-5.6.2.jar:?]
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2238) [org.apache.felix.framework-5.6.2.jar:?]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2144) [org.apache.felix.framework-5.6.2.jar:?]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998) [org.apache.felix.framework-5.6.2.jar:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1253) [org.apache.felix.fileinstall-3.5.8.jar:3.5.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1225) [org.apache.felix.fileinstall-3.5.8.jar:3.5.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512) [org.apache.felix.fileinstall-3.5.8.jar:3.5.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361) [org.apache.felix.fileinstall-3.5.8.jar:3.5.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:312) [org.apache.felix.fileinstall-3.5.8.jar:3.5.8]
Caused by: java.io.FileNotFoundException: /Users/joseorsini/dotCMS/releases/4.1.1-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/e/0/e0bf882e-8e1c-4b9b-9e3e-d98f736ed74b/file/IMG_0003.jpg (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_121]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_121]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_121]
	at com.liferay.util.FileUtil.copyFile(FileUtil.java:209) ~[dotcms_4.1.1_999999.jar:?]
	at com.liferay.util.FileUtil.copyFile(FileUtil.java:142) ~[dotcms_4.1.1_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:3077) ~[dotcms_4.1.1_999999.jar:?]
	... 13 more
```

If you make an ls where the file was supposed to be located, nothing is found, meaning the asset was deleted from filesystem

```
JoseMa-MacBook-Pro:4.1.1-dist joseorsini$ ls /Users/joseorsini/dotCMS/releases/4.1.1-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/e/0/e0bf882e-8e1c-4b9b-9e3e-d98f736ed74b/file/IMG_0003.jpg
ls: /Users/joseorsini/dotCMS/releases/4.1.1-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/e/0/e0bf882e-8e1c-4b9b-9e3e-d98f736ed74b/file/IMG_0003.jpg: No such file or directory
```

## Context
Reproduced in dotCMS 3.6.2 and 4.1.1, as reported by customer: https://my.dotcms.com/tickets/detail.dot?id=438b1d1c-4dfe-461b-83c7-17bd362758e8

## Your Environment

* dotCMS 3.6.2, 4.1.1.
* Any Browser.
* Any OS.
* Any Application Server.
* Java 8u121.
* Any DB.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/12247

**Comment by joseorsini** [comment]
Test fails on Windows. Scenario 001 described on this ticket:

- Sets the original value to a zero-byte file.
- New file assigned to binary field is not updated.

This happens only on Windows. Tests on Linux/Mac work fine. 

@dsilvam thoughts on how to improve this? https://github.com/dotCMS/core/pull/12247/files#diff-0e42bc8d57cb229663e56b48259b767dR3108 On this scenario, the original file is deleted on Linux, but doesn't seem to work on Windows. 

Tested on 3.6.2 after customer reported issues with provided fix.

**Comment by dsilvam** [comment]
New PR https://github.com/dotCMS/core/pull/12352
