### ISSUE TITLE
[Oracle] Problems deleting Text Area field from Content-Type against Oracle

### ISSUE THREAD

**Issue by agomez-dotcms** [dotCMS/core#12212]
As part of a [client request](https://my.dotcms.com/tickets/detail.dot?id=c12e87c8-c89c-404e-bba0-c2e12028bd55), **dotCMS 3.7.1 is unable to delete a Text Area field from any Content Type against Oracle** because of error when clearing field. After investigation, it was noticed that, even this error is not present in latest versions of dotCMS (4.1.1), but **it was fixed in the wrong way**. Hence, this ticket has been added to fix/track issue in latest versions of the product and as documentation of hotfix for client (in dotCMS 3.7.1).

## Expected Behavior
dotCMS should allow deletion of Text Area fields against Oracle. [SQL query generated as part of field cleaning](https://github.com/dotCMS/core/blob/4.1.1/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentFactoryImpl.java#L2375) should look like:
```
SELECT inode FROM contentlet  WHERE structure_inode = 'd35a514e-216f-493e-a734-9aea312d2d8d' AND (text_area1 IS NOT NULL AND TO_CHAR(text_area1) != '')
```

[Source-code to generate SQL query for field cleaning](https://github.com/dotCMS/core/blob/4.1.1/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentFactoryImpl.java#L2419) should look like:
```
public Queries getQueries(Field field) {
   ...
   if (isFloatField) {
      ...
   } else {
      ...
      if ( field.getFieldContentlet().contains("text_area") ) {
         ...
         } else if ( DbConnectionFactory.isOracle() ) {
            whereField.append("TO_CHAR(").append(field.getFieldContentlet()).append(") != ");      //<------------- PLEASE NOTE CALL TO TO_CHAR FUNCTION
         } ...
      }
      ...
   }
   ...
}
```

## Current Behavior
dotCMS 4.1.1 is allowing deletion of Text Area fields but with wrong query for field cleaning. SQL query currently looks like:
```
SELECT inode FROM contentlet  WHERE structure_inode = 'd35a514e-216f-493e-a734-9aea312d2d8d' AND (text_area1 IS NOT NULL AND 'text_area1' != '')
```

dotCMS 3.7.a does not allow deletion of Text Area fields. Instead, it throws following error:
```
[26/07/17 11:56:58:764 CST] ERROR job.DeleteFieldJob: Unable to delete field 'myTextareaField'. Field Inode: 2903704e-5bef-4f83-ae8f-94dfdb97303d, Structure Inode: d35a514e-216f-493e-a734-9aea312d2d8d
com.dotmarketing.exception.DotDataException: Error Clearing Field 'myTextareaField' for Structure with id: d35a514e-216f-493e-a734-9aea312d2d8d
	at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.clearField(ESContentFactoryImpl.java:2293) ~[dotcms_3.7.1_8d1e90a.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.cleanField(ESContentletAPIImpl.java:845) ~[dotcms_3.7.1_8d1e90a.jar:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.cleanField(ContentletAPIInterceptor.java:385) ~[dotcms_3.7.1_8d1e90a.jar:?]
	at com.dotmarketing.quartz.job.DeleteFieldJob.execute(DeleteFieldJob.java:116) [dotcms_3.7.1_8d1e90a.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223) [dot.quartz-all-1.8.6_2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) [dot.quartz-all-1.8.6_2.jar:?]
Caused by: java.sql.SQLException: ORA-00932: inconsistent datatypes: expected - got NCLOB
	at oracle.jdbc.driver.SQLStateMapping.newSQLException(SQLStateMapping.java:74) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
	at oracle.jdbc.driver.DatabaseError.newSQLException(DatabaseError.java:110) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:171) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:455) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:413) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:1030) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:194) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:785) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
	at oracle.jdbc.driver.T4CPreparedStatement.executeMaybeDescribe(T4CPreparedStatement.java:860) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1186) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3381) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3425) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1202) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:82) ~[tomcat-dbcp.jar:8.0.18]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:82) ~[tomcat-dbcp.jar:8.0.18]
	at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.clearField(ESContentFactoryImpl.java:2275) ~[dotcms_3.7.1_8d1e90a.jar:?]
	... 5 more
```

## Steps to Reproduce
1. Log into dotCMS Back-End as Administrator user
2. Add Text Area field to new or existing Content-Type
3. Delete Text Area field from corresponding Content Type
4. Look at error in Logs (3.7.1) or Look at generated SQL query in Debugger (4.1.1)

## Context
Reproduced during client tests on dotCMS 3.7.1. Reported by client on ticket: https://my.dotcms.com/tickets/detail.dot?id=c12e87c8-c89c-404e-bba0-c2e12028bd55

## Your Environment
* dotCMS version used: 3.7.1.
* Browser Name and version: Any Browser
* Operating System and version: Any OS
* Application Server and version: Apache Tomcat
* Database and version: Oracle 11g Express Edition

**Comment by agomez-dotcms** [comment]
PR for Master: https://github.com/dotCMS/core/pull/12213

**Comment by agomez-dotcms** [comment]
A hotfix for this issue (targeting dotCMS 3.7.1) may be found on https://github.com/dotCMS/support/tree/master/hotfixes/hotfix-GIT-12212_v3.7.1. Also, the original Support ticket may be accessed at https://my.dotcms.com/tickets/detail.dot?id=c12e87c8-c89c-404e-bba0-c2e12028bd55
