### ISSUE TITLE
Hazelcast: avoid NPE at init time.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12364]
As per this stacktrace on catalina.out file

```
14-Aug-2017 16:36:09.792 WARNING [hz._hzInstance_1_dev.event-1] com.hazelcast.spi.EventService.null [10.196.74.45]:5701 [dev] [3.8] Error while logging processing event
 java.lang.NullPointerException
    at com.dotcms.cache.transport.AbstractHazelcastCacheTransport.receive(AbstractHazelcastCacheTransport.java:99)
    at com.dotcms.cache.transport.AbstractHazelcastCacheTransport$1.onMessage(AbstractHazelcastCacheTransport.java:64)
    at com.hazelcast.topic.impl.TopicService.dispatchEvent(TopicService.java:135)
    at com.hazelcast.spi.impl.eventservice.impl.EventProcessor.process(EventProcessor.java:48)
    at com.hazelcast.spi.impl.eventservice.impl.RemoteEventProcessor.run(RemoteEventProcessor.java:36)
    at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:221)
    at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:204)

14-Aug-2017 16:36:09.794 SEVERE [hz._hzInstance_1_dev.event-1] com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.null [10.196.74.45]:5701 [dev] [3.8] hz._hzInstance_1_dev.event-1 caught an exception while processing task:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@300ef4b4
 java.lang.NullPointerException
    at com.dotcms.cache.transport.AbstractHazelcastCacheTransport.receive(AbstractHazelcastCacheTransport.java:99)
    at com.dotcms.cache.transport.AbstractHazelcastCacheTransport$1.onMessage(AbstractHazelcastCacheTransport.java:64)
    at com.hazelcast.topic.impl.TopicService.dispatchEvent(TopicService.java:135)
    at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:56)
    at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:221)
    at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:204)
```

It seems that this code https://github.com/dotCMS/core/blob/67371d2759506de60b7fdc312cdf6ec1d780699d/dotCMS/src/main/java/com/dotcms/cache/transport/AbstractHazelcastCacheTransport.java#L99 may need an improvement in order to avoid a NPE.

## Context
Reported by customer: https://my.dotcms.com/tickets/detail.dot?id=1ccdf93a-4013-4c51-94d3-a1664e6f149b

## Your Environment

* dotCMS 4.1.1.
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any App server.
* Java Brand and version: Java 8u121.
* Database and version: Any DB.
* Application module (if apply): N/A.

**Comment by jgambarios** [comment]
PRs: 
https://github.com/dotCMS/enterprise-2.x/pull/517
https://github.com/dotCMS/core/pull/12428

**Comment by bryanboza** [comment]
Fixed, tested on the last master // MySQL
