### ISSUE TITLE
Error when Push-Remove folder with multilang page

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12461]
Push remove folder with multilang page under it gives the following stack:

```
[30/08/17 08:45:03:467 PDT]  INFO db.DotConnect: Executing delete from multi_tree where child in (‘00edd2f2-8fe9-4583-a0f6-d3818d487231’) or parent1 in (‘00edd2f2-8fe9-4583-a0f6-d3818d487231’) or parent2 in (‘00edd2f2-8fe9-4583-a0f6-d3818d487231’)
[30/08/17 08:45:03:485 PDT] ERROR business.FolderAPI: No version info. Call setWorking first b110b7d6-22bf-4e87-83ed-2a33ba79476e
com.dotmarketing.business.DotStateException: No version info. Call setWorking first b110b7d6-22bf-4e87-83ed-2a33ba79476e
    at com.dotmarketing.business.VersionableAPIImpl.isLive(VersionableAPIImpl.java:183) ~[dotcms_project-8-license_23540a1.jar:?]
    at com.dotmarketing.portlets.contentlet.model.Contentlet.isLive(Contentlet.java:369) ~[dotcms_project-8-license_23540a1.jar:?]
    at com.dotmarketing.portlets.folders.business.FolderAPIImpl._deleteChildrenAssetsFromFolder(FolderAPIImpl.java:466) [dotcms_project-8-license_23540a1.jar:?]
    at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete(FolderAPIImpl.java:386) [dotcms_project-8-license_23540a1.jar:?]
    at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete(FolderAPIImpl.java:378) [dotcms_project-8-license_23540a1.jar:?]
    at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.a(SourceFile:85) [ee-project-8-license-SNAPSHOT.jar:?]
    at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.a(SourceFile:125) [ee-project-8-license-SNAPSHOT.jar:?]
    at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.handle(SourceFile:80) [ee-project-8-license-SNAPSHOT.jar:?]
    at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:202) [dotcms_project-8-license_23540a1.jar:?]
    at com.dotcms.rest.PublishThread.run(PublishThread.java:41) [dotcms_project-8-license_23540a1.jar:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
[30/08/17 08:45:03:656 PDT] ERROR business.PublisherAPIImpl: Error Publishing Bundle: No version info. Call setWorking first b110b7d6-22bf-4e87-83ed-2a33ba79476e
com.dotcms.publishing.DotPublishingException: No version info. Call setWorking first b110b7d6-22bf-4e87-83ed-2a33ba79476e
    at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.a(SourceFile:230) ~[ee-project-8-license-SNAPSHOT.jar:?]
    at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.handle(SourceFile:80) ~[ee-project-8-license-SNAPSHOT.jar:?]
    at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:202) [dotcms_project-8-license_23540a1.jar:?]
    at com.dotcms.rest.PublishThread.run(PublishThread.java:41) [dotcms_project-8-license_23540a1.jar:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: com.dotmarketing.exception.DotDataException: No version info. Call setWorking first b110b7d6-22bf-4e87-83ed-2a33ba79476e
    at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete(FolderAPIImpl.java:447) ~[dotcms_project-8-license_23540a1.jar:?]
    at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.a(SourceFile:85) ~[ee-project-8-license-SNAPSHOT.jar:?]
    at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.a(SourceFile:125) ~[ee-project-8-license-SNAPSHOT.jar:?]
    ... 4 more
Caused by: com.dotmarketing.exception.DotDataException: No version info. Call setWorking first b110b7d6-22bf-4e87-83ed-2a33ba79476e
    at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete(FolderAPIImpl.java:447) ~[dotcms_project-8-license_23540a1.jar:?]
    at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete(FolderAPIImpl.java:378) ~[dotcms_project-8-license_23540a1.jar:?]
    at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.a(SourceFile:85) ~[ee-project-8-license-SNAPSHOT.jar:?]
    at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.a(SourceFile:125) ~[ee-project-8-license-SNAPSHOT.jar:?]
    ... 4 more
Caused by: com.dotmarketing.business.DotStateException: No version info. Call setWorking first b110b7d6-22bf-4e87-83ed-2a33ba79476e
    at com.dotmarketing.portlets.folders.business.FolderAPIImpl._deleteChildrenAssetsFromFolder(FolderAPIImpl.java:517) ~[dotcms_project-8-license_23540a1.jar:?]
    at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete(FolderAPIImpl.java:386) ~[dotcms_project-8-license_23540a1.jar:?]
    at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete(FolderAPIImpl.java:378) ~[dotcms_project-8-license_23540a1.jar:?]
    at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.a(SourceFile:85) ~[ee-project-8-license-SNAPSHOT.jar:?]
    at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.a(SourceFile:125) ~[ee-project-8-license-SNAPSHOT.jar:?]
    ... 4 more
```

Affected page properties looked like this:

![multilang_page](https://user-images.githubusercontent.com/1576794/29882629-3c7c1e9e-8d73-11e7-9bba-9c1ebb16f2e8.png)

**Comment by erickgonzalez** [comment]
This was tested with the client's data set and was unsuccessfully reproduced. These were the steps that were tested:
1- Startup a Sender with client data set.
2- Startup a Receiver with a fresh install.
3- Apply licenses and conf PP.
4- Search a page that has versions in diff lang.
5- Push Publish that page.
5.1- Select Push-Remove option
5.2- Select Push option, give the system a couple of mins, Select Remove option.

On both scenarios, the push and then remove was successful.

**Comment by dsilvam** [comment]
Let's also retest this with the new dataset from support

**Comment by erickgonzalez** [comment]
Retested with client's new dataset and still unable to reproduce.
