### ISSUE TITLE
Folder fails to delete if content type is in it

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12507]
If you have a content type created in a folder and then try to delete the folder, the folder fails to delete. We should move the content type to system folder before deleting OR delete the content type.
1. Create a folder called test
2. Create a new a content type and select it as the host folder for the new content type.
3. try to delete folder

I believe we have the same issues with deleting hosts with a content type in them. 

**Log info:** https://gist.github.com/nollymar/5240416c2068d82fbb8f7a699ee0d262

**Comment by wezell** [comment]
This is still an issue, at least in MySQL

**Comment by wezell** [comment]
```
RROR 2017-12-06 10:49:30,760 com.dotcms.repackage.net.sf.hibernate.util.JDBCExceptionReporter:logExceptions(58): Cannot delete or update a parent row: a foreign key constraint fails (`dotcms`.`structure`, CONSTRAINT `fk_structure_folder` FOREIGN KEY (`folder`) REFERENCES `folder` (`inode`))
ERROR 2017-12-06 10:49:30,760 com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl:execute(2400): Could not synchronize database state with session
WARN  2017-12-06 10:49:30,762 com.dotmarketing.portlets.folders.action.EditFolderAction:warn(194): com.dotmarketing.exception.DotDataException: Error deleting object could not delete: [com.dotmarketing.portlets.folders.model.Folder#77f33776-2480-41b9-8696-0e24aeba47cd]
com.dotmarketing.exception.DotDataException: Error deleting object could not delete: [com.dotmarketing.portlets.folders.model.Folder#77f33776-2480-41b9-8696-0e24aeba47cd]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete_aroundBody22(FolderAPIImpl.java:439) ~[FolderAPIImpl.class:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl$AjcClosure23.run(FolderAPIImpl.java:1) ~[FolderAPIImpl$AjcClosure23.class:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[AspectJDelegateMethodInvocation.class:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:39) ~[LocalTransaction.class:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[WrapInTransactionMethodInterceptor.class:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[WrapInTransactionAspect.class:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete(FolderAPIImpl.java:328) ~[FolderAPIImpl.class:?]
	at com.dotmarketing.portlets.folders.action.EditFolderAction._deleteFolder(EditFolderAction.java:467) ~[EditFolderAction.class:?]
	at com.dotmarketing.portlets.folders.action.EditFolderAction.processAction(EditFolderAction.java:146) [EditFolderAction.class:?]
	at com.liferay.portal.struts.PortletRequestProcessor.process(PortletRequestProcessor.java:128) [PortletRequestProcessor.class:?]
	at com.liferay.portlet.StrutsPortlet.processAction(StrutsPortlet.java:116) [StrutsPortlet.class:?]
	at com.liferay.portlet.CachePortlet.processAction(CachePortlet.java:130) [CachePortlet.class:?]
	at com.liferay.portal.action.LayoutAction._processPortletRequest(LayoutAction.java:232) [LayoutAction.class:?]
	at com.liferay.portal.action.LayoutAction._processActionRequest(LayoutAction.java:249) [LayoutAction.class:?]
	at com.liferay.portal.action.LayoutAction.execute(LayoutAction.java:93) [LayoutAction.class:?]
	at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:421) [dot.struts-1.2.4_2.jar:1.2.4]
	at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:226) [dot.struts-1.2.4_2.jar:1.2.4]
	at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:128) [PortalRequestProcessor.class:?]
	at com.dotcms.repackage.org.apache.struts.action.ActionServlet.process(ActionServlet.java:1164) [dot.struts-1.2.4_2.jar:1.2.4]
	at com.dotcms.repackage.org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:397) [dot.struts-1.2.4_2.jar:1.2.4]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618) [servlet-api.jar:?]
	at com.liferay.portal.servlet.MainServlet.callParentService(MainServlet.java:251) [MainServlet.class:?]
	at com.liferay.portal.servlet.MainServlet.service(MainServlet.java:440) [MainServlet.class:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.repackage.com.liferay.filters.secure.SecureFilter.doFilter(SecureFilter.java:135) [dot.secure-filter-ukv_2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:200) [CMSFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [AbstractWebInterceptorSupportFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [AbstractWebInterceptorSupportFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:325) [URLMapFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:110) [VanityURLFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:132) [TimeMachineFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [ThreadNameFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:38) [CookiesFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:108) [CharsetEncodingFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: com.dotmarketing.exception.DotHibernateException: Error deleting object could not delete: [com.dotmarketing.portlets.folders.model.Folder#77f33776-2480-41b9-8696-0e24aeba47cd]
	at com.dotmarketing.db.HibernateUtil.delete(HibernateUtil.java:244) ~[HibernateUtil.class:?]
	at com.dotmarketing.portlets.folders.business.FolderFactoryImpl.delete(FolderFactoryImpl.java:82) ~[FolderFactoryImpl.class:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete_aroundBody22(FolderAPIImpl.java:409) ~[FolderAPIImpl.class:?]
	... 79 more
Caused by: com.dotcms.repackage.net.sf.hibernate.exception.GenericJDBCException: could not delete: [com.dotmarketing.portlets.folders.model.Folder#77f33776-2480-41b9-8696-0e24aeba47cd]
	at com.dotcms.repackage.net.sf.hibernate.exception.ErrorCodeConverter.handledNonSpecificException(ErrorCodeConverter.java:90) ~[dot.hibernate-2.1.7_2.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.exception.ErrorCodeConverter.convert(ErrorCodeConverter.java:79) ~[dot.hibernate-2.1.7_2.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:29) ~[dot.hibernate-2.1.7_2.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.persister.AbstractEntityPersister.convert(AbstractEntityPersister.java:1331) ~[dot.hibernate-2.1.7_2.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.persister.NormalizedEntityPersister.delete(NormalizedEntityPersister.java:595) ~[dot.hibernate-2.1.7_2.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.impl.ScheduledDeletion.execute(ScheduledDeletion.java:29) ~[dot.hibernate-2.1.7_2.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.execute(SessionImpl.java:2449) ~[dot.hibernate-2.1.7_2.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.executeAll(SessionImpl.java:2435) ~[dot.hibernate-2.1.7_2.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.execute(SessionImpl.java:2397) ~[dot.hibernate-2.1.7_2.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.flush(SessionImpl.java:2261) ~[dot.hibernate-2.1.7_2.jar:?]
	at com.dotmarketing.db.HibernateUtil.delete(HibernateUtil.java:242) ~[HibernateUtil.class:?]
	at com.dotmarketing.portlets.folders.business.FolderFactoryImpl.delete(FolderFactoryImpl.java:82) ~[FolderFactoryImpl.class:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete_aroundBody22(FolderAPIImpl.java:409) ~[FolderAPIImpl.class:?]
	... 79 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`dotcms`.`structure`, CONSTRAINT `fk_structure_folder` FOREIGN KEY (`folder`) REFERENCES `folder` (`inode`))
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_112]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_112]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_112]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.37-bin.jar:5.1.37]
	at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[mysql-connector-java-5.1.37-bin.jar:5.1.37]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934) ~[mysql-connector-java-5.1.37-bin.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870) ~[mysql-connector-java-5.1.37-bin.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806) ~[mysql-connector-java-5.1.37-bin.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470) ~[mysql-connector-java-5.1.37-bin.jar:5.1.37]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617) ~[mysql-connector-java-5.1.37-bin.jar:5.1.37]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550) ~[mysql-connector-java-5.1.37-bin.jar:5.1.37]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[mysql-connector-java-5.1.37-bin.jar:5.1.37]

```

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/13184

**Comment by DeanGonzalez** [comment]
Documented: https://auth.dotcms.com/docs/latest/deleting-a-folder,
https://auth.dotcms.com/docs/latest/deactivate-delete-sites

**Comment by dsilvam** [comment]
Note to Doc: by looking at the changes in code, the content type is always moved to system_folder, instead of the nearest parent.
