### ISSUE TITLE
We need a startup task to delete this for upgrading clients

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12624]
```
INFO  2017-09-19 17:48:26,636 com.dotmarketing.quartz.DotJobStore:info(260): ClusterManager: Scanning for instance "cc804b45-4199-43f0-83cd-1938d15b70bc"'s failed in-progress jobs.
INFO  2017-09-19 17:48:26,638 com.dotmarketing.quartz.DotJobStore:info(260): ClusterManager: ......Freed 1 acquired trigger(s).
ERROR 2017-09-19 17:48:26,643 com.dotmarketing.quartz.DotJobStore:error(528): MisfireHandler: Error handling misfires: Couldn't store trigger 'trigger23' for 'RemoveInactiveClusterServerJob' job:com.dotmarketing.quartz.job.DeleteInactiveClusterServersJob
org.quartz.JobPersistenceException: Couldn't store trigger 'trigger23' for 'RemoveInactiveClusterServerJob' job:com.dotmarketing.quartz.job.DeleteInactiveClusterServersJob
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1270) ~[dot.quartz-all-1.8.6_2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doUpdateOfMisfiredTrigger(JobStoreSupport.java:1038) ~[dot.quartz-all-1.8.6_2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.recoverMisfiredJobs(JobStoreSupport.java:982) ~[dot.quartz-all-1.8.6_2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3150) ~[dot.quartz-all-1.8.6_2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3923) [dot.quartz-all-1.8.6_2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:3943) [dot.quartz-all-1.8.6_2.jar:?]
Caused by: java.lang.ClassNotFoundException: com.dotmarketing.quartz.job.DeleteInactiveClusterServersJob
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1305) ~[catalina.jar:8.0.18]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157) ~[catalina.jar:8.0.18]
	at org.quartz.simpl.InitThreadContextClassLoadHelper.loadClass(InitThreadContextClassLoadHelper.java:72) ~[dot.quartz-all-1.8.6_2.jar:?]
```

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/12708

**Comment by jcastro-dotcms** [comment]
Fixing incorrect table names. PR: https://github.com/dotCMS/core/pull/12714

**Comment by bryanboza** [comment]
Fixed, tested upgrading to the last master // postgres
