### ISSUE TITLE
Seeing this on normal startup - not first time startup

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12681]
```
DEBUG: WIRE: [org.apache.felix.http.bundle [8](R 8.0)] osgi.wiring.package; (osgi.wiring.package=org.xml.sax.helpers) -> [org.apache.felix.framework [0](R 0)]
DEBUG: WIRE: [org.apache.felix.http.bundle [8](R 8.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.7)) -> [org.apache.felix.framework [0](R 0)]
[INFO] Started bridged http service
DEBUG: WIRE: [osgi.core [10](R 10.0)] osgi.wiring.package; (osgi.wiring.package=javax.security.auth.x500) -> [org.apache.felix.framework [0](R 0)]
INFO  2017-09-27 12:06:15,955 com.dotmarketing.util.OSGIUtil:info(58): osgi felix framework started
Sep 27, 2017 12:06:18 PM org.apache.tomcat.jdbc.pool.ConnectionPool abandon
WARNING: Connection has been abandoned PooledConnection[com.mysql.jdbc.JDBC4Connection@32c68d87]:java.lang.Exception
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getThreadDump(ConnectionPool.java:1052)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:768)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:617)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:186)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:127)
	at org.apache.tomcat.jdbc.pool.DataSource.getConnection(DataSource.java)
	at com.dotmarketing.db.DbConnectionFactory.getConnection(DbConnectionFactory.java:129)
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:513)
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:244)
	at com.dotmarketing.common.db.DotConnect.loadObjectResults(DotConnect.java:897)
	at com.dotcms.enterprise.cluster.ServerFactoryImpl.getAliveServers(ServerFactoryImpl.java:195)
	at com.dotcms.cluster.business.ServerAPIImpl.getAliveServers(ServerAPIImpl.java:180)
	at com.dotmarketing.business.ChainableCacheAdministratorImpl.setCluster(ChainableCacheAdministratorImpl.java:140)
	at com.dotcms.enterprise.cluster.ClusterFactory.lambda$0(ClusterFactory.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

INFO  2017-09-27 12:06:19,588 com.dotmarketing.business.cache.provider.caffine.CaffineCache:info(58): ***	 Building Cache : hostcache, size:1000,Concurrency:32

```

My context.xml
```
	<!-- MYSQL UTF8 -->
<Resource name="jdbc/dotCMSPool" auth="Container"
	type="javax.sql.DataSource" 
	driverClassName="${mysql.db.driver}"
	factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
	url="${mysql.db.base.url}" 
	username="${mysql.db.username}" 
	password="${mysql.db.password}" 
	minIdle="5"
	validationQuery="SELECT 1"
	testOnBorrow="true"
	maxWaitMillis="1000" 
	removeAbandoned="true"
	removeAbandonedTimeout="30"
    logAbandoned="true" 
/>
```

**Comment by wezell** [comment]
Build environment issue - needed to add the aspectj nature to my project.
