### ISSUE TITLE
Need fix the parent folder by dependency when you fix a html page conflict 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12765]
When you have a conflict with a folder and some page in to this folder, if you fix the page conflict, by dependency we should fix the parent folder conflict. 

This to avoid made the fix and try to push, and still having problems with the parent folder 

## Expected Behavior
We need fix the parent folder by dependency when you fix the html page conflict 

## Current Behavior
We fix just the html page conflict, but if after fix you try to push this page, we still having an error because the parent folder have a different identifier 

Log
```
[04/10/17 16:35:00:828 CST] ERROR business.PublisherAPIImpl: Error Publishing Bundle: Conflicts between Folders. Folder with path : '/bryan/' has different Inodes at sender and receiver. Please run the Integrity Checker at sender.
com.dotcms.publishing.DotPublishingException: Conflicts between Folders. Folder with path : '/bryan/' has different Inodes at sender and receiver. Please run the Integrity Checker at sender.
	at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.a(SourceFile:232) ~[ee-4.2.0-SNAPSHOT.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.handle(SourceFile:79) ~[ee-4.2.0-SNAPSHOT.jar:?]
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:205) [dotcms_4.2.0_ce0b2a2.jar:?]
	at com.dotcms.rest.PublishThread.run(PublishThread.java:41) [dotcms_4.2.0_ce0b2a2.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: com.dotmarketing.exception.DotDataException: Conflicts between Folders. Folder with path : '/bryan/' has different Inodes at sender and receiver. Please run the Integrity Checker at sender.
	at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.a(SourceFile:214) ~[ee-4.2.0-SNAPSHOT.jar:?]
	... 4 more

```

## Steps to Reproduce (for bugs)
1. Configure your push environment 
2. On both environments (sender and receiver) create a new folder and a new page into it with the same name. 
3. Run the integrity checker 
4. Try to fix the page conflicts on remote node 
5. Try to push publish the page 

## Your Environment
Tested on master // postgres // FF. This on both environments

**Comment by jgambarios** [comment]
Not a but, the Integrity checker don't search for conflicts on dependencies when fixing a conflict, if it is required to fix the folder conflict you should apply the fix on the folder (Folders tab) using also the Integrity Checker.
