### ISSUE TITLE
Unable to start master on Windows 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12805]
We are having an ilegal character on the script, then we are having an error trying to start 

## Expected Behavior
We should be able to start dotCMS on Windows without problems

## Current Behavior
We are having an ilegal exceptions and never starts 

Here the log: https://gist.github.com/bryanboza/a3a1e5e8e1881a8ebb3f5b6b27575d41

## Your Environment
Tested with the last nightly build // H2 // chrome

**Comment by john-thomas-dotcms** [comment]
I'm running Win 7 Enterprise, and I also can't start master (or the release-4.2 nightly), but I have different symptoms.

## Symptoms on my System

* The Tomcat console stops at the message "09-Oct-2017 13:40:24.307 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 136014 ms".
* There are no error messages in the dotCMS logs at all.
* Instead there's an error message in the Tomcat localhost log (e.g. `localhost.2017-10-09.log`):
        09-Oct-2017 13:40:24.027 SEVERE [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log StandardWrapper.Throwable
 com.dotmarketing.exception.DotRuntimeException: No Company!
	at com.dotmarketing.cms.factories.PublicCompanyFactory.getDefaultCompany(PublicCompanyFactory.java:59)
	at com.dotmarketing.servlets.StartupLogger.log(StartupLogger.java:23)
	at com.dotmarketing.servlets.InitServlet.init(InitServlet.java:103)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4901)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5188)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1069)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1719)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

## Steps to Reproduce:

1. Download zip for the release-4.2 nightly time stamped 2017-10-06 22:18 (https://dotcms.com/contentAsset/raw-data/1af55e08-5d13-4f0a-8b44-3d2a4c2ebf5e/zip/dotcms-2017-10-06_22-18.zip)
2. Unpack it to a folder.
3. Open a command prompt as an Administrator.
4. Change to the just unpacked folder.
5. Run `bin\startup.bat`.

## My Environment

* dotCMS version used: release-4.2 nightly build distro time stamped 2017-10-06 22:18
* Browser Name and version: Chrome 61.0.3163.79
* Operating System and version: Win 7 Enterprise
* Application Server and version: Tomcat (distro)
* Java Brand and version: 1.8.0_111
* Database and version: H2 (distro)

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/12863

The issue described by @john-thomas-dotcms cannot be reproduced after applying this fix.

**Comment by jcastro-dotcms** [comment]
PR for release-4.2: https://github.com/dotCMS/core/pull/12866

**Comment by bryanboza** [comment]
Fixed, tested with the last master // MSSQL-2017 and i am able to start without problems. Also tested with a starter site and tested the upgrade. 

@john-thomas-dotcms please confirm in your environment on Win7

**Comment by john-thomas-dotcms** [comment]
Master 10/13 is working fine on Win 7.  Looks good.
