### ISSUE TITLE
Query Test Tool not working with Category Field

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#12959]
I have a Content Type defined as follows with 2 pieces of content. There are values for both the text and Category Fields on both pieces of content. 
![cattest](https://user-images.githubusercontent.com/1486445/32230931-a7db6252-be2a-11e7-923c-3df0655baa25.png)

Without the Category Field the Search tool works with the Category Field it throws a JSP error on displaying the content 

The error is in the CategoryAPI NPE 

```Stacktrace:
        at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:567) ~[jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:469) ~[jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) ~[jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) ~[jasper.jar:8.0.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:584) ~[catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:523) ~[catalina.jar:8.0.18]
        at com.liferay.portlet.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:209) [dotcms_4.2.0_999999.jar:?]
        at com.liferay.portlet.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:76) [dotcms_4.2.0_999999.jar:?]
        at com.liferay.portlet.JSPPortlet.include(JSPPortlet.java:124) [dotcms_4.2.0_999999.jar:?]
        at com.liferay.portlet.JSPPortlet.doView(JSPPortlet.java:96) [dotcms_4.2.0_999999.jar:?]
        at com.dotcms.repackage.javax.portlet.GenericPortlet.doDispatch(GenericPortlet.java:235) [dot.portlet-1.0_2.jar:?]
        at com.liferay.portlet.JSPPortlet.doDispatch(JSPPortlet.java:72) [dotcms_4.2.0_999999.jar:?]
        at com.dotcms.repackage.javax.portlet.GenericPortlet.render(GenericPortlet.java:163) [dot.portlet-1.0_2.jar:?]
        at com.liferay.portlet.CachePortlet.render(CachePortlet.java:159) [dotcms_4.2.0_999999.jar:?]
        at org.apache.jsp.html.portal.layout_jsp._jspService(layout_jsp.java:618) [ROOT/:?]
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [jasper.jar:8.0.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) [jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) [jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) [jasper.jar:8.0.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:584) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:523) [catalina.jar:8.0.18]
        at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:934) [jasper.jar:8.0.18]
        at org.apache.jsp.html.portal.layout_005fportal_jsp._jspService(layout_005fportal_jsp.java:1353) [ROOT/:?]
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [jasper.jar:8.0.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) [jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) [jasper.jar:8.0.18]
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) [jasper.jar:8.0.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318) [catalina.jar:8.0.18]
        at com.liferay.portal.struts.StrutsUtil.forward(StrutsUtil.java:72) [dotcms_4.2.0_999999.jar:?]
        at com.liferay.portal.struts.PortalRequestProcessor.doForward(PortalRequestProcessor.java:142) [dotcms_4.2.0_999999.jar:?]
        at com.dotmarketing.struts.PortalRequestProcessor.doForward(PortalRequestProcessor.java:48) [dotcms_4.2.0_999999.jar:?]
        at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processTilesDefinition(TilesRequestProcessor.java:237) [dot.struts-1.2.4_2.jar:1.2.4]
        at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processForwardConfig(TilesRequestProcessor.java:300) [dot.struts-1.2.4_2.jar:1.2.4]
        at com.dotcms.repackage.com.oroad.stxx.plugin.StxxTilesRequestProcessor.processForwardConfig(StxxTilesRequestProcessor.java:134) [dot.stxx-1.3_2.jar:?]
        at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:231) [dot.struts-1.2.4_2.jar:1.2.4]
        at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:128) [dotcms_4.2.0_999999.jar:?]
        at com.dotcms.repackage.org.apache.struts.action.ActionServlet.process(ActionServlet.java:1164) [dot.struts-1.2.4_2.jar:1.2.4]
        at com.dotcms.repackage.org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:415) [dot.struts-1.2.4_2.jar:1.2.4]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:644) [servlet-api.jar:?]
        at com.liferay.portal.servlet.MainServlet.callParentService(MainServlet.java:251) [dotcms_4.2.0_999999.jar:?]
        at com.liferay.portal.servlet.MainServlet.service(MainServlet.java:440) [dotcms_4.2.0_999999.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotcms.repackage.com.liferay.filters.secure.SecureFilter.doFilter(SecureFilter.java:135) [dot.secure-filter-ukv_2.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:203) [dotcms_4.2.0_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.2.0_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.2.0_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:325) [dotcms_4.2.0_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:110) [dotcms_4.2.0_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:132) [dotcms_4.2.0_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_4.2.0_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:38) [dotcms_4.2.0_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:108) [dotcms_4.2.0_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at com.dotmarketing.portlets.categories.business.CategoryAPIImpl.isParent(CategoryAPIImpl.java:659) ~[dotcms_4.2.0_999999.jar:?]
        at com.dotmarketing.portlets.contentlet.util.ContentletUtil.getContentPrintableMap(ContentletUtil.java:122) ~[dotcms_4.2.0_999999.jar:?]
        at org.apache.jsp.WEB_002dINF.jsp.lucene.lucene_005fsearch_jsp._jspService(lucene_005fsearch_jsp.java:533) ~[?:?]
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:8.0.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) ~[jasper.jar:8.0.18]
```

**Comment by dsilvam** [comment]
This can be also reproduced from the Query Tool by doing: +contentType:your-type-with-cats

**Comment by shaydotcms** [comment]
Passed QA. Tested with client dataset dotcms_3.6 to master branch  / commit 6eb9c44c6108bcc8179108ae99b6dc637f0d044d
SQLServer 2012 / Mac OS 10.10 / Firefox v45.0.1 / Tomcat 8 / Java 8
