### ISSUE TITLE
Incorrect value for numeric Data Types in Content Type field not displaying any error message

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#13099]
Reproducible in https://demo.dotcms.com/dotAdmin

When adding a "Select" field to a Content Type, there are 2 available data types for numeric values: `Decimal` and `Whole Number`. If you select the `Whole Number` type, and enter the following value:
```
My option |1.7
```
The page does not save the field (which is correct and expected) and refreshes. However, no error message indicating an incorrect value is displayed. This is displayed in the `dotcms.log` file:
```
[21/11/17 11:25:02:178 CST] ERROR action.EditFieldAction: com.dotmarketing.business.DotStateException: Values entered are not valid for this datatypeinteger Option 1|1.4
com.dotmarketing.business.DotStateException: Values entered are not valid for this datatypeinteger Option 1|1.4
	at com.dotcms.contenttype.transform.field.ImplClassFieldTransformer.impleClass(ImplClassFieldTransformer.java:39) ~[dotcms_4.3.0_78dcad2.jar:?]
	at com.dotcms.contenttype.transform.field.ImplClassFieldTransformer.from(ImplClassFieldTransformer.java:28) ~[dotcms_4.3.0_78dcad2.jar:?]
	at com.dotcms.contenttype.transform.field.LegacyFieldTransformer.transformToNew(LegacyFieldTransformer.java:265) ~[dotcms_4.3.0_78dcad2.jar:?]
	at com.dotcms.contenttype.transform.field.LegacyFieldTransformer.<init>(LegacyFieldTransformer.java:50) ~[dotcms_4.3.0_78dcad2.jar:?]
	at com.dotcms.contenttype.transform.field.LegacyFieldTransformer.<init>(LegacyFieldTransformer.java:30) ~[dotcms_4.3.0_78dcad2.jar:?]
	at com.dotmarketing.portlets.structure.action.EditFieldAction._saveField(EditFieldAction.java:357) [dotcms_4.3.0_78dcad2.jar:?]
	at com.dotmarketing.portlets.structure.action.EditFieldAction.processAction(EditFieldAction.java:158) [dotcms_4.3.0_78dcad2.jar:?]
	at com.liferay.portal.struts.PortletRequestProcessor.process(PortletRequestProcessor.java:128) [dotcms_4.3.0_78dcad2.jar:?]
	at com.liferay.portlet.StrutsPortlet.processAction(StrutsPortlet.java:116) [dotcms_4.3.0_78dcad2.jar:?]
	at com.liferay.portlet.CachePortlet.processAction(CachePortlet.java:130) [dotcms_4.3.0_78dcad2.jar:?]
	at com.liferay.portal.action.LayoutAction._processPortletRequest(LayoutAction.java:232) [dotcms_4.3.0_78dcad2.jar:?]
	at com.liferay.portal.action.LayoutAction._processActionRequest(LayoutAction.java:249) [dotcms_4.3.0_78dcad2.jar:?]
	at com.liferay.portal.action.LayoutAction.execute(LayoutAction.java:93) [dotcms_4.3.0_78dcad2.jar:?]
	at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:421) [dot.struts-1.2.4_2.jar:1.2.4]
	at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:226) [dot.struts-1.2.4_2.jar:1.2.4]
	at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:128) [dotcms_4.3.0_78dcad2.jar:?]
	at com.dotcms.repackage.org.apache.struts.action.ActionServlet.process(ActionServlet.java:1164) [dot.struts-1.2.4_2.jar:1.2.4]
	at com.dotcms.repackage.org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:415) [dot.struts-1.2.4_2.jar:1.2.4]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644) [servlet-api.jar:?]
	at com.liferay.portal.servlet.MainServlet.callParentService(MainServlet.java:251) [dotcms_4.3.0_78dcad2.jar:?]
	at com.liferay.portal.servlet.MainServlet.service(MainServlet.java:440) [dotcms_4.3.0_78dcad2.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.repackage.com.liferay.filters.secure.SecureFilter.doFilter(SecureFilter.java:135) [dot.secure-filter-ukv_2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:200) [dotcms_4.3.0_78dcad2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.3.0_78dcad2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.3.0_78dcad2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:325) [dotcms_4.3.0_78dcad2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:110) [dotcms_4.3.0_78dcad2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:132) [dotcms_4.3.0_78dcad2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_4.3.0_78dcad2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:38) [dotcms_4.3.0_78dcad2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:108) [dotcms_4.3.0_78dcad2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: com.dotmarketing.business.DotStateException: Values entered are not valid for this datatypeinteger Option 1|1.4
	at com.dotcms.contenttype.model.field.SelectableValuesField.check(SelectableValuesField.java:56) ~[dotcms_4.3.0_78dcad2.jar:?]
	at com.dotcms.contenttype.model.field.ImmutableSelectField.validate(ImmutableSelectField.java:1961) ~[dotcms_4.3.0_78dcad2.jar:?]
	at com.dotcms.contenttype.model.field.ImmutableSelectField.access$14(ImmutableSelectField.java:1960) ~[dotcms_4.3.0_78dcad2.jar:?]
	at com.dotcms.contenttype.model.field.ImmutableSelectField$Builder.build(ImmutableSelectField.java:2383) ~[dotcms_4.3.0_78dcad2.jar:?]
	at com.dotcms.contenttype.model.field.ImmutableSelectField$Builder.build(ImmutableSelectField.java:1) ~[dotcms_4.3.0_78dcad2.jar:?]
	at com.dotcms.contenttype.transform.field.ImplClassFieldTransformer.impleClass(ImplClassFieldTransformer.java:37) ~[dotcms_4.3.0_78dcad2.jar:?]
	... 76 more
Caused by: java.lang.NumberFormatException: For input string: "1.4"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_144]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_144]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_144]
	at com.dotcms.contenttype.model.field.SelectableValuesField.check(SelectableValuesField.java:45) ~[dotcms_4.3.0_78dcad2.jar:?]
	at com.dotcms.contenttype.model.field.ImmutableSelectField.validate(ImmutableSelectField.java:1961) ~[dotcms_4.3.0_78dcad2.jar:?]
	at com.dotcms.contenttype.model.field.ImmutableSelectField.access$14(ImmutableSelectField.java:1960) ~[dotcms_4.3.0_78dcad2.jar:?]
	at com.dotcms.contenttype.model.field.ImmutableSelectField$Builder.build(ImmutableSelectField.java:2383) ~[dotcms_4.3.0_78dcad2.jar:?]
	at com.dotcms.contenttype.model.field.ImmutableSelectField$Builder.build(ImmutableSelectField.java:1) ~[dotcms_4.3.0_78dcad2.jar:?]
	at com.dotcms.contenttype.transform.field.ImplClassFieldTransformer.impleClass(ImplClassFieldTransformer.java:37) ~[dotcms_4.3.0_78dcad2.jar:?]
	... 76 more
```

## Expected Behavior
An error message indicating an invalid whole number should be displayed.

## Current Behavior
No error messages are being displayed.

## Possible Solution
Display an error message on the page.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)
1. Create a test Content Type.
2. Add a new field to it. Select the "Select" field.
3. Check the "Whole Number" data type.
4. Enter the following as its value: `My option |1.7`
5. Save the new field.
6. The field is not saved (which is ok) and the page refreshed. However, no error message is displayed.

## Context
Users need to know why saving this field failed.

## Your Environment
* dotCMS version used: dotCMS 4.2.2
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: Content Type portlet.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/13105

**Comment by bryanboza** [comment]
Fixed, no the message appears at ui level. Tested in the last master
