### ISSUE TITLE
Unable to upgrade from 3.x versions 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13196]
Related to #11609 

We have problems with the task **Task04305UpdateWorkflowActionTable** when you are upgrading from previous versions, from 3.x in this case 

## Expected Behavior
We should be able to upgrade from any version without problems 

## Current Behavior
We have a fatal error running the "**Task04305UpdateWorkflowActionTable**" and we are unable to start the dotcms instance 

## Steps to Reproduce (for bugs)
1. Start a 3.x server 
2. Apply the license 
3. Create some workflows (wf) and add some steps with actions  
4. Shutdown the server
5. Copy the asset folder to the master instance
6. Using the same database start the master instance 

## Your Environment
Tested upgrading from a 3.7.1 version to the last master code in postgres

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13200

**Comment by bryanboza** [comment]
Unable to upgrade in MSSQL 
Here the log error: 
```
[14/12/17 15:05:56:886 CST] FATAL startup.StartupTasksExecutor: Unable to execute the upgrade task : Task04305UpdateWorkflowActionTable
com.dotmarketing.exception.DotRuntimeException: The 'workflow_action_step' table could not be created.
	at com.dotmarketing.startup.runonce.Task04305UpdateWorkflowActionTable.createWorkflowActionStepTable(Task04305UpdateWorkflowActionTable.java:306) ~[dotcms_4.3.0_0a00a67.jar:?]
	at com.dotmarketing.startup.runonce.Task04305UpdateWorkflowActionTable.executeUpgrade(Task04305UpdateWorkflowActionTable.java:149) ~[dotcms_4.3.0_0a00a67.jar:?]
	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:271) [dotcms_4.3.0_0a00a67.jar:?]
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:102) [dotcms_4.3.0_0a00a67.jar:?]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4901) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5188) [catalina.jar:8.0.18]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714) [catalina.jar:8.0.18]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1069) [catalina.jar:8.0.18]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1719) [catalina.jar:8.0.18]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_40]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: com.dotmarketing.exception.DotDataException: Incorrect syntax near 'action_order'.{
  "SQL": ["CREATE TABLE workflow_action_step ( action_id NVARCHAR(36) NOT NULL, step_id NVARCHAR(36) NOT NULL action_order INT default 0, CONSTRAINT pk_workflow_action_step PRIMARY KEY NONCLUSTERED (action_id, step_id) )"],
  "maxRows": [-1],
  "offest": [0]
}
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:246) ~[dotcms_4.3.0_0a00a67.jar:?]
	at com.dotmarketing.startup.runonce.Task04305UpdateWorkflowActionTable.createWorkflowActionStepTable(Task04305UpdateWorkflowActionTable.java:295) ~[dotcms_4.3.0_0a00a67.jar:?]
	... 19 more
Caused by: java.sql.SQLException: Incorrect syntax near 'action_order'.
	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:368) ~[jtds-1.2.2.jar:1.2.2]
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2816) ~[jtds-1.2.2.jar:1.2.2]
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2254) ~[jtds-1.2.2.jar:1.2.2]
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:631) ~[jtds-1.2.2.jar:1.2.2]
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:584) ~[jtds-1.2.2.jar:1.2.2]
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:546) ~[jtds-1.2.2.jar:1.2.2]
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeImpl(JtdsStatement.java:723) ~[jtds-1.2.2.jar:1.2.2]
	at net.sourceforge.jtds.jdbc.JtdsStatement.execute(JtdsStatement.java:1157) ~[jtds-1.2.2.jar:1.2.2]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:290) ~[tomcat-dbcp.jar:8.0.18]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:290) ~[tomcat-dbcp.jar:8.0.18]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:625) ~[dotcms_4.3.0_0a00a67.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:514) ~[dotcms_4.3.0_0a00a67.jar:?]
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:244) ~[dotcms_4.3.0_0a00a67.jar:?]
	at com.dotmarketing.startup.runonce.Task04305UpdateWorkflowActionTable.createWorkflowActionStepTable(Task04305UpdateWorkflowActionTable.java:295) ~[dotcms_4.3.0_0a00a67.jar:?]
	... 19 more
```

**Comment by bryanboza** [comment]
Blocked by #13379

**Comment by bryanboza** [comment]
Problems trying to upgrade from 3.x to master in Oracle

**Comment by bryanboza** [comment]
Also we have this error on mssql... https://gist.github.com/bryanboza/d878067aaaef453095c0827f8cf20101

**Comment by bryanboza** [comment]
Fixed, tested with a clean install in every database and now it works without problems...
