### ISSUE TITLE
Workflow error starting dotCMS

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#13225]
Related to #11609 

We are having a WorkflowImportExportUtil error trying to start a new fresh instance with the last master code 

## Expected Behavior
We need start a clean instance without problems 

## Current Behavior
We are having the follow error
```
[15/12/17 15:00:11:273 CST] ERROR util.WorkflowImportExportUtil: Error: cannot convert object to class com.dotmarketing.portlets.workflows.model.WorkflowAction No enum constant com.dotmarketing.portlets.workflows.model.WorkflowStatus.
com.dotmarketing.exception.DotDataException: cannot convert object to class com.dotmarketing.portlets.workflows.model.WorkflowAction No enum constant com.dotmarketing.portlets.workflows.model.WorkflowStatus.
	at com.dotmarketing.portlets.workflows.business.WorkflowFactoryImpl.convertListToObjects(WorkflowFactoryImpl.java:93) ~[dotcms_4.3.0_4552600.jar:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowFactoryImpl.findAction(WorkflowFactoryImpl.java:385) ~[dotcms_4.3.0_4552600.jar:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowFactoryImpl.saveActionClass(WorkflowFactoryImpl.java:1041) ~[dotcms_4.3.0_4552600.jar:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.saveActionClass_aroundBody92(WorkflowAPIImpl.java:879) ~[dotcms_4.3.0_4552600.jar:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl$AjcClosure93.run(WorkflowAPIImpl.java:1) ~[dotcms_4.3.0_4552600.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.3.0_4552600.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:39) ~[dotcms_4.3.0_4552600.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_4.3.0_4552600.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_4.3.0_4552600.jar:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.saveActionClass(WorkflowAPIImpl.java:878) ~[dotcms_4.3.0_4552600.jar:?]
	at com.dotmarketing.portlets.workflows.util.WorkflowImportExportUtil.importWorkflowExport(WorkflowImportExportUtil.java:103) [dotcms_4.3.0_4552600.jar:?]
	at com.dotmarketing.util.ImportExportUtil.doImport(ImportExportUtil.java:728) [dotcms_4.3.0_4552600.jar:?]
	at com.dotmarketing.db.DotCMSInitDb.loadStarterSite(DotCMSInitDb.java:110) [dotcms_4.3.0_4552600.jar:?]
	at com.dotmarketing.db.DotCMSInitDb.InitializeDb_aroundBody2(DotCMSInitDb.java:48) [dotcms_4.3.0_4552600.jar:?]
	at com.dotmarketing.db.DotCMSInitDb$AjcClosure3.run(DotCMSInitDb.java:1) [dotcms_4.3.0_4552600.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) [aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) [dotcms_4.3.0_4552600.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) [dotcms_4.3.0_4552600.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) [dotcms_4.3.0_4552600.jar:?]
	at com.dotmarketing.db.DotCMSInitDb.InitializeDb(DotCMSInitDb.java:39) [dotcms_4.3.0_4552600.jar:?]
	at com.dotmarketing.startup.runalways.Task00004LoadStarter.executeUpgrade(Task00004LoadStarter.java:14) [dotcms_4.3.0_4552600.jar:?]
	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:212) [dotcms_4.3.0_4552600.jar:?]
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:102) [dotcms_4.3.0_4552600.jar:?]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4901) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5188) [catalina.jar:8.0.18]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714) [catalina.jar:8.0.18]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1069) [catalina.jar:8.0.18]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1719) [catalina.jar:8.0.18]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[15/12/17 15:00:11:278 CST]  INFO util.ImportExportUtil: Importing:	com.dotmarketing.beans.Permission
[15/12/17 15:00:11:294 CST]  INFO util.ImportExportUtil: Found :	335 com.dotmarketing.beans.Permission(s)
[15/12/17 15:00:13:308 CST]  INFO util.ImportExportUtil: Importing:	com.dotmarketing.portlets.containers.model.ContainerVersionInfo
[15/12/17 15:00:13:310 CST]  INFO util.ImportExportUtil: Found :	12 com.dotmarketing.portlets.containers.model.ContainerVers
```

## Steps to Reproduce (for bugs)
To recreate just need try to start a fresh install of dotCMS

## Your Environment
Tested on master // postgres // FF

**Comment by bryanboza** [comment]
Fixed, tested in the last master // postgres // FF, now we are able to start without problems
