### ISSUE TITLE
on clean install on MSSQL getting an error

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#13237]
```
 ERROR reindex.ReindexThread: Unable to index record with id [ff9d9f72-3650-4bca-9e0f-6ce18150d51e]
com.dotmarketing.exception.DotDataException: java.lang.Short cannot be cast to java.lang.Boolean
	at com.dotmarketing.portlets.folders.business.FolderFactoryImpl.findFolderByPath(FolderFactoryImpl.java:292) ~[dotcms_4.3.0_dd52111.jar:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.findFolderByPath_aroundBody0(FolderAPIImpl.java:74) ~[dotcms_4.3.0_dd52111.jar:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl$AjcClosure1.run(FolderAPIImpl.java:1) ~[dotcms_4.3.0_dd52111.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.3.0_dd52111.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_4.3.0_dd52111.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_4.3.0_dd52111.jar:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.findFolderByPath(FolderAPIImpl.java:70) ~[dotcms_4.3.0_dd52111.jar:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.findFolderByPath(FolderAPIImpl.java:98) ~[dotcms_4.3.0_dd52111.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.convertFatContentletToContentlet(ESContentFactoryImpl.java:289) ~[dotcms_4.3.0_dd52111.jar:?]
	at com.dotmarketing.common.reindex.ReindexThread.convertFatContentletToContentlet_aroundBody4(ReindexThread.java:709) ~[dotcms_4.3.0_dd52111.jar:?]
	at com.dotmarketing.common.reindex.ReindexThread$AjcClosure5.run(ReindexThread.java:1) ~[dotcms_4.3.0_dd52111.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.3.0_dd52111.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_4.3.0_dd52111.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_4.3.0_dd52111.jar:?]
	at com.dotmarketing.common.reindex.ReindexThread.convertFatContentletToContentlet(ReindexThread.java:706) ~[dotcms_4.3.0_dd52111.jar:?]
	at com.dotmarketing.common.reindex.ReindexThread.writeDocumentToIndex(ReindexThread.java:735) ~[dotcms_4.3.0_dd52111.jar:?]
	at com.dotmarketing.common.reindex.ReindexThread.run(ReindexThread.java:300) [dotcms_4.3.0_dd52111.jar:?]

```

**Comment by jgambarios** [comment]
Fixed in https://github.com/dotcms/core/issues/11609

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13254

**Comment by jgambarios** [comment]
I marked the ticket as needs work as I found a similar issue in oracle on a clean install.

```
21/12/17 17:53:53:837 CST] ERROR reindex.ReindexThread: Unable to index record with id [025e9295-771f-45ea-8c7e-32fff14d047d]
com.dotmarketing.exception.DotDataException: java.math.BigDecimal cannot be cast to java.lang.Integer
	at com.dotmarketing.portlets.folders.business.FolderFactoryImpl.findFolderByPath(FolderFactoryImpl.java:292) ~[dotcms_4.3.0_44c205b.jar:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.findFolderByPath_aroundBody0(FolderAPIImpl.java:74) ~[dotcms_4.3.0_44c205b.jar:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl$AjcClosure1.run(FolderAPIImpl.java:1) ~[dotcms_4.3.0_44c205b.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.3.0_44c205b.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_4.3.0_44c205b.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_4.3.0_44c205b.jar:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.findFolderByPath(FolderAPIImpl.java:70) ~[dotcms_4.3.0_44c205b.jar:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.findFolderByPath(FolderAPIImpl.java:98) ~[dotcms_4.3.0_44c205b.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.convertFatContentletToContentlet(ESContentFactoryImpl.java:289) ~[dotcms_4.3.0_44c205b.jar:?]
	at com.dotmarketing.common.reindex.ReindexThread.convertFatContentletToContentlet_aroundBody4(ReindexThread.java:709) ~[dotcms_4.3.0_44c205b.jar:?]
	at com.dotmarketing.common.reindex.ReindexThread$AjcClosure5.run(ReindexThread.java:1) ~[dotcms_4.3.0_44c205b.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.3.0_44c205b.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_4.3.0_44c205b.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_4.3.0_44c205b.jar:?]
	at com.dotmarketing.common.reindex.ReindexThread.convertFatContentletToContentlet(ReindexThread.java:706) ~[dotcms_4.3.0_44c205b.jar:?]
	at com.dotmarketing.common.reindex.ReindexThread.writeDocumentToIndex(ReindexThread.java:735) ~[dotcms_4.3.0_44c205b.jar:?]
	at com.dotmarketing.common.reindex.ReindexThread.run(ReindexThread.java:300) [dotcms_4.3.0_44c205b.jar:?]
```

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/13264

**Comment by bryanboza** [comment]
Fixed, now we are able to start with a clean install on MySQL and Oracle too without problems... Tested on the last master // MySQL and Oracle 12c...
