### ISSUE TITLE
Webdav - Uploading multiple files to a New folder shows exception in log: ERROR db.DotConnect: ERROR: duplicate key value violates unique constraint "permission_reference_asset_id_key"

### ISSUE THREAD

**Issue by acurionedotcms** [dotCMS/core#13309]
In Webdav (using Cyberduck client)
1- Create a new Folder
2- Upload multiple images or files (4 or 5 works)
3- Files are uploaded correctly
4- Go to the dotcms Log file:

There's an exception:
[04/01/18 11:47:36:282 CST] ERROR db.DotConnect: ERROR: duplicate key value violates unique constraint "permission_reference_asset_id_key"
  Detail: Key (asset_id)=(2b4cdd0d-e717-402b-8dc8-33737ca07cce) already exists.
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "permission_reference_asset_id_key"
  Detail: Key (asset_id)=(2b4cdd0d-e717-402b-8dc8-33737ca07cce) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:334) ~[postgresql-9.0-801.jdbc3.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeUpdate(DotConnect.java:1170) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeUpdate(DotConnect.java:1113) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.deleteInsertPermission_aroundBody0(PermissionBitFactoryImpl.java:2304) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl$AjcClosure1.run(PermissionBitFactoryImpl.java:1) ~[dotcms_4.3.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.deleteInsertPermission(PermissionBitFactoryImpl.java:2283) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions(PermissionBitFactoryImpl.java:2270) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.getInheritablePermissions(PermissionBitFactoryImpl.java:972) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.getInheritablePermissions(PermissionBitFactoryImpl.java:954) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions(PermissionBitFactoryImpl.java:2259) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.getPermissions(PermissionBitFactoryImpl.java:1052) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitAPIImpl.getPermissions_aroundBody18(PermissionBitAPIImpl.java:589) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitAPIImpl$AjcClosure19.run(PermissionBitAPIImpl.java:1) ~[dotcms_4.3.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitAPIImpl.getPermissions(PermissionBitAPIImpl.java:587) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.loadPermissions(ESMappingAPIImpl.java:344) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.toMap(ESMappingAPIImpl.java:193) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletIndexAPI.indexContentletList(ESContentletIndexAPI.java:355) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletIndexAPI.indexContentList(ESContentletIndexAPI.java:329) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.db.ReindexRunnable.run(ReindexRunnable.java:51) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.db.DotRunnableThread.internalRunner(DotRunnableThread.java:77) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrap(LocalTransaction.java:133) [dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.db.DotRunnableThread.run(DotRunnableThread.java:41) [dotcms_4.3.0_999999.jar:?]
[04/01/18 11:47:36:290 CST]  WARN business.PermissionBitFactoryImpl: Failed to insert Permission Ref. Usually not a problem. Permissionable:2b4cdd0d-e717-402b-8dc8-33737ca07cce Parent : 48190c8c-42c4-46af-8d1a-0cd5db894797 Type: com.dotmarketing.portlets.folders.model.Folder
[04/01/18 11:47:36:291 CST]  INFO business.PermissionBitFactoryImpl: LOAD PERM thread: Thread-39, type: com.dotmarketing.portlets.contentlet.model.Contentlet
[04/01/18 11:47:36:291 CST] ERROR business.ESContentletIndexAPI: Can't get a mapping for contentlet with id_lang:a881cba5-4325-41f0-994f-119fc14f6224_1 Content data: {owner=dotcms.org.1, identifier=a881cba5-4325-41f0-994f-119fc14f6224, fileName=kart2.jpg, modDate=Thu Jan 04 11:47:35 CST 2018, languageId=1, description=kart2, title=kart2.jpg, fileAsset=/Users/andrecurione/development/tomcat8/webapps/ROOT/assets/8/3/83c3d9dc-24a3-48eb-abed-56783f87b843/fileAsset/kart2.jpg, inode=83c3d9dc-24a3-48eb-abed-56783f87b843, metaData=**~~||%%CACHED_METADATA%%||~~**, folder=2b4cdd0d-e717-402b-8dc8-33737ca07cce, disabledWYSIWYG=[], sortOrder=0, modUser=dotcms.org.1, host=48190c8c-42c4-46af-8d1a-0cd5db894797, stInode=33888b6f-7a8e-4069-b1b6-5c1aa9d0a48d}
com.dotcms.content.business.DotMappingException
	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.toMap(ESMappingAPIImpl.java:294) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletIndexAPI.indexContentletList(ESContentletIndexAPI.java:355) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletIndexAPI.indexContentList(ESContentletIndexAPI.java:329) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.db.ReindexRunnable.run(ReindexRunnable.java:51) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.db.DotRunnableThread.internalRunner(DotRunnableThread.java:77) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrap(LocalTransaction.java:133) [dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.db.DotRunnableThread.run(DotRunnableThread.java:41) [dotcms_4.3.0_999999.jar:?]
Caused by: com.dotmarketing.exception.DotDataException: ERROR: duplicate key value violates unique constraint "permission_reference_asset_id_key"
  Detail: Key (asset_id)=(2b4cdd0d-e717-402b-8dc8-33737ca07cce) already exists.
	at com.dotmarketing.business.PermissionBitFactoryImpl.deleteInsertPermission_aroundBody0(PermissionBitFactoryImpl.java:2317) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl$AjcClosure1.run(PermissionBitFactoryImpl.java:1) ~[dotcms_4.3.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.deleteInsertPermission(PermissionBitFactoryImpl.java:2283) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions(PermissionBitFactoryImpl.java:2270) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.getInheritablePermissions(PermissionBitFactoryImpl.java:972) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.getInheritablePermissions(PermissionBitFactoryImpl.java:954) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions(PermissionBitFactoryImpl.java:2259) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.getPermissions(PermissionBitFactoryImpl.java:1052) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitAPIImpl.getPermissions_aroundBody18(PermissionBitAPIImpl.java:589) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitAPIImpl$AjcClosure19.run(PermissionBitAPIImpl.java:1) ~[dotcms_4.3.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitAPIImpl.getPermissions(PermissionBitAPIImpl.java:587) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.loadPermissions(ESMappingAPIImpl.java:344) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.toMap(ESMappingAPIImpl.java:193) ~[dotcms_4.3.0_999999.jar:?]
	... 6 more
Caused by: com.dotmarketing.exception.DotDataException: ERROR: duplicate key value violates unique constraint "permission_reference_asset_id_key"
  Detail: Key (asset_id)=(2b4cdd0d-e717-402b-8dc8-33737ca07cce) already exists.
	at com.dotmarketing.common.db.DotConnect.executeUpdate(DotConnect.java:1174) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeUpdate(DotConnect.java:1113) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.deleteInsertPermission_aroundBody0(PermissionBitFactoryImpl.java:2304) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl$AjcClosure1.run(PermissionBitFactoryImpl.java:1) ~[dotcms_4.3.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.deleteInsertPermission(PermissionBitFactoryImpl.java:2283) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions(PermissionBitFactoryImpl.java:2270) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.getInheritablePermissions(PermissionBitFactoryImpl.java:972) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.getInheritablePermissions(PermissionBitFactoryImpl.java:954) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions(PermissionBitFactoryImpl.java:2259) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.getPermissions(PermissionBitFactoryImpl.java:1052) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitAPIImpl.getPermissions_aroundBody18(PermissionBitAPIImpl.java:589) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitAPIImpl$AjcClosure19.run(PermissionBitAPIImpl.java:1) ~[dotcms_4.3.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitAPIImpl.getPermissions(PermissionBitAPIImpl.java:587) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.loadPermissions(ESMappingAPIImpl.java:344) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.toMap(ESMappingAPIImpl.java:193) ~[dotcms_4.3.0_999999.jar:?]
	... 6 more
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "permission_reference_asset_id_key"
  Detail: Key (asset_id)=(2b4cdd0d-e717-402b-8dc8-33737ca07cce) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388) ~[postgresql-9.0-801.jdbc3.jar:?]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:334) ~[postgresql-9.0-801.jdbc3.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeUpdate(DotConnect.java:1170) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeUpdate(DotConnect.java:1113) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.deleteInsertPermission_aroundBody0(PermissionBitFactoryImpl.java:2304) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl$AjcClosure1.run(PermissionBitFactoryImpl.java:1) ~[dotcms_4.3.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.deleteInsertPermission(PermissionBitFactoryImpl.java:2283) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions(PermissionBitFactoryImpl.java:2270) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.getInheritablePermissions(PermissionBitFactoryImpl.java:972) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.getInheritablePermissions(PermissionBitFactoryImpl.java:954) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions(PermissionBitFactoryImpl.java:2259) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.getPermissions(PermissionBitFactoryImpl.java:1052) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitAPIImpl.getPermissions_aroundBody18(PermissionBitAPIImpl.java:589) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitAPIImpl$AjcClosure19.run(PermissionBitAPIImpl.java:1) ~[dotcms_4.3.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.business.PermissionBitAPIImpl.getPermissions(PermissionBitAPIImpl.java:587) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.loadPermissions(ESMappingAPIImpl.java:344) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.toMap(ESMappingAPIImpl.java:193) ~[dotcms_4.3.0_999999.jar:?]
	... 6 more

**Comment by shaydotcms** [comment]
Passed QA.
No errrors in logs after creating and uploading different type of assets.
Tested on master branch / Mac 10.10 / Postgres 9.6 / Chrome v54.0.2840.98 / Tomcat 8 / Java 8

**Comment by wezell** [comment]
Postgres 9.4 is deprecated
