### ISSUE TITLE
Trying to edit the 3 column template

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13414]
In our starter, the 3 column template has a sidebar.  If you create a page that uses it, you are unable to save your changes to the template:

```
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of START_OBJECT token
 at [Source: {"body":{"rows":[{"columns":[{"leftOffset":1,"width":6,"containers":[{"identifier":"56bd55ea-b04b-480d-9e37-5d6f9217dcc3","uuid":"LEGACY_RELATION_TYPE"}]},{"leftOffset":7,"width":6,"containers":[{"identifier":"5363c6c6-5ba0-4946-b7af-cf875188ac2e","uuid":"LEGACY_RELATION_TYPE"}]}]}]},"header":false,"footer":false,"sidebar":{"containers":{"identifier":"fc193c82-8c32-4abe-ba8a-49522328c93e","uuid":"LEGACY_RELATION_TYPE"},"location":"","width":0,"widthPercent":20,"preview":false}}; line: 1, column: 327] (through reference chain: com.dotmarketing.portlets.templates.design.bean.TemplateLayout["sidebar"]->com.dotmarketing.portlets.templates.design.bean.Sidebar["containers"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:857) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:853) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:292) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:227) ~[jackson-databind-2.6.3.jar:2.6.3]

```

**Comment by fmontes** [comment]
This is fixed here: https://github.com/dotCMS/core/pull/13743
