### ISSUE TITLE
Cannot create a New template using Template Designer

### ISSUE THREAD

**Issue by acurionedotcms** [dotCMS/core#13436]
## Current Behavior
When attempting to create a new Template, the page shows error: 
"Unfortunately this has caused a problem. Please try again."
instead of displaying the Template designer
See log below

## Possible Solution
Seems this is the issue: 
Caused by: java.lang.IllegalArgumentException: the themeInode is null
at com.dotmarketing.portlets.templates.business.TemplateAPIImpl.getContainersInTemplate_aroundBody12(TemplateAPIImpl.java:261)

## Known Workarounds
No workaround

## Steps to Reproduce (for bugs)
1. Go to Site / Templates
2. Click on the elipsis, select: Add Template Designer
3. Page shows error: Unfortunately this has caused a problem. Please try again.

## Your Environment
* dotCMS version used: master
* Browser Name and version: chrome
* Operating System and version: mac os
* Application Server and version: tomcat
* Java Brand and version: java 8
* Database and version: postgres
* Application module (if apply):

**Comment by acurionedotcms** [comment]
Stacktrace:
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:584) ~[jasper.jar:8.5.24]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:481) ~[jasper.jar:8.5.24]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386) ~[jasper.jar:8.5.24]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330) ~[jasper.jar:8.5.24]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.24]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728) ~[catalina.jar:8.5.24]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:591) ~[catalina.jar:8.5.24]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:527) ~[catalina.jar:8.5.24]
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:894) ~[jasper.jar:8.5.24]
	at org.apache.jsp.html.portal.layout_005fportal_jsp._jspService(layout_005fportal_jsp.java:634) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:8.5.24]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443) ~[jasper.jar:8.5.24]
	... 121 more
Caused by: java.lang.IllegalArgumentException: the themeInode is null
	at com.dotcms.rendering.velocity.viewtools.DotTemplateTool.themeLayout(DotTemplateTool.java:114) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.rendering.velocity.viewtools.DotTemplateTool.themeLayout(DotTemplateTool.java:94) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.portlets.templates.business.TemplateAPIImpl.getContainersInTemplate_aroundBody12(TemplateAPIImpl.java:261) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.portlets.templates.business.TemplateAPIImpl$AjcClosure13.run(TemplateAPIImpl.java:1) ~[dotcms_4.3.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_4.3.0_999999.jar:?]
	at com.dotmarketing.portlets.templates.business.TemplateAPIImpl.getContainersInTemplate(TemplateAPIImpl.java:258) ~[dotcms_4.3.0_999999.jar:?]
	at org.apache.jsp.html.portlet.ext.templates.design.design_005ftemplates_jsp._jspService(design_005ftemplates_jsp.java:1337) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:8.5.24]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443) ~[jasper.jar:8.5.24]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386) ~[jasper.jar:8.5.24]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330) ~[jasper.jar:8.5.24]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.24]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728) ~[catalina.jar:8.5.24]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:591) ~[catalina.jar:8.5.24]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:527) ~[catalina.jar:8.5.24]
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:894) ~[jasper.jar:8.5.24]
	at org.apache.jsp.html.portal.layout_005fportal_jsp._jspService(layout_005fportal_jsp.java:634) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:8.5.24]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443) ~[jasper.jar:8.5.24]
	... 121 more
[18/01/18 10:51:24:260 CST] ERROR portlet.StrutsPortlet: org.apache.jasper.JasperException: An exception occurred processing JSP page [/html/portlet/ext/templates/design/design_templates.jsp] at line [52]

49: 	int containerSize = 0 ;
50: 	
51: 	if(template != null){
52: 		 containersList = templateAPI.getContainersInTemplate(template, user, true);
53: 		 if(containersList != null && containersList.size() > 0){
54: 			 containerSize = containersList.size();
55: 			for (int i = 0; i < containersList.size(); i++) {


Stacktrace:

**Comment by wezell** [comment]
This is fixed in this branch:

https://github.com/dotCMS/core/tree/nocode-webinar-branch

Here:
https://github.com/dotCMS/core/commit/2f20b7da5fef65913df9c831b24c53fef8216bf2#diff-ff83aa7707db819f32047274f624b31fR260
