### ISSUE TITLE
[ContentType] Conflicts with sortOrder reserved word and odd behavior of radio buttons' fields.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#13437]
## Expected Behavior
We should be able to create fields and validate if they don't collide with any reserved word. Additionally, Radio fields should allow a single selection of possible values.

## Current Behavior
If a field is named "Sort Order" (being 'sortOrder' as its variable), it causes a ClassCastException error message.
Radio buttons have all items marked as check, working as a multiple select field.

## Possible Solution
Check if Fields' variables don't collide with any reserved word, including the ones here 

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/Contentlet.java#L47-L85 

And make sure Radio buttons work as expected, allowing a single selection from possible options.

## Known Workarounds
Set a different name to Field, so "sortOrder" is not the exact field's velocity var name.

## Steps to Reproduce (for bugs)

1. Login to demo.dotcms.com site.
2. Create a Content Type called "Test".

<img width="1539" alt="screen shot 2018-01-18 at 11 13 34 am" src="https://user-images.githubusercontent.com/1717110/35111484-feb09d32-fc40-11e7-86ca-f9c77b9ea955.png">

3. Add a Radio button called "Sort Order".

<img width="1537" alt="screen shot 2018-01-18 at 11 13 42 am" src="https://user-images.githubusercontent.com/1717110/35111505-0d03b270-fc41-11e7-9d93-600ae4e5b892.png">

Where data type is "text" and field's values are:

```
Ascending|asc
Descending|desc
```

4. Create a Test content for this content type. UI shows both radio options as checked

<img width="1159" alt="screen shot 2018-01-18 at 11 11 01 am" src="https://user-images.githubusercontent.com/1717110/35111566-2ed95d28-fc41-11e7-83ba-a1506dada7c6.png">

5. Save/Publish this content. This error shows up 

<img width="1556" alt="screen shot 2018-01-18 at 11 11 16 am" src="https://user-images.githubusercontent.com/1717110/35111598-3c40494a-fc41-11e7-9492-19d73cbb7769.png">

And log files indicate a stacktrace similar to next one 

```
ERROR business.ESContentletAPIImpl: java.lang.String cannot be cast to java.lang.Long
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
        at com.dotmarketing.portlets.contentlet.model.Contentlet.getSortOrder(Contentlet.java:470) ~[dotcms_4.1.1_999999.jar:?]
        at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.convertContentletToFatContentlet(ESContentFactoryImpl.java:227) ~[dotcms_4.1.1_999999.jar:?]
        at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.save(ESContentFactoryImpl.java:1504) ~[dotcms_4.1.1_999999.jar:?]
        at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.save(ESContentFactoryImpl.java:1495) ~[dotcms_4.1.1_999999.jar:?]
        at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2878) [dotcms_4.1.1_999999.jar:?]
        at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:5592) [dotcms_4.1.1_999999.jar:?]
        at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkin(ContentletAPIInterceptor.java:149) [dotcms_4.1.1_999999.jar:?]
        at com.dotmarketing.portlets.contentlet.business.web.ContentletWebAPIImpl._saveWebAsset(ContentletWebAPIImpl.java:609) [dotcms_4.1.1_999999.jar:?]
        at com.dotmarketing.portlets.contentlet.business.web.ContentletWebAPIImpl.saveContent(ContentletWebAPIImpl.java:159) [dotcms_4.1.1_999999.jar:?]
        at com.dotmarketing.portlets.contentlet.ajax.ContentletAjax.saveContent(ContentletAjax.java:1374) [dotcms_4.1.1_999999.jar:?]
        at sun.reflect.GeneratedMethodAccessor3151.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule$1.doFilter(CreatorModule.java:229) [dot.dwr-3rc2modified_2.jar:?]
        at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule.executeMethod(CreatorModule.java:241) [dot.dwr-3rc2modified_2.jar:?]
        at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:379) [dot.dwr-3rc2modified_2.jar:?]
        at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:332) [dot.dwr-3rc2modified_2.jar:?]
        at com.dotcms.repackage.org.directwebremoting.dwrp.BaseCallHandler.handle(BaseCallHandler.java:104) [dot.dwr-3rc2modified_2.jar:?]
        at com.dotcms.repackage.org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:120) [dot.dwr-3rc2modified_2.jar:?]
        at com.dotcms.repackage.org.directwebremoting.servlet.DwrServlet.doPost(DwrServlet.java:141) [dot.dwr-3rc2modified_2.jar:?]
        at com.dotmarketing.servlets.DwrWrapperServlet.doPost(DwrWrapperServlet.java:62) [DwrWrapperServlet.class:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:644) [servlet-api.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:265) [dotcms_4.1.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.1.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.1.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:308) [dotcms_4.1.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:134) [dotcms_4.1.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_4.1.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) [dotcms_4.1.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:110) [dotcms_4.1.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:673) [catalina.jar:8.0.18]
```

## Context
This can be reproduced on our latest release (4.2.2) and it was reported by a customer: https://dotcms.zendesk.com/agent/tickets/95106

## Your Environment

* dotCMS version used: 4.1.1, 4.2.2.
* Browser Name and version: Firefox, Chrome.
* Operating System and version: Any OS.
* Application Server and version: Any supported application server.
* Java Brand and version: any supported Java 8 version.
* Database and version: Any DB.
* Application module (if apply): N/A

**Comment by joseorsini** [comment]
If field is deleted and re-created as "sortOrder1", actions over Radio buttons work just normal. This conflict is caused by having "sortOrder" as a field's VelocityVarName.

**Comment by oarrietadotcms** [comment]
Client hit this error in 4.3.3 but it is still reproducible in latest 5.1.6.

Ticket: https://dotcms.zendesk.com/agent/tickets/98591
