### ISSUE TITLE
[Content Import] Updating content of a type associated to a mandatory workflow is failing

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#13559]
Reproducible in https://demo.dotcms.com/c (4.2.2)
Reported via Support: https://dotcms.zendesk.com/agent/tickets/95086

**NOTE: In latest master, the Content Import is not even allowing to add new content because of a different error.**

When importing existing contents via a CSV file, such contents go through the usual checkin process which takes into account the Workflow associated to its Content Type. When the Workflow is mandatory, the content is not being updated, and an "empty" success message is displayed in the results page.

**NOTE: Adding new content is working correctly. The problem only shows up when updating content.**

**NOTE: The fix for this issue must also be included in the Content Import plugin: https://github.com/dotCMS/plugin-content-import-export**

## Expected Behavior
Users must be able to update content via CSV files.

## Current Behavior
Depending on the configuration of the Workflow associated to the Content Type, updating content can fail without displaying any error message in the results page.

## Possible Solution
The checkin call where the import process is failing is here: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/util/ImportUtil.java?utf8=%E2%9C%93#L1292

After discussing with @joseorsini we believe that adding the missing `Contentlet.WORKFLOW_ACTION_KEY` property to the contentlet map would fix the NPE, and would allow mandatory Workflows to correctly find the default action.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)
1. Log into the Demo Site and create a Content Type called "My Test". Set the Workflow to "Document Management".
2. Create two text fields: "Title", and "Description".
3. Go to the **Search** portlet > select the "My Test" type.
4. Create two sample contentlets of type "My Test" with these values: ["Title 1", "First test"], and ["Title 2", "Second test"].
5. Now, click "Add New Content" > "Import Content" > click the "Click here to download a CSV sample file" link to download the import template.
6. Add these values to the CSV file: ["Title 1", "Updated value"], and ["Title 2", "Updated value"]
7. Check the "Title" field in the "Key Fields", and click "Got to Preview".
8. Notice the warnings stating that the contents already exist. Finally, click "Import Content".
9. You will see an "empty" success message, and errors in the log similar to these:
```
[05/02/18 11:25:28:978 EST] INFO ajax.PermissionAjax: ##=> permissionMap: {inode=48190c8c-42c4-46af-8d1a-0cd5db894797, roleId=654b0931-1027-41f7-ad4d-173115ed8ec1, permission=3, id=12224, type=individual, isBitPermission=true}
[05/02/18 11:25:31:128 EST] INFO cluster.metadata: [a83fd805-5c45-4a82-8354-1077c0ef7216] [working_20180205000316] update_mapping [content] (dynamic)
[05/02/18 11:25:45:265 EST] INFO util.ImportUtil: 4 lines read correctly. 0 errors found.
[05/02/18 11:26:06:509 EST] INFO util.ImportUtil: 4 lines read correctly. 0 errors found.
[05/02/18 11:26:13:876 EST] INFO action.ImportContentletsAction: UserId : dotcms.org.1 : processAction : Importing Contentlets
[05/02/18 11:26:13:881 EST] ERROR business.ESContentletAPIImpl: A Workflow Action is mandatory for content of type:Prueba
com.dotmarketing.portlets.workflows.business.DotWorkflowException: A Workflow Action is mandatory for content of type:Prueba
at com.dotmarketing.portlets.workflows.model.WorkflowProcessor.<init>(WorkflowProcessor.java:154) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireWorkflowPreCheckin(WorkflowAPIImpl.java:775) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin_aroundBody98(ESContentletAPIImpl.java:2950) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure99.run(ESContentletAPIImpl.java:1) ~[dotcms_4.2.2_999999.jar:?]
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:39) [dotcms_4.2.2_999999.jar:?]
at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) [dotcms_4.2.2_999999.jar:?]
at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) [dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2841) [dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2805) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkin(ContentletAPIInterceptor.java:132) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.util.ImportUtil.importLine(ImportUtil.java:1292) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.util.ImportUtil.importFile(ImportUtil.java:240) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction._processFile(ImportContentletsAction.java:509) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction.access$1(ImportContentletsAction.java:501) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction$1.run(ImportContentletsAction.java:243) [dotcms_4.2.2_999999.jar:?]
[05/02/18 11:26:13:882 EST] ERROR util.ImportUtil: A Workflow Action is mandatory for content of type:Prueba
com.dotmarketing.portlets.workflows.business.DotWorkflowException: A Workflow Action is mandatory for content of type:Prueba
at com.dotmarketing.portlets.workflows.model.WorkflowProcessor.<init>(WorkflowProcessor.java:154) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireWorkflowPreCheckin(WorkflowAPIImpl.java:775) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin_aroundBody98(ESContentletAPIImpl.java:2950) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure99.run(ESContentletAPIImpl.java:1) ~[dotcms_4.2.2_999999.jar:?]
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:39) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2841) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2805) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkin(ContentletAPIInterceptor.java:132) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.util.ImportUtil.importLine(ImportUtil.java:1292) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.util.ImportUtil.importFile(ImportUtil.java:240) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction._processFile(ImportContentletsAction.java:509) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction.access$1(ImportContentletsAction.java:501) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction$1.run(ImportContentletsAction.java:243) [dotcms_4.2.2_999999.jar:?]
[05/02/18 11:26:13:882 EST] INFO util.ImportUtil: Error line: 1 (Titulo 1,bbbbb). Line Ignored.
[05/02/18 11:26:13:884 EST] ERROR business.ESContentletAPIImpl: A Workflow Action is mandatory for content of type:Prueba
com.dotmarketing.portlets.workflows.business.DotWorkflowException: A Workflow Action is mandatory for content of type:Prueba
at com.dotmarketing.portlets.workflows.model.WorkflowProcessor.<init>(WorkflowProcessor.java:154) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireWorkflowPreCheckin(WorkflowAPIImpl.java:775) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin_aroundBody98(ESContentletAPIImpl.java:2950) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure99.run(ESContentletAPIImpl.java:1) ~[dotcms_4.2.2_999999.jar:?]
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:39) [dotcms_4.2.2_999999.jar:?]
at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) [dotcms_4.2.2_999999.jar:?]
at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) [dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2841) [dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2805) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkin(ContentletAPIInterceptor.java:132) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.util.ImportUtil.importLine(ImportUtil.java:1292) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.util.ImportUtil.importFile(ImportUtil.java:240) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction._processFile(ImportContentletsAction.java:509) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction.access$1(ImportContentletsAction.java:501) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction$1.run(ImportContentletsAction.java:243) [dotcms_4.2.2_999999.jar:?]
[05/02/18 11:26:13:884 EST] ERROR util.ImportUtil: A Workflow Action is mandatory for content of type:Prueba
com.dotmarketing.portlets.workflows.business.DotWorkflowException: A Workflow Action is mandatory for content of type:Prueba
at com.dotmarketing.portlets.workflows.model.WorkflowProcessor.<init>(WorkflowProcessor.java:154) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireWorkflowPreCheckin(WorkflowAPIImpl.java:775) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin_aroundBody98(ESContentletAPIImpl.java:2950) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure99.run(ESContentletAPIImpl.java:1) ~[dotcms_4.2.2_999999.jar:?]
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:39) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2841) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2805) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkin(ContentletAPIInterceptor.java:132) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.util.ImportUtil.importLine(ImportUtil.java:1292) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.util.ImportUtil.importFile(ImportUtil.java:240) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction._processFile(ImportContentletsAction.java:509) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction.access$1(ImportContentletsAction.java:501) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction$1.run(ImportContentletsAction.java:243) [dotcms_4.2.2_999999.jar:?]
[05/02/18 11:26:13:884 EST] INFO util.ImportUtil: Error line: 2 (titulo 2,bbbbb). Line Ignored.
[05/02/18 11:26:13:887 EST] ERROR business.ESContentletAPIImpl: A Workflow Action is mandatory for content of type:Prueba
com.dotmarketing.portlets.workflows.business.DotWorkflowException: A Workflow Action is mandatory for content of type:Prueba
at com.dotmarketing.portlets.workflows.model.WorkflowProcessor.<init>(WorkflowProcessor.java:154) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireWorkflowPreCheckin(WorkflowAPIImpl.java:775) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin_aroundBody98(ESContentletAPIImpl.java:2950) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure99.run(ESContentletAPIImpl.java:1) ~[dotcms_4.2.2_999999.jar:?]
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:39) [dotcms_4.2.2_999999.jar:?]
at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) [dotcms_4.2.2_999999.jar:?]
at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) [dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2841) [dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2805) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkin(ContentletAPIInterceptor.java:132) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.util.ImportUtil.importLine(ImportUtil.java:1292) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.util.ImportUtil.importFile(ImportUtil.java:240) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction._processFile(ImportContentletsAction.java:509) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction.access$1(ImportContentletsAction.java:501) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction$1.run(ImportContentletsAction.java:243) [dotcms_4.2.2_999999.jar:?]
[05/02/18 11:26:13:887 EST] ERROR util.ImportUtil: A Workflow Action is mandatory for content of type:Prueba
com.dotmarketing.portlets.workflows.business.DotWorkflowException: A Workflow Action is mandatory for content of type:Prueba
at com.dotmarketing.portlets.workflows.model.WorkflowProcessor.<init>(WorkflowProcessor.java:154) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireWorkflowPreCheckin(WorkflowAPIImpl.java:775) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin_aroundBody98(ESContentletAPIImpl.java:2950) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure99.run(ESContentletAPIImpl.java:1) ~[dotcms_4.2.2_999999.jar:?]
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:39) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2841) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2805) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkin(ContentletAPIInterceptor.java:132) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.util.ImportUtil.importLine(ImportUtil.java:1292) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.util.ImportUtil.importFile(ImportUtil.java:240) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction._processFile(ImportContentletsAction.java:509) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction.access$1(ImportContentletsAction.java:501) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction$1.run(ImportContentletsAction.java:243) [dotcms_4.2.2_999999.jar:?]
[05/02/18 11:26:13:887 EST] INFO util.ImportUtil: Error line: 3 (titulo 3,bbbbb). Line Ignored.
[05/02/18 11:26:13:889 EST] ERROR business.ESContentletAPIImpl: A Workflow Action is mandatory for content of type:Prueba
com.dotmarketing.portlets.workflows.business.DotWorkflowException: A Workflow Action is mandatory for content of type:Prueba
at com.dotmarketing.portlets.workflows.model.WorkflowProcessor.<init>(WorkflowProcessor.java:154) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireWorkflowPreCheckin(WorkflowAPIImpl.java:775) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin_aroundBody98(ESContentletAPIImpl.java:2950) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure99.run(ESContentletAPIImpl.java:1) ~[dotcms_4.2.2_999999.jar:?]
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:39) [dotcms_4.2.2_999999.jar:?]
at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) [dotcms_4.2.2_999999.jar:?]
at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) [dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2841) [dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2805) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkin(ContentletAPIInterceptor.java:132) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.util.ImportUtil.importLine(ImportUtil.java:1292) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.util.ImportUtil.importFile(ImportUtil.java:240) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction._processFile(ImportContentletsAction.java:509) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction.access$1(ImportContentletsAction.java:501) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction$1.run(ImportContentletsAction.java:243) [dotcms_4.2.2_999999.jar:?]
[05/02/18 11:26:13:889 EST] ERROR util.ImportUtil: A Workflow Action is mandatory for content of type:Prueba
com.dotmarketing.portlets.workflows.business.DotWorkflowException: A Workflow Action is mandatory for content of type:Prueba
at com.dotmarketing.portlets.workflows.model.WorkflowProcessor.<init>(WorkflowProcessor.java:154) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireWorkflowPreCheckin(WorkflowAPIImpl.java:775) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin_aroundBody98(ESContentletAPIImpl.java:2950) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure99.run(ESContentletAPIImpl.java:1) ~[dotcms_4.2.2_999999.jar:?]
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:39) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2841) ~[dotcms_4.2.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2805) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkin(ContentletAPIInterceptor.java:132) ~[dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.util.ImportUtil.importLine(ImportUtil.java:1292) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.util.ImportUtil.importFile(ImportUtil.java:240) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction._processFile(ImportContentletsAction.java:509) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction.access$1(ImportContentletsAction.java:501) [dotcms_4.2.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction$1.run(ImportContentletsAction.java:243) [dotcms_4.2.2_999999.jar:?]
[05/02/18 11:26:13:889 EST] INFO util.ImportUtil: Error line: 4 (titulo 4,bbbbb). Line Ignored.
[05/02/18 11:26:13:889 EST] INFO util.ImportUtil: 4 lines read correctly. 4 errors found.
[05/02/18 11:26:14:902 EST] INFO action.ImportContentletsAction: UserId : dotcms.org.1 : processAction : Importing Contentlets
```

## Context
This is preventing users from updating contents whose Content Type is associated to a mandatory workflow.

## Your Environment
* dotCMS version used: 4.1.1, 4.2.2
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module (if apply): Content Import.

**Comment by wezell** [comment]
The checkin methods should handle this at the api level.  Also, @jgambarios @bryanboza we will need to test this case in 5.x

**Comment by jcastro-dotcms** [comment]
After analyzing the https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/action/ImportContentletsAction.java#L243 class and the https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/portlet/ext/contentlet/import_contentlets_results.jsp file, it seems like we need to also improve the display of potential errors in the UI when trying to import content.

**Comment by jgambarios** [comment]
@bryanboza this should not be a problem in 5.x

**Comment by bryanboza** [comment]
Unable to reproduce on master, since we remove the mandatory workflows in 5.x. Tested with the same steps and this is working fine. We have multiple changes in the import process, now you need select the action to execute to this contents.
