### ISSUE TITLE
websocket connection is not reestablished

### ISSUE THREAD

**Issue by vianneychacon** [dotCMS/core#13654]
Under some scenarios, the _websocket_ connection is interrupted but the backend session remains active. Once the _websocket_ connection is broken it won't reestablish until the user logs in again

## Expected Behavior

The websocket connection should be reestablished or switch to the alternative method

## Current Behavior

An exception is logged and the ws connection is lost (the user will not receive events notifications). 
```
[15/02/18 06:32:19:229 EST] ERROR websocket.SystemEventsWebSocketEndPoint: java.util.concurrent.ExecutionException: java.io.IOException: Broken pipe
java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: Broken pipe
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessageBlock(WsRemoteEndpointImplBase.java:282) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPing(WsRemoteEndpointImplBase.java:174) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.WsRemoteEndpointBase.sendPing(WsRemoteEndpointBase.java:55) ~[tomcat-websocket.jar:8.0.18]
        at com.dotcms.rest.api.v1.system.websocket.SystemEventsWebSocketEndPoint.doPing(SystemEventsWebSocketEndPoint.java:116) ~[dotcms_4.2.2_999999.jar:?]
        at com.dotcms.rest.api.v1.system.websocket.SystemEventsWebSocketEndPoint.processPingPongQueue(SystemEventsWebSocketEndPoint.java:95) ~[dotcms_4.2.2_999999.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Broken pipe
        at org.apache.tomcat.websocket.FutureToSendHandler.get(FutureToSendHandler.java:102) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessageBlock(WsRemoteEndpointImplBase.java:275) ~[tomcat-websocket.jar:8.0.18]
        ... 11 more
Caused by: java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:1.8.0_151]
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[?:1.8.0_151]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[?:1.8.0_151]
        at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[?:1.8.0_151]
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[?:1.8.0_151]
        at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:127) ~[tomcat-coyote.jar:8.0.18]
        at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:184) ~[tomcat-coyote.jar:8.0.18]
        at org.apache.coyote.http11.upgrade.NioServletOutputStream.doWriteInternal(NioServletOutputStream.java:94) ~[tomcat-coyote.jar:8.0.18]
        at org.apache.coyote.http11.upgrade.NioServletOutputStream.doWrite(NioServletOutputStream.java:61) ~[tomcat-coyote.jar:8.0.18]
        at org.apache.coyote.http11.upgrade.AbstractServletOutputStream.writeInternal(AbstractServletOutputStream.java:162) ~[tomcat-coyote.jar:8.0.18]
        at org.apache.coyote.http11.upgrade.AbstractServletOutputStream.write(AbstractServletOutputStream.java:129) ~[tomcat-coyote.jar:8.0.18]
        at org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer.onWritePossible(WsRemoteEndpointImplServer.java:99) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer.doWrite(WsRemoteEndpointImplServer.java:81) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:450) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessage(WsRemoteEndpointImplBase.java:338) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessageBlock(WsRemoteEndpointImplBase.java:270) ~[tomcat-websocket.jar:8.0.18]
... 11 more
```
or
```
15/02/18 06:19:19:224 EST] ERROR websocket.SystemEventsWebSocketEndPoint: java.util.concurrent.TimeoutException
java.io.IOException: java.util.concurrent.TimeoutException
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessageBlock(WsRemoteEndpointImplBase.java:282) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPing(WsRemoteEndpointImplBase.java:174) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.WsRemoteEndpointBase.sendPing(WsRemoteEndpointBase.java:55) ~[tomcat-websocket.jar:8.0.18]
        at com.dotcms.rest.api.v1.system.websocket.SystemEventsWebSocketEndPoint.doPing(SystemEventsWebSocketEndPoint.java:116) ~[dotcms_4.2.2_999999.jar:?]
        at com.dotcms.rest.api.v1.system.websocket.SystemEventsWebSocketEndPoint.processPingPongQueue(SystemEventsWebSocketEndPoint.java:95) ~[dotcms_4.2.2_999999.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.util.concurrent.TimeoutException
        at org.apache.tomcat.websocket.FutureToSendHandler.get(FutureToSendHandler.java:99) ~[tomcat-websocket.jar:8.0.18]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessageBlock(WsRemoteEndpointImplBase.java:275) ~[tomcat-websocket.jar:8.0.18]
... 11 more
```
Refreshing the page seems to try to reestablish the connection, but when the event comes in (a reindex notification for example) it fails
## Steps to Reproduce (for bugs)

1. Log into the backend
2. Put the client machine (were the browser is running) to **sleep** keeping the session open (could be a VM). I've been able to reproduce it sometimes by just leaving the tab opened without browser's activity
3. Wait until the exception is logged in _dotcms.log_
4. Wake up the machine and check that the session is still active but there are no notifications

## Context

dotCMS is running behind a reverse-proxy

## Your Environment

* dotCMS version used: 4.2.2
* Browser Name and version: Firefox 58.0.2
* Operating System and version: AWS Linux
* Application Server and version: Embedded tomcat
* Java Brand and version: OpenJDK 1.8
* Database and version: Postgresql

**Comment by jdotcms** [comment]
we have added a couple fixes to remove the session when the broken pipe and timeout happens, in addition we have added 2 properties

dotcms.websocket.millis.ping.timeout: Time out to wait for a ping/pong in seconds


dotcms.websocket.maxidletimeout: Time in millis to keep the sesion idle.


In addition Fox needs to check if the socket connection is reestablish when the browser is back fro idle state.

**Comment by bryanboza** [comment]
Fixed unable to reproduce after leaving the computer sleep more than 4 hours
