### ISSUE TITLE
[Contentlets] Deleting a language-version content does not delete its own old versions.

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#13682]
## Expected Behavior
If we're requesting a language-based version of a content to be deleted, it should be fully deleted along with all versions under the same language Id.

## Current Behavior
We're deleting only the current live/working version of it, and old versions of contents under the same language remain in the Database as orphan contents. 

## Possible Solution
Fix the way we iterate through all versions of a content given its identifier and language id, and delete them.

## Known Workarounds
None. 

## Steps to Reproduce (for bugs)

1. Create a Content (Generic) content, in English and Spanish.
2. Edit the Spanish version of the content several times, so the History Tab shows that there's one or more old versions of the content in Spanish Language.

<img width="1023" alt="screen shot 2018-02-21 at 5 20 32 pm" src="https://user-images.githubusercontent.com/1717110/36511481-6e3cb4d2-172c-11e8-9e3b-10adf60e3067.png">

3. Go back to Content tool and list all Content (Generic) contents in Spanish language.
4. Delete the Spanish version of the content you created in Step 1.
5. Open the content in English, and open its History tab. It shows "Sorry, an error occurred".

<img width="1413" alt="screen shot 2018-02-21 at 5 27 45 pm" src="https://user-images.githubusercontent.com/1717110/36511692-488d6960-172d-11e8-8361-111dcb4b08c4.png">

Stacktrace in dotcms.log file: 

```
[21/02/18 17:27:44:227 CST]  WARN error.custom_002derror_002dpage_jsp:  on /html/error/custom-error-page.jsp
```

Stacktrace on localhost-timestamp_based.log file

```
018 17:28:34.974 SEVERE [http-nio-8080-exec-3] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [] threw exception [java.lang.NullPointerException] with root cause
 java.lang.NullPointerException
	at org.apache.jsp.html.portlet.ext.contentlet.contentlet_005fversions_005finc_jsp._jspService(contentlet_005fversions_005finc_jsp.java:584)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:203)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:325)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:110)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:132)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:38)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

Data before deleting the Spanish version of content
```
dotcms422=# SELECT identifier, inode, title, mod_date, language_id from contentlet where identifier = 'a3cffe05-c9a7-458a-97b1-a4eae05ba60d' order by language_id asc, mod_date desc;
              identifier              |                inode                 |      title       |        mod_date         | language_id 
--------------------------------------+--------------------------------------+------------------+-------------------------+-------------
 a3cffe05-c9a7-458a-97b1-a4eae05ba60d | 88b26370-610c-453c-9408-97f119f26d14 | Test Content 001 | 2018-02-21 17:19:50.458 |           1
 a3cffe05-c9a7-458a-97b1-a4eae05ba60d | 0e5def95-570f-4475-bc50-991b57f9064e | Test Content 001 | 2018-02-21 17:20:21.143 |           2
 a3cffe05-c9a7-458a-97b1-a4eae05ba60d | 1296eda0-d999-4094-a9df-03bbb578dd99 | Test Content 001 | 2018-02-21 17:20:05.227 |           2
(3 rows)

dotcms422=# select * from contentlet_version_info where identifier = 'a3cffe05-c9a7-458a-97b1-a4eae05ba60d' order by lang asc;
              identifier              | lang |            working_inode             |              live_inode              | deleted | locked_by |        locked_on        |       version_ts        
--------------------------------------+------+--------------------------------------+--------------------------------------+---------+-----------+-------------------------+-------------------------
 a3cffe05-c9a7-458a-97b1-a4eae05ba60d |    1 | 88b26370-610c-453c-9408-97f119f26d14 | 88b26370-610c-453c-9408-97f119f26d14 | f       |           | 2018-02-21 17:19:50.586 | 2018-02-21 17:19:50.635
 a3cffe05-c9a7-458a-97b1-a4eae05ba60d |    2 | 0e5def95-570f-4475-bc50-991b57f9064e | 0e5def95-570f-4475-bc50-991b57f9064e | f       |           | 2018-02-21 17:20:21.193 | 2018-02-21 17:20:21.175
(2 rows)

```

Data **AFTER** Spanish version is deleted. See there's an orphan entry in contentlet table, that belongs to the old version of the Spanish-version content we just deleted.

```
dotcms422=# SELECT identifier, inode, title, mod_date, language_id from contentlet where identifier = 'a3cffe05-c9a7-458a-97b1-a4eae05ba60d' order by language_id asc, mod_date desc;
              identifier              |                inode                 |      title       |        mod_date         | language_id 
--------------------------------------+--------------------------------------+------------------+-------------------------+-------------
 a3cffe05-c9a7-458a-97b1-a4eae05ba60d | 88b26370-610c-453c-9408-97f119f26d14 | Test Content 001 | 2018-02-21 17:19:50.458 |           1
 a3cffe05-c9a7-458a-97b1-a4eae05ba60d | 1296eda0-d999-4094-a9df-03bbb578dd99 | Test Content 001 | 2018-02-21 17:20:05.227 |           2
(2 rows)

dotcms422=# select * from contentlet_version_info where identifier = 'a3cffe05-c9a7-458a-97b1-a4eae05ba60d' order by lang asc;
              identifier              | lang |            working_inode             |              live_inode              | deleted | locked_by |        locked_on        |       version_ts        
--------------------------------------+------+--------------------------------------+--------------------------------------+---------+-----------+-------------------------+-------------------------
 a3cffe05-c9a7-458a-97b1-a4eae05ba60d |    1 | 88b26370-610c-453c-9408-97f119f26d14 | 88b26370-610c-453c-9408-97f119f26d14 | f       |           | 2018-02-21 17:19:50.586 | 2018-02-21 17:19:50.635
(1 row)
```

## Context
Reported by customer: https://dotcms.zendesk.com/agent/tickets/95335 
Also it can be reproduced on latest stable release.

## Your Environment

* dotCMS version used: 3.7.x, 4.2.2.
* Browser Name and version: Any Browser.
* Operating System and version: Any OS.
* Application Server and version: Any supported application version.
* Java Brand and version: Any supported Java 8 Version.
* Database and version: Any supported DB engine.
* Application module (if apply): N/A.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14149
