### ISSUE TITLE
Add explicit support of UTF-8 Encoding for files handling in JAVA_OPTS

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#13693]
## Current Behavior
If the sun.jnu.encoding System property is not set to UTF-8, there might be problems when uploading files to the application, specially if they contain special characters that should be natively supported by most OS.

In some cases, this property might be set to an unsupported encoding, like ANSI_X3.4-1968. Since this is set directly at system level, any JVM process will inherit this property and affect how files are handled and stored in system. 

## Possible Solution
Explicitly add this property to the startup scripts.

## Known Workarounds
None.
## Steps to Reproduce (for bugs)

1. While the server is down, add this line of code on line 70 of bin/startup.sh file

```
JAVA_OPTS="$JAVA_OPTS -Dsun.jnu.encoding=ANSI_X3.4-1968"

```
2. Start the server.
3. On any site/folder, make sure to upload a file with special characters, like `questions? Answers’ replied here.pdf`. 
4. Content is not created, and System will thrown an error: 

```
[22/02/18 12:16:45:117 CST] ERROR ajax.ContentletAjax: can't make a copy of the uploaded file:java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /Users/joseorsini/dotCMS/releases/4.2.2-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/tmp_upload/dotcms.org.1/binary3/00f6daa6-eaea-4093-8ef2-d68682f161ce/questions Answers’ replied here.pdf
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /Users/joseorsini/dotCMS/releases/4.2.2-dist/dotserver/tomcat-8.0.18/webapps/ROOT/assets/tmp_upload/dotcms.org.1/binary3/00f6daa6-eaea-4093-8ef2-d68682f161ce/questions Answers’ replied here.pdf
  at sun.nio.fs.UnixPath.encode(UnixPath.java:147) ~[?:1.8.0_121]
  at sun.nio.fs.UnixPath.<init>(UnixPath.java:71) ~[?:1.8.0_121]
  at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281) ~[?:1.8.0_121]
  at java.nio.file.Paths.get(Paths.java:84) ~[?:1.8.0_121]
  at com.liferay.util.FileUtil.copyFile(FileUtil.java:194) ~[dotcms_4.2.2_999999.jar:?]
  at com.liferay.util.FileUtil.copyFile(FileUtil.java:157) ~[dotcms_4.2.2_999999.jar:?]
  at com.liferay.util.FileUtil.copyFile(FileUtil.java:140) ~[dotcms_4.2.2_999999.jar:?]
  at com.dotmarketing.portlets.contentlet.ajax.ContentletAjax.saveContent(ContentletAjax.java:1348) [dotcms_4.2.2_999999.jar:?]
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
```

## Context
Reported by customer: https://dotcms.zendesk.com/agent/tickets/95310 

## Your Environment

* dotCMS version used: 4.2.2.
* Browser Name and version: Any Browser.
* Operating System and version: Any operating system.
* Application Server and version: Any supported Application server.
* Java Brand and version: Any Java version.
* Database and version: Any supported DB engine.
* Application module (if apply): N/A.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/tomcat/pull/6

**Comment by bryanboza** [comment]
Now we have this encoding in the "dotStartup" file but we need include this in the startup too for the distro.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14776

**Comment by bryanboza** [comment]
Fixed, tested on master and now we have the change in all the files
