### ISSUE TITLE
[PushPublishing] Avoid NPE when local history of Bundle still being pushed is updated

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#13733]
Given certain circumstances where bundles being pushed to remote environments take more than one minute to be completed, the sender environment requests updates from these bundles but fail to retrieve more information since they're still being processed by remote endpoints. Specifically, attributes like Publish End Date, which end up being populated for every PublishAuditHistory, remains a a null value on remote environments, and comparing this data against local history (on sender) of these bundles 

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/publisher/business/PublisherQueueJob.java#L423-L428

Return a null pointer exception

```
[26/02/18 21:44:00:035 GMT] ERROR business.PublisherQueueJob: An error occurred when accessing end-point 'remote-env.dotcms.com' with IP remote-env.dotcms.com: null
java.lang.NullPointerException
       at com.dotcms.publisher.business.PublisherQueueJob.updateLocalPublishDatesFromRemote(PublisherQueueJob.java:417) ~[dotcms_4.2.0_999999.jar:?]
       at com.dotcms.publisher.business.PublisherQueueJob.collectEndpointInfoFromRemote(PublisherQueueJob.java:282) [dotcms_4.2.0_999999.jar:?]
       at com.dotcms.publisher.business.PublisherQueueJob.updateAuditStatus(PublisherQueueJob.java:243) [dotcms_4.2.0_999999.jar:?]
       at com.dotcms.publisher.business.PublisherQueueJob.execute(PublisherQueueJob.java:111) [dotcms_4.2.0_999999.jar:?]
       at org.quartz.core.JobRunShell.run(JobRunShell.java:223) [dot.quartz-all-1.8.6_2.jar:?]
       at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) [dot.quartz-all-1.8.6_2.jar:?]
```

## Expected Behavior
Update the local history of pushed bundles if we have a valid History record pulled from all remote endpoints this bundle was pushed to.

## Current Behavior
It fails at retrieving this information and store it locally, indicating any potential false positive/negative status about the bundle that's being processed.

## Known Workarounds
None.

## Context
Reported by customer: https://dotcms.zendesk.com/agent/tickets/95324

## Your Environment

* dotCMS version used: 4.2.2
* Browser Name and version: any Browser.
* Operating System and version: any Operating system.
* Application Server and version: Any supported application server.
* Java Brand and version:  Any supported Java 8 version.
* Database and version: Any supported DB and engine.
* Application module (if apply): N/A.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/13734
