### ISSUE TITLE
Receive from 0.0.0.0/0 netmask check fails in 5.0

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13742]
When setting up a pp environment and you add "Receive From" 0.0.0.0/0 and then try to run the integrity checker, you get this:
```
00:41:17.889  ERROR rest.IntegrityResource - Error caused by remote call of: 173.162.126.242
00:41:17.890  ERROR rest.IntegrityResource - Value [0] not in range (0,32]
java.lang.IllegalArgumentException: Value [0] not in range (0,32]
	at com.dotcms.repackage.org.apache.commons.net.util.SubnetUtils.rangeCheck(SubnetUtils.java:304) ~[dot.commons-net-3.3_2.jar:3.3]
	at com.dotcms.repackage.org.apache.commons.net.util.SubnetUtils.calculate(SubnetUtils.java:229) ~[dot.commons-net-3.3_2.jar:3.3]
	at com.dotcms.repackage.org.apache.commons.net.util.SubnetUtils.<init>(SubnetUtils.java:52) ~[dot.commons-net-3.3_2.jar:3.3]
	at com.dotcms.publisher.endpoint.business.PublishingEndPointFactoryImpl.validateAddress(PublishingEndPointFactoryImpl.java:151) ~[dotcms_5.0.0_e4b92d8.jar:?]
	at com.dotcms.publisher.endpoint.business.PublishingEndPointFactoryImpl.getEnabledSendingEndPointByAddress(PublishingEndPointFactoryImpl.java:141) ~[dotcms_5.0.0_e4b92d8.jar:?]
	at com.dotcms.publisher.endpoint.business.PublishingEndPointAPIImpl.findEnabledSendingEndPointByAddress_aroundBody14(PublishingEndPointAPIImpl.java:95) ~[dotcms_5.0.0_e4b92d8.jar:?]
	at com.dotcms.publisher.endpoint.business.PublishingEndPointAPIImpl$AjcClosure15.run(PublishingEndPointAPIImpl.java:1) ~[dotcms_5.0.0_e4b92d8.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_5.0.0_e4b92d8.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.0.0_e4b92d8.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.0.0_e4b92d8.jar:?]
	at com.dotcms.publisher.endpoint.business.PublishingEndPointAPIImpl.findEnabledSendingEndPointByAddress(PublishingEndPointAPIImpl.java:94) ~[dotcms_5.0.0_e4b92d8.jar:?]
	at com.dotcms.rest.IntegrityResource.generateIntegrityData(IntegrityResource.java:184) [dotcms_5.0.0_e4b92d8.jar:?
```

**Comment by wezell** [comment]
This seems to be the issue:

https://stackoverflow.com/questions/21854156/commons-net-3-3-subnetutils-does-not-allow-0-0-0-0-0

**Comment by wezell** [comment]
https://stackoverflow.com/questions/21854156/commons-net-3-3-subnetutils-does-not-allow-0-0-0-0-0
