### ISSUE TITLE
Copy Template fails

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13855]
```
11:35:36.825  INFO  util.ActivityLogger - class com.dotmarketing.portlets.templates.action.EditTemplateAction: demo.dotcms.com : Edit Template action , User dotcms.org.1 edit template Quest - 2 Column (Right Bar)
11:37:05.140  WARN  cache.LegacyContentTypeCacheImpl - Structure with inode: '799f176a-d32e-4844-a07c-1b5fcd107578' not found in db
11:37:05.141  WARN  cache.LegacyContentTypeCacheImpl - Structure with inode: '799f176a-d32e-4844-a07c-1b5fcd107578' not found in db
11:38:05.089  WARN  action.EditTemplateAction - com.dotmarketing.exception.DotHibernateException: Unable to save Object with primary key 0145f865-ad2a-43ef-b71d-272cd67883cd to Hibernate Session 
com.dotmarketing.exception.DotHibernateException: Unable to save Object with primary key 0145f865-ad2a-43ef-b71d-272cd67883cd to Hibernate Session 
	at com.dotmarketing.db.HibernateUtil.saveWithPrimaryKey(HibernateUtil.java:1178) ~[classes/:?]
	at com.dotmarketing.portlets.templates.business.TemplateFactoryImpl.save(TemplateFactoryImpl.java:141) ~[classes/:?]
	at com.dotmarketing.portlets.templates.business.TemplateFactoryImpl.save(TemplateFactoryImpl.java:116) ~[classes/:?]
	at com.dotmarketing.portlets.templates.business.TemplateAPIImpl.save(TemplateAPIImpl.java:178) ~[classes/:?]
	at com.dotmarketing.portlets.templates.business.TemplateAPIImpl.copy(TemplateAPIImpl.java:144) ~[classes/:?]
	at com.dotmarketing.portlets.templates.business.TemplateAPIImpl.copy(TemplateAPIImpl.java:174) ~[classes/:?]
	at com.dotmarketing.portlets.templates.business.TemplateAPIImpl.copy(TemplateAPIImpl.java:86) ~[classes/:?]
	at com.dotmarketing.portlets.templates.action.EditTemplateAction._copyWebAsset(EditTemplateAction.java:739) ~[classes/:?]
	at com.dotmarketing.portlets.templates.action.EditTemplateAction.processAction(EditTemplateAction.java:480) [classes/:?]
	at com.liferay.portal.struts.PortletRequestProcessor.process(PortletRequestProcessor.java:125) [classes/:?]
	at com.liferay.portlet.StrutsPortlet.processAction(StrutsPortlet.java:113) [classes/:?]
	at com.liferay.portlet.CachePortlet.processAction(CachePortlet.java:130) [classes/:?]
	at com.liferay.portal.action.LayoutAction._processPortletRequest(LayoutAction.java:230) [classes/:?]
	at com.liferay.portal.action.LayoutAction._processActionRequest(LayoutAction.java:247) [classes/:?]
	at com.liferay.portal.action.LayoutAction.execute(LayoutAction.java:89) [classes/:?]
```

**Comment by erickgonzalez** [comment]
Not able to reproduce with the latest master. Been able to copy successfully templates (tried with locked, unlocked, a copy of a copy).
