### ISSUE TITLE
Broken index cluster health page

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#13913]
dotcms-5.0-snapshot-7a1c684:

When you click on the green/yellow/red box for Elasticsearch cluster health, it throws an error. Looks like a jsp problem as this gets logged:

```
20-Mar-2018 21:12:05.495 SEVERE [http-nio-8080-exec-4] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [] threw exception [Unable to compile class for JSP:

An error occurred at line: [20] in the jsp file: [/html/portlet/ext/cmsmaintenance/index_cluster_status.jsp]
Type mismatch: cannot convert from List<NodeStats> to NodeStats[]
17:
18: ESClient client=new ESClient();
19: NodesStatsResponse ns=client.getClient().admin().cluster().nodesStats(new NodesStatsRequest()).actionGet();
20: NodeStats[] nsArray=ns.getNodes();
21: %>
22: <strong>Cluster: <%=ns.getClusterName() %></strong>
23: <% for(int i=0;i<nsArray.length;i++) { %>


An error occurred at line: [27] in the jsp file: [/html/portlet/ext/cmsmaintenance/index_cluster_status.jsp]
The method name() is undefined for the type DiscoveryNode
24: <table class="listingTable">
25:    <tr>
26:       <td> <strong>Node name</strong> </td>
27:       <td> <%= nsArray[i].getNode().name() %> <%=nsArray[i].getNode().isMasterNode() ? "(master)" : ""  %> </td>
28:    </tr>
29:    <tr>
30:       <td> Site Name </td>


An error occurred at line: [35] in the jsp file: [/html/portlet/ext/cmsmaintenance/index_cluster_status.jsp]
The method address() is undefined for the type DiscoveryNode
32:    </tr>
33:    <tr>
34:       <td> Address </td>
35:       <td> <%= nsArray[i].getNode().address() %> </td>
36:    </tr>
37:    <tr>
38:       <td> Store Size </td>


Stacktrace:] with root cause
 org.apache.jasper.JasperException: Unable to compile class for JSP:

An error occurred at line: [20] in the jsp file: [/html/portlet/ext/cmsmaintenance/index_cluster_status.jsp]
Type mismatch: cannot convert from List<NodeStats> to NodeStats[]
17:
18: ESClient client=new ESClient();
19: NodesStatsResponse ns=client.getClient().admin().cluster().nodesStats(new NodesStatsRequest()).actionGet();
20: NodeStats[] nsArray=ns.getNodes();
21: %>
22: <strong>Cluster: <%=ns.getClusterName() %></strong>
23: <% for(int i=0;i<nsArray.length;i++) { %>


An error occurred at line: [27] in the jsp file: [/html/portlet/ext/cmsmaintenance/index_cluster_status.jsp]
The method name() is undefined for the type DiscoveryNode
24: <table class="listingTable">
25:    <tr>
26:       <td> <strong>Node name</strong> </td>
27:       <td> <%= nsArray[i].getNode().name() %> <%=nsArray[i].getNode().isMasterNode() ? "(master)" : ""  %> </td>
28:    </tr>
29:    <tr>
30:       <td> Site Name </td>


An error occurred at line: [35] in the jsp file: [/html/portlet/ext/cmsmaintenance/index_cluster_status.jsp]
The method address() is undefined for the type DiscoveryNode
32:    </tr>
33:    <tr>
34:       <td> Address </td>
35:       <td> <%= nsArray[i].getNode().address() %> </td>
36:    </tr>
37:    <tr>
38:       <td> Store Size </td>


Stacktrace:
	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:102)
	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:212)
	at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:457)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:379)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:351)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:335)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:595)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:368)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotmarketing.filters.CMSFilter.doFilterInternal(CMSFilter.java:200)
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:56)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:322)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:111)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:399)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:134)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:38)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:102)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/13922

**Comment by shaydotcms** [comment]
Passed QA
Index health shows appropriate data when clicking on it. No errors showing.
![image](https://user-images.githubusercontent.com/8741846/37860561-382384a6-2eed-11e8-9757-750144055934.png)

Tested on Mac OS 10.10 / Postgres 9.6.6 / Chrome v64.0.3282.167 / Tomcat 8 / Java 8.6
