### ISSUE TITLE
Empty Starter import fails for workflow schema

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13979]
So, using this as our starter worked before all our workflow changes:

https://github.com/dotCMS/empty-starter

Now, we get - my concern is that this is indicative of a bigger issue.

Also, we are eating the exception and this is going to for sure cause issues future forward.

```
Mar 26, 2018 9:32:24 AM org.apache.tomcat.jdbc.pool.ConnectionPool abandon
WARNING: Connection has been abandoned PooledConnection[com.mysql.jdbc.JDBC4Connection@2b92f443]:java.lang.Exception
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getThreadDump(ConnectionPool.java:1102)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:807)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:651)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:198)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:132)
	at com.dotmarketing.db.DbConnectionFactory.getConnection(DbConnectionFactory.java:151)
	at com.dotmarketing.db.HibernateUtil.startLocalTransactionIfNeeded(HibernateUtil.java:1089)
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:34)
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23)
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41)
	at com.dotmarketing.portlets.workflows.util.WorkflowImportExportUtil.importWorkflowExport(WorkflowImportExportUtil.java:109)
	at com.dotmarketing.portlets.workflows.util.WorkflowImportExportUtil.importWorkflowExport(WorkflowImportExportUtil.java:99)
	at com.dotmarketing.portlets.workflows.util.WorkflowImportExportUtil.importWorkflowExport(WorkflowImportExportUtil.java:76)
	at com.dotmarketing.util.ImportExportUtil.doImport(ImportExportUtil.java:729)

```

**Comment by jdotcms** [comment]
This happens when something before didn't close the connection

**Comment by bryanboza** [comment]
Fixed, unable to reproduce with the last master... Tested on master // MySQL // FF
