### ISSUE TITLE
Cluster error in master 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14033]
In the last master code we are having a cluster error, this when you apply the license 

## Expected Behavior
We should avoid this kind of errors 

## Current Behavior
In a clean install when you apply the license we are having a NumberFormatException 
```
11:06:00.015  ERROR cluster.ClusterFactory - Unable to rewire cluster:null
11:06:00.015  ERROR cluster.ClusterFactory - servers:[]
11:06:00.016  ERROR job.ServerHeartbeatJob - Could not get ServerUptime
com.dotmarketing.exception.DotRuntimeException: null
	at com.dotcms.enterprise.cluster.ClusterFactory.rewireClusterIfNeeded(SourceFile:270) ~[ee-5.0.0-SNAPSHOT.jar:?]
	at com.dotmarketing.quartz.job.ServerHeartbeatJob.execute(ServerHeartbeatJob.java:43) [dotcms_5.0.0_65cc5cb.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223) [dot.quartz-all-1.8.6_2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) [dot.quartz-all-1.8.6_2.jar:?]
Caused by: java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542) ~[?:1.8.0_40]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_40]
	at com.dotcms.content.elasticsearch.util.ESClient.setPortsToServer(ESClient.java:294) ~[dotcms_5.0.0_65cc5cb.jar:?]
	at com.dotcms.content.elasticsearch.util.ESClient.setClusterNode(ESClient.java:201) ~[dotcms_5.0.0_65cc5cb.jar:?]
	at com.dotcms.enterprise.cluster.ClusterFactory.b(SourceFile:321) ~[ee-5.0.0-SNAPSHOT.jar:?]
	at com.dotcms.enterprise.cluster.ClusterFactory.addMeToCluster(SourceFile:293) ~[ee-5.0.0-SNAPSHOT.jar:?]
	at com.dotcms.enterprise.cluster.ClusterFactory.rewireCluster(SourceFile:287) ~[ee-5.0.0-SNAPSHOT.jar:?]
	at com.dotcms.enterprise.cluster.ClusterFactory.rewireClusterIfNeeded(SourceFile:260) ~[ee-5.0.0-SNAPSHOT.jar:?]
	... 3 more 
```

**Also if you are upgrading from a previous version to the last master, we have a FATAL and the system makes a roll back transaction** 
Log: https://gist.github.com/bryanboza/623db20ec4a7d62690f140f02b6ff0de

## Steps to Reproduce (for bugs)
1. Start a fresh instance
2. Login as admin
3. Apply a license pack 
4. Check your logs

## Your Environment
Tested in the last master // postgres

**Comment by dsilvam** [comment]
PR core: https://github.com/dotCMS/core/pull/14041
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/605
