### ISSUE TITLE
My Account Link Broken

### ISSUE THREAD

**Issue by ryan-ethode** [dotCMS/core#14055]
## Expected Behavior
When logged into the frontend, I can click the "My Account" link in the top menu and see my account information.

## Current Behavior
When logged into the frontend, when I click on "My Account", I get a 500 error.

## Possible Solution
Judging by the logs, there is a missing accounts file in the DotCMS core.

## Known Workarounds
There are no known workarounds that I am aware of.

## Steps to Reproduce (for bugs)
1. Log into the frontend on the demo site with the default "bill@dotcms.com" account.
2. Visit the demo.dotcms.com home page.
3. Click "My Account"

## Context
Giving frontend users the ability to view their user information and change their password would be helpful out of the box (rather than building one). The reset password button works in a pinch, but that's not a good UX choice for the only way to change the user's password.

## Your Environment
* dotCMS version used: 4.3.1
* Browser Name and version: DotCMS Cloud
* Operating System and version: n/a
* Application Server and version: n/a
* Java Brand and version: n/a
* Database and version: n/a
* Application module (if apply): n/a

## Logs (DotCMS Log)

[06/04/18 11:45:49:523 EDT] WARN auth.PrincipalThreadLocal: getName null
[06/04/18 11:46:02:272 EDT] INFO taillog.TailLogServlet: Requested logFile:/media/ephemeral0/wwwroot/demo41.dotcms.com/dotCMS-4.3.1/dotserver/tomcat-8.0.18/webapps/ROOT/dotsecure/logs/dotcms.log
[06/04/18 11:46:14:714 EDT] WARN action.MyAccountAction: Legacy Front End Account Management Disallowed.
[06/04/18 11:46:14:714 EDT] WARN action.MyAccountAction: ------------------------------------
[06/04/18 11:46:14:714 EDT] WARN action.MyAccountAction: To enable, add 'allow.legacy.com.dotmarketing.cms.myaccount.action.myaccountaction=true' to your dotmarketing-config.properties
[06/04/18 11:46:14:714 EDT] WARN action.MyAccountAction: ------------------------------------
[06/04/18 11:46:14:714 EDT] ERROR action.RequestProcessor: No action instance for path /myAccount could be created
java.lang.SecurityException: Front End Account Management Disallowed
at com.dotmarketing.cms.SecureAction.<init>(SecureAction.java:20) ~[dotcms_4.3.1_bb81de4.jar:?]
at com.dotmarketing.cms.myaccount.action.MyAccountAction.<init>(MyAccountAction.java:41) ~[dotcms_4.3.1_bb81de4.jar:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_151]
at com.dotcms.repackage.org.apache.struts.util.RequestUtils.applicationInstance(RequestUtils.java:145) ~[dot.struts-1.2.4_2.jar:1.2.4]
at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.processActionCreate(RequestProcessor.java:282) [dot.struts-1.2.4_2.jar:1.2.4]
at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:220) [dot.struts-1.2.4_2.jar:1.2.4]
at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:128) [dotcms_4.3.1_bb81de4.jar:?]
at com.dotcms.repackage.org.apache.struts.action.ActionServlet.process(ActionServlet.java:1164) [dot.struts-1.2.4_2.jar:1.2.4]
at com.dotcms.repackage.org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:397) [dot.struts-1.2.4_2.jar:1.2.4]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:618) [servlet-api.jar:?]
at com.liferay.portal.servlet.MainServlet.callParentService(MainServlet.java:251) [dotcms_4.3.1_bb81de4.jar:?]
at com.liferay.portal.servlet.MainServlet.service(MainServlet.java:440) [dotcms_4.3.1_bb81de4.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:203) [dotcms_4.3.1_bb81de4.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.3.1_bb81de4.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.3.1_bb81de4.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:325) [dotcms_4.3.1_bb81de4.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:110) [dotcms_4.3.1_bb81de4.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:132) [dotcms_4.3.1_bb81de4.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_4.3.1_bb81de4.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:38) [dotcms_4.3.1_bb81de4.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:108) [dotcms_4.3.1_bb81de4.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:673) [catalina.jar:8.0.18]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[06/04/18 11:46:14:715 EDT] WARN error.custom_002derror_002dpage_jsp: No action instance for path /myAccount could be created on /html/error/custom-error-page.jsp

**Comment by wezell** [comment]
Relies on old Struts code, can be implemented in a plugin.
