### ISSUE TITLE
Workflow requires default scheme

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14135]
1. Delete the default scheme.
2. View the workflow schemes and get an error:

To fix, we actually should comment the method out, fix the red and move forward.  I see a few places in code that are still expecting to get a default scheme and it is not there.

For example, the ContentBundler

```
16:39:48.140  INFO  delegate.SystemEventsJobDelegate - The event: e8ce068c-4fa7-45fa-aba6-2c505167bd45, has been skipped on the server: 4a9b7775-11f8-449b-9ecd-9b1816e1ac45
Apr 16, 2018 4:42:11 PM com.dotcms.repackage.org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 4.3.2.Final
Apr 16, 2018 4:42:13 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [jsp] in context with path [] threw exception [javax.servlet.ServletException: com.dotmarketing.exception.DotDataException: default scheme does not exist] with root cause
com.dotmarketing.exception.DotDataException: default scheme does not exist
	at com.dotmarketing.portlets.workflows.business.WorkflowFactoryImpl.findDefaultScheme(WorkflowFactoryImpl.java:616)
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.findDefaultScheme_aroundBody10(WorkflowAPIImpl.java:287)
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl$AjcClosure11.run(WorkflowAPIImpl.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43)
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29)
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41)
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.findDefaultScheme(WorkflowAPIImpl.java:286)
	at org.apache.jsp.html.portlet.ext.workflows.schemes.view_005fschemes_jsp._jspService(view_005fschemes_jsp.java:133)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
```

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14170

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on the last master.
