### ISSUE TITLE
Sporadic error uploading fragments

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#14272]
We are seeing this sporadic error when we upload OSGI fragments:

```
ERROR: Bundle org.apache.felix.framework [0] EventDispatcher: Error during dispatch. (java.lang.IllegalStateException: Invalid BundleContext.)
java.lang.IllegalStateException: Invalid BundleContext.
	at org.apache.felix.framework.BundleContextImpl.checkValidity(BundleContextImpl.java:511)
	at org.apache.felix.framework.BundleContextImpl.getService(BundleContextImpl.java:451)
	at org.osgi.util.tracker.ServiceTracker.addingService(ServiceTracker.java:414)
	at org.apache.felix.http.proxy.DispatcherTracker.addingService(DispatcherTracker.java:55)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
	at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
	at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4578)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3570)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:322)
	at org.apache.felix.http.bridge.internal.BridgeActivator.doStart(BridgeActivator.java:50)
	at org.apache.felix.http.base.internal.AbstractActivator.start(AbstractActivator.java:41)
	at org.apache.felix.http.bundle.internal.CombinedActivator.start(CombinedActivator.java:60)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2238)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2144)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
```

Because of the nature of the OSGI fragments (they affect all the existing plugins) when a fragment is installed basically the OSGI framework restarts as it needs all the plugins to be aware of the new fragment, when that restart starts the first step is to shutdown all the plugins before to start them again, *this error occurs when the plugins shutdown on certain order as the Bundle Context of a plugin A depends of a service in for example of a plugin B already stopped*.

**This error in the logs does not affect any execution.**

**Comment by wezell** [comment]
coming from Felix

**Comment by brentgriffin** [comment]
I originally thought this issue was specific to 5.0 but it is not.  The problem occurs in 4.3.2 but does not log in dotcms.log file.  It logs in catalina.out.

There was some discussion about this issue in Slack.  After some debugging, I can safely say that as the stack indicates, this is happening as the Felix framework is starting bundles, not when it is stopping them.  It seems that something is not in the proper state and when they validate the state as they are dispatching an event to it, it throws an exception.  This only happens when deploying and undeploying fragments.  Other plugins do not show this behavior.  For me these errors were not sporadic - they happened every time with fragment plugins.

Conditions from EventDispatcher breakpoint on call to invokeServiceListenerCallback
    (bundle.toString().compareTo("org.apache.felix.framework [0]") == 0) &&
    (filter.toString().compareTo("(&(objectClass=javax.servlet.http.HttpServlet)(http.felix.dispatcher=*))") == 0) &&
    (event.toString().compareTo("org.osgi.framework.ServiceEvent[source=[javax.servlet.http.HttpServlet]]") == 0)
