### ISSUE TITLE
ReplicasMode / ESClient not setting auto expand range properly

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#14303]
Version: 5.0-nightly-2018-04-30_22-12

In here https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/cluster/business/ReplicasMode.java

When it gets called from https://github.com/dotCMS/core/blob/320d6eb8c8cc5ebea8116e94e6ef7aa3fc5f6101/dotCMS/src/main/java/com/dotcms/content/elasticsearch/util/ESClient.java#L179-L180

When you use the replica autoexpand range (`0-all`), it tries to set `number_of_replicas` to `-1` which is an invalid setting in ES.

If we use the `auto_expand_replicas`, we should not set `number_of_replicas`

**Comment by chrismccracken** [comment]
Exception:
```
18:47:18.102  INFO  discovery.DiscoveryModule - using discovery type [zen]
18:47:18.783  INFO  node.Node - initialized
18:47:18.783  INFO  node.Node - starting ...
18:47:18.978  INFO  transport.TransportService - publish_address {10.0.2.5:9300}, bound_addresses {10.0.2.5:9300}
18:47:22.212  INFO  service.ClusterApplierService - detected_master {3bd693c46a0f}{FXsSMD5xTVKPp3k9f0Nm7Q}{AZP0h_uvSH-aItY0Jy3ArQ}{10.0.2.3}{10.0.2.3:9300}, added {{3bd693c46a0f}{FXsSMD5xTVKPp3k9f0Nm7Q}{AZP0h_uvSH-aItY0Jy3ArQ}{10.0.2.3}{10.0.2.3:9300},}, reason: apply cluster state (from master [master {3bd693c46a0f}{FXsSMD5xTVKPp3k9f0Nm7Q}{AZP0h_uvSH-aItY0Jy3ArQ}{10.0.2.3}{10.0.2.3:9300} committed version [6]])
18:47:22.217  INFO  node.Node - started
18:47:22.246  ERROR util.ESClient - Unable to set up ES replicas.
java.lang.IllegalArgumentException: Failed to parse value [-1] for setting [index.number_of_replicas] must be >= 0
	at org.elasticsearch.common.settings.Setting.parseInt(Setting.java:967) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.settings.Setting.parseInt(Setting.java:961) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.settings.Setting.lambda$intSetting$11(Setting.java:931) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.settings.Setting.get(Setting.java:348) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.settings.Setting.get(Setting.java:342) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:328) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:276) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.cluster.metadata.MetaDataUpdateSettingsService.updateSettings(MetaDataUpdateSettingsService.java:167) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.admin.indices.settings.put.TransportUpdateSettingsAction.masterOperation(TransportUpdateSettingsAction.java:89) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.admin.indices.settings.put.TransportUpdateSettingsAction.masterOperation(TransportUpdateSettingsAction.java:41) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:88) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:167) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:135) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:164) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.start(TransportMasterNodeAction.java:127) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:105) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:55) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:167) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:139) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:64) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:54) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1554) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:135) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1511) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1380) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:64) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[?:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```
