### ISSUE TITLE
What's Changed not working in 5.0

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14317]
If you try to hit "What's Changed" in 5.0, you get a 500 error.

http://localhost:8080/html/portlet/ext/htmlpages/view_live_working_diff.jsp?id=c12fe7e6-d338-49d5-973b-2d974d57015b&pageLang=1

```
template : org.apache.xalan.templates.StylesheetRoot@368894db
template : org.apache.xalan.templates.StylesheetRoot@1d443af0
May 07, 2018 4:30:13 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [jsp] in context with path [] threw exception [An exception occurred processing JSP page [/html/portlet/ext/htmlpages/view_live_working_diff.jsp] at line [21]

18:     }
19: 
20:     HTMLDiffUtilProxy dp = new HTMLDiffUtilProxy();
21:     String x = dp.htmlDiffPage(p, user, contentId);
22: %>
23: 
24: <%=x%>


Stacktrace:] with root cause
org.xml.sax.SAXNotRecognizedException: Feature 'http://cyberneko.org/html/features/override-namespaces' is not recognized.
	at org.apache.xerces.parsers.AbstractSAXParser.setFeature(Unknown Source)
	at com.dotmarketing.util.diff.helper.NekoHtmlParser.parse(NekoHtmlParser.java:50)
	at com.dotmarketing.util.diff.HtmlCleaner.cleanAndParse(HtmlCleaner.java:40)
	at com.dotcms.enterprise.HTMLDiffUtil.htmlDiffPage(HTMLDiffUtil.java:138)
```

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/14423

**Comment by dsilvam** [comment]
Waiting on ticket: https://github.com/dotCMS/core/issues/14412
