### ISSUE TITLE
Full content delete works but reports failure in bulk actions

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14632]
When you run a full content delete using the bulk processor, the system records it as a failure because we get a npe here :
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/workflows/business/WorkflowAPIImpl.java#L2103

![screen shot 2018-06-14 at 11 40 11 am](https://user-images.githubusercontent.com/934364/41422808-bc7a747e-6fc7-11e8-936f-21a0232513c0.png)

```
11:36:54.098  INFO  db.DotConnect - Executing delete from tree where child in ('b6c3949f-7778-4649-8e43-125a0c098582','1a190d07-3834-4bed-aad7-27cfa942c7b1') or parent in ('b6c3949f-7778-4649-8e43-125a0c098582','1a190d07-3834-4bed-aad7-27cfa942c7b1')
11:36:54.103  INFO  db.DotConnect - Executing delete from multi_tree where child in ('b6c3949f-7778-4649-8e43-125a0c098582','1a190d07-3834-4bed-aad7-27cfa942c7b1') or parent1 in ('b6c3949f-7778-4649-8e43-125a0c098582','1a190d07-3834-4bed-aad7-27cfa942c7b1') or parent2 in ('b6c3949f-7778-4649-8e43-125a0c098582','1a190d07-3834-4bed-aad7-27cfa942c7b1')
11:36:54.136  ERROR business.WorkflowAPIImpl - null
java.lang.NullPointerException: null
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireBulkActionTask_aroundBody130(WorkflowAPIImpl.java:2103) ~[classes/:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl$AjcClosure131.run(WorkflowAPIImpl.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[classes/:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[classes/:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[classes/:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[classes/:?]
```

**Comment by fabrizzio-dotCMS** [comment]
This should be fixed by now.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14664
