### ISSUE TITLE
[SASS] : Validate SCSS input file before trying to compile it

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#14755]
Reported by customer via Support (Basecamp).
Reproducible in dotCMS 4.3.3, but not in dotCMS 5.0.

An error is being thrown in the `dotcms.log` file when trying to open up an HTML Page that uses the SASS compiler to process CSS files. The error describes a situation where the SCSS file is not found:
```
[29/06/18 11:07:57:574 CST] ERROR csspreproc.DotLibSassCompiler: unable to compile sass code demo.dotcms.com:/application/themes/alexa/sass/styles.css live:false
io.bit3.jsass.CompilationException: Internal Error: File to read not found or unreadable: /Users/josecastro/dotCMS/git/support/core-4.3.2/dotcms_assets/node1/assets/tmp_upload/css_compile_space/f9e93a2b-637a-4cef-a2ac-e45ab1ddebd9/application/themes/alexa/sass/styles.scss

	at io.bit3.jsass.adapter.NativeAdapter.compileFile(Native Method) ~[jsass-5.5.4.jar:5.5.4]
	at io.bit3.jsass.adapter.NativeAdapter.compile(NativeAdapter.java:44) ~[jsass-5.5.4.jar:5.5.4]
	at io.bit3.jsass.Compiler.compile(Compiler.java:124) ~[jsass-5.5.4.jar:5.5.4]
	at io.bit3.jsass.Compiler.compileFile(Compiler.java:76) ~[jsass-5.5.4.jar:5.5.4]
	at com.dotcms.enterprise.csspreproc.DotLibSassCompiler.compile(DotLibSassCompiler.java:78) [ee_clean.jar:?]
	at com.dotcms.csspreproc.CSSPreProcessServlet.doGet(CSSPreProcessServlet.java:135) [dotcms_4.3.2_999999.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618) [servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:203) [dotcms_4.3.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.3.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.3.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:325) [dotcms_4.3.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:110) [dotcms_4.3.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:132) [dotcms_4.3.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_4.3.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:38) [dotcms_4.3.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:108) [dotcms_4.3.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

## Expected Behavior
A Web Developer must be able to include SCSS files without problems.

## Current Behavior
An error is being logged when SCSS files are referenced inside an HTML Page.

## Possible Solution
The following line in the source code: https://github.com/dotCMS/enterprise-2.x/blob/4.3.3/src/main/java/com/dotcms/enterprise/csspreproc/DotLibSassCompiler.java#L71 is omitting the Site name (hostname) in the path to the input SCSS file. Therefore, the String points to a path that does not exist and causes the compiler to fail.

## Known Workarounds
None.

## Steps to Reproduce (for bugs)
1. Create a theme, the VTL files, and a SCSS file for it.
2. Add a template that references the previous theme.
3. Create a new HTML Page and open it.
4. The page's styles are not rendering, and an error is displayed in the logs:

## Your Environment
* dotCMS version used: 4.3.3
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: SASS Compiler

**Comment by jcastro-dotcms** [comment]
PR for ee: https://github.com/dotCMS/enterprise-2.x/pull/623

**Comment by wezell** [comment]
working in master
