### ISSUE TITLE
Test pushing workflows

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14864]
I believe workflows are currently pushed as a dependency of content.  We need to 1) review the logic in the Bundler and Handlers to make sure they are sane and 2) make sure that this push publishing works with the new workflow schemes.

* When you push a piece of content in a workflow, you need to push the workflows as well.
* We will need to push the roles (assign to and permissions) that the workflow steps use
* We will need to test the new special roles

**Comment by jgambarios** [comment]
## Results of the workflows Push Publish tests:

1. **Workflow names conflicts:** If I create in the receiver a workflow with the same name of one existing in the sender PP fails:
``` java
Caused by: com.dotmarketing.exception.DotDataException: Conflicts between Workflow Schemes. Scheme with name : 'Test3' has different Inodes at sender and receiver. Please run the Integrity Checker at sender.
	at com.dotcms.enterprise.publishing.remote.handler.WorkflowHandler.handleWorkflows(WorkflowHandler.java:138) ~[ee_clean.jar:?]
	... 4 more
```
2. **Workflow names conflicts:** In the case described above: **The Integrity checker shows conflicts because of the duplicated names.**
**The Integrity Checker should try to resolve this kind of conflicts?**, I think we should remove this option from the Integrity Checker as we can have multiple workflows with the same name, this case should not be considered as a conflict.

3. **Workflow names conflicts:** Similar to above cases:
If in the sender server I have a workflow named **Workflow1** and in the remote I created manually **TWO** workflows with the same **Workflow1** name we have two errors:
    1. The push publish fails -> Described in point 1
    2. The integrity checker fails:
``` java
15:04:51.338  ERROR rest.IntegrityResource - Error checking integrity
java.lang.Exception: Error running the Workflow Schemes Integrity Check
	at com.dotcms.integritycheckers.SchemeIntegrityChecker.generateIntegrityResults(SchemeIntegrityChecker.java:160) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.integritycheckers.IntegrityUtil.completeCheckIntegrity(IntegrityUtil.java:600) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.rest.IntegrityResource$2.run_aroundBody0(IntegrityResource.java:455) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.rest.IntegrityResource$2$AjcClosure1.run(IntegrityResource.java:1) ~[dotcms_5.0.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.rest.IntegrityResource$2.run(IntegrityResource.java:401) ~[dotcms_5.0.0_999999.jar:?]
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "schemes_ir_pkey"
  Detail: Key (local_inode, endpoint_id)=(0b980d99-f634-4350-9c02-49f348e9b389, 8d1bb153-c88d-41b7-8d73-0a590e538c0d) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266) ~[postgresql-42.2.2.jar:42.2.2]
	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc.jar:?]
	at com.sun.proxy.$Proxy74.execute(Unknown Source) ~[?:?]
	at com.dotmarketing.common.db.DotConnect.executeStatement(DotConnect.java:236) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.integritycheckers.SchemeIntegrityChecker.generateIntegrityResults(SchemeIntegrityChecker.java:154) ~[dotcms_5.0.0_999999.jar:?]
	... 8 more
Exception in thread "Thread-631" java.lang.RuntimeException: Error checking integrity
	at com.dotcms.rest.IntegrityResource$2.run_aroundBody0(IntegrityResource.java:476)
	at com.dotcms.rest.IntegrityResource$2$AjcClosure1.run(IntegrityResource.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43)
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29)
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41)
	at com.dotcms.rest.IntegrityResource$2.run(IntegrityResource.java:401)
Caused by: java.lang.Exception: Error running the Workflow Schemes Integrity Check
	at com.dotcms.integritycheckers.SchemeIntegrityChecker.generateIntegrityResults(SchemeIntegrityChecker.java:160)
	at com.dotcms.integritycheckers.IntegrityUtil.completeCheckIntegrity(IntegrityUtil.java:600)
	at com.dotcms.rest.IntegrityResource$2.run_aroundBody0(IntegrityResource.java:455)
	... 6 more
```
4. **Steps conflicts:** Add to an already pushed Workflow in the sender a Step `Step4` and add a step with the same name to the same workflow in the Receiver, no errors in logs but the push never finished, the app enters into an endless cycle of push publish retries and I have to restart the server in order to be able to back to normal.

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/14918
https://github.com/dotCMS/enterprise-2.x/pull/627

**Comment by bryanboza** [comment]
Fixed, tested on master and now all those cases are working, a new case reported here #15047
