### ISSUE TITLE
Unable to delete host because of this error

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14913]
I am trying to delete a local host and am seeing this error when trying to delete a content type.  This is frustrating because the error is not in the content type deletion, but in the system trying to send me a notification about the deletion.  Why did we use GSON here and not Jackson like elsewhere in our system?

```
22:04:32.413  INFO  db.DotConnect - Executing delete from tree where child in ('eb1a2be9-1dae-472a-909a-bd98fb2c7ec5') or parent in ('eb1a2be9-1dae-472a-909a-bd98fb2c7ec5')
22:04:32.414  INFO  db.DotConnect - Executing delete from multi_tree where child in ('eb1a2be9-1dae-472a-909a-bd98fb2c7ec5') or parent1 in ('eb1a2be9-1dae-472a-909a-bd98fb2c7ec5') or parent2 in ('eb1a2be9-1dae-472a-909a-bd98fb2c7ec5')
22:04:32.489  ERROR event.SystemEventsFactory$SystemEventsAPIImpl - An error occurred when saving a system event with ID: [null]: Cannot find type adapter for class com.dotcms.contenttype.model.type.ImmutableSimpleContentType
java.lang.IllegalArgumentException: Cannot find type adapter for class com.dotcms.contenttype.model.type.ImmutableSimpleContentType
	at com.dotcms.util.deserializer.ImmutableTypeAdapter.serialize(ImmutableTypeAdapter.java:99) ~[classes/:?]
	at com.google.gson.TreeTypeAdapter.write(TreeTypeAdapter.java:70) ~[gson-2.5.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68) ~[gson-2.5.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:113) ~[gson-2.5.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:240) ~[gson-2.5.jar:?]
	at com.google.gson.Gson.toJson(Gson.java:652) ~[gson-2.5.jar:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:545) ~[gson-2.5.jar:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:524) ~[gson-2.5.jar:?]
	at com.google.gson.Gson$2.serialize(Gson.java:137) ~[gson-2.5.jar:?]
	at com.dotcms.util.deserializer.PayloadAdapter.serialize(PayloadAdapter.java:91) ~[classes/:?]
	at com.dotcms.util.deserializer.PayloadAdapter.serialize(PayloadAdapter.java:1) ~[classes/:?]
	at com.google.gson.TreeTypeAdapter.write(TreeTypeAdapter.java:70) ~[gson-2.5.jar:?]
	at com.google.gson.Gson.toJson(Gson.java:652) ~[gson-2.5.jar:?]
	at com.google.gson.Gson.toJson(Gson.java:631) ~[gson-2.5.jar:?]
	at com.google.gson.Gson.toJson(Gson.java:586) ~[gson-2.5.jar:?]
	at com.google.gson.Gson.toJson(Gson.java:566) ~[gson-2.5.jar:?]
	at com.dotcms.util.marshal.MarshalFactory$GsonMarshalUtils.marshal(MarshalFactory.java:301) ~[classes/:?]
	at com.dotcms.api.system.event.SystemEventsFactory$SystemEventsAPIImpl.push(SystemEventsFactory.java:159) ~[classes/:?]
	at com.dotcms.api.system.event.SystemEventsFactory$SystemEventsAPIImpl.push(SystemEventsFactory.java:190) ~[classes/:?]
	at com.dotcms.api.system.event.SystemEventsFactory$SystemEventsAPIImpl.push(SystemEventsFactory.java:195) ~[classes/:?]
	at com.dotcms.contenttype.business.ContentTypeAPIImpl.delete_aroundBody0(ContentTypeAPIImpl.java:107) ~[classes/:?]
	at com.dotcms.contenttype.business.ContentTypeAPIImpl$AjcClosure1.run(ContentTypeAPIImpl.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[classes/:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[classes/:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[classes/:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[classes/:?]
	at com.dotcms.contenttype.business.ContentTypeAPIImpl.delete(ContentTypeAPIImpl.java:72) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl$1DeleteHostThread.deleteHost(HostAPIImpl.java:688) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl$1DeleteHostThread.call_aroundBody0(HostAPIImpl.java:589) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl$1DeleteHostThread$AjcClosure1.run(HostAPIImpl.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[classes/:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[classes/:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[classes/:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl$1DeleteHostThread.call(HostAPIImpl.java:586) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl$1DeleteHostThread.call(HostAPIImpl.java:1) ~[classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
22:04:32.490  ERROR type.ContentType - An error occurred when saving a system event with ID: [null]: Cannot find type adapter for class com.dotcms.contenttype.model.type.ImmutableSimpleContentType
com.dotmarketing.exception.DotDataException: An error occurred when saving a system event with ID: [null]: Cannot find type adapter for class com.dotcms.contenttype.model.type.ImmutableSimpleContentType
	at com.dotcms.api.system.event.SystemEventsFactory$SystemEventsAPIImpl.push(SystemEventsFactory.java:180) ~[classes/:?]
	at com.dotcms.api.system.event.SystemEventsFactory$SystemEventsAPIImpl.push(SystemEventsFactory.java:190) ~[classes/:?]
```

**Comment by wezell** [comment]
[3dffe125-a9e3-408c-b049-8e5fdfb8c078.tar.gz](https://github.com/dotCMS/core/files/2235959/3dffe125-a9e3-408c-b049-8e5fdfb8c078.tar.gz)

**Comment by dsilvam** [comment]
PR 2: https://github.com/dotCMS/core/pull/15037
