### ISSUE TITLE
Integrity Checker not working between 2 servers

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14911]
I am seeing this error when I try to check integrity between 2 dotCMS servers:

```
17:47:38.256 WARN integritycheckers.SchemeIntegrityChecker - Results table not supported for integrity type = [SCHEMES]
17:47:38.256 WARN integritycheckers.StructureIntegrityChecker - Results table not supported for integrity type = [STRUCTURES]
17:47:38.257 WARN integritycheckers.ContentPageIntegrityChecker - Results table not supported for integrity type = [HTMLPAGES]
17:47:38.257 WARN integritycheckers.ContentFileAssetIntegrityChecker - Results table not supported for integrity type = [FILEASSETS]
17:47:38.258 WARN integritycheckers.RoleIntegrityChecker - Results table not supported for integrity type = [CMS_ROLES]
17:47:38.322 ERROR rest.IntegrityResource - Error initializing the integrity checking process for End Point server: [963d559f-9ee5-4888-b087-048e15e81b8a]
com.dotcms.repackage.javax.ws.rs.ProcessingException: Already connected
at com.dotcms.repackage.org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:264) ~[dot.jersey-client-2.22.1_4.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684) ~[dot.jersey-client-2.22.1_4.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681) ~[dot.jersey-client-2.22.1_4.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[dot.jersey-common-2.22.1_4.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[dot.jersey-common-2.22.1_4.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:228) ~[dot.jersey-common-2.22.1_4.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444) ~[dot.jersey-common-2.22.1_4.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681) ~[dot.jersey-client-2.22.1_4.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437) ~[dot.jersey-client-2.22.1_4.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:343) ~[dot.jersey-client-2.22.1_4.jar:?]
at com.dotcms.rest.IntegrityResource.postWithEndpointState(IntegrityResource.java:150) ~[dotcms_5.0.0_058eef8.jar:?]
at com.dotcms.rest.IntegrityResource.checkIntegrity(IntegrityResource.java:391) ~[dotcms_5.0.0_058eef8.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
```

**Comment by wezell** [comment]
See this:

https://stackoverflow.com/questions/28951667/already-connected-exception-trying-to-do-post-request-using-jersey-client-api
