### ISSUE TITLE
Seeing this on load starter.zip startup

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14920]
tested on a clean startup from latest nightly - but I see it on my dev install to:

```

15:43:37.162  INFO  util.ESClient - ***PATH HOME: /Users/will/git/dotcms5/releases/2018-07-24/dotserver/tomcat-8.5.24/webapps/ROOT/WEB-INF/elasticsearch
15:43:37.344  INFO  node.Node - initializing ...
15:43:37.442  INFO  env.NodeEnvironment - using [1] data paths, mounts [[/ (/dev/disk2)]], net usable_space [648.7gb], net total_space [1005.5gb], types [hfs]
15:43:37.448  INFO  env.NodeEnvironment - heap size [1gb], compressed ordinary object pointers [true]
15:43:37.449  INFO  node.Node - node name [2f5ebd7d-677f-4763-8940-293e8ce19509], node ID [sn6QbWe4TbupAqJih3seQA]
15:43:37.449  INFO  node.Node - version[6.1.3], pid[8986], build[af51318/2018-01-26T18:22:55.523Z], OS[Mac OS X/10.13.6/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_112/25.112-b16]
15:43:37.450  INFO  node.Node - JVM arguments [-Djava.util.logging.config.file=/Users/will/git/dotcms5/releases/2018-07-24/dotserver/tomcat-8.5.24/conf/logging.properties, -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager, -Djava.awt.headless=true, -Xverify:none, -Dfile.encoding=UTF8, -XX:+DisableExplicitGC, -XX:MaxMetaspaceSize=512m, -Xmx1G, -XX:+UseG1GC, -javaagent:/Users/will/git/dotcms5/releases/2018-07-24/dotserver/tomcat-8.5.24/webapps/ROOT/WEB-INF/lib/byte-buddy-agent-1.6.12.jar, -Dsun.jnu.encoding=UTF-8, -Ddotserver=2018-07-24, -Djdk.tls.ephemeralDHKeySize=2048, -Djava.protocol.handler.pkgs=org.apache.catalina.webresources, -Dignore.endorsed.dirs=, -Dcatalina.base=/Users/will/git/dotcms5/releases/2018-07-24/dotserver/tomcat-8.5.24, -Dcatalina.home=/Users/will/git/dotcms5/releases/2018-07-24/dotserver/tomcat-8.5.24, -Djava.io.tmpdir=/Users/will/git/dotcms5/releases/2018-07-24/dotserver/tomcat-8.5.24/temp]
15:43:38.068  INFO  plugins.PluginsService - loaded module [aggs-matrix-stats]
15:43:38.068  INFO  plugins.PluginsService - loaded module [analysis-common]
15:43:38.068  INFO  plugins.PluginsService - loaded module [ingest-common]
15:43:38.068  INFO  plugins.PluginsService - loaded module [lang-expression]
15:43:38.068  INFO  plugins.PluginsService - loaded module [lang-mustache]
15:43:38.068  INFO  plugins.PluginsService - loaded module [lang-painless]
15:43:38.068  INFO  plugins.PluginsService - loaded module [mapper-extras]
15:43:38.068  INFO  plugins.PluginsService - loaded module [parent-join]
15:43:38.068  INFO  plugins.PluginsService - loaded module [percolator]
15:43:38.068  INFO  plugins.PluginsService - loaded module [reindex]
15:43:38.068  INFO  plugins.PluginsService - loaded module [repository-url]
15:43:38.068  INFO  plugins.PluginsService - loaded module [transport-netty4]
15:43:38.068  INFO  plugins.PluginsService - loaded module [tribe]
15:43:38.069  INFO  plugins.PluginsService - loaded plugin [script-expert-relationships-sort]
15:43:39.619  INFO  discovery.DiscoveryModule - using discovery type [zen]
15:43:40.191  INFO  node.Node - initialized
15:43:40.191  INFO  node.Node - starting ...
15:43:40.390  INFO  transport.TransportService - publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
15:43:41.025  INFO  reindex.ReindexThread - Reindex Thread started with a sleep of 500
15:43:43.459  INFO  service.MasterService - zen-disco-elected-as-master ([0] nodes joined), reason: new_master {2f5ebd7d-677f-4763-8940-293e8ce19509}{sn6QbWe4TbupAqJih3seQA}{cIP3qBjMSpGuvNqLmsqbVw}{127.0.0.1}{127.0.0.1:9300}
15:43:43.466  INFO  service.ClusterApplierService - new_master {2f5ebd7d-677f-4763-8940-293e8ce19509}{sn6QbWe4TbupAqJih3seQA}{cIP3qBjMSpGuvNqLmsqbVw}{127.0.0.1}{127.0.0.1:9300}, reason: apply cluster state (from master [master {2f5ebd7d-677f-4763-8940-293e8ce19509}{sn6QbWe4TbupAqJih3seQA}{cIP3qBjMSpGuvNqLmsqbVw}{127.0.0.1}{127.0.0.1:9300} committed version [1] source [zen-disco-elected-as-master ([0] nodes joined)]])
15:43:43.472  INFO  node.Node - started
15:43:43.492  WARN  service.ClusterApplierService - failed to notify ClusterStateListener
org.elasticsearch.index.IndexNotFoundException: no such index
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:169) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:143) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:76) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.admin.indices.settings.put.TransportUpdateSettingsAction.checkBlock(TransportUpdateSettingsAction.java:71) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.admin.indices.settings.put.TransportUpdateSettingsAction.checkBlock(TransportUpdateSettingsAction.java:41) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$0(TransportMasterNodeAction.java:142) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.clusterChanged(ClusterStateObserver.java:186) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateListeners$7(ClusterApplierService.java:506) ~[elasticsearch-6.1.3.jar:6.1.3]
	at java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3527) ~[?:1.8.0_112]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743) ~[?:1.8.0_112]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_112]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:503) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:486) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:429) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:158) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:568) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) ~[elasticsearch-6.1.3.jar:6.1.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
15:43:43.493  INFO  gateway.GatewayService - recovered [0] indices into cluster_state
15:44:13.482  ERROR util.ESClient - Unable to set up ES replicas.
org.elasticsearch.discovery.MasterNotDiscoveredException: ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:213) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:317) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:244) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:578) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:568) ~[elasticsearch-6.1.3.jar:6.1.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
	at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedException(ClusterBlocks.java:165) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.admin.indices.settings.put.TransportUpdateSettingsAction.checkBlock(TransportUpdateSettingsAction.java:61) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.admin.indices.settings.put.TransportUpdateSettingsAction.checkBlock(TransportUpdateSettingsAction.java:41) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:135) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.start(TransportMasterNodeAction.java:127) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:105) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:55) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:167) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:139) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:81) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:405) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:394) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1247) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.updateSettings(AbstractClient.java:1629) ~[elasticsearch-6.1.3.jar:6.1.3]
	at com.dotcms.content.elasticsearch.util.ESClient.lambda$2(ESClient.java:186) ~[dotcms_5.0.0_a44201c.jar:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_112]
	at com.dotcms.content.elasticsearch.util.ESClient.setReplicasSettings(ESClient.java:186) ~[dotcms_5.0.0_a44201c.jar:?]
	at com.dotcms.content.elasticsearch.util.ESClient.initNode(ESClient.java:112) ~[dotcms_5.0.0_a44201c.jar:?]
	at com.dotcms.content.elasticsearch.util.ESClient.getClient(ESClient.java:79) ~[dotcms_5.0.0_a44201c.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletIndexAPI.initIndex(ESContentletIndexAPI.java:163) ~[dotcms_5.0.0_a44201c.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletIndexAPI.setUpFullReindex(ESContentletIndexAPI.java:216) ~[dotcms_5.0.0_a44201c.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.refreshAllContent(ESContentletAPIImpl.java:2208) ~[dotcms_5.0.0_a44201c.jar:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.refreshAllContent(ContentletAPIInterceptor.java:1426) ~[dotcms_5.0.0_a44201c.jar:?]
	at com.dotmarketing.util.ImportExportUtil.doImport(ImportExportUtil.java:864) ~[dotcms_5.0.0_a44201c.jar:?]
	at com.dotmarketing.db.DotCMSInitDb.loadStarterSite(DotCMSInitDb.java:110) ~[dotcms_5.0.0_a44201c.jar:?]
	at com.dotmarketing.db.DotCMSInitDb.InitializeDb_aroundBody2(DotCMSInitDb.java:48) ~[dotcms_5.0.0_a44201c.jar:?]
	at com.dotmarketing.db.DotCMSInitDb$AjcClosure3.run(DotCMSInitDb.java:1) ~[dotcms_5.0.0_a44201c.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_5.0.0_a44201c.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.0.0_a44201c.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.0.0_a44201c.jar:?]
	at com.dotmarketing.db.DotCMSInitDb.InitializeDb(DotCMSInitDb.java:39) ~[dotcms_5.0.0_a44201c.jar:?]
	at com.dotmarketing.startup.runalways.Task00004LoadStarter.executeUpgrade(Task00004LoadStarter.java:14) ~[dotcms_5.0.0_a44201c.jar:?]
	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:212) ~[dotcms_5.0.0_a44201c.jar:?]
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:107) ~[dotcms_5.0.0_a44201c.jar:?]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1183) ~[catalina.jar:8.5.24]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1099) ~[catalina.jar:8.5.24]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:989) ~[catalina.jar:8.5.24]
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4931) ~[catalina.jar:8.5.24]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5241) ~[catalina.jar:8.5.24]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[catalina.jar:8.5.24]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752) ~[catalina.jar:8.5.24]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728) ~[catalina.jar:8.5.24]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734) ~[catalina.jar:8.5.24]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1141) ~[catalina.jar:8.5.24]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875) ~[catalina.jar:8.5.24]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_112]
	... 3 more
15:44:18.488  INFO  caffine.CaffineCache - ***	 Building Cache : logmappercache, size:10,Concurrency:32
15:44:18.490  INFO  business.ESIndexAPI - createIndex : Trying to create index: working_20180724154337 with shards: 0
```

**Comment by erickgonzalez** [comment]
Error no longer shows in the log and the license was applied successfully.

**Comment by bryanboza** [comment]
Fixed, unable to see the errors
