### ISSUE TITLE
The new content type portlet errors out with this database

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15124]
When using push publishing, we encountered an error that once a content type was pushed, the whole content type portlet became unavailable and was throwing the error below in the logs.

Is there any way to make this process more robust rather than kill the whole portlet.  

To reproduce, you can download this postgres.dmp and restore it via `pg_restore -d dotcms <dmp file>`

https://dotcms.slack.com/files/U5MCEMN94/FC8F686M6/dotcms-dotcms.com-auth5-5.0.0-20180815135657.dmp

```
13:14:37.452  WARN  common.ParseField - Deprecated field [include] used, expected [includes] instead
13:14:37.556  ERROR contenttype.ContentTypeResource - null
com.dotmarketing.business.DotStateException: null
	at com.dotcms.contenttype.transform.contenttype.JsonContentTypeTransformer.mapObject(JsonContentTypeTransformer.java:148) ~[dotcms_5.0.0_058eef8.jar:?]
	at com.dotcms.contenttype.transform.contenttype.JsonContentTypeTransformer.mapList(JsonContentTypeTransformer.java:132) ~[dotcms_5.0.0_058eef8.jar:?]
	at com.dotcms.util.pagination.ContentTypesPaginator.transformContentTypesToMap(ContentTypesPaginator.java:107) ~[dotcms_5.0.0_058eef8.jar:?]
	at com.dotcms.util.pagination.ContentTypesPaginator.getItems(ContentTypesPaginator.java:65) ~[dotcms_5.0.0_058eef8.jar:?]
	at com.dotcms.util.pagination.PaginatorOrdered.getItems(PaginatorOrdered.java:26) ~[dotcms_5.0.0_058eef8.jar:?]
	at com.dotcms.util.PaginationUtil.getPage(PaginationUtil.java:128) ~[dotcms_5.0.0_058eef8.jar:?]
	at com.dotcms.rest.api.v1.contenttype.ContentTypeResource.getContentTypes(ContentTypeResource.java:351) ~[dotcms_5.0.0_058eef8.jar:?]
	at sun.reflect.GeneratedMethodAccessor1576.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[dot.jersey-common-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[dot.jersey-common-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[dot.jersey-common-2.22.1_4.jar:?]
```

**Comment by dsilvam** [comment]
Is it possible to reproduce via Integration test? using the same data from Will's scenario? @fabrizzio-dotCMS

**Comment by fabrizzio-dotCMS** [comment]
The issue is caused by a Content-Type (Code Share) that that has a field of type Category with null values 
(Even though the values are mandatory). 
The Content-type ended up having Null values product of the use of Push Publish. And not a direct save using the UI. I think It would be interesting having a look at the source database from where the Push-publish was originated. Any ideas @wezell  @DeanGonzalez Anybody?

**Comment by wezell** [comment]
Second report of this issue

```
10:26:08.038  ERROR contenttype.ContentTypeResource - null

com.dotmarketing.business.DotStateException: null

        at com.dotcms.contenttype.transform.contenttype.JsonContentTypeTransformer.mapObject(JsonContentTypeTransformer.java:148) ~[dotcms_5.0.0_968162a.jar:?]

        at com.dotcms.contenttype.transform.contenttype.JsonContentTypeTransformer.mapList(JsonContentTypeTransformer.java:132) ~[dotcms_5.0.0_968162a.jar:?]

        at com.dotcms.util.pagination.ContentTypesPaginator.transformContentTypesToMap(ContentTypesPaginator.java:107) ~[dotcms_5.0.0_968162a.jar:?]

        at com.dotcms.util.pagination.ContentTypesPaginator.getItems(ContentTypesPaginator.java:65) ~[dotcms_5.0.0_968162a.jar:?]

        at com.dotcms.util.pagination.PaginatorOrdered.getItems(PaginatorOrdered.java:26) ~[dotcms_5.0.0_968162a.jar:?]

        at com.dotcms.util.PaginationUtil.getPage(PaginationUtil.java:128) ~[dotcms_5.0.0_968162a.jar:?]

        at com.dotcms.rest.api.v1.contenttype.ContentTypeResource.getContentTypes(ContentTypeResource.java:351) ~[dotcms_5.0.0_968162a.jar:?]

        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]

        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_152]

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]

        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]

        at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[dot.jersey-server-2.22.1_4.jar:?]

 
```

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15142

**Comment by bryanboza** [comment]
Tested with the provided database and after the last changes now I'm able to navigate in the portlet without problems

**Comment by bryanboza** [comment]
Fixed, tested on master and I'm unable to reproduce
