### ISSUE TITLE
Error pushing entire sites 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15175]
We have problems trying to push entire sites and the bundle is failing 

## Expected Behavior
We need to be able to push complete sites without problems 

## Current Behavior
We bundle all the contents, but we have an error pushing 
ST:
```
13:24:45.697  ERROR business.PublisherAPIImpl - Error publishing bundle with ID 'f4a5f5ae-56bd-460c-9c91-b7b9f617400a.tar.gz': identifier is null
com.dotcms.publishing.DotPublishingException: identifier is null
	at com.dotcms.enterprise.publishing.remote.handler.LinkHandler.a(SourceFile:157) ~[ee-5.0.0.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.LinkHandler.handle(SourceFile:58) ~[ee-5.0.0.jar:?]
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:203) ~[dotcms_5.0.1_8b520e9.jar:?]
	at com.dotcms.rest.PublishThread.run(PublishThread.java:42) ~[dotcms_5.0.1_8b520e9.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: com.dotmarketing.business.DotStateException: identifier is null
	at com.dotmarketing.business.IdentifierFactoryImpl.loadFromDb(IdentifierFactoryImpl.java:198) ~[dotcms_5.0.1_8b520e9.jar:?]
	at com.dotmarketing.business.IdentifierFactoryImpl.find(IdentifierFactoryImpl.java:419) ~[dotcms_5.0.1_8b520e9.jar:?]
	at com.dotmarketing.business.IdentifierAPIImpl.find_aroundBody4(IdentifierAPIImpl.java:82) ~[dotcms_5.0.1_8b520e9.jar:?]
	at com.dotmarketing.business.IdentifierAPIImpl$AjcClosure5.run(IdentifierAPIImpl.java:1) ~[dotcms_5.0.1_8b520e9.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_5.0.1_8b520e9.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.0.1_8b520e9.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.0.1_8b520e9.jar:?]
	at com.dotmarketing.business.IdentifierAPIImpl.find(IdentifierAPIImpl.java:81) ~[dotcms_5.0.1_8b520e9.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.LinkHandler.a(SourceFile:108) ~[ee-5.0.0.jar:?]
	... 4 more
13:24:45.702  ERROR lang.String - Error publishing bundle with ID 'f4a5f5ae-56bd-460c-9c91-b7b9f617400a.tar.gz': com.dotcms.publishing.DotPublishingException: identifier is null
```

## Steps to Reproduce (for bugs)
1. Configure your push environment 
2. On sender create a copy of demo site 
3. Try to push this copy
4. On receiver check the log file

## Your Environment
Tested on release-5.0.1 // Postrges // FF (this on both sides)

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/631

**Comment by nollymar** [comment]
Tested on master successfully

**Comment by nollymar** [comment]
Tested on release 5.0.2 successfully

**Comment by bryanboza** [comment]
Tested on release-5.0.2 and works as expected
