### ISSUE TITLE
Pdfbox font cache directory is outside of data dirs

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#15383]
It looks like the Tika's Pdfbox font cache tries to write to a location outside of any of our defined data directories. When you run dotCMS as a restricted user (always Best Practice), it throws:
```
[Apache Tika] WARN org.apache.pdfbox.pdmodel.font.FileSystemFontProvider - Building on-disk font cache, this may take a while
[Apache Tika] WARN org.apache.pdfbox.pdmodel.font.FileSystemFontProvider - Could not write to font cache
java.io.FileNotFoundException: /srv/.pdfbox.cache (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at java.io.FileWriter.<init>(FileWriter.java:90)
	at org.apache.pdfbox.pdmodel.font.FileSystemFontProvider.saveDiskCache(FileSystemFontProvider.java:290)
	at org.apache.pdfbox.pdmodel.font.FileSystemFontProvider.<init>(FileSystemFontProvider.java:226)
	at org.apache.pdfbox.pdmodel.font.FontMapperImpl$DefaultFontProvider.<clinit>(FontMapperImpl.java:130)
	at org.apache.pdfbox.pdmodel.font.FontMapperImpl.getProvider(FontMapperImpl.java:149)
	at org.apache.pdfbox.pdmodel.font.FontMapperImpl.findFont(FontMapperImpl.java:413)
	at org.apache.pdfbox.pdmodel.font.FontMapperImpl.getTrueTypeFont(FontMapperImpl.java:321)
	at org.apache.pdfbox.pdmodel.font.PDTrueTypeFont.<init>(PDTrueTypeFont.java:220)
	at org.apache.pdfbox.pdmodel.font.PDFontFactory.createFont(PDFontFactory.java:75)
	at org.apache.pdfbox.pdmodel.PDResources.getFont(PDResources.java:143)
	at org.apache.pdfbox.contentstream.operator.text.SetFontAndSize.process(SetFontAndSize.java:60)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:838)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:495)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:469)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:150)
	at org.apache.pdfbox.text.LegacyPDFStreamEngine.processPage(LegacyPDFStreamEngine.java:139)
	at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:391)
	at org.apache.tika.parser.pdf.PDF2XHTML.processPage(PDF2XHTML.java:147)
	at org.apache.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java:319)
	at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:266)
	at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:117)
	at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:168)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
	at org.apache.tika.parser.ParsingReader$ParsingTask.run(ParsingReader.java:235)
	at java.lang.Thread.run(Thread.java:748)
[Apache Tika] WARN org.apache.pdfbox.pdmodel.font.FileSystemFontProvider - Installed fonts information will have to be reloaded for each start
[Apache Tika] WARN org.apache.pdfbox.pdmodel.font.FileSystemFontProvider - You can assign a directory to the 'pdfbox.fontcache' property
[Apache Tika] WARN org.apache.pdfbox.pdmodel.font.FileSystemFontProvider - Finished building on-disk font cache, found 0 fonts
[Apache Tika] WARN org.apache.pdfbox.pdmodel.font.PDTrueTypeFont - Using fallback font 'LiberationSans' for 'ArialMT'
```

If this font cache location is configurable, it should be under the location `DYNAMIC_CONTENT_PATH` is set to.

**Comment by wezell** [comment]
I believe this can be set via system property, e.g. `-Dpdfbox.fontcache=/tmp `
