### ISSUE TITLE
Adding new content with relationships fails

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15417]
1. Go to Edit content Screen and try to create a blog
3. Add a new blog entry with all the required fields and hit save.
4. It does not show up  and there is an error in the log 

```
09:27:50.770  INFO  util.SecurityLogger - class com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl : The Workflow History with id:301fe74a-f7f1-4c65-8d06-30c2349624be was saved.
09:27:50.833  INFO  factories.MultiTreeAPIImpl - Saving MutiTrees: pageId -> c12fe7e6-d338-49d5-973b-2d974d57015b multiTrees-> [com.dotmarketing.beans.MultiTree@7d9eb57c[parent1=c12fe7e6-d338-49d5-973b-2d974d57015b,parent2=56bd55ea-b04b-480d-9e37-5d6f9217dcc3,child=5aef0c62-b7d6-4805-9e7c-77a67f4822f3,relationType=2,treeOrder=0], com.dotmarketing.beans.MultiTree@27e7640d[parent1=c12fe7e6-d338-49d5-973b-2d974d57015b,parent2=5363c6c6-5ba0-4946-b7af-cf875188ac2e,child=2efc77b4-a54f-479b-8a81-a133b9e6da04,relationType=1,treeOrder=0], com.dotmarketing.beans.MultiTree@6824b38f[parent1=c12fe7e6-d338-49d5-973b-2d974d57015b,parent2=5363c6c6-5ba0-4946-b7af-cf875188ac2e,child=66d47ebf-7b11-4076-85b0-b6c8c373d000,relationType=1,treeOrder=1], com.dotmarketing.beans.MultiTree@7e735b8b[parent1=c12fe7e6-d338-49d5-973b-2d974d57015b,parent2=f1ba7688-453c-4c0d-a214-e5ac802b8034,child=7b396e44-6e22-49c8-8405-fe00f1c486fb,relationType=1,treeOrder=0]]
09:27:55.388  INFO  factories.MultiTreeAPIImpl - Saving MutiTrees: pageId -> c12fe7e6-d338-49d5-973b-2d974d57015b multiTrees-> [com.dotmarketing.beans.MultiTree@5dcb7099[parent1=c12fe7e6-d338-49d5-973b-2d974d57015b,parent2=56bd55ea-b04b-480d-9e37-5d6f9217dcc3,child=5aef0c62-b7d6-4805-9e7c-77a67f4822f3,relationType=2,treeOrder=0], com.dotmarketing.beans.MultiTree@569bd749[parent1=c12fe7e6-d338-49d5-973b-2d974d57015b,parent2=5363c6c6-5ba0-4946-b7af-cf875188ac2e,child=2efc77b4-a54f-479b-8a81-a133b9e6da04,relationType=1,treeOrder=0], com.dotmarketing.beans.MultiTree@1d09c52e[parent1=c12fe7e6-d338-49d5-973b-2d974d57015b,parent2=5363c6c6-5ba0-4946-b7af-cf875188ac2e,child=66d47ebf-7b11-4076-85b0-b6c8c373d000,relationType=1,treeOrder=1]]
09:28:06.672  WARN  cache.LegacyContentTypeCacheImpl - Structure with inode: '' not found in db
09:28:06.701  WARN  cache.LegacyContentTypeCacheImpl - Structure with inode: '' not found in db
09:28:13.539  WARN  cache.LegacyContentTypeCacheImpl - Structure with inode: '' not found in db
09:28:13.547  WARN  web.ContentletWebAPIImpl - java.lang.NullPointerException
java.lang.NullPointerException: null
	at com.dotmarketing.portlets.contentlet.business.web.ContentletWebAPIImpl.retrieveRelationshipsData(ContentletWebAPIImpl.java:1122) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.web.ContentletWebAPIImpl._saveWebAsset(ContentletWebAPIImpl.java:440) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.web.ContentletWebAPIImpl.saveContent_aroundBody0(ContentletWebAPIImpl.java:138) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.web.ContentletWebAPIImpl$AjcClosure1.run(ContentletWebAPIImpl.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[classes/:?]09:27:50.770  INFO  util.SecurityLogger - class com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl : The Workflow History with id:301fe74a-f7f1-4c65-8d06-30c2349624be was saved.
09:27:50.833  INFO  factories.MultiTreeAPIImpl - Saving MutiTrees: pageId -> c12fe7e6-d338-49d5-973b-2d974d57015b multiTrees-> [com.dotmarketing.beans.MultiTree@7d9eb57c[parent1=c12fe7e6-d338-49d5-973b-2d974d57015b,parent2=56bd55ea-b04b-480d-9e37-5d6f9217dcc3,child=5aef0c62-b7d6-4805-9e7c-77a67f4822f3,relationType=2,treeOrder=0], com.dotmarketing.beans.MultiTree@27e7640d[parent1=c12fe7e6-d338-49d5-973b-2d974d57015b,parent2=5363c6c6-5ba0-4946-b7af-cf875188ac2e,child=2efc77b4-a54f-479b-8a81-a133b9e6da04,relationType=1,treeOrder=0], com.dotmarketing.beans.MultiTree@6824b38f[parent1=c12fe7e6-d338-49d5-973b-2d974d57015b,parent2=5363c6c6-5ba0-4946-b7af-cf875188ac2e,child=66d47ebf-7b11-4076-85b0-b6c8c373d000,relationType=1,treeOrder=1], com.dotmarketing.beans.MultiTree@7e735b8b[parent1=c12fe7e6-d338-49d5-973b-2d974d57015b,parent2=f1ba7688-453c-4c0d-a214-e5ac802b8034,child=7b396e44-6e22-49c8-8405-fe00f1c486fb,relationType=1,treeOrder=0]]
09:27:55.388  INFO  factories.MultiTreeAPIImpl - Saving MutiTrees: pageId -> c12fe7e6-d338-49d5-973b-2d974d57015b multiTrees-> [com.dotmarketing.beans.MultiTree@5dcb7099[parent1=c12fe7e6-d338-49d5-973b-2d974d57015b,parent2=56bd55ea-b04b-480d-9e37-5d6f9217dcc3,child=5aef0c62-b7d6-4805-9e7c-77a67f4822f3,relationType=2,treeOrder=0], com.dotmarketing.beans.MultiTree@569bd749[parent1=c12fe7e6-d338-49d5-973b-2d974d57015b,parent2=5363c6c6-5ba0-4946-b7af-cf875188ac2e,child=2efc77b4-a54f-479b-8a81-a133b9e6da04,relationType=1,treeOrder=0], com.dotmarketing.beans.MultiTree@1d09c52e[parent1=c12fe7e6-d338-49d5-973b-2d974d57015b,parent2=5363c6c6-5ba0-4946-b7af-cf875188ac2e,child=66d47ebf-7b11-4076-85b0-b6c8c373d000,relationType=1,treeOrder=1]]
09:28:06.672  WARN  cache.LegacyContentTypeCacheImpl - Structure with inode: '' not found in db
09:28:06.701  WARN  cache.LegacyContentTypeCacheImpl - Structure with inode: '' not found in db
09:28:13.539  WARN  cache.LegacyContentTypeCacheImpl - Structure with inode: '' not found in db
09:28:13.547  WARN  web.ContentletWebAPIImpl - java.lang.NullPointerException
java.lang.NullPointerException: null
	at com.dotmarketing.portlets.contentlet.business.web.ContentletWebAPIImpl.retrieveRelationshipsData(ContentletWebAPIImpl.java:1122) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.web.ContentletWebAPIImpl._saveWebAsset(ContentletWebAPIImpl.java:440) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.web.ContentletWebAPIImpl.saveContent_aroundBody0(ContentletWebAPIImpl.java:138) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.web.ContentletWebAPIImpl$AjcClosure1.run(ContentletWebAPIImpl.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[classes/:?]
```

**Comment by wezell** [comment]
It looks like the code is still using the inodefactory - aka hibernate - to try to load relationships.  Here are some other instances that are doing the same thing and should probably be updated as well.

![screen shot 2018-10-12 at 10 01 52 am](https://user-images.githubusercontent.com/934364/46873956-faa3d780-ce05-11e8-810b-a78942397bcc.png)

**Comment by erickgonzalez** [comment]
@wezell yes yesterday I saw those calls to hibernate, testing right now the changes. I'll send the PR in a couple of minutes.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15418

**Comment by nollymar** [comment]
Now it's working fine

**Comment by bryanboza** [comment]
Fixed, tested on master and now it is working as expected
