### ISSUE TITLE
Bundle get stuck when uploading bundle on target env 

### ISSUE THREAD

**Issue by manuel-miranda** [dotCMS/core#15449]
Bundle get stuck after adding manually --no push

## Expected Behavior
Download a bundle for source env and upload the downloaded bundle file on the target env may work same as push, between these two env.

## Current Behavior
When a bundle is uploaded on the target env the bundle get stuck on the logs the full path of the uploaded bundle file is shown not just the UUID (this entry keeps showing up even after dotCMS restart):
```
[17/10/18 13:56:00:064 PDT]  INFO business.PublisherQueueJob: ===========================================================
[17/10/18 13:56:00:064 PDT]  INFO business.PublisherQueueJob: For bundle 'C:\Users\w10\Downloads\6ff85abe-1a1c-44cc-ae1a-c05cc5f4f16a':
[17/10/18 13:56:00:064 PDT]  INFO business.PublisherQueueJob: -> Status:          PUBLISHING_BUNDLE
[17/10/18 13:56:00:064 PDT]  INFO business.PublisherQueueJob: ===========================================================
```
Also:
```
[17/10/18 13:55:15:283 PDT] ERROR ajax.RemotePublishAjaxAction: null
java.nio.file.InvalidPathException: Illegal char <:> at index 83: C:\Users\w10\Desktop\receiver\dotserver\tomcat-8.0.18\webapps\ROOT\assets\bundles\C:\Users\w10\Downloads\6ff85abe-1a1c-44cc-ae1a-c05cc5f4f16a.tar.gz
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source) ~[?:1.8.0_191]
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:1.8.0_191]
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:1.8.0_191]
        at sun.nio.fs.WindowsPath.parse(Unknown Source) ~[?:1.8.0_191]
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source) ~[?:1.8.0_191]
        at java.io.File.toPath(Unknown Source) ~[?:1.8.0_191]
        at com.dotmarketing.util.FileUtil.writeToFile(FileUtil.java:124) ~[dotcms_4.3.2_ae725e9.jar:?]
        at com.dotcms.publisher.ajax.RemotePublishAjaxAction.uploadBundle(RemotePublishAjaxAction.java:731) ~[dotcms_4.3.2_ae725e9.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at com.dotcms.publisher.ajax.RemotePublishAjaxAction.service(RemotePublishAjaxAction.java:166) [dotcms_4.3.2_ae725e9.jar:?]
        at com.dotmarketing.servlets.ajax.AjaxAction.doPost(AjaxAction.java:56) [dotcms_4.3.2_ae725e9.jar:?]
        at com.dotmarketing.servlets.ajax.AjaxDirectorServlet.service(AjaxDirectorServlet.java:42) [dotcms_4.3.2_ae725e9.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:203) [dotcms_4.3.2_ae725e9.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.3.2_ae725e9.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.3.2_ae725e9.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:325) [dotcms_4.3.2_ae725e9.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:110) [dotcms_4.3.2_ae725e9.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:132) [dotcms_4.3.2_ae725e9.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_4.3.2_ae725e9.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:38) [dotcms_4.3.2_ae725e9.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:108) [dotcms_4.3.2_ae725e9.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
```
### Screenshots: 
Bundle Status:
![image](https://user-images.githubusercontent.com/29102758/47159495-38dc4380-d2ab-11e8-88e8-da633fbe1ad8.png)
Bundle details
![image](https://user-images.githubusercontent.com/29102758/47159531-50b3c780-d2ab-11e8-8277-d1abfaf07c3a.png)

Once this issue appear push publish stop working at all, pushing new content will get all bundles stuck on pending.
![image](https://user-images.githubusercontent.com/29102758/47162705-b5722080-d2b1-11e8-8285-f5e9130d34a8.png)
on dotcms-pushpublish.log
```
INFO class com.dotcms.publisher.business.PublishAuditStatus : Status Update: Pending. -   
INFO class com.dotcms.publisher.business.PublishAuditStatus : Status Update: Pending. -   
INFO class com.dotcms.publisher.business.PublishAuditStatus : Status Update: Pending. -   
INFO class com.dotcms.publisher.business.PublishAuditStatus : Status Update: Pending. -  
```
## Possible Solution
Push using push publish strategy, not download and upload manually.

## Known Workarounds
N/A

## Steps to Reproduce (for bugs)
1. Download bundle from source or sender environment. 
2. Upload the downloaded bundle to the target or receiver environment.

## Context
N/A

## Your Environment
* dotCMS version used: 4.3.2
* Browser Name and version: **MICROSOFT INTERNET EXPLORER /  EDGE 25.X**
* Operating System and version: **WINDOWS 10**
* Application Server and version: N/A
* Java Brand and version: Oracle Java 1.8u191
* Database and version: **Microsoft SQL Server 2014**
* Application module (if apply):N/A

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/15480

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF... Unable to reproduce after the last changes
