### ISSUE TITLE
Cluster issues when loaded from /assets/license_pack.zip

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15458]
When you start a server up for the first time with a license pack under the /assets/license_pack.zip, it throws exceptions to the log as the cluster is trying to init before the starter is imported
```
/application/themes/quest/_bower_components/bootstrap4/scss
16:42:11.282  INFO  util.ImportExportUtil - Importing folder path /application/themes/quest/_bower_components/bootstrap4/scss/mixins
16:42:11.285  INFO  util.ImportExportUtil - Importing folder path /application/themes/quest/_bower_components/bootstrap4/scss/utilities
16:42:11.288  INFO  util.ImportExportUtil - Importing folder path /application/themes/quest/_bower_components/chosen/public
16:42:11.292  WARN  service.ClusterApplierService - failed to notify ClusterStateListener
org.elasticsearch.index.IndexNotFoundException: no such index
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:169) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:143) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:76) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.admin.indices.settings.put.TransportUpdateSettingsAction.checkBlock(TransportUpdateSettingsAction.java:71) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.admin.indices.settings.put.TransportUpdateSettingsAction.checkBlock(TransportUpdateSettingsAction.java:41) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$0(TransportMasterNodeAction.java:142) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.clusterChanged(ClusterStateObserver.java:186) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateListeners$7(ClusterApplierService.java:506) ~[elasticsearch-6.1.3.jar:6.1.3]
	at java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3527) ~[?:1.8.0_162]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743) ~[?:1.8.0_162]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_162]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:503) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:486) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:429) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:158) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:568) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) ~[elasticsearch-6.1.3.jar:6.1.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
16:42:11.292  INFO  gateway.GatewayService - recovered [0] indices into cluster_state
16:42:11.297  INFO  util.ImportExportUtil - Importing folder path /application/themes/quest/_bower_components/fancybox/source
16:42:11.306  INFO  util.ImportExportUtil - Importing folder path /application/themes/quest/_bower_components/fancybox/source/helpers
16:42:11.314  INFO  util.ImportExportUtil - Importing folder path /application/themes/quest/_bower_components/font-awesome/fonts
16:42:11.317  INFO  util.ImportExportUtil - Importing folder path /application/themes/quest/_bower_components/font-awesome/less
16:42:11.319  INFO  util.ImportExportUtil - Importing folder path /application/themes/quest/_bower_components/font-awesome/css
16:42:11.323  INFO  util.ImportExportUtil - Importing folder path /application/themes/quest/_bower_components/video.js/font
16:42:11.326  INFO  util.ImportExportUtil - Importing folder path /application/themes/quest/images/template-thumbnails
16:42:11.329  INFO  util.ImportExportUtil - Importing folder path /application/themes/quest/images/layout
16:42:11.331  INFO  util.ImportExportUtil - Importing folder path /application/themes/quest/js/vendors
16:42:11.334  INFO  util.ImportExportUtil - Importing folder path /application/themes/quest/sass/widgets
```

When a second server in a cluster comes up, it throws this exception
```
db_1                    | ERROR:  duplicate key value violates unique constraint "cluster_server_pkey"
db_1                    | DETAIL:  Key (server_id)=(827e7dca-a8ff-45a9-87e2-da0612bc9ca9) already exists.
db_1                    | STATEMENT:  insert into cluster_server(server_id, cluster_id, name, ip_address, key_) values($1,$2,$3,$4,$5)
dotcms_2                | 16:00:58.184  ERROR cluster.ClusterFactory - Could not save Server to DB
dotcms_2                | com.dotmarketing.exception.DotDataException: ERROR: duplicate key value violates unique constraint "cluster_server_pkey"
dotcms_2                |   Detail: Key (server_id)=(827e7dca-a8ff-45a9-87e2-da0612bc9ca9) already exists.{
dotcms_2                |   "SQL": ["insert into cluster_server(server_id, cluster_id, name, ip_address, key_) values(?,?,?,?,?)"],
dotcms_2                |   "maxRows": [-1],
dotcms_2                |   "offest": [0],
dotcms_2                |   "params": [
dotcms_2                |     "827e7dca-a8ff-45a9-87e2-da0612bc9ca9",
dotcms_2                |     "ceec8ea7-2ad2-44c0-bfa4-24cb89f4c548",
dotcms_2                |     "578c4b2f3c52",
dotcms_2                |     "172.20.0.5",
dotcms_2                |     "n/a"
dotcms_2                |   ]
dotcms_2                | }
dotcms_2                |   at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:256) ~[dotcms_5.0.2_35bc8bd.jar:?]
dotcms_2                |   at com.dotcms.enterprise.cluster.ServerFactoryImpl.saveServer(SourceFile:58) ~[ee-5.0.2.jar:?]
dotcms_2                |   at com.dotcms.cluster.business.ServerAPIImpl.saveServer_aroundBody0(ServerAPIImpl.java:40) ~[dotcms_5.0.2_35bc8bd.jar:?]
dotcms_2                |   at com.dotcms.cluster.business.ServerAPIImpl$AjcClosure1.run(ServerAPIImpl.java:1) ~[dotcms_5.0.2_35bc8bd.jar:?]
dotcms_2                |   at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
dotcms_2                |   at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_5.0.2_35bc8bd.jar:?]
dotcms_2                |   at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.0.2_35bc8bd.jar:?]
dotcms_2                |   at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.0.2_35bc8bd.jar:?]
dotcms_2                |   at com.dotcms.cluster.business.ServerAPIImpl.saveServer(ServerAPIImpl.java:39) ~[dotcms_5.0.2_35bc8bd.jar:?]
dotcms_2                |   at com.dotcms.cluster.business.ServerAPIImpl.createMyServer(ServerAPIImpl.java:93) ~[dotcms_5.0.2_35bc8bd.jar:?]
dotcms_2                |   at com.dotcms.cluster.business.ServerAPIImpl.getOrCreateMyServer(ServerAPIImpl.java:55) ~[dotcms_5.0.2_35bc8bd.jar:?]
dotcms_2                |   at com.dotcms.enterprise.cluster.ClusterFactory.initialize(SourceFile:77) ~[ee-5.0.2.jar:?]
dotcms_2                |   at com.dotmarketing.startup.runalways.Task00030ClusterInitialize.executeUpgrade(Task00030ClusterInitialize.java:45) ~[dotcms_5.0.2_35bc8bd.jar:?]
dotcms_2                |   at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:212) ~[dotcms_5.0.2_35bc8bd.jar:?]
```

**Comment by wezell** [comment]
@brentgriffin performed smoke tests with the proposed change which worked as expected.
