### ISSUE TITLE
dotCMS cannot create database structure on JBOSS EAP 7.1

### ISSUE THREAD

**Issue by vianneychacon** [dotCMS/core#15502]
dotCMS is not able to deploy the starter's site database
## Expected Behavior

When an empty database is found, the system should create the basic structure using the starter site

## Current Behavior

The root cause is that dotCMS cannot read the files containing the SQL queries. From the `dotcms.log`:
```
[02/11/18 13:02:53:499 UTC]  INFO startup.StartupTasksExecutor: Starting startup tasks.
[02/11/18 13:02:54:267 UTC]  INFO runalways.Task00001LoadSchema: -------------------------------------------------------------------------------------
[02/11/18 13:02:54:267 UTC]  INFO runalways.Task00001LoadSchema:
[02/11/18 13:02:54:267 UTC]  INFO runalways.Task00001LoadSchema: Empty dotCMS database found.  Loading initial dotCMS schema for PostgreSQL
[02/11/18 13:02:54:267 UTC]  INFO runalways.Task00001LoadSchema:
[02/11/18 13:02:54:267 UTC]  INFO runalways.Task00001LoadSchema: -------------------------------------------------------------------------------------
[02/11/18 13:02:54:269 UTC]  INFO startup.StartupTasksExecutor: Running: Task00001LoadSchema
[02/11/18 13:02:54:269 UTC]  INFO runalways.Task00001LoadSchema: Loading schema
[02/11/18 13:02:54:435 UTC] FATAL runalways.Task00001LoadSchema: Error: Provider "vfs" not installed processed 0 statements
java.nio.file.FileSystemNotFoundException: Provider "vfs" not installed
        at java.nio.file.Paths.get(Paths.java:147) ~[?:1.8.0_191]
        at com.dotmarketing.startup.runalways.Task00001LoadSchema.executeUpgrade(Task00001LoadSchema.java:66) ~[dotcms_5.0.2_999999.jar:?]
        at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:212) ~[dotcms_5.0.2_999999.jar:?]
        at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:115) ~[dotcms_5.0.2_999999.jar:?]
        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117) ~[undertow-servlet-1.4.18.Final-redhat-2.jar!/:1.4.18.Final-redhat-2]
        at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78) ~[?:?]
        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103) ~[undertow-servlet-1.4.18.Final-redhat-2.jar!/:1.4.18.Final-redhat-2]
        at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:250) ~[undertow-servlet-1.4.18.Final-redhat-2.jar!/:1.4.18.Final-redhat-2]
        at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:133) ~[undertow-servlet-1.4.18.Final-redhat-2.jar!/:1.4.18.Final-redhat-2]
        at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:565) ~[undertow-servlet-1.4.18.Final-redhat-2.jar!/:1.4.18.Final-redhat-2]
        at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:536) ~[undertow-servlet-1.4.18.Final-redhat-2.jar!/:1.4.18.Final-redhat-2]
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42) ~[undertow-servlet-1.4.18.Final-redhat-2.jar!/:1.4.18.Final-redhat-2]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-1.4.18.Final-redhat-2.jar!/:1.4.18.Final-redhat-2]
        at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105) ~[?:?]
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508) ~[?:?]
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508) ~[?:?]
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508) ~[?:?]
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508) ~[?:?]
        at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:578) ~[undertow-servlet-1.4.18.Final-redhat-2.jar!/:1.4.18.Final-redhat-2]
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100) ~[?:?]
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
        at org.jboss.threads.JBossThread.run(JBossThread.java:320) ~[?:?]
```
## Steps to Reproduce (for bugs)

1. Build dotCMS as WAR
2. Deploy it in JBOSS EAP 7.1

## Your Environment

* dotCMS version used: 5.0.2
* Browser Name and version: NA
* Operating System and version: CentOS 7
* Application Server and version: JBOSS EAP 7.1
* Java Brand and version: OpenJDK 1.8.0_191
* Database and version: H2, Postgresql 9.6, MSSQL
* Application module (if apply):

**Comment by wezell** [comment]
@vianneychacon is this trying to run as an unexploded .war? does this work if you set JBoss to run as an exploded .war?

**Comment by wezell** [comment]
JT say no, it does not.

**Comment by wezell** [comment]
We need to doc on how to set up a JBoss environment - the workaround is that you need to load dotCMS and the starter.zip using the Tomcat first, before you point your Jboss installation to the dotCMS database.

**Comment by wezell** [comment]
No code fix here.
