### ISSUE TITLE
[core] Multi-language file can't be updated after other file uses original filename

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#15534]
Found while working on support ticket: [96891](https://dotcms.zendesk.com/agent/tickets/96891)
Reproducible in dotCMS 4.2.2, 5.0.3

Uploading a file asset with the same previous name than other asset that was renamed (only for a language) causes issues when trying to update one of the assets in other languages (that still have the original name) 

## Expected Behavior
When a file assets is renamed for a language, but still has the previous name for other languages, creating an new asset with the previous name shouldn't cause issues when updating assets in other languages.

## Current Behavior
If a file asset is renamed for a language, but still has the previous name for other languages, and a new asset is added with the previous name, the systems gets an error when trying to update assets in other languages.

## Possible Solution
Some possible options are:
- Not allowing to save an asset if the filename is still used by other asset for other language.
- When renaming an file asset for a language, rename also for the other languages.
- Fix the logic for updating file assets, so two different file assets are allowed to use the same filename if they belong to different languages.

## Known Workarounds
Dont't use the same filename for a new assets, when that filename is still in use for the file asset in other language. First rename the previous file asset for all the languages, then upload the new assets using the previous filename.

## Steps to Reproduce (for bugs)
1. Log into dotCMS 5.0.3
2. Upload a new file asset for English language (for example "logo.png")
3. Create a version of the file asset for Spanish language.
4. Rename only the English version (for example to "new-logo.png"). The Spanish version keeps the original name ("logo.png").
5. Upload a new file asset for English language using the original name ("logo.png").
<img width="866" alt="renamed-file-asset" src="https://user-images.githubusercontent.com/2894221/48305554-77ec6600-e4f2-11e8-8474-de052499d720.png">
7. Edit the version of the file asset for Spanish language.
8. Make a change for some property and click Save. A error message is shown

<img width="301" alt="error-saving-file-asset" src="https://user-images.githubusercontent.com/2894221/48305558-86d31880-e4f2-11e8-8942-fa9dad370b44.png">

Error message is logs is shown below:
```
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "identifier_parent_path_asset_name_host_inode_key"
  Detail: Key (parent_path, asset_name, host_inode)=(/training/, logo.png, 83e6f56f-2a60-4cd6-b3d9-1a66be98ecee) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144) ~[postgresql-42.2.2.jar:42.2.2]
	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc.jar:?]
	at com.sun.proxy.$Proxy75.execute(Unknown Source) ~[?:?]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:612) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:524) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:254) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.business.IdentifierFactoryImpl.saveIdentifier(IdentifierFactoryImpl.java:455) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.business.IdentifierAPIImpl.save_aroundBody14(IdentifierAPIImpl.java:126) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.business.IdentifierAPIImpl$AjcClosure15.run(IdentifierAPIImpl.java:1) ~[dotcms_5.0.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.business.IdentifierAPIImpl.save(IdentifierAPIImpl.java:125) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin_aroundBody118(ESContentletAPIImpl.java:3105) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure119.run(ESContentletAPIImpl.java:1) ~[dotcms_5.0.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2781) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:6148) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:6164) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkin(ContentletAPIInterceptor.java:175) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.portlets.workflows.actionlet.SaveContentActionlet.executeAction_aroundBody0(SaveContentActionlet.java:75) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.portlets.workflows.actionlet.SaveContentActionlet$AjcClosure1.run(SaveContentActionlet.java:1) ~[dotcms_5.0.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.portlets.workflows.actionlet.SaveContentActionlet.executeAction(SaveContentActionlet.java:50) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireWorkflowPostCheckin_aroundBody148(WorkflowAPIImpl.java:2061) ~[dotcms_5.0.0_999999.jar:?]
	... 98 more
```

## Context
This scenario happens when using multi language file assets, and one asset is renamed for one language only. Then a new file asset is created using the original filename (that is still in use for other languages).
Possible fix is to disable using the filename for a new asset until the previous asset is renamed for all the languages.
This was discovered while working on issue on a site reported by client in this support issue: [96891](https://dotcms.zendesk.com/agent/tickets/96891)

## Your Environment
* dotCMS version used: 4.2.2 and 5.0.3
* Browser Name and version: Not relevant
* Operating System and version: Not relevant
* Application Server and version: Not relevant
* Java Brand and version: Not relevant
* Database and version: Not relevant
* Application module (if apply): Site browser (creating and renaming file assets)

**Comment by wezell** [comment]
Notes from our meeting:

#### single source of truth for Filenames = identifier.asset_name


- [ ] we change the browser to show identifier name
- [ ] we change webdav to show identifier name
- [ ] we change edit content "file name" field to show identifier name
- [ ] we allow people to edit the identifier name on edit content screen.

- [ ] On the first upload, we take the name of the file for the identifier

- [ ] if you upload a new file (with a different name), we ask if you want to update the real url for the asset.  If so, we update the identifier, else not.

- [ ] On saving, we don't update the identifier with the new file name.

- [ ] When we "rename" or "move" the file, all we need to do is rename the identifier

- [ ] We need to fix the file asset control to show the proper "resource link"

**Comment by jgambarios** [comment]
The fixes for this issue will be handle inside this epic https://github.com/dotCMS/core/issues/15800

**Comment by bryanboza** [comment]
Unable to reproduce the main bug on master
