### ISSUE TITLE
[Push Publishing] : Provide more information when failing to push folder

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#15559]
Reproducible in latest master, and dotCMS 4.3.3
Found when working on ticket: https://dotcms.zendesk.com/agent/tickets/96985

When you create a Folder object, the `Default File Asset Type` field allows you to specify the default file Content Type used when uploading files to it. When Push Publishing such a folder, if the specified Content Type does not exist in the receiving instance, the push fails, and the logs don't provide enough useful detail.

## Expected Behavior
Improve the logging to indicate the information of the Folder that failed to push and solve the problem faster.

## Current Behavior
There's no quick information to find the failing folder quickly.

## Possible Solution
Go to the database and run queries, which is very slow when interacting with on-premise dotCMS instances.

## Known Workarounds
Go to the database and run queries, which is very slow when interacting with on-premise dotCMS instances.

## Steps to Reproduce (for bugs)
1. Set up a sending and receiving dotCMS instances.
2. Create a File Asset Content Type called "My File CT". **DO NOT push it to the receiver**.
3. Edit the `/images/` folder and set the value of the `Default File Asset Type` field to "My File CT".
4. Push publish the `/images/` folder, and check the log file.
5. You'll see an error like the following:
```
[16/11/18 07:25:00:612 PST] ERROR util.JDBCExceptionReporter: ERROR: insert or update on table "folder" violates foreign key constraint "fk_folder_file_structure_type"
Detail: Key (default_file_type)=(3977ed33-8f0d-42a0-9989-db215d3fd2db) is not present in table "structure".
[16/11/18 07:25:00:612 PST] ERROR impl.SessionImpl: Could not synchronize database state with session
[16/11/18 07:25:00:615 PST] ERROR business.PublisherAPIImpl: Error publishing bundle with ID 'c6a9049c-bc33-4e11-8052-7117a0db2333.tar.gz': Unable to save/update Object to Hibernate Session 
com.dotcms.publishing.DotPublishingException: Unable to save/update Object to Hibernate Session 
at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.a(SourceFile:232) ~[ee-4.3.3.jar:?]
at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.handle(SourceFile:79) ~[ee-4.3.3.jar:?]
at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:203) [dotcms_4.3.3_999999.jar:?]
at com.dotcms.rest.PublishThread.run(PublishThread.java:42) [dotcms_4.3.3_999999.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: com.dotmarketing.exception.DotHibernateException: Unable to save/update Object to Hibernate Session 
at com.dotmarketing.db.HibernateUtil.saveOrUpdate(HibernateUtil.java:546) ~[dotcms_4.3.3_999999.jar:?]
at com.dotmarketing.portlets.folders.business.FolderFactoryImpl.save(FolderFactoryImpl.java:1156) ~[dotcms_4.3.3_999999.jar:?]
at com.dotmarketing.portlets.folders.business.FolderAPIImpl.save_aroundBody26(FolderAPIImpl.java:569) ~[dotcms_4.3.3_999999.jar:?]
at com.dotmarketing.portlets.folders.business.FolderAPIImpl$AjcClosure27.run(FolderAPIImpl.java:1) ~[dotcms_4.3.3_999999.jar:?]
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.3.3_999999.jar:?]
at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:39) ~[dotcms_4.3.3_999999.jar:?]
at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_4.3.3_999999.jar:?]
at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_4.3.3_999999.jar:?]
at com.dotmarketing.portlets.folders.business.FolderAPIImpl.save(FolderAPIImpl.java:545) ~[dotcms_4.3.3_999999.jar:?]
at com.dotmarketing.portlets.folders.business.FolderAPIImpl.save(FolderAPIImpl.java:578) ~[dotcms_4.3.3_999999.jar:?]
at com.dotcms.enterprise.publishing.remote.handler.FolderHandler.a(SourceFile:226) ~[ee-4.3.3.jar:?]
... 4 more
```

## Context
Simply adding the information of the failing Folder allows the Engineering Team to get to the root cause of the problem way faster. This is specially important with on-premise customers.

## Your Environment
* dotCMS version used: dotCMS 4.3.3
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: Push Publishing.

**Comment by dsolistorres** [comment]
Attached backport hotfix for 4.3.3 version
[hotfix-GIT-15559_v4.3.3.zip](https://github.com/dotCMS/core/files/2830084/hotfix-GIT-15559_v4.3.3.zip)

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF.... Now we have more logging on those cases
