### ISSUE TITLE
ViewTool CalendarWebAPI.findEvents() throws "org.elasticsearch.index.query.QueryShardException: No mapping found for [calendarevent.startdate_dotraw] in order to sort on"

### ISSUE THREAD

**Issue by mwoodland** [dotCMS/core#15676]
We have a page in one of our sites that uses the CalendarWebAPI view tool to find and display events for the site.

Since upgrading to dotCMS 5.0.3 we get an exception when trying to render this page:

`org.elasticsearch.index.query.QueryShardException: No mapping found for [calendarevent.startdate_dotraw] in order to sort on
	at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:319) ~[classes/:na]
	at org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:155) ~[classes/:na]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:718) ~[classes/:na]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:552) ~[classes/:na]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:528) ~[classes/:na]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:324) ~[classes/:na]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:310) ~[classes/:na]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:306) ~[classes/:na]
	at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:996) ~[classes/:na]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) ~[classes/:na]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[classes/:na]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[classes/:na]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]`

Debugging the error shows that the sort order is added in EventFactoryImpl.findInLucene(), and the _dotraw appended in ESContentFactoryImpl.indexSearch(). With the query being generated under the following stack trace:

` java.lang.Thread.State: RUNNABLE
	  at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.indexSearch(ESContentFactoryImpl.java:1399)
	  at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.searchIndex(ESContentletAPIImpl.java:810)
	  at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.search(ESContentletAPIImpl.java:671)
	  at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.search(ESContentletAPIImpl.java:662)
	  at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.search(ContentletAPIInterceptor.java:1501)
	  at com.dotmarketing.portlets.calendar.business.EventFactoryImpl.findInLucene(EventFactoryImpl.java:287)
	  at com.dotmarketing.portlets.calendar.business.EventFactoryImpl.find(EventFactoryImpl.java:135)
	  at com.dotmarketing.portlets.calendar.business.EventAPIImpl.find(EventAPIImpl.java:98)
	  at com.dotmarketing.portlets.calendar.viewtools.CalendarWebAPI.findEvents(CalendarWebAPI.java:141)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372)
	  at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361)
	  at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:176)
	  at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285)
	  at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:572)
	  at org.apache.velocity.runtime.parser.node.ASTExpression.value(ASTExpression.java:71)
	  at org.apache.velocity.runtime.parser.node.ASTSetDirective.render(ASTSetDirective.java:150)
	  at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:339)
	  at com.dotcms.rendering.velocity.directive.DotDirective.renderTemplate(DotDirective.java:115)
	  at com.dotcms.rendering.velocity.directive.DotDirective.render(DotDirective.java:96)
	  at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:214)
	  at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:339)
	  at org.apache.velocity.Template.merge(Template.java:364)
	  at org.apache.velocity.Template.merge(Template.java:267)
	  at com.dotcms.rendering.velocity.viewtools.VelocityWebUtil.mergeTemplate(VelocityWebUtil.java:53)
	  at sun.reflect.GeneratedMethodAccessor451.invoke(Unknown Source:-1)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372)
	  at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361)
	  at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:176)
	  at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285)
	  at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:572)
	  at org.apache.velocity.runtime.parser.node.ASTExpression.value(ASTExpression.java:71)
	  at org.apache.velocity.runtime.parser.node.ASTSetDirective.render(ASTSetDirective.java:150)
	  at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:339)
	  at com.dotcms.rendering.velocity.directive.DotDirective.renderTemplate(DotDirective.java:115)
	  at com.dotcms.rendering.velocity.directive.DotDirective.render(DotDirective.java:96)
	  at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:214)
	  at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	  at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87)
	  at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	  at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:423)
	  at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:214)
	  at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:339)
	  at com.dotcms.rendering.velocity.directive.DotDirective.renderTemplate(DotDirective.java:115)
	  at com.dotcms.rendering.velocity.directive.DotDirective.render(DotDirective.java:96)
	  at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:214)
	  at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:339)
	  at org.apache.velocity.runtime.RuntimeInstance.render(RuntimeInstance.java:1361)
	  at org.apache.velocity.runtime.RuntimeInstance.evaluate(RuntimeInstance.java:1297)
	  at org.apache.velocity.runtime.RuntimeInstance.evaluate(RuntimeInstance.java:1248)
	  at org.apache.velocity.app.VelocityEngine.evaluate(VelocityEngine.java:198)
	  at org.apache.velocity.tools.generic.RenderTool.eval(RenderTool.java:138)
	  at org.apache.velocity.tools.view.tools.ViewRenderTool.eval(ViewRenderTool.java:125)
	  at sun.reflect.GeneratedMethodAccessor501.invoke(Unknown Source:-1)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372)
	  at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361)
	  at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:176)
	  at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285)
	  at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:374)
	  at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	  at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:423)
	  at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:214)
	  at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	  at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:423)
	  at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:214)
	  at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	  at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87)
	  at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:339)
	  at com.dotcms.rendering.velocity.directive.DotDirective.renderTemplate(DotDirective.java:115)
	  at com.dotcms.rendering.velocity.directive.DotDirective.render(DotDirective.java:96)
	  at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:214)
	  at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:339)
	  at org.apache.velocity.runtime.directive.Parse.render(Parse.java:264)
	  at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:214)
	  at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	  at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87)
	  at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:339)
	  at org.apache.velocity.Template.merge(Template.java:364)
	  at org.apache.velocity.Template.merge(Template.java:267)
	  at com.dotcms.rendering.velocity.servlet.VelocityLiveMode.serve(VelocityLiveMode.java:187)
	  at com.dotcms.rendering.velocity.servlet.VelocityLiveMode.serve(VelocityLiveMode.java:74)
	  at com.dotcms.rendering.velocity.servlet.VelocityServlet.service_aroundBody0(VelocityServlet.java:80)
	  at com.dotcms.rendering.velocity.servlet.VelocityServlet$AjcClosure1.run(VelocityServlet.java:1)
	  at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	  at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43)
	  at com.dotcms.aspects.interceptors.CloseDBMethodInterceptor.invoke(CloseDBMethodInterceptor.java:34)
	  at com.dotcms.aspects.aspectj.CloseDBAspect.invoke(CloseDBAspect.java:42)
	  at com.dotcms.rendering.velocity.servlet.VelocityServlet.service(VelocityServlet.java:48)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
	  at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470)
	  at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395)
	  at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316)
	  at com.dotmarketing.filters.CMSFilter.doFilterInternal(CMSFilter.java:184)
	  at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:56)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:121)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:104)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	  at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	  at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	  at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:134)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at uk.co.aquilaheywood.cms.common.filters.LoggerContextFilter.doFilter(LoggerContextFilter.java:36)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at uk.co.aquilaheywood.cms.common.filters.ClickJackingFilter.doFilter(ClickJackingFilter.java:31)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at uk.co.aquilaheywood.cms.common.filters.ForwardRequestFilter.doFilter(ForwardRequestFilter.java:53)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at uk.co.aquilaheywood.cms.common.filters.NoCacheFilter.doFilter(NoCacheFilter.java:49)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:88)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:46)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:102)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	  at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	  at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:685)
	  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
	  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
	  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	  - locked <0x6d2c> (a org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	  at java.lang.Thread.run(Thread.java:748)`

(Note that some of the line numbers above will not match the code in 5.0.3 since we're overriding the ESContentletAPIImpl and EventAPIImpl classes - but not overriding any of the behaviour in this case).

## Expected Behavior

The CalendarWebAPI should return the events rather than throwing an exception.

## Current Behavior

The CalendarWebAPI throws an exception.

## Known Workarounds

No known work around.

## Steps to Reproduce (for bugs)

1. Create a contentlet with the following vtl in it:

#if($UtilMethods.isSet($request.getParameter('date')))
  #set($dateString = $request.getParameter('date'))
#else
  #set($dateString = $date.format('yyyy-MM-dd',$UtilMethods.getCurrentDate()))
#end
#set($nowlv = $date.toDate('yyyy-MM-dd',$dateString))
#set($now = $date.toDate('yyyy-MM-dd',$dateString))
#set($fromDatelv = $date.toDate('yyyy-MM-dd',$dateString))
#set($toDatelv = $date.toDate('yyyy-MM-dd',$dateString))
#set($calendarlv = $date.toCalendar($nowlv))
#set($dayOfWeeklv = $math.sub($calendarlv.get(7),1))

#set($temp = $fromDatelv.setTime($math.sub($fromDatelv.getTime(), $math.mul(86400000,$dayOfWeeklv))))
#set($temp = $toDatelv.setTime($math.add($toDatelv.getTime(),$math.sub($math.mul(86400000,$math.sub(7,$dayOfWeeklv)),1))))

#set($tag = $request.getParameter('tag'))
#set($keywordBox = $request.getParameter('keywordBox'))

#if($UtilMethods.isSet($request.getParameter('cat')))
  #set($catV= $request.getParameter('cat'))
#else
  #set($catV= '')
#end

#set($events = $calendar.findEvents($host.identifier, $fromDatelv, $toDatelv, $tag, $keywordBox, $catV, "startDate", 1 , -1))

2. Try and view the contentlet.

## Context

This is causing an error when trying to view a page that displays the events for the current site.

## Your Environment

* dotCMS version used: 5.0.3
* Browser Name and version: N/A
* Operating System and version: CentOS Linux release 7.5.1804 (Core) 
* Application Server and version: tomcat 8.5.32
* Java Brand and version: jdk8_u152
* Database and version: mysql57-community

**Comment by mwoodland** [comment]
Changing the ESContentFactoryImpl to not append the _dotraw didn't seem to help as I ended up with an error "org.elasticsearch.index.query.QueryShardException: No mapping found for [calendarevent.startdate] in order to sort on" instead.

**Comment by mwoodland** [comment]
I've discovered that this errors seems to be being caused by some corrupted contentlets that are in my site.

**Comment by mwoodland** [comment]
After further investigation my it turns out my previous assertion was incorrect.

I've now managed to reproduce this issue on the demo site (https://demo.dotcms.com/dotAdmin/)

1. Log into the demo site and delete all the existing events (use the content search and search for content type "Event" and then unpublish and archive all the events, then show the archived events and delete them).
2. Through the system > maintenance > index page - rebuild the whole elastic search index.
3. Through the Dev tools > Query tool page - run a lucene query "+live:true" sorting on calendarEvent.startDate

You get an error: "Query Error :
java.lang.RuntimeException: Failed to execute phase [query], all shards failed; shardFailures {[g6r2sKFlSOSsViFTX-_cow][live_20181213093315][0]: RemoteTransportException[[ccf72c2ecee3][172.20.0.2:9300][indices:data/read/search[phase/query]]]; nested: QueryShardException[No mapping found for [calendarevent.sortorder_dotraw] in order to sort on]; }"

If you then add a new event and re-run the query the query will complete successfully.

**Comment by mwoodland** [comment]
By performing the above steps I also break the calendar page under the content menu. When going to the calendar page it gets stuck loading and displaying the spinny wheel thing.

**Comment by mwoodland** [comment]
Yes that's correct. If there are no events and you reindex then the problem occurs.

If you then add an event then the problem goes away, even if you then delete that event again.

**Comment by wezell** [comment]
What happens is that the fields get mapped into elasticsearch lazily, meaning if there are no events to be put into the index, elasticsearch does not have the mapping for it.  I used your vtl and steps to reproduce and  I see the error in the log, but it is a single line with a warn, not a stack and seems like just a noise problem rather than a critical issue.  It will also go away the first time an event is added.

`08:53:52.016  WARN  viewtools.CalendarWebAPI - findEvents Unable to search on lucene index. query = +type:content +structureInode:f6259cc9-5d78-453e-8167-efd7b72b2e96 +date1:[19000101000000 TO 20181215235959]  +(date2:[20181209000000 TO 30000101000000] (+(date4:[2018 TO 2920-08-31] bool2:true ) -bool1:false))+(conHost:48190c8c-42c4-46af-8d1a-0cd5db894797 conHost:SYSTEM_HOST) +live:true @ url:GET//demo.dotcms.com/api/v1/containers/5363c6c6-5ba0-4946-b7af-cf875188ac2e/content/2cf78f6c-87a1-4819-9b6f-bf3d0a179389 | lang:1 | ip:0:0:0:0:0:0:0:1 | Admin:true | start:12-13-2018 08:47:55 EST  ref:http://localhost:8080/dotAdmin/ >/EDIT_MODE/e6761364-d224-4a53-a5e6-67de7619a0c5/694805c6-8f07-467f-a434-0da04a93e9e5.fields`

**Comment by mwoodland** [comment]
Can you try reproducing the point about the calendar page on the demo site please?

When the calendarEvent.startDate is not in the index the calendar page in the admin site on the demo site doesn't work correctly.

We have a page in our sites that behaves similarly to how the demo calendar works, and we have this error when trying to populate the page if there are no events and the mapping isn't there.

**Comment by mattyarbrough** [comment]
Note that steps to reproduce on demo are:

Log into the demo site and delete all the existing events (use the content search and search for content type "Event" and then unpublish and archive all the events, then show the archived events and delete them). 
Through the system > maintenance > index page - rebuild the whole elastic search index. 
Through the Dev tools > Query tool page - run a lucene query "+live:true" sorting on calendarEvent.startDate 
You get an error: "Query Error : 
java.lang.RuntimeException: Failed to execute phase [query], all shards failed; shardFailures {[g6r2sKFlSOSsViFTX-_cow][live_20181213093315][0]: RemoteTransportException[[ccf72c2ecee3][172.20.0.2:9300][indices:data/read/search[phase/query]]]; nested: QueryShardException[No mapping found for [calendarevent.sortorder_dotraw] in order to sort on]; }"

If you then add a new event and re-run the query the query will complete successfully.

By performing the above steps I also break the calendar page under the content menu. When going to the calendar page it gets stuck loading and displaying the spinny wheel thin

**Comment by wezell** [comment]
The workaround is to add a single event to your site.
