### ISSUE TITLE
Folders failing to delete sporadically

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15736]
We are seeing errors in our tests that are variations of :
```
com.dotmarketing.exception.DotDataException: Failed-to-delete-unarchived-content
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete_aroundBody22(FolderAPIImpl.java:442)
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl$AjcClosure23.run(FolderAPIImpl.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43)
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40)
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23)
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41)
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete(FolderAPIImpl.java:327)
	at com.dotcms.rendering.velocity.services.HTMLPageAssetRenderedTest.restore(HTMLPageAssetRenderedTest.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.GeneratedMethodAccessor694.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:108)
	at sun.reflect.GeneratedMethodAccessor693.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.dotmarketing.business.DotStateException: Failed-to-delete-unarchived-content
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl._deleteChildrenAssetsFromFolder(FolderAPIImpl.java:529)
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete_aroundBody22(FolderAPIImpl.java:387)
	... 44 more
```

**Comment by wezell** [comment]
Happens on MySQL when you delete the demo host:
```
11:51:42.449  INFO  util.AdminLogger - UserId : dotcms.org.1 : class com.dotmarketing.portlets.folders.business.FolderAPIImpl : delete : Deleting folder with name login 
11:51:42.504  INFO  business.FolderAPIImpl - UserId : dotcms.org.1 : delete : Deleting folder with name spring 
11:51:42.504  INFO  util.AdminLogger - UserId : dotcms.org.1 : class com.dotmarketing.portlets.folders.business.FolderAPIImpl : delete : Deleting folder with name spring 
11:51:42.509  INFO  util.ActivityLogger - class com.dotcms.content.elasticsearch.business.ESContentletAPIImpl: demo.dotcms.com : Deleting Content , StartDate: N/A; EndDate: N/A; User:dotcms.org.1; ContentIdentifier: 951e63e3-8e3f-4ce4-92ef-ff9d7f66480e
11:51:42.512  ERROR business.FolderAPI - An error occurred when deleting contents of folder '/application/spring/' with Identifier [be731dec-372c-41b1-b8ec-894ec939d29a]: Failed to delete unarchived content. Content must be archived before it can be deleted.
com.dotmarketing.portlets.contentlet.business.DotContentletStateException: Failed to delete unarchived content. Content must be archived before it can be deleted.
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.deleteContentlets(ESContentletAPIImpl.java:1746) ~[classes/:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.delete_aroundBody62(ESContentletAPIImpl.java:1510) ~[classes/:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure63.run(ESContentletAPIImpl.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[classes/:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[classes/:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[classes/:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[classes/:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.delete(ESContentletAPIImpl.java:1508) ~[classes/:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.delete(ESContentletAPIImpl.java:1433) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.delete(ContentletAPIInterceptor.java:446) ~[classes/:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl._deleteChildrenAssetsFromFolder(FolderAPIImpl.java:483) ~[classes/:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete_aroundBody22(FolderAPIImpl.java:387) ~[classes/:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl$AjcClosure23.run(FolderAPIImpl.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[classes/:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[classes/:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[classes/:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[classes/:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete(FolderAPIImpl.java:327) ~[classes/:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete_aroundBody22(FolderAPIImpl.java:379) ~[classes/:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl$AjcClosure23.run(FolderAPIImpl.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[classes/:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[classes/:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[classes/:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[classes/:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete(FolderAPIImpl.java:327) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl$1DeleteHostThread.deleteHost(HostAPIImpl.java:667) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl$1DeleteHostThread.call_aroundBody0(HostAPIImpl.java:599) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl$1DeleteHostThread$AjcClosure1.run(HostAPIImpl.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[classes/:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[classes/:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[classes/:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl$1DeleteHostThread.call(HostAPIImpl.java:596) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl$1DeleteHostThread.call(HostAPIImpl.java:1) ~[classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
11:51:42.514  ERROR business.HostAPIImpl - Failed to delete unarchived content. Content must be archived before it can be deleted.
com.dotmarketing.exception.DotDataException: Failed to delete unarchived content. Content must be archived before it can be deleted.
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete_aroundBody22(FolderAPIImpl.java:442) ~[classes/:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl$AjcClosure23.run(FolderAPIImpl.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[classes/:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[classes/:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[classes/:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[classes/:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete(FolderAPIImpl.java:327) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl$1DeleteHostThread.deleteHost(HostAPIImpl.java:667) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl$1DeleteHostThread.call_aroundBody0(HostAPIImpl.java:599) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl$1DeleteHostThread$AjcClosure1.run(HostAPIImpl.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[classes/:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[classes/:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[classes/:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl$1DeleteHostThread.call(HostAPIImpl.java:596) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl$1DeleteHostThread.call(HostAPIImpl.java:1) ~[classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: com.dotmarketing.exception.DotDataException: Failed to delete unarchived content. Content must be archived before it can be deleted.
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete_aroundBody22(FolderAPIImpl.java:442) ~[classes/:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl$AjcClosure23.run(FolderAPIImpl.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[classes/:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[classes/:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[classes/:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[classes/:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete(FolderAPIImpl.java:327) ~[classes/:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete_aroundBody22(FolderAPIImpl.java:379) ~[classes/:?]
	... 21 more
Caused by: com.dotmarketing.business.DotStateException: Failed to delete unarchived content. Content must be archived before it can be deleted.
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl._deleteChildrenAssetsFromFolder(FolderAPIImpl.java:529) ~[classes/:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete_aroundBody22(FolderAPIImpl.java:387) ~[classes/:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl$AjcClosure23.run(FolderAPIImpl.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[classes/:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[classes/:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[classes/:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[classes/:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete(FolderAPIImpl.java:327) ~[classes/:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete_aroundBody22(FolderAPIImpl.java:379) ~[classes/:?]
	... 21 more
Caused by: com.dotmarketing.portlets.contentlet.business.DotContentletStateException: Failed to delete unarchived content. Content must be archived before it can be deleted.
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.deleteContentlets(ESContentletAPIImpl.java:1746) ~[classes/:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.delete_aroundBody62(ESContentletAPIImpl.java:1510) ~[classes/:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure63.run(ESContentletAPIImpl.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[classes/:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[classes/:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[classes/:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[classes/:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.delete(ESContentletAPIImpl.java:1508) ~[classes/:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.delete(ESContentletAPIImpl.java:1433) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.delete(ContentletAPIInterceptor.java:446) ~[classes/:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl._deleteChildrenAssetsFromFolder(FolderAPIImpl.java:483) ~[classes/:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete_aroundBody22(FolderAPIImpl.java:387) ~[classes/:?]
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl$AjcClosure23.run(FolderAPIImpl.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
```

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15741

**Comment by bryanboza** [comment]
Fixed, this test isn't failing in the last nightly builds
