### ISSUE TITLE
Unable to start dotcms-5.03 on Jboss-eap-6.4 and H2

### ISSUE THREAD

**Issue by ConnorLH** [dotCMS/core#15745]
I'm running CentOS 7, and deploy-as-a-war-in-jboss-eap-6-4. Finally I can't start release-5.03.
I followed this doc to deploy
https://dotcms.com/docs/latest/deploy-as-a-war-in-jboss-eap-6-4

## Steps to Reproduce
1. Followed docs to deploy
2. Start Jboss and find symptoms in the startlog
3. Jboss starte successfully
4. Cann't access dotcms application from browser

## Jboss log
02:00:37,713 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/]] (ServerService Thread Pool -- 61) JBWEB000289: Servlet Init threw load() exception: com.dotmarketing.exception.DotRuntimeException: No Company!
        at com.dotmarketing.cms.factories.PublicCompanyFactory.getDefaultCompany(PublicCompanyFactory.java:59) [dotcms_5.0.3_999999.jar:]
        at com.dotmarketing.servlets.StartupLogger.log(StartupLogger.java:23) [dotcms_5.0.3_999999.jar:]
        at com.dotmarketing.servlets.InitServlet.init(InitServlet.java:109) [dotcms_5.0.3_999999.jar:]
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1194) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1100) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:3593) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:3802) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
        at org.jboss.as.web.deployment.WebDeploymentService.doStart(WebDeploymentService.java:163) [jboss-as-web-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
        at org.jboss.as.web.deployment.WebDeploymentService.access$000(WebDeploymentService.java:61) [jboss-as-web-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
        at org.jboss.as.web.deployment.WebDeploymentService$1.run(WebDeploymentService.java:96) [jboss-as-web-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [rt.jar:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_181]
        at org.jboss.threads.JBossThread.run(JBossThread.java:122)

## My Environment
* dotCMS version used: release-5.03
* Browser Name and version: Chrome 69.0.3497.92
* Operating System and version: CentOS Linux release 7.5.1804
* Application Server and version: jboss-eap-6-4
* Java Brand and version: 1.8.0_181
* Database and version: H2

**Comment by wezell** [comment]
Are you trying to use h2 as your primary database?  Know that moving forward, all H2 use is deprecated and we don't recommend using it as the datastore for any purpose in dotCMS.

There is an issue with JBoss virtual file system loading the initial starter site into the db.  The current workaround for starting a fresh JBoss instance is this - start dotCMS using the distribution of tomcat pointed at the db of your choice.  Once the db has been populated, shutdown tomcat, and point your JBoss server at the newly created database.
