### ISSUE TITLE
[Push Publishing] : Pushing content with Tags that have single quote in their names are failing

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#15792]
Reproducible in dotCMs 4.3.3
Reported by customer via Support: https://dotcms.zendesk.com/agent/tickets/97261

Tags associated to Contentlets might have single quotes in their names. When pushing a Contentlet with associated Tags, the Push Publishing mechanism validates if the pushed Tags need to be updated or created in the destination dotCMS instance. When those Tags have single quotes in their names, the API is failing to handle them correctly and the push fails.

## Expected Behavior
The API must handle single quotes correctly.

## Current Behavior
Tags with single quotes in their names are causing Push Publishing to fail.

## Possible Solution
Code fix.

## Known Workarounds
N/A

## Steps to Reproduce
1. Create a dotCMS Push Publishing Environment with one sender and one receiver.
2. Create an HTML Page, and associate a Tag to it (add the `Tag` field to the Content Type if needed).
3. Push the new HTML Page to the receiver.
4. Force Push or make any change to the HTML Page so that it will be pushed again.
5. The Push fails, and the `dotcms.log` file displays an error similar to this one:
```
[07/01/19 16:17:49:131 EST] INFO caffine.CaffineCache: ***	Building Cache : workflowstepcache, size:1000,Concurrency:32
[07/01/19 16:17:49:140 EST] ERROR business.PublisherAPIImpl: Error publishing bundle with ID '197bc049-f2ff-41f9-b202-422cd98bfb3f.tar.gz': null
com.dotcms.publishing.DotPublishingException
at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:368) ~[ee-4.3.3.jar:?]
at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(SourceFile:153) ~[ee-4.3.3.jar:?]
at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(SourceFile:130) ~[ee-4.3.3.jar:?]
at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:203) [dotcms_4.3.3_999999.jar:?]
at com.dotcms.rest.PublishThread.run(PublishThread.java:42) [dotcms_4.3.3_999999.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
at com.dotcms.repackage.uk.ltd.getahead.dwr.WebContextFactory$ProxyWebContext.getHttpServletRequest(WebContextFactory.java:104) ~[dot.dwr-3rc2modified_2.jar:?]
at com.dotmarketing.util.web.WebDotcmsException.getFomatedMessage(WebDotcmsException.java:45) ~[dotcms_4.3.3_999999.jar:?]
at com.dotmarketing.util.web.WebDotcmsException.<init>(WebDotcmsException.java:31) ~[dotcms_4.3.3_999999.jar:?]
at com.dotmarketing.tag.business.GenericTagException.<init>(GenericTagException.java:11) ~[dotcms_4.3.3_999999.jar:?]
at com.dotmarketing.tag.business.TagAPIImpl.saveTag(TagAPIImpl.java:281) ~[dotcms_4.3.3_999999.jar:?]
at com.dotmarketing.tag.business.TagAPIImpl.saveTag(TagAPIImpl.java:216) ~[dotcms_4.3.3_999999.jar:?]
at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:693) ~[ee-4.3.3.jar:?]
at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:565) ~[ee-4.3.3.jar:?]
at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:225) ~[ee-4.3.3.jar:?]
... 5 more
[07/01/19 16:17:49:145 EST] ERROR lang.String: Error publishing bundle with ID '197bc049-f2ff-41f9-b202-422cd98bfb3f.tar.gz': com.dotcms.publishing.DotPublishingException
[07/01/19 16:17:49:145 EST] INFO rest.PublishThread: Finished bundle publish process
```

## Your Environment
* dotCMS version used: 4.3.3
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module: Push Publishing

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/15798

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF and after the changes, I'm unable to recreate the issue... A new case reported here #15885
