### ISSUE TITLE
[Search] Elastic Search fails when using "function_score" in a query

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#15845]
Reported via support ticket: [97338](https://dotcms.zendesk.com/agent/tickets/97338)
Reproducible in dotCMS 5.0.3

Executing an Elastic Search query fails when using "function_score".

## Expected Behavior
Function Score queries (queries with "function_score") should be supported as documented in:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html

## Current Behavior
Queries with "function_score" don't run and return an error.

## Possible Solution
Include score functions (script_score, random_score, field_value_factor, decay functions) in the class com.dotcms.enterprise.priv.util.SearchSourceBuilderUtil

## Known Workarounds
None

## Steps to Reproduce (for bugs)
1. Create an Elastic Search query using "function_score" including a score function as random_score or script_score. For example:
```
{
    "query": {
        "function_score": {
            "query": { "match_all": {} },
            "boost": "5",
            "random_score": {}, 
            "boost_mode":"multiply"
        }
    }
}
```
2. Run the elastic search against dotCMS using Elastic Search REST API:
```
curl -H "Content-Type: application/json" -XPOST http://localhost:8080/api/es/search -d @ es-query.json
```
3. dotCMS returns an error message: `Unknown namedObject category [org.elasticsearch.index.query.functionscore.ScoreFunctionBuilder]`

The following stack tracke shows in dotcms.log:
```
[16/01/19 09:02:55:535 CST]  WARN elasticsearch.ESContentResourcePortlet: Error processing :Unknown namedObject category [org.elasticsearch.index.query.functionscore.ScoreFunctionBuilder]
org.elasticsearch.ElasticsearchException: Unknown namedObject category [org.elasticsearch.index.query.functionscore.ScoreFunctionBuilder]
	at org.elasticsearch.common.xcontent.NamedXContentRegistry.parseNamedObject(NamedXContentRegistry.java:131) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.namedObject(AbstractXContentParser.java:402) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.query.functionscore.FunctionScoreQueryBuilder.fromXContent(FunctionScoreQueryBuilder.java:477) ~[elasticsearch-6.1.3.jar:6.1.3]
	at com.dotcms.enterprise.priv.util.SearchSourceBuilderUtil.lambda$registerQuery$3(SearchSourceBuilderUtil.java:218) ~[ee_clean.jar:?]
	at org.elasticsearch.common.xcontent.NamedXContentRegistry.parseNamedObject(NamedXContentRegistry.java:143) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.namedObject(AbstractXContentParser.java:402) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.query.AbstractQueryBuilder.parseInnerQueryBuilder(AbstractQueryBuilder.java:313) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.builder.SearchSourceBuilder.parseXContent(SearchSourceBuilder.java:1003) ~[elasticsearch-6.1.3.jar:6.1.3]
	at com.dotcms.enterprise.priv.util.SearchSourceBuilderUtil.getSearchSourceBuilder(SearchSourceBuilderUtil.java:210) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.priv.ESSearchAPIImpl.esSearchRaw(ESSearchAPIImpl.java:258) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.priv.ESSearchAPIImpl.esSearch(ESSearchAPIImpl.java:45) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.priv.ESSearchProxy.esSearch(ESSearchProxy.java:49) ~[ee_clean.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.esSearch(ESContentletAPIImpl.java:168) ~[dotcms_5.0.2_999999.jar:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.esSearch(ContentletAPIInterceptor.java:2404) ~[dotcms_5.0.2_999999.jar:?]
	at com.dotcms.rest.elasticsearch.ESContentResourcePortlet.search(ESContentResourcePortlet.java:64) ~[dotcms_5.0.2_999999.jar:?]
	at com.dotcms.rest.elasticsearch.ESContentResourcePortlet.searchPost(ESContentResourcePortlet.java:118) ~[dotcms_5.0.2_999999.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[dot.jersey-common-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[dot.jersey-common-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[dot.jersey-common-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[dot.jersey-common-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[dot.jersey-common-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) ~[dot.jersey-common-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471) ~[dot.jersey-container-servlet-core-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425) ~[dot.jersey-container-servlet-core-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383) ~[dot.jersey-container-servlet-core-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336) ~[dot.jersey-container-servlet-core-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223) ~[dot.jersey-container-servlet-core-2.22.1_4.jar:?]
	at com.dotcms.rest.servlet.ReloadableServletContainer.service(ReloadableServletContainer.java:98) ~[dotcms_5.0.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.CMSFilter.doFilterInternal(CMSFilter.java:199) ~[dotcms_5.0.2_999999.jar:?]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:56) ~[dotcms_5.0.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) ~[dotcms_5.0.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) ~[dotcms_5.0.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:114) ~[dotcms_5.0.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:104) ~[dotcms_5.0.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:399) ~[urlrewritefilter-4.0.4.jar:4.0.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:66) ~[dotcms_5.0.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:88) ~[dotcms_5.0.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:46) ~[dotcms_5.0.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:102) ~[dotcms_5.0.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[catalina.jar:8.5.32]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) ~[catalina.jar:8.5.32]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[catalina.jar:8.5.32]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[catalina.jar:8.5.32]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) ~[catalina.jar:8.5.32]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:8.5.32]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.32]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

## Context
This issue avoids using "function_score" in Elastic Search queries.
This was reported by client in this support issue: [97338](https://dotcms.zendesk.com/agent/tickets/97338)

## Your Environment
* dotCMS version used: 5.0.3
* Browser Name and version: Not relevant
* Operating System and version: Not relevant
* Application Server and version: Not relevant
* Java Brand and version: Not relevant
* Database and version: Not relavant
* Application module (if apply): Elastic Search

**Comment by nollymar** [comment]
A first approach to solve this problem was committed on this branch https://github.com/dotCMS/enterprise-2.x/tree/include-score-function-spec where this class was modified https://github.com/dotCMS/enterprise-2.x/blob/include-score-function-spec/src/main/java/com/dotcms/enterprise/priv/util/SearchSourceBuilderUtil.java

A test should be included.

**Comment by nollymar** [comment]
PR Enterprise: https://github.com/dotCMS/enterprise-2.x/pull/653

**Comment by nollymar** [comment]
Integration test included here: https://github.com/dotCMS/core/pull/16065

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF
