### ISSUE TITLE
SPA crashes on non-layout pages

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15915]
```
Debugger listening on ws://0.0.0.0:9229/6441fb2c-2133-4934-9268-b1c0a924aeff
For help see https://nodejs.org/en/docs/inspector
Server running http://localhost:5000
/Users/will/git/dotcms5/dotcms-spa-edit-mode/src/libs/dotcms.api.js:35
  if (page.layout) {
           ^

TypeError: Cannot read property 'layout' of undefined
    at Object.layout [as translate] (/Users/will/git/dotcms5/dotcms-spa-edit-mode/src/libs/dotcms.api.js:12:14)
    at IncomingMessage.translate (/Users/will/git/dotcms5/dotcms-spa-edit-mode/backend/server/server.js:73:41)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
[nodemon] app crashed - waiting for file changes before starting...


^Cnpm ERR! code ELIFECYCLE
npm ERR! errno 130
npm ERR! dotcms-spa-edit-mode-round@0.1.0 serve: `npm run build && nodemon --inspect=0.0.0.0:9229 backend/server/index.js`
npm ERR! Exit status 130
npm ERR!
npm ERR! Failed at the dotcms-spa-edit-mode-round@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

mustardgreen:dotcms-spa-edit-mode will$
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/will/.npm/_logs/2019-01-28T20_56_14_173Z-debug.log
```

**Comment by hmoreras** [comment]
After research... and together with Freddy, looks like this is not an error anymore with the updates the past week
