### ISSUE TITLE
FileAssets can disappear from the index

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15998]
Happens when saving a fileAsset (and might be helped along by hitting that asset on the front end).  The file asset as content is ok on the db and in the file system, it just does not appear in the browser or in the content search table (effectively disappearing). 

I get this in the logs:
```
Feb 07, 2019 7:43:32 PM com.dotcms.repackage.org.glassfish.jersey.servlet.WebComponent filterFormParameters
WARNING: A servlet request to the URI http://localhost:8080/api/v1/content/fileassets/02a58526-2afe-41c7-bb7a-0787b97c9763/resourcelink?dojo.preventCache=1549586612137 contains form parameters in the request body but the request body has been consumed by the servlet or a servlet filter accessing the request parameters. Only resource methods using @FormParam will work as expected. Resource methods consuming the request body by other means will not work as expected.
19:43:32.147  ERROR fileasset.FileAssetsResource - Exception on method findResourceLink with exception message: null
java.lang.NullPointerException: null
	at com.dotmarketing.portlets.contentlet.model.ResourceLink$ResourceLinkBuilder.build(ResourceLink.java:99) ~[classes/:?]
	at com.dotcms.rest.api.v1.fileasset.FileAssetsResource.findResourceLink(FileAssetsResource.java:71) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) ~[dot.jersey-server-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[dot.jersey-common-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[dot.jersey-common-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[dot.jersey-common-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[dot.jersey-common-2.22.1_4.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[dot.jersey-common-2.22.1_4.jar:?]
```

and this in the DB:

```
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 988
Server version: 10.3.9-MariaDB Homebrew

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [dotcms5]> select * from identifier where parent_path = '/application/vtl/';
+--------------------------------------+-------------------+-----------------+--------------------------------------+------------+-----------------+----------------+
| id                                   | parent_path       | asset_name      | host_inode                           | asset_type | syspublish_date | sysexpire_date |
+--------------------------------------+-------------------+-----------------+--------------------------------------+------------+-----------------+----------------+
| 6af05731-cbfa-4cb6-8cf3-59c7bb19f94d | /application/vtl/ | containers      | 48190c8c-42c4-46af-8d1a-0cd5db894797 | folder     | NULL            | NULL           |
| 0d60f507-558c-4763-aea2-ce760d4fc1b0 | /application/vtl/ | custom-fields   | 48190c8c-42c4-46af-8d1a-0cd5db894797 | folder     | NULL            | NULL           |
| a86888c4-d819-4a17-8bd8-a215ef9fed16 | /application/vtl/ | custom-workflow | 48190c8c-42c4-46af-8d1a-0cd5db894797 | folder     | NULL            | NULL           |
| 2179549e-62a8-467a-9564-54f35437abe4 | /application/vtl/ | macros          | 48190c8c-42c4-46af-8d1a-0cd5db894797 | folder     | NULL            | NULL           |
| b99d08e7-63ad-4e5b-9fd2-3fb53b50e613 | /application/vtl/ | pages           | 48190c8c-42c4-46af-8d1a-0cd5db894797 | folder     | NULL            | NULL           |
| 83877213-9a36-4a4c-bdd4-867a84642e18 | /application/vtl/ | test.vtl        | 48190c8c-42c4-46af-8d1a-0cd5db894797 | contentlet | NULL            | NULL           |
| fd6ca757-298d-4605-87c4-580c42c5d8f8 | /application/vtl/ | widgets         | 48190c8c-42c4-46af-8d1a-0cd5db894797 | folder     | NULL            | NULL           |
+--------------------------------------+-------------------+-----------------+--------------------------------------+------------+-----------------+----------------+
7 rows in set (0.000 sec)

MariaDB [dotcms5]> select * from identifier where parent_path = '/application/vtl/' and asset_name='test.vtl';
+--------------------------------------+-------------------+------------+--------------------------------------+------------+-----------------+----------------+
| id                                   | parent_path       | asset_name | host_inode                           | asset_type | syspublish_date | sysexpire_date |
+--------------------------------------+-------------------+------------+--------------------------------------+------------+-----------------+----------------+
| 83877213-9a36-4a4c-bdd4-867a84642e18 | /application/vtl/ | test.vtl   | 48190c8c-42c4-46af-8d1a-0cd5db894797 | contentlet | NULL            | NULL           |
+--------------------------------------+-------------------+------------+--------------------------------------+------------+-----------------+----------------+
1 row in set (0.000 sec)

MariaDB [dotcms5]> select * from contentlet_version_info where identifier ='83877213-9a36-4a4c-bdd4-867a84642e18';
+--------------------------------------+------+--------------------------------------+--------------------------------------+---------+-----------+---------------------+---------------------+
| identifier                           | lang | working_inode                        | live_inode                           | deleted | locked_by | locked_on           | version_ts          |
+--------------------------------------+------+--------------------------------------+--------------------------------------+---------+-----------+---------------------+---------------------+
| 83877213-9a36-4a4c-bdd4-867a84642e18 |    1 | 02a58526-2afe-41c7-bb7a-0787b97c9763 | 02a58526-2afe-41c7-bb7a-0787b97c9763 |         | NULL      | 2019-02-08 00:43:31 | 2019-02-08 00:43:30 |
+--------------------------------------+------+--------------------------------------+--------------------------------------+---------+-----------+---------------------+---------------------+
1 row in set (0.000 sec)

MariaDB [dotcms5]> select * from contentlet where inode='02a58526-2afe-41c7-bb7a-0787b97c9763';
+--------------------------------------+--------------+----------+---------------------+--------------+------------+---------------+--------------------------------------+---------------------+-------------+-----------------+------------------+--------------------------------------+-------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+-------+----------+----------+-------+-------+-------+-------+-------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+-------------------------------------------------------------------+------------+------------+------------+------------+------------+------------+------------+------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+----------+----------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+-------+-------+-------+-------+-------+-------+-------+-------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+
| inode                                | show_on_menu | title    | mod_date            | mod_user     | sort_order | friendly_name | structure_inode                      | last_review         | next_review | review_interval | disabled_wysiwyg | identifier                           | language_id | date1 | date2 | date3 | date4 | date5 | date6 | date7 | date8 | date9 | date10 | date11 | date12 | date13 | date14 | date15 | date16 | date17 | date18 | date19 | date20 | date21 | date22 | date23 | date24 | date25 | text1 | text2    | text3    | text4 | text5 | text6 | text7 | text8 | text9 | text10 | text11 | text12 | text13 | text14 | text15 | text16 | text17 | text18 | text19 | text20 | text21 | text22 | text23 | text24 | text25 | text_area1                                                        | text_area2 | text_area3 | text_area4 | text_area5 | text_area6 | text_area7 | text_area8 | text_area9 | text_area10 | text_area11 | text_area12 | text_area13 | text_area14 | text_area15 | text_area16 | text_area17 | text_area18 | text_area19 | text_area20 | text_area21 | text_area22 | text_area23 | text_area24 | text_area25 | integer1 | integer2 | integer3 | integer4 | integer5 | integer6 | integer7 | integer8 | integer9 | integer10 | integer11 | integer12 | integer13 | integer14 | integer15 | integer16 | integer17 | integer18 | integer19 | integer20 | integer21 | integer22 | integer23 | integer24 | integer25 | float1 | float2 | float3 | float4 | float5 | float6 | float7 | float8 | float9 | float10 | float11 | float12 | float13 | float14 | float15 | float16 | float17 | float18 | float19 | float20 | float21 | float22 | float23 | float24 | float25 | bool1 | bool2 | bool3 | bool4 | bool5 | bool6 | bool7 | bool8 | bool9 | bool10 | bool11 | bool12 | bool13 | bool14 | bool15 | bool16 | bool17 | bool18 | bool19 | bool20 | bool21 | bool22 | bool23 | bool24 | bool25 |
+--------------------------------------+--------------+----------+---------------------+--------------+------------+---------------+--------------------------------------+---------------------+-------------+-----------------+------------------+--------------------------------------+-------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+-------+----------+----------+-------+-------+-------+-------+-------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+-------------------------------------------------------------------+------------+------------+------------+------------+------------+------------+------------+------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+----------+----------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+-------+-------+-------+-------+-------+-------+-------+-------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+
| 02a58526-2afe-41c7-bb7a-0787b97c9763 |            0 | test.vtl | 2019-02-08 00:43:29 | dotcms.org.1 |          0 | test.vtl      | 33888b6f-7a8e-4069-b1b6-5c1aa9d0a48d | 2019-02-08 00:43:28 | NULL        | NULL            |                  | 83877213-9a36-4a4c-bdd4-867a84642e18 |           1 | NULL  | NULL  | NULL  | NULL  | NULL  | NULL  | NULL  | NULL  | NULL  | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL  | test.vtl | test.vtl | NULL  | test  | NULL  | NULL  | NULL  | NULL  | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | NULL   | {"fileSize":"449","contentType":"text/plain; charset=ISO-8859-1"} | NULL       | NULL       | NULL       | NULL       | NULL       | NULL       | NULL       | NULL       | NULL        | NULL        | NULL        | NULL        | NULL        | NULL        | NULL        | NULL        | NULL        | NULL        | NULL        | NULL        | NULL        | NULL        | NULL        | NULL        |        0 |        0 |        0 |        0 |        0 |        0 |        0 |        0 |        0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |         0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |       0 |       0 |       0 |       0 |       0 |       0 |       0 |       0 |       0 |       0 |       0 |       0 |       0 |       0 |       0 |       0 |     0 |     0 |     0 |     0 |     0 |     0 |     0 |     0 |     0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |
+--------------------------------------+--------------+----------+---------------------+--------------+------------+---------------+--------------------------------------+---------------------+-------------+-----------------+------------------+--------------------------------------+-------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+-------+----------+----------+-------+-------+-------+-------+-------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+-------------------------------------------------------------------+------------+------------+------------+------------+------------+------------+------------+------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+----------+----------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+-------+-------+-------+-------+-------+-------+-------+-------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+
1 row in set (0.001 sec)

```

The ContentletCache returns a 404 on the inode lookup

```
cache.get("02a58526-2afe-41c7-bb7a-0787b97c9763")
```
by Inode: com.dotmarketing.portlets.contentlet.model.Contentlet@22704d69[map={inode=CACHE_404_CONTENTLET, identifier=, nullProperties=[], disabledWYSIWYG=[], sortOrder=0, languageId=0, stInode=},lowIndexPriority=false]

**Comment by wezell** [comment]
So this gives us two issues:
1. a reindex does not fix this, which is bad.  It takes a cache flush and a reindex.  We should not rely on the cache to do a reindex, or at least fall back to the db if we get nothing back from the `contentletapi.find(inode)`
2. we have a condition where a cache is not being invalidated properly post checkin.

**Comment by wezell** [comment]
Here is the mapping getting put into the index: https://gist.github.com/wezell/1e980234c4981029cf3fcd4881856507

**Comment by wezell** [comment]
ahh, so it is in the index, just the contentletAPI.find("inode") returns null. Here is the raw results of my ES query - 1 hit but no content.
`{"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":1,"max_score":7.8770175,"hits":[]}}`

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16031
