### ISSUE TITLE
getRelatedContentAPIImpl fails when pulling

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16003]
I have a one to many relationship `Rating --> Movie` and the field is set on both sides.  I can edit `Movie`,  but when I try to edit `Rating` I get this in the on the screen and in the logs:

![screen shot 2019-02-10 at 7 31 47 pm](https://user-images.githubusercontent.com/934364/52542125-902a8600-2d6a-11e9-970a-81c2c8479c1d.png)

---
![screen shot 2019-02-10 at 7 29 38 pm](https://user-images.githubusercontent.com/934364/52542130-9456a380-2d6a-11e9-8212-c65e90ae52ae.png)

---
![screen shot 2019-02-10 at 7 29 48 pm](https://user-images.githubusercontent.com/934364/52542134-97519400-2d6a-11e9-88a8-db94b0bc8dcc.png)

---
### Where the error occurs

![screen shot 2019-02-10 at 7 34 11 pm](https://user-images.githubusercontent.com/934364/52542165-fdd6b200-2d6a-11e9-8555-ce22f7599c47.png)

```
com.dotmarketing.exception.DotDataException: Unable to look up related content
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.getRelatedContent_aroundBody60(ESContentletAPIImpl.java:1395)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure61.run(ESContentletAPIImpl.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43)
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29)
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.getRelatedContent(ESContentletAPIImpl.java:1380)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.pullRelated(ESContentletAPIImpl.java:1269)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.getAllRelationships_aroundBody50(ESContentletAPIImpl.java:1247)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure51.run(ESContentletAPIImpl.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43)
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29)
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.getAllRelationships(ESContentletAPIImpl.java:1226)
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.getAllRelationships(ContentletAPIInterceptor.java:979)
	at com.dotmarketing.portlets.contentlet.action.EditContentletAction._loadContentletRelationshipsInRequest(EditContentletAction.java:916)
	at com.dotmarketing.portlets.contentlet.action.EditContentletAction._retrieveWebAsset(EditContentletAction.java:841)
	at com.dotmarketing.portlets.contentlet.action.EditContentletAction.processAction(EditContentletAction.java:268)
	at com.liferay.portal.struts.PortletRequestProcessor.process(PortletRequestProcessor.java:125)
	at com.liferay.portlet.StrutsPortlet.processAction(StrutsPortlet.java:113)
	at com.liferay.portlet.CachePortlet.processAction(CachePortlet.java:130)
	at com.liferay.portal.action.LayoutAction._processPortletRequest(LayoutAction.java:230)
	at com.liferay.portal.action.LayoutAction._processActionRequest(LayoutAction.java:247)
	at com.liferay.portal.action.LayoutAction.execute(LayoutAction.java:89)
	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:421)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:226)
	at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:151)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1164)
	at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:397)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at com.liferay.portal.servlet.MainServlet.callParentService(MainServlet.java:272)
	at com.liferay.portal.servlet.MainServlet.service(MainServlet.java:481)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotcms.repackage.com.liferay.filters.secure.SecureFilter.doFilter(SecureFilter.java:135)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotmarketing.filters.CMSFilter.doFilterInternal(CMSFilter.java:199)
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:56)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:114)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:104)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:399)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:134)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:102)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to execute phase [query], all shards failed; shardFailures {[1N3KrlTdQzuNjF_I-hvxDg][working_20190207202151][0]: RemoteTransportException[[f3fcd446-2873-4090-bf84-580f82fb16ef][192.168.1.152:9301][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: IllegalArgumentException[No field found for [movie.rating-order] in mapping with types []]; }
	at com.dotcms.content.elasticsearch.business.ESContentFa
```

**Comment by nollymar** [comment]
Fixed here https://github.com/dotCMS/core/pull/16014

**Comment by bryanboza** [comment]
Unable to reproduce in the last master code
