### ISSUE TITLE
Canceling file upload causes file asset to show under System Host

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#16022]
Reported via support ticket: [97506](https://dotcms.zendesk.com/agent/tickets/97506)
Reproducible in dotCMS 5.0.3

If the upload file dialog is closed after choosing and uploading a file, and before clicking Save or Save/Publish, and then a new dotCMS session is started, a new attempt to upload the file causes the file to show under System Host.

## Expected Behavior
The file dialog can be closed after choosing and uploading a file, but before clicking Save. The expected behavior is that the file doesn't show under the folder since it wasn't saved and/or published. If a new session is started, the user should be able to upload the file and save/publish it to the folder since the previous upload was canceled. The file should show under the folder when the user saves it the second time. 

## Current Behavior
If the file dialog is closed after choosing and uploading a file, but before clicking Save, and a new dotCSM session is started, then trying to upload the file to the folder a second time fails, and also the file shows under System Hosts (instead of being located under the folder when the upload was made).

## Possible Solution
When a file is uploaded, a temporary identifier is created for it under System Host. If the file upload is canceled before clicking Save or Save/Publish, the identifier stays stored in the identifier table. If the user uploads the file again, dotCMS retrieves the temporary identifier from the session, instead of inserting the identifier again in the identifier table in the database. This is the code that retrieves the temporary file inode from a session attribute:

https://github.com/dotCMS/core/blob/057ed3aa504c6bc2eb705309462317152ed58647/dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/ajax/ContentletAjax.java#L2274-L2280

If a new dotCMS session is started, the temporary inode is not stored in the session attribute anymore, so the code tries to insert a new temporary identifier in the identifier table, using same file asset name under System Host, so the unique constraint in the table is broken, and an error raises.

To fix this issue, the code can be changed to add the scenario when the session is started again and the temporary identifier is in the identifier table. In that case, the identifier table can be queried before inserting the temporary identifier, to use the identifier that is already in the table instead of inserting a new one. 

## Known Workarounds
The temporary identifier can be removed manually from the database, so the file can be uploaded.

## Steps to Reproduce
1. Log into dotCMS 5.0.3
2. Go to a folder in the Site Browser
3. Right click on the folder and chose New Image or File, then choose File Asset to open the File Asset upload dialog.
4. Click Choose File button and chose a file from your local machine, wait until the file is uploaded and the Remove button shows for the file.
<img width="1225" alt="choose-file" src="https://user-images.githubusercontent.com/2894221/52650331-a857ed80-2eaf-11e9-8726-4dc53e6def45.png">

5. Close the File Asset upload dialog without Save the file.
<img width="1203" alt="cancel-file-upload" src="https://user-images.githubusercontent.com/2894221/52650345-b0179200-2eaf-11e9-95e8-23c952e5585d.png">

6. End the current user session and start a new session (you can use the same user or a different user).
7. Go to the folder from the step 2 and repeat step 3 to open the File Asset upload dialog again.
8. Choose the same file from step 4 from your local machine and click Save.
9. A error message is shown signaling that the file couldn't be uploaded.
<img width="1012" alt="file-asset-mandatory" src="https://user-images.githubusercontent.com/2894221/52650586-274d2600-2eb0-11e9-829d-bfa54fa7ac6d.png">

Also, the file is shown under Content Search portlet, but not under the folder that the file was being uploaded: it's shown under System Host (the temporary location):
<img width="1152" alt="file-under-system-host" src="https://user-images.githubusercontent.com/2894221/52650610-3207bb00-2eb0-11e9-957c-11297789c7cb.png">

The following error message is on the dotcms.log file:
```
[12/02/19 08:35:01:917 CST] ERROR business.IdentifierFactoryImpl: saveIdentifier failed:com.dotmarketing.exception.DotDataException: ERROR: duplicate key value violates unique constraint "identifier_parent_path_asset_name_host_inode_key"
  Detail: Key (parent_path, asset_name, host_inode)=(/, dotcms-logo-1.png, SYSTEM_HOST) already exists.{
  "SQL": ["INSERT INTO identifier (parent_path,asset_name,host_inode,asset_type,syspublish_date,sysexpire_date,id) values (?,?,?,?,?,?,?)"],
  "maxRows": [-1],
  "offest": [0],
  "params": [
    "/",
    "dotcms-logo-1.png",
    "SYSTEM_HOST",
    "contentlet",
    null,
    null,
    "cc18522c-affd-4ba5-8810-12337e71629e"
  ]
}
com.dotmarketing.exception.DotDataException: ERROR: duplicate key value violates unique constraint "identifier_parent_path_asset_name_host_inode_key"
  Detail: Key (parent_path, asset_name, host_inode)=(/, dotcms-logo-1.png, SYSTEM_HOST) already exists.{
  "SQL": ["INSERT INTO identifier (parent_path,asset_name,host_inode,asset_type,syspublish_date,sysexpire_date,id) values (?,?,?,?,?,?,?)"],
  "maxRows": [-1],
  "offest": [0],
  "params": [
    "/",
    "dotcms-logo-1.png",
    "SYSTEM_HOST",
    "contentlet",
    null,
    null,
    "cc18522c-affd-4ba5-8810-12337e71629e"
  ]
}
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:256) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.business.IdentifierFactoryImpl.saveIdentifier(IdentifierFactoryImpl.java:460) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.business.IdentifierFactoryImpl.createNewIdentifier(IdentifierFactoryImpl.java:384) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.business.IdentifierFactoryImpl.createNewIdentifier(IdentifierFactoryImpl.java:333) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.business.IdentifierAPIImpl.createNew_aroundBody18(IdentifierAPIImpl.java:157) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.business.IdentifierAPIImpl$AjcClosure19.run(IdentifierAPIImpl.java:1) ~[dotcms_5.0.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.business.IdentifierAPIImpl.createNew(IdentifierAPIImpl.java:145) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.business.IdentifierAPIImpl.createNew(IdentifierAPIImpl.java:141) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.internalCheckin(ESContentletAPIImpl.java:3221) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.lambda$17(ESContentletAPIImpl.java:2924) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.concurrent.lock.StripedLockImpl.tryLock(StripedLockImpl.java:79) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.concurrent.lock.StripedLockImpl.tryLock(StripedLockImpl.java:47) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.concurrent.lock.IdentifierStripedLock.tryLock(IdentifierStripedLock.java:19) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin_aroundBody120(ESContentletAPIImpl.java:2923) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure121.run(ESContentletAPIImpl.java:1) ~[dotcms_5.0.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2899) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:6381) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin_aroundBody112(ESContentletAPIImpl.java:2820) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure113.run(ESContentletAPIImpl.java:1) ~[dotcms_5.0.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2818) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkin(ContentletAPIInterceptor.java:256) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.portlets.contentlet.ajax.ContentletAjax.saveBinaryFileOnContent(ContentletAjax.java:2315) ~[dotcms_5.0.0_999999.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule$1.doFilter(CreatorModule.java:229) ~[dot.dwr-3rc2modified_3.jar:?]
	at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule.executeMethod(CreatorModule.java:241) ~[dot.dwr-3rc2modified_3.jar:?]
	at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:379) ~[dot.dwr-3rc2modified_3.jar:?]
	at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:332) ~[dot.dwr-3rc2modified_3.jar:?]
	at com.dotcms.repackage.org.directwebremoting.dwrp.BaseCallHandler.handle(BaseCallHandler.java:104) ~[dot.dwr-3rc2modified_3.jar:?]
	at com.dotcms.repackage.org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:120) ~[dot.dwr-3rc2modified_3.jar:?]
	at com.dotcms.repackage.org.directwebremoting.servlet.DwrServlet.doPost(DwrServlet.java:141) ~[dot.dwr-3rc2modified_3.jar:?]
	at com.dotmarketing.servlets.DwrWrapperServlet.doPost(DwrWrapperServlet.java:60) ~[dotcms_5.0.0_999999.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) ~[servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.CMSFilter.doFilterInternal(CMSFilter.java:199) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:56) ~[dotcms_5.0.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_5.0.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_5.0.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:114) ~[dotcms_5.0.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:104) ~[dotcms_5.0.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:399) ~[urlrewritefilter-4.0.4.jar:4.0.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:134) ~[dotcms_5.0.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:88) ~[dotcms_5.0.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:46) ~[dotcms_5.0.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:102) ~[dotcms_5.0.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_5.0.0_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[catalina.jar:8.5.32]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) ~[catalina.jar:8.5.32]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[catalina.jar:8.5.32]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[catalina.jar:8.5.32]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) ~[catalina.jar:8.5.32]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:8.5.32]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.32]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "identifier_parent_path_asset_name_host_inode_key"
  Detail: Key (parent_path, asset_name, host_inode)=(/, dotcms-logo-1.png, SYSTEM_HOST) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144) ~[postgresql-42.2.2.jar:42.2.2]
	at sun.reflect.GeneratedMethodAccessor223.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc.jar:?]
	at com.sun.proxy.$Proxy27.execute(Unknown Source) ~[?:?]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:612) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:524) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:254) ~[dotcms_5.0.0_999999.jar:?]
	... 105 more
```

## Context
This issue causes default that a file can't be uploaded to a dotCMS folder.
This was reported by client in this support issue: [97506](https://dotcms.zendesk.com/agent/tickets/97506)

## Your Environment
* dotCMS version used: 5.0.3
* Browser Name and version: Not relevant
* Operating System and version: Not relevant
* Application Server and version: Not relevant
* Java Brand and version: Not relevant
* Database and version: Not relevant
* Application module (if apply): File Asset upload

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16582

**Comment by nollymar** [comment]
Test results: The error is not displayed anymore and the file asset is saved correctly the second time. However, the index is messed up with the first identifier: 

```
10:15:56.298  WARN  reindex.ReindexQueueAPIImpl - Reindex failed for :IndexJournal [id=1086, identToIndex=f86f72a7-8a7f-4aa7-8695-225dd8638eda, priority=101, delete=false, serverId=null] because unable to find versions for content id:f86f72a7-8a7f-4aa7-8695-225dd8638eda
```

**Comment by erickgonzalez** [comment]
The reindex issue will be fixed in another ticket https://github.com/dotCMS/core/issues/16664 and a new file uploader will be implemented on the future

**Comment by dsilvam** [comment]
Passed Internal QA: File asset being able to be saved after canceling the first attempt. No errors in log.

**Comment by bryanboza** [comment]
Fixed tested on master // postgres // FF
