### ISSUE TITLE
[Push Publishing] Lookup of unique contents with double quotes and spaces throws an error

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#16257]
Reported via support ticket: [97801](https://dotcms.zendesk.com/agent/tickets/97801)
Reproducible in dotCMS 5.0.3, dotCMS 5.1.0

When looking up unique contents for being updated in push publishing, if the contents contains double quotes and spaces, it throws an error.

## Expected Behavior
Lookup of unique contents in push publishing should work for fields that contain spaces and double quotes, by escaping the quotes so the search doesn't throw an error.

## Current Behavior
Upon lookup of unique contents once they're pushed, any content with double quotes and spaces on its unique fields' values will fail, making the whole bundle to fail.

## Possible Solution
Escape properly the double quotes in all cases, even in the case that the field's value has spaces.

## Known Workarounds
None.

## Steps to Reproduce
1. Create a new content type (for example "History Timeline").
2. Add a "Title" text field. This one MUST be indexed, user searchable AND unique.
3. Create a content called with double quotes and spaces, for example: `"A+” student`
4. Push it to another environment.
5. The bundle fails to push publishing to the target environment.

Stacktrace: 
```
[19/03/19 18:55:04:251 CST] ERROR business.PublisherAPIImpl: Error publishing bundle with ID '9e891926-40a4-4eec-b016-afda11a0d698.tar.gz': Failed to execute phase [query], all shards failed; shardFailures {[KRZylFdTTceZBg4Uf_JzLw][working_20190305171013][0]: RemoteTransportException[[b294f18e-ab32-4952-9e4d-a5550d342ed1][192.168.1.144:9300][indices:data/read/search[phase/query]]]; nested: QueryShardException[Failed to parse query [+structurename:historytimeline +languageid:1 +(historytimeline.title:""a+” student" )]]; nested: ParseException[Cannot parse '+structurename:historytimeline +languageid:1 +(historytimeline.title:""a+” student" )': Lexical error at line 1, column 86.  Encountered: <EOF> after : "\" )"]; nested: TokenMgrError[Lexical error at line 1, column 86.  Encountered: <EOF> after : "\" )"]; }
com.dotcms.publishing.DotPublishingException: Failed to execute phase [query], all shards failed; shardFailures {[KRZylFdTTceZBg4Uf_JzLw][working_20190305171013][0]: RemoteTransportException[[b294f18e-ab32-4952-9e4d-a5550d342ed1][192.168.1.144:9300][indices:data/read/search[phase/query]]]; nested: QueryShardException[Failed to parse query [+structurename:historytimeline +languageid:1 +(historytimeline.title:""a+” student" )]]; nested: ParseException[Cannot parse '+structurename:historytimeline +languageid:1 +(historytimeline.title:""a+” student" )': Lexical error at line 1, column 86.  Encountered: <EOF> after : "\" )"]; nested: TokenMgrError[Lexical error at line 1, column 86.  Encountered: <EOF> after : "\" )"]; }
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handleContents(ContentHandler.java:384) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(ContentHandler.java:156) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(ContentHandler.java:131) ~[ee_clean.jar:?]
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:203) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.rest.PublishThread.run(PublishThread.java:42) ~[dotcms_5.0.0_999999.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.RuntimeException: Failed to execute phase [query], all shards failed; shardFailures {[KRZylFdTTceZBg4Uf_JzLw][working_20190305171013][0]: RemoteTransportException[[b294f18e-ab32-4952-9e4d-a5550d342ed1][192.168.1.144:9300][indices:data/read/search[phase/query]]]; nested: QueryShardException[Failed to parse query [+structurename:historytimeline +languageid:1 +(historytimeline.title:""a+” student" )]]; nested: ParseException[Cannot parse '+structurename:historytimeline +languageid:1 +(historytimeline.title:""a+” student" )': Lexical error at line 1, column 86.  Encountered: <EOF> after : "\" )"]; nested: TokenMgrError[Lexical error at line 1, column 86.  Encountered: <EOF> after : "\" )"]; }
	at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.indexSearch(ESContentFactoryImpl.java:1528) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.searchIndex(ESContentletAPIImpl.java:870) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.searchIndex(ContentletAPIInterceptor.java:1171) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.findUniqueContentMatch(ContentHandler.java:671) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.publish(ContentHandler.java:500) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handleContents(ContentHandler.java:235) ~[ee_clean.jar:?]
	... 5 more
Caused by: org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:274) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:132) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:243) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:107) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.search.InitialSearchPhase.access$100(InitialSearchPhase.java:49) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.search.InitialSearchPhase$2.lambda$onFailure$1(InitialSearchPhase.java:217) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:171) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.search.InitialSearchPhase.access$000(InitialSearchPhase.java:49) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.search.InitialSearchPhase$2.onFailure(InitialSearchPhase.java:217) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:531) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1056) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1149) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1133) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:66) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.search.SearchTransportService$6$1.onFailure(SearchTransportService.java:389) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService$2.onFailure(SearchService.java:318) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:312) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:306) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:996) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.3.jar:6.1.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	... 1 more
Caused by: org.elasticsearch.index.query.QueryShardException: Failed to parse query [+structurename:historytimeline +languageid:1 +(historytimeline.title:""a+” student" )]
	at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:1024) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:304) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:316) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:303) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:701) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:552) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:528) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:324) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:310) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:306) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:996) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.3.jar:6.1.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
	... 1 more
Caused by: org.apache.lucene.queryparser.classic.ParseException: Cannot parse '+structurename:historytimeline +languageid:1 +(historytimeline.title:""a+” student" )': Lexical error at line 1, column 86.  Encountered: <EOF> after : "\" )"
	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:114) ~[lucene-queryparser-7.1.0.jar:6.1.3]
	at org.elasticsearch.index.search.QueryStringQueryParser.parse(QueryStringQueryParser.java:777) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:1022) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:304) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:316) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:303) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:701) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:552) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:528) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:324) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:310) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:306) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:996) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.3.jar:6.1.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
	... 1 more
Caused by: org.apache.lucene.queryparser.classic.TokenMgrError: Lexical error at line 1, column 86.  Encountered: <EOF> after : "\" )"
	at org.apache.lucene.queryparser.classic.QueryParserTokenManager.getNextToken(QueryParserTokenManager.java:1119) ~[lucene-queryparser-7.1.0.jar:6.1.3]
	at org.apache.lucene.queryparser.classic.QueryParser.getToken(QueryParser.java:854) ~[lucene-queryparser-7.1.0.jar:6.1.3]
	at org.apache.lucene.queryparser.classic.QueryParser.jj_3R_3(QueryParser.java:668) ~[lucene-queryparser-7.1.0.jar:6.1.3]
	at org.apache.lucene.queryparser.classic.QueryParser.jj_3_2(QueryParser.java:697) ~[lucene-queryparser-7.1.0.jar:6.1.3]
	at org.apache.lucene.queryparser.classic.QueryParser.jj_2_2(QueryParser.java:653) ~[lucene-queryparser-7.1.0.jar:6.1.3]
	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:281) ~[lucene-queryparser-7.1.0.jar:6.1.3]
	at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:359) ~[lucene-queryparser-7.1.0.jar:6.1.3]
	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:303) ~[lucene-queryparser-7.1.0.jar:6.1.3]
	at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:215) ~[lucene-queryparser-7.1.0.jar:6.1.3]
	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:109) ~[lucene-queryparser-7.1.0.jar:6.1.3]
	at org.elasticsearch.index.search.QueryStringQueryParser.parse(QueryStringQueryParser.java:777) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:1022) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:304) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:316) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:303) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:701) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:552) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:528) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:324) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:310) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:306) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:996) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.3.jar:6.1.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
	... 1 more
[19/03/19 18:55:04:285 CST] ERROR lang.String: Error publishing bundle with ID '9e891926-40a4-4eec-b016-afda11a0d698.tar.gz': com.dotcms.publishing.DotPublishingException: Failed to execute phase [query], all shards failed; shardFailures {[KRZylFdTTceZBg4Uf_JzLw][working_20190305171013][0]: RemoteTransportException[[b294f18e-ab32-4952-9e4d-a5550d342ed1][192.168.1.144:9300][indices:data/read/search[phase/query]]]; nested: QueryShardException[Failed to parse query [+structurename:historytimeline +languageid:1 +(historytimeline.title:""a+” student" )]]; nested: ParseException[Cannot parse '+structurename:historytimeline +languageid:1 +(historytimeline.title:""a+” student" )': Lexical error at line 1, column 86.  Encountered: <EOF> after : "\" )"]; nested: TokenMgrError[Lexical error at line 1, column 86.  Encountered: <EOF> after : "\" )"]; }
```

As the stack trace shows above, the generated query that attempts to look for unique contents is 

`+structurename:historytimeline +languageid:1 +(historytimeline.title:""a+” student" )`

Which has spaces and un-escaped double quotes. Original content title is `"A+” Student` and belongs to a content type called "History Timeline".

## Context
Reported by customer: [97801](https://dotcms.zendesk.com/agent/tickets/97801)

## Your Environment
* dotCMS version used: 5.1.0
* Browser Name and version: Not relevant.
* Operating System and version: Not relevant.
* Application Server and version: Not relevant.
* Java Brand and version: Not relevant.
* Database and version: Not relevant.
* Application module (if apply): Push Publish

**Comment by dsolistorres** [comment]
PR: #16276

**Comment by wezell** [comment]
Thanks for the PR @dsolistorres !  


I was thinking about this issue and I think the right fix for it is when reindexing a contentlet of a structure that has a unique field add to the the index a SHA1(structureVar + unique field value + langaugeId) of the contentlet) to our content index.  Then, when checking if something is unique, we can just do a query against against the hashed values.  It would allow us to no have to do the list of non-acceptable values, etc and make the unique lookup very straight forward.

**Comment by wezell** [comment]
@dsolistorres this looks like great work.  I think we will need to apply the same lookup/validations here, when we check in content.  

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L4787-L4855

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the changes
