### ISSUE TITLE
Unable to restart index snapshots 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16304]
We are having problems when you create an index snapshot and then you try to restore it in the index tab

We have an IndexResource error and we are unable to restore
 
Here the error: 
```
11:56:26.347  ERROR index.ESIndexResource - Exception trying to restore index snapshot:com.dotmarketing.business.DotStateException: Index "live_20190327125431" is not closed and can not be restored
java.util.concurrent.CompletionException: com.dotmarketing.business.DotStateException: Index "live_20190327125431" is not closed and can not be restored
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592) ~[?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: com.dotmarketing.business.DotStateException: Index "live_20190327125431" is not closed and can not be restored
	at com.dotcms.content.elasticsearch.business.ESIndexAPI.restoreSnapshot(ESIndexAPI.java:961) ~[dotcms_5.0.0_8415ccc.jar:?]
	at com.dotcms.content.elasticsearch.business.ESIndexAPI.uploadSnapshot(ESIndexAPI.java:1083) ~[dotcms_5.0.0_8415ccc.jar:?]
	at com.dotcms.content.elasticsearch.business.ESIndexAPI.uploadSnapshot(ESIndexAPI.java:1045) ~[dotcms_5.0.0_8415ccc.jar:?]
	at com.dotcms.content.elasticsearch.business.ESIndexAPI.uploadSnapshot(ESIndexAPI.java:1004) ~[dotcms_5.0.0_8415ccc.jar:?]
	at com.dotcms.rest.api.v1.index.ESIndexResource.lambda$1(ESIndexResource.java:350) ~[dotcms_5.0.0_8415ccc.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_191]
	... 3 more
```

Tested on with the reindex improvements // Postgres

**Comment by nollymar** [comment]
Fixed on #16277

**Comment by erickgonzalez** [comment]
Tested and working as it should, now we can restore indices without issues.

**Comment by bryanboza** [comment]
Able to reproduce the same problem on Oracle... 
To recreate: 
- Login as admin 
- Make sure you have a EE license 
- Go to System --> Maintenance --> Index
- Right click to any of the index and download index snapshot 
- Try to upload the snapshot

**Comment by nollymar** [comment]
It is not an issue. The problem there is that you are trying to restore an index that has not been closed. So, the right steps would be:
1. Right click on the index --> Close Index
2. Upload snapshot 

Maybe, these details can be documented here https://dotcms.com/docs/latest/managing-site-indexes-with-elasticsearch
