### ISSUE TITLE
[Upgrade Task] Task05040LanguageTableIdentityOff throws error on MSSQL

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#16384]
Reported via Support: Ticket [97656](https://dotcms.zendesk.com/agent/tickets/97656)
Reproducible in dotCMS 5.1.1

The upgrade task Task05040LanguageTableIdentityOff throws an exception when running upgrade to 5.1.1 version on MS SQL Server.

### Steps to reproduce the behavior:
1. Setup a dotCMS instance running on 4.3.3 version and MS SQL Server database.
2. Install 5.1.1 version and point to the database that was running on 4.3.3
3. Start dotCSM so it runs the upgrade tasks,
4. The upgrade task Task05040LanguageTableIdentityOff throws this fatal error:
```
[12/04/19 11:19:34:942 CST] FATAL startup.StartupTasksExecutor: Unable to execute the upgrade task : Task05040LanguageTableIdentityOff
com.dotmarketing.exception.DotDataException: Transaction failed because this DDL statement is not allowed inside a snapshot isolation transaction. Since metadata is not versioned, a metadata change can lead to inconsistency if mixed within snapshot isolation.{
  "SQL": [" ALTER TABLE language ADD non_idenity_id numeric(19,0); "],
  "maxRows": [-1],
  "offest": [0]
}
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:256) ~[dotcms_5.1.1_f29c13b.jar:?]
	at com.dotmarketing.startup.runonce.Task05040LanguageTableIdentityOff.executeUpgrade_aroundBody0(Task05040LanguageTableIdentityOff.java:107) ~[dotcms_5.1.1_f29c13b.jar:?]
	at com.dotmarketing.startup.runonce.Task05040LanguageTableIdentityOff$AjcClosure1.run(Task05040LanguageTableIdentityOff.java:1) ~[dotcms_5.1.1_f29c13b.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.1.1_f29c13b.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.1.1_f29c13b.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.1.1_f29c13b.jar:?]
	at com.dotmarketing.startup.runonce.Task05040LanguageTableIdentityOff.executeUpgrade(Task05040LanguageTableIdentityOff.java:93) ~[dotcms_5.1.1_f29c13b.jar:?]
	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:271) ~[dotcms_5.1.1_f29c13b.jar:?]
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:115) ~[dotcms_5.1.1_f29c13b.jar:?]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4978) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5290) ~[catalina.jar:8.5.32]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734) ~[catalina.jar:8.5.32]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1140) ~[catalina.jar:8.5.32]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875) ~[catalina.jar:8.5.32]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Transaction failed because this DDL statement is not allowed inside a snapshot isolation transaction. Since metadata is not versioned, a metadata change can lead to inconsistency if mixed within snapshot isolation.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:258) ~[mssql-jdbc-6.2.2.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1535) ~[mssql-jdbc-6.2.2.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:845) ~[mssql-jdbc-6.2.2.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:752) ~[mssql-jdbc-6.2.2.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7151) ~[mssql-jdbc-6.2.2.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2478) ~[mssql-jdbc-6.2.2.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:219) ~[mssql-jdbc-6.2.2.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:199) ~[mssql-jdbc-6.2.2.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:729) ~[mssql-jdbc-6.2.2.jre8.jar:?]
	at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc.jar:?]
	at com.sun.proxy.$Proxy77.execute(Unknown Source) ~[?:?]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:635) ~[dotcms_5.1.1_f29c13b.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:524) ~[dotcms_5.1.1_f29c13b.jar:?]
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:254) ~[dotcms_5.1.1_f29c13b.jar:?]
	... 25 more
```

### Additional context
This has been reported by customer via Support: Ticket [97656](https://dotcms.zendesk.com/agent/tickets/97656)
The issue is causing problems for a client upgrading to dotCMS 5.1.1

**Comment by oarrietadotcms** [comment]
Fixed here: https://github.com/dotCMS/core/issues/16519
