### ISSUE TITLE
AjaxServlet loadJsonAsParams errors on mulitpart uploads

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16388]
For example, when you try to upload an osgi portlet.

```
dotcms_1  | java.nio.charset.MalformedInputException: Input length = 1
dotcms_1  | 	at java.nio.charset.CoderResult.throwException(CoderResult.java:281) ~[?:1.8.0_201]
dotcms_1  | 	at org.apache.tomcat.util.buf.B2CConverter.convert(B2CConverter.java:275) ~[tomcat-util.jar:8.5.32]
dotcms_1  | 	at org.apache.catalina.connector.InputBuffer.realReadChars(InputBuffer.java:426) ~[catalina.jar:8.5.32]
dotcms_1  | 	at org.apache.catalina.connector.InputBuffer.checkCharBufferEof(InputBuffer.java:652) ~[catalina.jar:8.5.32]
dotcms_1  | 	at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:468) ~[catalina.jar:8.5.32]
dotcms_1  | 	at org.apache.catalina.connector.CoyoteReader.read(CoyoteReader.java:108) ~[catalina.jar:8.5.32]
dotcms_1  | 	at java.io.Reader.read(Reader.java:100) ~[?:1.8.0_201]
dotcms_1  | 	at com.google.common.io.CharStreams.copy(CharStreams.java:74) ~[guava-20.0.jar:?]
dotcms_1  | 	at com.google.common.io.CharStreams.toStringBuilder(CharStreams.java:105) ~[guava-20.0.jar:?]
dotcms_1  | 	at com.google.common.io.CharStreams.toString(CharStreams.java:92) ~[guava-20.0.jar:?]
dotcms_1  | 	at com.dotmarketing.servlets.ajax.AjaxDirectorServlet.loadJsonAsParams(AjaxDirectorServlet.java:95) ~[dotcms_5.0.0_61e3db7.jar:?]
dotcms_1  | 	at com.dotmarketing.servlets.ajax.AjaxDirectorServlet.service(AjaxDirectorServlet.java:56) ~[dotcms_5.0.0_61e3db7.jar:?]
```

**Comment by dsilvam** [comment]
Passed Internal QA: Able to upload OSGI plugin and effectively becoming active.

**Comment by bryanboza** [comment]
Fixed, testing uploading the portlet plugin and works as expected
