### ISSUE TITLE
zero length file prevents webdav listing.

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16400]
If you have a file asset that has a zero length file associated with it, you cannot get a webdav listing.  Server throws this error:

1. To test - upload a file to the `/` directory of demo.
2. find the file under the assets directory by its inode, delete it from file system
3. connect via webdav and see if you can browse the server

```
dotcms_1  | 12:20:44.478  INFO  http.HttpManager - PROPFIND :: https://ubisoft.dotcms.io/webdav/live/1/demo.dotcms.com/ - https://ubisoft.dotcms.io/webdav/live/1/demo.dotcms.com/
dotcms_1  | 12:20:44.541  ERROR http.StandardFilter - process
dotcms_1  | java.lang.NullPointerException: null
dotcms_1  | 	at com.dotmarketing.webdav.FileResourceImpl.getContentLength(FileResourceImpl.java:122) ~[dotcms_5.0.0_20ea308.jar:?]
dotcms_1  | 	at com.dotcms.repackage.com.bradmcevoy.http.webdav.WebDavProtocol$ContentLengthPropertyWriter.getValue(WebDavProtocol.java:369) ~[dot.milton-api-1.8.1.4_3.jar:?]
dotcms_1  | 	at com.dotcms.repackage.com.bradmcevoy.http.webdav.WebDavProtocol$ContentLengthPropertyWriter.getValue(WebDavProtocol.java:363) ~[dot.milton-api-1.8.1.4_3.jar:?]
dotcms_1  | 	at com.dotcms.repackage.com.bradmcevoy.http.webdav.PropertyMap.getProperty(PropertyMap.java:68) ~[dot.milton-api-1.8.1.4_3.jar:?]
dotcms_1  | 	at com.dotcms.repackage.com.bradmcevoy.http.webdav.WebDavProtocol.getProperty(WebDavProtocol.java:232) ~[dot.milton-api-1.8.1.4_3.jar:?]
dotcms_1  | 	at com.dotcms.repackage.com.bradmcevoy.http.webdav.PropFindPropertyBuilder.processResource(PropFindPropertyBuilder.java:140) ~[dot.milton-api-1.8.1.4_3.jar:?]
dotcms_1  | 	at com.dotcms.repackage.com.bradmcevoy.http.webdav.PropFindPropertyBuilder.processResource(PropFindPropertyBuilder.java:190) ~[dot.milton-api-1.8.1.4_3.jar:?]
dotcms_1  | 	at com.dotcms.repackage.com.bradmcevoy.http.webdav.PropFindPropertyBuilder.appendResponses(PropFindPropertyBuilder.java:107) ~[dot.milton-api-1.8.1.4_3.jar:?]
dotcms_1  | 	at com.dotcms.repackage.com.bradmcevoy.http.webdav.PropFindPropertyBuilder.buildProperties(PropFindPropertyBuilder.java:86) ~[dot.milton-api-1.8.1.4_3.jar:?]
dotcms_1  | 	at com.dotcms.repackage.com.bradmcevoy.http.webdav.PropFindHandler.processExistingResource(PropFindHandler.java:132) ~[dot.milton-api-1.8.1.4_3.jar:?]
dotcms_1  | 	at com.dotcms.repackage.com.bradmcevoy.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:149) ~[dot.milton-api-1.8.1.4_3.jar:?]
dotcms_1  | 	at com.dotcms.repackage.com.bradmcevoy.http.webdav.PropFindHandler.processResource(PropFindHandler.java:103) ~[dot.milton-api-1.8.1.4_3.jar:?]
dotcms_1  | 	at com.dotcms.repackage.com.bradmcevoy.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:91) ~[dot.milton-api-1.8.1.4_3.jar:?]
dotcms_1  | 	at com.dotcms.repackage.com.bradmcevoy.http.webdav.PropFindHandler.process(PropFindHandler.java:97) ~[dot.milton-api-1.8.1.4_3.jar:?]
dotcms_1  | 	at com.dotcms.repackage.com.bradmcevoy.http.StandardFilter.process(StandardFilter.java:52) ~[dot.milton-api-1.8.1.4_3.jar:?]
dotcms_1  | 	at com.dotcms.repackage.com.bradmcevoy.http.FilterChain.process(FilterChain.java:40) ~[dot.milton-api-1.8.1.4_3.jar:?]
dotcms_1  | 	at com.dotcms.repackage.com.bradmcevoy.http.HttpManager.process(HttpManager.java:228) ~[dot.milton-api-1.8.1.4_3.jar:?]
dotcms_1  | 	at com.dotcms.repackage.com.bradmcevoy.http.MiltonServlet.service(MiltonServlet.java:195) ~[dot.milton-servlet-1.8.1.4_3.jar:?]
dotcms_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.32]
dotcms_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
```

**Comment by wezell** [comment]
PR: #16401

**Comment by bryanboza** [comment]
fixed, tested on master // postgres // FF
