### ISSUE TITLE
Fix portlets plugins

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#16448]
Related to: https://github.com/dotcms/core/issues/16161

### Describe the bug
With the changes of custom portlets, the portlets plugins are broken, we need to fix them to work with the new custom portlets code.

### Steps to reproduce the behavior:
Deploy any of our portlets plugins (OSGi or static).

ST for OSGi Plugin: https://gist.github.com/erickgonzalez/e28c8c6db13247acdf20b86ca60d1343

**Comment by nollymar** [comment]
Tests results: I was able to deploy static and dynamic portlets plugins successfully. I only got this error in the log after uploading the com.dotcms.portlet.fragment-0.2.jar:  

```
ERROR: Bundle org.apache.felix.framework [0] EventDispatcher: Error during dispatch. (java.lang.IllegalStateException: Invalid BundleContext.)
java.lang.IllegalStateException: Invalid BundleContext.
    at org.apache.felix.framework.BundleContextImpl.checkValidity(BundleContextImpl.java:511)
    at org.apache.felix.framework.BundleContextImpl.getService(BundleContextImpl.java:451)
    at org.osgi.util.tracker.ServiceTracker.addingService(ServiceTracker.java:414)
    at org.apache.felix.http.proxy.DispatcherTracker.addingService(DispatcherTracker.java:55)
    at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
    at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
    at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
    at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
    at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
    at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
    at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
    at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
    at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4595)
    at org.apache.felix.framework.Felix.registerService(Felix.java:3587)
    at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
    at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:322)
    at org.apache.felix.http.bridge.internal.BridgeActivator.doStart(BridgeActivator.java:50)
    at org.apache.felix.http.base.internal.AbstractActivator.start(AbstractActivator.java:41)
    at org.apache.felix.http.bundle.internal.CombinedActivator.start(CombinedActivator.java:60)
    at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
    at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
    at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
    at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
    at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
    at java.lang.Thread.run(Thread.java:748)
[INFO] Started bridged http service
```

However, it didn't prevent me from adding/removing the portlets from my plugins

**Comment by bryanboza** [comment]
Fixed, now we are able to upload this plugin without problems and works as expected

**Comment by bryanboza** [comment]
After the last changes, when you upload this plugin and then you add this to any tool group, we are able to open the portlet without problems and also use it. But when you try to stop or undeploy the plugin and you have been added one of these portlets, we are unable to undeploy. 
ST: https://gist.github.com/bryanboza/c55a6cb402be25ba80f4edb396d057a4

**Comment by erickgonzalez** [comment]
PR for undeploy plugins: https://github.com/dotCMS/core/pull/16532

**Comment by bryanboza** [comment]
Fixed, tested on master and now we are unable to reproduce the problem.

**Comment by nollymar** [comment]
Tested undeploying/stopping plugins after the fix and it's working correctly

**Comment by bryanboza** [comment]
Fixed, now we are able to stop and un-deploy without problems
