### ISSUE TITLE
unable to fix folder conflicts

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16471]
### Describe the bug
If you load a new starter site and a legacy site/data and then try to run fix conflicts between them, the fix conflicts fail.

### Steps to reproduce the behavior:
1. load a new dotCMS site in postgres
2. load another dotCMS instance with the legacy data
3. set up Push Publishing between them
4. Run integrity checker
5. Try to fix the conflicts local or remote - it throws an error in the logs

### Logs
```
15:00:01.333  INFO  db.DotConnect - Executing insert into inode (inode, owner, idate, type) values ('TEMP_INODE', 'DUMMY_OWNER', '1900-01-01 00:00:00.00', 'DUMMY_TYPE') 
15:00:01.395  INFO  db.DotConnect - Executing insert into identifier (id, parent_path, asset_name, host_inode, asset_type, syspublish_date, sysexpire_date) values ('TEMP_IDENTIFIER', '/System folder', 'DUMMY_ASSET_NAME', 'SYSTEM_HOST', 'folder', NULL, NULL) 
15:00:08.585  ERROR rest.IntegrityResource - Error fixing folders conflicts for End Point server: [90ec0187-6095-40e0-ad12-b3cf1fa11022]
com.dotmarketing.exception.DotDataException: ERROR: duplicate key value violates unique constraint "idx_ident_uniq_asset_name"
  Detail: Key (full_path_lc(identifier.*), host_inode)=(/, SYSTEM_HOST) already exists.
	at com.dotcms.integritycheckers.FolderIntegrityChecker.executeFix(FolderIntegrityChecker.java:259) ~[classes/:?]
	at com.dotcms.integritycheckers.IntegrityUtil.fixConflicts(IntegrityUtil.java:577) ~[classes/:?]
	at com.dotcms.rest.IntegrityResource.fixConflicts(IntegrityResource.java:1108) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
```

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16477

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF, now we are able to fix without problems
