### ISSUE TITLE
Smaller message when using osgi without ByteBuddy

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16524]
I run osgi plugins locally without bytebuddy, mainly without issues, but I do get an error in my console everytime a plugin is loaded.  This should be a 1 line warn imho.

```
	... 8 more
15:15:24.056  ERROR osgi.Activator - Error reading ClassReloadingStrategy from bytebuddy [java agent not set?]
java.lang.IllegalStateException: The Byte Buddy agent is not installed or not accessible
	at net.bytebuddy.dynamic.loading.ClassReloadingStrategy.fromInstalledAgent(ClassReloadingStrategy.java:148) ~[byte-buddy-1.6.12.jar:?]
	at com.dotmarketing.osgi.GenericBundleActivator.initializeServices(GenericBundleActivator.java:133) ~[classes/:?]
	at com.dotcms.osgi.Activator.start(Activator.java:43) ~[?:?]
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697) ~[org.apache.felix.framework-5.6.10.jar:?]
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240) ~[org.apache.felix.framework-5.6.10.jar:?]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146) ~[org.apache.felix.framework-5.6.10.jar:?]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998) ~[org.apache.felix.framework-5.6.10.jar:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.bytebuddy.agent.Installer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_202]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_202]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_202]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202]
	at net.bytebuddy.dynamic.loading.ClassReloadingStrategy.fromInstalledAgent(ClassReloadingStrategy.java:142) ~[byte-buddy-1.6.12.jar:?]
	... 12 more
```

**Comment by wezell** [comment]
PR: #16529
