### ISSUE TITLE
PortletFactory needs db handling

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16526]
Our `PortletFactory` leaks db connections when it is called from `com.liferay.portal.ejb.PortletManagerUtil`.  We need to ensure that transactions and db calls are close and are cleaned up.

```
May 06, 2019 3:47:34 PM org.apache.tomcat.jdbc.pool.ConnectionPool abandon
WARNING: Connection has been abandoned PooledConnection[org.postgresql.jdbc.PgConnection@919acb]:java.lang.Exception
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getThreadDump(ConnectionPool.java:1104)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:808)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:652)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:198)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:132)
	at com.dotmarketing.db.DbConnectionFactory.getConnection(DbConnectionFactory.java:167)
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:520)
	at com.dotmarketing.common.db.DotConnect.getResult(DotConnect.java:275)
	at com.dotmarketing.common.db.DotConnect.getInt(DotConnect.java:83)
	at com.dotmarketing.business.portal.PortletFactoryImpl.doesPortletExistInDb(PortletFactoryImpl.java:291)
	at com.dotmarketing.business.portal.PortletFactoryImpl.insertPortlet(PortletFactoryImpl.java:250)
	at com.liferay.portal.ejb.PortletManagerUtil.addPortlets(PortletManagerUtil.java:47)
	at com.dotmarketing.osgi.GenericBundleActivator.registerPortlets(GenericBundleActivator.java:389)
```

**Comment by wezell** [comment]
PR: #16527
