### ISSUE TITLE
clearIndex not working when Replicas is > 0

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#16533]
### Describe the bug
Only in < 5.x versions of dotCMS. In 5.x is already fixed.

### Steps to reproduce the behavior:
1. Create an AUTO_WIRE cluster of 2 nodes.
2. Run a full reindex.
3. Try to clear one of the old index.
4. See error in dotcms.log

```
[02/05/19 13:49:58:661 EDT] ERROR job.SiteSearchJobProxy: Error on updateReplica. Replicas are configured to be handled by dotCMS. 
com.dotmarketing.exception.DotDataException: Error on updateReplica. Replicas are configured to be handled by dotCMS. 
at com.dotcms.content.elasticsearch.business.ESIndexAPI.updateReplicas(ESIndexAPI.java:700) ~[dotcms_4.3.3_999999.jar:?] 
at com.dotcms.content.elasticsearch.business.ESIndexAPI.clearIndex(ESIndexAPI.java:478) ~[dotcms_4.3.3_999999.jar:?] 
```

### Expected behavior
Clearing the index.

### Code
As this is a 2-node cluster, the replicas will be = 1. So this if will try to update the number of replicas: https://github.com/dotCMS/core/blob/4.3.3/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESIndexAPI.java#L478. But then, as this is an AUTO WIRE cluster, it will fail here: https://github.com/dotCMS/core/blob/4.3.3/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESIndexAPI.java#L700

**Comment by oarrietadotcms** [comment]
Already fixed in here: https://github.com/dotCMS/core/commit/48c3b6468b46db1cd5b58968f914b0cdae41e084#diff-b0f605e60a6511003978bca7a3050fa8

I am creating this issue to have a future reference and a link to the hotfix.
