### ISSUE TITLE
The SwitchSiteListener is very noisy when you hit `/admin`

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16559]
The SwitchSiteListener is very noisy when logging in. There are multiple NPEs when trying to check permission and there is no user. We should validate if there is a user before calling the logic:

#### To Reproduce:
- be logged out and go to http://localhost:8080
- delete all your cookies
- go to http://localhost:8080/admin

```
14:23:07.426  ERROR business.HostAPIImpl - User null does not have permission to host:demo.dotcms.com
May 08, 2019 2:23:07 PM org.apache.catalina.session.StandardSession setAttribute
SEVERE: Session attribute event listener threw exception
com.dotmarketing.exception.DotRuntimeException: User null does not have permission to host:demo.dotcms.com
	at com.dotcms.listeners.SwitchSiteListener.triggerSwitchSiteEvent(SwitchSiteListener.java:71)
	at com.dotcms.listeners.SwitchSiteListener.attributeAdded(SwitchSiteListener.java:31)
	at org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1522)
	at org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1415)
	at org.apache.catalina.session.StandardSessionFacade.setAttribute(StandardSessionFacade.java:137)
	at com.dotmarketing.servlets.LoginEditModeServlet.service(LoginEditModeServlet.java:89)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

```

**Comment by wezell** [comment]
Dupe #16543
