### ISSUE TITLE
Containers a a files error pushing site

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#16553]
We are getting errors related to the Containers as Files in the receiver server when pushing sites:

```
17:26:14.787  ERROR business.PublisherAPIImpl - Error publishing bundle with ID '2a10e98c-1195-4bfd-acc6-202c729e2fc9.tar.gz': Unable to save Object with primary key d89f7f2e-c1d7-4d0e-bb18-d642fc5b9dc0 to Hibernate Session 
com.dotcms.publishing.DotPublishingException: Unable to save Object with primary key d89f7f2e-c1d7-4d0e-bb18-d642fc5b9dc0 to Hibernate Session 
	at com.dotcms.enterprise.publishing.remote.handler.ContainerHandler.a(SourceFile:175) ~[ee-5.0.0-SNAPSHOT.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContainerHandler.handle(SourceFile:83) ~[ee-5.0.0-SNAPSHOT.jar:?]
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:203) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at com.dotcms.rest.PublishThread.run(PublishThread.java:42) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: com.dotmarketing.exception.DotHibernateException: Unable to save Object with primary key d89f7f2e-c1d7-4d0e-bb18-d642fc5b9dc0 to Hibernate Session 
	at com.dotmarketing.db.HibernateUtil.saveWithPrimaryKey(HibernateUtil.java:1245) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at com.dotmarketing.portlets.containers.business.ContainerFactoryImpl.save(ContainerFactoryImpl.java:57) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at com.dotmarketing.portlets.containers.business.ContainerAPIImpl.save(ContainerAPIImpl.java:146) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at com.dotmarketing.portlets.containers.business.ContainerAPIImpl.save_aroundBody36(ContainerAPIImpl.java:622) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at com.dotmarketing.portlets.containers.business.ContainerAPIImpl$AjcClosure37.run(ContainerAPIImpl.java:1) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at com.dotmarketing.portlets.containers.business.ContainerAPIImpl.save(ContainerAPIImpl.java:561) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContainerHandler.a(SourceFile:125) ~[ee-5.0.0-SNAPSHOT.jar:?]
	... 4 more
Caused by: com.dotcms.repackage.net.sf.hibernate.MappingException: Unknown entity class: com.dotmarketing.portlets.containers.model.FileAssetContainer
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionFactoryImpl.getPersister(SessionFactoryImpl.java:347) ~[dot.hibernate-2.1.7_3.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.getClassPersister(SessionImpl.java:2718) ~[dot.hibernate-2.1.7_3.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.getPersister(SessionImpl.java:2725) ~[dot.hibernate-2.1.7_3.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.save(SessionImpl.java:822) ~[dot.hibernate-2.1.7_3.jar:?]
	at com.dotmarketing.db.HibernateUtil.saveWithPrimaryKey(HibernateUtil.java:1243) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at com.dotmarketing.portlets.containers.business.ContainerFactoryImpl.save(ContainerFactoryImpl.java:57) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at com.dotmarketing.portlets.containers.business.ContainerAPIImpl.save(ContainerAPIImpl.java:146) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at com.dotmarketing.portlets.containers.business.ContainerAPIImpl.save_aroundBody36(ContainerAPIImpl.java:622) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at com.dotmarketing.portlets.containers.business.ContainerAPIImpl$AjcClosure37.run(ContainerAPIImpl.java:1) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at com.dotmarketing.portlets.containers.business.ContainerAPIImpl.save(ContainerAPIImpl.java:561) ~[dotcms_5.0.0_d44f3f9.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContainerHandler.a(SourceFile:125) ~[ee-5.0.0-SNAPSHOT.jar:?]
	... 4 more
17:26:14.791  ERROR lang.String - Error publishing bundle with ID '2a10e98c-1195-4bfd-acc6-202c729e2fc9.tar.gz': com.dotcms.publishing.DotPublishingException: Unable to save Object with primary key d89f7f2e-c1d7-4d0e-bb18-d642fc5b9dc0 to Hibernate Session 
```

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16554

**Comment by bryanboza** [comment]
Fixed, tested on master and works as expected
