### ISSUE TITLE
[core] : Cutting/pasting folder fails when having related content

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#16607]
Reported via Support: https://dotcms.zendesk.com/agent/tickets/98263
Reproducible in dotCMS 4.3.3

**NOTE: This bug is NOT reproducible after dotCMS 5.1.5. This ticket has been created for tracking purposes and for creating the respective Hotfix Plugins. That's why it's closed.**

Contentlets can be created under a Folder. Such Contentlets can be associated to other Contentlets as well. When cutting/pasting that parent Folder to another location, the operation is failing during the content validation process. The following Java stack trace is printed in the `dotcms.log` file, which provides unuseful information:
```
[21/05/19 11:13:27:932 CST] ERROR business.ESContentletAPIImpl: Contentlet's fields are not valid
com.dotmarketing.portlets.contentlet.business.DotContentletValidationException: Contentlet's fields are not valid
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.validateContentlet_aroundBody118(ESContentletAPIImpl.java:4515) ~[dotcms_4.3.3_d383d2a.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure119.run(ESContentletAPIImpl.java:1) ~[dotcms_4.3.3_d383d2a.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.3.3_d383d2a.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_4.3.3_d383d2a.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_4.3.3_d383d2a.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.validateContentlet(ESContentletAPIImpl.java:4509) ~[dotcms_4.3.3_d383d2a.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin_aroundBody98(ESContentletAPIImpl.java:2946) ~[dotcms_4.3.3_d383d2a.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure99.run(ESContentletAPIImpl.java:1) ~[dotcms_4.3.3_d383d2a.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.3.3_d383d2a.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:39) ~[dotcms_4.3.3_d383d2a.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_4.3.3_d383d2a.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_4.3.3_d383d2a.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2852) ~[dotcms_4.3.3_d383d2a.jar:?]
...
...
...
```

### Steps to reproduce the behavior:
1. Go to the Site Browser, and create the following sample folder structure: `/associates/myhuman-resource-center/associate-handbook-accordion/introduction`
2. Create a blank HTML Page called "index" directly under `/associate-handbook-accordion/`
3. Go to the `Employee` Content Type (parent) and create a relationship with `Content (Generic)` (child), M-M.
4. Create a new `Content (Generic)` Contentlet with `/associates/myhuman-resource-center/associate-handbook-accordion/` **as its parent** (Site or Folder). Associate it with any existing `Employee` Contentlet, and save it.
5. Back to the Site Browser, create the following sample folder structure: `/rd-system-services/associate-services/myhuman-resource-center/associate-handbook/`
6. Cut the `/associates/myhuman-resource-center/associate-handbook-accordion/` Folder, and paste it under `/rd-system-services/associate-services/myhuman-resource-center/associate-handbook/`
7. The operation fails, and the error is displayed in the log.

### Expected behavior
Cutting/pasting a Folder like the one previously described must work.

### Additional context
The previously described scenario **DOES WORK** in latest dotCMS 5.1.5. In older versions, the source code is calling the incorrect method when pasting the Folder and its data. Version 5.1.5 calls the right one.

**Comment by jcastro-dotcms** [comment]
Closing ticket give that it's only meant for hotfix operations.
