### ISSUE TITLE
S3 publishing fails in dockerized dotCMS

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16612]
When dotCMS is started in docker, we try to merge the default `dotmarketing-config.properties` with those coming in from plugins and the dockerize template 

The merge happens here:
https://github.com/dotCMS/docker/blob/master/images/dotcms/ROOT/etc/cont-init.d/10-merge-docker-config.sh#L42

A side effect of this merge is that we seem to be munging regex values used in `dotmarketing-config.properties`.   One of these values `STATIC_PUSH_BUCKET_NAME_REGEX` is used to  to validate s3 bucket names.  In the distro, the config value for `STATIC_PUSH_BUCKET_NAME_REGEX` is  
`[,!:;&?$\\\\*\\/\\[\\]=\\|#_@\\(\\)<>\\s\\+"]+`

and in docker, the has been changed into (basically unescaped):
`[,!:;&?$\\*\/\[\]=\|#_@\(\)<>\s\+"]+`

This causes an error when trying to push to S3 
```
13:26:43.787  INFO  publishing.PublisherAPIImpl - Start of Bundler: c
13:26:43.831  INFO  publishing.PublisherAPIImpl - End of Bundler: c
13:26:43.831  INFO  publishing.PublisherAPIImpl - Start of Bundler: FileAssetBundler
13:26:43.832  INFO  bundlers.FileAssetBundler - +structuretype:4 +(path:/quest-logo.svg ) +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797  )
13:26:43.870  ERROR staticpublishing.AWSS3Publisher - Unclosed character class near index 26
[,!:;&?$\*/[]=|#_@()<>s+"]+
                          ^
java.util.regex.PatternSyntaxException: Unclosed character class near index 26
[,!:;&?$\*/[]=|#_@()<>s+"]+
                          ^
    at java.util.regex.Pattern.error(Pattern.java:1957) ~[?:1.8.0_212]
    at java.util.regex.Pattern.clazz(Pattern.java:2550) ~[?:1.8.0_212]
    at java.util.regex.Pattern.sequence(Pattern.java:2065) ~[?:1.8.0_212]
    at java.util.regex.Pattern.expr(Pattern.java:1998) ~[?:1.8.0_212]
    at java.util.regex.Pattern.compile(Pattern.java:1698) ~[?:1.8.0_212]
    at java.util.regex.Pattern.<init>(Pattern.java:1351) ~[?:1.8.0_212]
    at java.util.regex.Pattern.compile(Pattern.java:1028) ~[?:1.8.0_212]
    at java.lang.String.replaceAll(String.java:2223) ~[?:1.8.0_212]
    at com.dotcms.enterprise.publishing.staticpublishing.AWSS3Publisher.a(SourceFile:453) ~[ee-5.1.5.jar:?]
    at com.dotcms.enterprise.publishing.staticpublishing.AWSS3Publisher.a(SourceFile
```

**Comment by wezell** [comment]
PR: #16615

**Comment by wezell** [comment]
Note to QA - you will have to build a docker image from the release branch to test this.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes... Tested with a docker image with the release branch

**Comment by bryanboza** [comment]
Pending to test in master...

**Comment by bryanboza** [comment]
Unable to test on master. 

- We are having problems OSGI starting the last master on docker 
ST: https://gist.github.com/bryanboza/a2497825949ed7f3c320fd42fd8cabb9

**Comment by bryanboza** [comment]
Fixed, tested with the last master running on docker
