### ISSUE TITLE
Error pushing sites 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16623]
Related to #16481 

### Describe the bug
After the changes in the related card, we are unable to push an entire site 

### Steps to reproduce the behavior:
1. Login as admin 
2. Configure your push environment 
3. Create a copy of demo site 
4. Try to push 

We have this error on the receiver log file https://gist.github.com/bryanboza/f76b9a43721ee11a4043e10645271cc9

### Expected behavior
We need to be able to push entire sites without problems 

### Desktop (please complete the following information):
Tested on master // Posgres // FF... This on both sites

**Comment by erickgonzalez** [comment]
Not getting the error from above but getting this one:
```
09:46:10.612  ERROR business.PublisherAPIImpl - Error publishing bundle with ID '01DNQ3VPKKMVC695V4N07NY0DS.tar.gz': Index: 0, Size: 0
com.dotcms.publishing.DotPublishingException: Index: 0, Size: 0
	at com.dotcms.enterprise.publishing.remote.handler.LinkHandler.a(SourceFile:158) ~[ee-5.0.0-SNAPSHOT.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.LinkHandler.handle(SourceFile:59) ~[ee-5.0.0-SNAPSHOT.jar:?]
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:203) ~[dotcms_5.0.0_6a65677.jar:?]
	at com.dotcms.rest.PublishThread.run(PublishThread.java:42) ~[dotcms_5.0.0_6a65677.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_191]
	at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_191]
	at com.dotmarketing.portlets.links.business.MenuLinkFactoryImpl.load(MenuLinkFactoryImpl.java:40) ~[dotcms_5.0.0_6a65677.jar:?]
	at com.dotmarketing.portlets.links.business.MenuLinkAPIImpl.find_aroundBody8(MenuLinkAPIImpl.java:154) ~[dotcms_5.0.0_6a65677.jar:?]
	at com.dotmarketing.portlets.links.business.MenuLinkAPIImpl$AjcClosure9.run(MenuLinkAPIImpl.java:1) ~[dotcms_5.0.0_6a65677.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.0.0_6a65677.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.0.0_6a65677.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.0.0_6a65677.jar:?]
	at com.dotmarketing.portlets.links.business.MenuLinkAPIImpl.find(MenuLinkAPIImpl.java:152) ~[dotcms_5.0.0_6a65677.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.LinkHandler.a(SourceFile:108) ~[ee-5.0.0-SNAPSHOT.jar:?]
	... 4 more
```

**Comment by erickgonzalez** [comment]
PR https://github.com/dotCMS/core/pull/17376
PR EE https://github.com/dotCMS/enterprise-2.x/pull/686

**Comment by dsilvam** [comment]
Passed Internal QA: 
1. Configured PP on sender and receiver
2. Copied demo host on sender
3. PPed copied demo host

Copied host pushed correctly and showing proper status on both sender and receiver.

**Comment by bryanboza** [comment]
Fixed, tested on master with both environments using psql and works fine
