### ISSUE TITLE
Can't hit complete URL Map Path on backend

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#16671]
Tested on latest dotcms 5.1.5 version.

When logged into the backend of dotcms, you can browse to a URLMapped page and edit it in edit mode.  When you open a new tab (logged into edit mode) and try to hit a URLMapped page directly,

https://demo.dotcms.com/news/u-s-labor-department-moves-forward-on-retirement-advice-proposal

dotCMS redirects you to the detail page with no content loaded, even though same links work when browsing edit mode.  

![edit-mode-url-maps](https://user-images.githubusercontent.com/934364/58897724-f4c97200-86c6-11e9-9197-627064f07f3a.gif)

**Comment by wezell** [comment]
PR: #16672

**Comment by bryanboza** [comment]
Fixed, tested on master branch and now this works as expected

**Comment by bryanboza** [comment]
Fixed tested on release branch // docker // FF

**Comment by wezell** [comment]
This does not work on authoring:
```
dotcms_1  | 18:41:04.363  ERROR page.PageResource - HTMLPageAssetNotFoundException on PageResource.render, parameters:  org.apache.catalina.connector.RequestFacade@4aff2281, docs/latest/user-management null:
dotcms_1  | java.lang.NullPointerException: null
dotcms_1  | 	at com.dotmarketing.cms.urlmap.URLMapAPIImpl.getContentlet(URLMapAPIImpl.java:185) ~[dotcms_5.1.6_5f12cc0.jar:?]
dotcms_1  | 	at com.dotmarketing.cms.urlmap.URLMapAPIImpl.processURLMap(URLMapAPIImpl.java:71) ~[dotcms_5.1.6_5f12cc0.jar:?]
dotcms_1  | 	at com.dotmarketing.portlets.htmlpageasset.business.render.HTMLPageAssetRenderedAPIImpl.findByURLMap(HTMLPageAssetRenderedAPIImpl.java:307) ~[dotcms_5.1.6_5f12cc0.jar:?]
dotcms_1  | 	at com.dotmarketing.portlets.htmlpageasset.business.render.HTMLPageAssetRenderedAPIImpl.getHtmlPageAsset(HTMLPageAssetRenderedAPIImpl.java:267) ~[dotcms_5.1.6_5f12cc0.jar:?]
dotcms_1  | 	at com.dotmarketing.portlets.htmlpageasset.business.render.HTMLPageAssetRenderedAPIImpl.getDefaultEditPageMode(HTMLPageAssetRenderedAPIImpl.java:212) ~[dotcms_5.1.6_5f12cc0.jar:?]
dotcms_1  | 	at com.dotcms.rest.api.v1.page.PageResource.render(PageResource.java:218) ~[dotcms_5.1.6_5f12cc0.jar:?]
dotcms_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
dotcms_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
dotcms_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
dotcms_1  | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
```

**Comment by wezell** [comment]
This is broken if the content type in question does not have a Host or Folder field.

**Comment by wezell** [comment]
pr: #16671

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF and now it works as expected. Also tested on a Windows instance.
