### ISSUE TITLE
[core] : Latest master is not working with JBoss 7.1.1

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#16992]
Reported when working on Support Ticket: [Zendesk-98776](https://dotcms.zendesk.com/agent/tickets/98776)
Reproducible in latest master.

Trying to deploy dotCMS in JBoss 7.1.1 is not working.

### Steps to reproduce the behavior:
1. Follow our official documentation on how to deploy dotCMS in JBoss 7: https://dotcms.com/docs/latest/deploy-as-a-war-in-jboss-eap-7
2. Run the `bin/standalone.sh` script
3. The following error is printed on the Terminal:
```
josecastro@Joses-MBP-2:~/Downloads/jboss-as-7.1.1.Final\ (09:12:27)$ bin/standalone.sh 
=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /Users/josecastro/Downloads/jboss-as-7.1.1.Final

  JAVA: /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/bin/java

  JAVA_OPTS:  -server -XX:+UseCompressedOops -XX:+TieredCompilation -Xms1303m -Xmx1303m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman,net.bytebuddy.agent -Djava.awt.headless=true -javaagent:/Users/josecastro/Downloads/jboss-as-7.1.1.Final/standalone/deployments/ROOT.war/WEB-INF/lib/byte-buddy-agent-1.6.12.jar

=========================================================================

Exception in thread "main" javax.xml.parsers.FactoryConfigurationError: Provider __redirected.__SAXParserFactory could not be instantiated: java.lang.NullPointerException
	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:204)
	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:152)
	at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:232)
	at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:127)
	at jdk.xml.internal.JdkXmlUtils.getSAXFactory(JdkXmlUtils.java:235)
	at jdk.xml.internal.JdkXmlUtils.<clinit>(JdkXmlUtils.java:78)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.<init>(SchemaParsingConfig.java:319)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.<init>(SchemaParsingConfig.java:254)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.<init>(XSDHandler.java:480)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.<init>(XSDHandler.java:487)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.<init>(XMLSchemaLoader.java:357)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.<init>(XMLSchemaLoader.java:292)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.<init>(XMLSchemaFactory.java:97)
	at javax.xml.validation.SchemaFactoryFinder._newFactory(SchemaFactoryFinder.java:232)
	at javax.xml.validation.SchemaFactoryFinder.newFactory(SchemaFactoryFinder.java:146)
	at javax.xml.validation.SchemaFactory.newInstance(SchemaFactory.java:213)
	at __redirected.__SchemaFactory.<clinit>(__SchemaFactory.java:66)
	at __redirected.__JAXPRedirected.initAll(__JAXPRedirected.java:88)
	at org.jboss.modules.Module$1.run(Module.java:85)
	at org.jboss.modules.Module$1.run(Module.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.jboss.modules.Module.<clinit>(Module.java:72)
	at org.jboss.modules.Main.main(Main.java:255)
Caused by: java.lang.NullPointerException
	at __redirected.__RedirectedUtils.loadProvider(__RedirectedUtils.java:94)
	at __redirected.__RedirectedUtils.loadProvider(__RedirectedUtils.java:87)
	at __redirected.__SAXParserFactory.<init>(__SAXParserFactory.java:102)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:192)
	... 22 more
```

### Expected behavior
dotCMS must run on any of the supported servers without problems.

### Additional context
This is keeping the Support Team from checking the existence of #16991

## Acceptance Criteria
1. Test **ALL** the dotCMS features in JBoss too, as it is a supported environment.

**Comment by nollymar** [comment]
As JBoss 7.1.1 is not an official supported version (https://jbossas.jboss.org/downloads) , we are adding support to WildFly 17 (the latest version to date - https://wildfly.org/).

**Comment by nollymar** [comment]
These changes were applied to support WildFly 17: 
**core project:** https://github.com/dotCMS/core/pull/17118
**appservers-config project:** https://github.com/dotCMS/appservers-config/pull/3

**Comment by nollymar** [comment]
**Note to Doc:** This document contains the steps required to deploy dotCMS in WildFly 17: https://docs.google.com/document/d/1PYP7b_DBFxdjAEz-72YlKaP2HdBPQiSbyV0T2-sUG-Y/edit?usp=sharing

**Note to QA:** It is important to test the deployment using the supported databases (postgres, mysql, oracle, MSSQL). Additionally, verify that all features (especially those related to file management, i.e.: file upload/download) are working correctly

**Comment by wezell** [comment]
In 5.1.6 you need to start tomcat to initially populate the dotCMS database and then you can point wildfly to it. 
In 5.2., this is not necessary and you can start wildfly normally.

**Comment by wezell** [comment]
Part of 5.1.6
