### ISSUE TITLE
Non-selection of SystemAction throws an exception when creating a new Content Type

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17030]
When creating a new content type, if you do not select a system action, the content type cannot be saved.   

```
10:42:24.796  INFO  caffine.CaffineCache - ***	 Building Cache : workflowstepcache, size:1000,Concurrency:32
10:42:24.796  WARN  contenttype.ContentTypeResource - Deleting the system action: NEW, for content type: Testing
10:42:24.796  INFO  caffine.CaffineCache - ***	 Building Cache : workflowstepcache, size:1000,Concurrency:32
10:42:55.049  INFO  caffine.CaffineCache - ***	 Building Cache : workflowstepcache, size:1000,Concurrency:32
10:42:55.049  ERROR contenttype.ContentTypeResource - Could not delete the system action associated to the content type: Testing, system action: NEW, because it does not exists
com.dotcms.contenttype.exception.NotFoundInDbException: Could not delete the system action associated to the content type: Testing, system action: NEW, because it does not exists
	at com.dotcms.workflow.helper.WorkflowHelper.deleteSystemAction_aroundBody8(WorkflowHelper.java:413) ~[classes/:?]
	at com.dotcms.workflow.helper.WorkflowHelper$AjcClosure9.run(WorkflowHelper.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[classes/:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:59) ~[classes/:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[classes/:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[classes/:?]
	at com.dotcms.workflow.helper.WorkflowHelper.deleteSystemAction(WorkflowHelper.java:401) ~[classes/:?]
	at com.dotcms.rest.api.v1.contenttype.ContentTypeResource.saveContentTypeAndDependencies_aroundBody0(ContentTypeResource.java:253) ~[classes/:?]
	at com.dotcms.rest.api.v1.contenttype.ContentTypeResource$AjcClosure1.run(ContentTypeResource.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[classes/:?]
```

**Comment by wezell** [comment]
This was fixed
