### ISSUE TITLE
Rendering form on Front end fills logs with errors

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17054]
When I hit a page that has a form on it as an anonymous user on the front end, I get a ton of errors in the logs that look like:

```
14:11:40.157  ERROR business.KeyValueAPIImpl - An error occurred when retrieving a KeyValue object with key 'ContactUs.formReturnPage.fixed': You must specify a user if you are not respecting frontend roles
com.dotmarketing.exception.DotSecurityException: You must specify a user if you are not respecting frontend roles
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.searchIndex(ESContentletAPIImpl.java:816) ~[classes/:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.search(ESContentletAPIImpl.java:698) ~[classes/:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.search(ESContentletAPIImpl.java:689) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.search(ContentletAPIInterceptor.java:1602) ~[classes/:?]
	at com.dotcms.keyvalue.business.KeyValueAPIImpl.queryKeyValues(KeyValueAPIImpl.java:180) ~[classes/:?]
	at com.dotcms.keyvalue.business.KeyValueAPIImpl.get(KeyValueAPIImpl.java:137) ~[classes/:?]
	at com.dotcms.languagevariable.business.LanguageVariableAPIImpl.getValueFromUserLanguage(LanguageVariableAPIImpl.java:96) ~[classes/:?]
	at com.dotcms.languagevariable.business.LanguageVariableAPIImpl.get(LanguageVariableAPIImpl.java:66) ~[classes/:?]
	at com.dotcms.languagevariable.business.LanguageVariableAPI.getLanguageVariable(LanguageVariableAPI.java:105) ~[classes/:?]
	at com.dotcms.contenttype.model.field.layout.FieldUtil.setFieldInternationalization(FieldUtil.java:251) ~[classes/:?]
	at com.dotcms.contenttype.model.field.layout.FieldLayoutColumnSerializer.serialize(FieldLayoutColumnSerializer.java:64) ~[classes/:?]
	at com.dotcms.contenttype.model.field.layout.FieldLayoutColumnSerializer.serialize(FieldLayoutColumnSerializer.java:1) ~[classes/:?]
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1396) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:913) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.dotcms.contenttype.model.field.layout.FieldLayoutRowSerializer.serialize(FieldLayoutRowSerializer.java:68) ~[classes/:?]
	at com.dotcms.contenttype.model.field.layout.FieldLayoutRowSerializer.serialize(FieldLayoutRowSerializer.java:1) ~[classes/:?]
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1396) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:913) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.dotcms.contenttype.model.field.layout.FieldLayoutSerializer.serialize(FieldLayoutSerializer.java:35) ~[classes/:?]
	at com.dotcms.contenttype.model.field.layout.FieldLayoutSerializer.serialize(FieldLayoutSerializer.java:1) ~[classes/:?]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3905) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3219) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.dotcms.rendering.velocity.viewtools.StructuresWebAPI.getLayoutAsJson(StructuresWebAPI.java:294) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372) ~[classes/:?]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361) ~[classes/:?]
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:176) ~[classes/:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285) ~[classes/:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:374) ~[classes/:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) ~[classes/:?]
	at org.apache.velocity.runtime.parser.node.ASTElseIfStatement.render(ASTElseIfStatement.java:92) ~[classes/:?]
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:106) ~[classes/:?]
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:339) ~[classes/:?]
	at org.apache.velocity.Template.merge(Template.java:390) ~[classes/:?]
	at org.apache.velocity.Template.merge(Template.java:286) ~[classes/:?]
	at com.dotcms.rendering.velocity.viewtools.VelocityWebUtil.mergeTemplate(VelocityWebUtil.java:53) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372) ~[classes/:?]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361) ~[classes/:?]
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:176) ~[classes/:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285) ~[classes/:?]
```

**Comment by wezell** [comment]
Also, it looks like we are still calling the old form macro - I am seeing this in the logs:
```
14:16:54.600  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /html/css/content/forms.css
14:16:54.710  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /html/css/content/forms.css
14:16:55.338  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /dwr/engine.js
14:16:55.339  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /html/js/content/content_form_macro.js
14:16:55.340  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /dwr/interface/TagAjax.js
14:16:55.340  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /dwr/util.js
14:16:55.342  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /dwr/interface/BrowserAjax.js
14:16:55.349  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /dwr/interface/HostAjax.js
14:16:55.349  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /dwr/interface/CategoryAjax.js
14:16:55.349  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /dwr/interface/StructureAjax.js
14:16:55.351  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /dwr/interface/TemplateAjax.js
14:16:55.434  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /html/js/content/content_form_macro.js
14:16:55.470  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /dwr/engine.js
14:16:55.568  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /dwr/util.js
14:16:55.572  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /dwr/interface/TagAjax.js
14:16:55.577  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /dwr/interface/CategoryAjax.js
14:16:55.582  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /dwr/interface/BrowserAjax.js
14:16:55.587  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /dwr/interface/HostAjax.js
14:16:55.592  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /dwr/interface/TemplateAjax.js
14:16:55.596  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /dwr/interface/StructureAjax.js
14:16:55.653  INFO  util.SecurityLogger - class com.dotcms.filters.interceptor.dotcms.DefaultBackEndLoginRequiredWebInterceptor : LoginRequiredFilter for requested url: /html/js/dotcms/dijit/form/HostFolderFilteringSelect.js

```

**Comment by wezell** [comment]
PR: #17212

**Note** The previous pull was approved by FreddyR - this new pull is just cleaned up.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
