### ISSUE TITLE
Prevent calling loadPermissions when removing Permissions

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17138]
Currently, when we remove permissions from a "permissionable" we make a call to the recursive  loadPermission method in order to resolve what permissions need to be cleaned up.  I don't think this is necessary.  I think we can just delete from the permission table and the permission_references table, clearing cache appropiately and let the permission_reference table rebuild itself as needed.

This is an example of the issue that calling the `loadPermission` when deleting causes:

```.log
com.dotcms.exception.BaseRuntimeInternationalizationException: com.dotmarketing.exception.DotDataException
	at com.dotcms.contenttype.business.ContentTypeAPIImpl.delete_aroundBody0(ContentTypeAPIImpl.java:84)
	at com.dotcms.contenttype.business.ContentTypeAPIImpl$AjcClosure1.run(ContentTypeAPIImpl.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29)
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41)
	at com.dotcms.contenttype.business.ContentTypeAPIImpl.delete(ContentTypeAPIImpl.java:77)
	at com.dotmarketing.portlets.contentlet.business.ContentletAPITest.getAllLanguages(ContentletAPITest.java:2359)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.GeneratedMethodAccessor1456.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:108)
	at sun.reflect.GeneratedMethodAccessor1455.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.dotmarketing.exception.DotDataException
	at com.dotmarketing.business.PermissionBitFactoryImpl.lambda$4(PermissionBitFactoryImpl.java:2178)
	at io.vavr.control.Try.getOrElseThrow(Try.java:671)
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions_aroundBody2(PermissionBitFactoryImpl.java:2178)
	at com.dotmarketing.business.PermissionBitFactoryImpl$AjcClosure3.run(PermissionBitFactoryImpl.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29)
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41)
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions(PermissionBitFactoryImpl.java:2141)
	at com.dotmarketing.business.PermissionBitFactoryImpl.removePermissions(PermissionBitFactoryImpl.java:1039)
	at com.dotmarketing.business.PermissionBitFactoryImpl.removePermissions(PermissionBitFactoryImpl.java:1026)
	at com.dotmarketing.business.PermissionBitAPIImpl.removePermissions_aroundBody2(PermissionBitAPIImpl.java:428)
	at com.dotmarketing.business.PermissionBitAPIImpl$AjcClosure3.run(PermissionBitAPIImpl.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:59)
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23)
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41)
	at com.dotmarketing.business.PermissionBitAPIImpl.removePermissions(PermissionBitAPIImpl.java:426)
	at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.delete(ESContentFactoryImpl.java:593)
	at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.delete(ESContentFactoryImpl.java:553)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.destroyContentlets(ESContentletAPIImpl.java:1836)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.destroy_aroundBody78(ESContentletAPIImpl.java:1715)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure79.run(ESContentletAPIImpl.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:59)
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23)
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.destroy(ESContentletAPIImpl.java:1693)
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.destroy(ContentletAPIInterceptor.java:498)
	at com.dotcms.contenttype.business.ContentTypeFactoryImpl.deleteContentletsByType(ContentTypeFactoryImpl.java:541)
	at com.dotcms.contenttype.business.ContentTypeFactoryImpl.dbDelete(ContentTypeFactoryImpl.java:448)
	at com.dotcms.contenttype.business.ContentTypeFactoryImpl.delete(ContentTypeFactoryImpl.java:79)
	at com.dotcms.contenttype.business.ContentTypeAPIImpl.delete_aroundBody0(ContentTypeAPIImpl.java:81)
	... 57 more
Caused by: com.dotcms.concurrent.DotConcurrentException: Unable to acquire Lock on key `PermissionID:cc3c5807-2e98-481a-ba51-45144920ca8b` and thread `Test worker` 
	at com.dotcms.concurrent.lock.StripedLockImpl.tryLock(StripedLockImpl.java:94)
	at com.dotcms.concurrent.lock.StripedLockImpl.tryLock(StripedLockImpl.java:55)
	at com.dotcms.concurrent.lock.IdentifierStripedLock.tryLock(IdentifierStripedLock.java:16)
	at com.dotmarketing.business.PermissionBitFactoryImpl.lambda$3(PermissionBitFactoryImpl.java:2160)
	at io.vavr.control.Try.of(Try.java:62)
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions_aroundBody2(PermissionBitFactoryImpl.java:2160)
	... 89 more
```

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17145

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17182

**Comment by jgambarios** [comment]
The QA for this thicket will be made as part of https://github.com/dotcms/core/issues/16963
