### ISSUE TITLE
Site Search fails with new Language ID (long)

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#17184]
### Describe the bug
Reproducible in 5.1.6.

### Steps to reproduce the behavior:
1. Create a new Language
2. Create a new page and content in that new language
3. Try to create a Site Search index.

```
16:29:12.190  ERROR business.ESIndexAPI - failed to parse [language]
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [language]
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:302) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:485) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:607) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:407) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:384) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.mapper.DocumentParser.internalParseDocument(DocumentParser.java:93) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:67) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:261) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:708) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:686) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:667) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:548) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequest(TransportShardBulkAction.java:140) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:236) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:123) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:110) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:72) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1033) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1011) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:104) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:358) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:298) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:974) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:971) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:238) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2210) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:983) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.access$500(TransportReplicationAction.java:97) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:319) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:294) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:281) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:652) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.3.jar:6.1.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (1567807843598) out of range of int
 at [Source: (org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper); line: 1, column: 152]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804) ~[jackson-core-2.9.7.jar:2.9.7]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:669) ~[jackson-core-2.9.7.jar:2.9.7]
	at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:869) ~[jackson-core-2.9.7.jar:2.9.7]
	at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:801) ~[jackson-core-2.9.7.jar:2.9.7]
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:645) ~[jackson-core-2.9.7.jar:2.9.7]
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.doIntValue(JsonXContentParser.java:162) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.intValue(AbstractXContentParser.java:171) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType$6.parse(NumberFieldMapper.java:565) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType$6.parse(NumberFieldMapper.java:544) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.mapper.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:996) ~[elasticsearch-6.1.3.jar:6.1.3]
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:297) ~[elasticsearch-6.1.3.jar:6.1.3]
	... 38 more
```

Mapping was not changed after the Language Id code change: https://github.com/dotCMS/core/blob/5.1.6/dotCMS/src/main/resources/es-sitesearch-mapping.json#L54

### Additional context
Client ticket: https://dotcms.zendesk.com/agent/tickets/99124

## Acceptance Criteria

1. Unit test

**Comment by wezell** [comment]
Instead of mapping it to `long` I think we should try to map it to `keyword` to support future changes and then test to make sure it works

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/17257

**Comment by erickgonzalez** [comment]
Working as it should, there is no error in the log and able to find the content on the SiteSearch Index.

**Comment by bryanboza** [comment]
Fixed, unable to reproduce the main problem on master
