### ISSUE TITLE
Add CloseDbIfOpened to field variables

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17354]
We see this error in our tests sometimes:
```
com.dotmarketing.business.DotStateException: unable to load field variables:Connection has already been closed.{
  "SQL": ["select id, field_id, variable_name, variable_key, variable_value, user_id, last_mod_date from field_variable where field_id = ? order by variable_key"],
  "maxRows": [-1],
  "offest": [0],
  "params": "f231c8a7-9606-4823-8185-6e2172fd5506"
}
	at com.dotcms.contenttype.model.field.Field.fieldVariables(Field.java:188)
	at com.dotcms.contenttype.model.field.ImmutableHiddenField.fieldVariables(ImmutableHiddenField.java:1856)
	at com.dotcms.contenttype.transform.field.DbFieldTransformer.fromMap(DbFieldTransformer.java:181)
	at com.dotcms.contenttype.transform.field.DbFieldTransformer.asList(DbFieldTransformer.java:191)
	at com.dotcms.contenttype.business.FieldFactoryImpl.selectByContentTypeInDb(FieldFactoryImpl.java:308)
	at com.dotcms.contenttype.business.FieldFactoryImpl.byContentTypeId(FieldFactoryImpl.java:84)
	at com.dotcms.contenttype.business.FieldAPIImpl.byContentTypeId_aroundBody6(FieldAPIImpl.java:633)
	at com.dotcms.contenttype.business.FieldAPIImpl$AjcClosure7.run(FieldAPIImpl.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29)
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41)
	at com.dotcms.contenttype.business.FieldAPIImpl.byContentTypeId(FieldAPIImpl.java:632)
	at com.dotcms.contenttype.model.type.ContentType.fields(ContentType.java:165)
	at com.dotcms.contenttype.model.type.ImmutableSimpleContentType.fields(ImmutableSimpleContentType.java:1654)
	at com.dotcms.graphql.business.GraphqlAPIImpl.createSchemaType(GraphqlAPIImpl.java:168)
	at com.dotcms.graphql.business.GraphqlAPIImpl.lambda$1(GraphqlAPIImpl.java:263)
	at java.lang.Iterable.forEach(Iterable.java:75)
```

We need to make sure the connection is closed after loading field variables

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17355
