### ISSUE TITLE
dotCMS Upgrade Task to 5.2 fails

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17357]
Two issues here:
1. If there is an api key for a user that no longer exists in the system, the upgrade task will fail
2. The initial getting and storing of the Anonymous user fails because we are trying to add it to the CMS_ANON role, which is a locked role. 

```
17:59:50.620  INFO  runonce.Task05160MultiTreeAddPersonalizationColumnAndChangingPK - Adding new 'personalization' column to 'multi_tree' table.
17:59:50.620  INFO  db.DotConnect - Executing ALTER TABLE multi_tree ADD personalization varchar(255)   not null default 'dot:default'
17:59:50.644  INFO  runonce.Task05160MultiTreeAddPersonalizationColumnAndChangingPK - Adding new 'PK' to 'multi_tree' table, including personalization column.
17:59:50.644  INFO  db.DotConnect - Executing ALTER TABLE multi_tree ADD CONSTRAINT idx_multitree_index1 PRIMARY KEY (parent1, parent2, child, relation_type,personalization)
17:59:50.657  INFO  startup.StartupTasksExecutor - Database upgraded to version: 5160
17:59:50.665  INFO  startup.StartupTasksExecutor - Running: Task05165CreateContentTypeWorkflowActionMappingTable
17:59:50.665  INFO  runonce.Task05165CreateContentTypeWorkflowActionMappingTable - Creates the table workflow_action_mappings.
17:59:50.665  INFO  db.DotConnect - Executing create table workflow_action_mappings (
dotcms_1  |
   id varchar(36) not null,
   action varchar(36) not null,
   workflow_action varchar(255) not null,
   scheme_or_content_type  varchar(255) not null,
   primary key (id)
)
17:59:50.674  INFO  runonce.Task05165CreateContentTypeWorkflowActionMappingTable - Creates the table idx_workflow_action_mappings unique index.
17:59:50.674  INFO  db.DotConnect - Executing CREATE UNIQUE INDEX idx_workflow_action_mappings ON workflow_action_mappings (action, workflow_action, scheme_or_content_type)
17:59:50.680  INFO  startup.StartupTasksExecutor - Database upgraded to version: 5165
17:59:50.682  INFO  startup.StartupTasksExecutor - Running: Task05170DefineFrontEndAndBackEndRoles
db_1      | ERROR:  insert or update on table "users_cms_roles" violates foreign key constraint "fkusers_cms_roles2"
db_1      | DETAIL:  Key (user_id)=(dotcms.org.1) is not present in table "user_".
db_1      | STATEMENT:  INSERT INTO users_cms_roles (id, user_id, role_id) VALUES($1, $2, $3)
com.dotmarketing.exception.DotDataException: SQL Error doing a batch and couldn't rollback
	at com.dotmarketing.common.db.DotConnect.executeBatch_aroundBody0(DotConnect.java:1083)
	at com.dotmarketing.common.db.DotConnect$AjcClosure1.run(DotConnect.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:59)
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23)
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41)
	at com.dotmarketing.common.db.DotConnect.executeBatch(DotConnect.java:1050)
	at com.dotmarketing.common.db.DotConnect.executeBatch(DotConnect.java:1031)
	at com.dotmarketing.startup.runonce.Task05170DefineFrontEndAndBackEndRoles.addRole(Task05170DefineFrontEndAndBackEndRoles.java:283)
	at com.dotmarketing.startup.runonce.Task05170DefineFrontEndAndBackEndRoles.assignBackendRole(Task05170DefineFrontEndAndBackEndRoles.java:292)
	at com.dotmarketing.startup.runonce.Task05170DefineFrontEndAndBackEndRoles.executeUpgrade_aroundBody0(Task05170DefineFrontEndAndBackEndRoles.java:347)
	at com.dotmarketing.startup.runonce.Task05170DefineFrontEndAndBackEndRoles$AjcClosure1.run(Task05170DefineFrontEndAndBackEndRoles.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29)
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41)
	at com.dotmarketing.startup.runonce.Task05170DefineFrontEndAndBackEndRoles.executeUpgrade(Task05170DefineFrontEndAndBackEndRoles.java:308)
	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:275)
	at com.liferay.portal.servlet.MainServlet.init_aroundBody0(MainServlet.java:118)
	at com.liferay.portal.servlet.MainServlet$AjcClosure1.run(MainServlet.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29)
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41)
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:104)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4978)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5290)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1140)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.BatchUpdateException: Batch entry 6 INSERT INTO users_cms_roles (id, user_id, role_id) VALUES('75ff0950-d566-4f0e-9464-b8d6862d461b', 'dotcms.org.1', '02088e05-5ff5-43c2-a4fa-11a7272cb199') was aborted: ERROR: insert or update on table "users_cms_roles" violates foreign key constraint "fkusers_cms_roles2"
  Detail: Key (user_id)=(dotcms.org.1) is not present in table "user_".  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:479)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractQueryReport$StatementProxy.invoke(AbstractQueryReport.java:210)
	at com.sun.proxy.$Proxy25.executeBatch(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy25.executeBatch(Unknown Source)
	at com.dotmarketing.common.db.DotConnect.executeBatch_aroundBody0(DotConnect.java:1073)
	... 41 more
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "users_cms_roles" violates foreign key constraint "fkusers_cms_roles2"
  Detail: Key (user_id)=(dotcms.org.1) is not present in table "user_".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	... 57 more
25-Sep-2019 17:59:50.734 INFO [hz.ShutdownThread] com.hazelcast.instance.Node.null [192.168.64.3]:5701 [dev] [3.9.2] Running shutdown hook... Current state: ACTIVE
17:59:50.724  ERROR db.DotConnect - Batch entry 6 INSERT INTO users_cms_roles (id, user_id, role_id) VALUES('75ff0950-d566-4f0e-9464-b8d6862d461b', 'dotcms.org.1', '02088e05-5ff5-43c2-a4fa-11a7272cb199') was aborted: ERROR: insert or update on table "users_cms_roles" violates foreign key constraint "fkusers_cms_roles2"
  Detail: Key (user_id)=(dotcms.org.1) is not present in table "user_".  Call getNextException to see other errors in the batch.
java.sql.BatchUpdateException: Batch entry 6 INSERT INTO users_cms_roles (id, user_id, role_id) VALUES('75ff0950-d566-4f0e-9464-b8d6862d461b', 'dotcms.org.1', '02088e05-5ff5-43c2-a4fa-11a7272cb199') was aborted: ERROR: insert or update on table "users_cms_roles" violates foreign key constraint "fkusers_cms_roles2"
  Detail: Key (user_id)=(dotcms.org.1) is not present in table "user_".  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:479) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556) ~[postgresql-42.2.2.jar:42.2.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractQueryReport$StatementProxy.invoke(AbstractQueryReport.java:210) ~[tomcat-jdbc.jar:?]
	at com.sun.proxy.$Proxy25.executeBatch(Unknown Source) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc.jar:?]
	at com.sun.proxy.$Proxy25.executeBatch(Unknown Source) ~[?:?]
	at com.dotmarketing.common.db.DotConnect.executeBatch_aroundBody0(DotConnect.java:1073) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.common.db.DotConnect$AjcClosure1.run(DotConnect.java:1) ~[dotcms_5.0.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:59) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeBatch(DotConnect.java:1050) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeBatch(DotConnect.java:1031) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.startup.runonce.Task05170DefineFrontEndAndBackEndRoles.addRole(Task05170DefineFrontEndAndBackEndRoles.java:283) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.startup.runonce.Task05170DefineFrontEndAndBackEndRoles.assignBackendRole(Task05170DefineFrontEndAndBackEndRoles.java:292) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.startup.runonce.Task05170DefineFrontEndAndBackEndRoles.executeUpgrade_aroundBody0(Task05170DefineFrontEndAndBackEndRoles.java:347) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.startup.runonce.Task05170DefineFrontEndAndBackEndRoles$AjcClosure1.run(Task05170DefineFrontEndAndBackEndRoles.java:1) ~[dotcms_5.0.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.startup.runonce.Task05170DefineFrontEndAndBackEndRoles.executeUpgrade(Task05170DefineFrontEndAndBackEndRoles.java:308) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:275) ~[dotcms_5.0.0_999999.jar:?]
	at com.liferay.portal.servlet.MainServlet.init_aroundBody0(MainServlet.java:118) ~[dotcms_5.0.0_999999.jar:?]
	at com.liferay.portal.servlet.MainServlet$AjcClosure1.run(MainServlet.java:1) ~[dotcms_5.0.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.0.0_999999.jar:?]
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:104) ~[dotcms_5.0.0_999999.jar:?]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4978) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5290) ~[catalina.jar:8.5.32]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734) ~[catalina.jar:8.5.32]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1140) ~[catalina.jar:8.5.32]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875) ~[catalina.jar:8.5.32]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "users_cms_roles" violates foreign key constraint "fkusers_cms_roles2"
  Detail: Key (user_id)=(dotcms.org.1) is not present in table "user_".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178) ~[postgresql-42.2.2.jar:42.2.2]
	... 57 more
25-Sep-2019 17:59:50.735 INFO [hz.ShutdownThread] com.hazelcast.core.LifecycleService.null [192.168.64.3]:5701 [dev] [3.9.2] [192.168.64.3]:5701 is SHUTTING_DOWN
17:59:50.726  ERROR db.HibernateUtil - ---------- DotHibernate: error on rollbackTransaction ---------------
org.postgresql.util.PSQLException: Cannot rollback when autoCommit is enabled.
2019/09/25 17:59:51 Command exited with error: exit status 1
db_1      | LOG:  incomplete startup packet
[cmd] /srv/init.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
auth5_dotcms_1 exited with code 1
http_1    | BACKEND MEMBERS CHANGED: 0 members
http_1    | [WARNING] 267/175913 (238) : Reexecuting Master process
http_1    | [WARNING] 267/180004 (238) : Former worker 239 exited with code 0
```

**Comment by wezell** [comment]
Also I am seeing this:

```
8.49.249.66,user:null
dotcms_1  | 18:24:09.985  WARN  error.custom_002derror_002dpage_jsp - Exception Error on template on /html/error/custom-error-page.jsp
dotcms_1  | 18:24:10.648  INFO  caffine.CaffineCache - ***	 Building Cache : shortyidcache, size:1000,Concurrency:32
dotcms_1  | 18:24:10.656  INFO  util.SecurityLogger - class com.dotmarketing.business.RoleAPIImpl : Adding role:'CMS Anonymous' to user:anonymous email:anonymous@dotcmsfakeemail.org -- ip:108.49.249.66,user:null
dotcms_1  | java.lang.reflect.InvocationTargetException
dotcms_1  | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
dotcms_1  | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
dotcms_1  | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
dotcms_1  | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
dotcms_1  | 	at com.dotcms.osgi.logger.ClickHouseLoggerImpl.logInternal(ClickHouseLoggerImpl.java:89)
dotcms_1  | 	at com.dotcms.osgi.logger.ClickHouseLoggerImpl.log(ClickHouseLoggerImpl.java:74)
dotcms_1  | 	at com.dotcms.osgi.servlet.ClickhouseFilter.doFilter(ClickhouseFilter.java:81)
dotcms_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dotcms_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dotcms_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
dotcms_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
dotcms_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
dotcms_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
dotcms_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
dotcms_1  | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
dotcms_1  | 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:685)
dotcms_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
dotcms_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
dotcms_1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
dotcms_1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
dotcms_1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
dotcms_1  | 	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1699)
dotcms_1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
dotcms_1  | 	at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1050)
dotcms_1  | 	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$4.completed(Nio2Endpoint.java:630)
dotcms_1  | 	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$4.completed(Nio2Endpoint.java:608)
dotcms_1  | 	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
dotcms_1  | 	at sun.nio.ch.Invoker$2.run(Invoker.java:218)
dotcms_1  | 	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
dotcms_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
dotcms_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
dotcms_1  | 	at java.lang.Thread.run(Thread.java:748)
dotcms_1  | Caused by: java.lang.IllegalStateException: Duplicate key 06343b95b9304a13bb4f47d1bb56eceb
dotcms_1  | 	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
dotcms_1  | 	at java.util.HashMap.merge(HashMap.java:1254)
dotcms_1  | 	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
dotcms_1  | 	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
dotcms_1  | 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
dotcms_1  | 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
dotcms_1  | 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
dotcms_1  | 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
dotcms_1  | 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
dotcms_1  | 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
dotcms_1  | 	at com.dotcms.visitor.filter.characteristics.GDPRCharacter.<init>(GDPRCharacter.java:39)
dotcms_1  | 	... 32 more
dotcms_1  | 18:24:10.698  INFO  util.SecurityLogger - class com.dotmarketing.business.RoleAPIImpl : Adding role:'CMS Anonymous' to user:anonymous email:anonymous@dotcmsfakeemail.org -- ip:108.49.249.66,user:null
```

**Comment by fabrizzio-dotCMS** [comment]
I tested this fix against the provided database. All upgrade task ran successfully. No login problems whatsoever. The new Roles are there as expected and also applied to the respective user.

The second error reported that was supposed to appear while navigating on the frontend is not happening.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17379

**Comment by bryanboza** [comment]
Fixed, unable to reproduce on master
