### ISSUE TITLE
Getting a token for a front end user errors in the logs

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17398]
If you request an API token for a front end user, we get an error in the logs about `triggerSwitchSiteEventIfNecessary`
```
21:27:21.368  ERROR listeners.SwitchSiteListener - User user-403e032f-27fe-46aa-bf86-32761ef93ba6 does not have permission to host:demo.dotcms.com
com.dotmarketing.exception.DotSecurityException: User user-403e032f-27fe-46aa-bf86-32761ef93ba6 does not have permission to host:demo.dotcms.com
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl.find_aroundBody6(HostAPIImpl.java:289) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl$AjcClosure7.run(HostAPIImpl.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[classes/:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[classes/:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl.find(HostAPIImpl.java:266) ~[classes/:?]
	at com.dotcms.listeners.SwitchSiteListener.triggerSwitchSiteEventIfNecessary(SwitchSiteListener.java:59) ~[classes/:?]
	at com.dotcms.listeners.SwitchSiteListener.attributeAdded(SwitchSiteListener.java:31) ~[classes/:?]
	at org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1522) ~[catalina.jar:8.5.32]
	at org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1415) ~[catalina.jar:8.5.32]
	at org.apache.catalina.session.Standar
```

**Comment by wezell** [comment]
PR: #17394  - fixed in a bigger pr
