### ISSUE TITLE
Form validation failing

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17395]
When you save a struts form with a validation, we throw an error.
1. Open the Banner Container
2. Add the Content Generic to it with ${body} in the Content Type/Code field
3. Hit save.  You get an error in the logs that Validation is not happening.

```
19:05:00.945  ERROR validator.ValidatorForm - No such validation method: com.dotcms.repackage.org.apache.struts.validator.FieldChecks.validateRequired(java.lang.Object, org.apache.commons.validator.ValidatorAction, org.apache.commons.validator.Field, com.dotcms.repackage.org.apache.struts.action.ActionMessages, javax.servlet.http.HttpServletRequest)
org.apache.commons.validator.ValidatorException: No such validation method: com.dotcms.repackage.org.apache.struts.validator.FieldChecks.validateRequired(java.lang.Object, org.apache.commons.validator.ValidatorAction, org.apache.commons.validator.Field, com.dotcms.repackage.org.apache.struts.action.ActionMessages, javax.servlet.http.HttpServletRequest)
	at org.apache.commons.validator.ValidatorAction.loadValidationMethod(ValidatorAction.java:609) ~[commons-validator-1.6.jar:1.6]
	at org.apache.commons.validator.ValidatorAction.executeValidationMethod(ValidatorAction.java:537) ~[commons-validator-1.6.jar:1.6]
	at org.apache.commons.validator.Field.validateForRule(Field.java:840) ~[commons-validator-1.6.jar:1.6]
	at org.apache.commons.validator.Field.validate(Field.java:920) ~[commons-validator-1.6.jar:1.6]
	at org.apache.commons.validator.Form.validate(Form.java:293) ~[commons-validator-1.6.jar:1.6]
	at org.apache.commons.validator.Validator.validate(Validator.java:363) ~[commons-validator-1.6.jar:1.6]
	at com.dotcms.repackage.org.apache.struts.validator.ValidatorForm.validate(ValidatorForm.java:110) ~[dot.struts-1.2.10_1.jar:?]
	at com.dotmarketing.portlets.containers.struts.ContainerForm.validate(ContainerForm.java:114) ~[classes/:?]
	at com.dotmarketing.util.Validator.validate(Validator.java:27) ~[classes/:?]
	at com.dotmarketing.portlets.containers.action.EditContainerAction.processAction(EditContainerAction.java:154) ~[classes/:?]
	at com.liferay.portal.struts.PortletRequestProcessor.process(PortletRequestProcessor.java:124) ~[classes/:?]
	at com.liferay.portlet.StrutsPortlet.processAction(StrutsPortlet.java:120) ~[classes/:?]
	at com.liferay.portlet.ConcretePortletWrapper.processAction(ConcretePortletWrapper.java:97) ~[classes/:?]
	at com.liferay.portal.action.LayoutAction._processPortletRequest(LayoutAction.java:194) ~[classes/:?]
	at com.liferay.portal.action.LayoutAction._processActionRequest(LayoutAction.java:206) ~[classes/:?]
	at com.liferay.portal.action.LayoutAction.execute(LayoutAction.java:82) ~[classes/:?]
	at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:431) ~[dot.struts-1.2.10_1.jar:?]
	at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:237) ~[dot.struts-1.2.10_1.jar:?]
	at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:147) ~[classes/:?]
	at com.dotcms.repackage.org.apache.struts.action.ActionServlet.process(ActionServlet.java:1202) ~[dot.struts-1.2.10_1.jar:?]
	at com.dotcms.repackage.org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:430) ~[dot.struts-1.2.10_1.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) ~[servlet-api.jar:?]
	at com.liferay.portal.servlet.MainServlet.callParentService(MainServlet.java:242) ~[classes/:?]
	at com.liferay.portal.servlet.MainServlet.service(MainServlet.java:442) ~[classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.32]
 ```

**Comment by nollymar** [comment]
Dupe: https://github.com/dotCMS/core/issues/17302
