### ISSUE TITLE
Language variables can cause push publish conflicts

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#17596]
Reported via support ticket: [99516](https://dotcms.zendesk.com/agent/tickets/99516)
Reproducible in dotCMS 5.2.0

The recommended way to create language variables for multiple languages is to add a version for every language for the same variable (https://dotcms.com/docs/latest/global-language-variables#NewLanguage). For example you can create one language variable with the identifier 'be9f3585-8d37-498e-9dea-94571f8c31c1', using the key 'myTestVariable1', having 2 versions for 2 different languages.

On the other hand, you can also create different language variables (that mean different identifiers for every variable), and use the same key for different variables if every variable is for a different language. This is not the recommended approach, but it's feasible. For example you can create 2 different language variables that use the same key for 2 different languages:
- Variable 1: identifier '024e9c39-80a8-42fb-b1bc-4e0ac47a5ed9', key 'myTestVariable1', language 1
- Variable 2: identifier 'b600546b-86ac-45a4-9309-422140ef6124', key 'myTestVariable1', language 2

When language variables are included in a bundle being push published (that is done by default if the variables have been changed since the last push publish), dotCMS will try to match them using the key (unique field). However, the match doesn't take the language into account, so having different variables using the same key as described above, will cause the push publish to fail because conflicts.

### Steps to reproduce the behavior:
1. Go to sender instance and create one language variable with the key 'myTestVariable1' in at least 2 languages (you can use any other key). Note that you are creating multiple versions for the same variable (same identifier)
2. Go to receiver instance and create different language variable with the same key you used in the step 1, using the same languages from the previous step. Note that in this case you will create different variables (different identifiers) instead of multiple versions of the same variable.
3. Push publish a content item. Make sure the language variable has been changed in the sender since the last push publish, so it's included in the bundle being push published.
4. The push publish fails with this stack trace in the receiver instance:
```
[06/11/19 10:35:10:755 CST] ERROR handler.ContentHandler: Error on File /Users/danielsolis/dev/workspace/dotcms/external/assets/bundles/01DS0S070Y8YQQ29T7PQVFBYYR/live/System Host/1/0-content.d48bdfa6-214d-4eac-8e67-d4c0db0a2675.content.xml, content id:(empty) :null
java.lang.NullPointerException: null
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handleContents(ContentHandler.java:362) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(ContentHandler.java:161) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(ContentHandler.java:136) ~[ee_clean.jar:?]
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:203) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.rest.PublishThread.run(PublishThread.java:42) ~[dotcms_5.0.0_999999.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[06/11/19 10:35:10:761 CST] ERROR business.PublisherAPIImpl: Error publishing bundle with ID '01DS0S070Y8YQQ29T7PQVFBYYR.tar.gz': null
com.dotcms.publishing.DotPublishingException: null
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handleContents(ContentHandler.java:424) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(ContentHandler.java:161) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(ContentHandler.java:136) ~[ee_clean.jar:?]
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:203) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.rest.PublishThread.run(PublishThread.java:42) ~[dotcms_5.0.0_999999.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handleContents(ContentHandler.java:362) ~[ee_clean.jar:?]
	... 5 more
```

### Expected behavior
When dotCMS matches existing content on the receiver by using unique fields, as in the case of language variables, the match should take the language into account, to avoid matching a content item with the same unique value in a different language.

### Screenshots
A language variable created in the sender instance with 2 different versions for 2 different languages:
![image](https://user-images.githubusercontent.com/2894221/68321956-2dabaf80-0088-11ea-8e2d-877787fc96fd.png)

Two different language variables created in the receiver instance using the same key for 2 different languages:
![image](https://user-images.githubusercontent.com/2894221/68321980-369c8100-0088-11ea-9c8f-ad565406f352.png)

### Additional context
This has been reported by customer via Support: Ticket [99516](https://dotcms.zendesk.com/agent/tickets/99516)

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/695

**Comment by bryanboza** [comment]
Ok, after this fix now we are not failing in the push process, we create a new version of the existing variable with the new values. 
But we have a problem here: at some moment we are doing double-checking and we are creating two new versions of the content per language, one with the logged user and other with the system user. 
Here the SC: https://www.screencast.com/t/WNAjWPWd8

I tested pushing a single piece of content since we use the same content handler but this is not happening for single contents, the problem is just with language variables" 

### To recreate 
1. Login as admin 
2. Configure a push environment 
3. On sender create a new language variable (test1)
4. On receiver create the same language variable (test1)
5. On sender side create a page and add a piece of content with this on the body `$text.get("test1")`
6. Push this page
7. On sender again, change the value of the property 
8. Push it again 
9. Check the history of the content

**Comment by wezell** [comment]
New findings moved to this issue: #17908.  It is way better to have two versions of the content than for a PP to fail.
