### ISSUE TITLE
5.2.1 fails if there are NO urlmap patterns

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17642]
Root Cause of Issue: dotCMS didn't account for customers who don't use URL mapped content.

More detailed explanation:

The query "url_map_pattern is not null" on the structure table returned 0 rows.
This resulted in a null "Matches" object.
Which resulted in a null pointer exception breaking the URLMapFilter and effectively cutting off all backend access to dotCMS.

URLMapAPIImpl.java had to be fixed in two (2) places to check for the null condition.

Place #1 fixes this issue:
```
[19/11/19 13:50:22:629 EST] ERROR filters.URLMapFilter: null
java.lang.NullPointerException: null
        at com.dotmarketing.cms.urlmap.URLMapAPIImpl.processURLMap(URLMapAPIImpl.java:68) ~[dotcms_5.2.1_999999.jar:?]
        at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:91) ~[dotcms_5.2.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
        at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:104) ~[dotcms_5.2.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
        at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:399) ~[urlrewritefilter-4.0.4.jar:4.0.4]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
        at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:66) ~[dotcms_5.2.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
        at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:88) ~[dotcms_5.2.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
        at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:48) ~[dotcms_5.2.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
        at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:99) ~[dotcms_5.2.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
        at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_5.2.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[catalina.jar:8.5.32]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) ~[catalina.jar:8.5.32]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[catalina.jar:8.5.32]
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:685) ~[catalina.jar:8.5.32]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[catalina.jar:8.5.32]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) ~[catalina.jar:8.5.32]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) ~[tomcat-coyote.jar:8.5.32]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-coyote.jar:8.5.32]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800) ~[tomcat-coyote.jar:8.5.32]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471) ~[tomcat-coyote.jar:8.5.32]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:8.5.32]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.32]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

Place #2 fixes this issue:
[19/11/19 13:50:27:784 EST] ERROR lang.Class: null
java.lang.NullPointerException: null
        at com.dotmarketing.cms.urlmap.URLMapAPIImpl.getContentlet(URLMapAPIImpl.java:89) ~[dotcms_5.2.1_999999.jar:?]
        at com.dotmarketing.cms.urlmap.URLMapAPIImpl.isUrlPattern(URLMapAPIImpl.java:58) ~[dotcms_5.2.1_999999.jar:?]
        at com.dotmarketing.filters.CMSUrlUtil.isPageAsset(CMSUrlUtil.java:194) ~[dotcms_5.2.1_999999.jar:?]
        at com.dotmarketing.filters.CMSUrlUtil.resolveResourceType(CMSUrlUtil.java:108) ~[dotcms_5.2.1_999999.jar:?]
        at com.dotmarketing.filters.CMSFilter.doFilterInternal(CMSFilter.java:95) ~[dotcms_5.2.1_999999.jar:?]
        at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:47) ~[dotcms_5.2.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
        at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_5.2.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
        at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_5.2.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
        at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:119) ~[dotcms_5.2.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
        at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:104) ~[dotcms_5.2.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
        at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:399) ~[urlrewritefilter-4.0.4.jar:4.0.4]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
        at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:134) ~[dotcms_5.2.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
        at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:88) ~[dotcms_5.2.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
        at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:48) ~[dotcms_5.2.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
        at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:99) ~[dotcms_5.2.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
        at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_5.2.1_999999.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[catalina.jar:8.5.32]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) ~[catalina.jar:8.5.32]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[catalina.jar:8.5.32]
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:685) ~[catalina.jar:8.5.32]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) ~[catalina.jar:8.5.32]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[catalina.jar:8.5.32]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) ~[catalina.jar:8.5.32]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) ~[tomcat-coyote.jar:8.5.32]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-coyote.jar:8.5.32]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800) ~[tomcat-coyote.jar:8.5.32]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471) ~[tomcat-coyote.jar:8.5.32]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:8.5.32]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.32]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

Nathan I. Keiter | Lead Network Applications Programmer | Benefits Advisory Council Member | I.D.E.A Council Member
Gettysburg College | Information Technology | DataSystems
Campus Box 2453 | 300 North Washington Street | Gettysburg, PA 17325
Phone: 717.337.6993
https://www.gettysburg.edu

**Comment by freddyucv** [comment]
The error happend when you don't have any URL Mapper create into DotCMS, in this case the regular expresion build to check if a URL have to be result using URL Mapper is '^()'

https://github.com/dotCMS/core/commit/20ec348ec50a51f832986bf229c9bc2f9e80fab4#diff-3464e497d462876010f889418e10bdc9R297

then any URL match this regular expresion so that is way dotmcs try to found a match for any URL, the fix is not just check the Null also we have to avoid that the 'isUrlPattern' ,ethod return true in this case

https://github.com/dotCMS/core/blob/20ec348ec50a51f832986bf229c9bc2f9e80fab4/dotCMS/src/main/java/com/dotmarketing/cms/urlmap/URLMapAPIImpl.java#L57

**Comment by nkeiter** [comment]
Here's the hotfix.

[global-override-url-map-api-impl.zip](https://github.com/dotCMS/core/files/3870428/global-override-url-map-api-impl.zip)

**Comment by nkeiter** [comment]
I should note that this issue also affects 5.2.0

**Comment by freddyucv** [comment]
For QA:

Really the bug is not about upgrade, it is about not URL Map into your data base, so to reproduce the error you just have to remove all the Content Type with URL Map from the data base (I mean from the starter), so you have to remove this COntent Type to test:

- Blog
- News
- Products
- Location
- Event, really this Content Type cant not be deleted so you have to remove the 'Detail Page' and 'URL Pattern' attribute

![for_qa](https://user-images.githubusercontent.com/10408015/69346935-42b44100-0c39-11ea-89c5-64e89ccd3d18.gif)

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/17646

**Comment by dsilvam** [comment]
Passed Internal QA: Able to access /dotAdmin after going through the mentioned steps.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.2 // Postgres // FF

**Comment by wezell** [comment]
Please check if we are throwing and catching the exception every page hit.  If so, let's change the return to Optional<String> rather than use an exception as a control statement.

**Comment by dsilvam** [comment]
Re-Passed Internal QA: Able to access /dotAdmin after going through the mentioned steps.

**Comment by dsilvam** [comment]
@bryanboza this one needs to be re-tested.

**Comment by bryanboza** [comment]
Fixed, retested after the last changes and I'm able to access the /dotAdmin without problems... Tested on release-5.2.2 // Postgres // FF
