### ISSUE TITLE
startup failed due to schema not generated properly

### ISSUE THREAD

**Issue by ilbunilcho** [dotCMS/core#17774]
## dotCMS version
```
dotcms_5.2.2.tar.gz
```

## Describe the bug
trying to insert '01/01/1970' to timestamp column
so it cause pgexception

### OS
```
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
```

### PostgreSQL
```
Package: postgresql
Version: 11+204ubuntu0.1
```

## context.xml
```
<!-- POSTGRESQL -->
  <Resource name="jdbc/dotCMSPool" auth="Container"
      type="javax.sql.DataSource" driverClassName="org.postgresql.Driver"
      url="jdbc:postgresql://localhost/dotcms"
      username="dotcms" password="dotcms" maxTotal="60" maxIdle="10" maxWaitMillis="60000"
      removeAbandonedOnBorrow="true" removeAbandonedOnMaintenance="true" removeAbandonedTimeout="60" logAbandoned="true" 
      timeBetweenEvictionRunsMillis="30000" validationQuery="SELECT 1" testOnBorrow="true" testWhileIdle="true"/>
```

## log
```
03:51:37.917  INFO  db.DotConnect - Executing insert into PollsQuestion (questionId, portletId, groupId, companyId, userId, userName, createDate, modifiedDate, title, description) values ('1', '25', '-1', 'liferay.com', 'liferay.com.1', 'John Wayne', current_timestamp, current_timestamp, 'What is your favorite ice cream flavor?', 'What is your favorite ice cream flavor?')
03:51:37.918  INFO  db.DotConnect - Finished Executing insert into PollsQuestion (questionId, portletId, groupId, companyId, userId, userName, createDate, modifiedDate, title, description) values ('1', '25', '-1', 'liferay.com', 'liferay.com.1', 'John Wayne', current_timestamp, current_timestamp, 'What is your favorite ice cream flavor?', 'What is your favorite ice cream flavor?')
03:51:37.919  INFO  db.DotConnect - Executing insert into User_ (userId, companyId, createDate, password_, passwordEncrypted, passwordReset, firstName, middleName, lastName, male, birthday, emailAddress, skinId, dottedSkins, roundedSkins, greeting, layoutIds, loginDate, failedLoginAttempts, agreedToTermsOfUse, active_) values ('liferay.com.default', 'default', current_timestamp, 'password', 'f', 'f', '', '', '', 't', '01/01/1970', 'default@liferay.com', '01', 'f', 'f', 'Welcome!', '', current_timestamp, 0, 'f', 't')
03:51:37.920  FATAL runalways.Task00001LoadSchema - Error: 오류: 날짜/시간 필드의 값이 범위를 벗어남: "01/01/1970"
  Hint: 날짜 표현 방식("datestyle")을 다른 것으로 사용하고 있는 듯 합니다.
  Position: 376while trying to execute insert into User_ (userId, companyId, createDate, password_, passwordEncrypted, passwordReset, firstName, middleName, lastName, male, birthday, emailAddress, skinId, dottedSkins, roundedSkins, greeting, layoutIds, loginDate, failedLoginAttempts, agreedToTermsOfUse, active_) values ('liferay.com.default', 'default', current_timestamp, 'password', 'f', 'f', '', '', '', 't', '01/01/1970', 'default@liferay.com', '01', 'f', 'f', 'Welcome!', '', current_timestamp, 0, 'f', 't') processed 28 statements
org.postgresql.util.PSQLException: 오류: 날짜/시간 필드의 값이 범위를 벗어남: "01/01/1970"
  Hint: 날짜 표현 방식("datestyle")을 다른 것으로 사용하고 있는 듯 합니다.
  Position: 376
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266) ~[postgresql-42.2.2.jar:42.2.2]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:365) ~[tomcat-dbcp.jar:8.5.32]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:365) ~[tomcat-dbcp.jar:8.5.32]
	at com.dotmarketing.common.db.DotConnect.executeStatement(DotConnect.java:251) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotmarketing.startup.runalways.Task00001LoadSchema.executeUpgrade(Task00001LoadSchema.java:92) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:212) ~[dotcms_5.2.2_834c945.jar:?]
	at com.liferay.portal.servlet.MainServlet.init_aroundBody0(MainServlet.java:118) ~[dotcms_5.2.2_834c945.jar:?]
	at com.liferay.portal.servlet.MainServlet$AjcClosure1.run(MainServlet.java:1) ~[dotcms_5.2.2_834c945.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.2.2_834c945.jar:?]
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:104) ~[dotcms_5.2.2_834c945.jar:?]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4978) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5290) ~[catalina.jar:8.5.32]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734) ~[catalina.jar:8.5.32]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1140) ~[catalina.jar:8.5.32]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875) ~[catalina.jar:8.5.32]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
03:51:37.921  FATAL runalways.Task00001LoadSchema - Error: 오류: 날짜/시간 필드의 값이 범위를 벗어남: "01/01/1970"
  Hint: 날짜 표현 방식("datestyle")을 다른 것으로 사용하고 있는 듯 합니다.
  Position: 376 processed 28 statements
com.dotmarketing.exception.DotDataException: 오류: 날짜/시간 필드의 값이 범위를 벗어남: "01/01/1970"
  Hint: 날짜 표현 방식("datestyle")을 다른 것으로 사용하고 있는 듯 합니다.
  Position: 376
	at com.dotmarketing.startup.runalways.Task00001LoadSchema.executeUpgrade(Task00001LoadSchema.java:99) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:212) ~[dotcms_5.2.2_834c945.jar:?]
	at com.liferay.portal.servlet.MainServlet.init_aroundBody0(MainServlet.java:118) ~[dotcms_5.2.2_834c945.jar:?]
	at com.liferay.portal.servlet.MainServlet$AjcClosure1.run(MainServlet.java:1) ~[dotcms_5.2.2_834c945.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.2.2_834c945.jar:?]
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:104) ~[dotcms_5.2.2_834c945.jar:?]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4978) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5290) ~[catalina.jar:8.5.32]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734) ~[catalina.jar:8.5.32]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1140) ~[catalina.jar:8.5.32]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875) ~[catalina.jar:8.5.32]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: org.postgresql.util.PSQLException: 오류: 날짜/시간 필드의 값이 범위를 벗어남: "01/01/1970"
  Hint: 날짜 표현 방식("datestyle")을 다른 것으로 사용하고 있는 듯 합니다.
  Position: 376
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266) ~[postgresql-42.2.2.jar:42.2.2]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:365) ~[tomcat-dbcp.jar:8.5.32]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:365) ~[tomcat-dbcp.jar:8.5.32]
	at com.dotmarketing.common.db.DotConnect.executeStatement(DotConnect.java:251) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotmarketing.startup.runalways.Task00001LoadSchema.executeUpgrade(Task00001LoadSchema.java:92) ~[dotcms_5.2.2_834c945.jar:?]
	... 24 more
03:51:37.921  WARN  lang.System - No Valid License Found : /home/devkim/dotCMS/dotserver/tomcat-8.5.32/webapps/ROOT/dotsecure/license/license.dat
03:51:37.921  INFO  enterprise.LicenseUtil - Setting up default license
03:51:38.006  INFO  startup.StartupTasksExecutor - Not running: Task00002LoadClusterLicenses
03:51:38.007  INFO  startup.StartupTasksExecutor - Running: Task00003CreateSystemRoles
03:51:38.015  INFO  runalways.Task00003CreateSystemRoles - Task not executing seems the roles has not been upgraded yet
com.dotmarketing.exception.DotRuntimeException: org.postgresql.util.PSQLException: 오류: "inode" 이름의 릴레이션(relation)이 없습니다
  Position: 30
	at com.dotmarketing.common.db.DotConnect.getResult(DotConnect.java:280)
	at com.dotmarketing.common.db.DotConnect.getInt(DotConnect.java:84)
	at com.dotmarketing.startup.runalways.Task00004LoadStarter.forceRun(Task00004LoadStarter.java:22)
	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:208)
	at com.liferay.portal.servlet.MainServlet.init_aroundBody0(MainServlet.java:118)
	at com.liferay.portal.servlet.MainServlet$AjcClosure1.run(MainServlet.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29)
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41)
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:104)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4978)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5290)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1140)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: 오류: "inode" 이름의 릴레이션(relation)이 없습니다
  Position: 30
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:224)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:212)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:212)
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:636)
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:522)
	at com.dotmarketing.common.db.DotConnect.getResult(DotConnect.java:276)
	... 26 more
03:51:38.017  ERROR db.DotConnect - getResult(): unable to execute query.  Bad SQL? : select count(*) as test from inode [] 오류: "inode" 이름의 릴레이션(relation)이 없습니다
  Position: 30
org.postgresql.util.PSQLException: 오류: "inode" 이름의 릴레이션(relation)이 없습니다
  Position: 30
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:224) ~[postgresql-42.2.2.jar:42.2.2]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:212) ~[tomcat-dbcp.jar:8.5.32]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:212) ~[tomcat-dbcp.jar:8.5.32]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:636) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:522) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotmarketing.common.db.DotConnect.getResult(DotConnect.java:276) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotmarketing.common.db.DotConnect.getInt(DotConnect.java:84) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotmarketing.startup.runalways.Task00004LoadStarter.forceRun(Task00004LoadStarter.java:22) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:208) ~[dotcms_5.2.2_834c945.jar:?]
	at com.liferay.portal.servlet.MainServlet.init_aroundBody0(MainServlet.java:118) ~[dotcms_5.2.2_834c945.jar:?]
	at com.liferay.portal.servlet.MainServlet$AjcClosure1.run(MainServlet.java:1) ~[dotcms_5.2.2_834c945.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.2.2_834c945.jar:?]
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:104) ~[dotcms_5.2.2_834c945.jar:?]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4978) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5290) ~[catalina.jar:8.5.32]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734) ~[catalina.jar:8.5.32]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1140) ~[catalina.jar:8.5.32]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875) ~[catalina.jar:8.5.32]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
03:51:38.021  FATAL startup.StartupTasksExecutor - Unable to execute the upgrade task : Task00004LoadStarter
com.dotmarketing.exception.DotRuntimeException: org.postgresql.util.PSQLException: 오류: "inode" 이름의 릴레이션(relation)이 없습니다
  Position: 30
	at com.dotmarketing.common.db.DotConnect.getResult(DotConnect.java:280) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotmarketing.common.db.DotConnect.getInt(DotConnect.java:84) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotmarketing.startup.runalways.Task00004LoadStarter.forceRun(Task00004LoadStarter.java:22) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:208) ~[dotcms_5.2.2_834c945.jar:?]
	at com.liferay.portal.servlet.MainServlet.init_aroundBody0(MainServlet.java:118) ~[dotcms_5.2.2_834c945.jar:?]
	at com.liferay.portal.servlet.MainServlet$AjcClosure1.run(MainServlet.java:1) ~[dotcms_5.2.2_834c945.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.2.2_834c945.jar:?]
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:104) ~[dotcms_5.2.2_834c945.jar:?]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4978) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5290) ~[catalina.jar:8.5.32]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734) ~[catalina.jar:8.5.32]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1140) ~[catalina.jar:8.5.32]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875) ~[catalina.jar:8.5.32]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: org.postgresql.util.PSQLException: 오류: "inode" 이름의 릴레이션(relation)이 없습니다
  Position: 30
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:224) ~[postgresql-42.2.2.jar:42.2.2]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:212) ~[tomcat-dbcp.jar:8.5.32]
	at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:212) ~[tomcat-dbcp.jar:8.5.32]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:636) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:522) ~[dotcms_5.2.2_834c945.jar:?]
	at com.dotmarketing.common.db.DotConnect.getResult(DotConnect.java:276) ~[dotcms_5.2.2_834c945.jar:?]
	... 26 more

```

**Comment by wezell** [comment]
@ilbunilcho what does `show datestyle` return for you.  This is what I have.
```
dotcms=#   show datestyle;
 DateStyle
-----------
 ISO, MDY
(1 row)
``` 

Regardless, it looks like a legacy date in the `postgres.sql`, you could change it in that file.

**Comment by ilbunilcho** [comment]
I know datesytle problem.
can change my database's datestyle or postgres.sql to fix this problem but I suggest change query with 'to_timestamp('01/01/1970', 'MM/DD/YYYY')' in postgres.sql
thanks for quick reply

> @ilbunilcho what does `show datestyle` return for you. This is what I have.
> 
> ```
> dotcms=#   show datestyle;
>  DateStyle
> -----------
>  ISO, MDY
> (1 row)
> ```
> 
> Regardless, it looks like a legacy date in the `postgres.sql`, you could change it in that file.

I know datesytle problem.
can change my database's datestyle or postgres.sql to fix this problem but I suggest change query with 'to_timestamp('01/01/1970', 'MM/DD/YYYY')' in postgres.sql
thanks for quick reply
