### ISSUE TITLE
Error when downloading data/assets

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#17887]
### Describe the bug
When you try to download data/assets, we got the following error:

```
14:44:52.314  INFO  business.ESIndexAPI - backupIndex : Trying to backup index: cluster_a9b7ec2dff.working_20200122104252
14:44:52.314  INFO  util.AdminLogger - class com.dotcms.content.elasticsearch.business.ESIndexAPI : backupIndex : Trying to backup index: cluster_a9b7ec2dff.working_20200122104252
14:44:52.330  ERROR action.ViewCMSMaintenanceAction - Index :cluster_a9b7ec2dff.working_20200122104252 does not exist
java.io.IOException: Index :cluster_a9b7ec2dff.working_20200122104252 does not exist
        at com.dotcms.content.elasticsearch.business.ESIndexAPI.backupIndex(ESIndexAPI.java:254) ~[dotcms_5.0.0_ba6a4f9.jar:?]
        at com.dotmarketing.portlets.cmsmaintenance.action.ViewCMSMaintenanceAction.createXMLFiles_aroundBody0(ViewCMSMaintenanceAction.java:893) ~[dotcms_5.0.0_ba6a4f9.jar:?]
```

This is because of the new changes of ES externally, maybe we need to delete these lines https://github.com/dotCMS/core/blob/c4cde0e11782f9840449b962cea5cfeb3d5ede6c/dotCMS/src/main/java/com/dotmarketing/portlets/cmsmaintenance/action/ViewCMSMaintenanceAction.java#L890-L897

**Comment by wezell** [comment]
These lines can be removed - we do not need to ship an index when creating a starter.

**Comment by nollymar** [comment]
**Passed internal QA**. It was already fixed on another task

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
