### ISSUE TITLE
Modifying Plugin Version in MANIFEST.MF displays ERROR log

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#17959]
### Describe the bug
Reproducible in 5.2.4 (latest)
Reported here: https://dotcms.zendesk.com/agent/tickets/100409
### Steps to reproduce the behavior:
1. deploy plugins
2. start dotCMS
3. stop dotCMS
4. undeploy plugins
5. change version in plugins/com.dotcms.config/MANIFEST.MF from 1.0 to 1.1​
6. deploy plugins
7. start dotCMS

check dotcms.log and see this error:
```
[06/02/20 09:03:01:553 CET] ERROR util.JDBCExceptionReporter: Batch entry 0 insert into plugin (plugin_name, plugin_version, author, first_deployed_date, last_deployed_date, id) values ('dotCMS Config', '1.1', 'dotCMS', '2010-06-17 00:00:00-04', '2020-02-06 03:03:01.532-05', 'com.dotcms.config') was aborted: ERROR: duplicate key value violates unique constraint "plugin_pkey"
[06/02/20 09:03:01:553 CET] ERROR util.JDBCExceptionReporter: ERROR: duplicate key value violates unique constraint "plugin_pkey"
[06/02/20 09:03:01:554 CET] ERROR util.JDBCExceptionReporter: Batch entry 0 insert into plugin (plugin_name, plugin_version, author, first_deployed_date, last_deployed_date, id) values ('dotCMS Config', '1.1', 'dotCMS', '2010-06-17 00:00:00-04', '2020-02-06 03:03:01.532-05', 'com.dotcms.config') was aborted: ERROR: duplicate key value violates unique constraint "plugin_pkey"
[06/02/20 09:03:01:554 CET] ERROR util.JDBCExceptionReporter: ERROR: duplicate key value violates unique constraint "plugin_pkey"
Caused by: java.sql.BatchUpdateException: Batch entry 0 insert into plugin (plugin_name, plugin_version, author, first_deployed_date, last_deployed_date, id) values ('dotCMS Config', '1.1', 'dotCMS', '2010-06-17 00:00:00-04', '2020-02-06 03:03:01.532-05', 'com.dotcms.config') was aborted: ERROR: duplicate key value violates unique constraint "plugin_pkey"
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "plugin_pkey"
```
### Expected behavior
No errors in the log.

**Comment by zlymeda** [comment]
> **Important: This doesn't prevent the plugin to be deployed correctly**

This is not true. Configuration files are deployed, that is true. But any hooks are not registered due to this failure.

This is critical because after every release (thus version change) we have to manually remove the plugin from Postgres before we can run dotCMS.

**Comment by zlymeda** [comment]
PluginLoader.java:

```java
try{
    pluginAPI.save(plugin);
} catch (DotDataException e2) {
    Logger.fatal(this, "Method loadPlugins : Error deploying plugin id:" + id, e2);
    continue;  // << ---- skips the plugin
}

// ....

// these lines are not executed
setUpHooks(id);
pluginIds.add(id);
pluginAPI.setDeployedPluginOrder(pluginIds);
pluginAPI.loadBackEndFiles(plugin.getId());

```

**Comment by fabrizzio-dotCMS** [comment]
This is a hotfix from motiv-solutions
Honestly, I wasn't able to reproduce the issue with the original code. It seems ok. But I also tested the scenario with this fix in place and it also works fine. I'll leave it to QA to decide whether or not this needs to be included.

**Comment by fabrizzio-dotCMS** [comment]
Note for QA:
I think we need to test against any branch lacking this "fix" to validate if you see this happening or not.
I wasn't able to reproduce the error.  However, I am providing  PR with the fix from motiv-solutions. I tested that code and it also works. 
Once again please validate if this doesn't happen without having incorporated the code provided in the PR.

**Comment by nollymar** [comment]
**Internal QA:** Passed

I was able to reproduce the issue in 21.09:

```
Caused by: java.sql.BatchUpdateException: Batch entry 0 insert into plugin (plugin_name, plugin_version, author, first_deployed_date, last_deployed_date, id) values ('dotCMS Config', '1.1', 'dotCMS', '2021-09-10 16:39:03.909-05', '2021-09-10 16:42:08.364-05', 'com.dotcms.config') was aborted: ERROR: duplicate key value violates unique constraint "plugin_pkey"
  Detail: Key (id)=(com.dotcms.config) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148) ~[postgresql-42.2.8.jar:42.2.8]
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50) ~[postgresql-42.2.8.jar:42.2.8]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2234) ~[postgresql-42.2.8.jar:42.2.8]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:510) ~[postgresql-42.2.8.jar:42.2.8]
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:853) ~[postgresql-42.2.8.jar:42.2.8]
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1546) ~[postgresql-42.2.8.jar:42.2.8]
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[HikariCP-3.4.2.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.2.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.impl.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:54) ~[dot.hibernate-2.1.7_3.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.impl.BatcherImpl.executeBatch(BatcherImpl.java:128) ~[dot.hibernate-2.1.7_3.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.executeAll(SessionImpl.java:2438) ~[dot.hibernate-2.1.7_3.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.execute(SessionImpl.java:2392) ~[dot.hibernate-2.1.7_3.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.flush(SessionImpl.java:2261) ~[dot.hibernate-2.1.7_3.jar:?]
	at com.dotmarketing.db.HibernateUtil.saveOrUpdate(HibernateUtil.java:547) ~[dotcms_21.09_65bcb25.jar:?]
	... 55 more
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "plugin_pkey"
  Detail: Key (id)=(com.dotcms.config) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497) ~[postgresql-42.2.8.jar:42.2.8]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233) ~[postgresql-42.2.8.jar:42.2.8]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:510) ~[postgresql-42.2.8.jar:42.2.8]
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:853) ~[postgresql-42.2.8.jar:42.2.8]
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1546) ~[postgresql-42.2.8.jar:42.2.8]
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[HikariCP-3.4.2.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.2.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.impl.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:54) ~[dot.hibernate-2.1.7_3.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.impl.BatcherImpl.executeBatch(BatcherImpl.java:128) ~[dot.hibernate-2.1.7_3.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.executeAll(SessionImpl.java:2438) ~[dot.hibernate-2.1.7_3.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.execute(SessionImpl.java:2392) ~[dot.hibernate-2.1.7_3.jar:?]
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.flush(SessionImpl.java:2261) ~[dot.hibernate-2.1.7_3.jar:?]
	at com.dotmarketing.db.HibernateUtil.saveOrUpdate(HibernateUtil.java:547) ~[dotcms_21.09_65bcb25.jar:?]
```

However, with the fix provided it is working successfully.

**Steps to reproduce it:** 
1. Ask me for jars plugin-com.dotcms.config-1.0.jar and plugin-com.dotcms.config-1.1.jar
2. Using a fresh installation, copy (or replace if exists) the file `plugin-com.dotcms.config-1.0.jar` under `WEB-INF/lib` and rename it to: `plugin-com.dotcms.config.jar`
2. Start the server up
3. Shutdown the server
4. Replace the file `WEB-INF/lib/plugin-com.dotcms.config.jar` with this one `plugin-com.dotcms.config-1.1.jar` (do not forget to rename it)
5. Start the server again

**Comment by bryanboza** [comment]
Fixed, tested with the provided jars and now I'm unable to reproduce, tested on release-21.10
