### ISSUE TITLE
SiteSearch - items not removed from sitesearch index after unpublish/archive - 5.x

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#17976]
### Describe the bug
Unpublishing and/or archiving items does not remove them from a SiteSearch index.

### Steps to reproduce the behavior:

Recreated on demo.dotcms.com

1. Create new page(s)
2. Create new (non-incremental) SiteSearch index
3. Search for you new content - it should be there
4. Unpublish your content
5. Run SiteSearch reindex Job 
6. Search your SiteSearch

Content is still found

7. Archive your content
8. Run SiteSearch reindex Job 
9. Search your SiteSearch

### Expected behavior
Content should be removed from SiteSearch index.

### Actual behavior
Content is still found

### Screenshots
**Create new content**
![image](https://user-images.githubusercontent.com/49727631/74267723-3a195700-4ccc-11ea-8869-32600bd2e57f.png)

**Create new SiteSearch index (newIndex)**
![image](https://user-images.githubusercontent.com/49727631/74267651-10603000-4ccc-11ea-962f-2c9a433520aa.png)

**Search SiteSearch Index**
![image](https://user-images.githubusercontent.com/49727631/74267775-56b58f00-4ccc-11ea-98ca-8a2d284d2355.png)

**Unpublish/Archive Content**
![image](https://user-images.githubusercontent.com/49727631/74267747-4a313680-4ccc-11ea-9d94-d6fe17552c8a.png)

**Run SiteSearch job on your new index**
![image](https://user-images.githubusercontent.com/49727631/74267359-887a2600-4ccb-11ea-8dfe-d8ccff446315.png)

**Search SiteSearch index... Content is still there**

![image](https://user-images.githubusercontent.com/49727631/74267934-95e3e000-4ccc-11ea-8c6e-2503a244f489.png)

### Desktop (please complete the following information):
 - OS: n/a
 - Browser Chrome / FF
 - Version dotCMS 5.x

**Comment by wezell** [comment]
`working` or `archived` content should be removed from sitesearch indexes in both incremental and non-incremental site search jobs.

`deleted` content should only be removed from non-incremental site search jobs

**Comment by wezell** [comment]
## Incremental + New Index
- Create a new index
- Copy the already generated bundle
- Pull changed content based on last index date
  - Live / Working / Archived
     - Publish Live
     - Delete Working and Archived from index
- change default alias to new Index

## Incremental + Old Index
- Pull changed content based on last index date
  - Live / Working / Archived
     - Publish Live into index
     - Delete Working and Archived from index

Non-Incremental + New Index
- Create a new index
- generate bundle
  - Live 
     - Publish Live
- change alias to new Index

Non-Incremental + Old Index
- Create a new index
- generate bundle
  - Live 
     - Publish Live
- Delete old index
- Change alias to old Index



Non-Incremental + Existing Index

**Comment by jgambarios** [comment]
PR:
https://github.com/dotCMS/core/pull/18071
https://github.com/dotCMS/enterprise-2.x/pull/705

**Comment by jgambarios** [comment]
We found a couple of cases that need to be handle:

1. Incremental and no incremental jobs are not indexing non default language pages:
   * Create a new folder
   * Add a page in English and add content to that page
   * Create the Spanish version of that page and make sure the content inside the page also have spanish versions.
   * Run a site search job
   * Check the generated bundle, the spanish version of the page have no spanish content on it.

2. No incremental jobs uses a timestamp for the folder name, like for example: `2020-03-11_11-45-00`, if two or more non incremental jobs run at the same time, like for example every day at 3am they will "share" the same folder creating inconsistencies in the bundle data.

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/18141
https://github.com/dotCMS/enterprise-2.x/pull/710

**Comment by jgambarios** [comment]
Getting an error executing `Run Now` jobs:

1. Create a Run Now job with a new index Alias
2. Wait the job to finish
3. Create a new Run Now job reusing the same index Alias

We have these errors in logs:
https://gist.github.com/jgambarios/d3cee10b26098c0186c34a2fb9ebb2cd#file-gistfile1-txt-L586-L823

**Comment by fabrizzio-dotCMS** [comment]
This is a minor thing that is happening due to the fix I recently introduced to solve the multi-thread alias getting lost problem. It's just a matter of removing the '(Default)'  part of the alias name. Which is saved in the job params.  I'll get a fix for it shortly.

**Comment by fabrizzio-dotCMS** [comment]
I added an extra validation to ensure that new index names (input by the user) are compliant with the restrictions enforced by ES name wise.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/18170

**Comment by jgambarios** [comment]
### Content not found
1. Create a new Rich text content en english and spanish:
  **English:** 
  Title: Hello content
  Body: Hi, my name is Vlad Tepes (evil laugh)
  **Spanish:** 
  Title: Hola content
  Body: Hola, mi nombre es Juana de Arco

2. Create a new folder "folder1"
3. Create a page just in English "page1" and add the created rich content to the page

4. ` Dev Tools -> Site Search -> Job Scheduler`
Run now (But is the same result for incremental and no incremental scheculed jobs) selecting both languages

5. `Dev Tools -> Site Search -> Search `
Look for "vlad" -> **Nothing is found**
Look for "juana" -> **Page is found**


---
---

### Error in jsp in `Job Audit Data`
1. `Dev Tools -> Site Search -> Job Scheduler`
Non incremental, selecting both languages, running each 5mins 0 0/5 * 1/1 * ? *

2. `Dev Tools -> Site Search -> Job Scheduler`
Incremental, selecting both languages, running each 5mins 0 0/5 * 1/1 * ? *

3. Wait to finish at least two runs

4. `Dev Tools -> Site Search -> Job Audit Data`, try with both indexes, sometimes fails with the incremental, sometimes with the non incremental

``` java
15:32:25.355  ERROR lang.Class - An exception occurred processing JSP page [/html/portlet/ext/sitesearch/site_search_audit.jsp] at line [63]

60:         StringBuilder hostList=new StringBuilder();
61:         for(String hid : a.getHostList().split(",")) {
62:             if(UtilMethods.isSet(hid))
63:                 hostList.append(APILocator.getHostAPI().find(hid, APILocator.getUserAPI().getSystemUser(), false).getHostname())
64:                         .append("  ");
65:         }
66:         StringBuilder langList=new StringBuilder();


Stacktrace:
org.apache.jasper.JasperException: An exception occurred processing JSP page [/html/portlet/ext/sitesearch/site_search_audit.jsp] at line [63]

60:         StringBuilder hostList=new StringBuilder();
61:         for(String hid : a.getHostList().split(",")) {
62:             if(UtilMethods.isSet(hid))
63:                 hostList.append(APILocator.getHostAPI().find(hid, APILocator.getUserAPI().getSystemUser(), false).getHostname())
64:                         .append("  ");
65:         }
66:         StringBuilder langList=new StringBuilder();


Stacktrace:
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:584) ~[jasper.jar:8.5.32]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:481) ~[jasper.jar:8.5.32]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386) ~[jasper.jar:8.5.32]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330) ~[jasper.jar:8.5.32]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.CMSFilter.doFilterInternal(CMSFilter.java:191) ~[classes/:?]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:47) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:104) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:399) ~[urlrewritefilter-4.0.4.jar:4.0.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:134) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:88) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:48) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:99) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.NormalizationFilter.doFilter(NormalizationFilter.java:44) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[catalina.jar:8.5.32]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) ~[catalina.jar:8.5.32]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[catalina.jar:8.5.32]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[catalina.jar:8.5.32]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) ~[catalina.jar:8.5.32]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:8.5.32]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.32]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at org.apache.jsp.html.portlet.ext.sitesearch.site_005fsearch_005faudit_jsp._jspService(site_005fsearch_005faudit_jsp.java:599) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:8.5.32]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443) ~[jasper.jar:8.5.32]
	... 59 more
```

**Comment by fabrizzio-dotCMS** [comment]
:confused:

**Comment by jgambarios** [comment]
Latest found issues will be handle in https://github.com/dotCMS/core/issues/18194

**Comment by bryanboza** [comment]
Fixed, some new cards reported as enhancements... 

Tested on release-5.2.8 // Postgres // FF

**Comment by nollymar** [comment]
Additional PR to support larger index names: https://github.com/dotCMS/core/pull/18269
