### ISSUE TITLE
OSGi extension fragments don't work for JBoss 6.4

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#18004]
Reported via Support: [Zendesk-100478](https://dotcms.zendesk.com/agent/tickets/100478)
Reproducible in dotCMS 5.2.5

dotCMS dynamic plugins can use extension fragment bundles to export libraries required by the java code included in the plugins, as explained here:

https://dotcms.com/docs/latest/fragment-exported-packages-plugin#fragment-bundles

However extension fragments are not working on JBoss EAP 6.4.

### Steps to reproduce the behavior:
1. Set up JBoss EAP 6.4 to run dotCMS as explained in our official documentation:
https://dotcms.com/docs/latest/deploy-as-a-war-in-jboss-eap-6-4
2. Start dotCMS on JBoss
3. Compile the sample plugin 'com.dotcms.custom.spring' that is in the 'plugin-seeds' repository
https://github.com/dotCMS/plugin-seeds/tree/master/OSGi/com.dotcms.custom.spring
4. Go to 'Dev Tools -> Plugin' portlet in dotCMS backend, and deploy the generated fragment bundle: 'com.dotcms.custom.spring.fragment-0.2.jar'
5. The fragment bundle fails to deploy, and the following message shows in JBoss server log:
```
14:43:30,802 INFO  [stdout] (fileinstall-/Users/danielsolis/dev/jboss-eap-6.4/standalone/deployments/ROOT.war/WEB-INF/felix/load) Installing bundle com.dotcms.custom.spring.fragment / 0.2.0
14:43:30,810 INFO  [stdout] (fileinstall-/Users/danielsolis/dev/jboss-eap-6.4/standalone/deployments/ROOT.war/WEB-INF/felix/load) Failed to install artifact: /Users/danielsolis/dev/jboss-eap-6.4/standalone/deployments/ROOT.war/WEB-INF/felix/load/com.dotcms.custom.spring.fragment-0.2.jar: org.osgi.framework.BundleException: Could not create bundle object.
14:43:30,810 INFO  [stdout] (fileinstall-/Users/danielsolis/dev/jboss-eap-6.4/standalone/deployments/ROOT.war/WEB-INF/felix/load) org.osgi.framework.BundleException: Could not create bundle object.
14:43:30,811 INFO  [stdout] (fileinstall-/Users/danielsolis/dev/jboss-eap-6.4/standalone/deployments/ROOT.war/WEB-INF/felix/load) 	at org.apache.felix.framework.Felix.installBundle(Felix.java:3095)
14:43:30,811 INFO  [stdout] (fileinstall-/Users/danielsolis/dev/jboss-eap-6.4/standalone/deployments/ROOT.war/WEB-INF/felix/load) 	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:167)
14:43:30,811 INFO  [stdout] (fileinstall-/Users/danielsolis/dev/jboss-eap-6.4/standalone/deployments/ROOT.war/WEB-INF/felix/load) 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.installOrUpdateBundle(DirectoryWatcher.java:1037)
14:43:30,811 INFO  [stdout] (fileinstall-/Users/danielsolis/dev/jboss-eap-6.4/standalone/deployments/ROOT.war/WEB-INF/felix/load) 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.install(DirectoryWatcher.java:963)
14:43:30,811 INFO  [stdout] (fileinstall-/Users/danielsolis/dev/jboss-eap-6.4/standalone/deployments/ROOT.war/WEB-INF/felix/load) 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.install(DirectoryWatcher.java:884)
14:43:30,811 INFO  [stdout] (fileinstall-/Users/danielsolis/dev/jboss-eap-6.4/standalone/deployments/ROOT.war/WEB-INF/felix/load) 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:489)
14:43:30,811 INFO  [stdout] (fileinstall-/Users/danielsolis/dev/jboss-eap-6.4/standalone/deployments/ROOT.war/WEB-INF/felix/load) 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
14:43:30,811 INFO  [stdout] (fileinstall-/Users/danielsolis/dev/jboss-eap-6.4/standalone/deployments/ROOT.war/WEB-INF/felix/load) 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
14:43:30,812 INFO  [stdout] (fileinstall-/Users/danielsolis/dev/jboss-eap-6.4/standalone/deployments/ROOT.war/WEB-INF/felix/load) Caused by: java.lang.UnsupportedOperationException: Unable to add extension bundle.
14:43:30,812 INFO  [stdout] (fileinstall-/Users/danielsolis/dev/jboss-eap-6.4/standalone/deployments/ROOT.war/WEB-INF/felix/load) 	at org.apache.felix.framework.ExtensionManager.addExtensionBundle(ExtensionManager.java:439)
14:43:30,812 INFO  [stdout] (fileinstall-/Users/danielsolis/dev/jboss-eap-6.4/standalone/deployments/ROOT.war/WEB-INF/felix/load) 	at org.apache.felix.framework.Felix.installBundle(Felix.java:3061)
14:43:30,812 INFO  [stdout] (fileinstall-/Users/danielsolis/dev/jboss-eap-6.4/standalone/deployments/ROOT.war/WEB-INF/felix/load) 	... 7 more
```
### Expected behavior
Extension bundle fragments should work on OSGI framework included by dotCMS.

### Additional context
This has been reported by customer via Support: Ticket [100277](https://dotcms.zendesk.com/agent/tickets/100478).

**Comment by wezell** [comment]
@dsolistorres this is a known issue and is called out in our requirements doc:
https://dotcms.com/docs/latest/requirements

**Comment by dsolistorres** [comment]
Got it, I'm closing this issue, thanks
