### ISSUE TITLE
[BUG] 5.2.x: URL Map Patterns: Fields containing forward slash results in 404.

### ISSUE THREAD

**Issue by x0rsw1tch** [dotCMS/core#18015]
Greetings

Since upgrading from 3.6.2 (3.6.2 > 4.3.3 > 5.0.3 > 5.1.6) to 5.2.5, we have discovered an issue with the query builder, causing URL Mapped content pages to 404 when there is forward-slash in one of the fields. As an example, I have provided some detail using the demo site to replicate the bug.

Given this Content Type:

![image](https://user-images.githubusercontent.com/9543257/74863003-23ea4700-531b-11ea-9548-dd2c62b4e0e9.png)

Properties:

![image](https://user-images.githubusercontent.com/9543257/74863020-2d73af00-531b-11ea-929f-ff6dc7e4fc08.png)

Detail Page has a simple widget with the following code:

```
#if ($UtilMethods.isSet($URLMapContent))
  <h1>We have Content</h1>
  <h2>$URLMapContent.identifier</h2>
  <h2>$URLMapContent.title</h2>
#else
  <h1>FAIL!</h1>
#end
```

From here, I created two Contentlets, one with thePrefix containing a forward-slash, and one without:
![image](https://user-images.githubusercontent.com/9543257/74863120-55631280-531b-11ea-8ba2-7316eb65ca03.png)

### Expected behavior
When navigating to `/has/slash/testurlmap/stuff` or `/no-slash/testurlmap/stuff`, the correct page/content displays.

### Actual behavior
Navigating to `/has/slash/testurlmap/stuff` results in a 404.
Navigating to `/no-slash/testurlmap/stuff` works as intended.

Windows 10 x64
Chrome v80
dotCMS Release 5.2.5 Postgres 9.6

### Additional context

- While this URL Map may look a bit unusual, this is a just simplified representation of the client's actual URL Map pattern, which is configured with a field mapped to root level, a static 2nd level, and another mapped field on the 3rd level.
- Upon navigation to the URI containing the forward-slash in the path, an exception is thrown:

```
[19/02/20 13:28:08:508 EST]  WARN business.ESContentFactoryImpl: ----------------------------------------------
[19/02/20 13:28:08:508 EST]  WARN business.ESContentFactoryImpl: ----------------------------------------------
[19/02/20 13:28:08:508 EST]  WARN business.ESContentFactoryImpl: Elasticsearch Index Error : working_20200219125525
[19/02/20 13:28:08:508 EST]  WARN business.ESContentFactoryImpl: Elasticsearch Index Error : working_20200219125525
[19/02/20 13:28:08:508 EST]  WARN business.ESContentFactoryImpl: all shards failed
[19/02/20 13:28:08:508 EST]  WARN business.ESContentFactoryImpl: all shards failed
[19/02/20 13:28:08:508 EST] DEBUG business.ESContentFactoryImpl: all shards failed
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:274) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:132) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:243) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:107) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.InitialSearchPhase.access$100(InitialSearchPhase.java:49) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.InitialSearchPhase$2.lambda$onFailure$1(InitialSearchPhase.java:217) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:171) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.InitialSearchPhase.access$000(InitialSearchPhase.java:49) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.InitialSearchPhase$2.onFailure(InitialSearchPhase.java:217) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:531) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1056) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1149) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1133) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:66) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.SearchTransportService$6$1.onFailure(SearchTransportService.java:389) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService$2.onFailure(SearchService.java:318) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:312) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:306) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:996) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.3.jar:6.1.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: org.elasticsearch.index.query.QueryShardException: Failed to parse query [+structurename:testurlmapct +deleted:false +working:true +testurlmapct.urltitle_dotraw:has\\/slash +testurlmapct.urlsuffix_dotraw:stuff +languageid:1]
        at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:1024) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:304) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:316) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:303) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:705) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:552) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:528) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:324) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:310) ~[elasticsearch-6.1.3.jar:6.1.3]
        ... 9 more
Caused by: org.apache.lucene.queryparser.classic.ParseException: Cannot parse '+structurename:testurlmapct +deleted:false +working:true +testurlmapct.urltitle_dotraw:has\\/slash +testurlmapct.urlsuffix_dotraw:stuff +languageid:1': Lexical error at line 1, column 150.  Encountered: <EOF> after : "/slash +testurlmapct.urlsuffix_dotraw:stuff +languageid:1"
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:114) ~[lucene-queryparser-7.1.0.jar:6.1.3]
        at org.elasticsearch.index.search.QueryStringQueryParser.parse(QueryStringQueryParser.java:777) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:1022) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:304) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:316) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:303) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:705) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:552) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:528) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:324) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:310) ~[elasticsearch-6.1.3.jar:6.1.3]
        ... 9 more
Caused by: org.apache.lucene.queryparser.classic.TokenMgrError: Lexical error at line 1, column 150.  Encountered: <EOF> after : "/slash +testurlmapct.urlsuffix_dotraw:stuff +languageid:1"
        at org.apache.lucene.queryparser.classic.QueryParserTokenManager.getNextToken(QueryParserTokenManager.java:1119) ~[lucene-queryparser-7.1.0.jar:6.1.3]
        at org.apache.lucene.queryparser.classic.QueryParser.jj_ntk(QueryParser.java:861) ~[lucene-queryparser-7.1.0.jar:6.1.3]
        at org.apache.lucene.queryparser.classic.QueryParser.Term(QueryParser.java:429) ~[lucene-queryparser-7.1.0.jar:6.1.3]
        at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:355) ~[lucene-queryparser-7.1.0.jar:6.1.3]
        at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:303) ~[lucene-queryparser-7.1.0.jar:6.1.3]
        at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:215) ~[lucene-queryparser-7.1.0.jar:6.1.3]
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:109) ~[lucene-queryparser-7.1.0.jar:6.1.3]
        at org.elasticsearch.index.search.QueryStringQueryParser.parse(QueryStringQueryParser.java:777) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:1022) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:304) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:316) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:303) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:705) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:552) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:528) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:324) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:310) ~[elasticsearch-6.1.3.jar:6.1.3]
        ... 9 more
[19/02/20 13:28:08:508 EST] DEBUG business.ESContentFactoryImpl: all shards failed
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:274) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:132) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:243) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:107) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.InitialSearchPhase.access$100(InitialSearchPhase.java:49) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.InitialSearchPhase$2.lambda$onFailure$1(InitialSearchPhase.java:217) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:171) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.InitialSearchPhase.access$000(InitialSearchPhase.java:49) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.InitialSearchPhase$2.onFailure(InitialSearchPhase.java:217) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:531) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1056) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1149) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1133) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:66) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.action.search.SearchTransportService$6$1.onFailure(SearchTransportService.java:389) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService$2.onFailure(SearchService.java:318) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:312) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:306) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:996) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.3.jar:6.1.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: org.elasticsearch.index.query.QueryShardException: Failed to parse query [+structurename:testurlmapct +deleted:false +working:true +testurlmapct.urltitle_dotraw:has\\/slash +testurlmapct.urlsuffix_dotraw:stuff +languageid:1]
        at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:1024) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:304) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:316) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:303) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:705) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:552) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:528) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:324) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:310) ~[elasticsearch-6.1.3.jar:6.1.3]
        ... 9 more
Caused by: org.apache.lucene.queryparser.classic.ParseException: Cannot parse '+structurename:testurlmapct +deleted:false +working:true +testurlmapct.urltitle_dotraw:has\\/slash +testurlmapct.urlsuffix_dotraw:stuff +languageid:1': Lexical error at line 1, column 150.  Encountered: <EOF> after : "/slash +testurlmapct.urlsuffix_dotraw:stuff +languageid:1"
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:114) ~[lucene-queryparser-7.1.0.jar:6.1.3]
        at org.elasticsearch.index.search.QueryStringQueryParser.parse(QueryStringQueryParser.java:777) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:1022) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:304) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:316) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:303) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:705) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:552) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:528) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:324) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:310) ~[elasticsearch-6.1.3.jar:6.1.3]
        ... 9 more
Caused by: org.apache.lucene.queryparser.classic.TokenMgrError: Lexical error at line 1, column 150.  Encountered: <EOF> after : "/slash +testurlmapct.urlsuffix_dotraw:stuff +languageid:1"
        at org.apache.lucene.queryparser.classic.QueryParserTokenManager.getNextToken(QueryParserTokenManager.java:1119) ~[lucene-queryparser-7.1.0.jar:6.1.3]
        at org.apache.lucene.queryparser.classic.QueryParser.jj_ntk(QueryParser.java:861) ~[lucene-queryparser-7.1.0.jar:6.1.3]
        at org.apache.lucene.queryparser.classic.QueryParser.Term(QueryParser.java:429) ~[lucene-queryparser-7.1.0.jar:6.1.3]
        at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:355) ~[lucene-queryparser-7.1.0.jar:6.1.3]
        at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:303) ~[lucene-queryparser-7.1.0.jar:6.1.3]
        at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:215) ~[lucene-queryparser-7.1.0.jar:6.1.3]
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:109) ~[lucene-queryparser-7.1.0.jar:6.1.3]
        at org.elasticsearch.index.search.QueryStringQueryParser.parse(QueryStringQueryParser.java:777) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:1022) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:304) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:316) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:303) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:705) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:552) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:528) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:324) ~[elasticsearch-6.1.3.jar:6.1.3]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:310) ~[elasticsearch-6.1.3.jar:6.1.3]
        ... 9 more
[19/02/20 13:28:08:508 EST]  WARN business.ESContentFactoryImpl: ----------------------------------------------
[19/02/20 13:28:08:508 EST]  WARN business.ESContentFactoryImpl: ----------------------------------------------
```

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/18135

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after upgrade to master
