### ISSUE TITLE
[Roles] Cannot delete Role that is currently involved in Workflow Task

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#18136]
Reported via Support: [100739](https://dotcms.zendesk.com/agent/tickets/100739)
Reproducible in dotCMS 5.2.5, 5.2.7, and latest master.

The system is not allowing users to delete Roles that are currently involved in a pending Workflow Task. An exception is displayed in the log.

## Steps to Reproduce
1. Go to **Control Panel > Roles & Tools > expand Publisher / Legal > click Reviewer**, and create a new Role called `Test Role`.
2. Assign all the required permissions to the demo.dotcms.com Site.
3. Go to **Content Model > Workflows > System Workflow > click the Save sub-action in the New step** . Now, go to **Comments-and-Assigns > click User can Assign > select Test Role**, and click **Save**.
4. Go to **Site > Browser** and create a new page. When you click **Save**, select the Test Role in the Assignee dropdown.
5. Finally, try to delete the Test Role. You'll see the following Java Stack Trace:
```
[13/03/20 17:05:20:088 GMT] INFO caffine.CaffineCache: *** Building Cache : dotcmsrootrolescache, size:1000,Concurrency:32
[13/03/20 17:05:20:089 GMT] INFO business.RoleFactoryImpl: save : Role saved Id :fdcaa62b-b587-490e-bd4f-08a64bc8ceae
[13/03/20 17:05:20:089 GMT] INFO util.AdminLogger: class com.dotmarketing.business.RoleFactoryImpl : save : Role saved Id :fdcaa62b-b587-490e-bd4f-08a64bc8ceae
[13/03/20 17:05:20:093 GMT] INFO util.SecurityLogger: class com.dotmarketing.business.RoleAPIImpl : Deleting role:'Test Role' Role{id='fdcaa62b-b587-490e-bd4f-08a64bc8ceae', name='Test Role', description='', roleKey='null', DBFQN='02ae46fa-cb67-4ed8-82d5-f1f9a5e1d744 --> e36988eb-f206-4fd3-a06c-6a746d30a772 --> fdcaa62b-b587-490e-bd4f-08a64bc8ceae', FQN='Publisher / Legal --> Reviewer --> Test Role', parent='e36988eb-f206-4fd3-a06c-6a746d30a772', editPermissions=true, editUsers=true, editLayouts=true, locked=false, system=false} -- ip:186.15.157.179,user:Admin User [ID: dotcms.org.1][email:admin@dotcms.com]
[13/03/20 17:05:20:096 GMT] WARN util.JDBCExceptionReporter: SQL Error: 0, SQLState: 23503
[13/03/20 17:05:20:096 GMT] ERROR util.JDBCExceptionReporter: Batch entry 0 delete from cms_role where id='fdcaa62b-b587-490e-bd4f-08a64bc8ceae' was aborted: ERROR: update or delete on table "cms_role" violates foreign key constraint "workflow_action_next_assign_fkey" on table "workflow_action"
Detail: Key (id)=(fdcaa62b-b587-490e-bd4f-08a64bc8ceae) is still referenced from table "workflow_action". Call getNextException to see other errors in the batch.
[13/03/20 17:05:20:096 GMT] WARN util.JDBCExceptionReporter: SQL Error: 0, SQLState: 23503
[13/03/20 17:05:20:096 GMT] ERROR util.JDBCExceptionReporter: ERROR: update or delete on table "cms_role" violates foreign key constraint "workflow_action_next_assign_fkey" on table "workflow_action"
Detail: Key (id)=(fdcaa62b-b587-490e-bd4f-08a64bc8ceae) is still referenced from table "workflow_action".
[13/03/20 17:05:20:099 GMT] WARN util.JDBCExceptionReporter: SQL Error: 0, SQLState: 23503
[13/03/20 17:05:20:099 GMT] ERROR util.JDBCExceptionReporter: Batch entry 0 delete from cms_role where id='fdcaa62b-b587-490e-bd4f-08a64bc8ceae' was aborted: ERROR: update or delete on table "cms_role" violates foreign key constraint "workflow_action_next_assign_fkey" on table "workflow_action"
Detail: Key (id)=(fdcaa62b-b587-490e-bd4f-08a64bc8ceae) is still referenced from table "workflow_action". Call getNextException to see other errors in the batch.
[13/03/20 17:05:20:100 GMT] WARN util.JDBCExceptionReporter: SQL Error: 0, SQLState: 23503
[13/03/20 17:05:20:100 GMT] ERROR util.JDBCExceptionReporter: ERROR: update or delete on table "cms_role" violates foreign key constraint "workflow_action_next_assign_fkey" on table "workflow_action"
Detail: Key (id)=(fdcaa62b-b587-490e-bd4f-08a64bc8ceae) is still referenced from table "workflow_action".
[13/03/20 17:05:20:100 GMT] ERROR impl.SessionImpl: Could not synchronize database state with session
[13/03/20 17:05:20:104 GMT] ERROR business.RoleAPIImpl: Error deleting Role: Test Role
com.dotmarketing.exception.DotHibernateException: Error deleting object Could not execute JDBC batch update
at com.dotmarketing.db.HibernateUtil.delete(HibernateUtil.java:236) ~[dotcms_5.2.7_9cb2e09.jar:?]
at com.dotmarketing.business.RoleFactoryImpl.delete(RoleFactoryImpl.java:372) ~[dotcms_5.2.7_9cb2e09.jar:?]
at com.dotmarketing.business.RoleAPIImpl.delete_aroundBody10(RoleAPIImpl.java:175) ~[dotcms_5.2.7_9cb2e09.jar:?]
at com.dotmarketing.business.RoleAPIImpl$AjcClosure11.run(RoleAPIImpl.java:1) ~[dotcms_5.2.7_9cb2e09.jar:?]
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.2.7_9cb2e09.jar:?]
at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:59) ~[dotcms_5.2.7_9cb2e09.jar:?]
at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_5.2.7_9cb2e09.jar:?]
at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_5.2.7_9cb2e09.jar:?]
at com.dotmarketing.business.RoleAPIImpl.delete(RoleAPIImpl.java:139) ~[dotcms_5.2.7_9cb2e09.jar:?]
at com.dotmarketing.business.ajax.RoleAjax.deleteRole(RoleAjax.java:403) ~[dotcms_5.2.7_9cb2e09.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule$1.doFilter(CreatorModule.java:229) ~[dot.dwr-3rc2modified_3.jar:?]
at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule.executeMethod(CreatorModule.java:241) ~[dot.dwr-3rc2modified_3.jar:?]
at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:379) ~[dot.dwr-3rc2modified_3.jar:?]
at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:332) ~[dot.dwr-3rc2modified_3.jar:?]
at com.dotcms.repackage.org.directwebremoting.dwrp.BaseCallHandler.handle(BaseCallHandler.java:104) ~[dot.dwr-3rc2modified_3.jar:?]
at com.dotcms.repackage.org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:120) ~[dot.dwr-3rc2modified_3.jar:?]
at com.dotcms.repackage.org.directwebremoting.servlet.DwrServlet.doPost(DwrServlet.java:141) ~[dot.dwr-3rc2modified_3.jar:?]
at com.dotmarketing.servlets.DwrWrapperServlet.doPost(DwrWrapperServlet.java:60) ~[dotcms_5.2.7_9cb2e09.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) ~[servlet-api.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotmarketing.filters.CMSFilter.doFilterInternal(CMSFilter.java:191) ~[dotcms_5.2.7_9cb2e09.jar:?]
at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:47) ~[dotcms_5.2.7_9cb2e09.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_5.2.7_9cb2e09.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_5.2.7_9cb2e09.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:104) ~[dotcms_5.2.7_9cb2e09.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:399) ~[urlrewritefilter-4.0.4.jar:4.0.4]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:134) ~[dotcms_5.2.7_9cb2e09.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:88) ~[dotcms_5.2.7_9cb2e09.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:48) ~[dotcms_5.2.7_9cb2e09.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:99) ~[dotcms_5.2.7_9cb2e09.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_5.2.7_9cb2e09.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotcms.filters.NormalizationFilter.doFilter(NormalizationFilter.java:44) ~[dotcms_5.2.7_9cb2e09.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[catalina.jar:8.5.32]
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) ~[catalina.jar:8.5.32]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[catalina.jar:8.5.32]
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) ~[catalina.jar:8.5.32]
at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:685) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[catalina.jar:8.5.32]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) ~[catalina.jar:8.5.32]
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) ~[tomcat-coyote.jar:8.5.32]
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-coyote.jar:8.5.32]
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800) ~[tomcat-coyote.jar:8.5.32]
at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1699) ~[tomcat-coyote.jar:8.5.32]
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:8.5.32]
at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1050) ~[tomcat-coyote.jar:8.5.32]
at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$4.completed(Nio2Endpoint.java:630) ~[tomcat-coyote.jar:8.5.32]
at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$4.completed(Nio2Endpoint.java:608) ~[tomcat-coyote.jar:8.5.32]
at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126) ~[?:1.8.0_212]
at sun.nio.ch.Invoker$2.run(Invoker.java:218) ~[?:1.8.0_212]
at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112) ~[?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: com.dotcms.repackage.net.sf.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
at com.dotcms.repackage.net.sf.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:62) ~[dot.hibernate-2.1.7_3.jar:?]
at com.dotcms.repackage.net.sf.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:29) ~[dot.hibernate-2.1.7_3.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.BatcherImpl.convert(BatcherImpl.java:328) ~[dot.hibernate-2.1.7_3.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.BatcherImpl.executeBatch(BatcherImpl.java:135) ~[dot.hibernate-2.1.7_3.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.executeAll(SessionImpl.java:2438) ~[dot.hibernate-2.1.7_3.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.execute(SessionImpl.java:2397) ~[dot.hibernate-2.1.7_3.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.flush(SessionImpl.java:2261) ~[dot.hibernate-2.1.7_3.jar:?]
at com.dotmarketing.db.HibernateUtil.delete(HibernateUtil.java:234) ~[dotcms_5.2.7_9cb2e09.jar:?]
... 86 more
Caused by: java.sql.BatchUpdateException: Batch entry 0 delete from cms_role where id='fdcaa62b-b587-490e-bd4f-08a64bc8ceae' was aborted: ERROR: update or delete on table "cms_role" violates foreign key constraint "workflow_action_next_assign_fkey" on table "workflow_action"
Detail: Key (id)=(fdcaa62b-b587-490e-bd4f-08a64bc8ceae) is still referenced from table "workflow_action". Call getNextException to see other errors in the batch.
at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148) ~[postgresql-42.2.2.jar:42.2.2]
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179) ~[postgresql-42.2.2.jar:42.2.2]
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:479) ~[postgresql-42.2.2.jar:42.2.2]
at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835) ~[postgresql-42.2.2.jar:42.2.2]
at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556) ~[postgresql-42.2.2.jar:42.2.2]
at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at org.apache.tomcat.jdbc.pool.interceptor.AbstractQueryReport$StatementProxy.invoke(AbstractQueryReport.java:210) ~[tomcat-jdbc.jar:?]
at com.sun.proxy.$Proxy103.executeBatch(Unknown Source) ~[?:?]
at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc.jar:?]
at com.sun.proxy.$Proxy103.executeBatch(Unknown Source) ~[?:?]
at com.dotcms.repackage.net.sf.hibernate.impl.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:54) ~[dot.hibernate-2.1.7_3.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.BatcherImpl.executeBatch(BatcherImpl.java:128) ~[dot.hibernate-2.1.7_3.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.executeAll(SessionImpl.java:2438) ~[dot.hibernate-2.1.7_3.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.execute(SessionImpl.java:2397) ~[dot.hibernate-2.1.7_3.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.flush(SessionImpl.java:2261) ~[dot.hibernate-2.1.7_3.jar:?]
at com.dotmarketing.db.HibernateUtil.delete(HibernateUtil.java:234) ~[dotcms_5.2.7_9cb2e09.jar:?]
... 86 more
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "cms_role" violates foreign key constraint "workflow_action_next_assign_fkey" on table "workflow_action"
Detail: Key (id)=(fdcaa62b-b587-490e-bd4f-08a64bc8ceae) is still referenced from table "workflow_action".
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433) ~[postgresql-42.2.2.jar:42.2.2]
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178) ~[postgresql-42.2.2.jar:42.2.2]
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:479) ~[postgresql-42.2.2.jar:42.2.2]
at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835) ~[postgresql-42.2.2.jar:42.2.2]
at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556) ~[postgresql-42.2.2.jar:42.2.2]
at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at org.apache.tomcat.jdbc.pool.interceptor.AbstractQueryReport$StatementProxy.invoke(AbstractQueryReport.java:210) ~[tomcat-jdbc.jar:?]
at com.sun.proxy.$Proxy103.executeBatch(Unknown Source) ~[?:?]
at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc.jar:?]
at com.sun.proxy.$Proxy103.executeBatch(Unknown Source) ~[?:?]
at com.dotcms.repackage.net.sf.hibernate.impl.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:54) ~[dot.hibernate-2.1.7_3.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.BatcherImpl.executeBatch(BatcherImpl.java:128) ~[dot.hibernate-2.1.7_3.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.executeAll(SessionImpl.java:2438) ~[dot.hibernate-2.1.7_3.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.execute(SessionImpl.java:2397) ~[dot.hibernate-2.1.7_3.jar:?]
at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.flush(SessionImpl.java:2261) ~[dot.hibernate-2.1.7_3.jar:?]
at com.dotmarketing.db.HibernateUtil.delete(HibernateUtil.java:234) ~[dotcms_5.2.7_9cb2e09.jar:?]
... 86 more
[13/03/20 17:05:20:105 GMT] INFO caffine.CaffineCache: *** Building Cache : dotcmsrootrolescache, size:1000,Concurrency:32
[13/03/20 17:05:20:105 GMT] INFO caffine.CaffineCache: *** Building Cache : permissioncache, size:50000,Concurrency:32
[13/03/20 17:05:20:105 GMT] INFO caffine.CaffineCache: *** Building Cache : parentpermissionablecache, size:10000,Concurrency:32
[13/03/20 17:05:20:106 GMT] INFO util.ActivityLogger: class com.dotmarketing.business.ajax.RoleAjax: system : Error Deleting Role , Date: 2020-03-13 17:05:20; User:dotcms.org.1; RoleID: fdcaa62b-b587-490e-bd4f-08a64bc8ceae
[13/03/20 17:05:20:106 GMT] INFO ajax.RoleAjax: Error Deleting Role : Date: 2020-03-13 17:05:20; User:dotcms.org.1; RoleID: fdcaa62b-b587-490e-bd4f-08a64bc8ceae
[13/03/20 17:05:20:106 GMT] INFO util.AdminLogger: class com.dotmarketing.business.ajax.RoleAjax : Error Deleting Role : Date: 2020-03-13 17:05:20; User:dotcms.org.1; RoleID: fdcaa62b-b587-490e-bd4f-08a64bc8ceae
```

## Expected Behavior:
Need to determine the best way to allow users to remove the Role they select. Based on the root cause of the problem, it seems like dotCMS needs to figure out several options:

1. The Role must be deleted along with ALL of its dependencies.
2. The Role deletion must inform the user what specific Workflow Tasks are referencing such a Role. This way they can either approve those assets, or delete them.
3. The system must allow the user to replace the Role with another one. This is the same approach used by the User Deletion functionality.

**Comment by jcastro-dotcms** [comment]
After discussing the issue with the R&D Team, here's their feedback:

- For the dev involved in fixing the code: The only other way to go is to not allow a delete unless the user passes a different role in that will update the data to be the new role for the workflow/permission that uses it. This is the same approach used by the User Delete feature.
- The currently valid and official workaround: Prefix the Role name with something that indicates it has been archived so that no one uses it anymore.
