### ISSUE TITLE
NPE in sitesearch when content type does not find detail page

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#18164]
When executing a site search job if we have a Content Type with an URLMap and with an associated detail page that does not longer exist we are getting on logs a NPE.

``` java
14:13:20.901  INFO  bundlers.URLMapBundler - Start bundler
14:13:20.916  INFO  bundlers.URLMapBundler - +(structureName:Video structureName:Activity structureName:Product structureName:calendarEvent structureName:Blog )  +(conhost:SYSTEM_HOST conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:SYSTEM_HOST  ) 
14:13:21.110  ERROR bundlers.URLMapBundler - Unable to generate Bundler file object for contentlet: 1157214a-67c3-4535-aa67-bdb926692e07
java.lang.NullPointerException: null
	at com.dotcms.enterprise.publishing.bundlers.URLMapBundler.getDetailPage(URLMapBundler.java:438) ~[classes/:?]
	at com.dotcms.enterprise.publishing.bundlers.URLMapBundler.writeFileToDiskByHost(URLMapBundler.java:357) ~[classes/:?]
	at com.dotcms.enterprise.publishing.bundlers.URLMapBundler.writeFileToDisk(URLMapBundler.java:299) ~[classes/:?]
	at com.dotcms.enterprise.publishing.bundlers.URLMapBundler.writeURLMap(URLMapBundler.java:277) ~[classes/:?]
	at com.dotcms.enterprise.publishing.bundlers.URLMapBundler.processURLMaps(URLMapBundler.java:243) ~[classes/:?]
	at com.dotcms.enterprise.publishing.bundlers.URLMapBundler.generate(URLMapBundler.java:198) ~[classes/:?]
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:111) ~[classes/:?]
	at com.dotcms.publishing.job.SiteSearchJobImpl.run(SiteSearchJobImpl.java:148) ~[classes/:?]
	at com.dotcms.publishing.job.SiteSearchJobProxy.run(SiteSearchJobProxy.java:31) ~[classes/:?]
	at com.dotmarketing.quartz.DotJob.execute(DotJob.java:42) ~[classes/:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223) ~[dot.quartz-all-1.8.6_2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) ~[dot.quartz-all-1.8.6_2.jar:?]
```

We need to handle better this case detailing in the stack trace what the real issue is.

## Steps to reproduce

1. With a clean install create a `Run now` sitesearch job
2. Check the logs and you will see the NPE because the `Video - YouTube` Content Type does not have a detail page (or probably had it but was deleted leaving an old/wrong reference in the Content Type?).

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/712

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
