### ISSUE TITLE
Reindex problem in ORACLE: maximum open cursors exceeded

### ISSUE THREAD

**Issue by oarriet** [dotCMS/core#18161]
### Describe the bug
Client ticket: https://dotcms.zendesk.com/agent/tickets/100706

Afer reindexing in Oracle client is having problems with the amount of open cursors.
```
DotDataException: ORA-01000: maximum open cursors exceeded

dotcms_1 | "SQL": ["select * from (select * from dist_reindex_journal where MOD(id, ?) = ? and priority <= ? and id > ? ORDER BY priority ASC) where ROWNUM <= 2000"],
dotcms_1 | "maxRows": [-1],
dotcms_1 | "offest": [0],
dotcms_1 | "params": [
dotcms_1 | 1,
dotcms_1 | 0,
dotcms_1 | 400,
dotcms_1 | 7668368
dotcms_1 | ]
dotcms_1 | }
dotcms_1 | at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:262) ~[dotcms_5.1.6_999999.jar:?]
dotcms_1 | at com.dotmarketing.common.db.DotConnect.loadObjectResults(DotConnect.java:914) ~[dotcms_5.1.6_999999.jar:?]
dotcms_1 | at com.dotmarketing.common.reindex.ReindexQueueFactory.loadUpLocalQueue_aroundBody4(ReindexQueueFactory.java:272) ~[dotcms_5.1.6_999999.jar:?]
dotcms_1 | at com.dotmarketing.common.reindex.ReindexQueueFactory$AjcClosure5.run(ReindexQueueFactory.java:1) ~[dotcms_5.1.6_999999.jar:?]
dotcms_1 | at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
dotcms_1 | at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.1.6_999999.jar:?]
dotcms_1 | at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.1.6_999999.jar:?]
```

See commit here, solved problem in client env: https://github.com/dotCMS/support/commit/8b6da3445a983d224072a26e31d06e612a1c945a

**Comment by oarrietadotcms** [comment]
the code is already in 5.3. Please close this one.
