### ISSUE TITLE
Cluster Scaling part 2

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18190]
With the changes in #18050 we see this issue when starting a cluster.  This is because when a license is applied, the system inits the cluster, even though the server does not have

```

 2020-03-24 14:13:38.213 GMT [239] ERROR:  duplicate key value violates unique constraint "cluster_server_pkey"
db_1                    | 2020-03-24 14:13:38.213 GMT [239] DETAIL:  Key (server_id)=(9d2dba76-4960-419e-acec-70aad9ad91ff) already exists.
db_1                    | 2020-03-24 14:13:38.213 GMT [239] STATEMENT:  insert into cluster_server(server_id, cluster_id, name, ip_address, key_) values($1,$2,$3,$4,$5)
dotcms_2                | com.dotmarketing.business.DotStateException: Could not save Server to DB
dotcms_2                | 	at com.dotcms.enterprise.cluster.ClusterFactory.initialize(SourceFile:72)
dotcms_2                | 	at com.dotmarketing.startup.runalways.Task00030ClusterInitialize.executeUpgrade(Task00030ClusterInitialize.java:51)
dotcms_2                | 	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:212)
dotcms_2                | 	at com.liferay.portal.servlet.MainServlet.init_aroundBody0(MainServlet.java:118)
dotcms_2                | 	at com.liferay.portal.servlet.MainServlet$AjcClosure1.run(MainServlet.java:1)
dotcms_2                | 	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
dotcms_2                | 	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
dotcms_2                | 	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29)
dotcms_2                | 	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41)
dotcms_2                | 	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:104)
dotcms_2                | 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
dotcms_2                | 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091)
dotcms_2                | 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983)
dotcms_2                | 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4978)
dotcms_2                | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5290)
dotcms_2                | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
dotcms_2                | 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
dotcms_2                | 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
dotcms_2                | 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
dotcms_2                | 	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1140)
dotcms_2                | 	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875)
dotcms_2                | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
dotcms_2                | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
dotcms_2                | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
dotcms_2                | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
dotcms_2                | 	at java.lang.Thread.run(Thread.java:748)
dotcms_2                | Caused by: com.dotmarketing.exception.DotDataException: ERROR: duplicate key value violates unique constraint "cluster_server_pkey"
dotcms_2                |   Detail: Key (server_id)=(9d2dba76-4960-419e-acec-70aad9ad91ff) already exists.{
dotcms_2                |   "SQL": ["insert into cluster_server(server_id, cluster_id, name, ip_address, key_) values(?,?,?,?,?)"],
dotcms_2                |   "maxRows": [-1],
dotcms_2                |   "offest": [0],
dotcms_2                |   "params": [
dotcms_2                |     "9d2dba76-4960-419e-acec-70aad9ad91ff",
dotcms_2                |     "80cb7262c0",
dotcms_2                |     "a9d64ad6b5a2",
dotcms_2                |     "172.18.0.4",
dotcms_2                |     "n/a"
dotcms_2                |   ]
dotcms_2                | }
dotcms_2                | 	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:263)
dotcms_2                | 	at com.dotcms.enterprise.cluster.ServerFactoryImpl.saveServer(SourceFile:65)
dotcms_2                | 	at com.dotcms.cluster.business.ServerAPIImpl.saveServer_aroundBody0(ServerAPIImpl.java:43)
dotcms_2                | 	at com.dotcms.cluster.business.ServerAPIImpl$AjcClosure1.run(ServerAPIImpl.java:1)
dotcms_2                | 	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
dotcms_2                | 	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
dotcms_2                | 	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29)
dotcms_2                | 	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41)
dotcms_2                | 	at com.dotcms.cluster.business.ServerAPIImpl.saveServer(ServerAPIImpl.java:42)
dotcms_2                | 	at com.dotcms.cluster.business.ServerAPIImpl.createMyServer(ServerAPIImpl.java:93)
dotcms_2                | 	at com.dotcms.cluster.business.ServerAPIImpl.getOrCreateMyServer(ServerAPIImpl.java:57)
dotcms_2                | 	at com.dotcms.enterprise.cluster.ClusterFactory.initialize(SourceFile:65)
```

**Comment by wezell** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/717

**Comment by erickgonzalez** [comment]
I test this generating a new dotcms image of release-5.2.8 and works without issues.
Gonna create a new PR for the master branch.

**Comment by erickgonzalez** [comment]
PR for master: https://github.com/dotCMS/enterprise-2.x/pull/719
