### ISSUE TITLE
Apps - Backend: Implement a Secret Exporter

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18236]
1. We need a secret exporter (only CMS Admins) that takes a password and will encrypt the secrets (as json) which the user can then download.  If the user does not specify a password, we read the default password set in the config.properties and use it.

2. When starting dotCMS, we will look for a file under /assets/server/dotSecrets-import.xxx. If there is a file there and there is not already a secrets store, then we will read this, decode it with the password in the config, import the secrets and delete the dotSecrets-import.xxx file

**Note to QA:** Both Import/Export functionalities were implemented on the same card

~3.  Allow user to export only part of the apps - meaning, if a user is on the apps listing screen and exports, it will export all the apps.  If they are on the app detail page (host list) it will export the specific app config.  If they are on the config detail page, it will export the 1 config.~

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19004

**Comment by nollymar** [comment]
**Internal QA results: Needs work**

It is possible to export secrets without having an enterprise license

**Comment by fabrizzio-dotCMS** [comment]
PR: https://github.com/dotCMS/core/pull/19384

**Comment by wezell** [comment]
This needs some inline documentation - also, I don't think. we should have a default/shipped value here - it needs to be set-able but not set by default.
 
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/resources/dotmarketing-config.properties#L905

**Comment by nollymar** [comment]
**Internal QA:** I found a couple of issues after the new changes:

- [ ] If there is no license and I try to open the Apps portlet, an exception is thrown in catalina.out and the Dashboard portlet is displayed instead.

- [ ] This section in the documentation should be updated: "When starting dotCMS, we will look for a file under /assets/server/dotSecrets-import.xxx. If there is a file there and there is not already a secrets store, then we will read this, decode it with the password in the config, import the secrets and delete the dotSecrets-import.xxx file", because it only works if you are using a fresh installation or running an upgrade. The dotSecrets-import.xxx file will be ignored if you just restart the server.

- [ ] Importing/exporting secrets is not working for `SYSTEM_HOST`. Steps to reproduce it: 

**Export Test Case:** 
1. Using a fresh installation, create secrets for SYSTEM_HOST and demo sites.
2.  Set this property `APPS_IMPORT_EXPORT_DEFAULT_PASSWORD=ABCDE` in the dotcms-dotmarketing.properties and restart the server. 
3. Use this json to export the secrets: 
```
{ 
      "password":"ABCDE",
      "appKeysBySite":{     
            "48190c8c-42c4-46af-8d1a-0cd5db894797":["dotAmazonRekognition-config"],
            "SYSTEM_HOST":["dotAmazonRekognition-config"]     
      }

}

```


**Import Test Case:** I've attached the file I used for the test. Password `ABCDE`. The file has secrets for Amazon Rekognition.

**Comment by nollymar** [comment]
New PR: https://github.com/dotCMS/core/pull/19491

**Comment by nollymar** [comment]
**Update from last QA:** 
I got an exception importing a `dotSecrets-import.export` file from startup. These are the steps to reproduce it: 

1) I exported the attached file and removed my secrets
2) Then, I stopped the server, copied the exported file in the `assets/server/` directory
3) Finally, I started the server. The server crashed with an exception

This is the exception I got: 

```
com.dotmarketing.exception.DotDataException: Error Importing AppSecret from starer 
	at com.dotmarketing.startup.runalways.Task00050LoadAppsSecrets.executeUpgrade(Task00050LoadAppsSecrets.java:139)
	at com.dotmarketing.startup.StartupTasksExecutor.executeStartUpTasks(StartupTasksExecutor.java:133)
	at com.liferay.portal.servlet.MainServlet.init_aroundBody0(MainServlet.java:120)
	at com.liferay.portal.servlet.MainServlet$AjcClosure1.run(MainServlet.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29)
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41)
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:99)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4978)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5290)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1140)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Param `secret` is marked required in the descriptor but does not come with a value.
	at com.dotcms.security.apps.AppsUtil.validateForSave(AppsUtil.java:427)
	at com.dotmarketing.startup.runalways.Task00050LoadAppsSecrets.executeUpgrade(Task00050LoadAppsSecrets.java:111)
	... 24 more
```

Regardless of a problem with my secrets,  the server should deploy.

**Comment by bryanboza** [comment]
Fixed, now we can import the secrets without problems following this doc: https://auth.dotcms.com/devwiki/secrets-import
