### ISSUE TITLE
[OSGi] : Concurrent access to the bundle cache is causing problems

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#18319]
Reported via Support: [101123](https://dotcms.zendesk.com/agent/tickets/101123)
Reproducible in all versions dotCMS.

Clustered environments - usually the PROD instances - share the location of OSGi plugins. When Felix is initializing, there are times in which two or more nodes in the cluster attempt to access the bundle cache. By default, such an operation is disabled. According to Will, this has also happened with our Docker installation.

The error being displayed in the log is the following:
```
[17/04/20 12:17:39:854 EDT]  INFO framework.OSGIUtil: Loading Factory org.apache.felix.framework.FrameworkFactory
[17/04/20 12:17:39:878 EDT] ERROR framework.OSGIUtil: Could not create framework: org.osgi.framework.BundleException: Error creating bundle cache.
[17/04/20 12:17:39:878 EDT] ERROR AJAX.OSGIAJAX: Trying to run method:restart
[17/04/20 12:17:39:878 EDT] ERROR AJAX.OSGIAJAX: null
java.lang.RuntimeException: org.osgi.framework.BundleException: Error creating bundle cache.
	at org.apache.felix.framework.OSGIUtil.initializeFramework(OSGIUtil.java:210) ~[dotcms_5.2.6_b69c38c.jar:?]
	at org.apache.felix.framework.OSGIUtil.initializeFramework(OSGIUtil.java:97) ~[dotcms_5.2.6_b69c38c.jar:?]
	at com.dotmarketing.portlets.osgi.AJAX.OSGIAJAX.restart(OSGIAJAX.java:222) ~[dotcms_5.2.6_b69c38c.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at com.dotmarketing.portlets.osgi.AJAX.OSGIBaseAJAX.service(OSGIBaseAJAX.java:52) ~[dotcms_5.2.6_b69c38c.jar:?]
	at com.dotmarketing.portlets.osgi.AJAX.OSGIAJAX.service(OSGIAJAX.java:1) ~[dotcms_5.2.6_b69c38c.jar:?]
	at com.dotmarketing.servlets.ajax.AjaxAction.doPut(AjaxAction.java:62) ~[dotcms_5.2.6_b69c38c.jar:?]
	at com.dotmarketing.servlets.ajax.AjaxDirectorServlet.service(AjaxDirectorServlet.java:78) ~[dotcms_5.2.6_b69c38c.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.CMSFilter.doFilterInternal(CMSFilter.java:191) ~[dotcms_5.2.6_b69c38c.jar:?]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:47) ~[dotcms_5.2.6_b69c38c.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_5.2.6_b69c38c.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_5.2.6_b69c38c.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:104) ~[dotcms_5.2.6_b69c38c.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:399) ~[urlrewritefilter-4.0.4.jar:4.0.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:134) ~[dotcms_5.2.6_b69c38c.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:88) ~[dotcms_5.2.6_b69c38c.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:48) ~[dotcms_5.2.6_b69c38c.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:99) ~[dotcms_5.2.6_b69c38c.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_5.2.6_b69c38c.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.NormalizationFilter.doFilter(NormalizationFilter.java:44) ~[dotcms_5.2.6_b69c38c.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[catalina.jar:8.5.32]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) ~[catalina.jar:8.5.32]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[catalina.jar:8.5.32]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) ~[catalina.jar:8.5.32]
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:685) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[catalina.jar:8.5.32]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) ~[catalina.jar:8.5.32]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:8.5.32]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.32]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: org.osgi.framework.BundleException: Error creating bundle cache.
	at org.apache.felix.framework.Felix.init(Felix.java:697) ~[org.apache.felix.framework-5.6.10.jar:?]
	at org.apache.felix.framework.Felix.init(Felix.java:626) ~[org.apache.felix.framework-5.6.10.jar:?]
	at org.apache.felix.framework.OSGIUtil.initializeFramework(OSGIUtil.java:199) ~[dotcms_5.2.6_b69c38c.jar:?]
	... 68 more
Caused by: java.lang.Exception: Unable to lock bundle cache: java.nio.channels.OverlappingFileLockException
	at org.apache.felix.framework.cache.BundleCache.<init>(BundleCache.java:176) ~[org.apache.felix.framework-5.6.10.jar:?]
	at org.apache.felix.framework.Felix.init(Felix.java:692) ~[org.apache.felix.framework-5.6.10.jar:?]
	at org.apache.felix.framework.Felix.init(Felix.java:626) ~[org.apache.felix.framework-5.6.10.jar:?]
	at org.apache.felix.framework.OSGIUtil.initializeFramework(OSGIUtil.java:199) ~[dotcms_5.2.6_b69c38c.jar:?]
	... 68 more
```

### Steps to reproduce the behavior:
This might be strictly related to a PROD environment. Cannot be easily reproducible.

### Expected behavior
We should not have problems allowing concurrent access to the Felix Bundle Cache.

### Current Fix
Adding the following Felix property:
```
felix.felix.cache.locking=false
```
And restarting each node takes care of the problem.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/18320

**Comment by dsilvam** [comment]
This one should probably be verified once dotcms.com is upgraded to 5.3.0

**Comment by nollymar** [comment]
@bryanboza this task couldn't be tested on Internal QA for the reason @dsilvam explained above

**Comment by dsilvam** [comment]
Passing QA on this one based on the feedback from support.
