### ISSUE TITLE
Add JWT support to WebDAV

### ISSUE THREAD

**Issue by samuelmaddock** [dotCMS/core#18540]
As a dotCMS website developer, I want dotCMS' WebDAV feature to support JWT tokens using an HTTP Bearer Auth token in order to reuse existing API Access Keys and to forgo using cleartext username and passwords for automation tasks.

### Is your feature request related to a problem? Please describe
I've been creating tooling for my team to make working with dotCMS easier. Sometimes the tools I write require a mix of using the REST API and WebDAV. The REST API works well with API Authentication keys, but WebDAV does not support them.

### Describe the solution you'd like
Support `Authorization: Bearer <token>` in the dotCMS WebDAV implementation.

### Technical Approach
> A clear and concise description of any alternative solutions or features you've considered.

There are no alternative solutions that I'm aware of for this issue.

### Additional context
When attempting to use an API token, the WebDAV server response is a 500 error. Looking at `catalina.out`, we can see that the `com.dotcms.repackage.com.bradmcevoy.http.Auth.Scheme` enum doesn't support `Bearer`.
```
14:06:20.162 INFO http.HttpManager - GET :: http://redacted.com/webdav/live/1/redacted.com/redacted.vtl - http://redacted.com/webdav/live/1/redacted.com/redacted.vtl
14:06:20.171 ERROR http.StandardFilter - process
java.lang.IllegalArgumentException: No enum constant com.dotcms.repackage.com.bradmcevoy.http.Auth.Scheme.BEARER
at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_242]
at com.dotcms.repackage.com.bradmcevoy.http.Auth$Scheme.valueOf(Auth.java:61) ~[dot.milton-api-1.8.1.4_3.jar:?]
at com.dotcms.repackage.com.bradmcevoy.http.Auth.<init>(Auth.java:91) ~[dot.milton-api-1.8.1.4_3.jar:?]
at com.dotcms.repackage.com.bradmcevoy.http.ServletRequest.getAuthorization(ServletRequest.java:131) ~[dot.milton-servlet-1.8.1.4_3.jar:?]
at com.dotcms.repackage.com.bradmcevoy.http.AuthenticationService.authenticate(AuthenticationService.java:144) ~[dot.milton-api-1.8.1.4_3.jar:?]
at com.dotcms.repackage.com.bradmcevoy.http.HandlerHelper.checkAuthentication(HandlerHelper.java:83) ~[dot.milton-api-1.8.1.4_3.jar:?]
at com.dotcms.repackage.com.bradmcevoy.http.HandlerHelper.checkAuthorisation(HandlerHelper.java:95) ~[dot.milton-api-1.8.1.4_3.jar:?]
at com.dotcms.repackage.com.bradmcevoy.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:117) ~[dot.milton-api-1.8.1.4_3.jar:?]
at com.dotcms.repackage.com.bradmcevoy.http.http11.GetHandler.processResource(GetHandler.java:61) ~[dot.milton-api-1.8.1.4_3.jar:?]
at com.dotcms.repackage.com.bradmcevoy.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:91) ~[dot.milton-api-1.8.1.4_3.jar:?]
at com.dotcms.repackage.com.bradmcevoy.http.http11.GetHandler.process(GetHandler.java:55) ~[dot.milton-api-1.8.1.4_3.jar:?]
at com.dotcms.repackage.com.bradmcevoy.http.StandardFilter.process(StandardFilter.java:52) ~[dot.milton-api-1.8.1.4_3.jar:?]
at com.dotcms.repackage.com.bradmcevoy.http.FilterChain.process(FilterChain.java:40) ~[dot.milton-api-1.8.1.4_3.jar:?]
at com.dotcms.repackage.com.bradmcevoy.http.HttpManager.process(HttpManager.java:228) ~[dot.milton-api-1.8.1.4_3.jar:?]
at com.dotcms.repackage.com.bradmcevoy.http.MiltonServlet.service(MiltonServlet.java:195) ~[dot.milton-servlet-1.8.1.4_3.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotmarketing.filters.CMSFilter.doFilterInternal(CMSFilter.java:199) ~[dotcms_5.1.5_999999.jar:?]
at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:56) ~[dotcms_5.1.5_999999.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_5.1.5_999999.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_5.1.5_999999.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:114) ~[dotcms_5.1.5_999999.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:104) ~[dotcms_5.1.5_999999.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:399) ~[urlrewritefilter-4.0.4.jar:4.0.4]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:134) ~[dotcms_5.1.5_999999.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:88) ~[dotcms_5.1.5_999999.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:46) ~[dotcms_5.1.5_999999.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:100) ~[dotcms_5.1.5_999999.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_5.1.5_999999.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[catalina.jar:8.5.32]
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) ~[catalina.jar:8.5.32]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[catalina.jar:8.5.32]
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) ~[catalina.jar:8.5.32]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[catalina.jar:8.5.32]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) ~[catalina.jar:8.5.32]
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) ~[tomcat-coyote.jar:8.5.32]
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-coyote.jar:8.5.32]
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800) ~[tomcat-coyote.jar:8.5.32]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471) ~[tomcat-coyote.jar:8.5.32]
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:8.5.32]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.32]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

## Acceptance Criteria
1. A request to get a WebDAV file allows using an API Access Key.

**Comment by wezell** [comment]
This is complete, though not as described.  You can create an API token and use it as your password to login to dotCMS, e.g. will@dotcms.com:APITOKEN.  This allows webdav to be used even if you have 3rd party authentication (OAuth/SAML) enabled.
