### ISSUE TITLE
Bundleing a Page without a valid template throws an NPE

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18598]
I was trying to bundle an entire site, where there are pages whose templates no longer exist (this is a live customers data).  When I try to bundle the site, the bundle fails with an npe here:

```
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.32]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.NullPointerException
	at com.dotcms.publisher.util.DependencyManager.setHTMLPagesDependencies(DependencyManager.java:753) ~[classes/:?]
	at com.dotcms.publisher.util.DependencyManager.setHTMLPagesDependencies(DependencyManager.java:656) ~[classes/:?]
	at com.dotcms.publisher.util.DependencyManager.setDependencies(DependencyManager.java:341) ~[classes/:?]
	at com.dotcms.enterprise.publishing.remote.bundler.DependencyBundler.generate(DependencyBundler.java:68) ~[classes/:?]
	... 66 more

```

**Comment by wezell** [comment]
Also an NPE here:
```
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.32]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.NullPointerException
	at com.dotcms.publisher.util.DependencyManager.setHTMLPagesDependencies(DependencyManager.java:823) ~[classes/:?]
	at com.dotcms.publisher.util.DependencyManager.setHTMLPagesDependencies(DependencyManager.java:656) ~[classes/:?]
	at com.dotcms.publisher.util.DependencyManager.setDependencies(DependencyManager.java:341) ~[classes/:?]
	at com.dotcms.enterprise.publishing.remote.bundler.DependencyBundler.generate(DependencyBundler.java:68) ~[classes/:?]
```

**Comment by bryanboza** [comment]
Fixed tested on master deleting the template directly from the db, and after this we are able to bundle the page and also the site without problems. 

Now, if you try to open the page, this obviously will fail because the template does not exist.
