### ISSUE TITLE
Upgrade to 5.3 using postgres 9.6

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18640]
When upgrading a 5.2.x instance to 5.3.x and the source db is postgres 9.6, we have this error:

```
======================================================================
18:59:09.414  INFO  runonce.Task05225RemoveLoadRecordsToIndex - ==> Executing upgrade script
18:59:09.414  INFO  runonce.Task05225RemoveLoadRecordsToIndex - ======================================================================
18:59:09.416  INFO  db.DotConnect - Executing DROP FUNCTION IF EXISTS load_records_to_index
com.dotmarketing.exception.DotDataException: ERROR: syntax error at end of input
  Position: 46
	at com.dotmarketing.startup.AbstractJDBCStartupTask.executeUpgrade(AbstractJDBCStartupTask.java:797)
	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:275)
	at com.liferay.portal.servlet.MainServlet.init_aroundBody0(MainServlet.java:119)
	at com.liferay.portal.servlet.MainServlet$AjcClosure1.run(MainServlet.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29)
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41)
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:98)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4978)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5290)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1140)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
```

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/18647/files)
