### ISSUE TITLE
NPE in ContainerWebAPI.getPersonalizedContentList

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18855]
We have what I think is a race condition with the method 
`ContainerWebAPI.getPersonalizedContentList`

In any running dotCMS system, you can see messages like

```
[09/07/20 13:56:02:441 GMT]  WARN viewtools.ContainerWebAPI: getPersonalizedContentList null @ url:GET//dotcms.com/docs/latest/active-directory-error-codes | lang:1 | ip:88.26.234.105 | Admin:false | start:07-09-2020 01:52:41 GMT  ref:https://www.google.com/
```

When this occurs, the affected container does not display any content.

**Comment by wezell** [comment]
```
dotcms_1  | 14:39:27.495  WARN  viewtools.ContainerWebAPI - pageId      : 4537a853-8c23-4354-a248-708057775d76 @ url:GET//dotcms.com/docs/latest/docs/latest/log-file-locations | lang:1 | ip:108.49.249.66 | Admin:false | start:07-09-2020 02:39:26 GMT
dotcms_1  | 14:39:27.495  WARN  viewtools.ContainerWebAPI - containerId : 21a230ec-79a8-4c98-a0a7-32447ac67138 @ url:GET//dotcms.com/docs/latest/docs/latest/log-file-locations | lang:1 | ip:108.49.249.66 | Admin:false | start:07-09-2020 02:39:26 GMT
dotcms_1  | 14:39:27.495  WARN  viewtools.ContainerWebAPI - uuid        : 2 @ url:GET//dotcms.com/docs/latest/docs/latest/log-file-locations | lang:1 | ip:108.49.249.66 | Admin:false | start:07-09-2020 02:39:26 GMT
dotcms_1  | 14:39:27.495  WARN  viewtools.ContainerWebAPI - backuser    : anonymous user anonymous [ID: anonymous][email:anonymous@dotcmsfakeemail.org] @ url:GET//dotcms.com/docs/latest/docs/latest/log-file-locations | lang:1 | ip:108.49.249.66 | Admin:false | start:07-09-2020 02:39:26 GMT
dotcms_1  | 14:39:27.495  WARN  viewtools.ContainerWebAPI - pageMode    : LIVE @ url:GET//dotcms.com/docs/latest/docs/latest/log-file-locations | lang:1 | ip:108.49.249.66 | Admin:false | start:07-09-2020 02:39:26 GMT
dotcms_1  | 14:39:27.495  ERROR viewtools.ContainerWebAPI - getPersonalizedContentList error:null @ url:GET//dotcms.com/docs/latest/docs/latest/log-file-locations | lang:1 | ip:108.49.249.66 | Admin:false | start:07-09-2020 02:39:26 GMT
dotcms_1  | java.lang.NullPointerException: null
dotcms_1  | 	at com.dotcms.rendering.velocity.viewtools.VelocitySessionWrapper.getAttribute(VelocitySessionWrapper.java:24) ~[dotcms_5.3.4_999999.jar:?]
dotcms_1  | 	at com.dotcms.rendering.velocity.viewtools.VelocitySessionWrapper.getAttribute(VelocitySessionWrapper.java:24) ~[dotcms_5.3.4_999999.jar:?]
dotcms_1  | 	at com.dotcms.visitor.business.VisitorAPIImpl.getVisitor(VisitorAPIImpl.java:69) ~[dotcms_5.3.4_999999.jar:?]
dotcms_1  | 	at com.dotcms.visitor.business.VisitorAPIImpl.getVisitor(VisitorAPIImpl.java:50) ~[dotcms_5.3.4_999999.jar:?]
dotcms_1  | 	at com.dotcms.personalization.web.PersonalizationWebAPIImpl.getContainerPersonalization(PersonalizationWebAPIImpl.java:32) ~[dotcms_5.3.4_999999.jar:?]
dotcms_1  | 	at com.dotcms.rendering.velocity.viewtools.ContainerWebAPI.getPersonalizedContentListInternal(ContainerWebAPI.java:149) ~[dotcms_5.3.4_999999.jar:?]
dotcms_1  | 	at com.dotcms.rendering.velocity.viewtools.ContainerWebAPI.getPersonalizedContentList(ContainerWebAPI.java:109) ~[dotcms_5.3.4_999999.jar:?]
dotcms_1  | 	at sun.reflect.GeneratedMethodAccessor217.invoke(Unknown Source) ~[?:?]
dotcms_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
dotcms_1  | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
dotcms_1  | 	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372) ~[dotcms_5.3.4_999999.jar:?]
dotcms_1  | 	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361) ~[dotcms_5.3.4_999999.jar:?]
dotcms_1  | 	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:176) ~[dotcms_5.3.4_999999.jar:?]
dotcms_1  | 	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285) ~[dotcms_5.3.4_999999.jar:?]
dotcms_1  | 	at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:572) ~[dotcms_5.3.4_999999.jar:?]
dotcms_1  | 	at org.apache.velocity.runtime.parser.node.ASTExpression.value(ASTExpression.java:71) ~[dotcms_5.3.4_999999.jar:?]
```

**Comment by wezell** [comment]
If we want a smaller pull for 5.3.4, the fix is one line - 
https://github.com/dotCMS/core/pull/18858/files#diff-3fcec2e785fd29108c819fbb5274c4dcR38

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18858
