### ISSUE TITLE
Reindex not working in MSSQL

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#18912]
Reported via Support: [Zendesk-101869](https://dotcms.zendesk.com/agent/tickets/101869)
Reproducible in dotCMS 5.3.3

Running with MSQQL throws an error when doing a reindex in 5.3.3

This error is shown in the log:
```
[17/07/20 18:04:14:290 CST] ERROR reindex.ReindexThread: ReindexThread Exception
com.dotmarketing.exception.DotDataException: Incorrect syntax near the keyword 'from'.{
  "SQL": ["SELECT TOP 1 from dist_reindex_journal where priority >= ? and  priority < ?"],
  "maxRows": [-1],
  "offest": [0],
  "params": [
    300,
    400
  ]
}
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:273) ~[dotcms_5.3.3_af34408.jar:?]
	at com.dotmarketing.common.db.DotConnect.loadResults(DotConnect.java:393) ~[dotcms_5.3.3_af34408.jar:?]
	at com.dotmarketing.common.reindex.ReindexQueueFactory.hasReindexRecords(ReindexQueueFactory.java:156) ~[dotcms_5.3.3_af34408.jar:?]
	at com.dotmarketing.common.reindex.ReindexQueueAPIImpl.hasReindexRecords_aroundBody16(ReindexQueueAPIImpl.java:98) ~[dotcms_5.3.3_af34408.jar:?]
	at com.dotmarketing.common.reindex.ReindexQueueAPIImpl$AjcClosure17.run(ReindexQueueAPIImpl.java:1) ~[dotcms_5.3.3_af34408.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.3.3_af34408.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.3.3_af34408.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.3.3_af34408.jar:?]
	at com.dotmarketing.common.reindex.ReindexQueueAPIImpl.hasReindexRecords(ReindexQueueAPIImpl.java:97) ~[dotcms_5.3.3_af34408.jar:?]
	at com.dotcms.content.elasticsearch.business.ContentletIndexAPIImpl.isInFullReindex_aroundBody6(ContentletIndexAPIImpl.java:457) ~[dotcms_5.3.3_af34408.jar:?]
	at com.dotcms.content.elasticsearch.business.ContentletIndexAPIImpl$AjcClosure7.run(ContentletIndexAPIImpl.java:1) ~[dotcms_5.3.3_af34408.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.3.3_af34408.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.3.3_af34408.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.3.3_af34408.jar:?]
	at com.dotcms.content.elasticsearch.business.ContentletIndexAPIImpl.isInFullReindex(ContentletIndexAPIImpl.java:455) ~[dotcms_5.3.3_af34408.jar:?]
	at com.dotcms.content.elasticsearch.util.ESReindexationProcessStatus.inFullReindexation(ESReindexationProcessStatus.java:20) ~[dotcms_5.3.3_af34408.jar:?]
	at com.dotmarketing.common.reindex.ReindexThread.switchOverIfNeeded(ReindexThread.java:235) ~[dotcms_5.3.3_af34408.jar:?]
	at com.dotmarketing.common.reindex.ReindexThread.runReindexLoop(ReindexThread.java:201) ~[dotcms_5.3.3_af34408.jar:?]
	at com.dotmarketing.common.reindex.ReindexThread.lambda$0(ReindexThread.java:142) ~[dotcms_5.3.3_af34408.jar:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_181]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'from'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262) ~[mssql-jdbc-7.4.1.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1624) ~[mssql-jdbc-7.4.1.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:594) ~[mssql-jdbc-7.4.1.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524) ~[mssql-jdbc-7.4.1.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194) ~[mssql-jdbc-7.4.1.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2979) ~[mssql-jdbc-7.4.1.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248) ~[mssql-jdbc-7.4.1.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223) ~[mssql-jdbc-7.4.1.jre8.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:446) ~[mssql-jdbc-7.4.1.jre8.jar:?]
	at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractQueryReport$StatementProxy.invoke(AbstractQueryReport.java:210) ~[tomcat-jdbc.jar:?]
	at com.sun.proxy.$Proxy82.executeQuery(Unknown Source) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc.jar:?]
	at com.sun.proxy.$Proxy82.executeQuery(Unknown Source) ~[?:?]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-3.4.2.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.2.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:629) ~[dotcms_5.3.3_af34408.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:532) ~[dotcms_5.3.3_af34408.jar:?]
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:271) ~[dotcms_5.3.3_af34408.jar:?]
	... 26 more
```

The syntax error is located in this line:
https://github.com/dotCMS/core/blob/af34408b77bacd19e8790278ed3164839168ff71/dotCMS/src/main/java/com/dotmarketing/common/reindex/ReindexQueueFactory.java#L150

**Comment by dsilvam** [comment]
PR: #18916

**Comment by dsilvam** [comment]
Passed Internal QA: Reindex working in MSSQL.
