### ISSUE TITLE
[Push Publishing] : Existing archived content is causing push to fail

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#18920]
Reported via Support: [101886](https://dotcms.zendesk.com/agent/tickets/101886)
Reproducible in dotCMS 5.2.8.x, and latest master.

There are situations in which customers manually archive a piece of content in the receiving endpoint of a Push Publishing environment. Then, when a user attempts to push the same piece of content again, the receiving endpoint will report an error like the following: `Failed to publish because an error occurred: null`

<img width="1042" alt="Screen Shot 2020-07-20 at 15 24 39" src="https://user-images.githubusercontent.com/8779585/87988195-2d7c0480-ca9d-11ea-974d-b81bf7192f6a.png">

Even though manual interaction is not the recommended way of archiving or deleting a piece of content in the receiving endpoint, the application should be able to handle this situation.

## Steps to Reproduce

1. Set up a local Push Publishing environment.
2. Create a page in the sender, and push it.
3. In the receiver, archive such a new page.
4. Force Push or remove the push history of the page, and push it again.
5. You'll see a stack trace like this one in the log:
```
10:51:25.552  ERROR business.ESContentletAPIImpl - null
java.lang.NullPointerException: null
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.updateTemplateInAllLanguageVersions(ESContentletAPIImpl.java:5182) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.internalCheckin(ESContentletAPIImpl.java:4518) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.lambda$45(ESContentletAPIImpl.java:4115) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.concurrent.lock.StripedLockImpl.tryLock(StripedLockImpl.java:100) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.concurrent.lock.StripedLockImpl.tryLock(StripedLockImpl.java:55) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.concurrent.lock.IdentifierStripedLock.tryLock(IdentifierStripedLock.java:16) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin_aroundBody140(ESContentletAPIImpl.java:4114) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure141.run(ESContentletAPIImpl.java:1) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:59) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:4073) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:8224) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin_aroundBody130(ESContentletAPIImpl.java:3984) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure131.run(ESContentletAPIImpl.java:1) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:3979) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkin(ContentletAPIInterceptor.java:257) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:611) ~[ee-5.2.8.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:268) ~[ee-5.2.8.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(SourceFile:163) ~[ee-5.2.8.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(SourceFile:138) ~[ee-5.2.8.jar:?]
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:203) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.rest.PublishThread.run(PublishThread.java:42) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
10:51:25.556  ERROR handler.ContentHandler - Error on File /Users/josecastro/Downloads/dotCMS_releases/dotcms_5.2.8.2/dotserver/tomcat-8.5.32/webapps/ROOT/assets/bundles/01EDPAX9KVK52NKXEYJBBM3DXQ/live/xx.xxxxxxxxx.xx/1/10-index.content.xml, content id:c8a3a6ff-77f6-4a31-b961-3fcfc1924584 :null
com.dotmarketing.exception.DotRuntimeException: null
	at com.dotcms.exception.ExceptionUtil.bubbleUpException(ExceptionUtil.java:161) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin_aroundBody140(ESContentletAPIImpl.java:4121) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure141.run(ESContentletAPIImpl.java:1) ~[dotcms_5.2.8.2_cc873df.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
```

## Current Behavior
The push fails, and the reported error message is not useful.

## Expected Behavior
The application should either (1) report a useful error message, or (2) un-archive the page in the receiver, and apply the changes that come from the sender.

The NPE comes from calling the `findContentletByIdentifierAnyLanguage` method in these lines: https://github.com/dotCMS/core/blob/d8f4568aa2ec42057959f701b0a05e1194978257/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L5299-L5301
Which eventually calls this method:
https://github.com/dotCMS/core/blob/d8f4568aa2ec42057959f701b0a05e1194978257/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentFactoryImpl.java#L1053-L1065
As the content is archived, this method returns null, and generates a NPE later on.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/18971

**Comment by fabrizzio-dotCMS** [comment]
I'm returning this ticket. The archived content on the target continues to break the push publish operation.
If I send a whole bundle with 4 pages and only one of them has been archived on the receiver none of the other pieces of content will make it into the new destination. Basically they all fail. 

I no longer get an NPE instead I'm getting a more informative message but the problem remains unsolved.

here's what it looks like now :

```
`09:49:07.715  ERROR business.PublisherAPIImpl - Error publishing bundle with ID '01EGR9PNE99TDQ6437CK66XNVQ.tar.gz': An error occurred when processing Contentlet in '/Users/fabrizzio/code/servers/server2/assets/bundles/01EGR9PNE99TDQ6437CK66XNVQ/live/starter.dotcms.com/1/xyz/60-lol.content.xml' with ID '4818a3a6-c002-4cef-a852-7cd48cd409fc': 'Contentlet with ID '4818a3a6-c002-4cef-a852-7cd48cd409fc' has not been found, or is currently marked as 'Archived'.'
com.dotcms.publishing.DotPublishingException: An error occurred when processing Contentlet in '/Users/fabrizzio/code/servers/server2/assets/bundles/01EGR9PNE99TDQ6437CK66XNVQ/live/starter.dotcms.com/1/xyz/60-lol.content.xml' with ID '4818a3a6-c002-4cef-a852-7cd48cd409fc': 'Contentlet with ID '4818a3a6-c002-4cef-a852-7cd48cd409fc' has not been found, or is currently marked as 'Archived'.'`
```

I think the content on the receiver must reflect the status of the content sent (from the sender) I mean we're sending it to replace it. isn't that the point?

**Comment by nollymar** [comment]
@fabrizzio-dotCMS the fix has the purpose to avoid a NPE and log a more detailed message. I think this is the right behavior. 

@jcastro-dotcms can you please confirm this?

**Comment by nollymar** [comment]
I have confirmed with @wezell that the right behavior would be to unarchive the piece of content and push the changes from the sender to the receiver

**Comment by nollymar** [comment]
This PRs fix the issue reported by @fabrizzio-dotCMS : 
https://github.com/dotCMS/enterprise-2.x/pull/748
https://github.com/dotCMS/core/pull/19197

However, after fixing this issue I found another one related to workflow actions: https://github.com/dotCMS/core/issues/19193

**Comment by fabrizzio-dotCMS** [comment]
Tested this issue again against **release-5.3.8** and found another problem. I did it with pages and file-assets 
basically I had a sender with a folder with pages and images. I sent each one of them (one by one) to the receiver.
Once in the receiver, I verified the contents to ensure the items had been sent correctly. Then I had the items on the receiver archived. Back on the sender, I introduce a change (like removing and adding a new contentllet) for pages. Then I push-publish the page again. The page effectively gets unarchived but the url property is no longer there.  if you open the page properties dialog. You'll see it is missing. there too.. 
Files-Present are not affected by this bug
see attached gif
 
![gonne-url](https://user-images.githubusercontent.com/37148755/92034016-e040b300-ed29-11ea-883e-c5b9e5546199.gif)

**Comment by fabrizzio-dotCMS** [comment]
waiting for the resolution of this https://github.com/dotCMS/core/issues/19221

**Comment by nollymar** [comment]
The issue https://github.com/dotCMS/core/issues/19221 has been fixed

**Comment by fabrizzio-dotCMS** [comment]
Tested push-publish directly individua items and also sending bundles. 
The issue appears to be fixed. The content on the receiver accurately reflects the status of the respective item sent from the sender. Nothing breaks.  Passing it to QA

**Comment by bryanboza** [comment]
Related to #19221. Need wait for a card

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after the last changes in the cards #19221
