### ISSUE TITLE
SAML- Apps: Keystore validation prevents the server runs

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#19022]
If for some reason, the apps keystore validation fails when the server is starting, a runtime exception is thrown and the server falls into a non-recovery state. I reproduced this error on auth.dotcms.com and dotcms.com server which had an invalid `dotSecretsStore.p12`. As a workaround I had to remove the existing `dotSecretsStore.p12` and restart the server to force the regeneration of a valid one 

SAML logic should be able to handle this kind of exceptions without blocking the server starts.

Trace log: https://gist.github.com/nollymar/f3c18c38b1cb8a6d88c34d20a6554046

![Screen Shot 2020-08-03 at 11 55 54 AM](https://user-images.githubusercontent.com/8741395/89207464-64174c00-d580-11ea-8c22-d4b57d40a696.png)

**Comment by wezell** [comment]
I am also seeing a ton of this in my local log - now I get that I don't have the saml bundle in my codebase but, we all know osgi can get wonky and this much logging when osgi is struggling (every request) could quickly bring down a loaded server.



14:32:17.821  ERROR saml.DotSamlProxyFactory - Failure retrieving OSGI Service [interface com.dotcms.saml.SamlServiceBuilder] in bundle [com.dotcms.samlbundle]
java.lang.IllegalStateException: [com.dotcms.samlbundle] OSGI bundle NOT FOUND.
	at org.apache.felix.framework.OSGIUtil.getService(OSGIUtil.java:643) ~[classes/:?]
	at com.dotcms.saml.DotSamlProxyFactory.samlServiceBuilder(DotSamlProxyFactory.java:142) ~[classes/:?]
	at com.dotcms.saml.DotSamlProxyFactory.samlConfigurationService(DotSamlProxyFactory.java:181) ~[classes/:?]
	at com.dotcms.filters.interceptor.saml.SamlWebInterceptor.lambda$0(SamlWebInterceptor.java:98) ~[classes/:?]
	at io.vavr.control.Try.of(Try.java:75) ~[vavr-0.10.3.jar:?]
	at com.dotcms.filters.interceptor.saml.SamlWebInterceptor.samlConfig(SamlWebInterceptor.java:98) ~[classes/:?]
	at com.dotcms.filters.interceptor.saml.SamlWebInterceptor.intercept(SamlWebInterceptor.java:120) ~[classes/:?]
	at com.dotcms.filters.interceptor.SimpleWebInterceptorDelegateImpl.intercept(SimpleWebInterceptorDelegateImpl.java:193) ~[classes/:?]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.runInterceptors(AbstractWebInterceptorSupportFilter.java:38) ~[classes/:?]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:83) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.vanityurl.filters.VanityURLFilter.doFilter(VanityURLFilter.java:91) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176) ~[urlrewritefilter-4.0.4.jar:4.0.4]
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145) ~[urlrewritefilter-4.0.4.jar:4.0.4]

**Comment by nollymar** [comment]
Fixed on https://github.com/dotCMS/core/pull/19024

**Comment by nollymar** [comment]
**Note to QA:** 
An easy way to reproduce this issue is: 
1. Using a fresh installation, add Apps to the Menu
2. Shut the server down and replace the file `assets/server/secrets/dotSecretsStore.p12` by another file keeping the same name (it can be any file, the idea is to have a corrupted .p12 file)
3. Start the server. It should deploy correctly even when Apps is broken

**Comment by erickgonzalez** [comment]
Even though the `dotSecretsStore.p12` is corrupted the server starts and we log that there is an issue with the file.

**Comment by bryanboza** [comment]
Tested by @wezell

**Comment by nollymar** [comment]
Even after the fix, I kept seeing the logs: https://gist.github.com/nollymar/e392e1d77db1d762f8444770968607c0

I included a fix for 5.3.6.1: https://github.com/dotCMS/core/pull/19092/commits/4cd6b5f487e00d9f154060cf174b7bcbb9dea1b6

**Comment by bryanboza** [comment]
Still getting the error here, but to test I think we are missing some step here: 
- Run a fresh install and verify the file dotSecretsStore.p12 is created under assets/server/secrets when the server is up
- Stop the server and recreate the database keeping the assets folder
- Restart the server. You should see the error messages in catalina.out but the server deploys correctly
- Go to the apps portlet 

Tested on release-5.3.6.1 // Postgres // FF

**Comment by bryanboza** [comment]
Fixed, after the discussion seems that is ok that show the error when you got o the apps portlet, the idea is just not have this en every request. Tested on master // Postgres // FF
