### ISSUE TITLE
Deleting a content type with large amounts of content takes forever, times out

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19101]
We have customers with content types with large amounts of content objects - say 300,000 records.  When the customer goes to delete these content types, the system locks up and the deletion process times out.  We need a new pattern whereby we delete content types superficially - maybe just delete the entry from the structure table, and then we delete the content of the content type in a background stateful job .

Here is an associated thread dump

```
"url:DELETE//products.heatcraftrpd.com/api/v1/contenttype/id/fc3d3bb2-58d4-5a6c-8f02-5198650358b7 | lang:1 | ip:201.203.6.253 | Admin:true | start:08-10-2020 06:24:57 EDT  ref:https://prod-heatcraft.dotcmscloud.com/dotAdmin/" #339 daemon prio=5 os_prio=0 tid=0x00007f9e0557a000 nid=0x6989 runnable [0x00007f9c90302000]
   java.lang.Thread.State: RUNNABLE
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.dotmarketing.portlets.rules.business.RulesCacheImpl.putRulesByParent(RulesCacheImpl.java:101)
	at com.dotcms.enterprise.rules.h.getAllRulesByParent(SourceFile:102)
	at com.dotcms.enterprise.RulesFactoryProxy.getAllRulesByParent(SourceFile:65)
	at com.dotcms.enterprise.rules.g.getAllRulesByParent(SourceFile:186)
	at com.dotcms.enterprise.rules.g.deleteRulesByParent(SourceFile:248)
	at com.dotcms.enterprise.RulesAPIProxy.deleteRulesByParent(SourceFile:140)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.destroyContentlets(ESContentletAPIImpl.java:2126)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.internalDestroy(ESContentletAPIImpl.java:2026)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.destroy_aroundBody78(ESContentletAPIImpl.java:1998)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure79.run(ESContentletAPIImpl.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor$$Lambda$25/1977727340.execute(Unknown Source)
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:59)
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23)
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.destroy(ESContentletAPIImpl.java:1971)
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.destroy(ContentletAPIInterceptor.java:534)
	at com.dotcms.contenttype.business.ContentTypeFactoryImpl.deleteContentletsByType(ContentTypeFactoryImpl.java:541)
	at com.dotcms.contenttype.business.ContentTypeFactoryImpl.dbDelete(ContentTypeFactoryImpl.java:448)
	at com.dotcms.contenttype.business.ContentTypeFactoryImpl.delete(ContentTypeFactoryImpl.java:78)
	at com.dotcms.contenttype.business.ContentTypeAPIImpl.delete_aroundBody0(ContentTypeAPIImpl.java:81)
	at com.dotcms.contenttype.business.ContentTypeAPIImpl$AjcClosure1.run(ContentTypeAPIImpl.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor$$Lambda$25/1977727340.execute(Unknown Source)
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:59)
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23)
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41)
	at com.dotcms.contenttype.business.ContentTypeAPIImpl.delete(ContentTypeAPIImpl.java:77)
	at com.dotcms.rest.api.v1.contenttype.ContentTypeResource.deleteType(ContentTypeResource.java:291)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by wezell** [comment]
This task is dependent on either the quartz fix or the new scheduler implementation.

**Comment by swicken-dotcms** [comment]
Re-opening this as it's a remaining issue

**Comment by muhammadfaizandotcms** [comment]
Relevant Ticket: https://dotcms.zendesk.com/agent/tickets/110033

**Comment by damen-dotcms** [comment]
Hey @spbolton & @fabrizzio-dotCMS ,

Can you think through this and provide a summary of what might be causing this, and an estimate to resolve? Thanks!

**Comment by swicken-dotcms** [comment]
This also impacts bulk actions, not just content type deletes. It is not consistent either, it appears threads get 'stuck' processing very slowly. When that doesn't happen the deletes proceed normally (in the clients case 9500 took 1 hour).

**Comment by wezell** [comment]
Also, see this improvement request:
#24086

**Comment by wezell** [comment]
This strategy looks ok as long as the content type variable can be reused quickly, e.g. deleting a content type with a lot of records and then, while the background job is running, re-adding the content type.  I can see this happening with PP for example. We should have a quick brainstorm, things like
- How do deterministic ids play into this?
- Delete from index using a batch delete?
- Identifier collision
- performance of single item content delete - see #24086

**Comment by fabrizzio-dotCMS** [comment]
I've been pondering those things and it occurred to me that 
 we add a system CT like SYSTEM_RECYCLE excluded from ES 
and we send everything we want to remove asynchronously here. 

All Contentlets under this CT are destinated for removal using the Quartz Job This way we still can keep our constraints in place

**Comment by wezell** [comment]
Moving the content is going to be a heavier job than updating the `structure_inode` field I think.

**Comment by fabrizzio-dotCMS** [comment]
By moving I mean updating contentlet.structure_inode to point to a new CT. 
The problem I see modifying the CT we're about to delete. 
Like `structure.inode = 'MARKED_FOR_DELETE'` is that it only allows us to mark one CT at the time for removal

**Comment by wezell** [comment]
I mean, it could renamed 'MARKED_FOR_DELETE_{uuid}' or whatever and the job just picks up the everything that starts with 'MARKED_FOR_DELETE%;'

**Comment by bryanboza** [comment]
Fixed, tested in a large environment, not too big like the description (300k records),  but the delete process looks ok, and I'm able to delete records without problems. 

Tested on release-23.06 // Postgres // FF
