### ISSUE TITLE
Large amounts of content in structure can deadlock the DB when repermissioning

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19358]
If you are running a large dotCMS installation and you repermission a content type or host, we mark all the content records for reindex.  We do an "insert into" to fill the reindex table.  Our query here needs some performance tuning as this can deadlock a db if the amount of content is too large.

```
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy43.execute(Unknown Source)
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:609)
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:522)
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:261)
	at com.dotmarketing.common.reindex.ReindexQueueFactory.addStructureReindexEntries(ReindexQueueFactory.java:116)
	at com.dotmarketing.common.reindex.ReindexQueueAPIImpl.addStructureReindexEntries_aroundBody0(ReindexQueueAPIImpl.java:47)
	at com.dotmarketing.common.reindex.ReindexQueueAPIImpl$AjcClosure1.run(ReindexQueueAPIImpl.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor$$Lambda$31/803979942.execute(Unknown Source)
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:59)
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23)
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41)
	at com.dotmarketing.common.reindex.ReindexQueueAPIImpl.addStructureReindexEntries(ReindexQueueAPIImpl.java:46)
	at com.dotmarketing.business.PermissionBitFactoryImpl.resetPermissionReferences(PermissionBitFactoryImpl.java:2912)
	at com.dotmarketing.business.PermissionBitFactoryImpl.savePermission(PermissionBitFactoryImpl.java:1555)
	at com.dotmarketing.business.PermissionBitFactoryImpl.assignPermissions(PermissionBitFactoryImpl.java:1534)
	at com.dotmarketing.business.PermissionBitAPIImpl.assignPermissions_aroundBody24(PermissionBitAPIImpl.java:664)
	at com.dotmarketing.business.PermissionBitAPIImpl$AjcClosure25.run(PermissionBitAPIImpl.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor$$Lambda$31/803979942.execute(Unknown Source)
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:59)
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23)
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41)
	at com.dotmarketing.business.PermissionBitAPIImpl.assignPermissions(PermissionBitAPIImpl.java:618)
	at com.dotmarketing.business.ajax.PermissionAjax.saveAssetPermissions(PermissionAjax.java:298)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule$1.doFilter(CreatorModule.java:229)
	at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule.executeMethod(CreatorModule.java:241)
	at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:379)
	at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:332)
```

**Comment by wezell** [comment]
We have the structure on the `identifier` table.  There is no need to join the contentlet table to query the structure.

**Comment by dsilvam** [comment]
Passed Internal QA: Tested with custom dataset, repermissioning a Content Type with 100k content and checking the "Reset all children permissions to match the above". Took around 15 secs. Was taking around 2 min before the change.

**Comment by erickgonzalez** [comment]
Not back portable to 5.3.8 LTS, missing DB columns for queries.
