### ISSUE TITLE
Stop eating errors

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19621]
When we re-throw an exception, we need to include the original exception so as not to lose the original root cause of the exception.  Otherwise the error and error logging is unhelpful:

```
com.dotcms.publishing.DotBundleException: com.dotcms.publisher.util.DependencyManager : generate()Problem occured while publishing file: Unable to pull content 
at com.dotcms.enterprise.publishing.remote.bundler.DependencyBundler.generate(SourceFile:71) ~[ee-5.3.9.jar:?] 
at com.dotcms.publisher.ajax.RemotePublishAjaxAction.generateBundle_aroundBody0(RemotePublishAjaxAction.java:692) ~[dotcms_5.3.9_999999.jar:?] 
at com.dotcms.publisher.ajax.RemotePublishAjaxAction$AjcClosure1.run(RemotePublishAjaxAction.java:1) ~[dotcms_5.3.9_999999.jar:?] 
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?] 
at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.3.9_999999.jar:?] 
at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.3.9_999999.jar:?] 
at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.3.9_999999.jar:?] 
at com.dotcms.publisher.ajax.RemotePublishAjaxAction.generateBundle(RemotePublishAjaxAction.java:645) ~[dotcms_5.3.9_999999.jar:?] 
at com.dotcms.publisher.ajax.RemotePublishAjaxAction.downloadUnpushedBundle(RemotePublishAjaxAction.java:588) ~[dotcms_5.3.9_999999.jar:?] 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212] 
```

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/19622

**Comment by fabrizzio-dotCMS** [comment]
I introduced a couple of exceptions for the sake of testing if the message actually improves the stack trace. 
And sometimes the message can be null

Making the exception look like this:

```
Caused by: com.dotmarketing.business.DotStateException: Problem occured while publishing file:null
	at com.dotcms.publisher.util.DependencyManager.processList(DependencyManager.java:1223) ~[dotcms_master_42dfc95.jar:?]
	at com.dotcms.publisher.util.DependencyManager.setContentDependencies(DependencyManager.java:1345) ~[dotcms_master_42dfc95.jar:?]
	at com.dotcms.publisher.util.DependencyManager.setDependencies(DependencyManager.java:348) ~[dotcms_master_42dfc95.jar:?]
	at com.dotcms.enterprise.publishing.remote.bundler.DependencyBundler.generate(SourceFile:68) ~[ee-master-SNAPSHOT.jar:?]
	... 17 more
```


I don't think that there was anything wrong with the original approach 
where `Unable to pull content ` was the cause provided by a dotCMS custom exception.
It was hard to read but the info that leads o the cause was there. 

I think that doing this is not wrong
`	throw new DotStateException("Problem occurred while publishing file:", ex );`
Because it gives you a message with the overall situation and also provides you the cause.
Adding the message will not always improve the trace.
