### ISSUE TITLE
[Roles] : Improving error message when deleting Roles

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#19664]
Reported via Support: [102878](https://dotcms.zendesk.com/agent/tickets/102878)
Reproducible in dotCMS 20.10.1, and latest master.

It's highly common that customers perform Role cleanup tasks a few times a year. When they have a high number of Roles, it's very hard for a common user to remember where a given Role is being referenced. So, if they need to delete a Role and, for example, that Role is set in the `Assign To` field in a Workflow Action in any Workflow Scheme, they will see a database error message with no clues as to what happened.

**To Reproduce**
1. Create a dummy Role, and name it `My Test Role`.
2. Go to the **Workflows** portlet, select any Workflow Scheme, and add a dummy Workflow Action on any Workflow Step.
3. Make sure that the `Assign To` field points to the `My Test Role` you created.
4. Go back to the **Roles & Tools** portlet, and try to delete the `My Test Role`, the following error notification will be displayed in the browser:
```
A system error as occurred Error deleting object Could not execute JDBC batch update
```
Which disappears **VERY** quickly. And the following is shown in the log:
```
[07/12/20 17:04:55:959 GMT] INFO util.ActivityLogger: class com.dotmarketing.business.ajax.RoleAjax: system : Error Deleting Role , Date: 2020-12-07 17:04:55; User:dotcms.org.1; RoleID: 98d5824e-70e1-4397-9ff0-daa3aa5b6ca9
[07/12/20 17:04:55:959 GMT] INFO ajax.RoleAjax: Error Deleting Role : Date: 2020-12-07 17:04:55; User:dotcms.org.1; RoleID: 98d5824e-70e1-4397-9ff0-daa3aa5b6ca9
[07/12/20 17:04:55:959 GMT] INFO util.AdminLogger: class com.dotmarketing.business.ajax.RoleAjax : Error Deleting Role : Date: 2020-12-07 17:04:55; User:dotcms.org.1; RoleID: 98d5824e-70e1-4397-9ff0-daa3aa5b6ca9
[07/12/20 17:04:55:967 GMT] INFO log.accessLog: Method execution failed:
com.dotmarketing.exception.DotDataException: Error deleting object Could not execute JDBC batch update
at com.dotmarketing.business.RoleAPIImpl.delete_aroundBody10(RoleAPIImpl.java:182) ~[dotcms_20.11.1_999999.jar:?]
at com.dotmarketing.business.RoleAPIImpl$AjcClosure11.run(RoleAPIImpl.java:1) ~[dotcms_20.11.1_999999.jar:?]
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_20.11.1_999999.jar:?]
at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:59) ~[dotcms_20.11.1_999999.jar:?]
at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_20.11.1_999999.jar:?]
at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_20.11.1_999999.jar:?]
at com.dotmarketing.business.RoleAPIImpl.delete(RoleAPIImpl.java:137) ~[dotcms_20.11.1_999999.jar:?]
at com.dotmarketing.business.ajax.RoleAjax.deleteRole(RoleAjax.java:403) ~[dotcms_20.11.1_999999.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
...
...
``` 

**Expected behavior**
If a Role cannot be deleted, the UI and/or the logs should help the user figure out what happened, or now to solve the problem.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/19665

**Comment by alfredo-dotcms** [comment]
Internal QA done!

![image](https://user-images.githubusercontent.com/37185433/103018584-20ab8300-450b-11eb-8231-ac0b3573a389.png)

![image](https://user-images.githubusercontent.com/37185433/103018722-4cc70400-450b-11eb-89c8-d16b0477b94f.png)

fixed on master

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
