### ISSUE TITLE
Tuckey missing proxy class

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19663]
We use a Tuckey Filter of type "proxy", but every time it executes, it throws an exception about missing the org.apache.commons.httpclient.HostConfiguration class, which is part of the org.tuckey.urlrewritefilter library dependencies.

The dotCMS v4.3.3 instance includes Apache HttpClient library, but it looks like v5.3.8 does not.

This might be why we have had issues with the `/dotsaml` endpoint as well.

```
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/httpclient/HostConfiguration 
at org.tuckey.web.filters.urlrewrite.RequestProxy.execute(RequestProxy.java:102) ~[urlrewritefilter-4.0.4.jar:4.0.4] 
at org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:277) ~[urlrewritefilter-4.0.4.jar:4.0.4] 
at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:171) ~[urlrewritefilter-4.0.4.jar:4.0.4] 
at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145) ~[urlrewritefilter-4.0.4.jar:4.0.4] 
at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92) ~[urlrewritefilter-4.0.4.jar:4.0.4] 
at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389) ~[urlrewritefilter-4.0.4.jar:4.0.4] 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32] 

```

**Comment by jcastro-dotcms** [comment]
One more customer report: https://dotcms.zendesk.com/agent/tickets/103772
