### ISSUE TITLE
Error when editing templates (NumberFormatException for input string "LEGACY_RELATION_TYPE")

### ISSUE THREAD

**Issue by splotzky** [dotCMS/core#19692]
**Describe the bug**
We get an error message when we try to edit our templates under 'Site' > 'Templates':

```
An unexpected system error occurred.

javax.servlet.ServletException: com.dotcms.repackage.javax.portlet.PortletException
```

**To Reproduce**
This bug is not reproducible on 'demo.dotcms.com/dotAdmin', but the root cause in the stacktrace of our logs shows this error message:

```
java.lang.NumberFormatException: For input string: "LEGACY_RELATION_TYPE"
```

In our dotCMS database, the string 'LEGACY_RELATION_TYPE' only appears in the table 'multi_tree', column 'relation_type'. Almost all records in this table have the string 'LEGACY_RELATION_TYPE' set in the column 'relation_type'. Only the latest records have a number in this column.

So it could be a data migration issue. Our upgrade path over the past 18 months has been from dotCMS version 5.1.6 to 5.2.8 to 5.3.6.1 and finally to 20.11.

**Expected behavior**
The templates should be editable without any errors.

**Additional context**
Here is the complete stacktrace:

```
ERROR portlet.PortletRequestDispatcherImpl: org.apache.jasper.JasperException: An exception occurred processing JSP page [/html/portlet/ext/templates/design/design_templates.jsp] at line [344]

341: 
342: <%
343: 	final StringBuffer maxUUIDStr = new StringBuffer("{");
344: 	final Map<String, Long> maxUUID = DotTemplateTool.getMaxUUID(template);
345: 
346: 	for (Map.Entry<String, Long> maxUUIDEntry : maxUUID.entrySet()) {
347: 		maxUUIDStr.append("'" + maxUUIDEntry.getKey() + "'");


Stacktrace:
org.apache.jasper.JasperException: org.apache.jasper.JasperException: An exception occurred processing JSP page [/html/portlet/ext/templates/design/design_templates.jsp] at line [344]

341: 
342: <%
343: 	final StringBuffer maxUUIDStr = new StringBuffer("{");
344: 	final Map<String, Long> maxUUID = DotTemplateTool.getMaxUUID(template);
345: 
346: 	for (Map.Entry<String, Long> maxUUIDEntry : maxUUID.entrySet()) {
347: 		maxUUIDStr.append("'" + maxUUIDEntry.getKey() + "'");


Stacktrace:
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:565) ~[jasper.jar:8.5.32]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466) ~[jasper.jar:8.5.32]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386) ~[jasper.jar:8.5.32]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330) ~[jasper.jar:8.5.32]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:591) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:527) ~[catalina.jar:8.5.32]
	at com.liferay.portlet.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:206) ~[dotcms_20.11_e2cd856.jar:?]
	at com.liferay.portal.struts.PortletRequestProcessor.doInclude(PortletRequestProcessor.java:339) ~[dotcms_20.11_e2cd856.jar:?]
	at com.liferay.portal.struts.PortletRequestProcessor.doForward(PortletRequestProcessor.java:314) ~[dotcms_20.11_e2cd856.jar:?]
	at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processTilesDefinition(TilesRequestProcessor.java:239) ~[dot.struts-1.2.10_1.jar:?]
	at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processForwardConfig(TilesRequestProcessor.java:302) ~[dot.struts-1.2.10_1.jar:?]
	at com.dotcms.repackage.com.oroad.stxx.plugin.StxxTilesRequestProcessor.processForwardConfig(StxxTilesRequestProcessor.java:134) ~[dot.stxx-1.3_3.jar:?]
	at com.liferay.portal.struts.PortletRequestProcessor.processForwardConfig(PortletRequestProcessor.java:201) ~[dotcms_20.11_e2cd856.jar:?]
	at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:241) ~[dot.struts-1.2.10_1.jar:?]
	at com.liferay.portal.struts.PortletRequestProcessor.process(PortletRequestProcessor.java:87) ~[dotcms_20.11_e2cd856.jar:?]
	at com.liferay.portlet.StrutsPortlet.include(StrutsPortlet.java:152) ~[dotcms_20.11_e2cd856.jar:?]
	at com.liferay.portlet.StrutsPortlet.doView(StrutsPortlet.java:104) ~[dotcms_20.11_e2cd856.jar:?]
	at com.dotcms.repackage.javax.portlet.GenericPortlet.doDispatch(GenericPortlet.java:235) ~[dot.portlet-1.0_2.jar:?]
	at com.dotcms.repackage.javax.portlet.GenericPortlet.render(GenericPortlet.java:163) ~[dot.portlet-1.0_2.jar:?]
	at com.liferay.portlet.ConcretePortletWrapper.render(ConcretePortletWrapper.java:114) ~[dotcms_20.11_e2cd856.jar:?]
	at org.apache.jsp.html.portal.layout_jsp._jspService(layout_jsp.java:625) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:8.5.32]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443) ~[jasper.jar:8.5.32]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386) ~[jasper.jar:8.5.32]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330) ~[jasper.jar:8.5.32]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:591) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:527) ~[catalina.jar:8.5.32]
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:892) ~[jasper.jar:8.5.32]
	at org.apache.jsp.html.portal.layout_005fportal_jsp._jspService(layout_005fportal_jsp.java:1583) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:8.5.32]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443) ~[jasper.jar:8.5.32]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386) ~[jasper.jar:8.5.32]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330) ~[jasper.jar:8.5.32]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316) ~[catalina.jar:8.5.32]
	at com.liferay.portal.struts.StrutsUtil.forward(StrutsUtil.java:72) ~[dotcms_20.11_e2cd856.jar:?]
	at com.liferay.portal.struts.PortalRequestProcessor.doForward(PortalRequestProcessor.java:161) ~[dotcms_20.11_e2cd856.jar:?]
	at com.dotmarketing.struts.PortalRequestProcessor.doForward(PortalRequestProcessor.java:48) ~[dotcms_20.11_e2cd856.jar:?]
	at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processTilesDefinition(TilesRequestProcessor.java:239) ~[dot.struts-1.2.10_1.jar:?]
	at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processForwardConfig(TilesRequestProcessor.java:302) ~[dot.struts-1.2.10_1.jar:?]
	at com.dotcms.repackage.com.oroad.stxx.plugin.StxxTilesRequestProcessor.processForwardConfig(StxxTilesRequestProcessor.java:134) ~[dot.stxx-1.3_3.jar:?]
	at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:241) ~[dot.struts-1.2.10_1.jar:?]
	at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:147) ~[dotcms_20.11_e2cd856.jar:?]
	at com.dotcms.repackage.org.apache.struts.action.ActionServlet.process(ActionServlet.java:1202) ~[dot.struts-1.2.10_1.jar:?]
	at com.dotcms.repackage.org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:412) ~[dot.struts-1.2.10_1.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[servlet-api.jar:?]
	at com.liferay.portal.servlet.MainServlet.callParentService(MainServlet.java:249) ~[dotcms_20.11_e2cd856.jar:?]
	at com.liferay.portal.servlet.MainServlet.service(MainServlet.java:449) ~[dotcms_20.11_e2cd856.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.repackage.com.liferay.filters.secure.SecureFilter.doFilter(SecureFilter.java:135) ~[dot.secure-filter-ukv_2.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.CMSFilter.doFilterInternal(CMSFilter.java:198) ~[dotcms_20.11_e2cd856.jar:?]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:48) ~[dotcms_20.11_e2cd856.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_20.11_e2cd856.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_20.11_e2cd856.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.vanityurl.filters.VanityURLFilter.doFilter(VanityURLFilter.java:93) ~[dotcms_20.11_e2cd856.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:134) ~[dotcms_20.11_e2cd856.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:88) ~[dotcms_20.11_e2cd856.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:48) ~[dotcms_20.11_e2cd856.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:99) ~[dotcms_20.11_e2cd856.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_20.11_e2cd856.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176) ~[urlrewritefilter-4.0.4.jar:4.0.4]
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145) ~[urlrewritefilter-4.0.4.jar:4.0.4]
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92) ~[urlrewritefilter-4.0.4.jar:4.0.4]
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389) ~[urlrewritefilter-4.0.4.jar:4.0.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.NormalizationFilter.doFilter(NormalizationFilter.java:73) ~[dotcms_20.11_e2cd856.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[catalina.jar:8.5.32]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) ~[catalina.jar:8.5.32]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[catalina.jar:8.5.32]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[catalina.jar:8.5.32]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) ~[catalina.jar:8.5.32]
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:479) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:8.5.32]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.32]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: org.apache.jasper.JasperException: An exception occurred processing JSP page [/html/portlet/ext/templates/design/design_templates.jsp] at line [344]

341: 
342: <%
343: 	final StringBuffer maxUUIDStr = new StringBuffer("{");
344: 	final Map<String, Long> maxUUID = DotTemplateTool.getMaxUUID(template);
345: 
346: 	for (Map.Entry<String, Long> maxUUIDEntry : maxUUID.entrySet()) {
347: 		maxUUIDStr.append("'" + maxUUIDEntry.getKey() + "'");


Stacktrace:
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:584) ~[jasper.jar:8.5.32]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:481) ~[jasper.jar:8.5.32]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386) ~[jasper.jar:8.5.32]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330) ~[jasper.jar:8.5.32]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:591) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:527) ~[catalina.jar:8.5.32]
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:892) ~[jasper.jar:8.5.32]
	at org.apache.jsp.html.portal.layout_005fportal_jsp._jspService(layout_005fportal_jsp.java:630) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:8.5.32]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443) ~[jasper.jar:8.5.32]
	... 127 more
Caused by: java.lang.NumberFormatException: For input string: "LEGACY_RELATION_TYPE"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_252]
	at java.lang.Long.parseLong(Long.java:589) ~[?:1.8.0_252]
	at java.lang.Long.parseLong(Long.java:631) ~[?:1.8.0_252]
	at com.dotcms.rendering.velocity.viewtools.DotTemplateTool.getMaxUUID(DotTemplateTool.java:372) ~[dotcms_20.11_e2cd856.jar:?]
	at org.apache.jsp.html.portlet.ext.templates.design.design_005ftemplates_jsp._jspService(design_005ftemplates_jsp.java:1933) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:8.5.32]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443) ~[jasper.jar:8.5.32]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386) ~[jasper.jar:8.5.32]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330) ~[jasper.jar:8.5.32]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:591) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:527) ~[catalina.jar:8.5.32]
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:892) ~[jasper.jar:8.5.32]
	at org.apache.jsp.html.portal.layout_005fportal_jsp._jspService(layout_005fportal_jsp.java:630) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:8.5.32]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443) ~[jasper.jar:8.5.32]
	... 127 more
ERROR portlet.StrutsPortlet: org.apache.jasper.JasperException: An exception occurred processing JSP page [/html/portlet/ext/templates/design/design_templates.jsp] at line [344]

341: 
342: <%
343: 	final StringBuffer maxUUIDStr = new StringBuffer("{");
344: 	final Map<String, Long> maxUUID = DotTemplateTool.getMaxUUID(template);
345: 
346: 	for (Map.Entry<String, Long> maxUUIDEntry : maxUUID.entrySet()) {
347: 		maxUUIDStr.append("'" + maxUUIDEntry.getKey() + "'");


Stacktrace:
ERROR servlet.MainServlet: javax.servlet.ServletException: com.dotcms.repackage.javax.portlet.PortletException
```

**Comment by splotzky** [comment]
With dotCMS version 21.01 we still have this issue. How did the string 'LEGACY_RELATION_TYPE' get into our database table 'multi_tree'? Most likely from a migration script during a dotCMS upgrade. Would you agree with that?

**Comment by splotzky** [comment]
After debugging dotCMS we were able to fix this issue ourselves. We needed to migrate our older templates directly in the database:

- In table 'template', columns 'body' and 'drawed_body' we have replaced all occurrences of `#parseContainer('<containerIdentifier>')` with `#parseContainer('<containerIdentifier>','1')`
- In table 'multi_tree', column 'relation_type' we have replaced all occurrences of `LEGACY_RELATION_TYPE` with `1`

Now we can edit all templates again.
