### ISSUE TITLE
Content not saving in edit mode

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19717]
When you add a contentlet to a container I'm getting this error:

### STR
1. Create a template, theme, container etc...
2. Create a page
3. Add a content
4. See the error.

```
17:27:30.223  ERROR db.DotConnect - Batch entry 0 insert into multi_tree (parent1, parent2, child, relation_type, tree_order, personalization) values ('940bae52-be03-4774-b748-b39238f7607e','d71d56b4-0a8b-4bb2-be15-ffa5a23366ea','0207b411-b66a-4bcf-8da1-e3ab81db47c3','1',0,'dot:default')   was aborted: ERROR: duplicate key value violates unique constraint "multi_tree_pkey"
  Detail: Key (child, parent1, parent2, relation_type, personalization)=(0207b411-b66a-4bcf-8da1-e3ab81db47c3, 940bae52-be03-4774-b748-b39238f7607e, d71d56b4-0a8b-4bb2-be15-ffa5a23366ea, 1, dot:default) already exists.  Call getNextException to see other errors in the batch.
java.sql.BatchUpdateException: Batch entry 0 insert into multi_tree (parent1, parent2, child, relation_type, trade, personalization) values ('940bae52-be03-4774-b748-b39238f7607e','d71d56b4-0a8b-4bb2-be15-ffa5a23366ea','0207b411-b66a-4bcf-8da1-e3ab81db47c3','1',0,'dot:default')   was aborted: ERROR: duplicate key value violates unique constraint "multi_tree_pkey"
  Detail: Key (child, parent1, parent2, relation_type, personalization)=(0207b411-b66a-4bcf-8da1-e3ab81db47c3, 940bae52-be03-4774-b748-b39238f7607e, d71d56b4-0a8b-4bb2-be15-ffa5a23366ea, 1, dot:default) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148) ~[postgresql-42.2.8.jar:42.2.8]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2234) ~[postgresql-42.2.8.jar:42.2.8]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:510) ~[postgresql-42.2.8.jar:42.2.8]
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:853) ~[postgresql-42.2.8.jar:42.2.8]
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1546) ~[postgresql-42.2.8.jar:42.2.8]
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[HikariCP-3.4.2.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.2.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeBatch_aroundBody0(DotConnect.java:1083) ~[dotcms_master_cc8d136.jar:?]
	at com.dotmarketing.common.db.DotConnect$AjcClosure1.run(DotConnect.java:1) ~[dotcms_master_cc8d136.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_master_cc8d136.jar:?]
```

**Comment by nollymar** [comment]
I was not able to reproduce this issue on release-20.12. However, I found this one: https://github.com/dotCMS/core/issues/19720

**Comment by ivorpad** [comment]
I could not reproduce this bug.

Tested on release-21.02 with empty starter.

Log:

```bash
22:48:44.198  INFO  util.ActivityLogger - class com.dotcms.content.elasticsearch.business.ESContentletAPIImpl: default : Saving Content , StartDate: N/D; EndDate: N/D; User:dotcms.org.1; ContentIdentifier:
22:48:44.258  INFO  timedcache.TimedCacheProvider - ***	 Building Cache : esquerycache, size:10000, seconds:3600,Concurrency:32 (every 60000 millis)
22:48:44.447  INFO  util.ActivityLogger - class com.dotcms.content.elasticsearch.business.ESContentletAPIImpl: default : Content Saved , StartDate: N/D; EndDate: N/D; User:dotcms.org.1; ContentIdentifier: 5e029979-ea57-420b-886e-b46d50797442
22:48:44.528  INFO  util.ActivityLogger - class com.dotcms.content.elasticsearch.business.ESContentletAPIImpl: default : Publishing Content , StartDate: N/D; EndDate: N/D; User:dotcms.org.1; ContentIdentifier: 5e029979-ea57-420b-886e-b46d50797442
22:48:44.585  INFO  util.ActivityLogger - class com.dotcms.content.elasticsearch.business.ESContentletAPIImpl: default : Content Published , StartDate: N/D; EndDate: N/D; User:dotcms.org.1; ContentIdentifier: 5e029979-ea57-420b-886e-b46d50797442
22:48:44.592  INFO  caffine.CaffineCache - ***	 Building Cache : blockdirectivehtmlpagecache, size:1000,Concurrency:32
22:48:44.603  INFO  util.SecurityLogger - class com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl : The Workflow task with id:9c573eaf-600a-4948-87d9-a44f2ff31887 has been saved. -- ip:127.0.0.1,user:Admin User [ID: dotcms.org.1][email:admin@dotcms.com]
22:48:44.609  INFO  util.SecurityLogger - class com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl : The Workflow History with id:bd09abe4-0437-4f9d-b3f9-9ca003cb8ef5 was saved. -- ip:127.0.0.1,user:Admin User [ID: dotcms.org.1][email:admin@dotcms.com]
22:48:44.609  INFO  business.WorkflowAPIImpl - Needs reindex, adding the contentlet to the index at the end of the workflow execution
22:48:44.609  INFO  business.ContentletIndexAPIImpl - Indexing: 5e029979-ea57-420b-886e-b46d50797442 : page, includeDependencies: true, policy: DEFER
22:48:44.611  INFO  reindex.ReindexQueueAPIImpl - addIdentifierReindex: 5e029979-ea57-420b-886e-b46d50797442
22:48:44.613  INFO  business.WorkflowAPIImpl - Added contentlet to the index at the end of the workflow execution, dependencies: true
22:48:44.613  INFO  reindex.ReindexQueueAPIImpl - addIdentifierReindex: 5e029979-ea57-420b-886e-b46d50797442
22:48:44.906  INFO  caffine.CaffineCache - ***	 Building Cache : pagemultitreesworking, size:1000,Concurrency:32
22:48:45.010  INFO  caffine.CaffineCache - ***	 Building Cache : tagsbyinodecache, size:1000,Concurrency:32
22:48:45.184  INFO  reindex.ReindexThread - ---  ReindexThread total/todo/bulk: 8/1/2
22:48:45.710  INFO  caffine.CaffineCache - ***	 Building Cache : taginodesbyinodecache, size:1000,Concurrency:32
```
