### ISSUE TITLE
graphql query of [Blog] -> [related File with Category field] produces error 

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#19728]
**Describe the bug**
Graphql query that includes a Category field on a File Content Type, queried via a relationship with another Content Type, produces an error

**To Reproduce**
Steps to reproduce the behavior on demo.dotcms.com:
1. Add a category field e.g. "Product Line" to the File Content Type
2. Add a 1-to-many relationship between Blog and File 
3. Associate a Blog to multiple Files
4. submit Graphql query:
```
query { 
  BlogCollection(limit: 10) { 
    identifier 
      files { 
      title 
      productLineCategories { 
        keywords 
        name 
        active 
        velocityVar 
        key 
      } } } }
```
Response:
```
{  "errors": [
    {
      "message": "Internal Server Error(s) while executing query"
    }
  ],
  "data": {
    "BlogCollection": [
      {
        "identifier": "8526e60b-ede5-470a-9962-adfc2b6ef354",
        "files": [
          {
            "title": "html_head.vtl",
            "productLineCategories": null
          }, ...
```
partial stack trace:
```
20:50:10.680 ERROR datafetcher.CategoryFieldDataFetcher - null value in entry: keywords=null 
java.lang.NullPointerException: null value in entry: keywords=null	
at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32) ~[guava-27.0.1-android.jar:?] 
at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:249) ~[guava-27.0.1-android.jar:?] 
at com.dotmarketing.portlets.contentlet.transform.strategy.CategoryViewStrategy.transform(CategoryViewStrategy.java:104) ~[dotcms_5.3.9_999999.jar:?] 
at com.dotmarketing.portlets.contentlet.transform.strategy.CategoryViewStrategy.transform(CategoryViewStrategy.java:86) ~[dotcms_5.3.9_999999.jar:?] 
at com.dotmarketing.portlets.contentlet.transform.strategy.CategoryViewStrategy.transform(CategoryViewStrategy.java:61) ~[dotcms_5.3.9_999999.jar:?] 
at com.dotmarketing.portlets.contentlet.transform.strategy.AbstractTransformStrategy.apply(AbstractTransformStrategy.java:95) ~[dotcms_5.3.9_999999.jar:?] 
at com.dotmarketing.portlets.contentlet.transform.DotContentletTransformerImpl.lambda$3(DotContentletTransformerImpl.java:102) ~[dotcms_5.3.9_999999.jar:?]
```

**Comment by yolabingo** [comment]
cloud support ticket https://dotcms.zendesk.com/agent/tickets/103071

**Comment by nollymar** [comment]
Passed internal QA

**Comment by bryanboza** [comment]
Fixed, now this query is working as expected... Tested on release-20.12 // Postgres 
![image](https://user-images.githubusercontent.com/2641437/103567580-b0491e00-4e89-11eb-841f-9d1773f40527.png)
