### ISSUE TITLE
GraphQL API is requring language

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19827]
If you ask containers from the page without passing the language:

```
query Page {
  page(url: "index") {
    containers {
      name
    }
  }
}
```

You get an error:

```
15:01:19.060  ERROR page.ContainersDataFetcher - null
java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:552) ~[?:1.8.0_211]
	at java.lang.Long.parseLong(Long.java:631) ~[?:1.8.0_211]
	at com.dotcms.graphql.datafetcher.page.ContainersDataFetcher.get(ContainersDataFetcher.java:40) ~[dotcms_master_107f2eb.jar:?]
	at com.dotcms.graphql.datafetcher.page.ContainersDataFetcher.get(ContainersDataFetcher.java:1) ~[dotcms_master_107f2eb.jar:?]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270) ~[graphql-java-13.0.jar:?]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:198) ~[graphql-java-13.0.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:74) ~[graphql-java-13.0.jar:?]
	at graphql.execution.ExecutionStrategy.
```

You need to pass the language like:

```
{
  page(url: "index", languageId: "1") {
    containers {
      name
    }
  }
}
```

It should default to the default language.

**Comment by bryanboza** [comment]
Fixed, now we take the default one... Tested on release-21.05 // Postgres // FF
