### ISSUE TITLE
PP error pushing any bundle 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19897]
In the release branch, if you try to push any piece of content we are getting a NPE error in the log, even the bundle status say success
```
16:05:00.333  ERROR business.PublisherQueueJob - An error occurred when trying to publish bundles: null
java.lang.NullPointerException: null
	at com.liferay.portal.language.LanguageUtil.get(LanguageUtil.java:298) ~[dotcms_21.02_ae0d8e9.jar:?]
	at com.dotcms.publisher.business.PublisherQueueJob.updateBundleStatus(PublisherQueueJob.java:375) ~[dotcms_21.02_ae0d8e9.jar:?]
	at com.dotcms.publisher.business.PublisherQueueJob.updateAuditStatus(PublisherQueueJob.java:232) ~[dotcms_21.02_ae0d8e9.jar:?]
	at com.dotcms.publisher.business.PublisherQueueJob.execute_aroundBody0(PublisherQueueJob.java:121) ~[dotcms_21.02_ae0d8e9.jar:?]
	at com.dotcms.publisher.business.PublisherQueueJob$AjcClosure1.run(PublisherQueueJob.java:1) ~[dotcms_21.02_ae0d8e9.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_21.02_ae0d8e9.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_21.02_ae0d8e9.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_21.02_ae0d8e9.jar:?]
	at com.dotcms.publisher.business.PublisherQueueJob.execute(PublisherQueueJob.java:111) ~[dotcms_21.02_ae0d8e9.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223) ~[dot.quartz-all-1.8.6_2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) ~[dot.quartz-all-1.8.6_2.jar:?]
```

**To Reproduce**
- Login as admin
- Configure your push env
- Add a new piece of content 
- Push Publish it 
- Check your log file 

**Expected behavior**
We need be able to push without problems

**Desktop (please complete the following information):**
Tested on release-21.02 // Postgres // FF. This for both environments

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/19899
