### ISSUE TITLE
Problems with the Reindex thread starting with the empty starter 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#19959]
After the last changes in the release branch, we fix some problems causing during the upgrade, but one of this fixes is causing an error when you try to start a clean instance with the empty starter 
Error: 
```
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method) ~[?:1.8.0_211]
	at com.dotmarketing.util.ThreadUtils.sleep(ThreadUtils.java:51) ~[classes/:?]
	at com.dotmarketing.common.reindex.ReindexThread.runReindexLoop(ReindexThread.java:235) ~[classes/:?]
	at com.dotmarketing.common.reindex.ReindexThread.lambda$1(ReindexThread.java:154) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_211]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
```
To reproduce just need to start a fresh install with the empty starter in any DB. 

This error message will log indefinitely 

**Expected behavior**
We need to be able to start without problems 

**Desktop (please complete the following information):**
tested on release 21.02 // Postgres // FF

**Comment by dsilvam** [comment]
Fix: https://github.com/dotCMS/core/commit/470fb6a8563391becaec9df6456981cc2c09f4cb

**Comment by bryanboza** [comment]
Fixed, tested with the follow cases: 

- Tested starting with the empty starter
- Initial starter site import
- Upgrade
- Restarting after initial start
