### ISSUE TITLE
[workflow] : The "Send an Email" sub-action fails if executed before "Save content" sub-action

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#19993]
Found when working on Support: [103557](https://dotcms.zendesk.com/agent/tickets/103557)
Reproducible in dotCMS 5.3.8.2, and latest master.

The `Send an Email` sub-action sends an email with the specified content to the specified list of users: https://dotcms.com/docs/latest/workflow-sub-actions#Params . However, when it's called before calling the `Save content` sub-action, even though the content is successfully saved, it fails to send the expected email. Also, an error is logged to the dotcms.log file.

**To Reproduce**
1. Make sure the Mail Configuration in your dotCMS instance is all set.
2. Create a new Workflow Scheme called `Feedback`, with one Step called `New`, and one action called `Pending`. In the `Pending` action, set the following properties:
2.1. Next Step: `Current Step`
2.2. Show When: `Editing`, `Locked`, `New`, `Unpublished`
2.3. Assign To: `Current User`
2.4. Sub-actions:
2.4.1. `Velocity Script Actionlet`:
2.4.1.1. Script Code: `$content.setProperty("subject", "Feedback: ${content.subject}")`
2.4.1.2 Contentlet Result Property Name: `result`
2.4.2. `Send an Email`:
2.4.2.1. From Email: Put your configured email address here.
2.4.2.2. From Name: `Support Test Name`
2.4.2.3. To Email: The email address that will receive the notification.
2.4.2.4. To Name: `$content.name`
2.4.2.5. Email Subject: `Feedback Confirmation (from Pending)`
2.4.2.6. Email Body (html): `You submitted the following feedback: $content.email`
2.4.3. `Save content`:
3. Create a test Content Type called `My Test CT` with two simple text fields. Set the `Feedback` Workflow in this CT.
4. Go to the **Search** portlet and add a new content of type `My Test CT`.
5. The contentlet is saved. However, the email notification is never sent, and the following error is shown in the log:
```
13:19:12.712  ERROR actionlet.EmailActionlet - null
java.lang.NullPointerException: null
	at com.dotmarketing.portlets.workflows.actionlet.EmailActionlet.executeAction(EmailActionlet.java:104) ~[dotcms_5.3.8.2_01deb9e.jar:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireWorkflowPostCheckin_aroundBody166(WorkflowAPIImpl.java:2318) ~[dotcms_5.3.8.2_01deb9e.jar:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl$AjcClosure167.run(WorkflowAPIImpl.java:1) ~[dotcms_5.3.8.2_01deb9e.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.3.8.2_01deb9e.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:59) ~[dotcms_5.3.8.2_01deb9e.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_5.3.8.2_01deb9e.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_5.3.8.2_01deb9e.jar:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireWorkflowPostCheckin(WorkflowAPIImpl.java:2298) ~[dotcms_5.3.8.2_01deb9e.jar:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.lambda$64(WorkflowAPIImpl.java:3015) ~[dotcms_5.3.8.2_01deb9e.jar:?]
	at com.dotcms.util.ThreadContextUtil.wrapVoidNoReindex(ThreadContextUtil.java:85) ~[dotcms_5.3.8.2_01deb9e.jar:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireContentWorkflow_aroundBody180(WorkflowAPIImpl.java:3015) ~[dotcms_5.3.8.2_01deb9e.jar:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl$AjcClosure181.run(WorkflowAPIImpl.java:1) ~[dotcms_5.3.8.2_01deb9e.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.3.8.2_01deb9e.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:59) ~[dotcms_5.3.8.2_01deb9e.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_5.3.8.2_01deb9e.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_5.3.8.2_01deb9e.jar:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireContentWorkflow(WorkflowAPIImpl.java:2992) ~[dotcms_5.3.8.2_01deb9e.jar:?]
	at com.dotmarketing.portlets.contentlet.business.web.ContentletWebAPIImpl.saveWebAsset(ContentletWebAPIImpl.java:509) ~[dotcms_5.3.8.2_01deb9e.jar:?]
	at com.dotmarketing.portlets.contentlet.business.web.ContentletWebAPIImpl.saveContent_aroundBody0(ContentletWebAPIImpl.java:135) ~[dotcms_5.3.8.2_01deb9e.jar:?]
	at com.dotmarketing.portlets.contentlet.business.web.ContentletWebAPIImpl$AjcClosure1.run(ContentletWebAPIImpl.java:1) ~[dotcms_5.3.8.2_01deb9e.jar:?]
...
...
```

**Expected behavior**
The `Send an  Email` sub-action should not fail either before or after calling the `Save content` sub-action.

**Additional context**
The currently valid workaround is to call the `Send an Email` sub-action **BEFORE** calling the `Save content` sub-action.

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/20074

**Comment by bryanboza** [comment]
Fixed, tested following the provided steps and I'm unable to reproduce the problem after the changes.
