### ISSUE TITLE
Elasticsearch RestHighLevelClient does not handle RuntimeExceptions

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19992]
This could be named: dotCMS is unable to recover if we get a
```
java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED 
```
For various reasons, RuntimeExceptions get thrown when interacting with Elasticsearch. We do it in our code when searching or putting content to ES or searching content or it can happen outside of dotCMS in the case of memory or networks issues.   I think most people using Elasticsearch expect the `RestHighLevelClient ` code higher up in the stack to catch these exceptions and deal with them appropriately.   The issue is that Elasticsearch's `RestHighLevelClient` and the ES `Request` Objects are built to catch `Exceptions` and not `RuntimeExceptions`.  When a `RunTimeException` is thrown, what happens instead is the `RunTimeException` continues to propagate upwards until it hits the Apache HttpClient and basically destroys the Apache HttpClient connection. When this happens, the HttpClient does not recover and only a server restart will rebuild the HTTPClient - in a perfect world the HttpClient Connection should be rebuilt but this does not seem to happen.

There are 2 things we need to do: 
1. We need to rebuild our `RestHighLevelClient` when we see an `IllegalStateException` `reactor status: STOPPED `
2. We need to wrap all our calls that expect to use the `RestHighLevelClient` in trys that catch `RuntimeExceptions` and rethrow them as `DotElasticsearchException`

### For reference:
elastic/elasticsearch#39946
elastic/elasticsearch#45115
elastic/elasticsearch#42133

Logs showing the exception
---
Searching:
https://gist.github.com/wezell/ab8e3ebaf33a5f03c09de8f7c85c4920

Reindexing:
https://gist.github.com/wezell/06f25aa7f82aba26c3cb3b3be44c2985

**Comment by dsilvam** [comment]
Note to QA: Asked me for the steps to reproduce

**Comment by victoralfaro-dotcms** [comment]
When starting up:
```
12:43:34.821  ERROR util.DotRestHighLevelClientProvider$1 - [host=https://localhost:9200]
12:43:38.516  ERROR util.DotRestHighLevelClientProvider$1 - [host=https://localhost:9200]
12:43:38.517  ERROR client.InternalHttpAsyncClient - I/O reactor terminated abnormally
java.lang.IllegalStateException: java.lang.IllegalStateException: java.net.ConnectException: Connection refused
	at com.dotcms.content.elasticsearch.business.ESIndexAPI$1.onFailure(ESIndexAPI.java:1450) ~[dotcms_21.03_cc9a997.jar:?]
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:564) ~[elasticsearch-rest-client-7.3.2.jar:7.3.2]
	at org.elasticsearch.client.RestClient$1.failed(RestClient.java:326) ~[elasticsearch-rest-client-7.3.2.jar:7.3.2]
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137) ~[httpcore-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionFailed(DefaultClientExchangeHandlerImpl.java:101) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:426) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestFailed(AbstractClientExchangeHandler.java:348) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$100(AbstractClientExchangeHandler.java:62) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.failed(AbstractClientExchangeHandler.java:392) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137) ~[httpcore-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$1.failed(PoolingNHttpClientConnectionManager.java:316) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137) ~[httpcore-4.4.11.jar:4.4.11]
	at org.apache.http.nio.pool.RouteSpecificPool.failed(RouteSpecificPool.java:162) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.nio.pool.AbstractNIOConnPool.requestFailed(AbstractNIOConnPool.java:609) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.failed(AbstractNIOConnPool.java:889) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.reactor.SessionRequestImpl.failed(SessionRequestImpl.java:160) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:173) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.lang.IllegalStateException: java.net.ConnectException: Connection refused
	at com.dotcms.content.elasticsearch.business.ESIndexAPI$1.onFailure(ESIndexAPI.java:1450) ~[dotcms_21.03_cc9a997.jar:?]
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:564) ~[elasticsearch-rest-client-7.3.2.jar:7.3.2]
	at org.elasticsearch.client.RestClient$1.failed(RestClient.java:323) ~[elasticsearch-rest-client-7.3.2.jar:7.3.2]
	... 19 more
	Suppressed: java.net.ConnectException: Connection refused
		at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_251]
		at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_251]
		at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:171) ~[httpcore-nio-4.4.11.jar:4.4.11]
		at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145) ~[httpcore-nio-4.4.11.jar:4.4.11]
		at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351) ~[httpcore-nio-4.4.11.jar:4.4.11]
		at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221) ~[httpasyncclient-4.1.4.jar:4.1.4]
		at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) ~[httpasyncclient-4.1.4.jar:4.1.4]
		at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_251]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_251]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:171) ~[httpcore-nio-4.4.11.jar:4.4.11]
	... 5 more
12:43:38.520  ERROR business.ESIndexAPI - Elasticsearch Attempt #1 : I/O reactor has been shut down
12:43:45.847  ERROR business.ESIndexAPI - Elasticsearch Attempt #2 : java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
12:43:52.295  ERROR business.ESIndexAPI - Elasticsearch Attempt #3 : java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
12:43:57.298  ERROR business.ESIndexAPI - Elasticsearch Attempt #4 : java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
12:44:02.300  ERROR business.ESIndexAPI - Elasticsearch Attempt #5 : java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
12:44:07.303  ERROR business.ESIndexAPI - Elasticsearch Attempt #6 : java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
12:44:12.305  ERROR business.ESIndexAPI - Elasticsearch Attempt #7 : java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
12:44:17.308  ERROR business.ESIndexAPI - Elasticsearch Attempt #8 : java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
```

**Comment by victoralfaro-dotcms** [comment]
I get this response when making a POST to `/api/content/_search` like it's done in `Content Resource` / `Admin Request Just Query Param_Success` :
```
{
    "entity": {
        "contentTook": 281,
        "jsonObjectView": {
            "contentlets": []
        },
        "queryTook": 1291,
        "resultsSize": 0
    },
    "errors": [],
    "i18nMessagesMap": {},
    "messages": [],
    "permissions": []
}
```

**Comment by jcastro-dotcms** [comment]
PR from Will: https://github.com/dotCMS/core/pull/20142/files

**Comment by swicken-dotcms** [comment]
Too many differences in the ES implementation in 5.2.8 to bring these changes back.
