### ISSUE TITLE
Time machine is causing an error with the index 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20041]
After try to run a past time machine snapshot we are starting to get an error in the log related to the index, and continue showing this every x minutes 

Here the log: https://gist.github.com/bryanboza/8850a5f01719c4c406bfd09114b88685

**To Reproduce**
- Login as admin
- Create a new past time machine snapshot
- Check your log 

**Expected behavior**
We need be able to creta a snapshot without problems 

**Desktop (please complete the following information):**
Tested on release-21.03 // Postgres // FF

**Comment by john-thomas-dotcms** [comment]
This bug also exists in 5.3.8.x, and is affecting multiple customers.

**Comment by swicken-dotcms** [comment]
Ticket: https://dotcms.zendesk.com/agent/tickets/103712

**Comment by freddyucv** [comment]
ee PR: https://github.com/dotCMS/enterprise/pull/779

**Comment by dsilvam** [comment]
Needs work: still hapenning
```
12:34:21.472  ERROR bundlers.e - String index out of range: -12
java.lang.StringIndexOutOfBoundsException: String index out of range: -12
	at java.lang.String.substring(String.java:1931) ~[?:1.8.0_211]
	at com.dotmarketing.servlets.BinaryExporterServlet.doGet(BinaryExporterServlet.java:166) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.enterprise.publishing.bundlers.e.a(SourceFile:349) ~[ee-21.03.jar:?]
	at com.dotcms.enterprise.publishing.bundlers.e.generate(SourceFile:127) ~[ee-21.03.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl.publish_aroundBody0(PublisherAPIImpl.java:123) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl$AjcClosure1.run(PublisherAPIImpl.java:1) ~[dotcms_21.03_e137a1d.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:43) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:38) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.timemachine.business.TimeMachineAPIImpl.startTimeMachine(TimeMachineAPIImpl.java:55) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.timemachine.ajax.TimeMachineAjaxAction$4.run_aroundBody0(TimeMachineAjaxAction.java:344) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.timemachine.ajax.TimeMachineAjaxAction$4$AjcClosure1.run(TimeMachineAjaxAction.java:1) ~[dotcms_21.03_e137a1d.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.timemachine.ajax.TimeMachineAjaxAction$4.run(TimeMachineAjaxAction.java:340) ~[dotcms_21.03_e137a1d.jar:?]
12:34:47.737  ERROR bundlers.e - String index out of range: -12
java.lang.StringIndexOutOfBoundsException: String index out of range: -12
	at java.lang.String.substring(String.java:1931) ~[?:1.8.0_211]
	at com.dotmarketing.servlets.BinaryExporterServlet.doGet(BinaryExporterServlet.java:166) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.enterprise.publishing.bundlers.e.a(SourceFile:349) ~[ee-21.03.jar:?]
	at com.dotcms.enterprise.publishing.bundlers.e.generate(SourceFile:127) ~[ee-21.03.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl.publish_aroundBody0(PublisherAPIImpl.java:123) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl$AjcClosure1.run(PublisherAPIImpl.java:1) ~[dotcms_21.03_e137a1d.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:43) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:38) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.timemachine.business.TimeMachineAPIImpl.startTimeMachine(TimeMachineAPIImpl.java:55) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.timemachine.ajax.TimeMachineAjaxAction$4.run_aroundBody0(TimeMachineAjaxAction.java:344) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.timemachine.ajax.TimeMachineAjaxAction$4$AjcClosure1.run(TimeMachineAjaxAction.java:1) ~[dotcms_21.03_e137a1d.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_21.03_e137a1d.jar:?]
	at com.dotcms.timemachine.ajax.TimeMachineAjaxAction$4.run(TimeMachineAjaxAction.java:340) ~[dotcms_21.03_e137a1d.jar:?]```

**Comment by dsilvam** [comment]
Passed Internal QA: It's now logging warn `Contentlet not exists or not have LIVE version: %s, Used in: %s` instead.

**Comment by jcastro-dotcms** [comment]
@bryanboza please make sure that the snapshot is getting created correctly. Even if its not showing up as expected, we need to make sure that the snapshot does exist.

**Comment by bryanboza** [comment]
Fixed, now we are able to create the snapshots and see those ones without problems
