### ISSUE TITLE
[Push Publish] : Selecting the REMOVE option in Push Publishing modal is not working

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#20136]
Reported via Support: [103774](https://dotcms.zendesk.com/agent/tickets/103774)
Reproducible in dotCMS 5.3.8.4, but NOT in latest master.

Users can select the **REMOVE** option in the Push publishing dialog for deleting content on the receiving instance. however, when selecting it and clicking the **PUSH** button, nothing happens. However, an error is displayed in the `dotcms.log` file.

**To Reproduce**
1. Start up a local dotCMS 5.3.8.4 instance, and set up a dummy PP config. You don't need to set up any receiving instance.
2. Right-click a piece of content to push it.
3. In the modal, select the **REMOVE** tab, and click the **PUSH** button.
4. Nothing is displayed in the UI, but the following error shows up in the log:
```
14:26:50.072  ERROR ajax.RemotePublishAjaxAction - Unparseable date: "Invalid date-Invalid date"
java.text.ParseException: Unparseable date: "Invalid date-Invalid date"
	at java.text.DateFormat.parse(DateFormat.java:366) ~[?:1.8.0_162]
	at com.dotcms.publisher.ajax.RemotePublishAjaxAction.publish(RemotePublishAjaxAction.java:226) ~[dotcms_5.3.8.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at com.dotcms.publisher.ajax.RemotePublishAjaxAction.service(RemotePublishAjaxAction.java:171) ~[dotcms_5.3.8.4.jar:?]
	at com.dotmarketing.servlets.ajax.AjaxAction.doPost(AjaxAction.java:70) ~[dotcms_5.3.8.4.jar:?]
...
...
```

**Expected behavior**
The **REMOVE** option must work.

**Additional context**
This issue is NOT reproducible in latest master.

**Comment by jcastro-dotcms** [comment]
Closing ticket immediately as it has been created for tracking purposes only.

**Comment by swicken-dotcms** [comment]
Removing this change from 5.2.8.5, caused the PP modal to not display.
