### ISSUE TITLE
Unable to delete users from the user screen

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#20140]
**Describe the bug**
I can not remove users from the UI.

**To Reproduce**
1. Go to: System | Users
2. Create a brand new User
3. Now hit DELETE and enter a replacement user. Hit Delete again. 
4. See the following exception in the logs

```
18:10:39.829  ERROR job.DeleteUserJob - Unable to delete user 'user-f3e6ac13-c8c2-4f68-a451-49fe0d4e8197/Fabrizzio Araya'.
com.dotmarketing.business.DuplicateRoleException: A role with id = 8256a803-b5e4-422b-8baa-00931bc2af78 and name = Fabrizzio Araya
	at com.dotmarketing.business.RoleAPIImpl.save_aroundBody16(RoleAPIImpl.java:273) ~[dotcms_21.04_72b0ce8.jar:?]
	at com.dotmarketing.business.RoleAPIImpl$AjcClosure17.run(RoleAPIImpl.java:1) ~[dotcms_21.04_72b0ce8.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_21.04_72b0ce8.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:59) ~[dotcms_21.04_72b0ce8.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_21.04_72b0ce8.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_21.04_72b0ce8.jar:?]
	at com.dotmarketing.business.RoleAPIImpl.save(RoleAPIImpl.java:249) ~[dotcms_21.04_72b0ce8.jar:?]
	at com.dotmarketing.business.UserAPIImpl.delete_aroundBody54(UserAPIImpl.java:558) ~[dotcms_21.04_72b0ce8.jar:?]
	at com.dotmarketing.business.UserAPIImpl$AjcClosure55.run(UserAPIImpl.java:1) ~[dotcms_21.04_72b0ce8.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_21.04_72b0ce8.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:59) ~[dotcms_21.04_72b0ce8.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_21.04_72b0ce8.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_21.04_72b0ce8.jar:?]
	at com.dotmarketing.business.UserAPIImpl.delete(UserAPIImpl.java:462) ~[dotcms_21.04_72b0ce8.jar:?]
	at com.dotmarketing.quartz.job.DeleteUserJob.run(DeleteUserJob.java:126) ~[dotcms_21.04_72b0ce8.jar:?]
	at com.dotmarketing.quartz.DotJob.execute(DotJob.java:42) ~[dotcms_21.04_72b0ce8.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223) ~[dot.quartz-all-1.8.6_2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) ~[dot.quartz-all-1.8.6_2.jar:?]
```
5. Refresh the screen and see the user marked for deltetion is still there.

**Comment by bryanboza** [comment]
Tested on release-21.04 and I'm unable to reproduce
