### ISSUE TITLE
If UrlMap specifies an invalid field, then you can't open the edit content screen

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20147]
We have an issue in the `URLMapAPIImpl`.  We call this from the the `CMSUrlUtil` all the time.  If a dotCMS installation has an invalid UrlMap - where a user has specified a field that does not exist in their pattern, this error gets thrown.

To reproduce:

create a content type with a URLMap Pattern that specifies a non-valid field, e.g.

```/myUrlMa/{thisFieldDoesNotExist}```

and and then try to edit any content.  

You will get this in the logs:

```
java.lang.NullPointerException
	at com.dotmarketing.cms.urlmap.URLMapAPIImpl.buildFields(URLMapAPIImpl.java:225)
	at com.dotmarketing.cms.urlmap.URLMapAPIImpl.buildContentQuery(URLMapAPIImpl.java:313)
	at com.dotmarketing.cms.urlmap.URLMapAPIImpl.getContentlet(URLMapAPIImpl.java:247)
	at com.dotmarketing.cms.urlmap.URLMapAPIImpl.getContentlet(URLMapAPIImpl.java:95)
	at com.dotmarketing.cms.urlmap.URLMapAPIImpl.isUrlPattern(URLMapAPIImpl.java:53)
	at com.dotmarketing.filters.CMSUrlUtil.isPageAsset(CMSUrlUtil.java:206)
	at com.dotmarketing.filters.CMSUrlUtil.amISomething(CMSUrlUtil.java:396)
	at org.apache.jsp.html.portlet.ext.contentlet.field.tiny_005fmce_005fconfig_jsp._jspService(tiny_005fmce_005fconfig_jsp.java:171)
```

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/20155

**Comment by fabrizzio-dotCMS** [comment]
I followed the instructions explained here on the description and neither the content-editor neither the Content-type editor break when the urlMap references a non-existing field. 
Additionally, to that, I talked to support about the original issue. I tried accessing the content type through the front end. When the URLmap Pattern has an invalid non-exiting field and nothing breaks. The url takes me to the detail page specified. Which to me is a bit strange. But seems like an acceptable fallback. I am passing it.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.05 // Postgres // FF

**Comment by swicken-dotcms** [comment]
Too many differences in URLMapAPIImpl to bring these changes back to 5.2.8.5
