### ISSUE TITLE
Tika POI error thrown in logs

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20217]
When we start up dotCMS - in current master, we see this in the logs.  Seems like our poi jar is out of date.

See:
https://stackoverflow.com/questions/52218278/after-update-apache-poi-4-0-property-http-www-oracle-com-xml-jaxp-propertie

```
WARNING: SAX Security Manager could not be setup [log suppressed for 5 minutes]
org.xml.sax.SAXNotRecognizedException: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
	at org.apache.xerces.parsers.AbstractSAXParser.getProperty(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.setProperty(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.setProperty(Unknown Source)
	at org.apache.tika.utils.XMLReaderUtils.trySetXercesSecurityManager(XMLReaderUtils.java:607)
	at org.apache.tika.utils.XMLReaderUtils.getSAXParser(XMLReaderUtils.java:178)
	at org.apache.tika.utils.XMLReaderUtils.setPoolSize(XMLReaderUtils.java:522)
	at org.apache.tika.utils.XMLReaderUtils.<clinit>(XMLReaderUtils.java:105)
	at org.apache.tika.parser.external.ExternalParsersConfigReader.read(ExternalParsersConfigReader.java:58)
	at org.apache.tika.parser.external.ExternalParsersFactory.create(ExternalParsersFactory.java:67)
	at org.apache.tika.parser.external.ExternalParsersFactory.create(ExternalParsersFactory.java:59)
	at org.apache.tika.parser.external.ExternalParsersFactory.create(ExternalParsersFactory.java:49)
	at org.apache.tika.parser.external.ExternalParsersFactory.create(ExternalParsersFactory.java:44)
	at org.apache.tika.parser.external.CompositeExternalParser.<init>(CompositeExternalParser.java:44)
	at org.apache.tika.parser.external.CompositeExternalParser.<init>(CompositeExternalParser.java:37)
	at java.lang.J9VMInternals.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:2015)
	at org.apache.tika.config.ServiceLoader.loadStaticServiceProviders(ServiceLoader.java:358)
	at org.apache.tika.parser.DefaultParser.getDefaultParsers(DefaultParser.java:55)
	at org.apache.tika.parser.DefaultParser.<init>(DefaultParser.java:85)
	at org.apache.tika.parser.DefaultParser.<init>(DefaultParser.java:100)
	at org.apache.tika.parser.DefaultParser.<init>(DefaultParser.java:108)
	at org.apache.tika.parser.internal.Activator.start(Activator.java:41)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:823)
```

**Comment by spbolton** [comment]
This issue is due to the version of xercesImpl the new entityExpansionLimit proporty in the updated JRE.   XercesImpl is old and the latest version does not support this.   The implementation provided by the JRE should be used which can be done by removing all instances of xercesImpl from the classpath, but we still have a dependency on this,  or we explicitly set the implementation to the default implementation with java properties e.g. with tomcat adding to JAVA_OPTS.  We can also set the DocumentBuilderFactory and TransformerFactory

set JAVA_OPTS="$JAVA_OPTS -Djavax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl 
-Djavax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl 
-Djavax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl"

**Comment by wezell** [comment]
PR: #20994

**Comment by wezell** [comment]
Note to QA:  we should test

- Asset Metadata is still being generated properly
- The velocity XMLTool still works
- What's changed still works

**Comment by dsilvam** [comment]
Passed Internal QA: Tested on latest docker image for 21.10

**Comment by bryanboza** [comment]
Tested after the changes, and now we are getting this error when you try to use the what's changed 
https://gist.github.com/bryanboza/b9c323d10c899b65d6941ea4ef007443

We need some work here

**Comment by bryanboza** [comment]
Fixed, the what's changed problem was moved to a new card here #21122
