### ISSUE TITLE
Reindex fails if tika fails

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20318]
Apparently, when a contentlet is being reindexed and has a binary whose extended metadata fails to be parsed correctly, the whole content fails to be reindexed.  We need to insure 2 things
1. We ALWAYS need the basic metadata for any asset.  If tika fails to generate extended meta, we still need the basic metadata about the file generated.
2.  Reindexing should not fail if tika fails - in this case, it should fall back to basic metadata. 

![Screen Shot 2021-04-29 at 11.34.43 AM.png](https://images.zenhubusercontent.com/56e187366caf56c9d38d8bc5/794e1a76-24d5-4692-aedf-f17d82c5e93d)

```
[29/04/21 15:31:26:377 GMT] WARN storage.FileMetadataAPIImpl: The Contentlet named `Static Plugins (4.x)` references a binary field: `attachment2` that is null, does not exists or can not be access.
[29/04/21 15:31:26:377 GMT] WARN storage.FileMetadataAPIImpl: The Contentlet named `Static Plugins (4.x)` references a binary field: `attachment3` that is null, does not exists or can not be access.
[29/04/21 15:31:26:377 GMT] WARN storage.FileMetadataAPIImpl: The Contentlet named `Static Plugins (4.x)` references a binary field: `attachment4` that is null, does not exists or can not be access.
[29/04/21 15:31:26:390 GMT] ERROR tika.TikaUtils: Could not parse file metadata for file [/data/shared/assets/8/2/820ff3cc-7966-40d5-a1c9-62332e3b69c7/fileAsset/job-detail.vtl] [XML parse error]
org.apache.tika.exception.TikaException: XML parse error
at org.apache.tika.parser.xml.XMLParser.parse(XMLParser.java:81) ~[?:?]
at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[?:?]
at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[?:?]
at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[?:?]
at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143) ~[?:?]
at org.apache.tika.Tika.parseToString(Tika.java:527) ~[?:?]
at com.dotcms.osgi.tika.TikaProxy.parseToString(TikaProxy.java:101) ~[?:?]
at com.dotcms.tika.TikaUtils.getForcedMetaDataMap(TikaUtils.java:393) ~[dotcms_21.05_999999.jar:?]
at com.dotcms.storage.TikaMetadataGenerator.generate(TikaMetadataGenerator.java:32) ~[dotcms_21.05_999999.jar:?]
at com.dotcms.storage.FileStorageAPIImpl.generateFullMetaData(FileStorageAPIImpl.java:167) ~[dotcms_21.05_999999.jar:?]
at com.dotcms.storage.FileStorageAPIImpl.generateMetaData(FileStorageAPIImpl.java:252) ~[dotcms_21.05_999999.jar:?]
at com.dotcms.storage.FileMetadataAPIImpl.generateFullMetadata(FileMetadataAPIImpl.java:217) ~[dotcms_21.05_999999.jar:?]
at com.dotcms.storage.FileMetadataAPIImpl.generateContentletMetadata(FileMetadataAPIImpl.java:110) ~[dotcms_21.05_999999.jar:?]
at com.dotcms.storage.FileMetadataAPIImpl.generateContentletMetadata(FileMetadataAPIImpl.java:273) ~[dotcms_21.05_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.writeMetadata(ESMappingAPIImpl.java:430) ~[dotcms_21.05_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.toMap_aroundBody0(ESMappingAPIImpl.java:398) ~[dotcms_21.05_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl$AjcClosure1.run(ESMappingAPIImpl.java:1) ~[dotcms_21.05_999999.jar:?]
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.9.2.jar:?]
at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_21.05_999999.jar:?]
at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_21.05_999999.jar:?]
at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_21.05_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.toMap(ESMappingAPIImpl.java:247) ~[dotcms_21.05_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ContentletIndexAPIImpl.addBulkRequest(ContentletIndexAPIImpl.java:762) ~[dotcms_21.05_999999.jar:?]
```

**Comment by bryanboza** [comment]
Fixed, tested on release-21.05 // Postgres // FF. Testing adding events to the calendar and the doing a full reindex without problems
