### ISSUE TITLE
Storage data PK Violation - Collision saving metadata into the DB storage

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#20312]
**Description**
There's a rare situation that triggers a SQL exception when saving metadata into the db. 
Resulting in the following exception on the logs:

```
Caused by: com.dotmarketing.exception.DotDataException: ERROR: duplicate key value violates unique constraint "storage_data_pkey"
  Detail: Key (hash_id)=(6d8a9c6fa2c34572ed1f38240b88f393405f5d14e8406e74b35cd8074f45c31c) already exists.
	at com.dotmarketing.common.db.DotConnect.executeUpdate_aroundBody2(DotConnect.java:1227)
	at com.dotmarketing.common.db.DotConnect$AjcClosure3.run(DotConnect.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29)
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41)
	at com.dotmarketing.common.db.DotConnect.executeUpdate(DotConnect.java:1214)
	at com.dotmarketing.common.db.DotConnect.executeUpdate(DotConnect.java:1198)
	at com.dotcms.storage.DataBaseStoragePersistenceAPIImpl.pushNewFile(DataBaseStoragePersistenceAPIImpl.java:524)
	... 108 more
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "storage_data_pkey"
  Detail: Key (hash_id)=(6d8a9c6fa2c34572ed1f38240b88f393405f5d14e8406e74b35cd8074f45c31c) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at com.dotmarketing.common.db.DotConnect.executeUpdate_aroundBody2(DotConnect.java:1222)
	... 116 more

```
Most of the time the exception is coming from saving the separate binary chunks into the `storage_data` But I've seen it arise also from saving into the table `storage`. 

Looks like there's a simultaneous "double save" operation taking place. Wrapping the save logic on 
```
DataBaseStoragePersistenceAPIImpl.pushFile(final String groupName, final String path,
            final File file, final Map<String, Serializable> extraMeta)
```
within a synchronized block solves the problem. But we want to determine what is causing the multiple threads attempting to write metadata. 

**To Reproduce**
   It is currently unknown what exactly triggers the behavior
**Expected behavior**
  We should be able to save content and generate it's own metadata without seeing such exceptions

**Comment by fabrizzio-dotCMS** [comment]
I have reviewed the code that saves and recovers binaries. And looks ok. 

As far as I can tell the indexing process might get called from different thread contexts. Look at this piece of code from ContentletIndexAPIImpl.java

```
    public void addContentToIndex(final Contentlet parentContenlet, final boolean includeDependencies)
            throws DotDataException {
        ....
        if(parentContenlet.getIndexPolicy()==IndexPolicy.DEFER) {
            queueApi.addContentletsReindex(contentToIndex);
        }  else if (!DbConnectionFactory.inTransaction()) {
            addContentToIndex(contentToIndex);
        } else {
            HibernateUtil.addSyncCommitListener(() -> addContentToIndex(contentToIndex));
        }
    }
```

**Comment by fabrizzio-dotCMS** [comment]
I can reproduce this issue if I repeatedly run the following integration test: `ContentletAPITest.copyContentletWithSeveralVersionsOrderIssue()`
Once I introduce a bit of synchronization the issue goes away.

**Comment by wezell** [comment]
Fabrizzio - would an upsert solve the issue without the sync and maybe more reliable future forward?

**Comment by fabrizzio-dotCMS** [comment]
> Fabrizzio - would an upsert solve the issue without the sync and maybe more reliable future forward?

Definitely Worth to shot

**Comment by nollymar** [comment]
Passed internal QA
