### ISSUE TITLE
Can't edit content after upgrading from version 21.04

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#20358]
I get this error repeatedly after upgrading from version 21.04 to 21.05: 

```
Caused by: com.dotmarketing.exception.DotDataException: ERROR: column "hash_ref" of relation "storage" does not exist
  Position: 45
	at com.dotmarketing.common.db.DotConnect.executeUpdate_aroundBody2(DotConnect.java:1227) ~[dotcms_21.05_e1fa50b.jar:?]
	at com.dotmarketing.common.db.DotConnect$AjcClosure3.run(DotConnect.java:1) ~[dotcms_21.05_e1fa50b.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.9.2.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_21.05_e1fa50b.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_21.05_e1fa50b.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_21.05_e1fa50b.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeUpdate(DotConnect.java:1214) ~[dotcms_21.05_e1fa50b.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeUpdate(DotConnect.java:1198) ~[dotcms_21.05_e1fa50b.jar:?]
	at com.dotcms.storage.DataBaseStoragePersistenceAPIImpl.pushFileReference(DataBaseStoragePersistenceAPIImpl.java:502) ~[dotcms_21.05_e1fa50b.jar:?]
	at com.dotcms.storage.DataBaseStoragePersistenceAPIImpl.lambda$14(DataBaseStoragePersistenceAPIImpl.java:466) ~[dotcms_21.05_e1fa50b.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:59) ~[dotcms_21.05_e1fa50b.jar:?]
	at com.dotcms.storage.DataBaseStoragePersistenceAPIImpl.wrapInTransaction(DataBaseStoragePersistenceAPIImpl.java:93) ~[dotcms_21.05_e1fa50b.jar:?]
	... 114 more
Caused by: org.postgresql.util.PSQLException: ERROR: column "hash_ref" of relation "storage" does not exist
  Position: 45
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497) ~[postgresql-42.2.8.jar:42.2.8]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233) ~[postgresql-42.2.8.jar:42.2.8]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310) ~[postgresql-42.2.8.jar:42.2.8]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446) ~[postgresql-42.2.8.jar:42.2.8]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370) ~[postgresql-42.2.8.jar:42.2.8]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149) ~[postgresql-42.2.8.jar:42.2.8]
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124) ~[postgresql-42.2.8.jar:42.2.8]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-3.4.2.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.2.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeUpdate_aroundBody2(DotConnect.java:1222) ~[dotcms_21.05_e1fa50b.jar:?]
	at com.dotmarketing.common.db.DotConnect$AjcClosure3.run(DotConnect.java:1) ~[dotcms_21.05_e1fa50b.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.9.2.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_21.05_e1fa50b.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_21.05_e1fa50b.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_21.05_e1fa50b.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeUpdate(DotConnect.java:1214) ~[dotcms_21.05_e1fa50b.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeUpdate(DotConnect.java:1198) ~[dotcms_21.05_e1fa50b.jar:?]
	at com.dotcms.storage.DataBaseStoragePersistenceAPIImpl.pushFileReference(DataBaseStoragePersistenceAPIImpl.java:502) ~[dotcms_21.05_e1fa50b.jar:?]
	at com.dotcms.storage.DataBaseStoragePersistenceAPIImpl.lambda$14(DataBaseStoragePersistenceAPIImpl.java:466) ~[dotcms_21.05_e1fa50b.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:59) ~[dotcms_21.05_e1fa50b.jar:?]
	at com.dotcms.storage.DataBaseStoragePersistenceAPIImpl.wrapInTransaction(DataBaseStoragePersistenceAPIImpl.java:93) ~[dotcms_21.05_e1fa50b.jar:?]
	... 114 more
``` 

This error only happens when you start a fresh installation in version 21.04 and then try to upgrade to version 21.05 using postgres.

**Comment by nollymar** [comment]
Now, it fails for another reason: https://gist.github.com/nollymar/5a01ab62fa4fcce53274e96ea4fb443c

**Comment by nollymar** [comment]
**Internal QA:**  Passed

**Comment by bryanboza** [comment]
Fixed, unable to reproduce after upgrade from 21.04 version in psql
