### ISSUE TITLE
RelationshipFactory is being used by other API - db connection leak

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20354]
Our DB connection pattern say that we maintain/insure our db connections are closed in our API layer using our annotations.   Our APIs then call down to the "Factory/DAO" layers to retrieve data and can/should wrap many of such calls in transactions.  

We have an issue where classes are using our Relationship factory directly which is causing DB connection leaks. These leaks have not caused any noticeable issues, still we should make sure our DB connections are closed properly.

See the leak report below as an example
```
[05/03/21 14:03:08:784 GMT] INFO publishing.PublisherAPIImpl: Start of Bundler: BundleXMLAsc
[05/03/21 14:03:08:784 GMT] INFO publishing.PublisherAPIImpl: End of Bundler: BundleXMLAsc
[05/03/21 14:03:08:784 GMT] INFO publishing.PublisherAPIImpl: Start of Bundler: CategoryBundler
[05/03/21 14:03:08:784 GMT] INFO publishing.PublisherAPIImpl: End of Bundler: CategoryBundler
[05/03/21 14:03:08:792 GMT] INFO pusher.PushUtils: Compressing 1 to /data/shared/assets/bundles/01F01B436SNCT0Y134VX5HC122/../01F01B436SNCT0Y134VX5HC122.tar.gz
[05/03/21 14:03:13:800 GMT] WARN pool.ProxyLeakTask: Connection leak detection triggered for org.postgresql.jdbc.PgConnection@36bf24b3 on thread DotMarketingQuartzScheduler_Worker-21, stack trace follows
java.lang.Exception: Apparent connection leak detected
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[HikariCP-3.4.2.jar:?]
at com.dotmarketing.db.DbConnectionFactory.getConnection(DbConnectionFactory.java:206) ~[dotcms_5.3.8.4_999999.jar:?]
at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:531) ~[dotcms_5.3.8.4_999999.jar:?]
at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:271) ~[dotcms_5.3.8.4_999999.jar:?]
at com.dotmarketing.common.db.DotConnect.loadObjectResults(DotConnect.java:925) ~[dotcms_5.3.8.4_999999.jar:?]
at com.dotcms.contenttype.business.RelationshipFactoryImpl.byContentType(RelationshipFactoryImpl.java:284) ~[dotcms_5.3.8.4_999999.jar:?]
at com.dotcms.contenttype.business.RelationshipFactoryImpl.byContentType(RelationshipFactoryImpl.java:256) ~[dotcms_5.3.8.4_999999.jar:?]
at com.dotcms.publisher.util.DependencyManager.structureDependencyHelper(DependencyManager.java:1117) ~[dotcms_5.3.8.4_999999.jar:?]
at com.dotcms.publisher.util.DependencyManager.processList(DependencyManager.java:1277) ~[dotcms_5.3.8.4_999999.jar:?]
at com.dotcms.publisher.util.DependencyManager.setContentDependencies(DependencyManager.java:1343) ~[dotcms_5.3.8.4_999999.jar:?]
at com.dotcms.publisher.util.DependencyManager.setDependencies(DependencyManager.java:345) ~[dotcms_5.3.8.4_999999.jar:?]
at com.dotcms.enterprise.publishing.remote.bundler.DependencyBundler.generate(SourceFile:68) ~[ee-5.3.8.4.jar:?]
at com.dotcms.publishing.PublisherAPIImpl.publish_aroundBody0(PublisherAPIImpl.java:124) ~[dotcms_5.3.8.4_999999.jar:?]
at com.dotcms.publishing.PublisherAPIImpl$AjcClosure1.run(PublisherAPIImpl.java:1) ~[dotcms_5.3.8.4_999999.jar:?]
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.3.8.4_999999.jar:?]
```

**Comment by wezell** [comment]
PR: https://github.com/dotCMS/core/pull/20356
EE PR: https://github.com/dotCMS/enterprise/pull/797
