### ISSUE TITLE
Loading a starter fills logs with Tika errors

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20351]
We should not log an error when TIKA fails to parse a file, we should log a warnAndDebug.  We are getting too many of these in the logs.  I can only imagine what our customers will see with their thousands of VTL files

```
16:49:19.547  INFO  db.DotCMSInitDb - Records left to index : 579
16:49:20.929  ERROR tika.TikaUtils - Could not parse file metadata for file [/Users/will/git/dotcms/tomcat9/webapps/ROOT/assets/0/8/08947188-14b1-430f-92d0-a734ec3a5983/fileAsset/recommended-products.vtl] [XML parse error]
org.apache.tika.exception.TikaException: XML parse error
	at org.apache.tika.parser.xml.XMLParser.parse(XMLParser.java:81) ~[?:?]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[?:?]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[?:?]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[?:?]
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143) ~[?:?]
	at org.apache.tika.Tika.parseToString(Tika.java:527) ~[?:?]
	at com.dotcms.osgi.tika.TikaProxy.parseToString(TikaProxy.java:101) ~[?:?]
	at com.dotcms.tika.TikaUtils.getForcedMetaDataMap(TikaUtils.java:393) ~[classes/:?]
	at com.dotcms.storage.TikaMetadataGenerator.generate(TikaMetadataGenerator.java:32) ~[classes/:?]
	at com.dotcms.storage.FileStorageAPIImpl.generateFullMetaData(FileStorageAPIImpl.java:167) ~[classes/:?]
	at com.dotcms.storage.FileStorageAPIImpl.generateMetaData(FileStorageAPIImpl.java:252) ~[classes/:?]
```

**Comment by nollymar** [comment]
Passed internal QA

**Comment by bryanboza** [comment]
Unable to reproduce after the changes...
