### ISSUE TITLE
Concurrency Issues with loadPermission

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20464]
When you are inserting a large amount of contents simultaneously, the StripedLock on the PermissionBitFactoryImpl can timeout when trying to read permissions from the DB.  I am not sure why we have the StrippedLock here, as this is just a DB read and not a write.

We should make the read lock configurable and only use it if we see issues without it.

### Example Error
```



[17/05/21 12:17:58:998 GMT] ERROR business.ContentletIndexAPIImpl: Can't get a mapping for contentlet with id_lang:fa4496e3-6923-4e1c-b124-a4d2ce5076b3_1607343782547 Content data: {datum=2021-05-17 13:12:33.0, owner=user-4392578d-b44b-4519-a1b9-7de40f13d94a, nullProperties=[wfExpireDate, filterKey, whereToSend, wfPublishDate, wfNeverExpire, wfActionAssign, iWantTo, wfActionId, wfPublishTime, wfActionComments, wfExpireTime], identifier=fa4496e3-6923-4e1c-b124-a4d2ce5076b3, modDate=2021-05-17 13:17:04.7, vorname=Mika , eMailAdresse=mikakaschner@gmail.com, languageId=1607343782547, oeffentlich=Nein, valid=Nein, inode=adeb4cd6-a362-49db-84e7-5c36e0dbd289, postleitzahl=00000, folder=SYSTEM_FOLDER, disabledWYSIWYG=[], sortOrder=0, modUser=user-4392578d-b44b-4519-a1b9-7de40f13d94a, name=Kaschner , host=8a7d5e23-da1e-420a-b4f0-471e7da8ea2d, stInode=6ae8fbbe-297f-4778-ac15-92a16ce919ce}
com.dotcms.content.business.DotMappingException: An error occurred when mapping properties of Contentlet with ID 'fa4496e3-6923-4e1c-b124-a4d2ce5076b3': null
	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.toMap_aroundBody0(ESMappingAPIImpl.java:383) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl$AjcClosure1.run(ESMappingAPIImpl.java:1) ~[dotcms_5.3.8_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.toMap(ESMappingAPIImpl.java:211) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ContentletIndexAPIImpl.addBulkRequest(ContentletIndexAPIImpl.java:745) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ContentletIndexAPIImpl.appendBulkRequest_aroundBody14(ContentletIndexAPIImpl.java:686) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ContentletIndexAPIImpl$AjcClosure15.run(ContentletIndexAPIImpl.java:1) ~[dotcms_5.3.8_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ContentletIndexAPIImpl.appendBulkRequest(ContentletIndexAPIImpl.java:663) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ContentletIndexAPIImpl.appendBulkRequest(ContentletIndexAPIImpl.java:649) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ContentletIndexAPIImpl.appendBulkRequest(ContentletIndexAPIImpl.java:627) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.common.reindex.ReindexThread.reindexWithBulkRequest(ReindexThread.java:224) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.common.reindex.ReindexThread.runReindexLoop(ReindexThread.java:196) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.common.reindex.ReindexThread.lambda$0(ReindexThread.java:142) ~[dotcms_5.3.8_999999.jar:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: com.dotmarketing.exception.DotDataException
	at com.dotmarketing.business.PermissionBitFactoryImpl.lambda$8(PermissionBitFactoryImpl.java:1716) ~[dotcms_5.3.8_999999.jar:?]
	at io.vavr.control.Try.getOrElseThrow(Try.java:748) ~[vavr-0.10.3.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions_aroundBody2(PermissionBitFactoryImpl.java:1716) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl$AjcClosure3.run(PermissionBitFactoryImpl.java:1) ~[dotcms_5.3.8_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions(PermissionBitFactoryImpl.java:1679) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions_aroundBody0(PermissionBitFactoryImpl.java:1674) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl$AjcClosure1.run(PermissionBitFactoryImpl.java:1) ~[dotcms_5.3.8_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions(PermissionBitFactoryImpl.java:1670) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.getPermissions(PermissionBitFactoryImpl.java:827) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.business.PermissionBitAPIImpl.getPermissions_aroundBody18(PermissionBitAPIImpl.java:522) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.business.PermissionBitAPIImpl$AjcClosure19.run(PermissionBitAPIImpl.java:1) ~[dotcms_5.3.8_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.business.PermissionBitAPIImpl.getPermissions(PermissionBitAPIImpl.java:520) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.loadPermissions(ESMappingAPIImpl.java:545) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.toMap_aroundBody0(ESMappingAPIImpl.java:219) ~[dotcms_5.3.8_999999.jar:?]
	... 25 more
Caused by: com.dotcms.concurrent.DotConcurrentException: Unable to acquire Lock on key `PermissionID:fa4496e3-6923-4e1c-b124-a4d2ce5076b3` and thread `reindex-thread-0`
	at com.dotcms.concurrent.lock.StripedLockImpl.tryLock(StripedLockImpl.java:94) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.concurrent.lock.StripedLockImpl.tryLock(StripedLockImpl.java:55) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.concurrent.lock.IdentifierStripedLock.tryLock(IdentifierStripedLock.java:16) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.lambda$7(PermissionBitFactoryImpl.java:1698) ~[dotcms_5.3.8_999999.jar:?]
	at io.vavr.control.Try.of(Try.java:75) ~[vavr-0.10.3.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions_aroundBody2(PermissionBitFactoryImpl.java:1698) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl$AjcClosure3.run(PermissionBitFactoryImpl.java:1) ~[dotcms_5.3.8_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions(PermissionBitFactoryImpl.java:1679) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions_aroundBody0(PermissionBitFactoryImpl.java:1674) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl$AjcClosure1.run(PermissionBitFactoryImpl.java:1) ~[dotcms_5.3.8_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.loadPermissions(PermissionBitFactoryImpl.java:1670) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.business.PermissionBitFactoryImpl.getPermissions(PermissionBitFactoryImpl.java:827) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.business.PermissionBitAPIImpl.getPermissions_aroundBody18(PermissionBitAPIImpl.java:522) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.business.PermissionBitAPIImpl$AjcClosure19.run(PermissionBitAPIImpl.java:1) ~[dotcms_5.3.8_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotmarketing.business.PermissionBitAPIImpl.getPermissions(PermissionBitAPIImpl.java:520) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.loadPermissions(ESMappingAPIImpl.java:545) ~[dotcms_5.3.8_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.toMap_aroundBody0(ESMappingAPIImpl.java:219) ~[dotcms_5.3.8_999999.jar:?]
	... 25 more	

```

**Comment by bryanboza** [comment]
Fixed, testing using the ```/api/v1/workflow/actions/default/fire/PUBLISH``` endpoind using `ab` for concurrence and now we are supporting this without problems

To test this card you can use this command: 
```
ab -u test.txt -T application/json -A admin@dotcms.com:admin -c 100 -n 1000 http://localhost:8080/api/v1/workflow/actions/default/fire/PUBLISH
``` 

![image](https://user-images.githubusercontent.com/2641437/126676416-19a0ad9a-033c-443f-819f-4f1941f65eb9.png)


Tested on release-21.07 // Postgres // FF
