### ISSUE TITLE
configuration: limit bulk request size

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20568]
We have seen numerous cases of a dotcms cluster overwhelming an ES installation with index requests.  This can happen durning a full reindex, a large bulk re-permissioning  or if a major content type definition gets updated.  We need to slow dotCMS's roll and only put up to 1mb of content to elasticsearch at a given time (per node).

```
[23/06/21 10:44:52:780 AEST] ERROR reindex.ReindexThread: Bulk  process failed entirely:30,000 milliseconds timeout on connection http-outgoing-72 [ACTIVE]
java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-72 [ACTIVE]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:263) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:492) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:213) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
[23/06/21 10:44:53:076 AEST] ERROR util.DotRestHighLevelClientProvider$1: [host=https://prod-es2:9200]
[23/06/21 10:44:53:076 AEST] ERROR reindex.ReindexThread: Bulk  process failed entirely:30,000 milliseconds timeout on connection http-outgoing-73 [ACTIVE]
java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-73 [ACTIVE]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:263) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:492) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:213) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio-4.4.11.jar:4.4.11]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
[23/06/21 10:44:53:157 AEST]  INFO reindex.ReindexThread: ---  ReindexThread total/todo/bulk: 43521/100/200

```

**Comment by bryanboza** [comment]
Fixed, tested on release-21.06 // Postgres // FF 

Tested the following scenarios: 
- Cluster full reindex 
- Reindex just some content types 
- PP of a entire site from a single node to the cluster
