### ISSUE TITLE
Button for Navigation Reorder is not working correctly

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#20616]
Reported via Support: https://dotcms.zendesk.com/agent/tickets/104561
Reproducible in dotCMS 5.3.8.4 up to latest master (21.05.1)

According to our official documentation: https://dotcms.com/docs/latest/navtool-viewtool#ExampleAddReorderButton , users can display the **Reorder Button** for the navigation items. In previous versions of dotCMS, the Reorder feature automatically detected the folder path of the page it was placed in, and display the appropriate children up to two levels deep.

However, I was able to confirm with @dsilvam that this feature is not working as expected in more recent versions of dotCMS:

1. By default, the **Reorder Button** is always showing the level-1 folders of the Site, with no regards to the location of the page that is displaying it. This was probably introduced by the following code refactoring in dotCMS 5.1.0: https://github.com/dotCMS/core/commit/17e924eaf18405fac98d337c140f7ef2aff39a2b

2. When moving folders around in the Reorder window, the following JavaScript error is being logged to the browser's console dozens of times per second:
```
Uncaught InternalError: too much recursion
```
And the UI will not let you make any other change anymore. You have to close the Reorder window and open it up again.

3. Moving navigation items around that are further down the list is presenting problems because the placeholder is not being recognized, i.e., the drag-and-drop is not showing up. This means that navigation lists with many items can only be re-ordered partially.

**To Reproduce**
For concrete examples and data source, please ask me.

**Expected behavior**
The Reorder Button should work correctly the same way it does in previous dotCMS versions.

**Comment by jcastro-dotcms** [comment]
The Velocity code that must be used to render the Reorder Buttons is the following:
```
## ADD REORDER MENU BUTTON
#if ($EDIT_MODE && $PUBLISH_HTMLPAGE_PERMISSION)
   <div class="reorder-menu">
       #set($_formId="dot_form_menu_$date.date.time")
       #set ($folder = $folderAPI.findCurrentFolder($startFromPath, $host))
       #set ($menuId = $folder.inode)       
       #orderMenu()
   </div>
#end
```
The example code in our official documentation: https://dotcms.com/docs/latest/navtool-viewtool#ExampleAddReorderButton seems to be outdated, or not working anymore.

**Comment by dsilvam** [comment]
This PR https://github.com/dotCMS/core/pull/20716 fixes sending the proper start level for the reordering , solving point 1. 

For point 2, there are two options: downgrading prototype from 1.7.3 to 1.5.0, which is the version that comes with the scriptaculous we use; or update scriptaculous to version 1.9.0 which works with prototype 1.7. That solves point 2, but need to be careful if this breaks something else. However, even after fixing the infinite recursion issue the drag and drop is not properly working, not letting the drop to happen. This might have happened after converting the reorder to a popup in here https://github.com/dotCMS/core/commit/17e924eaf18405fac98d337c140f7ef2aff39a2b.

**Comment by wezell** [comment]
Reordering works the first time and not the second.

**Comment by nollymar** [comment]
**Internal QA:** The issues commented on the description are fixed, however, the reorder changes are not being persisted:

https://user-images.githubusercontent.com/8741395/128389394-af69685c-832e-4020-b98f-2f8af432ae12.mov

**Comment by alfredo-dotcms** [comment]
After some testing, seems like the error happens on the `About` page, for some reason an error is being thrown on the BE.

If you do this on other page with a smaller menu, it works!
https://monosnap.com/file/9OuT43vbPccXTDwPUdGInGX5I2PSZQ

the reordering on the FE is working
https://monosnap.com/file/V54JmqgsdNH1oIrMjWaWWBtWc5JWkd

**Comment by alfredo-dotcms** [comment]
`9:53:35.230  WARN  business.ESContentletAPIImpl - Contentlet [47a06180-9f4a-4e51-9ec0-3831f80f0a2e] has invalid / missing field(s).
com.dotmarketing.portlets.contentlet.business.DotContentletValidationException: Contentlet [47a06180-9f4a-4e51-9ec0-3831f80f0a2e] has invalid / missing field(s).
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.validateContentlet_aroundBody164(ESContentletAPIImpl.java:6287) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure165.run(ESContentletAPIImpl.java:1) ~[dotcms_master_b8b945a.jar:?]
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.9.2.jar:?]
    at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.validateContentlet(ESContentletAPIImpl.java:6266) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.validateContentlet_aroundBody168(ESContentletAPIImpl.java:6818) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure169.run(ESContentletAPIImpl.java:1) ~[dotcms_master_b8b945a.jar:?]
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.9.2.jar:?]
    at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.validateContentlet(ESContentletAPIImpl.java:6806) ~[dotcms_master_b8b945a.jar:?]
    at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.validateContentlet(ContentletAPIInterceptor.java:1927) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.internalCheckin(ESContentletAPIImpl.java:4719) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.lambda$68(ESContentletAPIImpl.java:4377) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.concurrent.lock.StripedLockImpl.tryLock(StripedLockImpl.java:100) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.concurrent.lock.StripedLockImpl.tryLock(StripedLockImpl.java:55) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.concurrent.lock.IdentifierStripedLock.tryLock(IdentifierStripedLock.java:16) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin_aroundBody148(ESContentletAPIImpl.java:4376) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure149.run(ESContentletAPIImpl.java:1) ~[dotcms_master_b8b945a.jar:?]
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.9.2.jar:?]
    at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_master_b8b945a.jar:?]
    at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:119) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:30) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:4335) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkinWithoutVersioning_aroundBody146(ESContentletAPIImpl.java:4316) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure147.run(ESContentletAPIImpl.java:1) ~[dotcms_master_b8b945a.jar:?]
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.9.2.jar:?]
    at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkinWithoutVersioning(ESContentletAPIImpl.java:4312) ~[dotcms_master_b8b945a.jar:?]
    at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkinWithoutVersioning(ContentletAPIInterceptor.java:309) ~[dotcms_master_b8b945a.jar:?]
    at com.dotmarketing.portlets.folders.action.OrderMenuAction._orderMenuItemsDragAndDrop_aroundBody0(OrderMenuAction.java:309) ~[dotcms_master_b8b945a.jar:?]
    at com.dotmarketing.portlets.folders.action.OrderMenuAction$AjcClosure1.run(OrderMenuAction.java:1) ~[dotcms_master_b8b945a.jar:?]
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.9.2.jar:?]
    at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_master_b8b945a.jar:?]
    at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:119) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:30) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_master_b8b945a.jar:?]
    at com.dotmarketing.portlets.folders.action.OrderMenuAction._orderMenuItemsDragAndDrop(OrderMenuAction.java:254) ~[dotcms_master_b8b945a.jar:?]
    at com.dotmarketing.portlets.folders.action.OrderMenuAction.processAction(OrderMenuAction.java:111) ~[dotcms_master_b8b945a.jar:?]
    at com.liferay.portal.struts.PortletRequestProcessor.process(PortletRequestProcessor.java:126) ~[dotcms_master_b8b945a.jar:?]
    at com.liferay.portlet.StrutsPortlet.processAction(StrutsPortlet.java:120) ~[dotcms_master_b8b945a.jar:?]
    at com.liferay.portlet.ConcretePortletWrapper.processAction(ConcretePortletWrapper.java:97) ~[dotcms_master_b8b945a.jar:?]
    at com.liferay.portal.action.LayoutAction._processPortletRequest(LayoutAction.java:194) ~[dotcms_master_b8b945a.jar:?]
    at com.liferay.portal.action.LayoutAction._processActionRequest(LayoutAction.java:206) ~[dotcms_master_b8b945a.jar:?]
    at com.liferay.portal.action.LayoutAction.execute(LayoutAction.java:82) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:431) ~[dot.struts-1.2.10_1.jar:?]
    at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:237) ~[dot.struts-1.2.10_1.jar:?]
    at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:147) ~[dotcms_master_b8b945a.jar:?]
    at com.dotcms.repackage.org.apache.struts.action.ActionServlet.process(ActionServlet.java:1202) ~[dot.struts-1.2.10_1.jar:?]
    at com.dotcms.repackage.org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:430) ~[dot.struts-1.2.10_1.jar:?]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) ~[servlet-api.jar:4.0.FR]
    at com.liferay.portal.servlet.MainServlet.callParentService(MainServlet.java:244) ~[dotcms_master_b8b945a.jar:?]
    at com.liferay.portal.servlet.MainServlet.service(MainServlet.java:444) ~[dotcms_master_b8b945a.jar:?]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[servlet-api.jar:4.0.FR]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.41]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
    at com.dotcms.repackage.com.liferay.filters.secure.SecureFilter.doFilter(SecureFilter.java:135) ~[dot.secure-filter-ukv_2.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
    at com.dotmarketing.filters.CMSFilter.doFilterInternal(CMSFilter.java:198) ~[dotcms_master_b8b945a.jar:?]
    at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:48) ~[dotcms_master_b8b945a.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
    at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_master_b8b945a.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
    at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_master_b8b945a.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
    at com.dotcms.vanityurl.filters.VanityURLFilter.doFilter(VanityURLFilter.java:109) ~[dotcms_master_b8b945a.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
    at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176) ~[urlrewritefilter-4.0.4.jar:4.0.4]
    at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145) ~[urlrewritefilter-4.0.4.jar:4.0.4]
    at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92) ~[urlrewritefilter-4.0.4.jar:4.0.4]
    at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389) ~[urlrewritefilter-4.0.4.jar:4.0.4]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
    at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:137) ~[dotcms_master_b8b945a.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
    at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:88) ~[dotcms_master_b8b945a.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
    at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:50) ~[dotcms_master_b8b945a.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
    at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:99) ~[dotcms_master_b8b945a.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
    at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_master_b8b945a.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
    at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
    at com.dotcms.filters.NormalizationFilter.doFilter(NormalizationFilter.java:73) ~[dotcms_master_b8b945a.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[catalina.jar:9.0.41]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[catalina.jar:9.0.41]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[catalina.jar:9.0.41]
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) ~[catalina.jar:9.0.41]
    at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764) ~[catalina.jar:9.0.41]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[catalina.jar:9.0.41]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[catalina.jar:9.0.41]
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-coyote.jar:9.0.41]
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-coyote.jar:9.0.41]
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888) ~[tomcat-coyote.jar:9.0.41]
    at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1693) ~[tomcat-coyote.jar:9.0.41]
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:9.0.41]
    at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1122) ~[tomcat-coyote.jar:9.0.41]
    at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:617) ~[tomcat-coyote.jar:9.0.41]
    at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:595) ~[tomcat-coyote.jar:9.0.41]
    at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126) ~[?:1.8.0_161]
    at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:430) ~[?:1.8.0_161]
    at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:191) ~[?:1.8.0_161]
    at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213) ~[?:1.8.0_161]
    at sun.nio.ch.KQueuePort$EventHandlerTask.run(KQueuePort.java:301) ~[?:1.8.0_161]
    at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112) ~[?:1.8.0_161]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
    at java.lang.Thread.run(Thread.java:748) 
`

**Comment by dsilvam** [comment]
**Passed Internal QA**.
Since the dataset used for testing has old identifiers, which used to be auto-increment, the property MINIMUM_SHORTY_ID_LENGTH needs to be set to the minimum length of the ids of sortable assets, in which case was 3. ShortyAPI was treating these old ids as non-valid thus they were not able to be ordered. 

This is a quick way to find this: 
```SELECT MIN(LENGTH(inode)) FROM inode WHERE type IN ('contentlet', 'links', 'folder') group by (length(inode)) LIMIT 1```
