### ISSUE TITLE
[Push Publishing] : Adding error message when Content Type points to non-existing Site

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#20627]
Found when working on Support ticket: [104668](https://dotcms.zendesk.com/agent/tickets/104668)
Reproducible as of dotCMS 5.3.8.5 LTS, up to latest master

In a Push Publishing environment, customers can create a Site in the sending instance, and manually create the same Site in the receiving instance. This is incorrect, and causes severe problems with Push Publishing. When you push a Content Type under this situation, all you get in the dotCMS UI is a generic error:
```
Failed to publish because an error occurred: An error occurred when processing Content Type in '/opt/dotcms/shared/assets/bundles/01FA3MHYRSRNNPMHSQV70VPGBC/working/{SITE-NAME}/59f367a4-1784-4222-b1a2-69232696e92d.contentType.json' with ID '{CONTENT-TYPE-NAME}': 59f367a4-1784-4222-b1a2-69232696e92d
```

**To Reproduce**
1. Set up a Push Publishing environment: One sender, and one receiver.
2. In the Sender:
2.1. Create a Site named `mysite.com`.
2.2. Create a Content Type named `My CT` living under `mysite.com`. You can add a single text field.
2.3. Push it, and make sure it works.
3. In the Receiver:
3.1. Create a new Site named `receiversite.com`
3.2. Update the `My CT` type to point to the new `receiversite.com`.
3.3. Rename the `receiversite.com` Site to `mysite.com`. This way, we'll have two Sites with the exact same name, but different ID.
4. Go back to the Sender:
4.1. Clear the **Push History** for the `My CT`.
4.2. Push it again. You'll see the error I previously mentioned, following error in the log:
```
[08/07/21 14:02:29:701 EDT] ERROR receiver.BundlePublisher: Error publishing bundle with ID '01FA3MHYRSRNNPMHSQV70VPGBC.tar.gz': An error occurred when processing Content Type in '/opt/dotcms/shared/assets/bundles/01FA3MHYRSRNNPMHSQV70VPGBC/working/{SITE-NAME}/59f367a4-1784-4222-b1a2-69232696e92d.contentType.json' with ID 'CONTENT-TYPE-NAME': 59f367a4-1784-4222-b1a2-69232696e92d
com.dotcms.publishing.DotPublishingException: An error occurred when processing Content Type in '/opt/dotcms/shared/assets/bundles/01FA3MHYRSRNNPMHSQV70VPGBC/working/{SITE-NAME}/59f367a4-1784-4222-b1a2-69232696e92d.contentType.json' with ID 'CONTENT-TYPE-NAME': 59f367a4-1784-4222-b1a2-69232696e92d
	at com.dotcms.enterprise.publishing.remote.handler.ContentTypeHandler.a(SourceFile:165) ~[ee-5.3.8.5.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.ContentTypeHandler.handle(SourceFile:99) ~[ee-5.3.8.5.jar:?]
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:205) ~[dotcms_5.3.8.5_cb76208.jar:?]
	at com.dotcms.rest.PublishThread.processBundle(PublishThread.java:46) ~[dotcms_5.3.8.5_cb76208.jar:?]
	at com.dotcms.rest.PublishThread.run(PublishThread.java:30) ~[dotcms_5.3.8.5_cb76208.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: com.dotmarketing.exception.DotDataException: ERROR: insert or update on table "structure" violates foreign key constraint "fk_structure_host"
  Detail: Key (host)=(592429d9-ee1b-4149-9f0e-b0ed710bb172) is not present in table "identifier".{
  "SQL": ["update structure set name=?, description=? ,default_structure = ?,page_detail=?,structuretype=?,system=?,fixed=?,velocity_var_name=?,url_map_pattern=?,host=?,folder=?,expire_date_var=?,publish_date_var=?,mod_date=? where inode=?"],
  "maxRows": [-1],
  "offest": [0],
  "params": [
    "CONTENT-TYPE-NAME",
    null,
    false,
    null,
    1,
    false,
    false,
    "{CONTENT-TYPE-VAR}",
    null,
    "592429d9-ee1b-4149-9f0e-b0ed710bb172",
    "SYSTEM_FOLDER",
    null,
    null,
    "2021-07-08 14:02:30.0",
    "59f367a4-1784-4222-b1a2-69232696e92d"
  ]
}
```

**Expected behavior**
The push Publishing mechanism must provide useful error messages in order to fix any problems as soon as possible.

**Additional context**
Adequate error reporting of Push Publishing errors save both customers and the Support Team a lot of time when troubleshooting problems.

**Comment by jcastro-dotcms** [comment]
EE PR: https://github.com/dotCMS/enterprise/pull/819

**Comment by erickgonzalez** [comment]
With the new SiteKey must be a unique feature this can't be reproduced anymore.
