### ISSUE TITLE
NPE exception running site search Job 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#20653]
**Describe the bug**
A site search job 
Found in the Release-Branch 21.07
Site-search Job does not Run due to an NPE

**To Reproduce**

1. Go to Site Search and schedule a job to run "Now"
2. Fill in all required info. Then Watch the console an NPE pops up preventing the Job from running 

The following Error appears 

```
0:44:39.238  INFO  job.SiteSearchJobImpl - Incremental mode [no]. current index is `sitesearch_20210713104010_fd18fd41-e3f8-11eb-bfe7-acde48001122`. new index is `sitesearch_20210713104439_9d50c452-e3f9-11eb-bfe7-acde48001122`. alias is `sitesearch_20210713104010_fd18fd41-e3f8-11eb-bfe7-acde48001122`  bundle id is `57e16482-e581-4c54-ad34-0d429093a3ae_2021-07-13_10-44-39`
10:44:39.238  INFO  util.PushPublishLogger - class com.dotcms.publishing.PublisherAPIImpl : [BundleID: 57e16482-e581-4c54-ad34-0d429093a3ae_2021-07-13_10-44-39] Started Publishing Task
10:44:39.239  INFO  publishing.PublisherAPIImpl - Writing bundle.xml file
10:44:39.263  INFO  publishing.PublisherAPIImpl - Start of Bundler: FileAssetBundler
10:44:39.263  INFO  bundlers.FileAssetBundler - +baseType:4  +(conhost:8a7d5e23-da1e-420a-b4f0-471e7da8ea2d  )
10:44:39.297  ERROR publishing.PublisherAPIImpl - null
java.lang.NullPointerException: null
	at com.dotcms.publisher.util.dependencies.DependencyModDateUtil.<init>(DependencyModDateUtil.java:55) ~[dotcms_21.07_3433556.jar:?]
	at com.dotcms.publisher.util.dependencies.DependencyModDateUtil.<init>(DependencyModDateUtil.java:49) ~[dotcms_21.07_3433556.jar:?]
	at com.dotcms.enterprise.publishing.bundlers.FileAssetBundler.a(SourceFile:229) ~[ee-21.07.jar:?]
	at com.dotcms.enterprise.publishing.bundlers.FileAssetBundler.generate(SourceFile:171) ~[ee-21.07.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl.publish_aroundBody0(PublisherAPIImpl.java:125) ~[dotcms_21.07_3433556.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl$AjcClosure1.run(PublisherAPIImpl.java:1) ~[dotcms_21.07_3433556.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.9.2.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_21.07_3433556.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_21.07_3433556.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_21.07_3433556.jar:?]
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:43) ~[dotcms_21.07_3433556.jar:?]
	at com.dotcms.publishing.job.SiteSearchJobImpl.run(SiteSearchJobImpl.java:150) ~[dotcms_21.07_3433556.jar:?]
	at com.dotcms.publishing.job.SiteSearchJobProxy.run_aroundBody0(SiteSearchJobProxy.java:31) ~[dotcms_21.07_3433556.jar:?]
	at com.dotcms.publishing.job.SiteSearchJobProxy$AjcClosure1.run(SiteSearchJobProxy.java:1) ~[dotcms_21.07_3433556.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.9.2.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_21.07_3433556.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_21.07_3433556.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_21.07_3433556.jar:?]
	at com.dotcms.publishing.job.SiteSearchJobProxy.run(SiteSearchJobProxy.java:17) ~[dotcms_21.07_3433556.jar:?]
	at com.dotmarketing.quartz.DotJob.execute(DotJob.java:42) ~[dotcms_21.07_3433556.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223) ~[dot.quartz-all-1.8.6_2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) ~[dot.quartz-all-1.8.6_2.jar:?]

```

**Expected behavior**
You should be able to schedule a Job

**Comment by wezell** [comment]
Let's remove the manifest changes from 21.07 and retest this

**Comment by dsilvam** [comment]
Passed Internal QA: Site search working again after the revert.

**Comment by bryanboza** [comment]
Fixed, now we are not getting this error. Tested on release-21.07 // Postgres // FF 

New card related to site search here: #20704

**Comment by swicken-dotcms** [comment]
Excluding as it is not reproducible on 21.06
