### ISSUE TITLE
WARN being log when exec actions over a page

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#20731]
When exec any action over a page the following log is being logged several times:
```
12:12:01.826  WARN  factories.InodeFactory - getParentsOfClass failed:com.dotmarketing.exception.DotHibernateException: Error setting SQLQuery 
com.dotmarketing.exception.DotHibernateException: Error setting SQLQuery 
        at com.dotmarketing.db.HibernateUtil.setSQLQuery(HibernateUtil.java:223) ~[dotcms_master_aac9377.jar:?]
        at com.dotmarketing.factories.InodeFactory.getParentsOfClass(InodeFactory.java:1477) ~[dotcms_master_aac9377.jar:?]
        at com.dotmarketing.factories.InodeFactory.getParentsOfClass(InodeFactory.java:1449) ~[dotcms_master_aac9377.jar:?]
        at com.dotmarketing.factories.PublishFactory.getUnpublishedRelatedAssetsForPage_aroundBody0(PublishFactory.java:526) ~[dotcms_master_aac9377.jar:?]
Caused by: java.lang.NullPointerException
        at com.dotmarketing.db.HibernateUtil.getTableName(HibernateUtil.java:108) ~[dotcms_master_aac9377.jar:?]
        at com.dotmarketing.db.HibernateUtil.setSQLQuery(HibernateUtil.java:220) ~[dotcms_master_aac9377.jar:?]
        ... 129 more
```

This is because now Category mapping was deleted from the hibernate. We need to change all the calls of the InodeFactory when using Category and also add an exception in all the methods of the InodeFactory like this:
```java
if(c.equals(Template.class)){
			throw new DotStateException("Template mapping was deleted from hibernate files");
		}
```

It's expected to create/edit pages without any warn on the logs.

STR:
1- Go To Site > Browser
2-  Add a New Page
3- Click Publish 
4-  Check the logs (at UI nothing shows up, the page is created successfully).

**Comment by bryanboza** [comment]
Fixed, tested following the provided steps and I'm unable to reproduce. Tested on release-21.09 // Postgres // FF
