### ISSUE TITLE
We need to remove Folders from Hibernate 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#20742]
**Description**
Folder Identifiers are now set using the DeterministicIdentifierAPI however when checking integrity against a remote receiver where another folder with the same name and location is created a conflict shows up. That is because the integrity validation for folders is carried out by comparing the two assigned inodes. 

Therefore if we really want to avoid this sort of conflict we should use the generated deterministic identifier also as the inode.
In order to do that we will need to separate Folders from hibernate because the inode is automatically set by it. 

Three tasks:
1. Remove Hibernate from Folders
2. Make folder.inode and folder.id both deterministic and equal.
3. Use Upserts to insert and update folder data.
4. Drop the constrant `fk_structure_folder`

**To Reproduce**
See the steps listed on https://github.com/dotCMS/core/issues/20714

**Expected behavior**
Even though we create manually folders on two different instances of dotCMS they must have the exact same id and inode on both the sender and receiver.  And if we run an integrity check those new folders should not appear on the results

Related to https://github.com/dotCMS/core/issues/20714

**Comment by nollymar** [comment]
**Note to QA:** Please test to create/edit folders and also this issue https://github.com/dotCMS/core/issues/20714

**Comment by bryanboza** [comment]
We are login this every time you edit a folder, this is too noise in the log
```
testing_pg-dotcms-1         | 20:52:36.989  INFO  business.IdentifierAPIImpl - Creating new identifier for versionable asset of type `folder` and title `test` 
testing_pg-dotcms-1         | 20:52:36.990  INFO  business.DeterministicIdentifierAPIImpl - hashing id: folder:demo.dotcms.com//test to 9bbe0a1eb38e040ea1af11a1f1405d99
testing_pg-dotcms-1         | 20:52:40.544  INFO  log.accessLog - Method execution failed: 
testing_pg-dotcms-1         | com.dotmarketing.business.DotStateException: You should use the FolderAPI to get folder information
testing_pg-dotcms-1         | 	at com.dotmarketing.factories.InodeFactory.getInode(InodeFactory.java:109) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at com.dotmarketing.business.ajax.PermissionAjax.retrievePermissionable_aroundBody0(PermissionAjax.java:410) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at com.dotmarketing.business.ajax.PermissionAjax$AjcClosure1.run(PermissionAjax.java:1) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.9.2.jar:?]
testing_pg-dotcms-1         | 	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at com.dotmarketing.business.ajax.PermissionAjax.retrievePermissionable(PermissionAjax.java:347) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at com.dotmarketing.business.ajax.PermissionAjax.getAssetPermissions(PermissionAjax.java:96) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
testing_pg-dotcms-1         | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
testing_pg-dotcms-1         | 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
testing_pg-dotcms-1         | 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
testing_pg-dotcms-1         | 	at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule$1.doFilter(CreatorModule.java:229) ~[dot.dwr-3rc2modified_3.jar:?]
testing_pg-dotcms-1         | 	at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule.executeMethod(CreatorModule.java:241) ~[dot.dwr-3rc2modified_3.jar:?]
testing_pg-dotcms-1         | 	at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:379) ~[dot.dwr-3rc2modified_3.jar:?]
testing_pg-dotcms-1         | 	at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:332) ~[dot.dwr-3rc2modified_3.jar:?]
testing_pg-dotcms-1         | 	at com.dotcms.repackage.org.directwebremoting.dwrp.BaseCallHandler.handle(BaseCallHandler.java:104) ~[dot.dwr-3rc2modified_3.jar:?]
testing_pg-dotcms-1         | 	at com.dotcms.repackage.org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:120) ~[dot.dwr-3rc2modified_3.jar:?]
testing_pg-dotcms-1         | 	at com.dotcms.repackage.org.directwebremoting.servlet.DwrServlet.doPost(DwrServlet.java:141) ~[dot.dwr-3rc2modified_3.jar:?]
testing_pg-dotcms-1         | 	at com.dotmarketing.servlets.DwrWrapperServlet.doPost(DwrWrapperServlet.java:60) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) ~[servlet-api.jar:4.0.FR]
testing_pg-dotcms-1         | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[servlet-api.jar:4.0.FR]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at com.dotmarketing.filters.CMSFilter.doFilterInternal(CMSFilter.java:168) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:49) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at com.dotcms.visitor.filter.servlet.VisitorFilter.doFilter(VisitorFilter.java:95) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at com.dotcms.vanityurl.filters.VanityURLFilter.doFilter(VanityURLFilter.java:114) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176) ~[urlrewritefilter-4.0.4.jar:4.0.4]
testing_pg-dotcms-1         | 	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145) ~[urlrewritefilter-4.0.4.jar:4.0.4]
testing_pg-dotcms-1         | 	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92) ~[urlrewritefilter-4.0.4.jar:4.0.4]
testing_pg-dotcms-1         | 	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389) ~[urlrewritefilter-4.0.4.jar:4.0.4]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:140) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:88) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:50) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:99) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at com.dotcms.filters.NormalizationFilter.doFilter(NormalizationFilter.java:73) ~[dotcms_22.03_999999.jar:?]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[catalina.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-coyote.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-coyote.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888) ~[tomcat-coyote.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1693) ~[tomcat-coyote.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1122) ~[tomcat-coyote.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:617) ~[tomcat-coyote.jar:9.0.41]
testing_pg-dotcms-1         | 	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:595) ~[tomcat-coyote.jar:9.0.41]
testing_pg-dotcms-1         | 	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127) ~[?:?]
testing_pg-dotcms-1         | 	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:439) ~[?:?]
testing_pg-dotcms-1         | 	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:191) ~[?:?]
testing_pg-dotcms-1         | 	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213) ~[?:?]
testing_pg-dotcms-1         | 	at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:306) ~[?:?]
testing_pg-dotcms-1         | 	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112) ~[?:?]
testing_pg-dotcms-1         | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
testing_pg-dotcms-1         | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
testing_pg-dotcms-1         | 	at java.lang.Thread.run(Thread.java:829) [?:?]
testing_pg-dotcms-1         | 20:52:41.017  INFO  delegate.SystemEventsJobDelegate - The event: 84241899-2177-4e70-814a-aa820e081017, has been skipped on the server: c70a11b6-47e0-4ba7-94e0-58b377410040

```

**Comment by nollymar** [comment]
Good catch. This is the fix: https://github.com/dotCMS/core/pull/21783

**Note to QA:** Please verify that permissions over folders are working as expected

**Comment by alfredo-dotcms** [comment]
looks good to me!
![image](https://user-images.githubusercontent.com/37185433/156585960-fb65ae7b-7c07-41ff-a2cf-633b541f1139.png)

**Comment by bryanboza** [comment]
Fixed, tested setting permissions to folders and also tested fixing site and folders conflict, everything is working as expected . Tested on release-22.03 // MSSQL // FF
