### ISSUE TITLE
[Containers] : Creating a Container in high traffic instances is failing

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#21291]
Reported via Support: [105710](https://dotcms.zendesk.com/agent/tickets/105710)
Reproducible as of dotCMS 5.3.8.6.1, and probably latest master (21.11)

Depending on how content and content structures are being handled, there are customers that would create Content are on objects such as Containers directly in their production instances. Even though this is not recommended at all -- because of data integrity conflicts and other issues -- the system should be able to let Users add the objects they need, even if the current dotCMS instance is taking a lot of traffic.

The customer in question has a hard time adding a Container when their **PROD** instance is taking a lot of traffic during the day. I monitored their instance for a couple of days and confirmed the following:

- The customer's team and I tried creating a Container during high-traffic hours. We got intermittent error messages when doing so, which represented most of the attempts to create it.
- At night and early in the morning, I was able to create as many Containers as I needed. As soon as more people started interacting with the system, the intermittent error message started to show up.

Here's the stack trace seen in the `dotcms.log` file:
```
[19/11/21 14:19:00:643 GMT] INFO util.ActivityLogger: class com.dotmarketing.portlets.containers.action.EditContainerAction: XXXXXXXX : Save WebAsset action , User XXXXXX saved dotcms support Container test 1
[19/11/21 14:19:00:645 GMT] WARN action.EditContainerAction: java.lang.NullPointerException
java.lang.NullPointerException: null
at com.dotmarketing.business.VersionableAPIImpl.setWorking_aroundBody30(VersionableAPIImpl.java:543) ~[dotcms_5.3.8.6.1_999999.jar:?]
at com.dotmarketing.business.VersionableAPIImpl$AjcClosure31.run(VersionableAPIImpl.java:1) ~[dotcms_5.3.8.6.1_999999.jar:?]
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.3.8.6.1_999999.jar:?]
at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:59) ~[dotcms_5.3.8.6.1_999999.jar:?]
at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_5.3.8.6.1_999999.jar:?]
at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_5.3.8.6.1_999999.jar:?]
at com.dotmarketing.business.VersionableAPIImpl.setWorking(VersionableAPIImpl.java:537) ~[dotcms_5.3.8.6.1_999999.jar:?]
at com.dotmarketing.portlets.containers.action.EditContainerAction._saveWebAsset(EditContainerAction.java:580) ~[dotcms_5.3.8.6.1_999999.jar:?]
at com.dotmarketing.portlets.containers.action.EditContainerAction.processAction(EditContainerAction.java:157) ~[dotcms_5.3.8.6.1_999999.jar:?]
at com.liferay.portal.struts.PortletRequestProcessor.process(PortletRequestProcessor.java:126) ~[dotcms_5.3.8.6.1_999999.jar:?]
at com.liferay.portlet.StrutsPortlet.processAction(StrutsPortlet.java:120) ~[dotcms_5.3.8.6.1_999999.jar:?]
at com.liferay.portlet.ConcretePortletWrapper.processAction(ConcretePortletWrapper.java:97) ~[dotcms_5.3.8.6.1_999999.jar:?]
at com.liferay.portal.action.LayoutAction._processPortletRequest(LayoutAction.java:194) ~[dotcms_5.3.8.6.1_999999.jar:?]
at com.liferay.portal.action.LayoutAction._processActionRequest(LayoutAction.java:206) ~[dotcms_5.3.8.6.1_999999.jar:?]
...
...
```

**To Reproduce**
Please reach out to me for more details on this. I tried using Apache Benchmark to simulate server load in a local development environment, but I was still unable to reproduce the intermittent error message.

**Expected behavior**
The application must allow users to create any object in a production instance, even if it takes longer to save the data.

**Additional context**
Beyond discussing the fact that this portlet should be migrated to Angular, there are a few things worth noting regarding this problem:

- Using Push Publishing to send the Container to the production instance is the only valid workaround we have found. Given that the code handling the push is very different from the code that adds the Container through the back-end, I strongly believe this is a problem with the DWR-related classes.

- It seems like the method that sets the working version of the Container is not seeing the Identifier object that was previously created. This is the method where we create both the Identifier, and the actual Container: https://github.com/dotCMS/core/blob/532e44824bfe348778f7a9f224b603b46c830e3d/dotCMS/src/main/java/com/dotmarketing/portlets/containers/action/EditContainerAction.java#L546 Which is setting the working version too: https://github.com/dotCMS/core/blob/532e44824bfe348778f7a9f224b603b46c830e3d/dotCMS/src/main/java/com/dotmarketing/factories/WebAssetFactory.java#L163

However, the `EditContainerAction` class is setting the working version once again: https://github.com/dotCMS/core/blob/532e44824bfe348778f7a9f224b603b46c830e3d/dotCMS/src/main/java/com/dotmarketing/portlets/containers/action/EditContainerAction.java#L580 And this second call is the one that is causing the intermittent error message, so maybe that's something worth looking at.

**Comment by erickgonzalez** [comment]
Containers Portlet has been upgraded to Angular/Rest API. Closing since it no longer goes through the EditContainerAction, where it was the issue.
