### ISSUE TITLE
java.lang.NoClassDefFoundError errors after Java update

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#21536]
**Describe the bug**
Posting for visibility - probably not a dotCMS issue per se.

We encountered errors after upgrading Java on some servers running binary installs of current 5.3.8 LTS.

`openjdk 1.8.0.312.b07-1.amzn2.0.2.x86_64` seems to cause the errors.
Rolling back to `1.8.0.302.b08-0.amzn2.0.1.x86_64` resolves the errors.

We saw two errors
**1**
```
WARN content.ContentTool: pullRelated java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.search.fetch.subphase.highlight.FastVectorHighlighter @ url:GET//***
```
**2**
```
java.lang.NoClassDefFoundError: Could not initialize class java.nio.file.Files$FileTypeDetectors
at java.nio.file.Files.probeContentType(Files.java:1617) ~[?:1.8.0_312]
at com.dotcms.util.MimeTypeUtils.lambda$0(MimeTypeUtils.java:37) ~[dotcms_5.3.8.7_f67689f.jar:?]
at com.rainerhahnekamp.sneakythrow.Sneaky.lambda$sneaked$8(Sneaky.java:223) ~[sneakythrow-1.1.0.jar:?]
at com.rainerhahnekamp.sneakythrow.Sneaky.sneak(Sneaky.java:73) ~[sneakythrow-1.1.0.jar:?]
at com.dotcms.util.MimeTypeUtils.getMimeType(MimeTypeUtils.java:37) ~[dotcms_5.3.8.7_f67689f.jar:?]
at com.dotmarketing.portlets.contentlet.model.Contentlet.getTitleImage(Contentlet.java:1033) ~[dotcms_5.3.8.7_f67689f.jar:?]
at com.dotmarketing.portlets.contentlet.transform.strategy.DefaultTransformStrategy.addCommonProperties(DefaultTransformStrategy.java:116) ~[dotcms_5.3.8.7_f67689f.jar:?]
at com.dotmarketing.portlets.contentlet.transform.strategy.DefaultTransformStrategy.transform(DefaultTransformStrategy.java:85) ~[dotcms_5.3.8.7_f67689f.jar:?]
at com.dotmarketing.portlets.contentlet.transform.strategy.AbstractTransformStrategy.apply(AbstractTransformStrategy.java:95) ~[dotcms_5.3.8.7_f67689f.jar:?]
at com.dotmarketing.portlets.contentlet.transform.DotContentletTransformerImpl.lambda$3(DotContentletTransformerImpl.java:95) ~[dotcms_5.3.8.7_f67689f.jar:?]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_312]
at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_312]
```

**Comment by wezell** [comment]
@yolabingo -  just to be clear, this happens in the binary install, correct?  The 5.3.8 docker images are unaffected, correct?
