### ISSUE TITLE
Unable to save/publish Page on auth

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#21966]
**Describe the bug**
We're getting an NPE That looks like this

```
nginx-ssl-proxy_1  | 72.74.50.112 - - [05/Apr/2022:18:57:55 +0000] "PUT /api/v1/workflow/actions/b9d89c80-3d88-4311-8365-187323c96436/fire?inode=52b44c26-5e13-4153-a71e-0eb05d3ff24a&indexPolicy=WAIT_FOR HTTP/2.0" 500 16 "https://authoring.dotcms.com/dotAdmin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36" "-"
dotcms-auth_1      | 18:57:55.284  ERROR business.ESContentletAPIImpl - null
dotcms-auth_1      | java.lang.NullPointerException: null
dotcms-auth_1      | 	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.updateTemplateInAllLanguageVersions(ESContentletAPIImpl.java:5759) ~[dotcms_22.04_999999.jar:?]
dotcms-auth_1      | 	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.internalCheckin(ESContentletAPIImpl.java:4849) ~[dotcms_22.04_999999.jar:?]
dotcms-auth_1      | 	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.lambda$69(ESContentletAPIImpl.java:4424) ~[dotcms_22.04_999999.jar:?]
dotcms-auth_1      | 	at com.dotcms.concurrent.lock.StripedLockImpl.tryLock(StripedLockImpl.java:100) ~[dotcms_22.04_999999.jar:?]
dotcms-auth_1      | 	at com.dotcms.concurrent.lock.StripedLockImpl.tryLock(StripedLockImpl.java:55) ~[dotcms_22.04_999999.jar:?]
```

When saving page `/documentation/index` with inode `52b44c26-5e13-4153-a71e-0eb05d3ff24a`

**To Reproduce**
1. On Authoring Go to site-browser and open page `/documentation/index`
2. Click on SAve/Publish
3. An Error occurs showing a NPE message

**Expected behavior**
We should be able to save the page

**Comment by fabrizzio-dotCMS** [comment]
PR https://github.com/dotCMS/core/pull/21967

**Comment by nollymar** [comment]
**QA:** It is working as expected on auth

**Comment by erickgonzalez** [comment]
Only for 22.03 LTS

**Comment by erickgonzalez** [comment]
Customer tickets:
https://dotcms.zendesk.com/agent/tickets/109186
https://dotcms.zendesk.com/agent/tickets/109209
