### ISSUE TITLE
Allow follow redirects to be configured

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22512]
When accessing remote urls programmatically, we need to allow or disallow "follow redirects" on a system wide and case by case basis.  By default, this should be set to false.

**Comment by victoralfaro-dotcms** [comment]
Using local 22.07 executed the following:
```
 curl -u admin@dotcms.com:admin -XGET https://local.dotcms.site:8443/api/vtl/dynamic/  \
-H "Content-Type:text/plain" \
-d 'content = $import.read("https://dotcms.com")'

   content = $import.read("https://dotcms.com")
```

No response and got the following in the log:
```
21:26:12.036  WARN  exception.BadRequestException - {"error":"dotcms.api.error.bad_request: got invalid response for url: https://dotcms.com response: 301"}
com.dotcms.rest.exception.BadRequestException: HTTP 400 Bad Request
	at com.dotcms.http.CircuitBreakerUrl.lambda$doOut$2(CircuitBreakerUrl.java:234) ~[dotcms_22.07_999999.jar:?]
	at net.jodah.failsafe.Functions$12.call(Functions.java:274) ~[failsafe-1.1.1.jar:1.1.1]
	at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145) ~[failsafe-1.1.1.jar:1.1.1]
	at net.jodah.failsafe.SyncFailsafe.run(SyncFailsafe.java:93) ~[failsafe-1.1.1.jar:1.1.1]
	at com.dotcms.http.CircuitBreakerUrl.doOut(CircuitBreakerUrl.java:210) ~[dotcms_22.07_999999.jar:?]
	at com.dotcms.http.CircuitBreakerUrl.doOut(CircuitBreakerUrl.java:171) ~[dotcms_22.07_999999.jar:?]
	at com.dotcms.http.CircuitBreakerUrl.doString(CircuitBreakerUrl.java:165) ~[dotcms_22.07_999999.jar:?]
	at org.apache.velocity.tools.view.tools.ImportTool.read(ImportTool.java:100) ~[dotcms_22.07_999999.jar:?]
	at org.apache.velocity.tools.view.tools.ImportTool.read(ImportTool.java:77) ~[dotcms_22.07_999999.jar:?]
```
