### ISSUE TITLE
Can't add categories to a contentlet  

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#22787]
**Describe the bug**

Discovered while working on https://github.com/dotCMS/core/issues/22756

Can't add categories to a contentlet. The dialog is broken in the release branch `release-22.09` 

![Screen Shot 2022-08-18 at 09 54 35](https://user-images.githubusercontent.com/37148755/185441706-ef387838-7487-4ebb-b95e-d8afcd2ae205.png)

however, it is working on `release-22.08`

The dialog  does not bring categories due to a server-side exception caused by an array index out of bounds

```
java.lang.IndexOutOfBoundsException: fromIndex = -1
	at java.util.AbstractList.subListRangeCheck(AbstractList.java:505) ~[?:?]
	at java.util.ArrayList.subList(ArrayList.java:1138) ~[?:?]
	at com.dotmarketing.portlets.categories.business.CategoryAPIImpl.getCategoriesSubList(CategoryAPIImpl.java:649) ~[dotcms_22.09_999999.jar:?]
	at com.dotmarketing.portlets.categories.business.CategoryAPIImpl.findChildren(CategoryAPIImpl.java:311) ~[dotcms_22.09_999999.jar:?]
	at com.dotmarketing.servlets.JSONCategoriesServlet.doGet(JSONCategoriesServlet.java:96) ~[dotcms_22.09_999999.jar:?]
```

But the problem originated in the front-end 
Tracing exception to JSONCategoriesServlet the expected values to  properly slice the array are not arriving

![Screen Shot 2022-08-18 at 10 00 20](https://user-images.githubusercontent.com/37148755/185441571-4c1f23be-6768-4c21-8fe2-1c03aa7306f9.png)

Therefore the values initiated with -1 cause the IndexOutOfBoundsException

If use my debugger to initialize the start and count variables to something like 0, 10 the paginator still does not work
 and it looks like this: 
 
![Screen Shot 2022-08-18 at 09 54 24](https://user-images.githubusercontent.com/37148755/185442730-73b1d6f2-639d-42bf-8297-cd389a05228a.png)

See the NaN values

I've tried to trace the origin of the error in the JSP code and the servlet but nothing obvious has changed recently. This makes me think this is due to the recent upgrade we did to **dojo.** 

Additionally here are the errors on the js console 
![Screen Shot 2022-08-18 at 10 15 42](https://user-images.githubusercontent.com/37148755/185444251-8913c35f-0f4c-45a2-81f4-6ed60ba2fad0.png)

**To Reproduce**
1. Create a Content-Type with a categories field. 
2. Make the Category field point to a category with subcategories in it.
3. Go to Content Search and try to create a new instance of the content type in question 
4. See errors described above

**Expected behavior**
Naturally, you should be able to select categories and create a new instance of the content

**Comment by hmoreras** [comment]
PR: https://github.com/dotCMS/core/pull/22838/


*To QA*: 

This js error is expected by the moment, as long as is not braking nothing of the functionality : 
<img width="826" alt="image" src="https://user-images.githubusercontent.com/31667212/186272521-e15e7126-df69-4dc4-bb1b-f6725f09f724.png">

**Comment by josemejias07** [comment]
**Approved QA** - Tested on 22.09_64b40c74_SNAPSHOT // Docker // FF
