### ISSUE TITLE
PublisherQueueJob gets stuck waiting for dependencies

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23041]
Seen in dotCMS 22.03 - a customer push published some pages and the remote publishing never took place.  In inspecting the instance and taking a threaddump, you can see the `ConcurrentDependencyProcessor` is waiting forever for the next item in the queue.  We need a failsafe device that will return after, say, a minute, if there are no more items in the queue.

```
"dotCMSQuartz_Worker-10" daemon prio=5 tid=0x0000fffedd2d7800 waiting on condition [0x000000001c1e9312]
  java.lang.Thread.State: WAITING  (parking)
	at java.base@11.0.14.1/jdk.internal.misc.Unsafe.park(Native Method)
	- waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1c1e9312)
	at java.base@11.0.14.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.14.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	at java.base@11.0.14.1/java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:483)
	at java.base@11.0.14.1/java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:671)
	at com.dotcms.publisher.util.dependencies.ConcurrentDependencyProcessor.waitUntilResolveAllDependencies(ConcurrentDependencyProcessor.java:134)
	at com.dotcms.publisher.util.dependencies.PushPublishigDependencyProcesor.waitUntilResolveAllDependencies(PushPublishigDependencyProcesor.java:728)
	at com.dotcms.publisher.pusher.PushPublisherConfig.waitUntilResolveAllDependencies(PushPublisherConfig.java:292)
	at com.dotcms.publisher.util.dependencies.DependencyManager.setDependencies(DependencyManager.java:333)
	at com.dotcms.enterprise.publishing.remote.bundler.DependencyBundler.generate(SourceFile:64)
	at com.dotcms.publishing.PublisherAPIImpl.publish_aroundBody0(PublisherAPIImpl.java:118)
	at com.dotcms.publishing.PublisherAPIImpl$AjcClosure1.run(PublisherAPIImpl.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29)
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41)
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:47)
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:42)
	at com.dotcms.publisher.business.PublisherQueueJob.execute_aroundBody0(PublisherQueueJob.java:186)
	at com.dotcms.publisher.business.PublisherQueueJob$AjcClosure1.run(PublisherQueueJob.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42)
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29)
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41)
	at com.dotcms.publisher.business.PublisherQueueJob.execute(PublisherQueueJob.java:112)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549)
```

**Comment by wezell** [comment]
Another customer reporting this

**Comment by wezell** [comment]
The job is running, just hung
![Screen Shot 2022-10-04 at 2 23 55 PM](https://user-images.githubusercontent.com/934364/193896458-4644a395-9ae6-4bf6-961d-28bfe3d76937.png)

**Comment by erickgonzalez** [comment]
Another customer: https://dotcms.zendesk.com/agent/tickets/108884

**Comment by erickgonzalez** [comment]
Code doesn't exist in 21.06 LTS
