### ISSUE TITLE
Remove repackaged version of `commons-io`

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#23123]
We should get rid of `dot.commons-io` in all over the code and use `commons-io` that is already a transitive dependency in the project.

**Acceptance Criteria:** 

The project must compile and tests run in green

**Comment by nollymar** [comment]
PRs: 
https://github.com/dotCMS/enterprise/pull/888
#23124

**Comment by nollymar** [comment]
Breaking change: The `dot.commons-io` was replaced by the non-repackaged `commons-io`. This change might cause compilation issues in those customers who use dot.commons-io as a dependency in their plugins. They should use `commons-io` instead.

**Comment by wezell** [comment]
This breaks Webdav - I am getting this error when connecting via webdav:
```

14:48:20.565  ERROR http.MiltonServlet - Exception starting milton servlet
java.lang.NoClassDefFoundError: com/dotcms/repackage/org/apache/commons/io/output/ByteArrayOutputStream
	at com.dotcms.repackage.com.bradmcevoy.http.webdav.DefaultWebDavResponseHandler.<init>(DefaultWebDavResponseHandler.java:65) ~[dot.milton-api-1.8.1.4_3.jar:?]
	at com.dotcms.repackage.com.bradmcevoy.http.HttpManager.<init>(HttpManager.java:122) ~[dot.milton-api-1.8.1.4_3.jar:?]
	at com.dotcms.repackage.com.bradmcevoy.http.ServletHttpManager.<init>(ServletHttpManager.java:45) ~[dot.milton-servlet-1.8.1.4_3.jar:?]
	at com.dotcms.repackage.com.bradmcevoy.http.MiltonServlet.init(MiltonServlet.java:161) ~[dot.milton-servlet-1.8.1.4_3.jar:?]
	at com.dotcms.repackage.com.bradmcevoy.http.MiltonServlet.init(MiltonServlet.java:119) ~[dot.milton-servlet-1.8.1.4_3.jar:?]
	at com.dotcms.repackage.com.bradmcevoy.http.MiltonServlet.init(MiltonServlet.java:98) ~[dot.milton-servlet-1.8.1.4_3.jar:?]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1164) ~[catalina.jar:9.0.60]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1117) ~[catalina.jar:9.0.60]
```

**Comment by wezell** [comment]
I think we will need to make sure that these libraries are updated as well:
https://github.com/dotCMS/dotcms-libs

**Comment by fabrizzio-dotCMS** [comment]
New PR here https://github.com/dotCMS/core/pull/23282

**Comment by fabrizzio-dotCMS** [comment]
new PR here https://github.com/dotCMS/core/pull/23287

**Comment by jdotcms** [comment]
Internal QA:

1. D&D a folder: everything have been uploaded ok.
2. Deleting a file on the webdav, it is reflected on the site browser
3. Deleting a file on the site browser, it is reflected on the webdav
4. On Webdav copying an asset to another folder, it is reflected on the sitebrowser
5. On Site Browser copying an asset to another folder, it is reflected on the webdav
6. Uploading file into the site browser are being reflected on webdav
7. Getting login with JWT instead of password also works.

**Comment by bryanboza** [comment]
Fixed, tested on release-22.11 // Docker // FF

**Comment by wezell** [comment]
We need to test 22.11 with WebDav

**Comment by bryanboza** [comment]
Tested on release-22.12 // Docker.... 

Multiple errors was moved to a new cards, then we can close this for now
