### ISSUE TITLE
Block Editor is not refreshing after Update and breaking on Re-edit

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#23388]
Tested on 22.10.2 using chrome

To reproduce: 

1) Deploy EMA, then go to starter blogs page and click on a blog, then go to edit mode to edit the blog.
2) Add a new headline or contentlet to the article and click Update
3) Try to click on the article again to re-edit,... bug is that the edit screen is blank and there is an error in the console.

https://user-images.githubusercontent.com/751424/202517955-fd54a79e-45c8-4389-a0c4-65bde738b82f.mp4

```
main.bbe1bf35292614a0.js:1 ERROR TypeError: Cannot read properties of null (reading ‘destroy’)
    at Object.l [as onExit] (7474.a9b4e3df17beff06.js:1:347177)
    at Object.destroy (7474.a9b4e3df17beff06.js:1:307424)
    at Pb.destroyPluginViews (7474.a9b4e3df17beff06.js:1:239464)
    at Pb.destroy (7474.a9b4e3df17beff06.js:1:243050)
    at N0.destroy (7474.a9b4e3df17beff06.js:1:301128)
    at n.ngOnDestroy (7474.a9b4e3df17beff06.js:1:501156)
    at Yd (main.bbe1bf35292614a0.js:1:831902)
    at Ds (main.bbe1bf35292614a0.js:1:831922)
    at Ql (main.bbe1bf35292614a0.js:1:831566)
    at Zl (main.bbe1bf35292614a0.js:1:831592)
```

**Comment by rjvelazco** [comment]
Unable to reproduce this issue on the last docker image. [`23.01_a7ac1417_SNAPSHOT `]

https://user-images.githubusercontent.com/72418962/209699121-9bf3590c-15fb-47c0-b91b-ead34aaddffe.mov
