### ISSUE TITLE
NPE loading Field 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#23397]
### Describe the bug
during a customer upgrade, we discovered that one of the old existing pages whose template data was stored in columns doesn't load because of a buggy condition that states that we do not support column-stored data. 
The fix is to get rid of that condition 

```
@CloseDBIfOpened
    public Object loadField(final String inode, final com.dotcms.contenttype.model.field.Field field) throws DotDataException{
        final ContentletJsonAPI contentletJsonAPI = APILocator.getContentletJsonAPI();
        if(APILocator.getContentletJsonAPI().isPersistContentAsJson()){
            final Object value = contentFactory.loadJsonField(inode, field);
            if(null != value){
                return value;
            }

            if(!contentletJsonAPI.isPersistContentletInColumns()){.     
                return null;      <---  Must go away !!!!
            }
            //But if passed this check then we should also give a try fetching the field from the columns.
        }
        return contentFactory.loadField(inode, field.dbColumn());
    }
```
The fix for this is basically removing the return null 

### To Reproduce
1. Get in touch with @swicken-dotcms or @fabrizzio-dotCMS for details on how to reproduce this issue
2. Error looks like this: 

```
10:08:36.583  ERROR business.ESContentletAPIImpl - null
java.lang.NullPointerException: null
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.updateTemplateInAllLanguageVersions(ESContentletAPIImpl.java:5736) ~[dotcms_22.03.3_2857d37.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.internalCheckin(ESContentletAPIImpl.java:4868) ~[dotcms_22.03.3_2857d37.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.lambda$69(ESContentletAPIImpl.java:4434) ~[dotcms_22.03.3_2857d37.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$$Lambda$2350/0x000000006ffeb820.execute(Unknown Source) ~[?:?]
	at com.dotcms.concurrent.lock.StripedLockImpl.tryLock(StripedLockImpl.java:100) ~[dotcms_22.03.3_2857d37.jar:?]
	at com.dotcms.concurrent.lock.StripedLockImpl.tryLock(StripedLockImpl.java:55) ~[dotcms_22.03.3_2857d37.jar:?]
```
### Expected behavior
We should be able to save pages that originally existed with a template field saved in columns on any newer version of dotCMS that has support for contentlet as json 

### Acceptance criteria
- Verify that the pages that caused the NPE on the customer db can be saved with no problem

**Comment by fabrizzio-dotCMS** [comment]
It appears that this issue had already been fixed by https://github.com/dotCMS/core/issues/21966
