### ISSUE TITLE
Add container code to advanced template is broken 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#23557]
### Describe the bug
In master branch you can not add a container into an advanced template 

### To Reproduce
1. Go to Templates, Create a new Template (Advanced Template)
2. Click on the dropdown to include a new Container. SElect any container 
3. See that nothing happens 
```
main.b5e4e600e5300744.js:1 ERROR TypeError: this.editor.getSelection is not a function
    at o.containerChange (5722.9f15a6e40d6f8102.js:1:25528)
    at 5722.9f15a6e40d6f8102.js:1:26760
    at ov (main.b5e4e600e5300744.js:1:861346)
    at Object.g [as next] (main.b5e4e600e5300744.js:1:861485)
    at b.__tryOrUnsub (main.b5e4e600e5300744.js:1:652764)
    at b.next (main.b5e4e600e5300744.js:1:651993)
    at v._next (main.b5e4e600e5300744.js:1:651172)
    at v.next (main.b5e4e600e5300744.js:1:650946)
    at uw.next (main.b5e4e600e5300744.js:1:648680)
    at uw.emit (main.b5e4e600e5300744.js:1:878239)
```

### Expected behavior
You should be able to select any available template and the code that includes the selected template in the Template body

### Screenshots

https://user-images.githubusercontent.com/37148755/206780359-7c7d86ed-ed1f-46ad-9871-fd9ffee13452.mov

**Comment by bryanboza** [comment]
Fixed, tested on release-23.01 // Docker // FF
