### ISSUE TITLE
Error when update zero size file through Webdav or CLI.

### ISSUE THREAD

**Issue by EdgarPsda** [dotCMS/core#24042]
### Problem Statement

When try to update a zero size file through webdav an error appears, this error is related with a 
`fk_contentlet_version_info_working` value.

## Windows commands:
Create zero size file

`type nul > zero-size.file`

 Create non-zero size file

`echo not empty > non-zero-size.file`

Check the file sizes

`dir *.file`
 
Upload non-zero size file with webdav using curl

`curl --verbose --user "admin@dotcms.com:admin" -T ".\non-zero-size.file" https://demo.dotcms.com/webdav/live/1/demo.dotcms.com/test-file.vtl`

Upload zero size file with webdav using curl

`curl --verbose --user "admin@dotcms.com:admin" -T ".\zero-size.file" https://demo.dotcms.com/webdav/live/1/demo.dotcms.com/test-file.vtl`

## Linux commands:
Create zero size file

`touch zero-size.file`

Create non-zero size file
`echo not empty > non-zero-size.file`

 Check the file sizes

`ls *.file -al`

 
Upload non-zero size file with webdav using curl

`curl --verbose --user 'admin@dotcms.com:admin' -T './non-zero-size.file' https://demo.dotcms.com/webdav/live/1/demo.dotcms.com/test-file.vtl`

 
Upload zero size file with webdav using curl
`curl --verbose --user 'admin@dotcms.com:admin' -T './zero-size.file' https://demo.dotcms.com/webdav/live/1/demo.dotcms.com/test-file.vtl`

### Following error message appears when upload/update zero size file:

```
[06/02/23 16:37:51:138 UTC] WARN webdav.HostResourceImpl: An error occurred while creating new file: test-file.vtl in this path: /webdav/live/1/default/ ERROR: update or delete on table "contentlet" violates foreign key constraint "fk_contentlet_version_info_working" on table "contentlet_version_info"
Detail: Key (inode)=(3a5ebb93-7dd8-4898-bb30-3fb959d5b222) is still referenced from table "contentlet_version_info".{
"SQL": ["delete from contentlet where inode=?"],
"maxRows": [-1],
"offest": [0],
"params": "3a5ebb93-7dd8-4898-bb30-3fb959d5b222"
}
com.dotmarketing.exception.DotDataException: ERROR: update or delete on table "contentlet" violates foreign key constraint "fk_contentlet_version_info_working" on table "contentlet_version_info"
Detail: Key (inode)=(3a5ebb93-7dd8-4898-bb30-3fb959d5b222) is still referenced from table "contentlet_version_info".{
"SQL": ["delete from contentlet where inode=?"],
"maxRows": [-1],
"offest": [0],
"params": "3a5ebb93-7dd8-4898-bb30-3fb959d5b222"
}
at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:273) ~[dotcms_22.03.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.delete(ESContentFactoryImpl.java:603) ~[dotcms_22.03.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.deleteVersion(ESContentFactoryImpl.java:766) ~[dotcms_22.03.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.deleteVersion_aroundBody88(ESContentletAPIImpl.java:2870) ~[dotcms_22.03.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure89.run(ESContentletAPIImpl.java:1) ~[dotcms_22.03.2_999999.jar:?]
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.9.2.jar:?]
at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_22.03.2_999999.jar:?]
at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:119) ~[dotcms_22.03.2_999999.jar:?]
at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:30) ~[dotcms_22.03.2_999999.jar:?]
at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_22.03.2_999999.jar:?]
at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.deleteVersion(ESContentletAPIImpl.java:2856) ~[dotcms_22.03.2_999999.jar:?]
at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.deleteVersion(ContentletAPIInterceptor.java:2362) ~[dotcms_22.03.2_999999.jar:?]
at com.dotmarketing.webdav.DotWebdavHelper.setResourceContent(DotWebdavHelper.java:849) ~[dotcms_22.03.2_999999.jar:?]
```
 

![Screenshot 2023-02-06 at 8 37 09 AM](https://user-images.githubusercontent.com/12899960/217030213-016e78ea-bacc-4046-8eda-2a019c3f894b.png)
![Screenshot 2023-02-06 at 8 37 27 AM](https://user-images.githubusercontent.com/12899960/217030275-ea613166-4171-4cbb-a154-93b73c7e3b4c.png)

### Acceptance Criteria

In both cases (zero file size or non-zero file size) the file can be updated/upload and it's showing good results in backend dashboard, but those error messages still in the system logs.

### dotCMS Version

This was tested locally with 22.03.2 version and demo site 23.01.

### Proposed Objective

Application Performance

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/109728

**Comment by wezell** [comment]
Many of our installs set `CONTENT_ALLOW_ZERO_LENGTH_FILES` to `true`.  If you set this parameter to `true` does webdav work as expected?  If so, this is not a bug.  It might be that we want to update our default value but we don't need to change code if it works as expected.

**Comment by nollymar** [comment]
@EdgarPsda could you please check what Will said?

**Comment by EdgarPsda** [comment]
Ok guys, I will do my test locally.

**Comment by EdgarPsda** [comment]
@nollymar actually I'm able to upload/update zero file size, the only thing here is that the error message comes when you hit the action.

**Comment by dcolina** [comment]
## Internal QA: Passed.

The issue couldn't be reproduced anymore. It was tested using the docker image `dotcms/dotcms:trunk_b69a711`.

https://github.com/user-attachments/assets/0005852b-05e1-43f2-9e6d-02dc4588546f

**Comment by bryanboza** [comment]
Fixed, tested on trunk // Docker // FF 
![Image](https://github.com/user-attachments/assets/9c921541-9a32-4b80-bf51-2e52f342699b)
