### ISSUE TITLE
Copy Child Content-Type breaks relationship

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#24414]
### Parent Issue

This defect was discovered while working on https://github.com/dotcms/core/issues/19101

### Problem Statement

We have a copy Content-type functionality that works fairly well in the majority of cases. However, if we try to copy a CT that has a relationship field that points back to its parent (using an inverse relationship) causes trouble.
Let's suppose we have a parent CT **A** with a relationship field that points to a child CT **B** it's a one-to-many type of relation.  Our Child CT also has a Relationship field that is set to point back at its parent. Then let's say we have two Content-types like:

![Screenshot 2023-03-20 at 08 44 16](https://user-images.githubusercontent.com/37148755/226375480-d610e1ed-9259-4d7c-9b6f-b8c2f24d6a3f.png)

![Screenshot 2023-03-20 at 08 44 33](https://user-images.githubusercontent.com/37148755/226375543-bec15d1c-814e-45bc-93c3-7e114c0965e7.png)

if we have a look at the relationship table entry for the Child CT using the following query

select * from relationship r where parent_structure_inode = 'f693aee86709b1884637d482e7d0f271' or child_structure_inode = 'f693aee86709b1884637d482e7d0f271';

it's gonna look like this: 
![Screenshot 2023-03-20 at 08 51 49](https://user-images.githubusercontent.com/37148755/226377743-f80780f7-767d-4cef-b0cf-5a766f6f66e3.png)

So far so good. The data in the table reflects what we have structured in our Types. We have a field that points to the parent named **observer** and also a field in the parent that points to our child structure named **child**.

Please notice that the data on the relationship record is also related with the data present in the Fields table.
This means that it is expected a field named "observer" in the child CT and a field named "child" in the parent CT.

Now if I make a copy of the CT **B**  the data stored in the relationship tables gets updated as follows 

![Screenshot 2023-03-20 at 09 08 25](https://user-images.githubusercontent.com/37148755/226382622-cf4d501d-78aa-4ea3-87d8-df699e3ba8dc.png)

Now we have two fields named observer in the **relation** record for the original Content-Type. An inconsistency here has been created since this leads the system to believe that the fields in the parent CT should be named **observer**. The Child relationship is broken.

Now deleting the child CT is also not possible as we get the following error in the FE

![Screenshot 2023-03-20 at 09 22 42](https://user-images.githubusercontent.com/37148755/226387007-7eca0a65-3593-4422-9d1d-50151449ca91.png)

accompanied with the following stack-trace

```
09:22:35.288  ERROR contenttype.ContentTypeResource - Error deleting content type
com.dotcms.contenttype.exception.NotFoundInDbException: Field variable with var: (observer) not found on CT (A).
	at com.dotcms.contenttype.business.FieldFactoryImpl.byContentTypeFieldVar(FieldFactoryImpl.java:65) ~[dotcms_master_dacda3e.jar:?]
	at com.dotcms.contenttype.business.FieldAPIImpl.byContentTypeAndVar(FieldAPIImpl.java:752) ~[dotcms_master_dacda3e.jar:?]
	at com.dotcms.contenttype.business.FieldAPIImpl.byContentTypeIdAndVar(FieldAPIImpl.java:766) ~[dotcms_master_dacda3e.jar:?]
	at com.dotcms.contenttype.business.ContentTypeFactoryImpl.deleteRelationships(ContentTypeFactoryImpl.java:956) ~[dotcms_master_dacda3e.jar:?]
	at com.dotcms.contenttype.business.ContentTypeFactoryImpl.dbDelete(ContentTypeFactoryImpl.java:645) ~[dotcms_master_dacda3e.jar:?]
	at com.dotcms.contenttype.business.ContentTypeFactoryImpl.delete(ContentTypeFactoryImpl.java:180) ~[dotcms_master_dacda3e.jar:?]
	at com.dotcms.contenttype.business.ContentTypeAPIImpl.prepAsyncDelete(ContentTypeAPIImpl.java:124) ~[dotcms_master_dacda3e.jar:?]
	at com.dotcms.contenttype.business.ContentTypeAPIImpl.delete(ContentTypeAPIImpl.java:92) ~[dotcms_master_dacda3e.jar:?]
	at com.dotcms.rest.api.v1.contenttype.ContentTypeResource.deleteType(ContentTypeResource.java:528) ~[dotcms_master_dacda3e.jar:?]
```

The code that causes this problem wasn't introduced specifically for the copy CT functionality.
But is it in our FieldAPI itself when calling 

```
Optional<Relationship> relationship = getRelationshipForField(result, contentTypeAPI,
                  type, user);

```
which internally does. 
```
relationship = relationshipAPI.getRelationshipFromField(field, user);

            //verify if the relationship already exists
            if (UtilMethods.isSet(relationship) && UtilMethods.isSet(relationship.getInode())) {

                updateRelationshipObject(field, type, relatedContentType, relationship, cardinality, user);

            }
```

The solution to this problem isn't straightforward. 

The above code isn't able to tell we're dealing with a brand-new field that belongs to a brand-new CT that is getting copied out from the original. It does do a look-up by the **reltion_type_value** finding an existing entry leading the code to believe it has to modify an existing relationship which isn't the case at all. 

For this code to work without having to make any heavy modification I would like to see the new field getting copied coming in with a value like "ACopy.child" since **reltion_type_value** is unique. 

Therefore I think a clean fix would be something like this: When we copy a content type that has a relationship we also copy the related  Content-Types

 

to

### Steps to Reproduce

1. Create 2 CT  A, B as described in the Problem statement 
2. Parent CT has to have a one-to-many relationship field.  Select "required" and "User Searchable"  

![Screenshot 2023-03-20 at 10 02 06](https://user-images.githubusercontent.com/37148755/226398831-989774a0-d3f7-4a0d-abdc-09dd97d49270.png)

3. Child CT also has to have a relationship field point back a the parent. 

When adding this field choose the option **Existing** and select the parent content-type A

![Screenshot 2023-03-20 at 10 02 30](https://user-images.githubusercontent.com/37148755/226398918-c7090867-0227-4b82-a00a-8f59c194d778.png)

4. Add a child instance of CT B
5. Add an instance of the Parent CT and have it  point at the child instance
6. Now from the  Content-types Portlet make a copy of the Child CT "B"
7. And finally attempt to remove the Original Child Content-Type B
8. You should see an error message like **"Field variable with var: (observer) not found on CT (A)."**

Additional context this issue can be seen in our demo site if you simply try to remove our Blog Content-Type

### Acceptance Criteria

Making a copy of a child-related CT shouldn't alter the structure of the relationship incorrectly the relationship should continue to work as expected and Removing the CT should be possible  at all times 

### dotCMS Version

This problem is present in 23.02 and earlier 

### Proposed Objective

Customer Success

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
https://helpdesk.dotcms.com/a/tickets/30477

_No response_

**Comment by erickgonzalez** [comment]
@nollymar, it seems that a customer is hitting this issue. Please consider this to your next sprint :) Thanks in advance. cc @Neehakethi 

Customer Ticket: https://helpdesk.dotcms.com/a/tickets/30477
