### ISSUE TITLE
Unable to upload File Asset using Podman

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#24937]
### Problem Statement

The customer is having issues uploading/editing file assets when deploying dotcms using Podman instead of Docker.

Error log:
```
06/05/23 09:40:43:065 UTC] ERROR transform.ContentletTransformer: Unable to populate contentlet from json for ID='c4469697-8445-4737-96fb-e27b7b9f4f35', Inode='9ed78a01-1dfa-43ef-8f34-7a8e3da364dc', Content-Type '33888b6f-7a8e-4069-b1b6-5c1aa9d0a48d': Cannot construct instance of `java.io.Serializable` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (String)"{"inode": "9ed78a01-1dfa-43ef-8f34-7a8e3da364dc", "owner": "1431830", "title": "js.vtl", "fields": {"title": {"type": "Text", "value": "js.vtl"}, "fileName": {"type": "Text", "value": "js.vtl"}, "fileAsset": {"type": "Binary", "value": "js.vtl", "metadata": {"name": "js.vtl", "sha256": "465dc7f6886a1375b4320b21bd8ad93fa2b7fedc9ca57974843b41092edb7a71", "isImage": false, "contentType": "text/velocity"}}, "sortOrder": {"type": "Long", "value": 0}, "description": {"type": "Text", "value": "js"}}, ""[truncated 293 chars]; line: 1, column: 793] (through reference chain: com.dotcms.content.model.ImmutableContentlet$Json["fields"]->java.util.LinkedHashMap["fileAsset"]->com.dotcms.content.model.type.system.BinaryFieldType$Json["metadata"]->java.util.LinkedHashMap["name"])
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `java.io.Serializable` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (String)"{"inode": "9ed78a01-1dfa-43ef-8f34-7a8e3da364dc", "owner": "1431830", "title": "js.vtl", "fields": {"title": {"type": "Text", "value": "js.vtl"}, "fileName": {"type": "Text", "value": "js.vtl"}, "fileAsset": {"type": "Binary", "value": "js.vtl", "metadata": {"name": "js.vtl", "sha256": "465dc7f6886a1375b4320b21bd8ad93fa2b7fedc9ca57974843b41092edb7a71", "isImage": false, "contentType": "text/velocity"}}, "sortOrder": {"type": "Long", "value": 0}, "description": {"type": "Text", "value": "js"}}, ""[truncated 293 chars]; line: 1, column: 793] (through reference chain: com.dotcms.content.model.ImmutableContentlet$Json["fields"]->java.util.LinkedHashMap["fileAsset"]->com.dotcms.content.model.type.system.BinaryFieldType$Json["metadata"]->java.util.LinkedHashMap["name"])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67) ~[jackson-databind-2.9.3.jar:2.9.3]
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1451) ~[jackson-databind-2.9.3.jar:2.9.3]
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1027) ~[jackson-databind-2.9.3.jar:2.9.3]
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:265) ~[jackson-databind-2.9.3.jar:2.9.3]
```

### Steps to Reproduce

N/A

### Acceptance Criteria

Should be able to upload file assets regardless of the architecture being used.

### dotCMS Version

22.03 LTS

### Proposed Objective

Customer Support

### Proposed Priority

Priority 1 - Show Stopper

**Comment by nollymar** [comment]
**Note to QA:** Save file assets and verify if their metadata is generated correctly

**Comment by erickgonzalez** [comment]
Just as a note, the customer confirmed this is working for them.

**Comment by josemejias11** [comment]
Hi @erickgonzalez,

Just to confirm. This is supposed to be a Postman via test, right? Or is just a Backend fix?

**Comment by fabrizzio-dotCMS** [comment]
> Hi @erickgonzalez,
> 
> Just to confirm. This is supposed to be a Postman via test, right? Or is just a Backend fix?

This was a backend fix. @josemejias11

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_b98a1003_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
