### ISSUE TITLE
Remove hardcoded referrer from Reach Page conditions 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#25020]
### Parent Issue

https://github.com/dotCMS/core/issues/22760

### Problem Statement

When an Experiment is configured with a Reach Page goal, there's a internal condition hardcoded which is that the referrer needs to be the page where the Experiment is created. This is not convenient since it lefts out cases like for example reaching a thank-you page, which can be a number of hops ahead of the page being tested, for example a particular product. 

The referrer needs to be empty. 

### Steps to Reproduce

* Configure a Experiment with a reach page goal to a certain page
* Hit the page not coming straight from the page in the Experiment
Current Behavior: The goal will not be counted. 
Expected: The goal should be counted. 

### Acceptance Criteria

When configuring an Experiment with a Reach Page goal, reaching the specified Page does not necessarily need to come from the page in the Experiment. 

IMPORTANT: The Experiment page need to be visited previous to reaching the specified Page (anytime before)

Automated test

### dotCMS Version

master / 23.06

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by victoralfaro-dotcms** [comment]
Setting experiment for `blogs` page. Target page is `store`.
For variant version it registered successfully the events with these hops: home -> blogs -> contat-us -> destinations -> store.
![image](https://github.com/dotCMS/core/assets/64026161/6beda842-7e29-47ea-a663-939b93688b61)
However for the original is not registering any events as seen in the screenshot.
Got this error from logs:
```
docker-dotcms-app-1  | 18:10:08.710  ERROR bayesian.BayesianAPIImpl - Cannot calculate probability with zero interactions for input: BayesianInput{type=AB, control=VariantBayesianInput{variant=DEFAULT, successes=0, failures=0}, variantPairs=[VariantBayesianInput{variant=dotexperiment-3cfc6a6221-variant-1, successes=1, failures=0}], priors=[BayesianPriors{alpha=1.0, beta=1.0}]}
docker-dotcms-app-1  | com.dotmarketing.exception.DotDataException: Variant successes and failures cannot be zero
docker-dotcms-app-1  | 	at com.dotcms.analytics.bayesian.BayesianAPIImpl.validateInput(BayesianAPIImpl.java:651) ~[dotcms_null.jar:?]
docker-dotcms-app-1  | 	at com.dotcms.analytics.bayesian.BayesianAPIImpl.noopFallback(BayesianAPIImpl.java:673) ~[dotcms_null.jar:?]
docker-dotcms-app-1  | 	at com.dotcms.analytics.bayesian.BayesianAPIImpl.doBayesian(BayesianAPIImpl.java:56) ~[dotcms_null.jar:?]
docker-dotcms-app-1  | 	at com.dotcms.experiments.business.ExperimentsAPIImpl.calcBayesian(ExperimentsAPIImpl.java:956) ~[dotcms_null.jar:?]
docker-dotcms-app-1  | 	at com.dotcms.experiments.business.ExperimentsAPIImpl.getResults(ExperimentsAPIImpl.java:926) ~[dotcms_null.jar:?]
docker-dotcms-app-1  | 	at com.dotcms.rest.api.v1.experiments.ExperimentsResource.getResult(ExperimentsResource.java:500) ~[dotcms_null.jar:?]
docker-dotcms-app-1  | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
docker-dotcms-app-1  | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
docker-dotcms-app-1  | 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
docker-dotcms-app-1  | 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[jersey-server-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[jersey-server-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[jersey-server-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[jersey-server-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[jersey-server-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[jersey-server-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[jersey-server-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) ~[jersey-server-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[jersey-common-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[jersey-common-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[jersey-common-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) ~[jersey-common-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) ~[jersey-server-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) ~[jersey-server-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471) ~[jersey-container-servlet-core-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425) ~[jersey-container-servlet-core-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383) ~[jersey-container-servlet-core-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336) ~[jersey-container-servlet-core-2.22.1.jar:?]
docker-dotcms-app-1  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223) ~[jersey-container-servlet-core-2.22.1.jar:?]
docker-dotcms-app-1  | 	at com.dotcms.rest.servlet.ReloadableServletContainer.service(ReloadableServletContainer.java:117) ~[dotcms_null.jar:?]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at com.dotmarketing.filters.CMSFilter.doFilterInternal(CMSFilter.java:181) ~[dotcms_null.jar:?]
docker-dotcms-app-1  | 	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:61) ~[dotcms_null.jar:?]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_null.jar:?]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_null.jar:?]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at com.dotcms.visitor.filter.servlet.VisitorFilter.doFilter(VisitorFilter.java:81) ~[dotcms_null.jar:?]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at com.dotcms.vanityurl.filters.VanityURLFilter.doFilter(VanityURLFilter.java:114) ~[dotcms_null.jar:?]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176) ~[urlrewritefilter-4.0.4.jar:4.0.4]
docker-dotcms-app-1  | 	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145) ~[urlrewritefilter-4.0.4.jar:4.0.4]
docker-dotcms-app-1  | 	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92) ~[urlrewritefilter-4.0.4.jar:4.0.4]
docker-dotcms-app-1  | 	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389) ~[urlrewritefilter-4.0.4.jar:4.0.4]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:137) ~[dotcms_null.jar:?]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:88) ~[dotcms_null.jar:?]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:53) ~[dotcms_null.jar:?]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:99) ~[dotcms_null.jar:?]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[dotcms_null.jar:?]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at com.dotcms.filters.NormalizationFilter.doFilter(NormalizationFilter.java:88) ~[dotcms_null.jar:?]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[catalina.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-coyote.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-coyote.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) ~[tomcat-coyote.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1701) ~[tomcat-coyote.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1190) ~[tomcat-coyote.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:633) ~[tomcat-coyote.jar:9.0.60]
docker-dotcms-app-1  | 	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:611) ~[tomcat-coyote.jar:9.0.60]
docker-dotcms-app-1  | 	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127) ~[?:?]
docker-dotcms-app-1  | 	at sun.nio.ch.Invoker$2.run(Invoker.java:219) ~[?:?]
docker-dotcms-app-1  | 	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112) ~[?:?]
docker-dotcms-app-1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
docker-dotcms-app-1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
docker-dotcms-app-1  | 	at java.lang.Thread.run(Thread.java:829) [?:?]
```
Setting this as `Needs work`

**Comment by bryanboza** [comment]
Fixed, now we are printing real data according to the experiment configuration.
