### ISSUE TITLE
NPE in PermissionAjax

### ISSUE THREAD

**Issue by kkleinwi** [dotCMS/core#25099]
### Problem Statement

Attempting to view the Permissions tab for a Category that has no permissions set causes an NPE. This in turn causes the Permissions tab to get stuck with only the roller image displaying.

```
30/05/23 14:17:49:162 UTC]  INFO log.accessLog: Method execution failed:
java.lang.NullPointerException: null
      at com.dotmarketing.business.ajax.PermissionAjax.addPermissionToRoleList(PermissionAjax.java:160) ~[dotcms_23.01.2_999999.jar:?]
      at com.dotmarketing.business.ajax.PermissionAjax.getAssetPermissions(PermissionAjax.java:100) ~[dotcms_23.01.2_999999.jar:?]
      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
      at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
      at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
```

I believe that the root cause of the error in in the "if" expression on line 160. The || operator should be &&.

### Steps to Reproduce

In our environment, clicking the "Reset Permissions" button on a leaf Category triggers this problem.

### Acceptance Criteria

The Permissions tab should work as expected without triggering an NPE

### dotCMS Version

23.01.2

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by kkleinwi** [comment]
Is there any chance we could escalate this? The code change is trivial and this is causing us significant issues.
