### ISSUE TITLE
Unable to Publish (all) of a folder

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#25440]
### Problem Statement

Whenever you click on the option to Publish (all) an error is thrown:

```
WARN action.PublishFolderAction: java.lang.ClassCastException: class com.dotmarketing.portlets.folders.model.Folder cannot be cast to class com.dotmarketing.beans.Inode (com.dotmarketing.portlets.folders.model.Folder and com.dotmarketing.beans.Inode are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @1e692555)
java.lang.ClassCastException: class com.dotmarketing.portlets.folders.model.Folder cannot be cast to class com.dotmarketing.beans.Inode (com.dotmarketing.portlets.folders.model.Folder and com.dotmarketing.beans.Inode are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @1e692555)
	at com.dotmarketing.factories.PublishFactory.getUnpublishedRelatedAssets(PublishFactory.java:525) ~[dotcms_23.01.3_999999.jar:?]
	at com.dotmarketing.factories.PublishFactory.getUnpublishedRelatedAssets(PublishFactory.java:485) ~[dotcms_23.01.3_999999.jar:?]
	at com.dotmarketing.portlets.folders.action.PublishFolderAction._prePublishFolder(PublishFolderAction.java:84) ~[dotcms_23.01.3_999999.jar:?]
	at com.dotmarketing.portlets.folders.action.PublishFolderAction.processAction(PublishFolderAction.java:44) ~[dotcms_23.01.3_999999.jar:?]
	at com.liferay.portal.struts.PortletRequestProcessor.process(PortletRequestProcessor.java:126) ~[dotcms_23.01.3_999999.jar:?]
```

### Steps to Reproduce

1- On the Site Browser Portlet
2- Create a folder
3- Inside the folder create the following:
3.1- File Asset
3.2- Page
3.3- Folder
4- Right click on the folder created in step 2.
5- Publish (All)
6- Get the error

### Acceptance Criteria

Everything in the folder should be published without issues.

### dotCMS Version

23.01+

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/112279

**Comment by erickgonzalez** [comment]
Note to QA and Dev: files inside the subfolder should also be published.

**Comment by erickgonzalez** [comment]
Not reproducible in 22.03 LTS

**Comment by bryanboza** [comment]
Fixed, I'm unable to reproduce on master, but here a new card related this process https://github.com/dotCMS/core/issues/25753
