### ISSUE TITLE
Importing Category lists via CSV - import button is disabled

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#25653]
### Problem Statement

Import button does nothing when clicking on import after selecting a csv file to import categories

<img width="1448" alt="image" src="https://github.com/dotCMS/core/assets/1569167/825a18b8-c76d-4fa9-b8d6-aa1001549783">

### Steps to Reproduce

Go the to categories portlet, create a new parent category, then one child category.  Export the single child category to a csv file... add a few more categories and attempt to import them.

### Acceptance Criteria

Entire list of new categories should be imported and immediately visible and replace or add/edit options should work as expected as well.

### dotCMS Version

Current Master

### Proposed Objective

User Experience

### Proposed Priority

Please Select

**Comment by DeanGonzalez** [comment]
Error generated in the log after clicking the button:
[28/07/23 15:58:59:519 UTC] ERROR servlet.VisitorFilter: Servlet execution threw an exception
javax.servlet.ServletException: Servlet execution threw an exception
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:234) ~[catalina.jar:9.0.60]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.60]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.60]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.60]

**Comment by ian-b-cooper** [comment]
This issue is seen in a customer ticket: https://dotcms.zendesk.com/agent/tickets/113599

**Comment by wezell** [comment]
Also applies to Tags importing and exporting.

**Comment by wezell** [comment]
We are missing this library
```
 compile group: 'com.dotcms.lib', name: 'dot.commons-io', version:'2.0.1_2'
```

**Comment by bryanboza** [comment]
Now it is working, but we still needing some work here. New issue created here: #27783
