### ISSUE TITLE
Unable to archive site with experiments

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25884]
### Parent Issue

When I try to archive a site in master, I am getting this error:

```
[24/08/23 14:15:46:442 UTC]  INFO log.accessLog: Method execution failed: 
java.lang.NullPointerException: parentPermissionable
	at java.util.Objects.requireNonNull(Objects.java:246) ~[?:?]
	at com.dotcms.experiments.model.Experiment$InitShim.getParentPermissionable(Experiment.java:345) ~[dotcms_master_2cdfd50.jar:?]
	at com.dotcms.experiments.model.Experiment.<init>(Experiment.java:111) ~[dotcms_master_2cdfd50.jar:?]
	at com.dotcms.experiments.model.Experiment$Builder.build(Experiment.java:2057) ~[dotcms_master_2cdfd50.jar:?]
	at com.dotcms.experiments.business.ExperimentTransformer.transform(ExperimentTransformer.java:76) ~[dotcms_master_2cdfd50.jar:?]
	at com.dotcms.experiments.business.ExperimentTransformer.<init>(ExperimentTransformer.java:39) ~[dotcms_master_2cdfd50.jar:?]
	at com.dotcms.util.transform.TransformerLocator.createExperimentTransformer(TransformerLocator.java:272) ~[dotcms_master_2cdfd50.jar:?]
	at com.dotcms.experiments.business.ExperimentsFactoryImpl.list(ExperimentsFactoryImpl.java:122) ~[dotcms_master_2cdfd50.jar:?]
	at com.dotcms.experiments.business.ExperimentsAPIImpl.cacheRunningExperiments(ExperimentsAPIImpl.java:1166) ~[dotcms_master_2cdfd50.jar:?]
	at com.dotcms.experiments.business.ExperimentsAPIImpl.getRunningExperiments(ExperimentsAPIImpl.java:1110) ~[dotcms_master_2cdfd50.jar:?]
	at com.dotcms.experiments.business.ExperimentsAPIImpl.getRunningExperimentPerPage(ExperimentsAPIImpl.java:1541) ~[dotcms_master_2cdfd50.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.internalArchive(ESContentletAPIImpl.java:3564) ~[dotcms_master_2cdfd50.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.internalArchive(ESContentletAPIImpl.java:3547) ~[dotcms_master_2cdfd50.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.archive(ESContentletAPIImpl.java:3485) ~[dotcms_master_2cdfd50.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.archive(ESContentletAPIImpl.java:3389) ~[dotcms_master_2cdfd50.jar:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.archive(ContentletAPIInterceptor.java:104) ~[dotcms_master_2cdfd50.jar:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl.archive(HostAPIImpl.java:631) ~[dotcms_master_2cdfd50.jar:?]
	at com.dotmarketing.business.ajax.HostAjax.archiveHost(HostAjax.java:298) ~[dotcms_master_2cdfd50.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
```

### Problem Statement

see above

### Steps to Reproduce

see above

### Acceptance Criteria

Please remove the "Can't Archive a Page %s because it has a Running Experiment. Experiment ID" from the contentlet API on content archive.

### dotCMS Version

master

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA: Archiving site demo in starter working as expected.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_1d55008**, Docker, macOS 13.0, FF v113.0
