### ISSUE TITLE
Unable to copy a contentlet having Site/Folder Field

### ISSUE THREAD

**Issue by Neehakethi** [dotCMS/core#26459]
### Problem Statement

Having a content type with a field Site/Folder(Not Required).
When we try to create a copy of this content, it throws an error 

`Caused by: java.lang.NullPointerException
	at com.dotmarketing.business.DeterministicIdentifierAPIImpl.lambda$deterministicIdSeed$4a664f34$1(DeterministicIdentifierAPIImpl.java:171) ~[dotcms_23.01.7_999999.jar:?]
	at io.vavr.control.Try.of(Try.java:75) ~[vavr-0.10.3.jar:?]
	at com.dotmarketing.business.DeterministicIdentifierAPIImpl.deterministicIdSeed(DeterministicIdentifierAPIImpl.java:169) ~[dotcms_23.01.7_999999.jar:?]
	at com.dotmarketing.business.DeterministicIdentifierAPIImpl.generateDeterministicIdBestEffort(DeterministicIdentifierAPIImpl.java:368) ~[dotcms_23.01.7_999999.jar:?]
	at com.dotmarketing.business.IdentifierAPIImpl.createNew(IdentifierAPIImpl.java:194) ~[dotcms_23.01.7_999999.jar:?]
	at com.dotmarketing.business.IdentifierAPIImpl.createNew(IdentifierAPIImpl.java:138) ~[dotcms_23.01.7_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.addOrUpdateContentletIdentifier(ESContentletAPIImpl.java:5154) ~[dotcms_23.01.7_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.internalCheckin(ESContentletAPIImpl.java:4956) ~[dotcms_23.01.7_999999.jar:?]
	... 22 more`

### Steps to Reproduce

1. Create a content type: Test having a Site/Folder field included  (This is not a required field: Required checkbox is not chosen)

<img width="998" alt="Screenshot 2023-10-18 at 3 45 25 PM" src="https://github.com/dotCMS/core/assets/139247809/354ee618-2ad6-43c1-96d1-b6a88c522add">

2. Create Content Test A for content Type Test (This will have a default value as **System Host / Root Site** assigned to Site/Folder) field 
<img width="1231" alt="Screenshot 2023-10-18 at 2 16 17 PM" src="https://github.com/dotCMS/core/assets/139247809/e479f34d-8ba7-435d-9553-dc51ce331c59">

3. Perform copy action on Test A to create a copy 
<img width="1341" alt="Screenshot 2023-10-18 at 3 47 40 PM" src="https://github.com/dotCMS/core/assets/139247809/4207b454-7322-4b7c-8e06-bd1b0efd2187">

4. This results in an error.
5. When choosing any specific folder under the root (application) for example, the copy function works fine.
<img width="1592" alt="Screenshot 2023-10-18 at 3 47 13 PM" src="https://github.com/dotCMS/core/assets/139247809/0f9e323e-98d8-48d4-9938-6c186fa6cbb8">

Error logs attached from demo : 
[dotcms (24).log](https://github.com/dotCMS/core/files/13033383/dotcms.24.log)

### Acceptance Criteria

Copy of a contentlet should work in case of having a Site/Folder Field included and is optional without throwing any errors 

### dotCMS Version

23.09.7
23.01.7

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/G01N0AU1NUC/p1697650841389619\
https://dotcms.zendesk.com/agent/tickets/113818

**Comment by AndreyDotcms** [comment]
The issue occurred because copying the contentlet overrides properties when the Host/Folder field is labeled as `Host`.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 

Now we are able to copy/duplicate content without problems.

**Comment by waqasakramdot** [comment]
Please note: It can even happen when a Host/folder is also required. However, the rest of the details are correct when saving content into another folder after that content can copy workflow.

Here is a new customer hitting this: https://dotcms.zendesk.com/agent/tickets/114629
