### ISSUE TITLE
dotCLI feedback by J

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#26610]
### Problem Statement

Will do a summary of all issue I have found by using the dotcli

### Steps to Reproduce

Will described on the comments

### Acceptance Criteria

Resolve the issues

### dotCMS Version

master

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by jdotcms** [comment]
1) Issues with user login when rebuild:
When rebuild the app, it seems the token is lost.
The instance seems to be not login and I need to relogin again to perform any task

**Comment by jdotcms** [comment]
2. When rebuild my local, I loss all assets but still having the file assets contentlets in my local and the path
When I tried the files push, it tries to use the metadata of a binary that does not exist and fails

I made this fix with @fabrizzio-dotCMS 

```
diff --git a/dotCMS/src/main/java/com/dotcms/rest/api/v1/asset/WebAssetHelper.java b/dotCMS/src/main/java/com/dotcms/rest/api/v1/asset/WebAssetHelper.java
index 3c52179b94..1a45fec60c 100644
--- a/dotCMS/src/main/java/com/dotcms/rest/api/v1/asset/WebAssetHelper.java
+++ b/dotCMS/src/main/java/com/dotcms/rest/api/v1/asset/WebAssetHelper.java
@@ -266,6 +266,10 @@ public class WebAssetHelper {
      */
     Predicate<Contentlet> nonNullMetadata = c -> {
         try {
+            if (null == Try.of(()->c.getBinary(FileAssetAPI.BINARY_FIELD)).getOrNull()) {
+                return true;
+            }
+
             return null != c.getBinaryMetadata(FileAssetAPI.BINARY_FIELD);
         } catch (DotDataException e) {
             return false;
```

```
13:23:25.047  INFO  asset.WebAssetResource - User [dotcms.org.1] is requesting assets info for path [//api-site/application/modules]
13:23:31.380  WARN  mapper.RuntimeExceptionMapper - null
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
	at java.util.ImmutableCollections$MapN.<init>(ImmutableCollections.java:827) ~[?:?]
	at java.util.Map.of(Map.java:1568) ~[?:?]
	at com.dotcms.rest.api.v1.asset.WebAssetHelper.toAsset(WebAssetHelper.java:314) ~[dotcms_master_eb4e842.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.dotcms.rest.api.v1.asset.WebAssetHelper.toAssets(WebAssetHelper.java:290) ~[dotcms_master_eb4e842.jar:?]
	at com.dotcms.rest.api.v1.asset.WebAssetHelper.getAssetInfo(WebAssetHelper.java:208) ~[dotcms_master_eb4e842.jar:?]
	at com.dotcms.rest.api.v1.asset.WebAssetHelper.getAssetInfo(WebAssetHelper.java:123) ~[dotcms_master_eb4e842.jar:?]
	at com.dotcms.rest.api.v1.asset.WebAssetResource.getAssetsInfo(WebAssetResource.java:69) ~[dotcms_master_eb4e842.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method
```
