### ISSUE TITLE
ContentTypes with relationships is breaking Push 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#26642]
### Problem Statement

pushing any of the following CTs  Blog, BlogCommentor, FaqWidget, BlogComment
is causing an issue updating it on the server side 

```
[ERROR] ❗  Error pushing file [/Users/fabrizzioaraya/super-push-1/content-types/Blog.json] for operation [UPDATE] - [ Status: (400) With error: {
  "message" : "Content-type is not valid (Relationship Cardinality needs to be set)"
} ]
 HTTP 400 Bad Request: The server encountered an error processing the request.
javax.ws.rs.WebApplicationException:  Status: (400) With error: {
  "message" : "Content-type is not valid (Relationship Cardinality needs to be set)"
}
	at com.dotcms.api.provider.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:61)
	at com.dotcms.api.provider.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:20)
	at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:41)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:153)
	at com.sun.proxy.$Proxy74.updateContentTypes(Unknown Source)
	at com.dotcms.api.client.push.contenttype.ContentTypePushHandler.edit(ContentTypePushHandler.java:70)
	at com.dotcms.api.client.push.contenttype.ContentTypePushHandler_Subclass.edit$$superforward1(Unknown Source)
	at com.dotcms.api.client.push.contenttype.ContentTypePushHandler_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:24)
	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.dotcms.api.client.push.contenttype.ContentTypePushHandler_Subclass.edit(Unknown Source)
	at com.dotcms.api.client.push.contenttype.ContentTypePushHandler.edit(ContentTypePushHandler.java:18)
	at com.dotcms.api.client.push.task.ProcessResultTask.compute(ProcessResultTask.java:84)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### Steps to Reproduce

1. set up a dotCMS instance with full starter. 
2. Pull down the all available content-types 
3. Now run Global push or directly run ct push on any of the following ct 
`Blog, BlogCommentor, FaqWidget, BlogComment`

### Acceptance Criteria

The pushed CT should succeed. If we're missing a cardinality it must be specified in the json structure to have a default non-null acceptable value

### dotCMS Version

current master 

### Proposed Objective

Customer Success

### Proposed Priority

Priority 2 - Important

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_b295876_SNAPSHOT**, Docker, macOS 13.0, FF v113.0

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
