### ISSUE TITLE
User login tries to access default host

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#27069]
### User Story

When an user logs in, we try to load the default host, but in case the user doesn't have access to it we log the following:

```
[14/12/23 16:55:38:693 GMT] ERROR business.HostAPIImpl: User 'Erick David [ID: user-66c98e28-cd40-4595-866f-6aa32b45dd9d][email:[edavid@test.com](mailto:edavid@test.com)]' does not have READ permissions on Site 'newDefaultSite'
[14/12/23 16:55:38:694 GMT] WARN exception.ForbiddenException: {"error":"dotcms.api.error.forbidden: User 'Erick David  [ID: user-66c98e28-cd40-4595-866f-6aa32b45dd9d][email:[email:[edavid@test.com](mailto:edavid@test.com)]' does not have READ permissions on Site 'newDefaultSite'"}
com.dotcms.rest.exception.ForbiddenException: HTTP 403 Forbidden
at com.dotcms.rest.api.v1.site.SiteResource.currentSite(SiteResource.java:156) ~[dotcms_23.10.24_lts_8463e7f.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
```

### Acceptance Criteria

Let's suppress this log as a WARN/DEBUG.

Add a fallback to the first available host.

### Proposed Objective

Please Select

### Proposed Priority

Please Select

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/114541

**Comment by dsilvam** [comment]
Passed Internal QA. Tested with the following scenario: 
1. Two hosts: default and demo.dotcms.com (default host)
2. Created a user with permissions only for default. 

When logging in with the user the current host was the one which the user has access to and the following got logged: 
```
10:40:37.715  WARN  login.LoginServiceAPIFactory$LoginServiceImpl - User 'user-9460a01e-8588-4d76-a842-4698769229f9' does not have READ permission to the Default Site. Setting the first available Site 'default' as current one
```

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_d50032a**, Docker, macOS 14.5, FF v126.0.1
