### ISSUE TITLE
CLI: Error creating the symlink when dotCLI is installed via `npm install -g @dotcms/dotcli`

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#27736]
### Problem Statement
An error occurs when attempting to install `dotCLI` using the command `npm install -g @dotcms/dotcli`.

```
(base) ➜  core git:(master) ✗ npm install -g  @dotcms/dotcli
npm ERR! code 1
npm ERR! path /Users/**/.nvm/versions/node/v21.5.0/lib/node_modules/@dotcms/dotcli
npm ERR! command failed
npm ERR! command sh -c node src/postinstall.js install
npm ERR! Installing CLI
npm ERR! Platform: darwin
npm ERR! Architecture: arm64
npm ERR! Binary found for your platform darwin-arm64: bin/dotcms-cli-24.02.20-osx-aarch_64
npm ERR! {
npm ERR!   config: {
npm ERR!     alias: 'dotcli',
npm ERR!     binaryKey: 'dotcms-cli-darwin-arm64',
npm ERR!     binaryPath: 'bin/dotcms-cli-24.02.20-osx-aarch_64',
npm ERR!     extension: ''
npm ERR!   }
npm ERR! }
npm ERR! Creating symlink for the relevant binary for your platform darwin-arm64
npm ERR! Installing cli: /Users/**/.nvm/versions/node/v21.5.0/lib/node_modules/@dotcms/dotcli/bin/dotcms-cli-24.02.20-osx-aarch_64 dotcli
npm ERR! Error while creating symlink: Error: EEXIST: file already exists, symlink '/Users/**/.nvm/versions/node/v21.5.0/lib/node_modules/@dotcms/dotcli/bin/dotcms-cli-24.02.20-osx-aarch_64' -> '/Users/**/.nvm/versions/node/v21.5.0/bin/dotcli'
npm ERR!     at async Object.symlink (node:internal/fs/promises:993:10)
npm ERR!     at async createSymlink (/Users/**/.nvm/versions/node/v21.5.0/lib/node_modules/@dotcms/dotcli/src/postinstall.js:92:13)
npm ERR!     at async Object.installCli [as install] (/Users/**/.nvm/versions/node/v21.5.0/lib/node_modules/@dotcms/dotcli/src/postinstall.js:117:5) {
npm ERR!   errno: -17,
npm ERR!   code: 'EEXIST',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '/Users/**/.nvm/versions/node/v21.5.0/lib/node_modules/@dotcms/dotcli/bin/dotcms-cli-24.02.20-osx-aarch_64',
npm ERR!   dest: '/Users/**/.nvm/versions/node/v21.5.0/bin/dotcli'
npm ERR! }
npm ERR! Error: Failed to create symlink.
npm ERR!     at createSymlink (/Users/**/.nvm/versions/node/v21.5.0/lib/node_modules/@dotcms/dotcli/src/postinstall.js:97:15)
npm ERR!     at async Object.installCli [as install] (/Users/**/.nvm/versions/node/v21.5.0/lib/node_modules/@dotcms/dotcli/src/postinstall.js:117:5)
```

### Steps to Reproduce
1. Run the command `npm install -g @dotcms/dotcli`.

### Acceptance Criteria
- The installation of `dotCLI` using the command `npm install -g @dotcms/dotcli` should complete without errors.

### dotCMS Version
N/A

### Proposed Objective
Quality Assurance

### Proposed Priority
Priority 3 - Average

### External Links
N/A

### Assumptions & Initiation Needs
- This issue assumes that the `npm` package manager and `dotCLI` repository are functioning as expected.
- Initiation requires access to the environment where the installation is being attempted.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
N/A

**Comment by bryanboza** [comment]
Fixed,m unable to reproduce in the last CLI version // master
