### ISSUE TITLE
fix flakey postman tests when no body is sent to workflow fire

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#28108]
Some postman tests are failing but not every time and in the log we can see it is complaining about "Entity is empty". the cause of this is that the endpoint is expecting a body of type FormDataMultiPart and in these cases the postman test is not sending any body.    We still do not know why this does not fail every time but the solution in this case is to make sure the test is passing an empty json object in the body.  

The main test that breaks is "File Asset Metadata" in Content_Resource.postman_collection.json

This has been tested in Postman after starting services with
./mvnw -pl :dotcms-postman pre-integration-test -Dpostman.test.skip=false -Pdebug

and the whole of Content_Resource.postman_collection can be tested locally with
./mvnw -pl :dotcms-postman verify -Dpostman.test.skip=false -Pdebug -Dpostman.collections=Content_Resource.postman_collection

of with just installed as
just test-postman Content_Resource.postman_collection

```
2024-03-28T16:04:19.9821748Z [INFO] ↳ Unpublish Test File
2024-03-28T16:04:22.9996703Z DOTCMS:16:04:22.998  INFO  util.SecurityLogger - class com.dotmarketing.cms.login.factories.LoginFactory : User admin@dotcms.com has sucessfully logged in from IP: 172.17.0.1 -- ip:172.17.0.1,user:Admin User [ID: dotcms.org.1][email:admin@dotcms.com]
2024-03-28T16:04:23.0328755Z DOTCMS:16:04:23.027  WARN  mapper.RuntimeExceptionMapper - Entity is empty.
2024-03-28T16:04:23.0330249Z DOTCMS:javax.ws.rs.BadRequestException: Entity is empty.
2024-03-28T16:04:23.0334125Z DOTCMS:	at org.glassfish.jersey.media.multipart.internal.FormDataParamValueFactoryProvider$ValueFactory.getEntity(FormDataParamValueFactoryProvider.java:136) ~[jersey-media-multipart-2.22.1.jar:?]
2024-03-28T16:04:23.0338233Z DOTCMS:	at org.glassfish.jersey.media.multipart.internal.FormDataParamValueFactoryProvider$FormDataMultiPartFactory.provide(FormDataParamValueFactoryProvider.java:152) ~[jersey-media-multipart-2.22.1.jar:?]
2024-03-28T16:04:23.0342626Z DOTCMS:	at org.glassfish.jersey.media.multipart.internal.FormDataParamValueFactoryProvider$FormDataMultiPartFactory.provide(FormDataParamValueFactoryProvider.java:148) ~[jersey-media-multipart-2.22.1.jar:?]
2024-03-28T16:04:23.0346347Z DOTCMS:	at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.provide(ParamValueFactoryWithSource.java:71) ~[jersey-server-2.22.1.jar:?]
2024-03-28T16:04:23.0349572Z DOTCMS:	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:94) ~[jersey-server-2.22.1.jar:?]
2024-03-28T16:04:23.0352084Z DOTCMS:	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:127) ~[jersey-server-2.22.1.jar:?]
2024-03-28T16:04:23.0356237Z DOTCMS:	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[jersey-server-2.22.1.jar:?]
2024-03-28T16:04:23.0359659Z DOTCMS:	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[jersey-server-2.22.1.jar:?]
2024-03-28T16:04:23.0362418Z DOTCMS:	at org.glassfish.jersey.server.model.ResourceM
```

**Comment by spbolton** [comment]
There are two matching PUT requests for the same path in WorkflowResource one accepts a body of json or javascript and the other accepts multipart/form-data.  It seems when no body is sent it is not determined which of these methods is used and when the multipart/form-data method is picked it throws the error with "Entity is empty" and when the json version is picked it continues ignoring the body. The fix forces the content type of the body to json and prevents the issue. 

    @Path("/actions/default/fire/{systemAction}")
