### ISSUE TITLE
Graphql: Editing PageAssets break Schema Generation

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#28114]
### Problem Statement

Graphql schema generation is too brittle.  If you edit a Page Asset and delete some of the non-required fields, graphql dies and is unable to generate its schema.

```
object type 'Page2024' does not implement interface 'PageBaseType' because field 'seokeywords' is missing
object type 'Page2024' does not implement interface 'PageBaseType' because field 'pagemetadata' is missing
object type 'Page2024' does not implement interface 'PageBaseType' because field 'seodescription' is missing
object type 'htmlpageasset' does not implement interface 'PageBaseType' because field 'seokeywords' is missing
graphql.schema.validation.InvalidSchemaException: invalid schema:
object type 'Page2024' does not implement interface 'PageBaseType' because field 'seokeywords' is missing
object type 'Page2024' does not implement interface 'PageBaseType' because field 'pagemetadata' is missing
object type 'Page2024' does not implement interface 'PageBaseType' because field 'seodescription' is missing
object type 'htmlpageasset' does not implement interface 'PageBaseType' because field 'seokeywords' is missing
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:418) ~[graphql-java-13.0.jar:?]
	at com.dotcms.graphql.business.GraphqlAPIImpl.generateSchema(GraphqlAPIImpl.java:220) ~[classes/:?]
```

### Steps to Reproduce

1. Create a new Page Content Type
2. Delete many of the optional fields - e.g. SEO Description, SEO Keywords, etc. fields
3. Go to the graphql portlet and try to load the schema, you will get a 500 exception.

### Acceptance Criteria

Users should be able to delete all non-required fields and still get a graph schema.

### dotCMS Version

24.03

### Proposed Objective

Reliability

### Proposed Priority

Priority 2 - Important

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk // Docker // FF
