### ISSUE TITLE
Flakey Test: CLI -  com.dotcms.api.ContentTypeAPIIT.Test_Create_Then_Update_Then_Delete_Content_Type

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#28136]
Original Job Run
https://github.com/dotCMS/core/actions/runs/8531760820/attempts/1
Rerun
https://github.com/dotCMS/core/actions/runs/8531760820

Commit with failure
https://github.com/dotCMS/core/commit/fc926d3ee6afe90ca3b4942542fe0ac682d5b2fa

```
Error:  com.dotcms.api.ContentTypeAPIIT.Test_Create_Then_Update_Then_Delete_Content_Type -- Time elapsed: 1.736 s <<< FAILURE!
org.opentest4j.AssertionFailedError: CT was not deleted
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
	at com.dotcms.api.ContentTypeAPIIT.Test_Create_Then_Update_Then_Delete_Content_Type(ContentTypeAPIIT.java:256)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1008)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:827)
	at
```

[2_CLI Tests - JDK 11.txt](https://github.com/dotCMS/core/files/14852532/2_CLI.Tests.-.JDK.11.txt)

**Comment by spbolton** [comment]
2024-04-17T23:18:56. Same error 
[9_Merge Group Test _ CLI Tests - JDK 11.txt](https://github.com/dotCMS/core/files/15019040/9_Merge.Group.Test._.CLI.Tests.-.JDK.11.txt)

**Comment by nollymar** [comment]
Failed again on [here](https://github.com/dotCMS/core/actions/runs/10478780890/job/29025863719)

![Image](https://github.com/user-attachments/assets/f50a9bf9-05ec-420b-b947-6236b778ade5)
