### ISSUE TITLE
Flakey Test CLI: Test_Command_Content_Type_Folder_Push

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#28615]
Found in run 

[4_Merge Group Test _ CLI Tests - JDK 11.txt](https://github.com/dotCMS/core/files/15381284/4_Merge.Group.Test._.CLI.Tests.-.JDK.11.txt)

https://github.com/dotCMS/core/actions/runs/9161073223/job/25185722719

```

2024-05-20T18:37:28.1745012Z 2024-05-20 18:37:28,166 DEBUG [com.dot.api.cli.pul.PullServiceImpl] (executor-thread-22) Fetching Content Types by key [var_1716230247916].
2024-05-20T18:37:28.4259745Z [ERROR] ❗  Error in command [content-type pull] with message: 
2024-05-20T18:37:28.4261487Z 2024-05-20 18:37:28,419 ERROR [com.dot.cli.com.OutputOptionMixin] (main) Error in command [content-type pull] with message: 
2024-05-20T18:37:28.4262651Z   404 
2024-05-20T18:37:28.4263778Z  Not Found: The requested resource was not found or is restricted.: com.dotcms.api.client.pull.exception.PullException: 404
2024-05-20T18:37:28.4265522Z 	at com.dotcms.api.client.util.ErrorHandlingUtilImpl.mapException(ErrorHandlingUtilImpl.java:198)
2024-05-20T18:37:28.4267371Z 	at com.dotcms.api.client.util.ErrorHandlingUtilImpl.mapPullException(ErrorHandlingUtilImpl.java:175)
2024-05-20T18:37:28.4269022Z 	at com.dotcms.api.client.util.ErrorHandlingUtilImpl_ClientProxy.mapPullException(Unknown Source)
2024-05-20T18:37:28.4270376Z 	at com.dotcms.api.client.pull.PullServiceImpl.fetch(PullServiceImpl.java:151)
2024-05-20T18:37:28.4271711Z 	at com.dotcms.api.client.pull.PullServiceImpl.pull(PullServiceImpl.java:48)
2024-05-20T18:37:28.4272960Z 	at com.dotcms.api.client.pull.PullServiceImpl_Subclass.pull$$superforward1(Unknown Source)
2024-05-20T18:37:28.4274342Z 	at com.dotcms.api.client.pull.PullServiceImpl_Subclass$$function$$1.apply(Unknown Source)
2024-05-20T18:37:28.4275767Z 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
2024-05-20T18:37:28.4277267Z 	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:124)
2024-05-20T18:37:28.4279111Z 	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
2024-05-20T18:37:28.4280830Z 	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
2024-05-20T18:37:28.4282148Z 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
2024-05-20T18:37:28.4283521Z 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
2024-05-20T18:37:28.4284893Z 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
2024-05-20T18:37:28.4286144Z 	at com.dotcms.api.client.pull.PullServiceImpl_Subclass.pull(Unknown Source)
2024-05-20T18:37:28.4287371Z 	at com.dotcms.cli.command.contenttype.ContentTypePull.call(ContentTypePull.java:98)
2024-05-20T18:37:28.4288899Z 	at com.dotcms.cli.command.contenttype.ContentTypePull_Subclass.call$$superforward1(Unknown Source)
2024-05-20T18:37:28.4289931Z 	at com.dotcms.cli.command.contenttype.ContentTypePull_Subclass$$function$$4.apply(Unknown Source)
2024-05-20T18:37:28.4290869Z 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
2024-05-20T18:37:28.4291991Z 	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:124)
2024-05-20T18:37:28.4293373Z 	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
2024-05-20T18:37:28.4294406Z 	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
2024-05-20T18:37:28.4295344Z 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
2024-05-20T18:37:28.4296666Z 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
2024-05-20T18:37:28.4297720Z 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
2024-05-20T18:37:28.4298738Z 	at com.dotcms.cli.command.contenttype.ContentTypePull_Subclass.call(Unknown Source)
2024-05-20T18:37:28.4299585Z 	at com.dotcms.cli.command.contenttype.ContentTypePull.call(ContentTypePull.java:24)
2024-05-20T18:37:28.4300263Z 	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
2024-05-20T18:37:28.4300802Z 	at picocli.CommandLine.access$1500(CommandLine.java:148)
2024-05-20T18:37:28.4301525Z 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
2024-05-20T18:37:28.4302263Z 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
2024-05-20T18:37:28.4302787Z 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
2024-05-20T18:37:28.4303401Z 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
2024-05-20T18:37:28.4304033Z 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
2024-05-20T18:37:28.4304693Z 	at com.dotcms.cli.common.DotExecutionStrategy.execute(DotExecutionStrategy.java:87)
2024-05-20T18:37:28.4305638Z 	at picocli.CommandLine.execute(CommandLine.java:2170)
2024-05-20T18:37:28.4306782Z 	at com.dotcms.cli.command.contenttype.ContentTypeCommandIT.Test_Command_Content_Type_Folder_Push(ContentTypeCommandIT.java:941)
2024-05-20T18:37:28.4307849Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-05-20T18:37:28.4308713Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-05-20T18:37:28.4309867Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-05-20T18:37:28.4310674Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2024-05-20T18:37:28.4311414Z 	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:999)
2024-05-20T18:37:28.4312688Z 	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:813)
2024-05-20T18:37:28.4314283Z 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
2024-05-20T18:37:28.4315656Z 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
2024-05-20T18:37:28.4317035Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2024-05-20T18:37:28.4318094Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
2024-05-20T18:37:28.4319153Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
2024-05-20T18:37:28.4320167Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
2024-05-20T18:37:28.4321572Z 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
2024-05-20T18:37:28.4322907Z 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
2024-05-20T18:37:28.4324121Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2024-05-20T18:37:28.4325332Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2024-05-20T18:37:28.4326568Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2024-05-20T18:37:28.4327674Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2024-05-20T18:37:28.4328750Z 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
2024-05-20T18:37:28.4329876Z 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
2024-05-20T18:37:28.4331027Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
2024-05-20T18:37:28.4332140Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2024-05-20T18:37:28.4333238Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
2024-05-20T18:37:28.4334323Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
2024-05-20T18:37:28.4335353Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
2024-05-20T18:37:28.4336621Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
2024-05-20T18:37:28.4337686Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2024-05-20T18:37:28.4338829Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
2024-05-20T18:37:28.4339738Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2024-05-20T18:37:28.4340644Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
2024-05-20T18:37:28.4341700Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2024-05-20T18:37:28.4342725Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
2024-05-20T18:37:28.4343681Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
2024-05-20T18:37:28.4344403Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2024-05-20T18:37:28.4345479Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
2024-05-20T18:37:28.4346812Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
2024-05-20T18:37:28.4347966Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2024-05-20T18:37:28.4349016Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
2024-05-20T18:37:28.4349910Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2024-05-20T18:37:28.4350803Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
2024-05-20T18:37:28.4351846Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2024-05-20T18:37:28.4352930Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
2024-05-20T18:37:28.4353932Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
2024-05-20T18:37:28.4354655Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2024-05-20T18:37:28.4355728Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
2024-05-20T18:37:28.4357097Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
2024-05-20T18:37:28.4358242Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2024-05-20T18:37:28.4359282Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
2024-05-20T18:37:28.4360174Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2024-05-20T18:37:28.4361062Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
2024-05-20T18:37:28.4362354Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2024-05-20T18:37:28.4363391Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
2024-05-20T18:37:28.4364345Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
2024-05-20T18:37:28.4365572Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
2024-05-20T18:37:28.4366921Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2024-05-20T18:37:28.4368062Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
2024-05-20T18:37:28.4369320Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
2024-05-20T18:37:28.4370371Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
2024-05-20T18:37:28.4371491Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
2024-05-20T18:37:28.4372582Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
2024-05-20T18:37:28.4373770Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
2024-05-20T18:37:28.4374905Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
2024-05-20T18:37:28.4375836Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
2024-05-20T18:37:28.4376805Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
2024-05-20T18:37:28.4377737Z 	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
2024-05-20T18:37:28.4378724Z 	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:56)
2024-05-20T18:37:28.4379696Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
2024-05-20T18:37:28.4380761Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
2024-05-20T18:37:28.4381817Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
2024-05-20T18:37:28.4382752Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
2024-05-20T18:37:28.4383569Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2024-05-20T18:37:28.4384371Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
2024-05-20T18:37:28.4385118Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
2024-05-20T18:37:28.4385688Z Caused by: javax.ws.rs.NotFoundException: 404
2024-05-20T18:37:28.4386428Z 	at com.dotcms.api.provider.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:62)
2024-05-20T18:37:28.4387488Z 	at com.dotcms.api.provider.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:21)
2024-05-20T18:37:28.4388617Z 	at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:41)
2024-05-20T18:37:28.4389783Z 	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:155)
2024-05-20T18:37:28.4390546Z 	at com.sun.proxy.$Proxy187.getContentType(Unknown Source)
2024-05-20T18:37:28.4391296Z 	at com.dotcms.api.client.pull.contenttype.ContentTypeFetcher.fetchByKey(ContentTypeFetcher.java:61)
2024-05-20T18:37:28.4392323Z 	at com.dotcms.api.client.pull.contenttype.ContentTypeFetcher_Subclass.fetchByKey$$superforward1(Unknown Source)
2024-05-20T18:37:28.4393323Z 	at com.dotcms.api.client.pull.contenttype.ContentTypeFetcher_Subclass$$function$$1.apply(Unknown Source)
2024-05-20T18:37:28.4394294Z 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
2024-05-20T18:37:28.4395286Z 	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:124)
2024-05-20T18:37:28.4396385Z 	at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
2024-05-20T18:37:28.4397437Z 	at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
2024-05-20T18:37:28.4398226Z 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
2024-05-20T18:37:28.4399090Z 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
2024-05-20T18:37:28.4400044Z 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
2024-05-20T18:37:28.4400934Z 	at com.dotcms.api.client.pull.contenttype.ContentTypeFetcher_Subclass.fetchByKey(Unknown Source)
2024-05-20T18:37:28.4401930Z 	at com.dotcms.api.client.pull.contenttype.ContentTypeFetcher.fetchByKey(ContentTypeFetcher.java:17)
2024-05-20T18:37:28.4402817Z 	at com.dotcms.api.client.pull.PullServiceImpl.lambda$fetch$0(PullServiceImpl.java:109)
2024-05-20T18:37:28.4403683Z 	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
2024-05-20T18:37:28.4404573Z 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
2024-05-20T18:37:28.4405451Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:581)
2024-05-20T18:37:28.4406237Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2024-05-20T18:37:28.4407032Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2024-05-20T18:37:28.4407773Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2024-05-20T18:37:28.4408532Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2024-05-20T18:37:28.4409381Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-05-20T18:37:28.4410016Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2024-05-20T18:37:28.4410308Z 
2024-05-20T18:37:28.4410408Z   404 
2024-05-20T18:37:28.4410836Z  Not Found: The requested resource was not found or is restricted.

```

**Comment by nollymar** [comment]
This test failed again:

```
org.opentest4j.AssertionFailedError: expected: <0> but was: <1>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:527)
	at com.dotcms.cli.command.contenttype.ContentTypeCommandIT.Test_Command_Content_Type_Folder_Push(ContentTypeCommandIT.java:1145)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1013)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:827)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	Suppressed: com.dotcms.api.client.pull.exception.PullException: 404
		at com.dotcms.api.client.util.ErrorHandlingUtilImpl.mapException(ErrorHandlingUtilImpl.java:198)
		at com.dotcms.api.client.util.ErrorHandlingUtilImpl.mapPullException(ErrorHandlingUtilImpl.java:175)
		at com.dotcms.api.client.util.ErrorHandlingUtilImpl_ClientProxy.mapPullException(Unknown Source)
		at com.dotcms.api.client.pull.PullServiceImpl.fetch(PullServiceImpl.java:151)
		at com.dotcms.api.client.pull.PullServiceImpl.pull(PullServiceImpl.java:48)
		at com.dotcms.api.client.pull.PullServiceImpl_Subclass.pull$$superforward(Unknown Source)
		at com.dotcms.api.client.pull.PullServiceImpl_Subclass$$function$$1.apply(Unknown Source)
		at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
		at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
		at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:124)
		at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
		at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
		at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
		at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
		at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
		at com.dotcms.api.client.pull.PullServiceImpl_Subclass.pull(Unknown Source)
		at com.dotcms.cli.command.contenttype.ContentTypePull.call(ContentTypePull.java:97)
		at com.dotcms.cli.command.contenttype.ContentTypePull_Subclass.call$$superforward(Unknown Source)
		at com.dotcms.cli.command.contenttype.ContentTypePull_Subclass$$function$$4.apply(Unknown Source)
		at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
		at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
		at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:124)
		at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
		at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
		at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
		at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
		at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
		at com.dotcms.cli.command.contenttype.ContentTypePull_Subclass.call(Unknown Source)
		at com.dotcms.cli.command.contenttype.ContentTypePull.call(ContentTypePull.java:24)
		at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
		at picocli.CommandLine.access$1500(CommandLine.java:148)
		at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
		at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
		at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
		at com.dotcms.cli.common.DotExecutionStrategy.internalExecute(DotExecutionStrategy.java:183)
		at com.dotcms.cli.common.DotExecutionStrategy.execute(DotExecutionStrategy.java:94)
		at picocli.CommandLine.execute(CommandLine.java:2170)
		at com.dotcms.cli.command.contenttype.ContentTypeCommandIT.Test_Command_Content_Type_Folder_Push(ContentTypeCommandIT.java:1143)
		... 5 more
	Caused by: jakarta.ws.rs.NotFoundException: 404
		at com.dotcms.api.provider.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:62)
		at com.dotcms.api.provider.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:21)
		at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:60)
		at io.quarkus.restclient.runtime.QuarkusProxyInvocationHandler.invoke(QuarkusProxyInvocationHandler.java:172)
		at com.sun.proxy.$Proxy210.getContentType(Unknown Source)
		at com.dotcms.api.client.pull.contenttype.ContentTypeFetcher.fetchByKey(ContentTypeFetcher.java:61)
		at com.dotcms.api.client.pull.contenttype.ContentTypeFetcher_Subclass.fetchByKey$$superforward(Unknown Source)
		at com.dotcms.api.client.pull.contenttype.ContentTypeFetcher_Subclass$$function$$1.apply(Unknown Source)
		at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
		at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
		at io.quarkus.arc.impl.ActivateRequestContextInterceptor.invoke(ActivateRequestContextInterceptor.java:124)
		at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:33)
		at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
		at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
		at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
		at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
		at com.dotcms.api.client.pull.contenttype.ContentTypeFetcher_Subclass.fetchByKey(Unknown Source)
		at com.dotcms.api.client.pull.contenttype.ContentTypeFetcher.fetchByKey(ContentTypeFetcher.java:17)
		at com.dotcms.api.client.pull.PullServiceImpl.lambda$fetch$0(PullServiceImpl.java:109)
		at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
		at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
		at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:587)
		at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
		at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
		at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
		at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:829)
```
