### ISSUE TITLE
dotcli does not install on Windows 10: Installation is not supported for this win32/x64 combination.

### ISSUE THREAD

**Issue by tinynow** [dotCMS/core#28687]
### Problem Statement

Cannot install @dotcms/dotcli either locally or globally. 

### Steps to Reproduce

```
npm ERR! code 1
npm ERR! path D:\repos\dotcms-deploy\node_modules\@dotcms\dotcli
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node src/postinstall.js install
npm ERR! Installing CLI
npm ERR! Platform: win32
npm ERR! Architecture: x64
npm ERR! Error: Installation is not supported for this win32/x64 combination.
npm ERR!     at parsePackageJson (D:\repos\dotcms-deploy\node_modules\@dotcms\dotcli\src\postinstall.js:49:15)
npm ERR!     at Object.installCli [as install] (D:\repos\dotcms-deploy\node_modules\@dotcms\dotcli\src\postinstall.js:127:26)
npm ERR!     at Object.<anonymous> (D:\repos\dotcms-deploy\node_modules\@dotcms\dotcli\src\postinstall.js:165:17)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1376:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1207:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:1023:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
npm ERR!     at node:internal/main/run_main_module:28:49
```
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.19045 Build 19045
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Type	x64-based PC

### Acceptance Criteria

To be able to install the CLI.

### dotCMS Version

24.5.20

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 1 - Show Stopper

**Comment by tinynow** [comment]
Full log
```
0 verbose cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
1 info using npm@10.2.4
2 info using node@v20.11.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\kreo235\AppData\Roaming\nvm\v20.11.0\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\kreo235\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Program Files\nodejs\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:setEnvs Completed in 0ms
15 timing config:load Completed in 8ms
16 timing npm:load:configload Completed in 8ms
17 timing config:load:flatten Completed in 2ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 1ms
20 verbose title npm install @dotcms/dotcli
21 verbose argv "install" "--global" "@dotcms/dotcli"
22 timing npm:load:setTitle Completed in 0ms
23 timing npm:load:display Completed in 1ms
24 verbose logfile logs-max:10 dir:C:\Users\kreo235\AppData\Local\npm-cache\_logs\2024-07-19T15_20_44_534Z-
25 verbose logfile C:\Users\kreo235\AppData\Local\npm-cache\_logs\2024-07-19T15_20_44_534Z-debug-0.log
26 timing npm:load:logFile Completed in 11ms
27 timing npm:load:timers Completed in 0ms
28 timing npm:load:configScope Completed in 0ms
29 timing npm:load Completed in 48ms
30 timing config:load:flatten Completed in 0ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 2 files
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 8ms
35 timing idealTree:userRequests Completed in 3ms
36 silly idealTree buildDeps
37 silly fetch manifest @dotcms/dotcli@*
38 http fetch GET 200 https://registry.npmjs.org/@dotcms%2fdotcli 591ms (cache updated)
39 silly placeDep ROOT @dotcms/dotcli@24.7.12 OK for:  want: *
40 timing idealTree:#root Completed in 599ms
41 timing idealTree:node_modules/@dotcms/dotcli Completed in 0ms
42 timing idealTree:buildDeps Completed in 599ms
43 timing idealTree:fixDepFlags Completed in 1ms
44 timing idealTree Completed in 612ms
45 timing reify:loadTrees Completed in 615ms
46 timing reify:diffTrees Completed in 1ms
47 silly reify moves {}
48 timing reify:retireShallow Completed in 1ms
49 timing reify:createSparse Completed in 2ms
50 timing reify:loadBundles Completed in 0ms
51 silly tarball no local data for @dotcms/dotcli@https://registry.npmjs.org/@dotcms/dotcli/-/dotcli-24.7.12.tgz. Extracting by manifest.
52 http fetch GET 200 https://registry.npmjs.org/@dotcms/dotcli/-/dotcli-24.7.12.tgz 2359ms (cache miss)
53 timing reifyNode:node_modules/@dotcms/dotcli Completed in 2365ms
54 timing reify:unpack Completed in 2365ms
55 timing reify:unretire Completed in 1ms
56 timing build:queue Completed in 8ms
57 info run @dotcms/dotcli@24.7.12 postinstall node_modules/@dotcms/dotcli node src/postinstall.js install
58 info run @dotcms/dotcli@24.7.12 postinstall { code: 1, signal: null }
59 timing reify:rollback:createSparse Completed in 183ms
60 timing reify:rollback:retireShallow Completed in 0ms
61 timing command:install Completed in 3363ms
62 verbose stack Error: command failed
62 verbose stack     at ChildProcess.<anonymous> (C:\Users\kreo235\AppData\Roaming\nvm\v20.11.0\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:53:27)
62 verbose stack     at ChildProcess.emit (node:events:518:28)
62 verbose stack     at maybeClose (node:internal/child_process:1105:16)
62 verbose stack     at Socket.<anonymous> (node:internal/child_process:457:11)
62 verbose stack     at Socket.emit (node:events:518:28)
62 verbose stack     at Pipe.<anonymous> (node:net:337:12)
63 verbose pkgid @dotcms/dotcli@24.7.12
64 verbose cwd D:\repos\front-end-code
65 verbose Windows_NT 10.0.19045
66 verbose node v20.11.0
67 verbose npm  v10.2.4
68 error code 1
69 error path C:\Users\kreo235\AppData\Roaming\nvm\v20.11.0\node_modules\@dotcms\dotcli
70 error command failed
71 error command C:\WINDOWS\system32\cmd.exe /d /s /c node src/postinstall.js install
72 error Installing CLI
72 error Platform: win32
72 error Architecture: x64
73 error Error: Installation is not supported for this win32/x64 combination.
73 error     at parsePackageJson (C:\Users\kreo235\AppData\Roaming\nvm\v20.11.0\node_modules\@dotcms\dotcli\src\postinstall.js:49:15)
73 error     at Object.installCli [as install] (C:\Users\kreo235\AppData\Roaming\nvm\v20.11.0\node_modules\@dotcms\dotcli\src\postinstall.js:127:26)
73 error     at Object.<anonymous> (C:\Users\kreo235\AppData\Roaming\nvm\v20.11.0\node_modules\@dotcms\dotcli\src\postinstall.js:165:17)
73 error     at Module._compile (node:internal/modules/cjs/loader:1376:14)
73 error     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
73 error     at Module.load (node:internal/modules/cjs/loader:1207:32)
73 error     at Module._load (node:internal/modules/cjs/loader:1023:12)
73 error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
73 error     at node:internal/main/run_main_module:28:49
74 verbose exit 1
75 timing npm Completed in 6995ms
76 verbose unfinished npm timer reify 1721402448163
77 verbose unfinished npm timer reify:build 1721402451153
78 verbose unfinished npm timer build 1721402451153
79 verbose unfinished npm timer build:deps 1721402451153
80 verbose unfinished npm timer build:run:postinstall 1721402451161
81 verbose unfinished npm timer build:run:postinstall:node_modules/@dotcms/dotcli 1721402451161
82 verbose code 1
83 error A complete log of this run can be found in: C:\Users\kreo235\AppData\Local\npm-cache\_logs\2024-07-19T15_20_44_534Z-debug-0.log
```

**Comment by prestonso** [comment]
Closing due to no response.

**Comment by RudyRG** [comment]
When installing dotCLI in WSL Ubuntu on Windows 11, i got the same error "Installation is not supported for this win32/x64 combination".
That was because WSL was using the Windows version of npm that i had already installed within Windows.
The solution is to also install the Linux version of npm within WSL itself:

sudo apt-get update
sudo apt install npm

**Comment by wezell** [comment]
Thanks you for this Rudy - we will update the docs
