### ISSUE TITLE
dotAsset is Breaking FileViewStrategy

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#28857]
### User Story

In our content API v1 we are using the new Transformers which is great.  The issue is that our API responses for binaries are all different based on what type of content you have and what field type you are using.  This is part of what makes using images in dotCMS - all the responses vary.

This does not need to be the case as in the end everything is just a binary field.

### The Bug
The bug is this - if you create 2 related content types, parent + child and the child has a File or Image field that has a dotAsset in it, and you request the parent content via the v1 version of the content api with `?depth=1`, it will throw this error:

```
{
  "message": "Contentlet : 3fb168f8-34ce-4f9c-875f-4a2a9b13c9c3 is not a FileAsset"
}
```

Likewise, In the block editor, if you add a link a piece of content that has a relationship to another piece of content that has a file field that has a dotAsset selected, you will see this error and your content will not render or be displayed. 

 

### Acceptance Criteria

Fix the bug and make sure our API responses for dotAssets, FileAssets, Binaries and file and image fields are the same

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

```
Caused by: com.dotmarketing.business.DotStateException: Contentlet : 3fb168f8-34ce-4f9c-875f-4a2a9b13c9c3 is not a FileAsset
	at com.dotmarketing.portlets.fileassets.business.FileAssetAPIImpl.fromContentlet(FileAssetAPIImpl.java:256) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.transform.strategy.FileViewStrategy.transform(FileViewStrategy.java:106) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.transform.strategy.FileViewStrategy.transform(FileViewStrategy.java:79) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.transform.strategy.AbstractTransformStrategy.apply(AbstractTransformStrategy.java:91) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.transform.DotContentletTransformerImpl.lambda$transform$3(DotContentletTransformerImpl.java:105) ~[classes/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:558) ~[?:?]
	at com.dotmarketing.portlets.contentlet.transform.DotContentletTransformerImpl.transform(DotContentletTransformerImpl.java:107) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.transform.DotContentletTransformerImpl.lambda$hydrate$7(DotContentletTransformerImpl.java:121) ~[classes/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.dotmarketing.portlets.contentlet.transform.DotContentletTransformerImpl.hydrate(DotContentletTransformerImpl.java:123) ~[classes/:?]
	at com.dotcms.rest.ContentResource.contentletToJSON(ContentResource.java:1408) ~[classes/:?]
	at com.dotcms.rest.ContentResource.addRelatedContentToJsonArray(ContentResource.java:1296) ~[classes/:?]
	at com.dotcms.rest.ContentResource.addRelationshipsToJSON(ContentResource.java:1211) ~[classes/:?]
	at com.dotcms.rendering.velocity.viewtools.content.util.ContentUtils.addRelationships(ContentUtils.java:814) ~[classes/:?]
```

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker: [`dotcms/trunk_ a66d047`]

### Video


https://github.com/dotCMS/core/assets/72418962/b0b32ad8-0fac-4072-bec4-d7484c293956

**Comment by bryanboza** [comment]
Fxed, tested on latest trunk // Docker // Postman
