### ISSUE TITLE
fileAsset Required Error while importing FileAsset through CSV

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#29079]
### Problem Statement

When importing FileAssets through a CSV file, even though the fileAsset column has a value of full HTTPS URL/ID path/ResourceLink, it shows a fileAsset is required error in the logs.

```
ARN business.ESContentletAPIImpl: Field [fileAsset] is required
[02/07/24 09:05:17:040 GMT] ERROR util.ImportUtil: An error occurred when importing line # 2: Line #2 contains errors
required: fileAsset

com.dotmarketing.exception.DotRuntimeException: Line #2 contains errors
required: fileAsset

	at com.dotmarketing.util.ImportUtil.importLine(ImportUtil.java:1392) ~[classes/:?]
	at com.dotmarketing.util.ImportUtil.importFile(ImportUtil.java:267) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction._generatePreview(ImportContentletsAction.java:483) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.action.ImportContentletsAction.processAction(ImportContentletsAction.java:185) ~[classes/:?]
	at com.liferay.portal.struts.PortletRequestProcessor.process(PortletRequestProcessor.java:126) ~[classes/:?]
	at com.liferay.portlet.StrutsPortlet.processAction(StrutsPortlet.java:120) ~[classes/:?]
	at com.liferay.portlet.ConcretePortletWrapper.processAction(ConcretePortletWrapper.java:97) ~[classes/:?]
	at com.liferay.portal.action.LayoutAction._processPortletRequest(LayoutAction.java:194) ~[classes/:?]
	at com.liferay.portal.action.LayoutAction._processActionRequest(LayoutAction.java:206) ~[classes/:?]
	at com.liferay.portal.action.LayoutAction.execute(LayoutAction.java:82) ~[classes/:?]
	at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:431) ~[dot.struts-1.2.10_1.jar:?]
	at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:237) ~[dot.struts-1.2.10_1.jar:?]
	at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:149) ~[classes/:?]
	at com.dotcms.repackage.org.apache.struts.action.ActionServlet.process(ActionServlet.java:1202) ~[dot.struts-1.2.10_1.jar:?]
	at com.dotcms.repackage.org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:430) ~[dot.struts-1.2.10_1.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555) ~[servlet-api.jar:4.0.FR]
	at com.liferay.portal.servlet.MainServlet.callParentService(MainServlet.java:249) ~[classes/:?]
	at com.liferay.portal.servlet.MainServlet.service(MainServlet.java:449) ~[classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[servlet-api.jar:4.0.FR]```
```

### Steps to Reproduce

1. Try to import the following CSV
[CSV_BinaryField.csv](https://github.com/user-attachments/files/16196714/CSV_BinaryField.csv)

2. Get the error
<img width="696" alt="Screenshot 2024-07-12 at 8 50 00 AM" src="https://github.com/user-attachments/assets/1e3f76f4-8970-43fc-a763-bce04ca2fc89">

### Acceptance Criteria

- The import feature should recognize the URL passed.
- Should work to create or update content.
- Test with a CSV with several entries; some of the entries make them invalid URLs.

### dotCMS Version

24.4.* - 24.6.*

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116985

**Comment by erickgonzalez** [comment]
Working as it should. No errors were found when previewing/importing, and the content was created successfully.

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_0f67690**, Docker, macOS 14.5, FF v126.0.1

Error is still showing up on the latest master 

<img width="494" alt="Screenshot 2024-07-18 at 1 41 22 PM" src="https://github.com/user-attachments/assets/c409608a-1683-440f-8e19-6f2917375acb">

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_9bee608**, Docker, macOS 14.5, FF v126.0.1
