### ISSUE TITLE
Allow single object POSTs to /api/v1/workflow/actions/default/fire/

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#29178]
### User Story

As a developer I was trying to use a payload like this except with a POST 
https://auth.dotcms.com/docs/latest/save-content-using-workflows#examples-related-content

and it was failing with a inscrutable error

```
18:09:19.240  WARN  mapper.JsonMappingExceptionMapper - Cannot deserialize value of type `java.util.ArrayList<java.util.Map<java.lang.String,java.lang.Object>>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 15]
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<java.util.Map<java.lang.String,java.lang.Object>>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 15]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1767) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1541) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1488) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:396) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:252) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:158) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:293) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217) ~[jackson-databind-2.16.1.jar:2.16.1]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342) ~[jackson-databind-2.16.1.jar:2.16.1]
```

There is no reason why the PUT operates differently than the POST

### Acceptance Criteria

The POST endpoint should be able to take either an array or an object.

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

See slack convo here:
https://dotcms.slack.com/archives/C028Z3R2D/p1720563107378899

**Comment by jdotcms** [comment]
starting the review

**Comment by jdotcms** [comment]
It works smooth, you can now send a single object or a collection
Nice changes, would need doc @jdcmsd 

Steps to test
1) Create a content type
<img width="1260" alt="Screenshot 2024-07-17 at 12 39 50 PM" src="https://github.com/user-attachments/assets/1d3e0cd1-fbf8-4fee-9e53-2edc6f827f58">


2) Send POST as single object and collection (including [])
```
curl --location 'https://local.dotcms.site:8443/api/v1/workflow/actions/default/fire/PUBLISH' \
--header 'Content-Type: application/json' \
--header 'Authorization: ••••••' \
--data-raw '{
   "contentlet": {
      "contentType":"Employee",
      "languageId":1,
      "firstName":"Dean",
      "lastName":"Gonzalez",
      "gender":"male",
      "jobTitle":"General Manager",
      "email":"dean@dotcms.com",
      "location":"+identifier:0c69da5c-2a05-452f-9305-3be6926d5079"
   }
}'
```

And 

```
curl --location 'https://local.dotcms.site:8443/api/v1/workflow/actions/default/fire/PUBLISH' \
--header 'Content-Type: application/json' \
--header 'Authorization: ••••••' \
--data-raw '{
   "contentlet": [{
      "contentType":"Employee",
      "languageId":1,
      "firstName":"Jonathan",
      "lastName":"Sanchez",
      "gender":"male",
      "jobTitle":"General Manager",
      "email":"j@dotcms.com",
      "location":"+identifier:0c69da5c-2a05-452f-9305-3be6926d5079"
   }]
}'
```

See the content search

<img width="1268" alt="Screenshot 2024-07-17 at 12 40 05 PM" src="https://github.com/user-attachments/assets/dbfbbf75-ce66-4520-9f2f-042dc1d2949e">

Be Happy
