### ISSUE TITLE
Creating a Page with no active license brings an exceptions 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#29531]
### Problem Statement

I tried to create a brand new page without knowing I didn't have a license installed, and then I got a blank page properties dialog with a message like: 
```
An unexpected system error occurred.
com.dotcms.repackage.javax.portlet.PortletException
```

### Steps to Reproduce

Remove the installed license if any
Go to:  Site Manager - Pages 
Then hit Create new Page The following screen shows up: 

![Screenshot 2024-08-12 at 10 43 08 AM](https://github.com/user-attachments/assets/187b7f4b-003b-419b-be8e-f274ec12e09b)

accompanied by the following stacktrace. 

ug 12, 2024 4:26:03 PM org.apache.catalina.core.ApplicationDispatcher invoke
SEVERE: Servlet.service() for servlet [jsp] threw exception
com.dotmarketing.exception.InvalidLicenseException: Apps requires of an enterprise level license.
	at com.dotcms.security.apps.AppsAPIImpl.getSecrets(AppsAPIImpl.java:185)
	at com.dotcms.ai.app.ConfigService.lambda$config$82dd47a0$1(ConfigService.java:34)
	at io.vavr.control.Try.of(Try.java:75)
	at com.dotcms.ai.app.ConfigService.config(ConfigService.java:34)
	at com.dotcms.ai.viewtool.AIViewTool.config(AIViewTool.java:121)
	at com.dotcms.ai.viewtool.AIViewTool.init(AIViewTool.java:37)
	at org.apache.velocity.tools.view.ViewToolInfo.getInstance(ViewToolInfo.java:192)
	at org.apache.velocity.tools.view.servlet.ServletToolboxManager.getToolbox(ServletToolboxManager.java:397)
	at org.apache.velocity.tools.view.XMLToolboxManager.getToolboxContext(XMLToolboxManager.java:175)
	at com.dotcms.rendering.velocity.util.VelocityUtil.getWebContext(VelocityUtil.java:350)
	at com.dotcms.rendering.velocity.util.VelocityUtil.getWebContext(VelocityUtil.java:243)
	at org.apache.jsp.html.portlet.ext.contentlet.edit_005fcontentlet_jsp._jspService(edit_005fcontentlet_jsp.java:1464) 

This was done on a fresh install with an empty strater 

### Acceptance Criteria

if  creating pages is an enterprise feature we should get better error message 

### dotCMS Version

current trunk 

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by john-thomas-dotcms** [comment]
@fabrizzio-dotCMS this was a while ago, and we haven't heard it reported by anyone else.  Do you know if it's still happening?

**Comment by wezell** [comment]
no longer an issue with BSL
