### ISSUE TITLE
Flakey Test CLI: ContentTypeAPIIT.Test_Create_Then_Update_Action_Mappings

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#29654]
```
2024-08-20T03:40:58.9804314Z [ERROR] Tests run: 15, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 18.63 s <<< FAILURE! -- in com.dotcms.api.ContentTypeAPIIT
2024-08-20T03:40:58.9806378Z [ERROR] com.dotcms.api.ContentTypeAPIIT.Test_Create_Then_Update_Action_Mappings -- Time elapsed: 3.470 s <<< FAILURE!
2024-08-20T03:40:58.9807819Z org.opentest4j.AssertionFailedError: expected: <Modified 2!> but was: <Modified!>
2024-08-20T03:40:58.9809192Z 	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
2024-08-20T03:40:58.9811027Z 	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
2024-08-20T03:40:58.9812549Z 	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
2024-08-20T03:40:58.9813832Z 	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
2024-08-20T03:40:58.9815130Z 	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
2024-08-20T03:40:58.9816360Z 	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
2024-08-20T03:40:58.9817822Z 	at com.dotcms.api.ContentTypeAPIIT.Test_Create_Then_Update_Action_Mappings(ContentTypeAPIIT.java:379)
2024-08-20T03:40:58.9819174Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2024-08-20T03:40:58.9820555Z 	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1013)
2024-08-20T03:40:58.9822300Z 	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:827)
2024-08-20T03:40:58.9823725Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2024-08-20T03:40:58.9824812Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2024-08-20T03:40:58.9825459Z
```
Workflow run Nightly: https://github.com/dotCMS/core/actions/runs/10464730879

Log: 

[5_Nightly Test _ CLI Tests.txt](https://github.com/user-attachments/files/16673902/5_Nightly.Test._.CLI.Tests.txt)

**Comment by nollymar** [comment]
Failed again 

```
com.dotcms.api.ContentTypeAPIIT ► Test_Create_Then_Update_Action_Mappings
Failed test found in:
  /tmp/build-reports-test/build-reports-test-CLI Tests/tools/dotcms-cli/api-data-model/target/failsafe-reports/TEST-com.dotcms.api.ContentTypeAPIIT.xml
Error:
  org.opentest4j.AssertionFailedError: expected: <Modified 2!> but was: <Modified!>
org.opentest4j.AssertionFailedError: expected: <Modified 2!> but was: <Modified!>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
	at com.dotcms.api.ContentTypeAPIIT.Test_Create_Then_Update_Action_Mappings(ContentTypeAPIIT.java:379)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1013)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:827)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
```

**Comment by nollymar** [comment]
New failure: https://github.com/dotCMS/core/actions/runs/10483356366/job/29037719787

**Comment by spbolton** [comment]
Repeated twice in one day

https://github.com/dotCMS/core/actions/runs/10492169004

https://github.com/dotCMS/core/actions/runs/10493377923
