### ISSUE TITLE
Spike: Determine approach to get rid of Telemetry DB and use the analytics infra 

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#30088]
### User Story

We want to use the same analytics infra  that we are already using for Experiment and Content Analytics to Telemetry

### Acceptance Criteria

- 

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyDOTCMS** [comment]
In this Spike I did the follow:

- Send Event with the Telemetry format to Jitsu to be storage in Clickhouse, the body of the reuquest was like this:
```

{
  "utc_time": "2024-03-21 10:29:59.8",
  "event_type": "METRIC_SNAPSHOT",
  "url": "Anything_3",
  "clientName": "newell",
  "clientEnv": "dev2301",
  "clientVersion": "1",
  "clientCategory": "CLIENT",
  "schemaVersion": "221018",
  "insertDate": "2024-09-18 08:00:00.100000 +00:00",
  "snapshot":  [see example of this object here](https://gist.github.com/freddyDOTCMS/b5fdb5efe868b1fd8477cb9e9c826c6e)
}
```

- In Clickhouse the follow new fields was added to the events ClickHouse table:

client_category
client_env
client_name
client_version
snapshot
schema_version
insert_date // it is realy the utc_time field that we already have in CH

We sent the url field because it looks like is mandatory is it is not sent then Jitsu reponse with a 200 but it does not save the Event in CH

- Export data from Telemetry PROD DataBase to CH DataBase, for it I used the follow [here
](https://gist.github.com/freddyDOTCMS/73504ff7257e8bfb7c7a0012ec3cced5)

I exported successfully a little more than 11k registers , in this point one throw the follow Exception

```
java.time.format.DateTimeParseException: Text '2024-02-01 12:17:47.72' could not be parsed, unparsed text found at index 21
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2049)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
	at java.base/java.time.LocalDateTime.parse(LocalDateTime.java:492)
	at com.dotcms.DatabaseToJson.run(DatabaseToJson.java:62)
- retrieve this data from CH
```

When A Exception is throw the Code used stop all the process so after this Exception it does not continue with the others registers.

- Create a New DateModel and showed the data exported in CubeJS, for this we used this DataModel [here](https://gist.github.com/freddyDOTCMS/e21f9e2140fc770ada2b27fe2e1eec96
- ) set in the same Schema that we are already using.

Outcome:

We are going to create a least 2 o 3 new issues:

- First Issue: Used the Analytics infra to storage the Telemetry data.
- Second Issue: Export the Data from Telemetry PROD to CH Database.
- Third Issue: Create the new DataModel to support Telemetry data from CubeJS

Also we are going to need a SQL Script to add the new columns that we need in the Events CH Table, exactly how it script is going to be executed depende of this #29878
