### ISSUE TITLE
Dirty Content kills cache, breaks content queries

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#30437]
Third time we have seen this on different environments.

1. Kevin was unable to load a list of partners on the headless server - https://github.com/dotCMS/core/issues/30609
https://dotcms.slack.com/archives/C077D1U7ZHB/p1729533201422469
2. John Thomas was unable to save content on the authoring server: - Captured here https://github.com/dotCMS/core/issues/30468
https://dotcms.slack.com/archives/C058GCQ7T39/p1729810977873979 
3. Site map was not generating on headless server
https://dotcms.slack.com/archives/C077D1U7ZHB/p1730121574996369 - https://github.com/dotCMS/core/issues/30609

Was:  Storyblock failing to load relationships

### Problem Statement

I've seen ~~two~~ three issues on dotcms sites where content is failing to load because of this issue.  The issue is resolved with a cache flush but the fact is that some content is getting dirty/corrupted somewhere.  The first time I saw it I wrote it off, but something is amiss for sure.  There is no log or debugging to know which contentlet has failed to load but in the first case, I saw the following in the logger - this message was repeated whenever the partner page failed to load.

```
com.fasterxml.jackson.core.exc.StreamConstraintsException: Document nesting depth (1001) exceeds the maximum allowed (1000, from StreamReadConstraints.getMaxNestingDepth()`)
....
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4905) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3848) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3816) ~[?:?]
	at com.dotcms.rendering.velocity.viewtools.content.util.ContentUtils.addRelationships(ContentUtils.java:816) ~[?:?]
	at com.dotcms.rendering.velocity.viewtools.content.util.ContentUtils.addRelationships(ContentUtils.java:787) ~[?:?]
	at com.dotcms.contenttype.business.StoryBlockAPIImpl.addContentletRelationships(StoryBlockAPIImpl.java:370) ~[?:?]
	at com.dotcms.contenttype.business.StoryBlockAPIImpl.refreshBlockEditorDataMap(StoryBlockAPIImpl.java:345) ~[?:?]
	at com.dotcms.contenttype.business.StoryBlockAPIImpl.refreshStoryBlockMap(StoryBlockAPIImpl.java:157) ~[?:?]
	at com.dotcms.contenttype.business.StoryBlockAPIImpl.isRefreshed(StoryBlockAPIImpl.java:125) ~[?:?]
	at com.dotcms.contenttype.business.StoryBlockAPIImpl.refreshStoryBlockValueReferences(StoryBlockAPIImpl.java:101) ~[?:?]
	at com.dotcms.contenttype.business.StoryBlockAPIImpl.lambda$refreshReferences$2(StoryBlockAPIImpl.java:71) ~[?:?]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
```

### Steps to Reproduce

not sure

### Acceptance Criteria

should have better logging at least

### dotCMS Version

24.10.x

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Second issue from the three reported is being handled on this ticket https://github.com/dotCMS/core/issues/30468

**Comment by spbolton** [comment]
- Create a new type containing a story block field and a Relationship field
- Create items A, B, and C
- In the relationship field relate B->A, C->B, A->C.
- In each of the story block fields add the other 2 items directly.
- Trace and view the value of jsonWithRelationships.toString() in ContentUtils.addRelationships.

A short cut to generating the result of jsonWithRelationships is to call the content api directly for the id of A, B or C and specify depth=2 e.g. http://localhost:58190/api/v1/content/c1492b19-e1d1-44d2-9afd-a7ff49c4dad8?depth=2
Increasing the number of items used  could reach 1000 depth, but I am not sure what the limiting factor is at the moment that prevents this from creating an infinite loop.   just know the document gets very large with these few items and on my vm it runs out of memory before I hit the 1000 limit

**Comment by yolabingo** [comment]
Cloud customer ticket - block cache issues https://dotcms.freshdesk.com/a/tickets/28353

**Comment by jcastro-dotcms** [comment]
Official fix is being addressed in the following ticket:

* #30609
