### ISSUE TITLE
Remove calls to ElasticReadOnlyCommand and disable EsReadOnlyMonitorJob 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#30468]
### Problem Statement

Both the job and the command had their purpose when the dotCMS setup included an embedded ES and the disks would fill up. Now that dotCMS uses a managed ES, these command and job are not needed and in fact they are failing on our servers because of lacking of permissions to get the cluster settings. 

```
[22/10/24 17:00:00:392 GMT] ERROR core.JobRunShell: Job dotcms_jobs.EsReadOnlyMonitorJob threw an unhandled Exception: 
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=security_exception, reason=no permissions for [cluster:monitor/term] and User [name=corpsites-es, backend_roles=[], requestedTenant=null]]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:187) ~[?:?]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1911) ~[?:?]
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1888) ~[?:?]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1645) ~[?:?]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1602) ~[?:?]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1572) ~[?:?]
	at org.elasticsearch.client.ClusterClient.getSettings(ClusterClient.java:98) ~[?:?]
	at com.dotcms.content.elasticsearch.business.ElasticsearchUtil.getClusterSettings(ElasticsearchUtil.java:158) ~[?:?]
	at com.dotcms.content.elasticsearch.business.ElasticsearchUtil.getClusterUpdateInterval(ElasticsearchUtil.java:136) ~[?:?]
	at com.dotcms.content.elasticsearch.business.ElasticReadOnlyCommandImpl.loadTimeToWaitAfterWriteModeSet(ElasticReadOnlyCommandImpl.java:118) ~[?:?]
	at com.dotcms.content.elasticsearch.business.ElasticReadOnlyCommandImpl.executeCheck(ElasticReadOnlyCommandImpl.java:87) ~[?:?]
	at com.dotmarketing.quartz.job.EsReadOnlyMonitorJob.execute(EsReadOnlyMonitorJob.java:20) ~[?:?]
```

### Steps to Reproduce

Reproducible from different actions: 
* When the job runs every five minutes 
* When checkin in content 

### Acceptance Criteria

The error doesn't happen again upon any action on the CMS, in particular when saving content. 
The EsReadOnlyMonitorJob does not run and it's not present in the list of system jobs from the maintenance tab. 

### dotCMS Version

`trunk_cad5532`

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
* Docker image: `trunk_7408571`

The code using the `ElasticReadOnlyCommand` class has been removed. If there's no easy way for you to generate an `ES read only` status in your local, you check the following:

* Go to the `Roles & Tools` portlet, and add the `Job Scheduler` portlet.
* This is the data table **BEFORE** the fix form this ticket -- notice the presence of the `EsReadOnlyMonitorJob` class:

<img width="1382" alt="before" src="https://github.com/user-attachments/assets/227a9f9f-768a-4221-ad8e-877da3d863e1">

* And this is the data table **AFTER** the fix:

<img width="1349" alt="after" src="https://github.com/user-attachments/assets/071d9be8-2ba7-4c9a-b9d3-6cf0fab271e5">

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_0fe6d13**, Docker, macOS 14.5, FF v126.0.1

**Comment by dsilvam** [comment]
Passed IQA: Feedback on both local docker instance and the headless dotcms.com

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_0dfb0a3**, Docker, macOS 14.5, FF v126.0.1
