### ISSUE TITLE
TimedCacheProvider syncs on gets

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#30528]
### Problem Statement

We use the TimedCacheProvider all over in code, where cache performance is critical.  There should be no reason to sync on the `TimedCacheProvider.get()` method as this causes unneeded slowdowns and blockings....

### Steps to Reproduce

```
CPU time: 3,467.6 milliseconds
"url:GET//testing.io/api/content/limit/0/depth/3/language/1/query/+contentType:ClTagUrl%20+deleted:false%20+working:true%20+languageId:1%20+ClTagUrl.type:testing.com%20/orderby/ClTagUrl.key | lang:1 | ip:52.71.43.114 | Admin:false | start:10-30-2024 08:54:59 UTC" #364
   java.lang.Thread.State: BLOCKED
        at com.dotmarketing.business.cache.provider.timedcache.TimedCacheProvider.get(TimedCacheProvider.java:99)
        - waiting to lock com.dotmarketing.business.cache.provider.timedcache.TimedCacheProvider@50fb120d
        at com.dotcms.enterprise.cache.provider.CacheProviderAPIImpl.get(CacheProviderAPIImpl.java:409)
        at com.dotmarketing.business.ChainableCacheAdministratorImpl.get(ChainableCacheAdministratorImpl.java:273)
        at com.dotmarketing.business.DotCacheAdministrator.getNoThrow(DotCacheAdministrator.java:72)
        at com.dotmarketing.business.CommitListenerCacheWrapper.getNoThrow(CommitListenerCacheWrapper.java:88)
        at com.dotmarketing.business.PermissionCacheImpl.lambda$doesUserHavePermission$1(PermissionCacheImpl.java:113)
        at com.dotmarketing.business.PermissionCacheImpl$$Lambda$2672/0x00000008013f6440.apply()
        at java.util.Optional.map(Optional.java:265)
        at com.dotmarketing.business.PermissionCacheImpl.doesUserHavePermission(PermissionCacheImpl.java:113)
        at com.dotmarketing.business.PermissionBitAPIImpl.doesUserHavePermission(PermissionBitAPIImpl.java:312)
        at com.dotmarketing.business.PermissionBitAPIImpl.doesUserHavePermission(PermissionBitAPIImpl.java:277)
        at com.dotmarketing.business.PermissionBitAPIImpl.doesUserHavePermission(PermissionBitAPIImpl.java:745)
        at com.dotmarketing.business.PermissionBitAPIImpl.doesUserHavePermission(PermissionBitAPIImpl.java:737)
        at com.dotcms.contenttype.business.ContentTypeAPIImpl.find(ContentTypeAPIImpl.java:374)
        at com.dotmarketing.business.RelationshipAPIImpl.getRelationshipFromField(RelationshipAPIImpl.java:411)
        at com.dotcms.rest.ContentResource.addRelationshipsToJSON(ContentResource.java:1202)
        at com.dotcms.rest.ContentResource.addRelatedContentToJsonArray(ContentResource.java:1322)
        at com.dotcms.rest.ContentResource.addRelationshipsToJSON(ContentResource.java:1222)
```

### Acceptance Criteria

Do not have blocking `cache.get` calls under load.

### dotCMS Version

23.10

### Proposed Objective

Application Performance

### Proposed Priority

Priority 1 - Show Stopper

**Comment by jcastro-dotcms** [comment]
This code issue was found in customer environments under heavy load, and there's no effective way for QA to verify it in a local controlled instance. This ticket can be marked as `Done`.
