### ISSUE TITLE
Can not save content with binary fields

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#30893]
### Problem Statement

I can not save pieces of content containing a binary field 

### Steps to Reproduce

Create a Content-type with let's say : 
Title Field and 
Binary Filed

Now, create an instance of the content type 
fill in a text in the text filed and upload an image on the binary field hit save
You'll see a dialog pops up like:
With a message like :  Error: Cannot invoke "com.dotmarketing.beans.Host.getIdentifier()" because "host" is null
![Screenshot 2024-12-09 at 11 03 48 AM](https://github.com/user-attachments/assets/279efc72-cc2b-40c2-817f-0ca97995f4a0)

the following stack trace can be seen in the logs 

```
16:51:14.333  INFO  workflow.OpenAIGenerateImageRunner - Running OpenAI Generate Image Content for : my-Content
16:51:14.340  ERROR workflow.OpenAIGenerateImageRunner - Error: Cannot invoke "com.dotmarketing.beans.Host.getIdentifier()" because "host" is null
java.lang.NullPointerException: Cannot invoke "com.dotmarketing.beans.Host.getIdentifier()" because "host" is null
	at com.dotcms.ai.util.VelocityContextFactory.getMockContext(VelocityContextFactory.java:33) ~[?:?]
	at com.dotcms.ai.workflow.OpenAIGenerateImageRunner.run(OpenAIGenerateImageRunner.java:106) ~[?:?]
	at com.dotcms.ai.workflow.OpenAIGenerateImageActionlet.executeAction(OpenAIGenerateImageActionlet.java:42) ~[?:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireWorkflowPostCheckin(WorkflowAPIImpl.java:2446) ~[?:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.lambda$fireContentWorkflow$73(WorkflowAPIImpl.java:3403) ~[?:?]
	at com.dotcms.util.ThreadContextUtil.wrapVoidNoReindex(ThreadContextUtil.java:85) ~[?:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireContentWorkflow(WorkflowAPIImpl.java:3403) ~[?:?]
	at com.dotmarketing.portlets.contentlet.business.web.ContentletWebAPIImpl.saveWebAsset(ContentletWebAPIImpl.java:539) ~[?:?]
	at com.dotmarketing.portlets.contentlet.business.web.ContentletWebAPIImpl.saveContent(ContentletWebAPIImpl.java:162) ~[?:?]
	at com.dotmarketing.portlets.contentlet.ajax.ContentletAjax.saveContent(ContentletAjax.java:1987) ~[?:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule$1.doFilter(CreatorModule.java:229) ~[?:?]
	at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule.executeMethod(CreatorModule.java:241) ~[?:?]
	at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:379) ~[?:?]
	at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:332) ~[?:?]
	at com.dotcms.repackage.org.directwebremoting.dwrp.BaseCallHandler.handle(BaseCallHandler.java:104) ~[?:?]
	at com.dotcms.repackage.org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:120) ~[?:?]
	at com.dotcms.repackage.org.directwebremoting.servlet.DwrServlet.doPost(DwrServlet.java:141) ~[?:?]
```

### Acceptance Criteria

You should be able to save content at all times when the fields have been provided with the expected values

### dotCMS Version

current main 

### Proposed Objective

Customer Success

### Proposed Priority

Priority 1 - Show Stopper

**Comment by victoralfaro-dotcms** [comment]
Tested using `dotcms/dotcms:trunk_d67b5fd`

Content Type
![image](https://github.com/user-attachments/assets/a114ab73-dc07-43d0-9f28-cc643603087d)

Content
![image](https://github.com/user-attachments/assets/10864532-da16-46f4-9de3-a61a17c053ad)
