### ISSUE TITLE
Content Edit: Add the ability to lock and unlock content

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#30900]
### User Story

As a content editor, I must be able to lock and unlock content, so I can perform workflow actions which require the content to be locked (such as save).

The current content edit screen allows users to lock and unlock content in 2 different ways:
* Via workflow actions that contain the 'Lock content' and 'Unlock content` subactions.
* Via "default" lock and unlock actions, which show as buttons above all other workflow action buttons, regardless of whether or not any lock/unlock workflow actions are available.

The new content edit screen already allows lock and unlock via Workflow actions.  We need to give users the same ability to perform lock and unlock when no lock/unlock actions exist in the workflow.

To do this, we need to add a control to the content edit screen to allow the user to lock and unlock content.

### Acceptance Criteria

1. A lock/unlock control is visible in the content edit screen.
2. The lock/unlock control is enabled when both of the following are true:
    * The current user has edit rights on the current contentlet.
    * The current user has access to any workflow action in the current workflow step which includes any save actionlet.
3. The lock/unlock control is disabled when the current user does not have edit rights on the current contentlet.
4. The lock/unlock control is disabled when the current user does not have access to any workflow action in the current step that includes a save actionlet.
5. When the user locks or unlocks the content using the control, the change takes effect immediately.
    * The user does NOT need to execute a workflow action for the lock or unlock to take effect.
6. When content is locked, the content edit window is closed, and the content is re-opened, it remains locked.
7. When content is unlocked, the content edit window is closed, and the content is re-opened, it remains unlocked.
8. If the content is not locked, and the user attempts to perform a workflow action from the content edit screen which performs a save or other actionlet that modifies the content:
    * If no other user has a lock on the contentlet, the action succeeds without error or notice.
    * If another user already has a lock on the contentlet, the user attempting the workflow action receives a popup with an error.

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

**Comment by jdotcms** [comment]
Working on the BE part

**Comment by jdotcms** [comment]
In other to test this functionality you can
1) use curl to test the lock/unlock new endpoints
```
curl --location --request PUT 'http://localhost:8080/api/v1/content/_lock/08cab7944c8c173c5e9fdf2a574bfffb' \
--header 'Authorization: ••••••' 
```
```
curl --location --request PUT 'http://localhost:8080/api/v1/content/_unlock/08cab7944c8c173c5e9fdf2a574bfffb' \
--header 'Authorization: ••••••' 
```

2) Use the forze unlock
Now on workflow if you add an unlock subaction, there is a new checkbox called forze unlock, this allows even to a non admin user, if the checkbox is on, to fire the actionlet.

a) got to workflow and create a unlock content action
b) add the unlock
c) create a limited user
d) play with the forze checkbox to see how is rendered the action for the limited user, even if it hasnt lock permissions

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: FAILED ❌
* Docker image: `trunk_f0dd21b`

Trying to hit this REST endpoint:
```curl
curl --location --request PUT 'http://localhost:8080/api/v1/content/_lock/{CONTENT-ID}'
```
Is generating the following error:
```
dotcms-1      | 15:27:48.125  WARN  mapper.RuntimeExceptionMapper - HTTP 404 Not Found
dotcms-1      | javax.ws.rs.NotFoundException: HTTP 404 Not Found
dotcms-1      | 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:250) ~[?:?]
dotcms-1      | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[?:?]
dotcms-1      | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[?:?]
dotcms-1      | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[?:?]
dotcms-1      | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[?:?]
dotcms-1      | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[?:?]
dotcms-1      | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[?:?]
dotcms-1      | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) ~[?:?]
dotcms-1      | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679) ~[?:?]
dotcms-1      | 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392) ~[?:?]
dotcms-1      | 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[?:?]
dotcms-1      | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365) ~[?:?]
dotcms-1      | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318) ~[?:?]
dotcms-1      | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[?:?]
...
...
...
```

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED ✅
* Docker image: `trunk_4841a88`

The new REST Endpoints allow you to lock and unlock content, as described in [this comment from Jonathan](https://github.com/dotCMS/core/issues/30900#issuecomment-2578233012). Additionally, creating a Workflow Action that has the Unlock action with the "Force Unlock" checked, allows a limited user to unlock content that they didn't lock originally.
