### ISSUE TITLE
Turn of maven coverage flag in ci build as it is causing exceptions and data is not used currently

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#30917]
When we were trying to work with code coverage we added a maven profile to add the configuration to handle the bytecode manipulation required.   The data returned does not work correctly due to our own bytecode manipulation with ByteBuddy and we need to do refactoring before we can properly handle code coverage.  In the meantime we are getting errors in the logs due to this like the following.    To cleanup the logs, prevent confusion when we are not using the coverage data we should remove the flag

The following can be seen in the e2e testing logs where -Pcoverage is being used. 

```

DOTCMS]14:14:51.524  INFO  impl.DefaultConverterManager - Probably not an issue: com/dotcms/repackage/com.dotcms.repackage.jsx3.xml.CdfDocument is not available so the jsx3doc converter will not load. This is only an problem if you wanted to use it.
[DOTCMS]java.lang.instrument.IllegalClassFormatException: Error while instrumenting org/apache/jsp/html/portlet/ext/contentlet/edit_005fcontentlet_jsp with JaCoCo 0.8.11.202310140853/f33756c.
[DOTCMS]	at org.jacoco.agent.rt.internal_4742761.CoverageTransformer.transform(CoverageTransformer.java:94)
[DOTCMS]	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
[DOTCMS]	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
[DOTCMS]	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:610)
[DOTCMS]	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[DOTCMS]	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
[DOTCMS]	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[DOTCMS]	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
[DOTCMS]	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
[DOTCMS]	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
[DOTCMS]	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
[DOTCMS]	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
[DOTCMS]	at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:129)
[DOTCMS]	at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:58)
```

**Comment by sfreudenthaler** [comment]
not sure what to qa on this beyond what's already been running?  Maybe we can move to done?
