### ISSUE TITLE
Token Invalid in CubeJS Server after token renew

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#31019]
### Problem Statement

When the token expires and is renewed, the Cube.js server returns an 'Invalid Token' error when you attempt to execute a query.

### Steps to Reproduce

- Start dotCMS and Analytics Infrastructure and set the DOT_ANALYTICS_ACCESSTOKEN_TTL to 2000, also don't forget set the DOT_ANALYTICS_IDP_URL to 'http://localhost:61111/realms/dotcms/protocol/openid-connect/token' or  'http://host.docker.internal:61111/realms/dotcms/protocol/openid-connect/token'  if you are using docker
- Set the Analytics App with the follow values:

```
clientId: 	analytics-customer-customer1
Secret:	 testsecret
Analytics Config URL: 	http://host.docker.internal:8088/c/customer1/cluster1/keys
Analytics Write URL use: 	http://host.docker.internal:8081/api/v1/event
Analytics Read URL use:	 http://host.docker.internal:4001/
```

Use localhost as domain if you are not using docker

- Execute the follow request to get CA data

POST
url: {dotcms server}/api/v1/analytics/content/_query
body:

```
{
    "query": {
        "measures": ["request.count"]
    }
}
```

You are going to got a 200 HTT COde and the result of this query

- Wait 5 minutes and hit the Enpoint again

You are going to got 500 Http error and the follow message

```
{
    "message": "CubeJS Server is not available"
}
```

If you check the Cubejs Server console you see the follow error

```

cube                | Internal Server Error: 475d3097-f563-4494-8d92-6ca3d567397f-span-1 (6ms)
cube                | --
cube                | {
cube                |   "measures": [
cube                |     "request.count"
cube                |   ],
cube                |   "offset": 0
cube                | }
cube                | --
cube                | {} 
cube                | Error: No valid token
cube                |     at ApiGateway.queryRewrite (/cube/conf/cube.js:17:19)
cube                |     at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1133:38
cube                |     at Array.map (<anonymous>)
cube                |     at ApiGateway.getNormalizedQueries (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1130:15)
cube                |     at ApiGateway.load (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1595:20)
cube                |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
cube                |     at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:247:7

```

### Acceptance Criteria

After the token expired it must be renew automatically and you should be able to execute any query in the CubeJS Server

### dotCMS Version

latest

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED ✅
* Docker image: `trunk_27a6ddf`

We can run CubeJS queries without issues now. The token is now getting renewed as expected.
