### ISSUE TITLE
Problems restoring website after fixing asset inconsistencies

### ISSUE THREAD

**Issue by aforest85** [dotCMS/core#5813]
Hi,

In a bit of trouble, Within CMS Maintenance.. I did a 'Fix Asset Inconsistencies' today which deleted nearly all of the HTML files for our site.

This meant the front end was not accessible and the logs said "ERROR filters.URLMapFilter: No valid detail page for structure 'Latest'. Looking for detail page " . 

At this point we could still access the backend.

We did a backup of Data & Assets yesterday so I have tried to restore this by renaming the zip file starter.zip and placing in the DotCMS folder, 

Also created a new empty DB called temp and pointed ROOT.XML to it - like it says here http://dotcms.com/docs/latest/BackupAndRestore

After restarting the DotCMS service we now just get the text '500' in the browser rather than 404 errors.

Now dotcms.log looks like this 

"[19/06/14 12:01:52:435 BST] ERROR business.ESContentFactoryImpl: Unable to find Structure or Structure Velocity Variable Name from passed in structureInode Query : +structureInode: +working:true +host.isdefault:true 
[19/06/14 12:01:52:436 BST]  WARN web.HostWebAPIImpl: Content Index is fouled up, need to try db: null
[19/06/14 12:01:52:438 BST] ERROR business.HostAPIImpl: 
java.lang.NullPointerException
    at com.dotmarketing.portlets.contentlet.business.HostAPIImpl.createDefaultHost(HostAPIImpl.java:671)
    at com.dotmarketing.portlets.contentlet.business.HostAPIImpl.findDefaultHost(HostAPIImpl.java:100)
    at com.dotmarketing.portlets.contentlet.business.HostAPIImpl.findByName(HostAPIImpl.java:217)
    at com.dotmarketing.portlets.contentlet.business.HostAPIImpl.resolveHostName(HostAPIImpl.java:138)
    at com.dotmarketing.business.web.HostWebAPIImpl.getCurrentHost(HostWebAPIImpl.java:65)
    at org.apache.jsp.portal._500_jsp._jspService(_500_jsp.java:70)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:646)
    at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:438)
    at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:374)
    at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:302)
    at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:415)
    at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:342)
    at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:286)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:555)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:852)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
    at java.lang.Thread.run(Thread.java:662)"

Any advise would be greatly appreciated.

Thanks,

Keith.

**Comment by yuvraj11** [comment]
Facing the same issue, Were you able to resolve it?

**Comment by jtesser** [comment]
this is an old issue that should not be happening in the current version
