### ISSUE TITLE
Cluster tries to init autowire before sitelic is created on upgrade

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#6970]
During an upgrade from 2.5.6 to 3.0.1, the following error is thrown before the Task03042AddLicenseRepoModel SQL upgrade task that creates the table has been run:

2015-01-14 17:14:32,523 ERROR com.dotcms.enterprise.cluster.ClusterFactory - Error trying to wire node to the Cluster
com.dotmarketing.exception.DotDataException: ERROR: relation "sitelic" does not exist
  Position: 22
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:234)
	at com.dotmarketing.common.db.DotConnect.loadObjectResults(DotConnect.java:859)
	at com.dotcms.enterprise.license.a.b(SourceFile:143)
	at com.dotcms.enterprise.license.a.c(SourceFile:147)
	at com.dotcms.enterprise.license.LicenseManager.isLicenseOnRepo(SourceFile:65)
	at com.dotcms.enterprise.LicenseUtil.setUpLicenseRepo(SourceFile:195)
	at com.dotcms.enterprise.cluster.ClusterFactory.addNodeToCluster(SourceFile:290)
	at com.dotcms.enterprise.cluster.ClusterFactory.addNodeToCluster(SourceFile:197)
	at com.dotcms.enterprise.cluster.ClusterFactory.initialize(SourceFile:111)
	at com.dotmarketing.startup.runalways.Task00009ClusterInitialize.executeUpgrade(Task00009ClusterInitialize.java:17)
	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:214)
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:116)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1284)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1197)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1087)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5210)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5493)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1247)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1898)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "sitelic" does not exist
  Position: 22
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:273)
	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:574)
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:486)
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:232)
	... 27 more

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-16 // H2 // FF
