### ISSUE TITLE
Data exeption WARN pushing pages to a new folder in the receiver side

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7067]
Now you can create and push pages , but when you try to push a page in to a new folder that does not exist on the receiver side, the system is showing an stack trace in the log with a WARN: 
```
[23/01/15 11:23:03:515 CST]  WARN business.HTMLPageAssetAPIImpl: Unable to convert contentlet to page asset com.dotmarketing.portlets.contentlet.model.Contentlet@40692fe3[map={stInode=2d1850e4-0373-4d50-8899-ae61ae0d604f, seokeywords=, owner=dotcms.org.2795, lastReview=2015-01-23 11:22:48.443, redirecturl=, modUser=dotcms.org.2795, identifier=3254976c-f096-4fb3-a2c0-d4b9d38fdb88, showOnMenu=, template=9396ac6a-d32c-4539-966e-c776e7562cfb, httpsreq=, cachettl=15, _use_mod_date=2015-01-23 11:22:48.447, url=test-limited, __disable_workflow__=true, _dont_validate_me=true, sortOrder=0, friendlyname=test limited, modDate=2015-01-23 11:22:48.447, host=48190c8c-42c4-46af-8d1a-0cd5db894797, languageId=1, disabledWYSIWYG=[], title=test limited, seodescription=, pagemetadata=, inode=39226c3b-1ea4-47e7-8203-e97afb411ca1, folder=bcbba9c6-ded0-4f4c-b1d0-10744f73f2a2},lowIndexPriority=false]
com.dotmarketing.exception.DotDataException
	at com.dotmarketing.portlets.folders.business.FolderFactoryImpl.findFolderByPath(FolderFactoryImpl.java:234)
	at com.dotmarketing.portlets.folders.business.FolderAPIImpl.findFolderByPath(FolderAPIImpl.java:73)
	at com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPIImpl.fromContentlet(HTMLPageAssetAPIImpl.java:154)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:384)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:161)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(SourceFile:94)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(SourceFile:84)
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:162)
	at com.dotcms.rest.PublishThread.run(PublishThread.java:41)
	at java.lang.Thread.run(Thread.java:745)
```

Tested on nightly build 2015-01-22 // H2 // FF

**Comment by bryanboza** [comment]
FYI: The push is working fine, but this WARN does not looks fine

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-27 // H2 // FF
