### ISSUE TITLE
XSS detector does not give enough information to fix

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7075]
When I run a spider on the starter site, I am getting this all over the logs:

```
15-01-26 09:03:11,636 WARN  IntrusionDetector - [SECURITY FAILURE Anonymous:null@unknown -> /dotcms/IntrusionDetector] Invalid input: context=URLContext, type(HTTPParameterValue)=^[\p{L}\p{N}.\-/+=_ !$*?@\#,]{0,1000}$, input=Quick Picks & Lists
com.dotcms.repackage.org.owasp.esapi.errors.ValidationException: URLContext: Invalid input. Please conform to regex ^[\p{L}\p{N}.\-/+=_ !$*?@\#,]{0,1000}$ with a maximum length of 19
    at com.dotcms.repackage.org.owasp.esapi.reference.validation.StringValidationRule.checkWhitelist(StringValidationRule.java:144)
    at com.dotcms.repackage.org.owasp.esapi.reference.validation.StringValidationRule.checkWhitelist(StringValidationRule.java:160)
    at com.dotcms.repackage.org.owasp.esapi.reference.validation.StringValidationRule.getValid(StringValidationRule.java:284)
    at com.dotcms.repackage.org.owasp.esapi.reference.DefaultValidator.getValidInput(DefaultValidator.java:214)
    at com.dotcms.repackage.org.owasp.esapi.reference.DefaultValidator.isValidInput(DefaultValidator.java:152)
    at com.dotcms.repackage.org.owasp.esapi.reference.DefaultValidator.isValidInput(DefaultValidator.java:143)
    at com.liferay.util.Xss.URLHasXSS(Xss.java:184)
    at com.dotmarketing.viewtools.RequestWrapper.getParameter(RequestWrapper.java:199)
    at com.dotmarketing.viewtools.RequestWrapper.getParameter(RequestWrapper.java:198)
```

The error, while verbose, does not provide enough information for the "error" to be traced down and  fixed.  We should at least spit out the page (and/or referer)  the error is found on.

**Comment by jtesser** [comment]
For sure.  I am thinking we need to add this in a few places. But a catch in the com.dotmarketing.viewtools.RequestWrapper.getParameter would be a start. Not sure we have a thread local yet to deal in the Xss class
