### ISSUE TITLE
Unable to push html pages versions in different languages 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7107]
Here we have two interesting cases... 

1- If you create the a new page in a different language and try to push, the system is pushing the page without problems.... That's fine, but...

2- If you create a new page in english, then go to page properties and here you create a new page version in a different language, when you try to push, the system have an error and the push fail 
![2015-01-27_1155](https://cloud.githubusercontent.com/assets/2641437/5923756/6fa9b71e-a61b-11e4-99fc-5b26aafe35df.png)

Here the complete log: 
```[27/01/15 11:37:02:178 CST] ERROR business.PublisherAPIImpl: Error Publishing Bundle: Can't find contentlet: a79284ae-7c2d-4d4b-ac20-e6b840af0aed lang:2 live:true
com.dotcms.publishing.DotPublishingException: Can't find contentlet: a79284ae-7c2d-4d4b-ac20-e6b840af0aed lang:2 live:true
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:273)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(SourceFile:94)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(SourceFile:84)
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:162)
	at com.dotcms.rest.PublishThread.run(PublishThread.java:41)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.dotmarketing.portlets.contentlet.business.DotContentletStateException: Can't find contentlet: a79284ae-7c2d-4d4b-ac20-e6b840af0aed lang:2 live:true
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.findContentletByIdentifier(ESContentletAPIImpl.java:405)
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.findContentletByIdentifier(ContentletAPIInterceptor.java:750)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:332)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:135)
	... 5 more
Caused by: com.dotmarketing.exception.DotHibernateException: Error loading object from Hibernate Session 
	at com.dotmarketing.db.HibernateUtil.load(HibernateUtil.java:261)
	at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.find(ESContentFactoryImpl.java:753)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.find(ESContentletAPIImpl.java:350)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.findContentletByIdentifier(ESContentletAPIImpl.java:397)
	... 8 more
Caused by: java.lang.NullPointerException: null is not a valid identifier
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.load(SessionImpl.java:1929)
	at com.dotmarketing.db.HibernateUtil.load(HibernateUtil.java:242)
	... 11 more
[27/01/15 11:37:02:182 CST] ERROR lang.String: Error Publishing: com.dotcms.publishing.DotPublishingException: Can't find contentlet: a79284ae-7c2d-4d4b-ac20-e6b840af0aed lang:2 live:true```

Tested on nightly build 2015-01-27 // MySQL // FF

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-27 // Postgres // FF.... Nice fix

**Comment by shayngr** [comment]
added to test rail http://qa.dotcms.com/index.php?/cases/view/52831
