### ISSUE TITLE
Error trying to push unpublished html pages 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7135]
When you create a new html page and just save it...  Not publish, and you try to push to a remote server the system is having an error and you  can't push this page... 

The same situation when you was pushed any page, then unpublished that on sender, and try to push this page again... I tried with the force push and have the same error...  

Here the log:
```
[28/01/15 16:28:00:017 CST]  WARN impl.SessionImpl: finalizing unclosed session with closed connection
[28/01/15 16:28:00:100 CST] ERROR publishing.PublisherAPIImpl: Index: 0, Size: 0
com.dotcms.publishing.DotBundleException: Index: 0, Size: 0
	at com.dotcms.enterprise.publishing.remote.bundler.DependencyBundler.generate(SourceFile:65)
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:58)
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:17)
	at com.dotcms.publisher.business.PublisherQueueJob.execute(PublisherQueueJob.java:134)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.dotcms.publisher.util.DependencyManager.setHTMLPagesDependencies(DependencyManager.java:566)
	at com.dotcms.publisher.util.DependencyManager.setDependencies(DependencyManager.java:263)
	at com.dotcms.enterprise.publishing.remote.bundler.DependencyBundler.generate(SourceFile:62)
	... 5 more
[28/01/15 16:28:00:100 CST] ERROR business.PublisherQueueJob: Unable to publish Bundle: Index: 0, Size: 0
com.dotcms.publishing.DotPublishingException: Index: 0, Size: 0
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:86)
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:17)
	at com.dotcms.publisher.business.PublisherQueueJob.execute(PublisherQueueJob.java:134)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549)
Caused by: com.dotcms.publishing.DotBundleException: Index: 0, Size: 0
	at com.dotcms.enterprise.publishing.remote.bundler.DependencyBundler.generate(SourceFile:65)
	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:58)
	... 4 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.dotcms.publisher.util.DependencyManager.setHTMLPagesDependencies(DependencyManager.java:566)
	at com.dotcms.publisher.util.DependencyManager.setDependencies(DependencyManager.java:263)
	at com.dotcms.enterprise.publishing.remote.bundler.DependencyBundler.generate(SourceFile:62)
	... 5 more
```
Tested on nightly build 2015-01-27 // Postgres // FF

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-04 // H2 // FF

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/55735
