### ISSUE TITLE
URLMapFilter.java code thread safety

### ISSUE THREAD

**Issue by tbomer** [dotCMS/core#7185]
The doFilter method can be entered by any request thread.  Line 153:

			Collections.sort(patternsCache, new Comparator<PatternCache>()

Does a sort on the patternsCache which is an ArrayList.  If another thread enters the synchronized method buildCacheObjects, it is possible to get a ConcurrentModificationException from the ArrayList.  A fix that is working for us is to change the patternsCache to a sorted set (keep the collection sorted by default on adds):
instead of ArrayList and sorting in the doFilter:
line 64:	private Set<PatternCache> patternsCache = new ConcurrentSkipListSet<PatternCache>(new Comparator<PatternCache>() {
		public int compare(PatternCache o1, PatternCache o2) {
			String regex1 = o1.getRegEx();
			String regex2 = o2.getRegEx();
			if (!regex1.endsWith("/")) {
				regex1 += "/";
			}
			if (!regex2.endsWith("/")) {
				regex2 += "/";
			}

			int regExLength1 = getSlashCount(regex1);
			int regExLength2 = getSlashCount(regex2);
			if (regExLength1 < regExLength2) {
				return 1;
			} else if (regExLength1 > regExLength2) {
				return -1;
			} else {
				return 0;
			}
		}
	});

Then remove the Collections.sort method on line 153 mentioned above and it becomes thread safe.

**Comment by tbomer** [comment]
This is the original exception:

SEVERE: Servlet.service() for servlet proxy threw exception
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
at java.util.ArrayList$Itr.next(ArrayList.java:791)
at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:182)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:162)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at com.bancvue.dotcms.filters.HeaderFilter.doFilter(HeaderFilter.java:29)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at com.bancvue.dotcms.AuthFilter.doFilter(AuthFilter.java:91)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at com.bancvue.metrics.MetricsFilter.doFilter(MetricsFilter.java:39)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:615)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602)
at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
at java.lang.Thread.run(Thread.java:722)

**Comment by tbomer** [comment]
line numbers may be off slightly as we are working the 2.5.6 branch

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7212

**Comment by bryanboza** [comment]
Unable to test... Proceed to remove the needs QA label....
