### ISSUE TITLE
"Unknown error" running SASS compiler on Windows

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7236]
See https://github.com/dotCMS/core/issues/6855

original issue still remains

**Comment by joseorsini** [comment]
Also related to Support Ticket: https://my.dotcms.com/tickets/detail.dot?id=be13887e-e2f6-43a2-b545-9708bac94ff9

Client is running 3.3.1 on a Solaris 10 machine, and according to the following articles 

http://stackoverflow.com/questions/12433270/jruby-gem-installation-error-or-any-gem-error-while-executing-gem-errno
http://stackoverflow.com/questions/10843587/rails-3-2-using-jruby-on-solaris
http://jruby.org/2012/08/07/jruby-1-7-0-preview2.html 

Our JRuby version does not work on Solaris environments. Despite JRuby 1.7.0 Preview 2 states that the problem reported on JRuby-6496 Jira task has been solved, there are documented cases of JRuby still not working for Solaris Environments. 

Stacktrace:

```
[16/08/16 13:38:49:803 PDT] ERROR csspreproc.CSSPreProcessServlet: Exception while serving compiled css file
java.lang.Exception: java.lang.RuntimeException: org.jruby.embed.EvalFailedException: (Errno::ENOENT) /opt/dotcms/cms_data/dotcms_3.5/tmp_upload/css_compile_space/5d5dec5f-d5b7-4e88-8e5b-fc20679def4f/www.xxxxxxx.com/application/themes/xxxxx/src/scss
	at com.dotcms.csspreproc.CSSPreProcessServlet.doGet(CSSPreProcessServlet.java:144) [dotcms_3.5_g14af2ce.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618) [servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:417) [dotcms_3.5_g14af2ce.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61) [dotcms_3.5_g14af2ce.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:307) [dotcms_3.5_g14af2ce.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:174) [dotcms_3.5_g14af2ce.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_3.5_g14af2ce.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) [dotcms_3.5_g14af2ce.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146) [dotcms_3.5_g14af2ce.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.RuntimeException: org.jruby.embed.EvalFailedException: (Errno::ENOENT) /opt/dotcms/cms_data/dotcms_3.5/tmp_upload/css_compile_space/5d5dec5f-d5b7-4e88-8e5b-fc20679def4f/www.equinix.com/application/themes/THM_equinix/src/scss
	at com.dotcms.enterprise.csspreproc.c.compile(SourceFile:83) ~[ee-gaf7f4f0.jar:?]
	at com.dotcms.enterprise.csspreproc.SassCompiler.compile(SourceFile:19) ~[ee-gaf7f4f0.jar:?]
	at com.dotcms.csspreproc.CSSPreProcessServlet.doGet(CSSPreProcessServlet.java:140) ~[dotcms_3.5_g14af2ce.jar:?]
	... 48 more
Caused by: org.jruby.embed.EvalFailedException: (Errno::ENOENT) /opt/dotcms/cms_data/dotcms_3.5/tmp_upload/css_compile_space/5d5dec5f-d5b7-4e88-8e5b-fc20679def4f/www.xxxxxxx.com/application/themes/xxxxx/src/scss
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:133) ~[jruby-complete-1.7.19.jar:?]
	at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1340) ~[jruby-complete-1.7.19.jar:?]
	at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1333) ~[jruby-complete-1.7.19.jar:?]
	at com.dotcms.enterprise.csspreproc.c.compile(SourceFile:70) ~[ee-gaf7f4f0.jar:?]
	at com.dotcms.enterprise.csspreproc.SassCompiler.compile(SourceFile:19) ~[ee-gaf7f4f0.jar:?]
	at com.dotcms.csspreproc.CSSPreProcessServlet.doGet(CSSPreProcessServlet.java:140) ~[dotcms_3.5_g14af2ce.jar:?]
	... 48 more
Caused by: org.jruby.exceptions.RaiseException: (Errno::ENOENT) /opt/dotcms/cms_data/dotcms_3.5/tmp_upload/css_compile_space/5d5dec5f-d5b7-4e88-8e5b-fc20679def4f/www.xxxxxxx.com/application/themes/xxxxx/src/scss
	at org.jruby.RubyDir.chdir(org/jruby/RubyDir.java:342) ~[jruby-complete-1.7.19.jar:?]
	at RUBY.(root)(<script>:7) ~[?:?]
	at com.dotcms.enterprise.csspreproc.c.compile(SourceFile:70) ~[ee-gaf7f4f0.jar:?]
	at com.dotcms.enterprise.csspreproc.SassCompiler.compile(SourceFile:19) ~[ee-gaf7f4f0.jar:?]
```

**Comment by chrismccracken** [comment]
Per the JRuby changelog (http://jruby.org/news), there were quite a few Solaris and Windows bugfixes in the 1.7.20 and 1.7.22 updates (we have 1.7.19). It would be worth trying newer versions of that.

**Comment by joseorsini** [comment]
Using 1.7.25 on dotCMS 3.5 + Java 8 triggers this error message when we try to compile a .scss file. It happens on Windows Server 2012 and Mac OSX El Capitan.

```
[17/08/16 10:26:50:678 EDT] ERROR csspreproc.CSSPreProcessServlet: Error compiling demo.dotcms.com:/about-us/header.css
java.lang.RuntimeException: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- compass
       	at com.dotcms.enterprise.csspreproc.c.compile(SourceFile:83) ~[ee-gaf7f4f0.jar:?]
       	at com.dotcms.enterprise.csspreproc.SassCompiler.compile(SourceFile:19) ~[ee-gaf7f4f0.jar:?]
       	at com.dotcms.csspreproc.CSSPreProcessServlet.doGet(CSSPreProcessServlet.java:140) [dotcms_3.5_g14af2ce.jar:?]
       	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618) [servlet-api.jar:?]
       	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:244) [dotcms_3.5_g14af2ce.jar:?]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61) [dotcms_3.5_g14af2ce.jar:?]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:307) [dotcms_3.5_g14af2ce.jar:?]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:174) [dotcms_3.5_g14af2ce.jar:?]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_3.5_g14af2ce.jar:?]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) [dotcms_3.5_g14af2ce.jar:?]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146) [dotcms_3.5_g14af2ce.jar:?]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
       	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
       	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
       	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
       	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
       	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
       	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
       	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
       	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
       	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
       	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
       	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- compass
       	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:132) ~[jruby-complete-1.7.25.jar:?]
       	at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1360) ~[jruby-complete-1.7.25.jar:?]
       	at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1353) ~[jruby-complete-1.7.25.jar:?]
       	at com.dotcms.enterprise.csspreproc.c.compile(SourceFile:70) ~[ee-gaf7f4f0.jar:?]
       	... 50 more
Caused by: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- compass
       	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040) ~[jruby-complete-1.7.25.jar:?]
       	at RUBY.require(/Users/joseorsini/dotCMS/releases/3.5-dist/dotserver/tomcat-8.0.18/webapps/ROOT/WEB-INF/lib/jruby-complete-1.7.25.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54) ~[?:?]
       	at RUBY.(root)(<script>:2) ~[?:?]
       	at com.dotcms.enterprise.csspreproc.c.compile(SourceFile:70) ~[ee-gaf7f4f0.jar:?]
       	at com.dotcms.enterprise.csspreproc.SassCompiler.compile(SourceFile:19) ~[ee-gaf7f4f0.jar:?]
[17/08/16 10:26:50:680 EDT] ERROR csspreproc.CSSPreProcessServlet: Exception while serving compiled css file
java.lang.Exception: java.lang.RuntimeException: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- compass
       	at com.dotcms.csspreproc.CSSPreProcessServlet.doGet(CSSPreProcessServlet.java:144) [dotcms_3.5_g14af2ce.jar:?]
       	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618) [servlet-api.jar:?]
       	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:244) [dotcms_3.5_g14af2ce.jar:?]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61) [dotcms_3.5_g14af2ce.jar:?]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:307) [dotcms_3.5_g14af2ce.jar:?]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:174) [dotcms_3.5_g14af2ce.jar:?]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_3.5_g14af2ce.jar:?]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) [dotcms_3.5_g14af2ce.jar:?]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146) [dotcms_3.5_g14af2ce.jar:?]
       	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
       	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
       	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
       	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
       	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
       	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
       	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
       	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
       	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
       	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
       	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
       	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
       	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.RuntimeException: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- compass
       	at com.dotcms.enterprise.csspreproc.c.compile(SourceFile:83) ~[ee-gaf7f4f0.jar:?]
       	at com.dotcms.enterprise.csspreproc.SassCompiler.compile(SourceFile:19) ~[ee-gaf7f4f0.jar:?]
       	at com.dotcms.csspreproc.CSSPreProcessServlet.doGet(CSSPreProcessServlet.java:140) ~[dotcms_3.5_g14af2ce.jar:?]
       	... 48 more
Caused by: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- compass
       	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:132) ~[jruby-complete-1.7.25.jar:?]
       	at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1360) ~[jruby-complete-1.7.25.jar:?]
       	at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1353) ~[jruby-complete-1.7.25.jar:?]
       	at com.dotcms.enterprise.csspreproc.c.compile(SourceFile:70) ~[ee-gaf7f4f0.jar:?]
       	at com.dotcms.enterprise.csspreproc.SassCompiler.compile(SourceFile:19) ~[ee-gaf7f4f0.jar:?]
       	at com.dotcms.csspreproc.CSSPreProcessServlet.doGet(CSSPreProcessServlet.java:140) ~[dotcms_3.5_g14af2ce.jar:?]
       	... 48 more
Caused by: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- compass
       	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040) ~[jruby-complete-1.7.25.jar:?]
       	at RUBY.require(/Users/joseorsini/dotCMS/releases/3.5-dist/dotserver/tomcat-8.0.18/webapps/ROOT/WEB-INF/lib/jruby-complete-1.7.25.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54) ~[?:?]
       	at RUBY.(root)(<script>:2) ~[?:?]
       	at com.dotcms.enterprise.csspreproc.c.compile(SourceFile:70) ~[ee-gaf7f4f0.jar:?]
       	at com.dotcms.enterprise.csspreproc.SassCompiler.compile(SourceFile:19) ~[ee-gaf7f4f0.jar:?]
```

**Comment by wezell** [comment]
The libsass based sass compiler might support windows
