### ISSUE TITLE
Fresh checkout - first build - 500 HTTP when starting dotcms

### ISSUE THREAD

**Issue by UdoGerhards** [dotCMS/core#7240]
Hello together,

I've a fresh checkout from the core repository, but unfortunately, after I have build the core according to 

=> http://dotcms.com/docs/latest/DevelopmentEnvironment

the CMS is not able to start.

Everytime I start the CMS with H2-database, during the import of the starter.zip, I have a lot of importing errors and in the end the following exception is thrown:

...
2015-02-11 22:00:17,906 ERROR com.dotmarketing.portlets.contentlet.business.HostAPIImpl - Unable to save/update Object to Hibernate Session 
com.dotmarketing.exception.DotHibernateException: Unable to save/update Object to Hibernate Session 
	at com.dotmarketing.db.HibernateUtil.saveOrUpdate(HibernateUtil.java:476)
	at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.save(ESContentFactoryImpl.java:1352)
	at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.save(ESContentFactoryImpl.java:1338)
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl.createSystemHost(HostAPIImpl.java:777)
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl.findSystemHost(HostAPIImpl.java:466)
	at com.dotmarketing.servlets.InitServlet.init(InitServlet.java:227)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1284)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1197)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1087)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5210)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5493)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1247)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1898)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.dotcms.repackage.net.sf.hibernate.exception.GenericJDBCException: could not insert: [com.dotmarketing.portlets.contentlet.business.Contentlet#c0fbc794-05f4-45dc-86df-ddb59b71ad9d]
	at com.dotcms.repackage.net.sf.hibernate.exception.ErrorCodeConverter.handledNonSpecificException(ErrorCodeConverter.java:90)
	at com.dotcms.repackage.net.sf.hibernate.exception.ErrorCodeConverter.convert(ErrorCodeConverter.java:79)
	at com.dotcms.repackage.net.sf.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:29)
	at com.dotcms.repackage.net.sf.hibernate.persister.AbstractEntityPersister.convert(AbstractEntityPersister.java:1331)
	at com.dotcms.repackage.net.sf.hibernate.persister.NormalizedEntityPersister.insert(NormalizedEntityPersister.java:464)
	at com.dotcms.repackage.net.sf.hibernate.persister.NormalizedEntityPersister.insert(NormalizedEntityPersister.java:426)
	at com.dotcms.repackage.net.sf.hibernate.impl.ScheduledInsertion.execute(ScheduledInsertion.java:37)
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.execute(SessionImpl.java:2449)
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.executeAll(SessionImpl.java:2435)
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.execute(SessionImpl.java:2392)
	at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.flush(SessionImpl.java:2261)
	at com.dotmarketing.db.HibernateUtil.saveOrUpdate(HibernateUtil.java:474)
        ... 21 more
Caused by: org.h2.jdbc.JdbcSQLException: Referentielle Integrität verletzt: "FK_CONTENTLET_LANG: PUBLIC.CONTENTLET FOREIGN KEY(LANGUAGE_ID) REFERENCES PUBLIC.LANGUAGE(ID) (0)"
Referential integrity constraint violation: "FK_CONTENTLET_LANG: PUBLIC.CONTENTLET FOREIGN KEY(LANGUAGE_ID) REFERENCES PUBLIC.LANGUAGE(ID) (0)"; SQL statement:
insert into contentlet (show_on_menu, title, mod_date, mod_user, sort_order, friendly_name, structure_inode, last_review, next_review, review_interval, disabled_wysiwyg, identifier, language_id, date1, date2, date3, date4, date5, date6, date7, date8, date9, date10, date11, date12, date13, date14, date15, date16, date17, date18, date19, date20, date21, date22, date23, date24, date25, text1, text2, text3, text4, text5, text6, text7, text8, text9, text10, text11, text12, text13, text14, text15, text16, text17, text18, text19, text20, text21, text22, text23, text24, text25, text_area1, text_area2, text_area3, text_area4, text_area5, text_area6, text_area7, text_area8, text_area9, text_area10, text_area11, text_area12, text_area13, text_area14, text_area15, text_area16, text_area17, text_area18, text_area19, text_area20, text_area21, text_area22, text_area23, text_area24, text_area25, integer1, integer2, integer3, integer4, integer5, integer6, integer7, integer8, integer9, integer10, integer11, integer12, integer13, integer14, integer15, integer16, integer17, integer18, integer19, integer20, integer21, integer22, integer23, integer24, integer25, "float1", "float2", "float3", "float4", "float5", "float6", "float7", "float8", "float9", "float10", "float11", "float12", "float13", "float14", "float15", "float16", "float17", "float18", "float19", "float20", "float21", "float22", "float23", "float24", "float25", bool1, bool2, bool3, bool4, bool5, bool6, bool7, bool8, bool9, bool10, bool11, bool12, bool13, bool14, bool15, bool16, bool17, bool18, bool19, bool20, bool21, bool22, bool23, bool24, bool25, inode) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23506-176]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
        at org.h2.message.DbException.get(DbException.java:178)
        at org.h2.message.DbException.get(DbException.java:154)
        at org.h2.constraint.ConstraintReferential.checkRowOwnTable(ConstraintReferential.java:373)
        at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:315)
        at org.h2.table.Table.fireConstraints(Table.java:909)
        at org.h2.table.Table.fireAfterRow(Table.java:927)
        at org.h2.command.dml.Insert.insertRows(Insert.java:162)
        at org.h2.command.dml.Insert.update(Insert.java:115)
        at org.h2.command.CommandContainer.update(CommandContainer.java:79)
        at org.h2.command.Command.executeUpdate(Command.java:254)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:158)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:144)
        at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
        at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
        at com.dotcms.repackage.net.sf.hibernate.persister.NormalizedEntityPersister.insert(NormalizedEntityPersister.java:454)
...

and also after the first call to the page

...
com.dotmarketing.exception.DotRuntimeException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at com.dotmarketing.common.db.DotConnect.getString(DotConnect.java:305)
        at com.dotmarketing.portlets.contentlet.business.HostAPIImpl.createDefaultHost(HostAPIImpl.java:736)
        at com.dotmarketing.portlets.contentlet.business.HostAPIImpl.findDefaultHost(HostAPIImpl.java:98)
        at com.dotmarketing.portlets.contentlet.business.HostAPIImpl.resolveHostName(HostAPIImpl.java:150)
        at com.dotmarketing.business.web.HostWebAPIImpl.getCurrentHost(HostWebAPIImpl.java:65)
        at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:54)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
2015-02-11 22:00:45,869 ERROR com.dotmarketing.filters.ThreadNameFilter - Unable to retrieve current request host for URI /
...

This happens on H2 database as well as on postgres. Does anyone know what I have to change in order to make the import of the starter.zip happen.

As I said, its a clean clone of the repository, no source code changes, etc.

System: 

MacBook Pro
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

BR

Udo Gerhards

**Comment by jtesser** [comment]
ok this works for all of us

1. do not use Java 8
2. use deploy-war-tomcat7 which will download an drop the war in a tomcat at the sam level as your checkout. 
3. start with ./bin/dotStartup.sh for this

**Comment by UdoGerhards** [comment]
Hi jtesser,

after your answer it looks like it depends on java 8 because steps 2. and 3. where done like you described. I will try out and keep you updated. 

Thanks a lot, Udo

**Comment by jtesser** [comment]
i would use the mailing list for this as this isn't a bug.
