### ISSUE TITLE
Live mode not rendering pages

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7275]
Edit mode and preview mode work.  This is both the latest nightly build and in the master-3.1 branch. 
Live mode gives you the error below:

This issue is currently a blocker for starter development.

```
2015-02-17 11:32:22,433 ERROR com.dotmarketing.services.PageServices - 
java.lang.NullPointerException
	at com.dotmarketing.services.PageServices.buildStream(PageServices.java:183)
	at com.dotmarketing.services.PageServices.buildStream(PageServices.java:77)
	at com.dotmarketing.velocity.DotResourceLoader.generateStream(DotResourceLoader.java:424)
	at com.dotmarketing.velocity.DotResourceLoader.getResourceStream(DotResourceLoader.java:165)
	at org.apache.velocity.Template.process(Template.java:113)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:433)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:350)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1519)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1499)
	at org.apache.velocity.app.VelocityEngine.getTemplate(VelocityEngine.java:374)
	at com.dotmarketing.velocity.VelocityServlet.doLiveMode(VelocityServlet.java:509)
	at com.dotmarketing.velocity.VelocityServlet.service(VelocityServlet.java:226)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:246)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter
```

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-18 // Postgres // FF
