### ISSUE TITLE
NPE when you try to add a new language 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7368]
We have a NPE when you go to System ==> Languages and try to add a new one
To recreate just clean the dotcms cache in the maintenance portlet and then try to add the language 
```
 ERROR velocity.ClientVelocityServlet: java.lang.NullPointerException
java.lang.NullPointerException
	at com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPIImpl.fromContentlet(HTMLPageAssetAPIImpl.java:173)
	at com.dotmarketing.velocity.VelocityServlet.getPage(VelocityServlet.java:1310)
	at com.dotmarketing.velocity.VelocityServlet.isArchive(VelocityServlet.java:1102)
	at com.dotmarketing.velocity.VelocityServlet.service(VelocityServlet.java:193)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:488)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
	at org.apache.jsp.portal._404_jsp._jspService(_404_jsp.java:176)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:488)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:467)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:338)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:203)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

Tested on nightly build 2015-02-24 // Postgres // FF

**Comment by bryanboza** [comment]
Not able to reproduce in the last nightly.... But now i can't delete again

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-27 // Postgres // FF
