### ISSUE TITLE
Push Publishing: Improve logging and exception handling with failed Push Pub jobs

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7390]
Related to https://my.dotcms.com/ticket/dotcms-12

Reproduced in 2.5.7 and 3.0.1.

Steps to reproduce:

1. Create a Test Structure with a Title and Image fields. Make sure the selected host for this structure is "demo.dotcms.com"
2. Upload an image through Website Browser. Once it's uploaded, grab its inode.
3. Create a Test Structure and add the Image you uploaded in step 2 as value of its Image Field. Save and Publish.
4. Go to the Assets directory and find the image according to its inode. Delete it.
5. Push demo.dotcms.com host.

Exception (in 2.5.7)
```
[02/03/15 14:43:30:871 EST] ERROR business.ESContentletAPIImpl: 
[02/03/15 14:43:30:871 EST] ERROR business.ESContentletAPIImpl: java.lang.NullPointerException
[02/03/15 14:43:30:871 EST] ERROR business.ESContentletAPIImpl: java.lang.NullPointerException
java.lang.NullPointerException
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2167)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:1971)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:1967)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:1924)
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkin(ContentletAPIInterceptor.java:256)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:273)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:147)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(SourceFile:83)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(SourceFile:73)
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:161)
	at com.dotcms.rest.PublishThread.run(PublishThread.java:40)
	at java.lang.Thread.run(Thread.java:745)
[02/03/15 14:43:30:952 EST] ERROR business.PublisherAPIImpl: Error Publishing Bundle: null
com.dotcms.publishing.DotPublishingException
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:244)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(SourceFile:83)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(SourceFile:73)
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:161)
	at com.dotcms.rest.PublishThread.run(PublishThread.java:40)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.dotmarketing.exception.DotRuntimeException
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2580)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:1971)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:1967)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:1924)
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkin(ContentletAPIInterceptor.java:256)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:273)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:147)
	... 5 more
[02/03/15 14:43:30:957 EST] ERROR lang.String: Error Publishing: com.dotcms.publishing.DotPublishingException
[02/03/15 14:43:30:957 EST]  INFO rest.PublishThread:  : [BundleID: 573b69c4-cd2b-4139-83b8-d156b1d757a2.tar.gz] Finished bundle publish process
```

All file references exist in the DB but not in the Assets folder (a scenario that we have noticed more than once in some clients), and this makes the entire process of Pushing a host to fail. We could improve logging too, just to make sure that if a content fails, we can get more info about the failure and the content associated to it.

**Comment by oarrietadotcms** [comment]
Logging improved, now it says a message like this: ERROR com.dotcms.publisher.business.PublisherAPIImpl - Error Publishing Bundle: Unable to validate field: fileAsset identifier: 501ac533-6080-4356-a136-664dc06b5af9 inode: b7d3459d-a33b-4e81-a0a6-be3026b56f5b

Pull request: https://github.com/dotCMS/core/pull/7399

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-16 // Postgres // FF
