### ISSUE TITLE
Unable to push pages in the site root 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7445]
We have an error on log when you try to push some page that are located in the root of the site...

Here the log:
```
[10/03/15 15:25:03:165 CST] ERROR business.ESContentletAPIImpl: You can only create an identifier on a host of folder.  Trying: null
[10/03/15 15:25:03:166 CST] ERROR business.ESContentletAPIImpl: com.dotmarketing.business.DotStateException: You can only create an identifier on a host of folder.  Trying: null
[10/03/15 15:25:03:166 CST] ERROR business.ESContentletAPIImpl: com.dotmarketing.business.DotStateException: You can only create an identifier on a host of folder.  Trying: null
com.dotmarketing.business.DotStateException: You can only create an identifier on a host of folder.  Trying: null
	at com.dotmarketing.business.IdentifierAPIImpl.createNew(IdentifierAPIImpl.java:144)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2517)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2319)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2315)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2267)
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkin(ContentletAPIInterceptor.java:257)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:394)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:151)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(SourceFile:84)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(SourceFile:74)
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:162)
	at com.dotcms.rest.PublishThread.run(PublishThread.java:41)
	at java.lang.Thread.run(Thread.java:745)
[10/03/15 15:25:03:628 CST] ERROR business.PublisherAPIImpl: Error Publishing Bundle: You can only create an identifier on a host of folder.  Trying: null
com.dotcms.publishing.DotPublishingException: You can only create an identifier on a host of folder.  Trying: null
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:263)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(SourceFile:84)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(SourceFile:74)
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:162)
	at com.dotcms.rest.PublishThread.run(PublishThread.java:41)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.dotmarketing.exception.DotRuntimeException: You can only create an identifier on a host of folder.  Trying: null
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2987)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2319)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2315)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2267)
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkin(ContentletAPIInterceptor.java:257)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:394)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:151)
	... 5 more
[10/03/15 15:25:03:630 CST] ERROR lang.String: Error Publishing: com.dotcms.publishing.DotPublishingException: You can only create an identifier on a host of folder.  Trying: null
[10/03/15 15:25:03:630 CST]  INFO rest.PublishThread: Finished bundle publish process
```

To recreate:
- Create a new page in the site root 
- Try to push 
- Check the dotcms.log file  

Tested on nightly build 2015-03-03 // H2 // FF

**Comment by jgambarios** [comment]
Unable to reproduce with latest 3.1, tested with postgres and h2.

**Comment by bryanboza** [comment]
Some other change was fixed this issue, able to reproduce in 2015-03-03 build, but not in the last one ....

**Comment by shayngr** [comment]
Created tc http://qa.dotcms.com/index.php?/cases/view/55718
