### ISSUE TITLE
NPE generating XML site maps 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7457]
We have a NullPointerException every time the system try to generate the site map.... 
```
[11/03/15 16:35:10:030 CST] ERROR xmlsitemap.XMLSitemapJob: 
java.lang.NullPointerException
	at com.dotcms.xmlsitemap.XMLSitemapJob.generateSitemapPerHost(XMLSitemapJob.java:252)
	at com.dotcms.xmlsitemap.XMLSitemapJob.execute(XMLSitemapJob.java:131)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549)
[11/03/15 16:35:10:098 CST] ERROR xmlsitemap.XMLSitemapJob: 
java.lang.NullPointerException
	at com.dotcms.xmlsitemap.XMLSitemapJob.generateSitemapPerHost(XMLSitemapJob.java:252)
	at com.dotcms.xmlsitemap.XMLSitemapJob.execute(XMLSitemapJob.java:131)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549)
[11/03/15 16:35:10:164 CST] ERROR xmlsitemap.XMLSitemapJob: 
java.lang.NullPointerException
	at com.dotcms.xmlsitemap.XMLSitemapJob.generateSitemapPerHost(XMLSitemapJob.java:252)
	at com.dotcms.xmlsitemap.XMLSitemapJob.execute(XMLSitemapJob.java:131)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549)
```
To reproduce just need enable the following parameters in the dotmarketing-config.properties files...
org.dotcms.XMLSitemap.ENABLE=true

Tested on nightly build 2015-03-10 // H2 // FF

**Comment by bryanboza** [comment]
FYI: The system is creating the file, but if you open it, this don't have nothing in to it....

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-13 // Postgres // FF
