### ISSUE TITLE
Page URLs are not working with UTF8 Characters

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#7464]
ie... /home/同城聊天室网站

Would appear the first time you hit it the error is 
2015-03-12 16:04:40,546 WARN  IntrusionDetector - [SECURITY FAILURE Anonymous:null@unknown -> /dotcms/IntrusionDetector] Invalid input: context=URLContext, type(HTTPURI)=^/([a-zA-Z0-9,.\-_:'"’\[\]() @%\*]*/?)*$, input=/home/同城聊天室网站
com.dotcms.repackage.org.owasp.esapi.errors.ValidationException: URLContext: Invalid input. Please conform to regex ^/([a-zA-Z0-9,.\-_:'"’\[\]() @%\*]*/?)*$ with a maximum length of 13
	at com.dotcms.repackage.org.owasp.esapi.reference.validation.StringValidationRule.checkWhitelist(StringValidationRule.java:144)
	at com.dotcms.repackage.org.owasp.esapi.reference.validation.StringValidationRule.checkWhitelist(StringValidationRule.java:160)
	at com.dotcms.repackage.org.owasp.esapi.reference.validation.StringValidationRule.getValid(StringValidationRule.java:284)
	at com.dotcms.repackage.org.owasp.esapi.reference.DefaultValidator.getValidInput(DefaultValidator.java:214)
	at com.dotcms.repackage.org.owasp.esapi.reference.DefaultValidator.isValidInput(DefaultValidator.java:152)
	at com.dotcms.repackage.org.owasp.esapi.reference.DefaultValidator.isValidInput(DefaultValidator.java:143)
	at com.liferay.util.Xss.URIHasXSS(Xss.java:150)
	at com.dotmarketing.filters.CMSFilter.xssCheck(CMSFilter.java:365)
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:84)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:297)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:169)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:744)
2015-03-12 16:04:40,546 WARN  com.dotmarketing.filters.CMSFilter - XSS Found in request URI: /home/同城聊天室网站

**Comment by jtesser** [comment]
I think this issue is a duplicate of https://github.com/dotCMS/core/issues/6572

**Comment by oarrietadotcms** [comment]
Notes:

1. ESAPI doesn't allow blacklist of characters so I update the code to use the old XSS mechanism ONLY for URI, the params remains using ESAPI.
2. I guess we will to improve the list of characters but it should be easy to update in next releases. 

PR: https://github.com/dotCMS/core/pull/7466

**Comment by jtesser** [comment]
@oarrietadotcms i will contact you when you get in this morning. I have a few ideas

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-03-13 // Postgres // FF
