### ISSUE TITLE
Adding a Tab with no tools gives you an Array out of Bounds exception.

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7480]
This is with data from the starter - the CMS Admin tab has no tools.  The only way to recover is to go to DB and restart (cache flush does not work).

![image](https://cloud.githubusercontent.com/assets/934364/6719391/9c046f9c-cd90-11e4-97a3-f95525f6160a.png)

![image](https://cloud.githubusercontent.com/assets/934364/6719401/aca720ce-cd90-11e4-87b6-1c641d508f63.png)

```
 
2015-03-17 17:11:00,120 ERROR com.liferay.portal.servlet.MainServlet - Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:635)
        at java.util.ArrayList.get(ArrayList.java:411)
        at org.apache.jsp.html.portal.layout_005fportal_jsp._jspService(layout_005fportal_jsp.java:1194)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:
```

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-04-11 // H2 // FF
