### ISSUE TITLE
3.1: Error 500 with Frontend pages in Weblogic Server

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7486]
Reproduced in 3.1 deployed in Weblogic 10.3.3 and 10.3.6.

If an Enterprise License is not applied to the dotCMS instance, the VelocityServlet.java class should redirect to /portal/no_license.jsp page. Instead, it redirects to the Error 500 page and the following stacktrace is displayed in logfiles.

BUT and even more important the front end is not loading with the license.  The issue is with the http/part library 

```
####<Mar 19, 2015 4:57:30 PM EDT> <Error> <HTTP> <MacBook-Pro.local> <myserver> <[ACTIVE] ExecuteThread: '2' for queue: 'weblogic.kernel.Default (self-tuning)'> <<WLS Kernel>> <> <> <1426798650168> <BEA-101020> <[ServletContext@1231767765[app:dotcms31 module:dotcms.war path: spec-version:2.5]] Servlet failed with Exception
java.lang.ClassCastException: com.dotmarketing.viewtools.RequestWrapper cannot be cast to weblogic.servlet.internal.ServletRequestImpl
	at weblogic.servlet.internal.ServletRequestImpl.getOriginalRequest(ServletRequestImpl.java:1446)
	at weblogic.servlet.internal.RequestDispatcherImpl.forward(RequestDispatcherImpl.java:112)
	at com.dotmarketing.velocity.VelocityServlet.service(VelocityServlet.java:161)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:227)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:125)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:301)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:184)
	at weblogic.servlet.internal.RequestDispatcherImpl.invokeServlet(RequestDispatcherImpl.java:526)
	at weblogic.servlet.internal.RequestDispatcherImpl.forward(RequestDispatcherImpl.java:253)
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:249)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:297)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:169)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at weblogic.servlet.internal.RequestEventsFilter.doFilter(RequestEventsFilter.java:27)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3730)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3696)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2273)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2179)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1490)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:256)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:221)
```

In this ticket, client suggests a way to fix the problem http://jira.dotmarketing.net/browse/EE-7587?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=5999255

**Comment by joseorsini** [comment]
Committed tested code in 3.1 + Weblogic 10.3.6. If a license is not applied, it redirects to /portal/no_license.jsp. If an Enterprise license is applied, all Frontend pages are displayed as expected.

**Comment by jtesser** [comment]
@jgambarios implement the fix with this solution 
http://www.coderanch.com/t/519555/BEA-Weblogic/java-lang-ClassCastException-weblogic-weblogic

make sure web logic still works

**Comment by jtesser** [comment]
the concern as discussed in slack was the request wrapper not being used

**Comment by dsilvam** [comment]
@joseorisni and I tried the other fix and it worked.

**Comment by joseorsini** [comment]
Tested the fix proposed by @dsilvam and worked. 

Code: https://gist.github.com/joseorsini/18a18cb13a898be011ef

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-04-08 // postgres // FF // webLogic 12c
