### ISSUE TITLE
3.1: ES Search Portlet does not load in Weblogic 10.3.6

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7489]
After deploying 3.1 in Weblogic 10.3.6 (it's not needed to have a license applied to it), we have the following in the ES Search portlet
![screen shot 2015-03-19 at 1 49 54 pm](https://cloud.githubusercontent.com/assets/1717110/6752128/0aa853b2-cee2-11e4-867a-2b387363610d.png)

Stacktrace:
 ```
2015-03-20 09:17:42,344 ERROR com.dotcms.rest.JSPPortlet - java.lang.ClassCastException: com.sun.proxy.$Proxy52 cannot be cast to weblogic.servlet.internal.ServletRequestImpl
java.lang.ClassCastException: com.sun.proxy.$Proxy52 cannot be cast to weblogic.servlet.internal.ServletRequestImpl
	at weblogic.servlet.internal.ServletRequestImpl.getOriginalRequest(ServletRequestImpl.java:1446)
	at weblogic.servlet.internal.RequestDispatcherImpl.include(RequestDispatcherImpl.java:350)
	at com.dotcms.rest.BaseRestPortlet.getJspResponse(BaseRestPortlet.java:104)
	at com.dotcms.rest.BaseRestPortlet.getLayout(BaseRestPortlet.java:165)
	at com.dotcms.rest.JSPPortlet.layoutGet(JSPPortlet.java:39)
	at sun.reflect.GeneratedMethodAccessor207.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.dotcms.repackage.com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.dotcms.repackage.com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.dotcms.repackage.com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.dotcms.repackage.com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
	at com.dotcms.repackage.com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.dotcms.repackage.com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.dotcms.repackage.com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.dotcms.repackage.com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.dotcms.repackage.com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1483)
	at com.dotcms.repackage.com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1414)
	at com.dotcms.repackage.com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1363)
	at com.dotcms.repackage.com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1353)
	at com.dotcms.repackage.com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:414)
	at com.dotcms.repackage.com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
	at com.dotcms.repackage.com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:708)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at com.dotcms.rest.servlet.ReloadableServletContainer.service(ReloadableServletContainer.java:119)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:227)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:125)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:301)
	at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:26)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:254)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:297)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:169)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at weblogic.servlet.internal.RequestEventsFilter.doFilter(RequestEventsFilter.java:27)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3730)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3696)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2273)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2179)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1490)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:256)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:221)
```

Even after changing the weblogic.xml and set the classloader to prefer the WEB-INF classes over Weblogic's, we still have the same issue

```
       <container-descriptor>
           <prefer-web-inf-classes>true</prefer-web-inf-classes>
      </container-descriptor>
```

**Comment by joseorsini** [comment]
FYI https://code.google.com/p/gitblit/issues/detail?id=224

**Comment by bryanboza** [comment]
Fixed, tested on nightly build 2015-04-08 // Postgres // FF // WebLogic 12c
