### ISSUE TITLE
Unable to start  dotcms-3.2 on H2 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7558]
We are having a database error when you try to start the server 

Here the complete log:
```
[06/04/15 18:17:12:510 CEST] ERROR util.JDBCExceptionReporter: Tabla "COMPANY" no encontrada
Table "COMPANY" not found; SQL statement:
select companyhbm0_.companyId as companyId0_, companyhbm0_.key_ as key_0_, companyhbm0_.portalURL as portalURL0_, companyhbm0_.homeURL as homeURL0_, companyhbm0_.mx as mx0_, companyhbm0_.name as name0_, companyhbm0_.shortName as shortName0_, companyhbm0_.type_ as type_0_, companyhbm0_.size_ as size_0_, companyhbm0_.street as street0_, companyhbm0_.city as city0_, companyhbm0_.state as state0_, companyhbm0_.zip as zip0_, companyhbm0_.phone as phone0_, companyhbm0_.fax as fax0_, companyhbm0_.emailAddress as emailAd16_0_, companyhbm0_.authType as authType0_, companyhbm0_.autoLogin as autoLogin0_, companyhbm0_.strangers as strangers0_ from Company companyhbm0_ where companyhbm0_.companyId=? [42102-176]
[06/04/15 18:17:12:510 CEST]  WARN util.JDBCExceptionReporter: SQL Error: 42102, SQLState: 42S02
[06/04/15 18:17:12:510 CEST] ERROR util.JDBCExceptionReporter: Tabla "COMPANY" no encontrada
Table "COMPANY" not found; SQL statement:
select companyhbm0_.companyId as companyId0_, companyhbm0_.key_ as key_0_, companyhbm0_.portalURL as portalURL0_, companyhbm0_.homeURL as homeURL0_, companyhbm0_.mx as mx0_, companyhbm0_.name as name0_, companyhbm0_.shortName as shortName0_, companyhbm0_.type_ as type_0_, companyhbm0_.size_ as size_0_, companyhbm0_.street as street0_, companyhbm0_.city as city0_, companyhbm0_.state as state0_, companyhbm0_.zip as zip0_, companyhbm0_.phone as phone0_, companyhbm0_.fax as fax0_, companyhbm0_.emailAddress as emailAd16_0_, companyhbm0_.authType as authType0_, companyhbm0_.autoLogin as autoLogin0_, companyhbm0_.strangers as strangers0_ from Company companyhbm0_ where companyhbm0_.companyId=? [42102-176]
[06/04/15 18:17:12:557 CEST] ERROR db.DotConnect: getResult(): unable to execute query.  Bad SQL? : select * from qrtz_triggers,      qrtz_cron_triggers where (qrtz_triggers.job_group='User Job' or        qrtz_triggers.job_group='Recurrent Campaign') and       qrtz_triggers.job_group<>'PAUSED' and       qrtz_triggers.start_time < ? and       qrtz_triggers.trigger_name=qrtz_cron_triggers.trigger_name and       qrtz_triggers.trigger_group=qrtz_cron_triggers.trigger_group [1428337032541] Tabla "QRTZ_TRIGGERS" no encontrada
Table "QRTZ_TRIGGERS" not found; SQL statement:
select * from qrtz_triggers,      qrtz_cron_triggers where (qrtz_triggers.job_group='User Job' or        qrtz_triggers.job_group='Recurrent Campaign') and       qrtz_triggers.job_group<>'PAUSED' and       qrtz_triggers.start_time < ? and       qrtz_triggers.trigger_name=qrtz_cron_triggers.trigger_name and       qrtz_triggers.trigger_group=qrtz_cron_triggers.trigger_group [42102-176]
org.h2.jdbc.JdbcSQLException: Tabla "QRTZ_TRIGGERS" no encontrada
Table "QRTZ_TRIGGERS" not found; SQL statement:
select * from qrtz_triggers,      qrtz_cron_triggers where (qrtz_triggers.job_group='User Job' or        qrtz_triggers.job_group='Recurrent Campaign') and       qrtz_triggers.job_group<>'PAUSED' and       qrtz_triggers.start_time < ? and       qrtz_triggers.trigger_name=qrtz_cron_triggers.trigger_name and       qrtz_triggers.trigger_group=qrtz_cron_triggers.trigger_group [42102-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.Parser.readTableOrView(Parser.java:5213)
	at org.h2.command.Parser.readTableFilter(Parser.java:1220)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1859)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1968)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1853)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1674)
	at org.h2.command.Parser.parseSelect(Parser.java:1662)
	at org.h2.command.Parser.parsePrepared(Parser.java:434)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:287)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:287)
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:551)
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:486)
	at com.dotmarketing.common.db.DotConnect.getResult(DotConnect.java:248)
	at com.dotmarketing.common.db.DotConnect.getResults(DotConnect.java:362)
	at com.dotmarketing.servlets.UpdateQuartzCronJobsServlet.init(UpdateQuartzCronJobsServlet.java:46)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4901)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5188)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1069)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1719)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Tested on nightly build 2015-04-02 // H2 // FF

**Comment by bryanboza** [comment]
Tested on MSSQL and have the same error ...

**Comment by jtesser** [comment]
@bryanboza is it not starting or r u just getting the quartz log error? It is working for all of us

**Comment by bryanboza** [comment]
@jtesser It's not starting, I have the error 500

**Comment by bryanboza** [comment]
@jtesser @erickgonzalez  Seems the error is only on Windows, tested locally on my mac and is working fine with the same nightly build

**Comment by erickgonzalez** [comment]
Not able to reproduce, I sent @bryanboza a new dist and he started without issues.

**Comment by bryanboza** [comment]
Tested in a different build and is working fine... Seems the problem is with the 2015-04-02 nightly build...

**Comment by jtesser** [comment]
so this is not working.  We were building the nightly for java 8 only Now is working with 7 and 8

**Comment by erickgonzalez** [comment]
@bryanboza test with the lastest nightly build (from today) it should work now.

**Comment by bryanboza** [comment]
Fixed, tested on nightly build 2015-04-07 // h2 // FF
