### ISSUE TITLE
NPE trying to delete host with multi-language contents 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7561]
Related to #7407 

When you create a new host with a multi language pages and this pages have content in different languages, if you try to delete the complete site, we are having a NPE 
```
[07/04/15 09:10:06:038 CST] ERROR business.HostAPIImpl: 
java.lang.NullPointerException
	at com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPIImpl.fromContentlet(HTMLPageAssetAPIImpl.java:151)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.loadPageByIdentifier(ESContentletAPIImpl.java:743)
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.delete(ESContentletAPIImpl.java:1176)
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.delete(ContentletAPIInterceptor.java:503)
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl$1DeleteHostThread.deleteHost(HostAPIImpl.java:587)
	at com.dotmarketing.portlets.contentlet.business.HostAPIImpl$1DeleteHostThread.run(HostAPIImpl.java:538)
[07/04/15 09:10:13:897 CST]  INFO allocation.decider: [4b07f1eb-7e82-4df9-b64f-6a73cf1ccfa5] low disk watermark [15%] exceeded on [7UaAqFEQT3mZk4F-SRftxg][4b07f1eb-7e82-4df9-b64f-6a73cf1ccfa5] free: 27.4gb[11.8%], replicas will not be assigned to this node
```
To recreate: 
- Create a new site 
- Create a new page in English and Spanish 
- Add content to this page in both languages
- Stop the site and then try to delete 

Tested on nightly build 2015-04-06 // H2 // FF

**Comment by bryanboza** [comment]
Fixed, tested on master-3.5 // Potgres // FF.... Now we have some WARN messages and a struts error on log, but the host and contents was deleted....  Here the log: https://gist.github.com/bryanboza/7a6dbf76e00719840aa164a485f51194
