### ISSUE TITLE
Error trying to push html pages

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7562]
Related to #7526 

We are having errors trying to push a folder with a html page.... 
![2015-04-07_0932](https://cloud.githubusercontent.com/assets/2641437/7026890/c9af9c2c-dd09-11e4-8cd0-580ad3322292.png)

To recerate
- Create a new folder 
- Add a new page into the folder 
- Try to push 

We have the follow error in the log:
```
[07/04/15 09:34:08:696 CST] ERROR business.PublisherAPIImpl: Error Publishing Bundle: null
com.dotcms.publishing.DotPublishingException
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:263)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(SourceFile:84)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.handle(SourceFile:74)
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:162)
	at com.dotcms.rest.PublishThread.run(PublishThread.java:41)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:293)
	at com.dotcms.enterprise.publishing.remote.handler.ContentHandler.a(SourceFile:125)
	... 5 more
```

Sender:  nightly build 2015-04-06 // MySQL // FF // Java8 // OSX
Receiver: nightly build 2015-04-06 // MySQL // Chrome // Java8 // OSX

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/271

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-04-08 // H2 // FF
