### ISSUE TITLE
Override plugin is not working in WebLogic 12c 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7576]
When you try to upload the override OSGI plugin we are having the follow error: 

```
2015-04-09 16:05:45,068 ERROR com.dotmarketing.osgi.override.Activator - Error injecting context for overriding
java.lang.NullPointerException
    at com.dotmarketing.osgi.UrlOsgiClassLoader.reload(UrlOsgiClassLoader.java:212)
    at com.dotmarketing.osgi.UrlOsgiClassLoader.reload(UrlOsgiClassLoader.java:97)
    at com.dotmarketing.osgi.GenericBundleActivator.injectContext(GenericBundleActivator.java:293)
    at com.dotmarketing.osgi.GenericBundleActivator.injectContext(GenericBundleActivator.java:250)
    at com.dotmarketing.osgi.GenericBundleActivator.publishBundleServices(GenericBundleActivator.java:133)
    at com.dotmarketing.osgi.override.Activator.start(Activator.java:20)
    at com.dotcms.repackage.org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
    at com.dotcms.repackage.org.apache.felix.framework.Felix.activateBundle(Felix.java:2146)
    at com.dotcms.repackage.org.apache.felix.framework.Felix.startBundle(Felix.java:2064)
    at com.dotcms.repackage.org.apache.felix.framework.Felix.setBundleStartLevel(Felix.java:1483)
    at com.dotcms.repackage.org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:334)
    at java.lang.Thread.run(Thread.java:745)
    at java.lang.Thread.run(Thread.java:745)
Error while starting bundle: file:/Users/Azuy/Desktop/WebLogic/Middleware/user_projects/domains/base_domain/servers/AdminServer/deploy/dotcms.war/WEB-INF/felix/load/com.dotcms.override-0.1.jar: com.dotcms.repackage.org.osgi.framework.BundleException: Activator start error in bundle com.dotcms.override [7].
com.dotcms.repackage.org.osgi.framework.BundleException: Activator start error in bundle com.dotcms.override [7].
```

FYI: I tested in a single tomcat instance and works fine 

Tested on nightly build 2015-04-08 // Postgres // FF // WebLogic 12c

**Comment by dim-s** [comment]
WildFly 10.1 has the same issue:

We are using DotCMS 3.7.1.

```
2017-03-02 18:18:52,840 INFO  [stdout] (fileinstall-/opt/wildfly/standalone/deployments/dotcms_3.7.1.war/WEB-INF/felix/load) Caused by: java.lang.NullPointerException
    at com.dotmarketing.osgi.UrlOsgiClassLoader.reload(UrlOsgiClassLoader.java:212)
    at com.dotmarketing.osgi.UrlOsgiClassLoader.reload(UrlOsgiClassLoader.java:97)
    at com.dotmarketing.osgi.GenericBundleActivator.injectContext(GenericBundleActivator.java:409)
    at com.dotmarketing.osgi.GenericBundleActivator.injectContext(GenericBundleActivator.java:366)
    at com.dotmarketing.osgi.GenericBundleActivator.publishBundleServices(GenericBundleActivator.java:174)
    at com.s7.reksoft.plugin.LanguageVariablesPlugin.start(LanguageVariablesPlugin.java:13)
    at com.dotcms.repackage.org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
    at com.dotcms.repackage.org.apache.felix.framework.Felix.activateBundle(Felix.java:2146)
    ... 7 more
```
