### ISSUE TITLE
Error deleting folder

### ISSUE THREAD

**Issue by grinev** [dotCMS/core#7603]
When trying to delete folder got this error:

An unexpected system error occurred.
object references an unsaved transient instance - save the transient instance before flushing: com.dotmarketing.beans.Identifier

Reproduced on versions 3.1 and 3.2

```
[17/04/15 23:50:14:836 MSK] ERROR business.FolderAPI: object references an unsaved transient instance - save the transient instance before flushing: com.dotmarketing.beans.Identifier
com.dotmarketing.exception.DotRuntimeException: object references an unsaved transient instance - save the transient instance before flushing: com.dotmarketing.beans.Identifier
        at com.dotmarketing.db.HibernateUtil.load(HibernateUtil.java:436)
        at com.dotmarketing.business.BaseWebAssetAPI.getVersionInfo(BaseWebAssetAPI.java:415)
        at com.dotmarketing.business.BaseWebAssetAPI.deleteAsset(BaseWebAssetAPI.java:329)
        at com.dotmarketing.portlets.files.business.FileAPIImpl.delete(FileAPIImpl.java:481)
        at com.dotmarketing.portlets.folders.business.FolderAPIImpl._deleteChildrenAssetsFromFolder(FolderAPIImpl.java:424)
        at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete(FolderAPIImpl.java:360)
        at com.dotmarketing.portlets.folders.action.EditFolderAction._deleteFolder(EditFolderAction.java:409)
        at com.dotmarketing.portlets.folders.action.EditFolderAction.processAction(EditFolderAction.java:135)
        at com.liferay.portal.struts.PortletRequestProcessor.process(PortletRequestProcessor.java:128)
        at com.liferay.portlet.StrutsPortlet.processAction(StrutsPortlet.java:116)
        at com.liferay.portlet.CachePortlet.processAction(CachePortlet.java:130)
        at com.liferay.portal.action.LayoutAction._processPortletRequest(LayoutAction.java:232)
        at com.liferay.portal.action.LayoutAction._processActionRequest(LayoutAction.java:249)
        at com.liferay.portal.action.LayoutAction.execute(LayoutAction.java:93)
        at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:421)
        at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:226)
        at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:158)
        at com.dotcms.repackage.org.apache.struts.action.ActionServlet.process(ActionServlet.java:1164)
        at com.dotcms.repackage.org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:397)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:734)
        at com.liferay.portal.servlet.MainServlet.callParentService(MainServlet.java:277)
        at com.liferay.portal.servlet.MainServlet.service(MainServlet.java:506)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.dotcms.repackage.com.liferay.filters.secure.SecureFilter.doFilter(SecureFilter.java:135)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:232)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:299)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.s7.cms.filter.NonExistentLanguageFilter.doFilter(NonExistentLanguageFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.s7.cms.filter.URLCleanupFilter.doFilter(URLCleanupFilter.java:61)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.s7.cms.filter.RememberMeProfileAutoLoginFilter.doFilter(RememberMeProfileAutoLoginFilter.java:75)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.s7.cms.filter.DefaultLanguageFilter.doFilter(DefaultLanguageFilter.java:50)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:397)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:631)
        at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:567)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:518)
        at org.jboss.threads.SimpleDirectExecutor.execute(SimpleDirectExecutor.java:33)
        at org.jboss.threads.QueueExecutor.runTask(QueueExecutor.java:801)
        at org.jboss.threads.QueueExecutor.access$100(QueueExecutor.java:45)
        at org.jboss.threads.QueueExecutor$Worker.run(QueueExecutor.java:821)
        at java.lang.Thread.run(Thread.java:745)
        at org.jboss.threads.JBossThread.run(JBossThread.java:122)
Caused by: com.dotcms.repackage.net.sf.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: com.dotmarketing.beans.Identifier
        at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.throwTransientObjectException(SessionImpl.java:2796)
        at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.getEntityIdentifierIfNotUnsaved(SessionImpl.java:2788)
        at com.dotcms.repackage.net.sf.hibernate.type.EntityType.getIdentifier(EntityType.java:67)
        at com.dotcms.repackage.net.sf.hibernate.type.ManyToOneType.nullSafeSet(ManyToOneType.java:47)
        at com.dotcms.repackage.net.sf.hibernate.loader.Loader.bindPositionalParameters(Loader.java:753)
        at com.dotcms.repackage.net.sf.hibernate.loader.Loader.prepareQueryStatement(Loader.java:793)
        at com.dotcms.repackage.net.sf.hibernate.loader.Loader.doQuery(Loader.java:269)
        at com.dotcms.repackage.net.sf.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:138)
        at com.dotcms.repackage.net.sf.hibernate.loader.Loader.doList(Loader.java:1063)
        at com.dotcms.repackage.net.sf.hibernate.loader.Loader.list(Loader.java:1054)
        at com.dotcms.repackage.net.sf.hibernate.hql.QueryTranslator.list(QueryTranslator.java:854)
        at com.dotcms.repackage.net.sf.hibernate.impl.SessionImpl.find(SessionImpl.java:1554)
        at com.dotcms.repackage.net.sf.hibernate.impl.QueryImpl.list(QueryImpl.java:49)
        at com.dotmarketing.db.HibernateUtil.load(HibernateUtil.java:410)
        ... 85 more
[17/04/15 23:50:14:839 MSK]  WARN action.EditFolderAction: com.dotmarketing.exception.DotDataException: object references an unsaved transient instance - save the transient instance before flushing: com.dotmarketing.beans.Identifier
com.dotmarketing.exception.DotDataException: object references an unsaved transient instance - save the transient instance before flushing: com.dotmarketing.beans.Identifier
        at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete(FolderAPIImpl.java:394)
        at com.dotmarketing.portlets.folders.action.EditFolderAction._deleteFolder(EditFolderAction.java:409)
        at com.dotmarketing.portlets.folders.action.EditFolderAction.processAction(EditFolderAction.java:135)
        at com.liferay.portal.struts.PortletRequestProcessor.process(PortletRequestProcessor.java:128)
        at com.liferay.portlet.StrutsPortlet.processAction(StrutsPortlet.java:116)
        at com.liferay.portlet.CachePortlet.processAction(CachePortlet.java:130)
        at com.liferay.portal.action.LayoutAction._processPortletRequest(LayoutAction.java:232)
        at com.liferay.portal.action.LayoutAction._processActionRequest(LayoutAction.java:249)
        at com.liferay.portal.action.LayoutAction.execute(LayoutAction.java:93)
        at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:421)
        at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:226)
        at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:158)
        at com.dotcms.repackage.org.apache.struts.action.ActionServlet.process(ActionServlet.java:1164)
        at com.dotcms.repackage.org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:397)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:734)
        at com.liferay.portal.servlet.MainServlet.callParentService(MainServlet.java:277)
        at com.liferay.portal.servlet.MainServlet.service(MainServlet.java:506)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.dotcms.repackage.com.liferay.filters.secure.SecureFilter.doFilter(SecureFilter.java:135)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
        at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:232)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:299)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.s7.cms.filter.NonExistentLanguageFilter.doFilter(NonExistentLanguageFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.s7.cms.filter.URLCleanupFilter.doFilter(URLCleanupFilter.java:61)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.s7.cms.filter.RememberMeProfileAutoLoginFilter.doFilter(RememberMeProfileAutoLoginFilter.java:75)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.s7.cms.filter.DefaultLanguageFilter.doFilter(DefaultLanguageFilter.java:50)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:397)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:631)
        at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:567)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:518)
        at org.jboss.threads.SimpleDirectExecutor.execute(SimpleDirectExecutor.java:33)
        at org.jboss.threads.QueueExecutor.runTask(QueueExecutor.java:801)
        at org.jboss.threads.QueueExecutor.access$100(QueueExecutor.java:45)
        at org.jboss.threads.QueueExecutor$Worker.run(QueueExecutor.java:821)
        at java.lang.Thread.run(Thread.java:745)
        at org.jboss.threads.JBossThread.run(JBossThread.java:122)
Caused by: com.dotmarketing.business.DotStateException: object references an unsaved transient instance - save the transient instance before flushing: com.dotmarketing.beans.Identifier
        at com.dotmarketing.portlets.folders.business.FolderAPIImpl._deleteChildrenAssetsFromFolder(FolderAPIImpl.java:473)
        at com.dotmarketing.portlets.folders.business.FolderAPIImpl.delete(FolderAPIImpl.java:360)
        ... 80 more
```

**Comment by jtesser** [comment]
@bryanboza do you have a reproducible case here?

**Comment by jtesser** [comment]
@bryanboza @brentgriffin any idea here?

**Comment by shayngr** [comment]
Unable to reproduce on different DBs and Oss. 
Tested on:
3.2 Nightly build 2015-05-21 18:42// Ubuntu 14.04 // Postgres // Firefox
3.2 Nightly build 2015-05-21 18:42// MacOSX 10.10 // Mysql // Chrome
