### ISSUE TITLE
Oracle - SQL command not properly ended 

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/core#7637]
[22/04/15 14:18:11:184 EDT] ERROR cluster.ClusterFactory: Error trying to wire node to the Cluster 
com.dotmarketing.exception.DotDataException: ORA-00933: SQL command not properly ended 

        at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:234) 
        at com.dotmarketing.common.db.DotConnect.loadObjectResults(DotConnect.java:859) 
        at com.dotcms.enterprise.cluster.ServerFactoryImpl.getAliveServers(SourceFile:178) 
        at com.dotcms.cluster.business.ServerAPIImpl.getAliveServers(ServerAPIImpl.java:110) 
        at com.dotcms.enterprise.cluster.ClusterFactory.addNodeToCluster(SourceFile:211) 
        at com.dotcms.enterprise.cluster.ClusterFactory.addNodeToCluster(SourceFile:197) 
        at com.dotcms.enterprise.cluster.ClusterFactory.initialize(SourceFile:111) 
        at com.dotmarketing.startup.runalways.Task00009ClusterInitialize.executeUpgrade(Task00009ClusterInitialize.java:45) 
        at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:214) 
        at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:116) 
        at weblogic.servlet.internal.StubSecurityHelper$ServletInitAction.run(StubSecurityHelper.java:283) 
        at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321) 
        at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:121) 
        at weblogic.servlet.internal.StubSecurityHelper.createServlet(StubSecurityHelper.java:64) 
        at weblogic.servlet.internal.StubLifecycleHelper.createOneInstance(StubLifecycleHelper.java:58) 
        at weblogic.servlet.internal.StubLifecycleHelper.<init>(StubLifecycleHelper.java:48) 
        at weblogic.servlet.internal.ServletStubImpl.prepareServlet(ServletStubImpl.java:539) 
        at weblogic.servlet.internal.WebAppServletContext.preloadServlet(WebAppServletContext.java:1976) 
        at weblogic.servlet.internal.WebAppServletContext.loadServletsOnStartup(WebAppServletContext.java:1950) 
        at weblogic.servlet.internal.WebAppServletContext.preloadResources(WebAppServletContext.java:1869) 
        at weblogic.servlet.internal.WebAppServletContext.start(WebAppServletContext.java:3126) 
        at weblogic.servlet.internal.WebAppModule.startContexts(WebAppModule.java:1512) 
        at weblogic.servlet.internal.WebAppModule.start(WebAppModule.java:486) 
        at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:425) 
        at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:41)

**Comment by oarrietadotcms** [comment]
There were 2 issues here: 

1. We don't need to check alive servers is heartbeat is disabled, Pull request for that: https://github.com/dotCMS/enterprise-2.x/pull/272

2. The SQL error in the log is because the client has this property duplicated: HEARTBEAT_TIMEOUT.  As I wrote in the issue https://github.com/dotCMS/core/issues/7596 I moved some properties to dotcms-config-cluster.properties. You need to update your plugin to move that property also.
