### ISSUE TITLE
Wrong format for cron expression 

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/core#7638]
I haven't been able to reproduce this one locally. 

We saw it happening on a weblogic instance, so we were wondering whether this needs to be fixed in the core or via plugin for such type of instances.

[22/04/15 14:18:31:934 EDT] ERROR init.DotInitScheduler: Day-of-Week values must be between 1 and 7 
java.text.ParseException: Day-of-Week values must be between 1 and 7 
        at org.quartz.CronExpression.addToSet(CronExpression.java:920) 
        at org.quartz.CronExpression.checkNext(CronExpression.java:655) 
        at org.quartz.CronExpression.storeExpressionVals(CronExpression.java:638) 
        at org.quartz.CronExpression.buildExpression(CronExpression.java:430) 
        at org.quartz.CronExpression.<init>(CronExpression.java:255) 
        at org.quartz.CronTrigger.setCronExpression(CronTrigger.java:471) 
        at org.quartz.CronTrigger.<init>(CronTrigger.java:381) 
        at com.dotmarketing.init.DotInitScheduler.start(DotInitScheduler.java:789)

**Comment by chrismccracken** [comment]
Here's the config:

ENABLE_REMOVE_INACTIVE_CLUSTER_SERVER=true
REMOVE_INACTIVE_CLUSTER_SERVER_CRON_EXPRESSION=59 59 23 * * ?

REMOVE_INACTIVE_CLUSTER_SERVER_PERIOD=2W

**Comment by oarrietadotcms** [comment]
I think this is related to the issue here: https://github.com/dotCMS/core/issues/7637, because I can't reproduce it on my local.

See point 2.

The SQL error in the log is because the client has this property duplicated: REMOVE_INACTIVE_CLUSTER_SERVER_CRON_EXPRESSION. As I wrote in the issue #7596 I moved some properties to dotcms-config-cluster.properties. You need to update your plugin to move that property also.
