### ISSUE TITLE
NPE trying to start a dotCMS instance using WebSphere 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7668]
We are having a initializer error trying to start dotcms in a WebSphere server, The server never starts....

Here the log error:
```
err] Exception in thread "Thread-54" 
[err] java.lang.ExceptionInInitializerError
[err] 	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.loadFields(ESMappingAPIImpl.java:535)
[err] 	at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.toMap(ESMappingAPIImpl.java:263)
[err] 	at com.dotcms.content.elasticsearch.business.ESContentletIndexAPI.indexContentletList(ESContentletIndexAPI.java:328)
[err] 	at com.dotcms.content.elasticsearch.business.ESContentletIndexAPI.access$100(ESContentletIndexAPI.java:44)
[err] 	at com.dotcms.content.elasticsearch.business.ESContentletIndexAPI$1.run(ESContentletIndexAPI.java:298)
[err] 	at com.dotcms.content.elasticsearch.business.ESContentletIndexAPI.addContentToIndex(ESContentletIndexAPI.java:310)
[err] 	at com.dotmarketing.common.reindex.ReindexThread.writeDocumentToIndex(ReindexThread.java:401)
[err] 	at com.dotmarketing.common.reindex.ReindexThread.run(ReindexThread.java:161)
[err] Caused by: java.lang.NullPointerException
[err] 	at com.dotcms.enterprise.LicenseUtil.<clinit>(SourceFile:28)
[err] 	... 8 more
2015-04-28 13:35:11,191 INFO  com.dotmarketing.util.ImportExportUtil - Records left to index : 800
2015-04-28 13:36:11,489 INFO  com.dotmarketing.util.ImportExportUtil - Records left to index : 800
2015-04-28 13:37:11,798 INFO  com.dotmarketing.util.ImportExportUtil - Records left to index : 800
[AUDIT   ] CWWKE0055I: Server shutdown requested on Tuesday, April 28, 2015 at 1:37 PM. The server dotcms is shutting down.
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://azuy-virtualbox.dotcms:8080/
[AUDIT   ] WTRN0105I: The transaction service has shutdown successfully with no transactions requiring recovery.
[AUDIT   ] CWWKE0036I: The server dotcms stopped after 6 minutes, 19.066 seconds.
 
```

Testing Info:  Linux // WebSphere v 8.5.5 // dotcms-3.2

**Comment by wezell** [comment]
Here are the results - getting "Failed Requests" and seeing the following in the log


https://gist.github.com/wezell/756ec40f17aee61b0497

**Comment by jtesser** [comment]
So I think the issue here is you need to get at the WEB-INF/lib dir this way https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/util/ResourceCollectorUtil.java#L46

**Comment by bryanboza** [comment]
FYI: Tested in h2 and postgres and have the same error...

**Comment by maurizo** [comment]
Pull request: #7776
Pull request: dotCMS/enterprise-2.x#278

**Comment by bryanboza** [comment]
Fixed, tested in a generated distribution from master-3.2 // Postgres // WebSphere v8.5.5
