### ISSUE TITLE
Not sure why we need to get into java.util.UUID

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7683]
Just return the durn id if it is not null

https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/beans/Identifier.java#L59

Seen in thread dumps.  Not a huge thing, just unnecessary.
```
"url:GET//demo.dotcms.com/ | lang:1 | ip:127.0.0.1 | Admin:false | start:05-01-2015 09:42:33 EDT" daemon prio=10 tid=0x00000000013d6000 nid=0x1517 runnable [0x00007fd2004c2000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.Long.toUnsignedString(Long.java:250)
	at java.lang.Long.toHexString(Long.java:177)
	at java.util.UUID.digits(UUID.java:385)
	at java.util.UUID.toString(UUID.java:375)
	at com.dotmarketing.beans.Identifier.getId(Identifier.java:60)
	at com.dotmarketing.velocity.VelocityServlet.getPage(VelocityServlet.java:134
```

**Comment by wezell** [comment]
Another thread:

```
"url:GET//demo.dotcms.com/ | lang:1 | ip:127.0.0.1 | Admin:false | start:05-01-2015 09:42:33 EDT" daemon prio=10 tid=0x00007fd3085d9000 nid=0x1554 runnable [0x00007fd1f86c4000]
   java.lang.Thread.State: RUNNABLE
	at java.util.Arrays.copyOfRange(Arrays.java:2694)
	at java.lang.String.<init>(String.java:203)
	at java.lang.String.substring(String.java:1877)
	at java.lang.Long.decode(Long.java:657)
	at java.util.UUID.fromString(UUID.java:202)
	at com.dotmarketing.beans.Identifier.getId(Identifier.java:59)
	at com.dotmarketing.beans.Identifier.getInode(Identifier.java:53)

```

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7716

**Comment by brentgriffin** [comment]
Requested code has been removed.  Does not seem like it it should cause problems but regression testing will need to prove that.
