### ISSUE TITLE
Seeing this error and failed requests when benchmarking

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7739]
I know we did work on the navtool / languages.  Need to take a look.
This is on the dotcms-2015-05-14 nightly build

```
[14/05/15 10:11:59:982 EDT] ERROR business.LanguageFactoryImpl: getLanguage failed passed id is not numeric.
java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:404)
	at java.lang.Long.parseLong(Long.java:483)
	at com.dotmarketing.portlets.languagesmanager.business.LanguageFactoryImpl.getLanguage(LanguageFactoryImpl.java:93)
	at com.dotmarketing.portlets.languagesmanager.business.LanguageAPIImpl.getLanguage(LanguageAPIImpl.java:46)
	at com.dotmarketing.business.web.LanguageWebAPIImpl.checkSessionLocale(LanguageWebAPIImpl.java:76)
	at com.dotmarketing.business.web.LanguageWebAPIImpl.getLanguage(LanguageWebAPIImpl.java:97)
	at com.dotmarketing.viewtools.navigation.NavTool.getNav(NavTool.java:56)
	at com.dotmarketing.viewtools.navigation.NavResult.getChildren(NavResult.java:151)
	at sun.reflect.GeneratedMethodAccessor281.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.velocity.runtime.parser.node.PropertyExecutor.execute(PropertyExecutor.java:128)
	at org.apache.velocity.util.introspection.UberspectImpl$VelGetterImpl.invoke(UberspectImpl.java:516)
	at org.apache.velocity.runtime.parser.node.ASTIdentifier.execute(ASTIdentifier.java:202)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285)
	at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:572)
	at org.apache.velocity.runtime.parser.node.ASTExpression.value(ASTExpression.java:71)
	at org.apache.velocity.runtime.parser.node.ASTSetDirective.render(ASTSetDirective.java:150)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:423)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:211)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:330)
	at org.apache.velocity.Template.merge(Template.java:362)
	at org.apache.velocity.Template.merge(Template.java:265)
	at com.dotmarketing.viewtools.VelocityWebUtil.mergeTemplate(VelocityWebUtil.java:87)
	at sun.reflect.GeneratedMethodAccessor202.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:178)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285)
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:374)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:218)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:308)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:226)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:211)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:330)
	at org.apache.velocity.Template.merge(Template.java:362)
	at org.apache.velocity.Template.merge(Template.java:265)
	at com.dotmarketing.viewtools.VelocityWebUtil.mergeTemplate(VelocityWebUtil.java:87)
	at sun.reflect.GeneratedMethodAccessor202.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:178)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285)
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:374)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:330)
	at org.apache.velocity.Template.merge(Template.java:362)
	at org.apache.velocity.Template.merge(Template.java:265)
	at com.dotmarketing.velocity.VelocityServlet.doLiveMode(VelocityServlet.java:540)
	at com.dotmarketing.velocity.VelocityServlet.service(VelocityServlet.java:251)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:203)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:299)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:49)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7754

**Comment by jtesser** [comment]
@oarrietadotcms this is still broke.  Getting this now and still getting errors

**Comment by wezell** [comment]
Here are the results - getting "Failed Requests" and seeing the following in the log


https://gist.github.com/wezell/756ec40f17aee61b0497

**Comment by wezell** [comment]
In the changes to the navtool since 3.2, we made the instance variables for the request and languageId static that I am 99% are the cause of these issues.  The navtool needs to be instantiated each request and should not share these variables.

https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/viewtools/navigation/NavTool.java#L34

**Comment by wezell** [comment]
No more failures while benchmarking & nav is still multilingual:

```
will@OboxTurbo:~/dotcms/2015-05-19$ ab -n 10000 -c 50 http://192.168.1.18:8081/
This is ApacheBench, Version 2.3 <$Revision: 1528965 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 192.168.1.18 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        Apache-Coyote/1.1
Server Hostname:        192.168.1.18
Server Port:            8081

Document Path:          /
Document Length:        29974 bytes

Concurrency Level:      50
Time taken for tests:   7.734 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      302920000 bytes
HTML transferred:       299740000 bytes
Requests per second:    1292.94 [#/sec] (mean)
Time per request:       38.671 [ms] (mean)
Time per request:       0.773 [ms] (mean, across all concurrent requests)
Transfer rate:          38247.85 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.6      0      10
Processing:     3   38  28.2     29     196
Waiting:        3   37  27.9     28     195
Total:          3   39  28.2     30     196

Percentage of the requests served within a certain time (ms)
  50%     30
  66%     43
  75%     52
  80%     59
  90%     79
  95%     95
  98%    114
  99%    130
 100%    196 (longest request)

```

**Comment by bryanboza** [comment]
Fixed, tested in the performance testing made bi @wezell
