### ISSUE TITLE
Navtool language improvement

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7740]
We need to get the language once in the viewtool init method and reuse it in the methods, rather than call it every getNav

**Comment by wezell** [comment]
reasoning for this - the navtool gets called multiple times per page and I have seen threads in the getLocale methods

**Comment by wezell** [comment]
Also, I am seeing errors in the  are seeing this when doing benchmarking, as well as failed requests.  We will need to fix.
```
2015-05-18 09:53:46,508 ERROR com.dotmarketing.portlets.languagesmanager.business.LanguageFactoryImpl - getLanguage failed passed id is not numeric.
java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:404)
	at java.lang.Long.parseLong(Long.java:483)
	at com.dotmarketing.portlets.languagesmanager.business.LanguageFactoryImpl.getLanguage(LanguageFactoryImpl.java:93)
	at com.dotmarketing.portlets.languagesmanager.business.LanguageAPIImpl.getLanguage(LanguageAPIImpl.java:46)
	at com.dotmarketing.business.web.LanguageWebAPIImpl.getLanguage(LanguageWebAPIImpl.java:98)
	at com.dotmarketing.viewtools.navigation.NavTool.getNav(NavTool.java:56)
	at com.dotmarketing.viewtools.navigation.NavTool.getNav(NavTool.java:192)
	at sun.reflect.GeneratedMethodAccessor627.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:178)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285)
	at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:572)
	at org.apache.velocity.runtime.parser.node.ASTExpression.value(ASTExpression.java:71)
	at org.apache.velocity.runtime.parser.node.ASTSetDirective.render(ASTSetDirective.java:150)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:330)
	at org.apache.velocity.Template.merge(Template.java:362)
	at org.apache.velocity.Template.merge(Template.java:265)
	at com.dotmarketing.viewtools.VelocityWebUtil.mergeTemplate(VelocityWebUtil.java:87)
	at sun.reflect.GeneratedMethodAccessor382.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:178)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285)
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:374)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:218)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:308)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:226)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:211)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:330)
	at org.apache.velocity.Template.merge(Template.java:362)
	at org.apache.velocity.Template.merge(Template.java:265)
	at com.dotmarketing.viewtools.VelocityWebUtil.mergeTemplate(VelocityWebUtil.java:87)
	at sun.reflect.GeneratedMethodAccessor382.invoke(Unknown Source)

```

**Comment by oarrietadotcms** [comment]
For sure @wezell , I am working on this and the rest of the nav tool issues. I hope to commit everything today.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7754

**Comment by bryanboza** [comment]
Fixed, tested by @wezell in the performance testing...
