### ISSUE TITLE
Integrity checker fails from dotcms.com

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7852]
I am trying to run the integrity checker from dotcms.com to a local new install and it is failing. I see the conflicts and select fix at remote node and it errors out:

![screen shot 2015-06-17 at 3 44 22 pm](https://cloud.githubusercontent.com/assets/934364/8216933/d0955de8-1507-11e5-97ef-f882fdd99cec.png)

```
2015-06-17 15:41:46,304 INFO  com.dotmarketing.business.DotGuavaCacheAdministratorImpl - ***	 Building Cache : publishingendpointcache, size:100, toDisk:false,Concurrency:32
2015-06-17 15:42:00,778 INFO  com.dotcms.rest.IntegrityUtil - Writing '/Users/will/git/tomcat8/webapps/ROOT/assets/integrity/3e8a69d8-68a2-41fe-8a04-ffd1537f0bc2/FoldersToCheck.csv' to zip file
2015-06-17 15:42:00,780 INFO  com.dotcms.rest.IntegrityUtil - Writing '/Users/will/git/tomcat8/webapps/ROOT/assets/integrity/3e8a69d8-68a2-41fe-8a04-ffd1537f0bc2/StructuresToCheck.csv' to zip file
2015-06-17 15:42:00,780 INFO  com.dotcms.rest.IntegrityUtil - Writing '/Users/will/git/tomcat8/webapps/ROOT/assets/integrity/3e8a69d8-68a2-41fe-8a04-ffd1537f0bc2/SchemesToCheck.csv' to zip file
2015-06-17 15:42:00,781 INFO  com.dotcms.rest.IntegrityUtil - Writing '/Users/will/git/tomcat8/webapps/ROOT/assets/integrity/3e8a69d8-68a2-41fe-8a04-ffd1537f0bc2/HtmlPagesToCheck.csv' to zip file
2015-06-17 15:42:00,781 INFO  com.dotcms.rest.IntegrityUtil - Writing '/Users/will/git/tomcat8/webapps/ROOT/assets/integrity/3e8a69d8-68a2-41fe-8a04-ffd1537f0bc2/ContentPagesToCheck.csv' to zip file
Unzipping StructuresToFix.csv
2015-06-17 15:42:48,153 INFO  com.dotmarketing.common.db.DotConnect - Executing insert into inode values ('TEMP_INODE', 'DUMMY_OWNER', '1900-01-01 00:00:00.00', 'DUMMY_TYPE') 
2015-06-17 15:42:48,156 INFO  com.dotmarketing.common.db.DotConnect - Executing insert into structure values ('TEMP_INODE', 'DUMMY_NAME', 'DUMMY_DESC', '0', '', '', '', 1, '1', '0', 'DUMMY_VAR_NAME', 'DUMMY_PATERN', 'SYSTEM_HOST', 'SYSTEM_FOLDER', 'EXPIRE_DUMMY', 'PUBLISH_DUMMY', '1900-01-01 00:00:00.00')
2015-06-17 15:42:48,158 INFO  com.dotmarketing.common.db.DotConnect - Executing update container_structures set structure_id = 'TEMP_INODE' where structure_id = '33888b6f-7a8e-4069-b1b6-5c1aa9d0a48d'
2015-06-17 15:42:48,159 INFO  com.dotmarketing.common.db.DotConnect - Executing update contentlet set structure_inode = 'TEMP_INODE' where structure_inode = '33888b6f-7a8e-4069-b1b6-5c1aa9d0a48d'
2015-06-17 15:42:48,220 INFO  com.dotmarketing.common.db.DotConnect - Executing update field set structure_inode = 'TEMP_INODE' where structure_inode = '33888b6f-7a8e-4069-b1b6-5c1aa9d0a48d'
2015-06-17 15:42:48,223 INFO  com.dotmarketing.common.db.DotConnect - Executing update relationship set parent_structure_inode = 'TEMP_INODE' where parent_structure_inode = '33888b6f-7a8e-4069-b1b6-5c1aa9d0a48d'
2015-06-17 15:42:48,224 INFO  com.dotmarketing.common.db.DotConnect - Executing update relationship set child_structure_inode = 'TEMP_INODE' where child_structure_inode = '33888b6f-7a8e-4069-b1b6-5c1aa9d0a48d'
2015-06-17 15:42:48,224 INFO  com.dotmarketing.common.db.DotConnect - Executing update workflow_scheme_x_structure set structure_id = 'TEMP_INODE' where structure_id = '33888b6f-7a8e-4069-b1b6-5c1aa9d0a48d'
2015-06-17 15:42:48,225 INFO  com.dotmarketing.common.db.DotConnect - Executing update permission set inode_id = 'TEMP_INODE' where inode_id = '33888b6f-7a8e-4069-b1b6-5c1aa9d0a48d'
2015-06-17 15:42:48,226 INFO  com.dotmarketing.common.db.DotConnect - Executing update permission_reference set asset_id = 'TEMP_INODE' where asset_id = '33888b6f-7a8e-4069-b1b6-5c1aa9d0a48d'
2015-06-17 15:42:48,227 INFO  com.dotmarketing.common.db.DotConnect - Executing delete from structure where inode = '33888b6f-7a8e-4069-b1b6-5c1aa9d0a48d'
2015-06-17 15:42:48,244 ERROR com.dotmarketing.db.HibernateUtil - ---------- DotHibernate: error on rollbackTransaction ---------------
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Can't call rollback when autocommit=true
2015-06-17 15:42:48,244 ERROR com.dotcms.rest.IntegrityResource - Error fixing structures conflicts from remote
com.dotmarketing.exception.DotDataException: Cannot delete or update a parent row: a foreign key constraint fails (`dotcms3`.`folder`, CONSTRAINT `fk_folder_file_structure_type` FOREIGN KEY (`default_file_type`) REFERENCES `structure` (`inode`))
	at com.dotcms.rest.IntegrityUtil.fixStructures(IntegrityUtil.java:1554)
	at com.dotcms.rest.IntegrityUtil.fixConflicts(IntegrityUtil.java:1175)
	at com.dotcms.rest.IntegrityUtil.fixConflicts(IntegrityUtil.java:999)
	at com.dotcms.rest.IntegrityResource.fixConflictsFromRemote(IntegrityResource.java:940)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.dotcms.repackage.com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.dotcms.repackage.com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.dotcms.repackage.com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.dotcms.repackage.com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
	at com.dotcms.repackage.com.sun.jersey.server.impl.uri
```

**Comment by jtesser** [comment]
For the devs here I am sure this is a I started on an old version and have upgraded issue.  Lets address
