### ISSUE TITLE
Upgrade from 1.9 to 3.2.4 fails

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#7984]
The **Task00010CheckAnonymousUser** task is currently checking if the anonymous role exist using the role name, this needs to be change it to use the role key.

```
[24/07/15 08:09:23:886 CST] FATAL startup.StartupTasksExecutor: Unable to execute the upgrade task : Task00010CheckAnonymousUser
com.dotmarketing.exception.DotDataException: Duplicated role key.
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:234)
	at com.dotmarketing.startup.runalways.Task00010CheckAnonymousUser.executeUpgrade(Task00010CheckAnonymousUser.java:75)
	at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:214)
	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:116)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4901)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5188)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1069)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1719)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Duplicated role key.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1522)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1716)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:332)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:197)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:197)
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:564)
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:486)
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:232)
	... 19 more
```

**Comment by erickgonzalez** [comment]
PR https://github.com/dotCMS/core/pull/7986

**Comment by shayngr** [comment]
Fix is working. Tested on: 
Release candidate for 3.2.4 (http://dotcms.com/physical_downloads/test/dotcms_3.2.4.zip)
Win7 Pro SP1
SQLServer 2012
Firefox
