### ISSUE TITLE
Running ES Externally - Issue with Repackaging

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#8046]
Running elasticsearch externally
---
Download Elasticsearch 1.4.2
https://www.elastic.co/downloads/past-releases/elasticsearch-1-4-2

config/elasticsearch.yml

```
cluster.name: dotCMSContentIndex_3x
```

./bin/elasticsearch

dotcms-config-cluster.properties
```
CLUSTER_AUTOWIRE=false
es.node.master=false
es.node.data=false

es.discovery.zen.ping.unicast.hosts=localhost:9300     <---------ip/port of the external 
```

One issue due to repackaging:

If you set the dotCMS node to act as a data/master node alongside the standalone Elasticsearch and try to update the replicas, you get an error.  ES passes a serialized message to the ES cluster, and in dotCMS that the class that is being serialized is not found, which makes sense because the ES library in dotCMS has been repackaged.  As a hack, I solved this by dropping the ES distro's elasticsearch-1.4.2.jar into dotCMS WEB-INF/lib

Here is the Error:

```
com.dotcms.repackage.org.elasticsearch.transport.RemoteTransportException: Failed to deserialize exception response from stream
Caused by: com.dotcms.repackage.org.elasticsearch.transport.TransportSerializationException: Failed to deserialize exception response from stream
	at com.dotcms.repackage.org.elasticsearch.transport.netty.MessageChannelHandler.handlerResponseError(MessageChannelHandler.java:173)
	at com.dotcms.repackage.org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:125)
	at com.dotcms.repackage.org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at com.dotcms.repackage.org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at com.dotcms.repackage.org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at com.dotcms.repackage.org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at com.dotcms.repackage.org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at com.dotcms.repackage.org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at com.dotcms.repackage.org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at com.dotcms.repackage.org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at com.dotcms.repackage.org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at com.dotcms.repackage.org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at com.dotcms.repackage.org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at com.dotcms.repackage.org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at com.dotcms.repackage.org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at com.dotcms.repackage.org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at com.dotcms.repackage.org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
	at com.dotcms.repackage.org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at com.dotcms.repackage.org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at com.dotcms.repackage.org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at com.dotcms.repackage.org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.InvalidClassException: failed to read class descriptor
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1603)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at com.dotcms.repackage.org.elasticsearch.transport.netty.MessageChannelHandler.handlerResponseError(MessageChannelHandler.java:171)
	... 23 more
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.transport.RemoteTransportException
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1305)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
	at com.dotcms.repackage.org.elasticsearch.common.io.ThrowableObjectInputStream.loadClass(ThrowableObjectInputStream.java:93)
	at com.dotcms.repackage.org.elasticsearch.common.io.ThrowableObjectInputStream.readClassDescriptor(ThrowableObjectInputStream.java:67)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1601)
```

**Comment by jtesser** [comment]
https://www.flowdock.com/app/dotcms/support/threads/9zqAPUBeV9_BzTZ8tPJSx75brUL
https://www.flowdock.com/app/dotcms/support/threads/NSiwBj8UdUFJ9BHX53dw2DzTFC4

**Comment by jtesser** [comment]
We need to discuss autoscale here

**Comment by jtesser** [comment]
Need to message using the Notification API here.

**Comment by jtesser** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/64
