### ISSUE TITLE
ReST Portlets throwing IllegalStateException in Master-3.5: 'getWriter()' already called for response.

### ISSUE THREAD

**Issue by ggranum** [dotCMS/core#8072]
This is probably caused by either the introduction of the actionlet servlet filter, or the upgrade we made to the Jersey libs.

## Repro steps
  * Start the server, apply a trial license, log in as admin.
  * Navigate to System -> Roles and Tabs
  * Select 'System -> Administrator' from the left-hand tree panel
  * Select the 'CMS Tabs' tab to activate the menu settings panel.
  * Click on 'System' to bring up edit dialog.
  * From the 'tools' dropdown, select 'Rest Example Portlet' and click Add.
  * Verify that the tool has been added to menu by scrolling to the bottom of the panel.
  * Click Save to save and dismiss the edit dialog.
  * Refresh the page.
  * Activate the System Menu. 'Rest Example Portlet' should be present as the last option in the menu. 
  * Click the 'Rest Example Portlet' menu item. A blank child panel will be the result.
  * Check your log messages to see the stack trace.

## Stack 

```bash
2015-08-12 09:57:02,018 WARN  com.dotcms.repackage.org.apache.struts.util.RequestUtils - No FormBeanConfig found under ''
12-Aug-2015 09:57:11.653 WARNING [url:GET//demo.dotcms.com/api/portlet/REST_EXAMPLE_PORTLET/ | lang:1 | ip:0:0:0:0:0:0:0:1 | Admin:false | start:08-12-2015 09:15:25 PDT  ref:http://localhost:8080/c/portal/layout?p_l_id=a8e430e3-8010-40cf-ade1-5978e61241a8&p_p_id=EXT_ROLE_ADMIN&p_p_action=0&&dm_rlout=1&r=1439398580563  ?r=804301135] com.dotcms.repackage.org.glassfish.jersey.servlet.WebComponent.filterFormParameters A servlet request to the URI http://localhost:8080/api/portlet/REST_EXAMPLE_PORTLET/?r=804301135 contains form parameters in the request body but the request body has been consumed by the servlet or a servlet filter accessing the request parameters. Only resource methods using @FormParam will work as expected. Resource methods consuming the request body by other means will not work as expected.
12-Aug-2015 09:57:11.704 SEVERE [url:GET//demo.dotcms.com/api/portlet/REST_EXAMPLE_PORTLET/ | lang:1 | ip:0:0:0:0:0:0:0:1 | Admin:false | start:08-12-2015 09:15:25 PDT  ref:http://localhost:8080/c/portal/layout?p_l_id=a8e430e3-8010-40cf-ade1-5978e61241a8&p_p_id=EXT_ROLE_ADMIN&p_p_action=0&&dm_rlout=1&r=1439398580563  ?r=804301135] com.dotcms.repackage.org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse Error while closing the output stream in order to commit response.
 java.lang.IllegalStateException: getWriter() has already been called for this response
	at org.apache.catalina.connector.Response.getOutputStream(Response.java:544)
	at org.apache.catalina.connector.ResponseFacade.getOutputStream(ResponseFacade.java:195)
	at javax.servlet.ServletResponseWrapper.getOutputStream(ServletResponseWrapper.java:100)
	at javax.servlet.ServletResponseWrapper.getOutputStream(ServletResponseWrapper.java:100)
	at com.dotcms.repackage.org.glassfish.jersey.servlet.internal.ResponseWriter.writeResponseStatusAndHeaders(ResponseWriter.java:176)
	at com.dotcms.repackage.org.glassfish.jersey.server.ServerRuntime$Responder$1.getOutputStream(ServerRuntime.java:654)
	at com.dotcms.repackage.org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:200)
	at com.dotcms.repackage.org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer(CommittingOutputStream.java:305)
	at com.dotcms.repackage.org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:261)
	at com.dotcms.repackage.org.glassfish.jersey.message.internal.CommittingOutputStream.close(CommittingOutputStream.java:276)
	at com.dotcms.repackage.org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:839)
	at com.dotcms.repackage.org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:412)
	at com.dotcms.repackage.org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:737)
	at com.dotcms.repackage.org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:421)
	at com.dotcms.repackage.org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:411)
	at com.dotcms.repackage.org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308)
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at com.dotcms.repackage.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at com.dotcms.repackage.org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:288)
	at com.dotcms.repackage.org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1110)
	at com.dotcms.repackage.org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:401)
	at com.dotcms.repackage.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
	at com.dotcms.repackage.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:335)
	at com.dotcms.repackage.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:222)
	at com.dotcms.rest.servlet.ReloadableServletContainer.service(ReloadableServletContainer.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:216)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:300)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)


```

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/8097

Tested on Tomcat, Jboss, Websphere and Weblogic.
