### ISSUE TITLE
Content cannot be deleted using a worflow task

### ISSUE THREAD

**Issue by monzonj** [dotCMS/core#8124]
Any content that is archived should be able to be deleted. This usually works, but it doesn't if the DELETE command comes from a workflow sub-step 

Error:

[07/09/15 13:15:08:943 CEST] INFO business.ESContentletAPIImpl: UserId : dotcms.org.2831 : delete : User trying to delete the following contents[76bf2904-ae7b-44a3-b690-148f5d656a9b]
[07/09/15 13:15:08:975 CEST] WARN web.ContentletWebAPIImpl: com.dotmarketing.portlets.workflows.business.DotWorkflowException
com.dotmarketing.portlets.workflows.business.DotWorkflowException
at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireWorkflowPostCheckin(WorkflowAPIImpl.java:833)
at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireWorkflowNoCheckin(WorkflowAPIImpl.java:862)
at com.dotmarketing.portlets.contentlet.business.web.ContentletWebAPIImpl._saveWebAsset(ContentletWebAPIImpl.java:395)
at com.dotmarketing.portlets.contentlet.business.web.ContentletWebAPIImpl.saveContent(ContentletWebAPIImpl.java:142)
at com.dotmarketing.portlets.contentlet.ajax.ContentletAjax.saveContent(ContentletAjax.java:1402)
at sun.reflect.GeneratedMethodAccessor2313.invoke(Unknown Source)

**Comment by monzonj** [comment]
This issue is most likely related to: https://github.com/dotCMS/core/issues/7878
