### ISSUE TITLE
Enhancement: Improve logging in FolderAPIImpl class

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#8804]
Reproduced in 3.3 and 3.3.1. 

Depending on how permissions are set, some users may not have access to read specific assets or folders. However, the log messages in FolderAPIImpl class does not help to figure out which user had a specific problem with permissions over a folder

```
[23/03/16 16:06:16:211 CDT] ERROR business.FileAssetAPIImpl: User com.liferay.portal.model.User@2c2ff93e does not have permission to read xxxxxxx
    com.dotmarketing.exception.DotSecurityException: User com.liferay.portal.model.User@2c2ff93e does not have permission to read system folder
    at com.dotmarketing.portlets.folders.business.FolderAPIImpl.find(FolderAPIImpl.java:501) ~[dotcms_3.3_1bbd913.jar:?]
```

Also, during the execution of Migrating pages as contents, we have noticed on upgraded clients that, once a page has become orphaned (it exists in DB but its parent folder doesn't), we don't have a good way to figure out the exact root cause of the problem.

```
[22/03/16 00:10:23:737 EDT] ERROR menubuilders.RefreshMenus: User com.liferay.portal.model.User@cb1c722f does not have permission to read null
    com.dotmarketing.exception.DotSecurityException: User com.liferay.portal.model.User@cb1c722f does not have permission to read null
    at com.dotmarketing.portlets.folders.business.FolderAPIImpl.findParentFolder(FolderAPIImpl.java:141) ~[dotcms_3.3_1bbd913.jar:?]
```

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/8807
