### ISSUE TITLE
Force Close Connection in InitServlet 

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#8843]
Related to https://github.com/dotCMS/enterprise-2.x/issues/359 and Support ticket https://my.dotcms.com/tickets/detail.dot?id=d9992bb7-349f-4e97-91d3-2aeacfc5aa47 

Currently, the InitServlet class has a half-way implementation of force-closing leaked connections. 

Stacktrace.
```

####<Apr 6, 2016 10:44:30 PM EDT> <Info> <Health> <nj09mhf0681.mhf.mhc> <ids_1> <weblogic.GCMonitor> <<anonymous>> <> <> <1459997070772> <BEA-310002> <94% of the total memory in the server is free>
####<Apr 6, 2016 10:44:48 PM EDT> <Warning> <JDBC> <nj09mhf0681.mhf.mhc> <ids_1> <[ACTIVE] ExecuteThread: '5' for queue: 'weblogic.kernel.Default (self-tuning)'> <<WLS Kernel>> <> <> <1459997088416> <BEA-001153> <Forcibly releasing inactive connection "weblogic.jdbc.wrapper.PoolConnection_oracle_jdbc_driver_T4CConnection@ff27" back into the connection pool "dotcms_pool_dev2", currently reserved by: java.lang.Exception
        at weblogic.jdbc.common.internal.ConnectionEnv.setup(ConnectionEnv.java:318)
        at weblogic.common.resourcepool.ResourcePoolImpl.reserveResource(ResourcePoolImpl.java:344)
        at weblogic.common.resourcepool.ResourcePoolImpl.reserveResource(ResourcePoolImpl.java:322)
        at weblogic.jdbc.common.internal.ConnectionPool.reserve(ConnectionPool.java:438)
        at weblogic.jdbc.common.internal.ConnectionPool.reserve(ConnectionPool.java:317)
        at weblogic.jdbc.common.internal.MultiPool.searchLoadBalance(MultiPool.java:310)
        at weblogic.jdbc.common.internal.MultiPool.findPool(MultiPool.java:178)
        at weblogic.jdbc.common.internal.ConnectionPoolManager.reserve(ConnectionPoolManager.java:87)
        at weblogic.jdbc.common.internal.ConnectionPoolManager.reserve(ConnectionPoolManager.java:106)
        at weblogic.jdbc.pool.Driver.connect(Driver.java:149)
        at weblogic.jdbc.jts.Driver.getNonTxConnection(Driver.java:652)
        at weblogic.jdbc.jts.Driver.connect(Driver.java:127)
        at weblogic.jdbc.common.internal.RmiDataSource.getConnection(RmiDataSource.java:355)
        at com.dotmarketing.db.DbConnectionFactory.getConnection(DbConnectionFactory.java:87)
        at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:488)
        at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:231)
        at com.dotmarketing.common.db.DotConnect.loadObjectResults(DotConnect.java:862)
        at com.dotcms.enterprise.cluster.ServerFactoryImpl.getServer(SourceFile:80)
        at com.dotcms.cluster.business.ServerAPIImpl.getServer(ServerAPIImpl.java:38)
        at com.dotcms.enterprise.license.LicenseManager.h(SourceFile:525)
        at com.dotcms.enterprise.license.LicenseManager.getDisplayServerId(SourceFile:547)
        at com.dotcms.enterprise.LicenseUtil.getDisplayServerId(SourceFile:96)
        at com.dotmarketing.servlets.InitServlet$InitThread.run(InitServlet.java:385)
```

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/8844
