### ISSUE TITLE
Force Close DB Connections in URLMapFilter

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#8866]
Reported by client via Support ticket https://my.dotcms.com/tickets/detail.dot?id=d9992bb7-349f-4e97-91d3-2aeacfc5aa47

Related to dotCMS/enterprise-2.x#359 and #8843 

Database connection leaks were reported by client running 3.3.1 under Weblogic 12c Application Server. Open connections for retrieving VanityURLs on the URLMapFilter are not being closed properly and, depending on the debug params set at JDBC Connector Pool, these DB connections cannot be recovered.

Stacktrace:

```
####<Apr 8, 2016 11:25:26 AM EDT> <Warning> <JDBC> <nj09mhf0681.mhf.mhc> <ids_1> <[ACTIVE] ExecuteThread: '7' for queue: 'weblogic.kernel.Default (self-tuning)'> <<WLS Kernel>> <> <> <1460129126904> <BEA-001153> <Forcibly releasing inactive connection "weblogic.jdbc.wrapper.PoolConnection_oracle_jdbc_driver_T4CConnection@98cf" back into the connection pool "dotcms_pool_dev2", currently reserved by: java.lang.Exception
        at weblogic.jdbc.common.internal.ConnectionEnv.setup(ConnectionEnv.java:318)
        at weblogic.common.resourcepool.ResourcePoolImpl.reserveResource(ResourcePoolImpl.java:344)
        at weblogic.common.resourcepool.ResourcePoolImpl.reserveResource(ResourcePoolImpl.java:322)
        at weblogic.jdbc.common.internal.ConnectionPool.reserve(ConnectionPool.java:438)
        at weblogic.jdbc.common.internal.ConnectionPool.reserve(ConnectionPool.java:317)
        at weblogic.jdbc.common.internal.MultiPool.searchLoadBalance(MultiPool.java:310)
        at weblogic.jdbc.common.internal.MultiPool.findPool(MultiPool.java:178)
        at weblogic.jdbc.common.internal.ConnectionPoolManager.reserve(ConnectionPoolManager.java:87)
        at weblogic.jdbc.common.internal.ConnectionPoolManager.reserve(ConnectionPoolManager.java:106)
        at weblogic.jdbc.pool.Driver.connect(Driver.java:149)
        at weblogic.jdbc.jts.Driver.getNonTxConnection(Driver.java:652)
        at weblogic.jdbc.jts.Driver.connect(Driver.java:127)
        at weblogic.jdbc.common.internal.RmiDataSource.getConnection(RmiDataSource.java:355)
        at com.dotmarketing.db.DbConnectionFactory.getConnection(DbConnectionFactory.java:87)
        at com.dotmarketing.db.HibernateUtil.getSession(HibernateUtil.java:630)
        at com.dotmarketing.db.HibernateUtil.setQuery(HibernateUtil.java:186)
        at com.dotmarketing.portlets.virtuallinks.factories.VirtualLinkFactory.getVirtualLinkByURL(VirtualLinkFactory.java:43)
        at com.dotmarketing.cache.VirtualLinksCache.getPathFromCache(VirtualLinksCache.java:55)
        at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:121)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
        at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:174)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
        at com.mhf.region.resolver.filters.PersonalizedSiteForHostFilter.doFilter(PersonalizedSiteForHostFilter.java:121)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
        at com.mhf.region.resolver.filters.GeoLocationBasedRedirectionForHostFilter.doFilter(GeoLocationBasedRedirectionForHostFilter.java:117)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
        at com.mhf.region.resolver.filters.ConfigureLanguageForHostFilter.doFilter(ConfigureLanguageForHostFilter.java:65)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
        at com.mhf.region.resolver.filters.LogFilter.doFilter(LogFilter.java:73)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
        at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:93)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
        at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
        at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
        at weblogic.servlet.internal.RequestEventsFilter.doFilter(RequestEventsFilter.java:27)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.doIt(WebAppServletContext.java:3684)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3650)
        at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
        at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:121)
        at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2268)
        at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2174)
        at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1446)
        at weblogic.work.ExecuteThread.execute(ExecuteThread.java:201)
        at weblogic.work.ExecuteThread.run(ExecuteThread.java:173)
```

**Comment by dsilvam** [comment]
related to https://github.com/dotCMS/core/issues/8566

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/8869

**Comment by kannamraju** [comment]
Hey guys,
Any update on when this would be resolved as we are using 3.2.3 version and facing the same issue. We are constantly facing the issue of site outages because of this issue.
Thanks,
Kumar. 
http://www.prometheanworld.com

**Comment by dsilvam** [comment]
new PR for 3.6: https://github.com/dotCMS/core/pull/9295

**Comment by jgambarios** [comment]
Pull request rejected:

> 
Closed as we don't think this is the proper solution, we should not need to close the hibernate session inside a Filter, the HibernateSessionsListener should take care of the session and if it is not doing it we need to find out why: https://github.com/dotCMS/core/blob/master-3.7/src/com/dotmarketing/listeners/HibernateSessionsListener.java#L19-L29

Marking this ticket for 3.7 in order to find a proper fix.
