### ISSUE TITLE
Issue after upgrading from dotCMS 3.3 to dotCMS 3.3.2

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#8939]
we have an issue after upgrading from dotCMS 3.3 to 3.3.2. 
On the contact page we have a "Message reason" dropdown built from dotCMS content.
The content is named "DropdownText". The dropdown is populated in a vtl file:

 <div class="ym-fbox-text">
                        <label for="message">Message reason</label>
                        <select id="message" name="message" class="required select" data-bind="{value: reason}">
                            <option name="disabled" value="disabled" disabled="disabled" selected="selected">Please select</option>
							#foreach($con in $dotcontent.pull("+structureName:DropdownText +(conhost:SYSTEM_HOST) +DropdownText.dropdownCode:contact",0,"DropdownText.text asc"))
							<option value="$con.text">$con.text</option>
							#end
                        </select>
                    </div>

The dotCMS log shows this error, and the dropdown is empty:

[25/04/16 10:56:06:382 BST] ERROR util.SQLUtil: Invalid or pernicious sql parameter passed in : DropdownText
com.dotmarketing.business.DotStateException: Invalid or pernicious sql parameter passed in : DropdownText
	at com.dotmarketing.common.util.SQLUtil.sanitizeParameter(SQLUtil.java:201) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotmarketing.portlets.structure.factories.StructureFactory.getStructureByVelocityVarName(StructureFactory.java:109) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotmarketing.cache.ContentTypeCacheImpl.getStructureByVelocityVarName(ContentTypeCacheImpl.java:135) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotmarketing.cache.FieldsCache.getFieldsByStructureVariableName(FieldsCache.java:82) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.translateQuerySortBy(ESContentFactoryImpl.java:1644) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.translateQuery(ESContentFactoryImpl.java:1600) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.indexSearch(ESContentFactoryImpl.java:1248) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.searchIndex(ESContentletAPIImpl.java:665) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.search(ESContentletAPIImpl.java:537) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.search(ESContentletAPIImpl.java:529) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.search(ContentletAPIInterceptor.java:1561) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotmarketing.viewtools.content.util.ContentUtils.pull(ContentUtils.java:231) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotmarketing.viewtools.content.ContentTool.pull(ContentTool.java:164) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotmarketing.viewtools.content.ContentTool.pull(ContentTool.java:157) [dotcms_3.3.2_fb28b98f.jar:?]
	at sun.reflect.GeneratedMethodAccessor364.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:178) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:572) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:321) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:211) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:330) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.Template.merge(Template.java:362) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.Template.merge(Template.java:265) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotmarketing.viewtools.VelocityWebUtil.mergeTemplate(VelocityWebUtil.java:87) [dotcms_3.3.2_fb28b98f.jar:?]
	at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:178) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:374) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:218) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:308) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:226) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:211) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:330) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.Template.merge(Template.java:362) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.Template.merge(Template.java:265) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotmarketing.viewtools.VelocityWebUtil.mergeTemplate(VelocityWebUtil.java:87) [dotcms_3.3.2_fb28b98f.jar:?]
	at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:178) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:572) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTExpression.value(ASTExpression.java:71) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTSetDirective.render(ASTSetDirective.java:150) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:330) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.Template.merge(Template.java:362) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.Template.merge(Template.java:265) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotmarketing.viewtools.VelocityWebUtil.mergeTemplate(VelocityWebUtil.java:87) [dotcms_3.3.2_fb28b98f.jar:?]
	at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:178) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:374) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:218) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:308) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:226) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:211) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:218) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:308) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:226) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:211) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:423) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:211) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:330) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.Template.merge(Template.java:362) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.Template.merge(Template.java:265) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotmarketing.viewtools.VelocityWebUtil.mergeTemplate(VelocityWebUtil.java:87) [dotcms_3.3.2_fb28b98f.jar:?]
	at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:178) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:374) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:330) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:106) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:218) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:308) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:226) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:211) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:330) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.Template.merge(Template.java:362) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.Template.merge(Template.java:265) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotmarketing.viewtools.VelocityWebUtil.mergeTemplate(VelocityWebUtil.java:87) [dotcms_3.3.2_fb28b98f.jar:?]
	at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:372) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:361) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:178) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:285) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:374) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:330) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.Template.merge(Template.java:362) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.velocity.Template.merge(Template.java:265) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotmarketing.velocity.VelocityServlet.doLiveMode(VelocityServlet.java:523) [dotcms_3.3.2_fb28b98f.jar:?]
	at com.dotmarketing.velocity.VelocityServlet.service(VelocityServlet.java:216) [dotcms_3.3.2_fb28b98f.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at nl.isaac.dotcms.davosselfservice.filter.MiddlewareCleanupFilter.doFilter(MiddlewareCleanupFilter.java:51) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:720) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318) [catalina.jar:8.0.33]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:209) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:300) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:174) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at nl.isaac.dotcms.davosselfservice.filter.LogDeeplinkFilter.doFilter(LogDeeplinkFilter.java:66) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at nl.isaac.dotcms.davosselfservice.filter.KeepAliveFilter.doFilter(KeepAliveFilter.java:36) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at nl.isaac.dotcms.davosselfservice.filter.RoutingFilter.doFilter(RoutingFilter.java:77) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at nl.isaac.dotcms.davosselfservice.filter.SelfServiceSessionInitialisationFilter.doFilter(SelfServiceSessionInitialisationFilter.java:32) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at nl.isaac.dotcms.davosselfservice.filter.LoginFilter.doFilter(LoginFilter.java:107) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at nl.isaac.dotcms.davosselfservice.filter.MiddlewareCleanupFilter.doFilter(MiddlewareCleanupFilter.java:51) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at nl.isaac.dotcms.davosselfservice.filter.DisableWebsiteFilter.doFilter(DisableWebsiteFilter.java:123) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at nl.isaac.dotcms.davosselfservice.filter.RequestStoringFilter.doFilter(RequestStoringFilter.java:28) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146) [dotcms_3.3.2_fb28b98f.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.33]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) [catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522) [catalina.jar:8.0.33]
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:868) [tomcat-coyote.jar:8.0.33]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) [tomcat-coyote.jar:8.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502) [tomcat-coyote.jar:8.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458) [tomcat-coyote.jar:8.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_77]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_77]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.33]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]

However when I refresh the page I see no error, and the dropdown is populated.
When I empty the dotCMS cache, I get the error again.

I have added a screenshot of the content which is rendered.

whats going wrong here, this must be a byproduct of the security fix for http://dotcms.com/security/SI-35 ?

**Comment by oarrietadotcms** [comment]
The reason behind this false positive is the new [Evil SQL Words](https://github.com/dotCMS/core/blob/master-3.3/src/com/dotmarketing/common/util/SQLUtil.java#L30-L32), in this specific case "DropdownText" contains "drop". We need blank spaces in some of this Evil Words, i.e. "drop " instead "drop".

The VTL keeps working because [we are returning a new Structure](https://github.com/dotCMS/core/blob/master-3.3/src/com/dotmarketing/portlets/structure/factories/StructureFactory.java#L111) in case the parameter contains an Evil SQL Word. And then that structure is [added to the cache](https://github.com/dotCMS/core/blob/master-3.3/src/com/dotmarketing/cache/ContentTypeCacheImpl.java#L135).

I will need confirmation from @brentgriffin or @wezell that you want to add the blank spaces to the Evil SQL Words.

**Comment by wezell** [comment]
@oarrietadotcms looks like there are a number of evil words that need spaces after them.  Maybe we need to be smarter here?

I'd like to avoid regexes if that is possible (might not be), but there are some words that would start a sql statement and have spaces after them and some that would be in the middle of a sql statement and have spaces before and after them.

**Comment by brentgriffin** [comment]
Agreed - clearly we already encountered this issue with "as ", "not ", and "set "

**Comment by oarrietadotcms** [comment]
Please let me know what do you think about this list with blankspaces: 

**private static final Set<String> EVIL_SQL_WORDS = ImmutableSet.of( "select ", "insert ", "delete ", "update ", "replace ", "create ", " distinct ", " like ", " and ", " or ", " limit ", " group ", " order ", "as ", " count ", "drop ", "alter ", "truncate ", "declare ", " where ", "exec ", "--", " procedure ", "pg_", "lock ", "unlock ", "write ", " engine ", "null", "not ", " mode ", "set ", ";" );**

**Comment by wezell** [comment]
Looks good.  Maybe " as " but not sure.

**Comment by oarrietadotcms** [comment]
Yes, makes sense, I will test this new list and create the PR.

**Comment by john-thomas-dotcms** [comment]
The SqlResultsTool is only looking for the following strings (in what could potentially be query strings created from user-supplied input): "DELETE", "DROP", "TRUNCATE", "ALTER", "CREATE" and "UPDATE" (no spaces in any of them).

https://github.com/dotCMS/core/blob/master-3.5/src/com/dotmarketing/viewtools/SQLResultsViewTool.java#L265-267

Should we update the restricted query terms in that tool as well, or maybe create a single source where we can keep the restricted query terms the same for both?

**Comment by oarrietadotcms** [comment]
PR for 3.3: https://github.com/dotCMS/core/pull/8942
PR for 3.5: https://github.com/dotCMS/core/pull/8943

Also I committed directly to master for Support repo.

**Comment by oarrietadotcms** [comment]
@wezell Let me know what do you think about @john-thomas-dotcms comment. I can create an issue for 3.5.1 and work on that if you want.

**Comment by wezell** [comment]
@oarrietadotcms - I think they are different issues - and would take different lists and checks.  The SQL tool should allow you to run fully formed select queries and is just trying to prevent a few harmful cases.  The Sanitizer evil words are more for checking individual parameters rather than whole queries.

**Comment by monzonj** [comment]
The way to sanitize SQL is not by preventing the user from using any magic keyword. 

How to sanitize properly: http://bobby-tables.com/java.html 

Basically use PreparedStatement in all your queries

**Comment by bryanboza** [comment]
Fixed, tested on from dotcms_3.3 to master 3.5 // Postgres // FF...

**Comment by bryanboza** [comment]
@jgambarios Maybe we need the same fix to master-3.6 // Please take look...

**Comment by jgambarios** [comment]
It is already in master-3.6.
