### ISSUE TITLE
Size Quartz thread pool more intelligently

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#9111]
Currently, each Quartz pool allocates 50 threads by default for a total of 150 Quartz threads no matter the server size. This creates unnecessary thread contention and performance degradation. A more sane size would be for each pool to init with # threads determined by # of CPUs (8 CPUs = 8 Quartz threads per pool).

**Comment by chrismccracken** [comment]
```
150 threads with this stack:
"DotMarketingQuartzExclusiveScheduler_Worker-1": awaiting notification on [0x0000000244581850]
"DotMarketingQuartzExclusiveScheduler_Worker-10": awaiting notification on [0x0000000250f79990]
"DotMarketingQuartzExclusiveScheduler_Worker-11": awaiting notification on [0x000000024acc50d8]
"DotMarketingQuartzExclusiveScheduler_Worker-12": awaiting notification on [0x0000000243d092f0]
"DotMarketingQuartzExclusiveScheduler_Worker-13": awaiting notification on [0x000000024d7ce678]
"DotMarketingQuartzExclusiveScheduler_Worker-14": awaiting notification on [0x0000000243e4cee0]
"DotMarketingQuartzExclusiveScheduler_Worker-15": awaiting notification on [0x000000024b20be38]
"DotMarketingQuartzExclusiveScheduler_Worker-16": awaiting notification on [0x00000002488fbd20]
"DotMarketingQuartzExclusiveScheduler_Worker-17": awaiting notification on [0x000000024a8ece50]
"DotMarketingQuartzExclusiveScheduler_Worker-18": awaiting notification on [0x000000024ba70090]
"DotMarketingQuartzExclusiveScheduler_Worker-19": awaiting notification on [0x00000002417af908]
"DotMarketingQuartzExclusiveScheduler_Worker-2": awaiting notification on [0x0000000244472858]
"DotMarketingQuartzExclusiveScheduler_Worker-20": awaiting notification on [0x000000024d7ce4f0]
"DotMarketingQuartzExclusiveScheduler_Worker-21": awaiting notification on [0x0000000241827400]
"DotMarketingQuartzExclusiveScheduler_Worker-22": awaiting notification on [0x0000000243d09168]
"DotMarketingQuartzExclusiveScheduler_Worker-23": awaiting notification on [0x000000024d7ce188]
"DotMarketingQuartzExclusiveScheduler_Worker-24": awaiting notification on [0x000000024b0d8a18]
"DotMarketingQuartzExclusiveScheduler_Worker-25": awaiting notification on [0x00000002445816c8]
"DotMarketingQuartzExclusiveScheduler_Worker-26": awaiting notification on [0x000000024acc4f50]
"DotMarketingQuartzExclusiveScheduler_Worker-27": awaiting notification on [0x0000000243f0f760]
"DotMarketingQuartzExclusiveScheduler_Worker-28": awaiting notification on [0x0000000243d08fe0]
"DotMarketingQuartzExclusiveScheduler_Worker-29": awaiting notification on [0x00000002417af780]
"DotMarketingQuartzExclusiveScheduler_Worker-3": awaiting notification on [0x00000002447a3c88]
"DotMarketingQuartzExclusiveScheduler_Worker-30": awaiting notification on [0x0000000252a7c4a0]
"DotMarketingQuartzExclusiveScheduler_Worker-31": awaiting notification on [0x000000024ba6ff08]
"DotMarketingQuartzExclusiveScheduler_Worker-32": awaiting notification on [0x0000000241827278]
"DotMarketingQuartzExclusiveScheduler_Worker-33": awaiting notification on [0x000000024d7ce000]
"DotMarketingQuartzExclusiveScheduler_Worker-34": awaiting notification on [0x00000002444726d0]
"DotMarketingQuartzExclusiveScheduler_Worker-35": awaiting notification on [0x0000000243d08e58]
"DotMarketingQuartzExclusiveScheduler_Worker-36": awaiting notification on [0x0000000244581540]
"DotMarketingQuartzExclusiveScheduler_Worker-37": awaiting notification on [0x000000024d06e3f8]
"DotMarketingQuartzExclusiveScheduler_Worker-38": awaiting notification on [0x000000024ba6fd80]
"DotMarketingQuartzExclusiveScheduler_Worker-39": awaiting notification on [0x0000000250f79808]
"DotMarketingQuartzExclusiveScheduler_Worker-4": awaiting notification on [0x00000002446589c0]
"DotMarketingQuartzExclusiveScheduler_Worker-40": awaiting notification on [0x00000002418270f0]
"DotMarketingQuartzExclusiveScheduler_Worker-41": awaiting notification on [0x000000024a8eccc8]
"DotMarketingQuartzExclusiveScheduler_Worker-42": awaiting notification on [0x000000024af9b638]
"DotMarketingQuartzExclusiveScheduler_Worker-43": awaiting notification on [0x0000000250b7b678]
"DotMarketingQuartzExclusiveScheduler_Worker-44": awaiting notification on [0x00000002445813b8]
"DotMarketingQuartzExclusiveScheduler_Worker-45": awaiting notification on [0x0000000243f0f5d8]
"DotMarketingQuartzExclusiveScheduler_Worker-46": awaiting notification on [0x0000000243d08cd0]
"DotMarketingQuartzExclusiveScheduler_Worker-47": awaiting notification on [0x000000024b0d8890]
"DotMarketingQuartzExclusiveScheduler_Worker-48": awaiting notification on [0x00000002515b2350]
"DotMarketingQuartzExclusiveScheduler_Worker-49": awaiting notification on [0x0000000241826f68]
"DotMarketingQuartzExclusiveScheduler_Worker-5": awaiting notification on [0x0000000243d09478]
"DotMarketingQuartzExclusiveScheduler_Worker-50": awaiting notification on [0x00000002447a3978]
"DotMarketingQuartzExclusiveScheduler_Worker-6": awaiting notification on [0x00000002417afa90]
"DotMarketingQuartzExclusiveScheduler_Worker-7": awaiting notification on [0x000000024b56db60]
"DotMarketingQuartzExclusiveScheduler_Worker-8": awaiting notification on [0x00000002447a3b00]
"DotMarketingQuartzExclusiveScheduler_Worker-9": awaiting notification on [0x0000000252a7c628]
"DotMarketingQuartzLocalScheduler_Worker-1": awaiting notification on [0x000000024ba6f8b8]
"DotMarketingQuartzLocalScheduler_Worker-10": awaiting notification on [0x0000000252a0c9e0]
"DotMarketingQuartzLocalScheduler_Worker-11": awaiting notification on [0x000000024af9ae90]
"DotMarketingQuartzLocalScheduler_Worker-12": awaiting notification on [0x0000000252a0e310]
"DotMarketingQuartzLocalScheduler_Worker-13": awaiting notification on [0x0000000244471f28]
"DotMarketingQuartzLocalScheduler_Worker-14": awaiting notification on [0x0000000243d08218]
"DotMarketingQuartzLocalScheduler_Worker-15": awaiting notification on [0x000000024acc4ab8]
"DotMarketingQuartzLocalScheduler_Worker-16": awaiting notification on [0x000000024b20bb28]
"DotMarketingQuartzLocalScheduler_Worker-17": awaiting notification on [0x000000024ba6f730]
"DotMarketingQuartzLocalScheduler_Worker-18": awaiting notification on [0x0000000243e4c5b0]
"DotMarketingQuartzLocalScheduler_Worker-19": awaiting notification on [0x0000000250c80898]
"DotMarketingQuartzLocalScheduler_Worker-2": awaiting notification on [0x000000024a8ec9b8]
"DotMarketingQuartzLocalScheduler_Worker-20": awaiting notification on [0x0000000244471da0]
"DotMarketingQuartzLocalScheduler_Worker-21": awaiting notification on [0x000000024b0d8270]
"DotMarketingQuartzLocalScheduler_Worker-22": awaiting notification on [0x000000024a8ec830]
"DotMarketingQuartzLocalScheduler_Worker-23": awaiting notification on [0x000000024d7cdb68]
"DotMarketingQuartzLocalScheduler_Worker-24": awaiting notification on [0x0000000243d08090]
"DotMarketingQuartzLocalScheduler_Worker-25": awaiting notification on [0x0000000241851e58]
"DotMarketingQuartzLocalScheduler_Worker-26": awaiting notification on [0x0000000244471c18]
"DotMarketingQuartzLocalScheduler_Worker-27": awaiting notification on [0x0000000243e4c428]
"DotMarketingQuartzLocalScheduler_Worker-28": awaiting notification on [0x000000024ba6f5a8]
"DotMarketingQuartzLocalScheduler_Worker-29": awaiting notification on [0x0000000252a0c858]
"DotMarketingQuartzLocalScheduler_Worker-3": awaiting notification on [0x00000002447a3668]
"DotMarketingQuartzLocalScheduler_Worker-30": awaiting notification on [0x000000024b20b9a0]
"DotMarketingQuartzLocalScheduler_Worker-31": awaiting notification on [0x000000024a8ec6a8]
"DotMarketingQuartzLocalScheduler_Worker-32": awaiting notification on [0x0000000241851cd0]
"DotMarketingQuartzLocalScheduler_Worker-33": awaiting notification on [0x0000000243e4c2a0]
"DotMarketingQuartzLocalScheduler_Worker-34": awaiting notification on [0x00000002447a34e0]
"DotMarketingQuartzLocalScheduler_Worker-35": awaiting notification on [0x0000000244580bb8]
"DotMarketingQuartzLocalScheduler_Worker-36": awaiting notification on [0x000000024b20b818]
"DotMarketingQuartzLocalScheduler_Worker-37": awaiting notification on [0x000000024a8ec520]
"DotMarketingQuartzLocalScheduler_Worker-38": awaiting notification on [0x0000000241851b48]
"DotMarketingQuartzLocalScheduler_Worker-39": awaiting notification on [0x0000000244471a90]
"DotMarketingQuartzLocalScheduler_Worker-4": awaiting notification on [0x0000000243e4c738]
"DotMarketingQuartzLocalScheduler_Worker-40": awaiting notification on [0x000000024d7cd9e0]
"DotMarketingQuartzLocalScheduler_Worker-41": awaiting notification on [0x0000000244580a30]
"DotMarketingQuartzLocalScheduler_Worker-42": awaiting notification on [0x000000024ba6f420]
"DotMarketingQuartzLocalScheduler_Worker-43": awaiting notification on [0x000000024a8ec398]
"DotMarketingQuartzLocalScheduler_Worker-44": awaiting notification on [0x0000000243e4c118]
"DotMarketingQuartzLocalScheduler_Worker-45": awaiting notification on [0x00000002445808a8]
"DotMarketingQuartzLocalScheduler_Worker-46": awaiting notification on [0x00000002418519c0]
"DotMarketingQuartzLocalScheduler_Worker-47": awaiting notification on [0x000000024b0d80e8]
"DotMarketingQuartzLocalScheduler_Worker-48": awaiting notification on [0x000000024d7cd858]
"DotMarketingQuartzLocalScheduler_Worker-49": awaiting notification on [0x000000024a8ec210]
"DotMarketingQuartzLocalScheduler_Worker-5": awaiting notification on [0x000000024d7cdcf0]
"DotMarketingQuartzLocalScheduler_Worker-50": awaiting notification on [0x0000000243e4bf90]
"DotMarketingQuartzLocalScheduler_Worker-6": awaiting notification on [0x0000000244580d40]
"DotMarketingQuartzLocalScheduler_Worker-7": awaiting notification on [0x0000000241826ad0]
"DotMarketingQuartzLocalScheduler_Worker-8": awaiting notification on [0x0000000243d083a0]
"DotMarketingQuartzLocalScheduler_Worker-9": awaiting notification on [0x0000000241826c58]
"DotMarketingQuartzScheduler_Worker-1": awaiting notification on [0x0000000250f79680]
"DotMarketingQuartzScheduler_Worker-10": awaiting notification on [0x000000024d7cde78]
"DotMarketingQuartzScheduler_Worker-11": awaiting notification on [0x0000000250c80d30]
"DotMarketingQuartzScheduler_Worker-12": awaiting notification on [0x0000000243f0f2b0]
"DotMarketingQuartzScheduler_Worker-13": awaiting notification on [0x000000024d06e0e8]
"DotMarketingQuartzScheduler_Worker-14": awaiting notification on [0x0000000243e4cd58]
"DotMarketingQuartzScheduler_Worker-15": awaiting notification on [0x0000000243d089c0]
"DotMarketingQuartzScheduler_Worker-16": awaiting notification on [0x000000024b0d8708]
"DotMarketingQuartzScheduler_Worker-17": awaiting notification on [0x000000024ba6fa40]
"DotMarketingQuartzScheduler_Worker-18": awaiting notification on [0x00000002417af5f8]
"DotMarketingQuartzScheduler_Worker-19": awaiting notification on [0x000000024acc4dc8]
"DotMarketingQuartzScheduler_Worker-2": awaiting notification on [0x000000024d06e270]
"DotMarketingQuartzScheduler_Worker-20": awaiting notification on [0x00000002444723c0]
"DotMarketingQuartzScheduler_Worker-21": awaiting notification on [0x0000000243e4cbd0]
"DotMarketingQuartzScheduler_Worker-22": awaiting notification on [0x0000000241852168]
"DotMarketingQuartzScheduler_Worker-23": awaiting notification on [0x0000000243d08838]
"DotMarketingQuartzScheduler_Worker-24": awaiting notification on [0x000000024af9b328]
"DotMarketingQuartzScheduler_Worker-25": awaiting notification on [0x0000000252a0e498]
"DotMarketingQuartzScheduler_Worker-26": awaiting notification on [0x0000000250c80ba8]
"DotMarketingQuartzScheduler_Worker-27": awaiting notification on [0x0000000244472238]
"DotMarketingQuartzScheduler_Worker-28": awaiting notification on [0x00000002449716c8]
"DotMarketingQuartzScheduler_Worker-29": awaiting notification on [0x0000000243e4ca48]
"DotMarketingQuartzScheduler_Worker-3": awaiting notification on [0x000000024af9b4b0]
"DotMarketingQuartzScheduler_Worker-30": awaiting notification on [0x0000000243d086b0]
"DotMarketingQuartzScheduler_Worker-31": awaiting notification on [0x0000000250f794f8]
"DotMarketingQuartzScheduler_Worker-32": awaiting notification on [0x000000024b0d8580]
"DotMarketingQuartzScheduler_Worker-33": awaiting notification on [0x000000024b20bcb0]
"DotMarketingQuartzScheduler_Worker-34": awaiting notification on [0x000000024af9b1a0]
"DotMarketingQuartzScheduler_Worker-35": awaiting notification on [0x0000000241851fe0]
"DotMarketingQuartzScheduler_Worker-36": awaiting notification on [0x00000002444720b0]
"DotMarketingQuartzScheduler_Worker-37": awaiting notification on [0x0000000243e4c8c0]
"DotMarketingQuartzScheduler_Worker-38": awaiting notification on [0x0000000243f0f128]
"DotMarketingQuartzScheduler_Worker-39": awaiting notification on [0x0000000241826de0]
"DotMarketingQuartzScheduler_Worker-4": awaiting notification on [0x0000000244581220]
"DotMarketingQuartzScheduler_Worker-40": awaiting notification on [0x00000002447a37f0]
"DotMarketingQuartzScheduler_Worker-41": awaiting notification on [0x0000000250b7b368]
"DotMarketingQuartzScheduler_Worker-42": awaiting notification on [0x000000024a8ecb40]
"DotMarketingQuartzScheduler_Worker-43": awaiting notification on [0x000000024acc4c40]
"DotMarketingQuartzScheduler_Worker-44": awaiting notification on [0x00000002488915a8]
"DotMarketingQuartzScheduler_Worker-45": awaiting notification on [0x0000000244581098]
"DotMarketingQuartzScheduler_Worker-46": awaiting notification on [0x0000000243d08528]
"DotMarketingQuartzScheduler_Worker-47": awaiting notification on [0x000000024b0d83f8]
"DotMarketingQuartzScheduler_Worker-48": awaiting notification on [0x000000024af9b018]
"DotMarketingQuartzScheduler_Worker-49": awaiting notification on [0x0000000250c80a20]
"DotMarketingQuartzScheduler_Worker-5": awaiting notification on [0x0000000244472548]
"DotMarketingQuartzScheduler_Worker-50": awaiting notification on [0x000000024b56d9d8]
"DotMarketingQuartzScheduler_Worker-6": awaiting notification on [0x00000002418522f0]
"DotMarketingQuartzScheduler_Worker-7": awaiting notification on [0x0000000243f0f438]
"DotMarketingQuartzScheduler_Worker-8": awaiting notification on [0x0000000243d08b48]
"DotMarketingQuartzScheduler_Worker-9": awaiting notification on [0x0000000250b7b4f0]
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:543)
```
