### ISSUE TITLE
Task03540UpdateTagInodesReferences takes too long

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9313]
This upgrade task is taking a long time to finish even with not-so-large datasets. 
Execution time needs to be reduced considerably. 
A large dataset is needed to work on this and also for testing it out by QA when done.

**Comment by chrismccracken** [comment]
This NPE was also thrown which killed the task after it ran for about 20 hours:

```
[06/07/16 07:53:28:688 UTC]  INFO runonce.Task03540UpdateTagInodesReferences: Fetching more tags from the DB, please wait...
[06/07/16 07:53:28:815 UTC] FATAL startup.StartupTasksExecutor: Unable to execute the upgrade task : Task03540UpdateTagInodesReferences
java.lang.NullPointerException
        at com.dotmarketing.tag.business.TagAPIImpl.getTagAndCreate(TagAPIImpl.java:144) ~[dotcms_3.5_g14af2ce.jar:?]
        at com.dotmarketing.tag.business.TagAPIImpl.getTagsInText(TagAPIImpl.java:711) ~[dotcms_3.5_g14af2ce.jar:?]
        at com.dotmarketing.tag.business.TagAPIImpl.getTagsInText(TagAPIImpl.java:687) ~[dotcms_3.5_g14af2ce.jar:?]
        at com.dotmarketing.startup.runonce.Task03540UpdateTagInodesReferences.executeUpgrade(Task03540UpdateTagInodesReferences.java:95) ~[dotcms_3.5_g14af2ce.jar:?]
        at com.dotmarketing.startup.StartupTasksExecutor.executeUpgrades(StartupTasksExecutor.java:268) [dotcms_3.5_g14af2ce.jar:?]
        at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:116) [dotcms_3.5_g14af2ce.jar:?]
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4901) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5188) [catalina.jar:8.0.18]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.18]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.18]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714) [catalina.jar:8.0.18]
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1069) [catalina.jar:8.0.18]
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1719) [catalina.jar:8.0.18]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[06/07/16 07:53:28:820 UTC]  INFO startup.StartupTasksExecutor: Finishing upgrade tasks.
```

**Comment by chrismccracken** [comment]
Using the test data set with 2692440 rows in contentlet. SQL slow query logging set to 1000ms threshold, but nothing logged. All SQL activity for task seems to be this query:
`SELECT inode, identifier, text_area2 FROM contentlet WHERE structure_inode=$1 AND text_area2 IS N
OT NULL`

Contentlet table definitions and explain analyze (before/after query is cached) are at https://gist.github.com/chrismccracken/22a2cf974bd08c7056821a9a918db05e

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9359

**Comment by oarrietadotcms** [comment]
another PR for 3.6: https://github.com/dotCMS/core/pull/9365

**Comment by DeanGonzalez** [comment]
Added here: http://auth.dotcms.com/docs/latest/change-log#release-3.5.1 (changelog content for 3.5.1 is still under construction)

**Comment by shaydotcms** [comment]
Test done  on #9335
