### ISSUE TITLE
Workflow Scheme: Issues for File-type Content Types

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9341]
Reproduced in 3.3.2 and 3.5. 

Related ticket: https://my.dotcms.com/tickets/detail.dot?id=db26983a-2c15-4ce1-a724-dd9b56e50e33

Steps to reproduce:
1. Make "Document Management" as a Mandatory Workflow Scheme. on its Default Action, select "None".
2. Edit the File Asset content type and select "Document Management" as its Workflow Scheme. 
3. Go to Website Browser and try to upload a new File Asset. 

A default Workflow Action is required for Mandatory Workflows on File-Type Content Types. Once a "File Asset" field is populated, it should show a thumbnail of the recently uploaded image, however, we're getting the following error:

```
[11/07/16 12:38:15:450 EDT]  WARN business.ESContentletAPIImpl: Cannot delete content that has a working copy in another language
[11/07/16 12:38:22:961 EDT] ERROR business.ESContentletAPIImpl: A workflow action is manditory for content of type:File Asset
[11/07/16 12:38:22:961 EDT] ERROR business.ESContentletAPIImpl: com.dotmarketing.portlets.workflows.business.DotWorkflowException: A workflow action is manditory for content of type:File Asset
[11/07/16 12:38:22:961 EDT] ERROR ajax.ContentletAjax: Contentlet failed while creating new binary content
com.dotmarketing.portlets.workflows.business.DotWorkflowException: A workflow action is manditory for content of type:File Asset
    at com.dotmarketing.portlets.workflows.model.WorkflowProcessor.<init>(WorkflowProcessor.java:154) ~[dotcms_3.3.2_fb28b98f.jar:?]
    at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireWorkflowPreCheckin(WorkflowAPIImpl.java:790) ~[dotcms_3.3.2_fb28b98f.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2511) ~[dotcms_3.3.2_fb28b98f.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2383) ~[dotcms_3.3.2_fb28b98f.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2379) ~[dotcms_3.3.2_fb28b98f.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2331) ~[dotcms_3.3.2_fb28b98f.jar:?]
    at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkin(ContentletAPIInterceptor.java:257) ~[dotcms_3.3.2_fb28b98f.jar:?]
    at com.dotmarketing.portlets.contentlet.ajax.ContentletAjax.saveBinaryFileOnContent(ContentletAjax.java:2133) [dotcms_3.3.2_fb28b98f.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule$1.doFilter(CreatorModule.java:229) [dot.dwr-3rc2modified_2.jar:?]
    at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule.executeMethod(CreatorModule.java:241) [dot.dwr-3rc2modified_2.jar:?]
    at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:379) [dot.dwr-3rc2modified_2.jar:?]
    at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:332) [dot.dwr-3rc2modified_2.jar:?]
    at com.dotcms.repackage.org.directwebremoting.dwrp.BaseCallHandler.handle(BaseCallHandler.java:104) [dot.dwr-3rc2modified_2.jar:?]
    at com.dotcms.repackage.org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:120) [dot.dwr-3rc2modified_2.jar:?]
    at com.dotcms.repackage.org.directwebremoting.servlet.DwrServlet.doPost(DwrServlet.java:141) [dot.dwr-3rc2modified_2.jar:?]
    at com.dotmarketing.servlets.DwrWrapperServlet.doPost(DwrWrapperServlet.java:60) [dotcms_3.3.2_fb28b98f.jar:?]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:644) [servlet-api.jar:?]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:214) [dotcms_3.3.2_fb28b98f.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61) [dotcms_3.3.2_fb28b98f.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.CacheImagesFilter.doFilter(CacheImagesFilter.java:47) [dotcms_3.3.2_fb28b98f.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:300) [dotcms_3.3.2_fb28b98f.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:174) [dotcms_3.3.2_fb28b98f.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_3.3.2_fb28b98f.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) [dotcms_3.3.2_fb28b98f.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146) [dotcms_3.3.2_fb28b98f.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
    at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```

And the backend view looks like this: 

<img width="1317" alt="screen shot 2016-07-11 at 12 41 02 pm" src="https://cloud.githubusercontent.com/assets/1717110/16738684/ccb85b54-4764-11e6-8dd2-ea0add8c5759.png">

Workaround: Set at least one Default Action on the Scheme definition.

It would be ideal to show on backend view that Mandatory Workflow Schemes should have at least one Default Action, in the Add/Edit Content view AND the Workflow Scheme properties view.

**Comment by joseorsini** [comment]
**NOTE** 

On prior versions of 3.6, the content that we tried to add and triggered this issue is not fully deleted form the DB once we click on Cancel button. The file is saved anyways. We get the following: 

```
[11/07/16 12:46:09:837 EDT]  INFO business.ESContentletAPIImpl: UserId : system : delete : User trying to delete the following contents[30a9d43a-74b6-4ca8-be9e-163980d09677]
[11/07/16 12:46:09:849 EDT]  WARN business.ESContentletAPIImpl: Cannot delete content that has a working copy in another language
```

And the file is not removed, so the operation is not rolled back properly.
