### ISSUE TITLE
Workflows: Push Publish Actionlet not working in Edit Mode

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9351]
Reproduced in 3.3.2 and 3.5. 

Related to: https://my.dotcms.com/tickets/detail.dot?id=db26983a-2c15-4ce1-a724-dd9b56e50e33

Steps to reproduce

1. Assign "Document Management" Workflow Scheme to Page Asset Content Type. 
2. Go to Document Management Workflow and add a new Action under "Published" Step. Let's call it "Push It".
3. Open "Push It" and assign "Push Publish" sub-action to it. Save.
4. Go to any page under Published Status on Edit Mode. On the Left Menu, click on "Push It" workflow action button. 

The Problem is caused by the Push Publishing Actionlet. Once a user clicks on the action, it should return a Dialog Box indicating the Push Publishing config (Environments, Push Type, Force Push, etc.), just like the following screenshot from Website Browser (it also applies to Content Search Manager):

<img width="1338" alt="screen shot 2016-07-12 at 4 11 52 pm" src="https://cloud.githubusercontent.com/assets/1717110/16781953/7c76c184-484b-11e6-8136-ca1567e33506.png">

 This IS NOT happening on Edit Mode:

<img width="1315" alt="screen shot 2016-07-12 at 4 12 20 pm" src="https://cloud.githubusercontent.com/assets/1717110/16781967/89af8462-484b-11e6-9a08-185f12a59b64.png">

Stacktrace: (after adding more logging details and implementing fix from #8130)

``` 
[12/07/16 15:24:57:357 EDT] ERROR business.WorkflowAPIImpl: There was an unexpected Error: null
java.lang.NullPointerException
    at com.dotmarketing.portlets.workflows.actionlet.PushPublishActionlet.executeAction(PushPublishActionlet.java:70) ~[dotcms_3.3.2_fb28b98f.jar:?]
    at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireWorkflowPostCheckin(WorkflowAPIImpl.java:881) [WorkflowAPIImpl.class:?]
    at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.fireWorkflowNoCheckin(WorkflowAPIImpl.java:930) [WorkflowAPIImpl.class:?]
    at com.dotcms.rest.WorkflowResource.fireWorkflow(WorkflowResource.java:144) [dotcms_3.3.2_fb28b98f.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at com.dotcms.repackage.com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) [dot.jersey-server-1.12_2.jar:1.12]
    at com.dotcms.repackage.com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) [dot.jersey-server-1.12_2.jar:1.12]
    at com.dotcms.repackage.com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) [dot.jersey-server-1.12_2.jar:1.12]
    at com.dotcms.repackage.com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288) [dot.jersey-server-1.12_2.jar:1.12]
    at com.dotcms.repackage.com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [dot.jersey-server-1.12_2.jar:1.12]
    at com.dotcms.repackage.com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) [dot.jersey-server-1.12_2.jar:1.12]
    at com.dotcms.repackage.com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [dot.jersey-server-1.12_2.jar:1.12]
    at com.dotcms.repackage.com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) [dot.jersey-server-1.12_2.jar:1.12]
    at com.dotcms.repackage.com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1483) [dot.jersey-server-1.12_2.jar:1.12]
    at com.dotcms.repackage.com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1414) [dot.jersey-server-1.12_2.jar:1.12]
    at com.dotcms.repackage.com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1363) [dot.jersey-server-1.12_2.jar:1.12]
    at com.dotcms.repackage.com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1353) [dot.jersey-server-1.12_2.jar:1.12]
    at com.dotcms.repackage.com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:414) [dot.jersey-servlet-1.12_2.jar:1.12]
    at com.dotcms.repackage.com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537) [dot.jersey-servlet-1.12_2.jar:1.12]
    at com.dotcms.repackage.com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:708) [dot.jersey-servlet-1.12_2.jar:1.12]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
    at com.dotcms.rest.servlet.ReloadableServletContainer.service(ReloadableServletContainer.java:119) [dotcms_3.3.2_fb28b98f.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:214) [dotcms_3.3.2_fb28b98f.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61) [dotcms_3.3.2_fb28b98f.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:300) [dotcms_3.3.2_fb28b98f.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:174) [dotcms_3.3.2_fb28b98f.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_3.3.2_fb28b98f.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) [dotcms_3.3.2_fb28b98f.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146) [dotcms_3.3.2_fb28b98f.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
    at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:673) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
    at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by joseorsini** [comment]
Proposed commit https://github.com/dotCMS/core/commit/3e4124ccb58fd759e5cf4db9fadd64dbfe0f9561 was tested on the following scenario:

1. One Auth Environment (Standalone).
2. Two Receiver environments: 
  - 2-node Clustered Environment
  - 1 Standalone Environment.

All endpoints are running dotCMS 3.5 + Postgres DB.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/9355

**Comment by shaydotcms** [comment]
Passed QA. Dialog Box indicating the Push Publishing config is returned
Tested locally in:
master-3.6 // Win7 Pro SP1 // SQLServer 2012 // Firefox
