### ISSUE TITLE
Push Publishing: Delete All Pushed Assets history is not working

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9383]
Reproduced in 3.3.1. 

Once an user hits the "Delete Pushed Assets History" button on Maintenance portlet, this error is thrown: 

``` 
[20/07/16 14:40:57:664 BST] ERROR ajax.CMSMaintenanceAjax: ORA-03290: Invalid truncate command - missing CLUSTER or TABLE keyword

com.dotmarketing.exception.DotDataException: ORA-03290: Invalid truncate command - missing CLUSTER or TABLE keyword

at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:233) ~[dotcms_3.3.1_2521e19.jar:?]
at com.dotcms.publisher.assets.business.PushedAssetsFactoryImpl.deleteAllPushedAssets(PushedAssetsFactoryImpl.java:91) ~[dotcms_3.3.1_2521e19.jar:?]
at com.dotcms.publisher.assets.business.PushedAssetsAPIImpl.deleteAllPushedAssets(PushedAssetsAPIImpl.java:79) ~[dotcms_3.3.1_2521e19.jar:?]
at com.dotmarketing.portlets.cmsmaintenance.ajax.CMSMaintenanceAjax.deletePushedAssets(CMSMaintenanceAjax.java:239) [dotcms_3.3.1_2521e19.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule$1.doFilter(CreatorModule.java:229) [dot.dwr-3rc2modified_2.jar:?]
at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule.executeMethod(CreatorModule.java:241) [dot.dwr-3rc2modified_2.jar:?]
at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:379) [dot.dwr-3rc2modified_2.jar:?]
at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:332) [dot.dwr-3rc2modified_2.jar:?]
at com.dotcms.repackage.org.directwebremoting.dwrp.BaseCallHandler.handle(BaseCallHandler.java:104) [dot.dwr-3rc2modified_2.jar:?]
at com.dotcms.repackage.org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:120) [dot.dwr-3rc2modified_2.jar:?]
at com.dotcms.repackage.org.directwebremoting.servlet.DwrServlet.doPost(DwrServlet.java:141) [dot.dwr-3rc2modified_2.jar:?]
at com.dotmarketing.servlets.DwrWrapperServlet.doPost(DwrWrapperServlet.java:60) [dotcms_3.3.1_2521e19.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:644) [servlet-api.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:225) [CMSFilter.class:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61) [dotcms_3.3.1_2521e19.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.filters.CacheImagesFilter.doFilter(CacheImagesFilter.java:47) [dotcms_3.3.1_2521e19.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:300) [dotcms_3.3.1_2521e19.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:174) [dotcms_3.3.1_2521e19.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_3.3.1_2521e19.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) [dotcms_3.3.1_2521e19.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146) [dotcms_3.3.1_2521e19.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.sql.SQLException: ORA-03290: Invalid truncate command - missing CLUSTER or TABLE keyword

at oracle.jdbc.driver.SQLStateMapping.newSQLException(SQLStateMapping.java:74) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
at oracle.jdbc.driver.DatabaseError.newSQLException(DatabaseError.java:110) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:171) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:455) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:413) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:1030) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:183) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:936) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1222) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1770) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1739) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:298) ~[ojdbc5.jar:Oracle JDBC Driver version - "11.1.0.6.0-Production+"]
at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:290) ~[tomcat-dbcp.jar:8.0.18]
at org.apache.tomcat.dbcp.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:290) ~[tomcat-dbcp.jar:8.0.18]
at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:590) ~[dotcms_3.3.1_2521e19.jar:?]
at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:489) ~[dotcms_3.3.1_2521e19.jar:?]
at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:231) ~[dotcms_3.3.1_2521e19.jar:?]
```

It happens because the SQL Query executed for dropping all history has a bad syntax for Oracle Databases (see https://github.com/dotCMS/core/blob/master-3.6/src/com/dotcms/publisher/assets/business/PushedAssetsFactory.java#L17). "TABLE" is optional on Postgres and MySQL dbs.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/9443

**Comment by nollymar** [comment]
The implementation was tested. Result: Successful
