### ISSUE TITLE
Pages: issues adding non-default contents to pages

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9429]
Reproduced in 3.3.1 and 3.5. 

Related to: https://my.dotcms.com/tickets/detail.dot?id=13b33be7-78fb-49a5-8391-87eeea5423d8 

Steps:
1. Make sure that DEFAULT_PAGE_TO_DEFAULT_CONTENT property is set to true. 
2. Create a /about-us/test page in English.
3. Create two separate Web Page Contents: one in English, one in Spanish.
4. Go to /about-us/test page in Edit Mode and add the English content to the English version of the page. Content is added without issues. 
5. Switch to Spanish language in Edit Mode and try to add the Spanish content to the page. Content is not added.

Stacktrace:

```
[26/07/16 10:51:05:158 EDT] ERROR action.DirectorAction: Creating MultiTree failed: Contentlet with identifier ad9cb5de-5511-417e-b331-42a4df67f9cb does not exist in Espanol
[26/07/16 10:51:05:158 EDT] ERROR action.DirectorAction: Unable to add content to page
com.dotmarketing.exception.DotRuntimeException: The selected language (Espanol) for this content does not match the page language.
    at com.dotmarketing.portlets.director.action.DirectorAction.processAction(DirectorAction.java:609) [dotcms_3.5_g14af2ce.jar:?]
    at com.liferay.portal.struts.PortletRequestProcessor.process(PortletRequestProcessor.java:128) [dotcms_3.5_g14af2ce.jar:?]
    at com.liferay.portlet.StrutsPortlet.processAction(StrutsPortlet.java:116) [dotcms_3.5_g14af2ce.jar:?]
    at com.liferay.portlet.CachePortlet.processAction(CachePortlet.java:130) [dotcms_3.5_g14af2ce.jar:?]
    at com.liferay.portal.action.LayoutAction._processPortletRequest(LayoutAction.java:232) [dotcms_3.5_g14af2ce.jar:?]
    at com.liferay.portal.action.LayoutAction._processActionRequest(LayoutAction.java:249) [dotcms_3.5_g14af2ce.jar:?]
    at com.liferay.portal.action.LayoutAction.execute(LayoutAction.java:93) [dotcms_3.5_g14af2ce.jar:?]
    at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:421) [dot.struts-1.2.4_2.jar:1.2.4]
    at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:226) [dot.struts-1.2.4_2.jar:1.2.4]
    at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:160) [dotcms_3.5_g14af2ce.jar:?]
    at com.dotcms.repackage.org.apache.struts.action.ActionServlet.process(ActionServlet.java:1164) [dot.struts-1.2.4_2.jar:1.2.4]
    at com.dotcms.repackage.org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:415) [dot.struts-1.2.4_2.jar:1.2.4]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:644) [servlet-api.jar:?]
    at com.liferay.portal.servlet.MainServlet.callParentService(MainServlet.java:277) [dotcms_3.5_g14af2ce.jar:?]
    at com.liferay.portal.servlet.MainServlet.service(MainServlet.java:506) [dotcms_3.5_g14af2ce.jar:?]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotcms.repackage.com.liferay.filters.secure.SecureFilter.doFilter(SecureFilter.java:135) [dot.secure-filter-ukv_2.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:244) [dotcms_3.5_g14af2ce.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61) [dotcms_3.5_g14af2ce.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:307) [dotcms_3.5_g14af2ce.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:174) [dotcms_3.5_g14af2ce.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_3.5_g14af2ce.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) [dotcms_3.5_g14af2ce.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146) [dotcms_3.5_g14af2ce.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
    at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```

Despite DEFAULT_PAGE_TO_DEFAULT_CONTENT property is set to true, non-default contents cannot be added to one language version page. This has become a problem for some clients who recently upgraded to 3.x and migrated all their pages to Contents, which are created with default language only, and creating a new version with non-default languages may take considerable time to achieve.

-----

Tested recently on dotCMS 3.7.1 and 4.0. Another issue surfaced during some tests with non-default languages. 

1. Create 1 page in Spanish language. 
2. Create 2 Generic Contents in Spanish Language.
3. On Edit Mode, add these 2 contents to any container on the page. 
4. Once both contents have been added, try to reorder them. 

Stacktrace

```
[08/05/17 14:19:52:371 EDT] ERROR portlet.StrutsPortlet: java.lang.NullPointerException
[08/05/17 14:19:54:118 EDT] ERROR filters.CmsUrlUtil: Unable to find/demos/test-page-teleflex
```

Reported here: https://my.dotcms.com/tickets/detail.dot?id=adf06de8-d58f-470d-8c90-88d0d27803ba

**Comment by joseorsini** [comment]
We should ask here https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/portlets/director/action/DirectorAction.java#L586 and here https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/portlets/contentlet/business/web/ContentletWebAPIImpl.java#L281 if DEFAULT_PAGE_TO_DEFAULT_LANGUAGE property is true. That would allow adding contents in different languages to a page asset

**Comment by wezell** [comment]
@joseorsini pull requests are always appreciated!

**Comment by joseorsini** [comment]
@wezell I haven't had the time to test this on 3.6.0 and on master-3.7. Once I'm able to, I'll upload a PR :)

**Comment by joseorsini** [comment]
Tested recently on dotCMS 3.7.1 and 4.0. Issue persists. 


1. Create 1 page in Spanish language. 
2. Create 2 Generic Contents in Spanish Language.
3. On Edit Mode, add these 2 contents to any container on the page. 
4. Once both contents have been added, try to reorder them. 

Stacktrace

```
[08/05/17 14:19:52:371 EDT] ERROR portlet.StrutsPortlet: java.lang.NullPointerException
[08/05/17 14:19:54:118 EDT] ERROR filters.CmsUrlUtil: Unable to find/demos/test-page-teleflex
```

Reported here: https://my.dotcms.com/tickets/detail.dot?id=adf06de8-d58f-470d-8c90-88d0d27803ba

**Comment by joseorsini** [comment]
@wezell @jgambarios @dsilvam there are two issues here: 

1. If config states that pages fall back to default language in case a specific language version is requested, should we allow users to add non-default language versions of contents to it? (this is still unresolved)

2. There is an issue with reordering and removing contents from containers, once a non-default language version of page is requested. this was fixed here fix reorder and remove contents from containers. 

If item # 1 is not possible, then please review item # 2 which was recently fixed. Sending a PR right away

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/11527

**Comment by dsilvam** [comment]
@joseorsini I think for point 1),  the user should first create an spanish version of the page to be able to add spanish content. The DEFAULT_PAGE_TO_DEFAULT_LANGUAGE acts showing english content (assuming default) when spanish version of the page is requested

**Comment by joseorsini** [comment]
@dsilvam agreed. This came as a customer's request however they had to create a non-default language version of pages as a workaround. I agree that both pages and contents should have their own language versions in order to avoid this mix up. 

That being said, the original issue can be closed, however, please review my point 2) and the fix. This issue affects all current releases and potential fix seems to solve it.

**Comment by joseorsini** [comment]
PR for release-4.1: https://github.com/dotCMS/core/pull/11560

**Comment by bryanboza** [comment]
Fixed, tested reordering the contents in a page with a non default language and works fine....
