### ISSUE TITLE
IOUtils.toString() can hit OOM by oversized metadata

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#9451]
At https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/portlets/fileassets/business/FileAssetAPIImpl.java#L522

**Comment by chrismccracken** [comment]
The reindex thread died when it hit a fileasset's metadata that was 5.6G in size uncompressed:
```
Exception in thread "Thread-34" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:569)
        at java.lang.StringBuilder.append(StringBuilder.java:190)
        at com.dotcms.repackage.org.apache.commons.io.output.StringBuilderWriter.write(StringBuilderWriter.java:138)
        at com.dotcms.repackage.org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1365)
        at com.dotcms.repackage.org.apache.commons.io.IOUtils.copy(IOUtils.java:1340)
        at com.dotcms.repackage.org.apache.commons.io.IOUtils.copy(IOUtils.java:1287)
        at com.dotcms.repackage.org.apache.commons.io.IOUtils.toString(IOUtils.java:502)
        at com.dotmarketing.portlets.fileassets.business.FileAssetAPIImpl.getContentMetadataAsString(FileAssetAPIImpl.java:523)
        at com.dotcms.content.elasticsearch.business.ESMappingAPIImpl.toMap(ESMappingAPIImpl.java:345)
        at com.dotcms.content.elasticsearch.business.ESContentletIndexAPI.indexContentletList(ESContentletIndexAPI.java:327)
        at com.dotcms.content.elasticsearch.business.ESContentletIndexAPI.access$100(ESContentletIndexAPI.java:43)
        at com.dotcms.content.elasticsearch.business.ESContentletIndexAPI$1.run(ESContentletIndexAPI.java:297)
        at com.dotcms.content.elasticsearch.business.ESContentletIndexAPI.addContentToIndex(ESContentletIndexAPI.java:309)
        at com.dotmarketing.common.reindex.ReindexThread.writeDocumentToIndex(ReindexThread.java:674)
        at com.dotmarketing.common.reindex.ReindexThread.run(ReindexThread.java:260)

**Comment by chrismccracken** [comment]
https://my.dotcms.com/tickets/detail.dot?id=d7a7428b-49a3-4611-acf3-22b72e3cfbca

**Comment by wezell** [comment]
@chrismccracken do you have the file so we can test against it?

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9949

**Comment by chrismccracken** [comment]
Ref https://my.dotcms.com/ticket/dotcms-199/

**Comment by oarrietadotcms** [comment]
PR for master-3.7: https://github.com/dotCMS/core/pull/10605

**Comment by erickgonzalez** [comment]
Tested the reindex with a fresh install (in Postgres, MySQL, and MSSQL) and works as it should. To try hit the error we need a file asset with a huge metadata, but this was previously tested by @chrismccracken with an upgrade of a client's DB that experience the issue and was resolved.
