### ISSUE TITLE
Shutting down dotCMS throws errors

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9492]
Nightly build 8/4/16 - all defualts
OSX Yosemite

this is using the supplied:
`./bin/shutdown.sh` 
script

```
04-Aug-2016 11:48:21.612 INFO [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["http-nio-8080"]
04-Aug-2016 11:48:21.694 INFO [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["http-nio-8080"]
04-Aug-2016 11:48:22.631 INFO [Thread-20] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [com.dotcms.repackage.org.apache.logging.log4j.core.impl.ThrowableProxy]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.dotcms.repackage.org.apache.logging.log4j.core.impl.ThrowableProxy]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1327)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1313)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1196)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
	at com.dotcms.repackage.org.apache.logging.log4j.core.impl.Log4jLogEvent.getThrownProxy(Log4jLogEvent.java:323)
	at com.dotcms.repackage.org.apache.logging.log4j.core.impl.Log4jLogEvent.serialize(Log4jLogEvent.java:429)
	at com.dotcms.repackage.org.apache.logging.log4j.core.appender.AsyncAppender.append(AsyncAppender.java:155)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:430)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:409)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
	at com.dotcms.repackage.org.apache.logging.log4j.core.Logger.logMessage(Logger.java:112)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:727)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:716)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:354)
	at com.dotmarketing.util.Logger.error(Logger.java:124)
	at com.dotcms.cluster.common.ClusterServerActionThread.run(ClusterServerActionThread.java:62)

2016-08-04 11:48:22,633 ERROR An exception occurred processing Appender generic java.lang.IllegalStateException: Can't overwrite cause with java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.dotcms.repackage.org.apache.logging.log4j.core.impl.ThrowableProxy]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at java.lang.Throwable.initCause(Throwable.java:457)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1196)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
	at com.dotcms.repackage.org.apache.logging.log4j.core.impl.Log4jLogEvent.getThrownProxy(Log4jLogEvent.java:323)
	at com.dotcms.repackage.org.apache.logging.log4j.core.impl.Log4jLogEvent.serialize(Log4jLogEvent.java:429)
	at com.dotcms.repackage.org.apache.logging.log4j.core.appender.AsyncAppender.append(AsyncAppender.java:155)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:430)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:409)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
	at com.dotcms.repackage.org.apache.logging.log4j.core.Logger.logMessage(Logger.java:112)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:727)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:716)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:354)
	at com.dotmarketing.util.Logger.error(Logger.java:124)
	at com.dotcms.cluster.common.ClusterServerActionThread.run(ClusterServerActionThread.java:62)
Caused by: java.lang.ClassNotFoundException
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1315)
	... 15 more

04-Aug-2016 11:48:24.635 INFO [Thread-20] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [com.dotcms.repackage.org.apache.logging.log4j.core.impl.ThrowableProxy]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.dotcms.repackage.org.apache.logging.log4j.core.impl.ThrowableProxy]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1327)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1313)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1196)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
	at com.dotcms.repackage.org.apache.logging.log4j.core.impl.Log4jLogEvent.getThrownProxy(Log4jLogEvent.java:323)
	at com.dotcms.repackage.org.apache.logging.log4j.core.impl.Log4jLogEvent.serialize(Log4jLogEvent.java:429)
	at com.dotcms.repackage.org.apache.logging.log4j.core.appender.AsyncAppender.append(AsyncAppender.java:155)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:430)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:409)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
	at com.dotcms.repackage.org.apache.logging.log4j.core.Logger.logMessage(Logger.java:112)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:727)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:716)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:354)
	at com.dotmarketing.util.Logger.error(Logger.java:124)
	at com.dotcms.cluster.common.ClusterServerActionThread.run(ClusterServerActionThread.java:62)

2016-08-04 11:48:24,635 ERROR An exception occurred processing Appender generic java.lang.IllegalStateException: Can't overwrite cause with java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.dotcms.repackage.org.apache.logging.log4j.core.impl.ThrowableProxy]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at java.lang.Throwable.initCause(Throwable.java:457)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1196)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
	at com.dotcms.repackage.org.apache.logging.log4j.core.impl.Log4jLogEvent.getThrownProxy(Log4jLogEvent.java:323)
	at com.dotcms.repackage.org.apache.logging.log4j.core.impl.Log4jLogEvent.serialize(Log4jLogEvent.java:429)
	at com.dotcms.repackage.org.apache.logging.log4j.core.appender.AsyncAppender.append(AsyncAppender.java:155)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:430)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:409)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
	at com.dotcms.repackage.org.apache.logging.log4j.core.Logger.logMessage(Logger.java:112)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:727)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:716)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:354)
	at com.dotmarketing.util.Logger.error(Logger.java:124)
	at com.dotcms.cluster.common.ClusterServerActionThread.run(ClusterServerActionThread.java:62)
Caused by: java.lang.ClassNotFoundException
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1315)
	... 15 more

04-Aug-2016 11:48:26.638 INFO [Thread-20] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [com.dotcms.repackage.org.apache.logging.log4j.core.impl.ThrowableProxy]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.dotcms.repackage.org.apache.logging.log4j.core.impl.ThrowableProxy]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1327)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1313)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1196)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
	at com.dotcms.repackage.org.apache.logging.log4j.core.impl.Log4jLogEvent.getThrownProxy(Log4jLogEvent.java:323)
	at com.dotcms.repackage.org.apache.logging.log4j.core.impl.Log4jLogEvent.serialize(Log4jLogEvent.java:429)
	at com.dotcms.repackage.org.apache.logging.log4j.core.appender.AsyncAppender.append(AsyncAppender.java:155)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:430)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:409)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
	at com.dotcms.repackage.org.apache.logging.log4j.core.Logger.logMessage(Logger.java:112)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:727)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:716)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:354)
	at com.dotmarketing.util.Logger.error(Logger.java:124)
	at com.dotcms.cluster.common.ClusterServerActionThread.run(ClusterServerActionThread.java:62)

2016-08-04 11:48:26,639 ERROR An exception occurred processing Appender generic java.lang.IllegalStateException: Can't overwrite cause with java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.dotcms.repackage.org.apache.logging.log4j.core.impl.ThrowableProxy]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at java.lang.Throwable.initCause(Throwable.java:457)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1196)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
	at com.dotcms.repackage.org.apache.logging.log4j.core.impl.Log4jLogEvent.getThrownProxy(Log4jLogEvent.java:323)
	at com.dotcms.repackage.org.apache.logging.log4j.core.impl.Log4jLogEvent.serialize(Log4jLogEvent.java:429)
	at com.dotcms.repackage.org.apache.logging.log4j.core.appender.AsyncAppender.append(AsyncAppender.java:155)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:430)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:409)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
	at com.dotcms.repackage.org.apache.logging.log4j.core.Logger.logMessage(Logger.java:112)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:727)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:716)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:354)
	at com.dotmarketing.util.Logger.error(Logger.java:124)
	at com.dotcms.cluster.common.ClusterServerActionThread.run(ClusterServerActionThread.java:62)
Caused by: java.lang.ClassNotFoundException
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1315)
	... 15 more

04-Aug-2016 11:48:28.643 INFO [Thread-20] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [com.dotcms.repackage.org.apache.logging.log4j.core.impl.ThrowableProxy]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.dotcms.repackage.org.apache.logging.log4j.core.impl.ThrowableProxy]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1327)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1313)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1196)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
	at com.dotcms.repackage.org.apache.logging.log4j.core.impl.Log4jLogEvent.getThrownProxy(Log4jLogEvent.java:323)
	at com.dotcms.repackage.org.apache.logging.log4j.core.impl.Log4jLogEvent.serialize(Log4jLogEvent.java:429)
	at com.dotcms.repackage.org.apache.logging.log4j.core.appender.AsyncAppender.append(AsyncAppender.java:155)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:430)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:409)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
	at com.dotcms.repackage.org.apache.logging.log4j.core.Logger.logMessage(Logger.java:112)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:727)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:716)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:354)
	at com.dotmarketing.util.Logger.error(Logger.java:124)
	at com.dotcms.cluster.common.ClusterServerActionThread.run(ClusterServerActionThread.java:62)

2016-08-04 11:48:28,643 ERROR An exception occurred processing Appender generic java.lang.IllegalStateException: Can't overwrite cause with java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.dotcms.repackage.org.apache.logging.log4j.core.impl.ThrowableProxy]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at java.lang.Throwable.initCause(Throwable.java:457)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1196)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
	at com.dotcms.repackage.org.apache.logging.log4j.core.impl.Log4jLogEvent.getThrownProxy(Log4jLogEvent.java:323)
	at com.dotcms.repackage.org.apache.logging.log4j.core.impl.Log4jLogEvent.serialize(Log4jLogEvent.java:429)
	at com.dotcms.repackage.org.apache.logging.log4j.core.appender.AsyncAppender.append(AsyncAppender.java:155)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:430)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:409)
	at com.dotcms.repackage.org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
	at com.dotcms.repackage.org.apache.logging.log4j.core.Logger.logMessage(Logger.java:112)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:727)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:716)
	at com.dotcms.repackage.org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:354)
	at com.dotmarketing.util.Logger.error(Logger.java:124)
	at com.dotcms.cluster.common.ClusterServerActionThread.run(ClusterServerActionThread.java:62)
Caused by: java.lang.ClassNotFoundException
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1315)
	... 15 more

Killing Tomcat with the PID: 20442
The Tomcat process has been killed.
```

**Comment by wezell** [comment]
Non-priority, can reopen if needed
