### ISSUE TITLE
Push Publishing: Improvements for PublisherQueueJob

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9675]
Reported on https://my.dotcms.com/tickets/detail.dot?id=e0f45b34-1c11-440e-b17d-d98d1a2f1cb2 .

Also reported on master-3.6

Depending on the current status of a bundle that was previously pushed, the PublisherQueueJob will ask for a status update, which it's retrieved from the Receiver endpoints specified on the publishing_queue_audit.status_pojo column. These possible status are:
- FAILED_TO_SEND_TO_ALL_GROUPS(4).
- FAILED_TO_SEND_TO_SOME_GROUPS(5).
- FAILED_TO_BUNDLE(6).
- BUNDLE_SENT_SUCCESSFULLY(10).
- RECEIVED_BUNDLE(11).
- PUBLISHING_BUNDLE(12).

As specified [here](https://github.com/dotCMS/core/blob/master-3.6/src/com/dotcms/publisher/business/PublishAuditStatus.java#L20-L30). If a Receiver environment is configured over https, there are a few cases that the call for retrieving the bundle status return Error 404

Stacktrace:

```
[26/08/16 15:20:00:055 EDT] ERROR business.PublisherQueueJob: HTTP 404 Not Found
com.dotcms.repackage.javax.ws.rs.NotFoundException: HTTP 404 Not Found
at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1008) ~[dot.jersey-client-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:816) ~[dot.jersey-client-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92) ~[dot.jersey-client-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:700) ~[dot.jersey-client-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[dot.jersey-common-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[dot.jersey-common-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:228) ~[dot.jersey-common-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444) ~[dot.jersey-common-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:696) ~[dot.jersey-client-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:420) ~[dot.jersey-client-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:316) ~[dot.jersey-client-2.22.1_1.jar:?]
at com.dotcms.publisher.business.PublisherQueueJob.updateAuditStatus(PublisherQueueJob.java:216) [dotcms_3.6_ee8458c.jar:?]
at com.dotcms.publisher.business.PublisherQueueJob.execute(PublisherQueueJob.java:68) [dotcms_3.6_ee8458c.jar:?]
at org.quartz.core.JobRunShell.run(JobRunShell.java:223) [dot.quartz-all-1.8.6_2.jar:?]
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) [dot.quartz-all-1.8.6_2.jar:?]
[26/08/16 15:20:00:067 EDT] ERROR business.PublisherQueueJob: HTTP 404 Not Found
com.dotcms.repackage.javax.ws.rs.NotFoundException: HTTP 404 Not Found
at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1008) ~[dot.jersey-client-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:816) ~[dot.jersey-client-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92) ~[dot.jersey-client-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:700) ~[dot.jersey-client-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[dot.jersey-common-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[dot.jersey-common-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:228) ~[dot.jersey-common-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444) ~[dot.jersey-common-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:696) ~[dot.jersey-client-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:420) ~[dot.jersey-client-2.22.1_1.jar:?]
at com.dotcms.repackage.org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:316) ~[dot.jersey-client-2.22.1_1.jar:?]
at com.dotcms.publisher.business.PublisherQueueJob.updateAuditStatus(PublisherQueueJob.java:216) [dotcms_3.6_ee8458c.jar:?]
at com.dotcms.publisher.business.PublisherQueueJob.execute(PublisherQueueJob.java:68) [dotcms_3.6_ee8458c.jar:?]
at org.quartz.core.JobRunShell.run(JobRunShell.java:223) [dot.quartz-all-1.8.6_2.jar:?]
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) [dot.quartz-all-1.8.6_2.jar:?]
```

From the DB, we have the following data. You can see that the status_pojo objects are referencing existing and valid endpoints (site name was removed).

```
dotcms=> select * from publishing_environment;
                  id                  |    name    | push_to_all
--------------------------------------+------------+-------------
 cfc2191b-260f-44b3-99e3-eefbaa68b565 | thissite.com | f
(1 row)

dotcms=> select * from publishing_end_point;
                  id                  |               group_id               |  server_name   |   address   | port | protocol | enabled |                             auth_key
                           | sending
--------------------------------------+--------------------------------------+----------------+-------------+------+----------+---------+---------------------------------------
---------------------------+---------
 08ab48c0-4a15-4627-84ad-8bc13d21f90a |                                      | www.thissite.com | xx.xxx.xxx.xxx | 80   | http     | t       | z+5cVJU8jfn4Wj1Ye+WcfQDlXCNu1rxVig8Qbf
+diZtwR/EzuCN1jOaOWYX8ph3t | t
 cceec581-d61c-4aec-b77c-97bcdc1730ef | cfc2191b-260f-44b3-99e3-eefbaa68b565 | thissite.com     | thissite.com  | 443  | https    | t       | N+OKM2SOpmGTcS1Cviw+Q40sLPCXbGNlMTkXaF
d5XxmCpVHWojdtkA==         | f
(2 rows)

dotcms=> select * from publishing_queue_audit where status = 10 or status = 11 or status = 12 or status = 13 or status = 4 or status = 5;
              bundle_id               | status |                                       status_pojo                                        |     status_updated      |
      create_date
--------------------------------------+--------+------------------------------------------------------------------------------------------+-------------------------+-
------------------------
 4d670195-dbae-422c-8b1e-00e850586987 |      4 | <com.dotcms.publisher.business.PublishAuditHistory>                                     +| 2016-05-26 09:26:00.012 |
2016-05-26 09:26:00.012
                                      |        |   <endpointsMap>                                                                        +|                         |
                                      |        |     <entry>                                                                             +|                         |
                                      |        |       <string>cfc2191b-260f-44b3-99e3-eefbaa68b565</string>                             +|                         |
                                      |        |       <map>                                                                             +|                         |
                                      |        |         <entry>                                                                         +|                         |
                                      |        |           <string>cceec581-d61c-4aec-b77c-97bcdc1730ef</string>                         +|                         |
                                      |        |           <com.dotcms.publisher.business.EndpointDetail>                                +|                         |
                                      |        |             <status>8</status>                                                          +|                         |
                                      |        |             <info>Failed to publish because an error occurred: identifier is null</info>+|                         |
                                      |        |           </com.dotcms.publisher.business.EndpointDetail>                               +|                         |
                                      |        |         </entry>                                                                        +|                         |
                                      |        |       </map>                                                                            +|                         |
                                      |        |     </entry>                                                                            +|                         |
                                      |        |   </endpointsMap>                                                                       +|                         |
                                      |        |   <bundleStart>2016-05-26 13:29:00.124 UTC</bundleStart>                                +|                         |
                                      |        |   <bundleEnd>2016-05-26 13:29:00.140 UTC</bundleEnd>                                    +|                         |
                                      |        |   <numTries>4</numTries>                                                                +|                         |
                                      |        |   <assets>                                                                              +|                         |
                                      |        |     <entry>                                                                             +|                         |
                                      |        |       <string>b6d8eefd-2f95-4534-8958-d9d8fd45ac0e</string>                             +|                         |
                                      |        |       <string>folder</string>                                                           +|                         |
                                      |        |     </entry>                                                                            +|                         |
                                      |        |   </assets>                                                                             +|                         |
                                      |        | </com.dotcms.publisher.business.PublishAuditHistory>                                     |                         |
 804396e6-0306-4f70-b7f4-15cebcee333d |      4 | <com.dotcms.publisher.business.PublishAuditHistory>                                     +| 2016-05-26 09:26:00.151 |
2016-05-26 09:26:00.151
                                      |        |   <endpointsMap>                                                                        +|                         |
                                      |        |     <entry>                                                                             +|                         |
                                      |        |       <string>cfc2191b-260f-44b3-99e3-eefbaa68b565</string>                             +|                         |
                                      |        |       <map>                                                                             +|                         |
                                      |        |         <entry>                                                                         +|                         |
                                      |        |           <string>cceec581-d61c-4aec-b77c-97bcdc1730ef</string>                         +|                         |
                                      |        |           <com.dotcms.publisher.business.EndpointDetail>                                +|                         |
                                      |        |             <status>8</status>                                                          +|                         |
                                      |        |             <info>Failed to publish because an error occurred: identifier is null</info>+|                         |
                                      |        |           </com.dotcms.publisher.business.EndpointDetail>                               +|                         |
                                      |        |         </entry>                                                                        +|                         |
                                      |        |       </map>                                                                            +|                         |
                                      |        |     </entry>                                                                            +|                         |
                                      |        |   </endpointsMap>                                                                       +|                         |
                                      |        |   <bundleStart>2016-05-26 13:27:00.225 UTC</bundleStart>                                +|                         |
                                      |        |   <bundleEnd>2016-05-26 13:27:00.233 UTC</bundleEnd>                                    +|                         |
                                      |        |   <numTries>2</numTries>                                                                +|                         |
                                      |        |   <assets>                                                                              +|                         |
                                      |        |     <entry>                                                                             +|                         |
                                      |        |       <string>66c98fdd-6cdb-475d-8ed7-fffe043a9694</string>                             +|                         |
                                      |        |       <string>contentlet</string>                                                       +|                         |
                                      |        |     </entry>                                                                            +|                         |
                                      |        |   </assets>                                                                             +|                         |
                                      |        | </com.dotcms.publisher.business.PublishAuditHistory>                                     |                         |
(2 rows)
```

The numTries value on the status_pojo value NEVER gets updated while this is happening, so depending on the current value ox MAX_NUMBER_TRIES properties, it will keep requesting a bundle status, and hitting the same error 404 on each run of the PublisherQueueJob.

I think we should Update the status_pojo object and at least update the numTries object if the response status was different than 200. Once it reaches a value equal or greater than MAX_NUMBER_TRIES config, no updates will be requested again.

**Comment by joseorsini** [comment]
Update. By inspecting the Receiver Environment's DB 

```
dotcms.com=> select * from publishing_queue_audit where bundle_id = '4d670195-dbae-422c-8b1e-00e850586987';
 bundle_id | status | status_pojo | status_updated | create_date
-----------+--------+-------------+----------------+-------------
(0 rows)

dotcms.com=> select * from publishing_queue_audit where bundle_id = '804396e6-0306-4f70-b7f4-15cebcee333d';
 bundle_id | status | status_pojo | status_updated | create_date
-----------+--------+-------------+----------------+-------------
(0 rows)

dotcms.com=> select * from publishing_bundle where id = '4d670195-dbae-422c-8b1e-00e850586987';
                  id                  |                 name                 |      publish_date       | expire_date | owner  | force_push
--------------------------------------+--------------------------------------+-------------------------+-------------+--------+------------
 4d670195-dbae-422c-8b1e-00e850586987 | 4d670195-dbae-422c-8b1e-00e850586987 | 2016-05-26 09:24:00.219 |             | system | f
(1 row)

dotcms.com=> select * from publishing_bundle where id = '804396e6-0306-4f70-b7f4-15cebcee333d';
                  id                  |                 name                 |      publish_date       | expire_date | owner  | force_push
--------------------------------------+--------------------------------------+-------------------------+-------------+--------+------------
 804396e6-0306-4f70-b7f4-15cebcee333d | 804396e6-0306-4f70-b7f4-15cebcee333d | 2016-05-26 09:25:00.282 |             | system | f
```

The bundle was pushed, but since it couldn't be processed (as per the Audit info on Sender Environment), no auditInfo was created, so the REST API call returns Error 404 by default.
