### ISSUE TITLE
Page to content migration not working on dotCMS 3.6.0

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/core#9760]
Tested on dotCMS 3.6.0 (starter site/H2).

To reproduce:
1. Go to System > Maintenance > Tools
2. Scroll down to "Migrate HTML Pages to Content"
3. Click on "Execute"
4. You should see this message "HTML Pages could not be migrated to Contents. Please check dotCMS logfiles for more information."
5. The following exception gets recorded in dotcms.log :

```
[09/09/16 12:02:53:609 EDT] ERROR business.HTMLPageAssetAPIImpl: There was a problem migrating Pages to Contents: null
com.dotmarketing.exception.DotRuntimeException
    at com.dotmarketing.portlets.htmlpageasset.model.HTMLPageAsset.getMap(HTMLPageAsset.java:149) ~[dotcms_3.6.0_3876030.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2594) ~[dotcms_3.6.0_3876030.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2556) ~[dotcms_3.6.0_3876030.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2551) ~[dotcms_3.6.0_3876030.jar:?]
    at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2501) ~[dotcms_3.6.0_3876030.jar:?]
    at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.checkin(ContentletAPIInterceptor.java:259) ~[dotcms_3.6.0_3876030.jar:?]
    at com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPIImpl.migrateLegacyPage(HTMLPageAssetAPIImpl.java:497) ~[dotcms_3.6.0_3876030.jar:?]
    at com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPIImpl.migrateAllLegacyPages(HTMLPageAssetAPIImpl.java:422) [dotcms_3.6.0_3876030.jar:?]
    at com.dotmarketing.portlets.cmsmaintenance.ajax.CMSMaintenanceAjax.migrateHTMLPagesToContent(CMSMaintenanceAjax.java:311) [dotcms_3.6.0_3876030.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
    at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule$1.doFilter(CreatorModule.java:229) [dot.dwr-3rc2modified_2.jar:?]
    at com.dotcms.repackage.org.directwebremoting.impl.CreatorModule.executeMethod(CreatorModule.java:241) [dot.dwr-3rc2modified_2.jar:?]
    at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:379) [dot.dwr-3rc2modified_2.jar:?]
    at com.dotcms.repackage.org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:332) [dot.dwr-3rc2modified_2.jar:?]
    at com.dotcms.repackage.org.directwebremoting.dwrp.BaseCallHandler.handle(BaseCallHandler.java:104) [dot.dwr-3rc2modified_2.jar:?]
    at com.dotcms.repackage.org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:120) [dot.dwr-3rc2modified_2.jar:?]
    at com.dotcms.repackage.org.directwebremoting.servlet.DwrServlet.doPost(DwrServlet.java:141) [dot.dwr-3rc2modified_2.jar:?]
    at com.dotmarketing.servlets.DwrWrapperServlet.doPost(DwrWrapperServlet.java:60) [dotcms_3.6.0_3876030.jar:?]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:644) [servlet-api.jar:?]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:259) [dotcms_3.6.0_3876030.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61) [dotcms_3.6.0_3876030.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:308) [dotcms_3.6.0_3876030.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:130) [dotcms_3.6.0_3876030.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_3.6.0_3876030.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) [dotcms_3.6.0_3876030.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146) [dotcms_3.6.0_3876030.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
    at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_74]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_74]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
    at com.dotmarketing.business.VersionableAPIImpl.isLocked(VersionableAPIImpl.java:195) ~[dotcms_3.6.0_3876030.jar:?]
    at com.dotmarketing.portlets.contentlet.model.Contentlet.isLocked(Contentlet.java:374) ~[dotcms_3.6.0_3876030.jar:?]
    at com.dotmarketing.portlets.htmlpageasset.model.HTMLPageAsset.getMap(HTMLPageAsset.java:146) ~[dotcms_3.6.0_3876030.jar:?]
    ... 68 more
```

**Comment by joseorsini** [comment]
This is a race condition introduced on this line 

https://github.com/dotCMS/core/blob/master-3.6/src/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L2594 

At this point, and it basically happens only when the Migrate Pages to Content tool is called, it tries to generate a Map of the content to be saved, however, for this scenario, no identifier has been created yet to the new contentlet object, so this call 

https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/portlets/htmlpageasset/model/HTMLPageAsset.java#L146 

will attempt to search the Versionable Id on cache, returning a null.

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9762

**Comment by shaydotcms** [comment]
Passed QA.
Upgraded from 2.5.7 to 3.6 and executed Migrate to Content option. It's working properly on master-3.6 // MySQL 5.6.23, Postgres 9.3.5, Oracle 12c.
No error message in logs.
