### ISSUE TITLE
Adapt tests under tests.com.dotmarketing.portlets.contentlet 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9882]
We need to make the integration tests under this package to run outside the container
## Expected Behavior

All these tests running via right click on the IDE
## Current Behavior

They fail when running outside the test runner servlet
## Possible Solution

Include call to IntegrationTestInitService.getInstance().init();

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/9897

**Comment by agomez-dotcms** [comment]
After merging/testing, the ticket could not be verified because introduced integration-tests are failing when ran from IDE. It looks integration-tests might not be completely setup to work with the new codebase layout:

com.dotmarketing.portlets.contentlet.ajax.ContentletAjaxTest: FAILED
com.dotmarketing.portlets.contentlet.business.HostAPITest: FAILED
com.dotmarketing.portlets.contentlet.business.FileAssetTest: IGNORED

<img width="1102" alt="screen shot 2016-10-28 at 10 28 14 am" src="https://cloud.githubusercontent.com/assets/22307536/19814073/f6af1ce6-9cf9-11e6-95c4-4a5ed59a7bfa.png">

<img width="1100" alt="screen shot 2016-10-28 at 10 31 56 am" src="https://cloud.githubusercontent.com/assets/22307536/19814080/fe26df2c-9cf9-11e6-8901-a507fc464aaa.png">

<img width="1100" alt="screen shot 2016-10-28 at 10 31 10 am" src="https://cloud.githubusercontent.com/assets/22307536/19814086/046827e2-9cfa-11e6-8936-d48050304560.png">

After tests ran, gollowing error stack-trace was recovered from logs:

INFO  2016-10-28 10:31:47,556 [main] com.dotmarketing.util.Config:info(58): Initializing properties reader.
INFO  2016-10-28 10:31:47,557 [main] com.dotmarketing.util.Config:info(58): Loading dotCMS [dotmarketing-config.properties] Properties...
FATAL 2016-10-28 10:31:47,567 [main] com.dotmarketing.util.Config:fatal(156): Exception loading properties for file [dotmarketing-config.properties]
java.io.FileNotFoundException: /Users/anibalgomez/Development/Workspace/dotCMS/work/core/test-resources/it-dotmarketing-config.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_102]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_102]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_102]
	at com.dotmarketing.util.Config.readProperties(Config.java:183) [classes/:?]
	at com.dotmarketing.util.Config.readProperties(Config.java:116) [classes/:?]
	at com.dotmarketing.util.Config._loadProperties(Config.java:96) [classes/:?]
	at com.dotmarketing.util.Config._refreshProperties(Config.java:199) [classes/:?]
	at com.dotmarketing.util.Config.getStringProperty(Config.java:323) [classes/:?]
	at com.dotmarketing.util.ConfigUtils.getDynamicContentPath(ConfigUtils.java:42) [classes/:?]
	at com.dotcms.cluster.business.ServerAPIImpl.readServerId(ServerAPIImpl.java:40) [classes/:?]
	at com.dotcms.enterprise.license.LicenseManager.setupCryptServerId(LicenseManager.java:511) [eelic_clean.jar:?]
	at com.dotcms.enterprise.license.LicenseManager.<init>(LicenseManager.java:57) [eelic_clean.jar:?]
	at com.dotcms.enterprise.license.LicenseManager.getInstance(LicenseManager.java:255) [eelic_clean.jar:?]
	at com.dotcms.enterprise.LicenseUtil.getLevel(LicenseUtil.java:106) [ee_clean.jar:?]
	at com.dotcms.LicenseTestUtil.getLicense(LicenseTestUtil.java:20) [classes/:?]
	at com.dotmarketing.portlets.contentlet.business.HostAPITest.prepare(HostAPITest.java:38) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]

**Comment by agomez-dotcms** [comment]
Please notice the problem reported with the error in the integration-tests is apparently fixed as part of a PR pending to be merged (https://github.com/dotCMS/core/pull/10006)

**Comment by agomez-dotcms** [comment]
After merging PR https://github.com/dotCMS/core/pull/10006, this issue has now Passed QA
