### ISSUE TITLE
Users: Deleting a User does not fix bundles' owner

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9917]
As of 3.6.0, we introduced Deleting users feature, however, in some specific scenarios the tool doesn't seem to replace all info on DB for the user being deleted.
## Expected Behavior

Once we select a User to replace all occurrences in DB of user to be deleted, we should update all these occurrences
## Current Behavior

If a user is the owner of a created bundle, after it's deleted, its information remains in the DB, so once we open an Asset pushed by this user (after it was deleted), the backend throws an error. 
## Possible Solution

Enforce data integrity between user_ table and all other tables that include an owner/mod user column. Make proper cleanup/update in DB during the deletion process
## Known Workarounds

Delete the offending bundles does the trick.
## Steps to Reproduce (for bugs)
1. Create a user (for this test, user is called Jose Orsini and his userId is **dotcms.org.2842**).
2. Assign CMS Administrator role to this new user so he can have access to all backend features.
3. Set up a Push Publishing environment (1 Sender node, 1 Receiver Node) and discard potential issues via Integrity Checker.
4. Push Jose Orsini user to Receiver environment.
5. Login to the backend as Jose Orsini and edit demo.dotcms.com site (add a couple of site aliases and then save/publish it).
6. Add the demo.dotcms.com site to a bundle, called **site-bundle**.
7. Go to Publishing Queue and Force Push this new bundle. 
8. Once the push is done, Log in to the Sender environment as Admin user (dotcms.org.1).
9. Go to Users portlet and delete Jose Orsini user (select Admin User as his replacement).
10. Go to Sites portlet and open demo.dotcms.com site. An error is thrown on backend and logfiles. 
- Bundle definition before user is deleted:

```
# select * from publishing_bundle where name = 'site-bundle';
                  id                  |    name     |    publish_date     | expire_date |      owner      | force_push
--------------------------------------+-------------+---------------------+-------------+-----------------+------------
 72a06944-4913-41e3-9728-d939d614f156 | site-bundle | 2016-10-07 11:02:00 |             | dotcms.org.2842 | f
(1 row)
```
- Bundle definition AFTER user is deleted. "Owner" column should be replaced with "dotcms.org.1" id.

```
# select * from publishing_bundle where name = 'site-bundle';
                  id                  |    name     |    publish_date     | expire_date |      owner      | force_push
--------------------------------------+-------------+---------------------+-------------+-----------------+------------
 72a06944-4913-41e3-9728-d939d614f156 | site-bundle | 2016-10-07 11:02:00 |             | dotcms.org.2842 | f
(1 row)
```
- Publishing_bundle definition on postgres. No FK is enforcing data integrity between owner column and User_ table

```
# \d publishing_bundle;
            Table "public.publishing_bundle"
    Column    |            Type             | Modifiers
--------------+-----------------------------+-----------
 id           | character varying(36)       | not null
 name         | character varying(255)      | not null
 publish_date | timestamp without time zone |
 expire_date  | timestamp without time zone |
 owner        | character varying(100)      |
 force_push   | boolean                     |
Indexes:
    "publishing_bundle_pkey" PRIMARY KEY, btree (id)
Referenced by:
    TABLE "publishing_bundle_environment" CONSTRAINT "fk_bundle_id" FOREIGN KEY (bundle_id) REFERENCES publishing_bundle(id)
```

Logfile

```
[07/10/16 11:08:32:502 EDT] ERROR portlet.PortletRequestDispatcherImpl: org.apache.jasper.JasperException: com.dotmarketing.business.NoSuchUserException: dotcms.org.2842
org.apache.jasper.JasperException: org.apache.jasper.JasperException: com.dotmarketing.business.NoSuchUserException: dotcms.org.2842
    at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:548) ~[jasper.jar:8.0.18]
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:454) ~[jasper.jar:8.0.18]
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) ~[jasper.jar:8.0.18]
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) ~[jasper.jar:8.0.18]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) ~[catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) ~[catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:584) ~[catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:523) ~[catalina.jar:8.0.18]
    at com.liferay.portlet.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:209) [dotcms_3.6.0_0e1bc9e.jar:?]
    at com.liferay.portal.struts.PortletRequestProcessor.doInclude(PortletRequestProcessor.java:344) [dotcms_3.6.0_0e1bc9e.jar:?]
    at com.liferay.portal.struts.PortletRequestProcessor.doForward(PortletRequestProcessor.java:319) [dotcms_3.6.0_0e1bc9e.jar:?]
    at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processTilesDefinition(TilesRequestProcessor.java:237) [dot.struts-1.2.4_2.jar:1.2.4]
    at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processForwardConfig(TilesRequestProcessor.java:300) [dot.struts-1.2.4_2.jar:1.2.4]
    at com.dotcms.repackage.com.oroad.stxx.plugin.StxxTilesRequestProcessor.processForwardConfig(StxxTilesRequestProcessor.java:134) [dot.stxx-1.3_2.jar:?]
    at com.liferay.portal.struts.PortletRequestProcessor.processForwardConfig(PortletRequestProcessor.java:205) [dotcms_3.6.0_0e1bc9e.jar:?]
    at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:231) [dot.struts-1.2.4_2.jar:1.2.4]
    at com.liferay.portal.struts.PortletRequestProcessor.process(PortletRequestProcessor.java:91) [dotcms_3.6.0_0e1bc9e.jar:?]
    at com.liferay.portlet.StrutsPortlet.include(StrutsPortlet.java:148) [dotcms_3.6.0_0e1bc9e.jar:?]
    at com.liferay.portlet.StrutsPortlet.doView(StrutsPortlet.java:100) [dotcms_3.6.0_0e1bc9e.jar:?]
    at com.dotcms.repackage.javax.portlet.GenericPortlet.doDispatch(GenericPortlet.java:235) [dot.portlet-1.0_2.jar:?]
    at com.dotcms.repackage.javax.portlet.GenericPortlet.render(GenericPortlet.java:163) [dot.portlet-1.0_2.jar:?]
    at com.liferay.portlet.CachePortlet.render(CachePortlet.java:159) [dotcms_3.6.0_0e1bc9e.jar:?]
    at org.apache.jsp.html.portal.layout_jsp._jspService(layout_jsp.java:605) [ROOT/:?]
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [jasper.jar:8.0.18]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) [jasper.jar:8.0.18]
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) [jasper.jar:8.0.18]
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) [jasper.jar:8.0.18]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:584) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:523) [catalina.jar:8.0.18]
    at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:934) [jasper.jar:8.0.18]
    at org.apache.jsp.html.portal.layout_005fportal_jsp._jspService(layout_005fportal_jsp.java:2964) [ROOT/:?]
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [jasper.jar:8.0.18]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) [jasper.jar:8.0.18]
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) [jasper.jar:8.0.18]
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) [jasper.jar:8.0.18]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318) [catalina.jar:8.0.18]
    at com.liferay.portal.struts.StrutsUtil.forward(StrutsUtil.java:72) [dotcms_3.6.0_0e1bc9e.jar:?]
    at com.liferay.portal.struts.PortalRequestProcessor.doForward(PortalRequestProcessor.java:174) [dotcms_3.6.0_0e1bc9e.jar:?]
    at com.dotmarketing.struts.PortalRequestProcessor.doForward(PortalRequestProcessor.java:51) [dotcms_3.6.0_0e1bc9e.jar:?]
    at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processTilesDefinition(TilesRequestProcessor.java:237) [dot.struts-1.2.4_2.jar:1.2.4]
    at com.dotcms.repackage.org.apache.struts.tiles.TilesRequestProcessor.processForwardConfig(TilesRequestProcessor.java:300) [dot.struts-1.2.4_2.jar:1.2.4]
    at com.dotcms.repackage.com.oroad.stxx.plugin.StxxTilesRequestProcessor.processForwardConfig(StxxTilesRequestProcessor.java:134) [dot.stxx-1.3_2.jar:?]
    at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:231) [dot.struts-1.2.4_2.jar:1.2.4]
    at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:160) [dotcms_3.6.0_0e1bc9e.jar:?]
    at com.dotcms.repackage.org.apache.struts.action.ActionServlet.process(ActionServlet.java:1164) [dot.struts-1.2.4_2.jar:1.2.4]
    at com.dotcms.repackage.org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:397) [dot.struts-1.2.4_2.jar:1.2.4]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:618) [servlet-api.jar:?]
    at com.liferay.portal.servlet.MainServlet.callParentService(MainServlet.java:277) [dotcms_3.6.0_0e1bc9e.jar:?]
    at com.liferay.portal.servlet.MainServlet.service(MainServlet.java:506) [dotcms_3.6.0_0e1bc9e.jar:?]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotcms.repackage.com.liferay.filters.secure.SecureFilter.doFilter(SecureFilter.java:135) [dot.secure-filter-ukv_2.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:259) [dotcms_3.6.0_0e1bc9e.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.AutoLoginFilter.doFilter(AutoLoginFilter.java:61) [dotcms_3.6.0_0e1bc9e.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:308) [dotcms_3.6.0_0e1bc9e.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
    at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
    at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
    at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:130) [dotcms_3.6.0_0e1bc9e.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_3.6.0_0e1bc9e.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33) [dotcms_3.6.0_0e1bc9e.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146) [dotcms_3.6.0_0e1bc9e.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
    at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: org.apache.jasper.JasperException: com.dotmarketing.business.NoSuchUserException: dotcms.org.2842
    at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:548) ~[jasper.jar:8.0.18]
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:469) ~[jasper.jar:8.0.18]
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) ~[jasper.jar:8.0.18]
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) ~[jasper.jar:8.0.18]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) ~[catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) ~[catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:584) ~[catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:523) ~[catalina.jar:8.0.18]
    at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:934) ~[jasper.jar:8.0.18]
    at org.apache.jsp.html.portal.layout_005fportal_jsp._jspService(layout_005fportal_jsp.java:636) ~[?:?]
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:8.0.18]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) ~[jasper.jar:8.0.18]
    ... 117 more
Caused by: com.dotmarketing.business.NoSuchUserException: dotcms.org.2842
    at com.dotmarketing.business.UserFactoryLiferayImpl.loadUserById(UserFactoryLiferayImpl.java:145) ~[dotcms_3.6.0_0e1bc9e.jar:?]
    at com.dotmarketing.business.UserAPIImpl.loadUserById(UserAPIImpl.java:84) ~[dotcms_3.6.0_0e1bc9e.jar:?]
    at org.apache.jsp.html.portlet.ext.contentlet.edit_005fcontentlet_jsp._jspService(edit_005fcontentlet_jsp.java:5339) ~[?:?]
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:8.0.18]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) ~[jasper.jar:8.0.18]
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) ~[jasper.jar:8.0.18]
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) ~[jasper.jar:8.0.18]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) ~[catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) ~[catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:584) ~[catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:523) ~[catalina.jar:8.0.18]
    at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:934) ~[jasper.jar:8.0.18]
    at org.apache.jsp.html.portal.layout_005fportal_jsp._jspService(layout_005fportal_jsp.java:636) ~[?:?]
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:8.0.18]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) ~[jasper.jar:8.0.18]
    ... 117 more
Caused by: com.liferay.portal.NoSuchUserException: dotcms.org.2842
    at com.liferay.portal.ejb.UserPersistence.findByPrimaryKey(UserPersistence.java:246) ~[dotcms_3.6.0_0e1bc9e.jar:?]
    at com.liferay.portal.ejb.UserUtil.findByPrimaryKey(UserUtil.java:128) ~[dotcms_3.6.0_0e1bc9e.jar:?]
    at com.liferay.portal.ejb.UserLocalManagerImpl.getUserById(UserLocalManagerImpl.java:357) ~[dotcms_3.6.0_0e1bc9e.jar:?]
    at com.liferay.portal.ejb.UserLocalManagerUtil.getUserById(UserLocalManagerUtil.java:145) ~[dotcms_3.6.0_0e1bc9e.jar:?]
    at com.dotmarketing.business.UserFactoryLiferayImpl.loadUserById(UserFactoryLiferayImpl.java:143) ~[dotcms_3.6.0_0e1bc9e.jar:?]
    at com.dotmarketing.business.UserAPIImpl.loadUserById(UserAPIImpl.java:84) ~[dotcms_3.6.0_0e1bc9e.jar:?]
    at org.apache.jsp.html.portlet.ext.contentlet.edit_005fcontentlet_jsp._jspService(edit_005fcontentlet_jsp.java:5339) ~[?:?]
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:8.0.18]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) ~[jasper.jar:8.0.18]
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) ~[jasper.jar:8.0.18]
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) ~[jasper.jar:8.0.18]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) ~[catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721) ~[catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:584) ~[catalina.jar:8.0.18]
    at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:523) ~[catalina.jar:8.0.18]
    at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:934) ~[jasper.jar:8.0.18]
    at org.apache.jsp.html.portal.layout_005fportal_jsp._jspService(layout_005fportal_jsp.java:636) ~[?:?]
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:8.0.18]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[servlet-api.jar:?]
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:431) ~[jasper.jar:8.0.18]
    ... 117 more
```

Screenshot of Backend after user is deleted:
<img width="1337" alt="screen shot 2016-10-07 at 11 20 44 am" src="https://cloud.githubusercontent.com/assets/1717110/19195576/2653ff96-8c80-11e6-9bc9-552ebf04dc1a.png">
## Context

Reproduced on local 3.6.0 environment.
Reproduced on cloud customer. Support Ticket: https://my.dotcms.com/tickets/detail.dot?id=76a2f1a4-b012-4380-9e0a-a52509fde636
## Your Environment

- dotCMS 3.6.0.
- Google Chrome Browser.
- macOS Sierra 10.12.
- Java 8.
- Postgres 9.4.1.

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9951

**Comment by shaydotcms** [comment]
Passed QA.
Bundle owner is reassigned properly to selected user. No error message in logs

Once we select a User to replace all occurrences in DB of user to be deleted, we should update all these occurrences

Current Behavior

If a user is the owner of a created bundle, after it's deleted, its information remains in the DB, so once we open an Asset pushed by this user (after it was deleted), the backend throws an error.
Tested on:
dotCMS 3.6.0.
Google Chrome Browser.
macOS Sierra 10.12.
Java 8.
Postgres 9.4.1.
