### ISSUE TITLE
Auomated tests for ES Snapshot functionality

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#9921]
Related to #9127 

Integration and Unit tests where applicable. 

Please involve @shaydotcms for test cases.

**Comment by maurizo** [comment]
PR: https://github.com/dotCMS/core/pull/9955
PR EE: https://github.com/dotCMS/enterprise-2.x/pull/390

**Comment by agomez-dotcms** [comment]
After merging/testing, the ticket could not be completely verified because introduced integration-tests are failing when ran from IDE. It looks integration-tests might not be completely setup to work with the new codebase layout:

**com.dotcms.content.elasticsearch.business.ESIndexHelperTest**: PASSED
**com.dotcms.rest.api.v1.index.ESIndexResourceTest**: PASSED
**com.dotcms.content.elasticsearch.business.ESIndexAPITest**: PASSED

<img width="1094" alt="screen shot 2016-10-28 at 10 12 39 am" src="https://cloud.githubusercontent.com/assets/22307536/19813641/e3692e80-9cf7-11e6-9bcc-f1ae2411be75.png">

<img width="1101" alt="screen shot 2016-10-28 at 10 12 04 am" src="https://cloud.githubusercontent.com/assets/22307536/19813665/f7c44310-9cf7-11e6-8bcb-2646e85f84c8.png">

<img width="1104" alt="screen shot 2016-10-28 at 10 11 34 am" src="https://cloud.githubusercontent.com/assets/22307536/19813677/062bac4a-9cf8-11e6-925b-c508aa1a5d9c.png">

After tests ran, gollowing error stack-trace was recovered from logs:

INFO  2016-10-28 10:19:57,121 [main] com.dotmarketing.util.Config:info(58): Initializing properties reader.
INFO  2016-10-28 10:19:57,122 [main] com.dotmarketing.util.Config:info(58): Loading dotCMS [dotmarketing-config.properties] Properties...
FATAL 2016-10-28 10:19:57,130 [main] com.dotmarketing.util.Config:fatal(156): Exception loading properties for file [dotmarketing-config.properties]
java.io.FileNotFoundException: /Users/anibalgomez/Development/Workspace/dotCMS/work/core/test-resources/it-dotmarketing-config.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_102]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_102]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_102]
	at com.dotmarketing.util.Config.readProperties(Config.java:183) [classes/:?]
	at com.dotmarketing.util.Config.readProperties(Config.java:116) [classes/:?]
	at com.dotmarketing.util.Config._loadProperties(Config.java:96) [classes/:?]
	at com.dotmarketing.util.Config._refreshProperties(Config.java:199) [classes/:?]
	at com.dotmarketing.util.Config.getStringProperty(Config.java:223) [classes/:?]
	at com.dotmarketing.util.Config.getStringProperty(Config.java:210) [classes/:?]
	at com.dotcms.content.elasticsearch.business.ESIndexAPITest.prepare(ESIndexAPITest.java:43) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]

**Comment by agomez-dotcms** [comment]
Please notice the problem reported with the error in the integration-tests is apparently fixed as part of a PR pending to be merged (https://github.com/dotCMS/core/pull/10006)

**Comment by agomez-dotcms** [comment]
After merging PR https://github.com/dotCMS/core/pull/10006, this issue has now Passed QA
